### ISSUE TITLE
Modify Keptn installation so Keptn Quality Gates works standalone

### ISSUE THREAD

**Issue by dirkwall** [keptn/keptn#1013]
- remove Distributor of GateKeeper Service so the workflow is stopped

**Comment by agrimmer** [comment]
How should we implement this? I can think of for possible options:
- `keptn install --quality-gates-only`
- `kubectl delete deployment gatekeeper-service-evaluation-done-distributor -n keptn`
- `keptn configure core --disable-promotion`
- Extend shipyard with `promotion_strategy` [automatic=default, manual, none]

Can you please post your preferred option?

**Comment by johannes-b** [comment]
Extending the shipyard with the `promotion_strategy` is the option that best follows the Keptn-approach of explicitly describing the configuration and expected workflow behavior.

**Comment by dirkwall** [comment]
Please create a PR to keptn/spec repository for that. Let's discuss it in the next spec meeting on Nov 11.

**Comment by grabnerandi** [comment]
My proposed solution is that as a user I can simply say "keptn install capabilities=qualitygates"
This should install keptn and ONLY those components that are needed for that capability. That also implies for "quality gates only" that we DO NOT install istio or any other things not necessary. REmember - right now users want quality gates but they have an issue with us always installing Istio!

If we do it like "keptn install capabilities=X,Y,Z" then this is a nice extensible model where as a user I can decide which capabilites I want right now and at a later time may add capabilities, e.g: self-healing ...

**Comment by dirkwall** [comment]
@grabnerandi agreed. We need to discuss that in the context of having a standalone control plane, that aligns with the capabilities you've mentioned.

**Comment by agrimmer** [comment]
We extended the install command of the CLI with the flag `--use-case=quality-gates`. 
This flag allows to install a Keptn version, which is dedicated to the quality gates use case. For example, the quality gates use case does not require Istio and, hence, it is not installed. Instead, we are using `nginx` for the Ingress.
