### ISSUE TITLE
Dynatrace Integration: Add tagging rules and host detection rules for frontend applications (Real User Monitoring)

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1024]
Also paging @grabnerandi on this issue as he provided valueable input for debugging this.

**Environment**

* Keptn Version (`keptn version`): 0.5
* Kubernetes Cloud Provider (e.g., GKE, AKS): GKE

**Affected Component**

* [x] Docs
* [ ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [ ] Bridge
* [ ] Gatekeeper
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter
* [x] Dynatrace Integration

**Describe the bug**

When adding the Dynatrace OneAgent the documentation executes certain scripts to automatically add tags to the services (e.g., `service: sockshop`, `stage: sockshop-dev`). 
This not only helps separating services from each other for monitoring within Dynatrace, but also provides certain metrics for Loadtests  (e.g., `test-subject: true`).

However, this is not true for "applications" (e.g., a Web Frontend where the JavaScript Agent is injected). Here all services get aggregated into one application (usually the default application):

![Screenshot from 2019-10-30 12-40-36](https://user-images.githubusercontent.com/56065213/67855356-a0f67400-fb12-11e9-8689-4f603129719d.png)
![Screenshot from 2019-10-30 12-40-43](https://user-images.githubusercontent.com/56065213/67855355-a05ddd80-fb12-11e9-9e81-4c45b7d90c4d.png)

**To Reproduce**

Add Dynatrace OneAgent, open the frontend for all 3 stages, and observe the behaviour within Dynatrace

**Expected behavior**
There should be three separate apps (+ the default app), e.g.:

![Screenshot from 2019-10-30 12-42-59](https://user-images.githubusercontent.com/56065213/67855529-e3b84c00-fb12-11e9-964a-a7780fc88842.png)

In addition, I believe that the same auto-tagging rules as for services should be applied:
![Screenshot from 2019-10-30 12-46-05](https://user-images.githubusercontent.com/56065213/67855719-427dc580-fb13-11e9-985b-077249c4c0b0.png)

**Current behavior**
At the moment all user actions are aggregated in the default application.

**Possible Fix**
In Dynatrace, go to Settings, Web & mobile monitoring, and select "Application detection & RUM". Then click on "Create application detection rule" and create rules like this:
* Application: Sockshop Dev
* Rule: If the domain (host) contains "sockshop-dev"

**Comment by christian-kreuzberger-dtx** [comment]
We can currently not accept the implementation as it requires us to store way too many default flags within our dynatrace-service. This will cause issues in the future (incompatibilities, invalid values, etc...), and we believe that those flags should be handled by Dynatrace.

**Comment by johannes-b** [comment]
When this feature will be further developed, please take into account to update the documentation of the Dynatrace API token (https://keptn.sh/docs/0.6.0/reference/monitoring/dynatrace/#setup-dynatrace). Enable: **Real user monitoring JavaScript tag management**.

**Comment by agrimmer** [comment]
Moved this issue to https://github.com/keptn-contrib/dynatrace-service/issues/154
