### ISSUE TITLE
Keptn 0.5.0 install for eks fails 

### ISSUE THREAD

**Issue by robertjahn** [keptn/keptn#1028]
**Environment**
* Client OS (e.g., Linux, OSX, Windows):  Linux 
* Keptn Version (`keptn version`): 0.5.0
* Kubernetes Cloud Provider (e.g., GKE, AKS): EKS 1.14 
* Kubernetes version (`kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-eks-5876d6", GitCommit:"5876d6b7429820450950ade17fe7b4bf5ccada7f", GitTreeState:"clean", BuildDate:"2019-09-24T20:54:25Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```

**Affected Component**

* [ ] Docs
* [X] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [ ] Bridge
* [ ] Gatekeeper
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**
Receive this error and the installation cannot proceed
```
root@012ef06e4347:/usr/keptn/scripts/provision-cluster# keptn install -p eks
Installing keptn...
Please enter the following information or press enter to keep the old value:
Cluster Name []: jahn-keptn-workshop-cluster
AWS Region []: us-west-2
Could not connect to cluster. Please verify that you have entered the correct information. Error: Error executing command aws eks --region us-west-2 update-kubeconfig --name jahn-keptn-workshop-cluster: exec: "aws": executable file not found in $PATH
```

**To Reproduce**
See above

**Expected behavior**

**Current behavior**

**Screenshots**

**Additional context**
If run the install with the p=kubernetes, keptn does install but gets an 'Authentication was unsuccessful' message at the end.  This Authentication is due to the route53 ELB not yet being setup just yet.  Might be nice to have a extra message to indicate what to check like 'Authentication was unsuccessful - verify domain setup'

```
root@012ef06e4347:/usr/keptn/scripts/provision-cluster# keptn install -p kubernetes
Installing keptn...
Please enter the following information or press enter to keep the old value:

Please confirm that the provided information is correct: 
Cluster: rob.jahn@dynatrace.com@jahn-keptn-workshop-cluster.us-west-2.eksctl.io

Is this all correct? (y/n)
y
Using a file-based storage for the key because the password-store seems to be not set up.
Deploying keptn installer pod...
Installer pod deployed successfully.
Getting logs of pod installer-sn5vg
Starting installation of Keptn
Testing connection to Kubernetes API
Connection to Kubernetes API successful
Installing Istio
Installing Istio done
Installing Tiller
Installing Tiller done
Installing Keptn
Installing Logging
Installing Keptn done
Wear uniform
Keptn wears uniform
Installation of Keptn complete.
Starting to authenticate
Authentication was unsuccessful
```

**Comment by grabnerandi** [comment]
FYI - I ran into the same issue. Seems the keptn CLI either doesnt find the installed aws cli or it is calling it wrong.
In my case - just as for Rob - I already had kubectl configured for my eks cluster. So I also went ahead and used the --platform=kubernetes install option which worked fine

**Comment by robertjahn** [comment]
Note: both Ansi and I were running the Keptn CLI within this docker container that is built with the required CLI and other tooling.  https://github.com/keptn-workshops/workshop-utils
Here is versions from within that.
```
root@012ef06e4347:/usr/keptn/examples/onboarding-carts# aws --version
aws-cli/1.16.270 Python/3.6.8 Linux/4.9.184-linuxkit botocore/1.13.6

root@012ef06e4347:/usr/keptn/examples/onboarding-carts# keptn version
CLI version: 0.5.0
```

**Comment by christian-kreuzberger-dtx** [comment]
I just tried this Dockerfile and I was able to reproduce the issue. The `aws` command is accessible via the command line, but it is not when `keptn` calls it with
```go
func (p eksPlatform) authenticateAtCluster() (bool, error) {
	_, err := keptnutils.ExecuteCommand("aws", []string{
		"eks",
		"--region",
		p.creds.AwsRegion,
		"update-kubeconfig",
		"--name",
		p.creds.ClusterName,
	})

	if err != nil {
		fmt.Println("Could not connect to cluster. " +
			"Please verify that you have entered the correct information. Error: " + err.Error())
		return false, err
	}

	return true, nil
}
```

I believe that the issue however lies within the Dockerfile, not within Keptn. AWS CLI is installed using pip using the following lines:
```

# install pip
RUN curl -O https://bootstrap.pypa.io/get-pip.py
RUN python3 get-pip.py --user
ENV PATH ~/.local/bin:$PATH

## AWS CLI
RUN ~/.local/bin/pip3 install awscli --upgrade --user
RUN rm get-pip.py
```

The PATH variable seems to be the issue here. Following the tutorial on https://docs.aws.amazon.com/cli/latest/userguide/install-linux-al2017.html the PATH variable should not contain a `~` but an absolute path, in our case `/root/.local/bin`.

Changing this in the Dockerfile makes everything work :) I've created a PR for this in your repo: https://github.com/keptn-workshops/workshop-utils/pull/4
