### ISSUE TITLE
Wrong image version referenced in dynatrace-service setup scripts

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#1065]
See thread conversation here for more background: https://keptn.slack.com/archives/CHTQV79FT/p1572951286001200

But - dynatrace-service.yaml file in master and also in the latest releases points to the 0.2 version and not the actual last version, e.g: 3.1: the https://github.com/keptn-contrib/dynatrace-service/blob/release-0.3.1/deploy/manifests/dynatrace-service/dynatrace-service.yaml

This means our users are loading an older version of this keptn service

**Comment by bacherfl** [comment]
Since v 0.2.0 of the dynatrace service only the installation scripts have changed, while the image itself has been left untouched. That’s why in the manifest it still references 0.2.0

**Comment by grabnerandi** [comment]
Thanks Florian. I guess I was then just confused by our version matrix that is listed here: https://github.com/keptn/keptn - It says that these are the versions of the container images and it lists dynatrace-service0.3.1 for keptn 0.5.x. Maybe we can fix this in the readme?

**Comment by bacherfl** [comment]
the readme is now up to date
