### ISSUE TITLE
Dynatrace service tags unrelated services

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#1077]
The automated tagging rules set up by the Dynatrace service tag unrelated services that are not being deployed by Keptn, as you can see in the screenshot

![image](https://user-images.githubusercontent.com/7677092/68429705-76846680-0163-11ea-80c6-6fc0407c01a5.png)

The service in the image has the tag "test-subject:true" but is not related to any tests performed by Keptn.

Desired state:
Tag only services that have been deployed by Keptn.

**Comment by christian-kreuzberger-dtx** [comment]
Thanks for the hint. Right now the auto-tagging works using the kubernetes pod name and namespace name (which can obviously lead to false-positives, as you demonstrated). 
This is something we are planning to improve on based on Issue #1025, as detailed by @grabnerandi by using `DT_CUSTOM_PROP`.

**Comment by dirkwall** [comment]
This is not a Keptn issue. Please track this here: https://github.com/keptn-contrib/dynatrace-service
