### ISSUE TITLE
JMeter/Wait-service needs to send Test-finished event with start/end time rather than startedat

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1078]
Right now jmeter-service sends a test-finished event which is manually constructed using a string map.

Task: Change jmeter-service such that the test-finished event from keptn/go-utils is used

**Comment by johannes-b** [comment]
Hi Christian, 
the same change is necessary for the wait-service I figured out today. Please see: https://github.com/keptn/keptn/blob/develop/wait-service/main.go#L192

Can you address this change?

**Comment by christian-kreuzberger-dtx** [comment]
Will do.

**Comment by christian-kreuzberger-dtx** [comment]
We have a similar problem in wait-service for deployment finished that we need to tackle later: https://github.com/keptn/keptn/blob/9de712adb3c5a27c521e01dbd756952585bed41c/wait-service/main.go#L34-L39
