### ISSUE TITLE
Adapt DT integration to create rules based on DT_CUSTOM_PROP

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#1110]
Currently, DT rules are created based on DT_TAGS. They have to be changed to use DT_CUSTOM_PROP instead.

**Comment by agrimmer** [comment]
I completed changing the `applyAutoTaggingRules`-script to use custom properties.
Next, the dynatrace-service itself needs to be adapted to use `DT_CUSTOM_PROP`. Furthermore, changes in the `remediation-service` will be necessary as this service uses the DT tags to derive the project, service, and stage information.
