### ISSUE TITLE
Cleanup: "keptn delete project" does not delete helm release

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1120]
When creating a new project, onboarding a new project, sending new artifacts etc..., and then deleting the project, e.g., using
```console
keptn delete project sockshop
```
it is no longer possible to create and use a project with the same name (it says the namespace is already taken).

I've already deleted the kubernetes namespaces using `kubectl delete namespace sockshop-dev` (and `-staging` and `-production`), but I believe there is also the helm deployments which would have to be manually deleted:

```console
helm delete --purge sockshop-dev-carts
helm delete --purge sockshop-dev-carts-db
helm delete --purge sockshop-dev-carts-db-generated
helm delete --purge sockshop-dev-carts-generated
helm delete --purge sockshop-dev

helm delete --purge sockshop-staging-carts
helm delete --purge sockshop-staging-carts-db
helm delete --purge sockshop-staging-carts-db-generated
helm delete --purge sockshop-staging-carts-generated
helm delete --purge sockshop-staging

helm delete --purge sockshop-production-carts
helm delete --purge sockshop-production-carts-db
helm delete --purge sockshop-production-carts-db-generated
helm delete --purge sockshop-production-carts-generated
helm delete --purge sockshop-production
```

even quicker would be this (but this could lead to unwated consequences):
```console
helm delete --purge $(helm ls | grep sockshop | cut -f1 | tr '\n' ' ')
```

The result can be verified by using
```console
helm list
```

**Solution**: We either implement the proper delete logic using helm, or we document this as necessary steps for cleaning up.

**Comment by agrimmer** [comment]
It is intended to not delete the namespaces or helm-releases when we delete the keptn project. But I already added a check, if the namespaces are available:
https://github.com/keptn/keptn/blob/3fe80ba2dd9e33cd9d4e024481989b1218a96f7a/shipyard-service/main.go#L211
If not, the error messages describe how to delete the namespace and the helm releases.
