### ISSUE TITLE
Keptn update domain uses wrong URL for authenticate

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#1121]
I am testing the current keptn develop to validate 0.6beta.
when doing a keptn update domain mydomain.abc.com the CLI seems to update the config mags but then does a keptn auth without prepending api.keptn to the domain name

here is an example output
$ keptn06 configure domain keptn-temp.lab.mydomain.org
Starting to configure domain
Starting to authenticate
Authentication was unsuccessful. Post https://keptn-temp.lab.mydomain.org/v1/auth: dial tcp 10.102.xx.yy:443: connect: connection refused

In our authenticate instructions on the website we always prepend the domain with api.keptn - I assume this is also necessary here

**Comment by agrimmer** [comment]
The prefix `api.keptn` should not be needed as we are setting the Host in the headers anyway.

**Comment by agrimmer** [comment]
We have to revert this change otherwise we cannot use `NodePort` anymore. More precisely, this change results in an invalid URL, e.g., `https://api.keptn.x.x.x.x:30564/v1/auth`.
