### ISSUE TITLE
keptn start evaluate generates timestamp in the future when no starttime is given

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#1138]
this is for 0.6b

I executed
```
~/keptn send event start-evaluation --project=sample --service=sampleservice --stage=hardening --timeframe=5m
```

The Dynatrace SLI service runs into errors as the generated timestamp seems to be in the future. Here is the error message when I execute the query I see in the dynatrace-sli logs manually
```
{
  "error": {
    "code": 400,
    "message": "Constraints violated.",
    "constraintViolations": [
      {
        "path": null,
        "message": "The start timestamp resides in the future.",
        "parameterLocation": null,
        "location": null
      }
    ]
  }
}
```

I assume the problem is timezone related. When you use NOW make sure to convert it to the correct timezone that the Dynatrace API expects

**Comment by christian-kreuzberger-dtx** [comment]
> I assume the problem is timezone related. When you use NOW make sure to convert it to the correct timezone that the Dynatrace API expects

Yep, that's exactly the problem.
