### ISSUE TITLE
Extend all CloudEvents and CLI send-event commands with optional labels

### ISSUE THREAD

**Issue by dirkwall** [keptn/keptn#1149]
Implementation of this [keptn/spec PR](https://github.com/keptn/spec/pull/10).

Extension of the `start-evaluation` event with labels that allow users to provide labels for evaluations.

**Comment by christian-kreuzberger-dtx** [comment]
This feature requires workflow-engine/shipyard-controller.

**Comment by christian-kreuzberger-dtx** [comment]
This issue is still work in progress, I'm labelling this as "future".

**Comment by christian-kreuzberger-dtx** [comment]
@johannes-b Do all our cloud-events have labels now? I thought they did, though wanted to check back with you.

**Comment by johannes-b** [comment]
In the course of implementing [KEP 06](https://github.com/keptn/enhancement-proposals/pull/6), this need to be verified.

**Comment by johannes-b** [comment]
I close this issue in favor of #2126
