### ISSUE TITLE
Get evaluation result by provided labels

### ISSUE THREAD

**Issue by dirkwall** [keptn/keptn#1151]
In #1149, the start-evaluation event is extended with labels. In #1150, the provided labels are stored with each evaluation result in the data store.

```console
keptn get event evaluation-done --labels build-id=1234
```

In addition to that, the user should be able to retrieve an evaluation result by providing labels for querying.

**Comment by christian-kreuzberger-dtx** [comment]
Just tested this: currently the sli provider do not return "labels" within the get-sli.done cloudevent:

![Screenshot from 2020-02-12 13-28-26](https://user-images.githubusercontent.com/56065213/74335047-9303f080-4d9b-11ea-805b-0b86dcb5582e.png)

Therefore, right now it makes to sense to implement this.

**Comment by christian-kreuzberger-dtx** [comment]
This feature requires #1149 to be implemented. In addition, we should formulate a user story.

**Comment by christian-kreuzberger-dtx** [comment]
@johannes-b is this still relevant?
