### ISSUE TITLE
API: Expose Keptn Bridge via Istio Ingress Gateway OR nginx ingress depending on what is available

### ISSUE THREAD

**Issue by dirkwall** [keptn/keptn#1153]
It should be possible to expose the should on a public endpoint, e.g. `bridge.keptn.<domain>`, if the user wants to do that.
~This should be configurable in the installation process.~
This should be configurable at run time, e.g. using the CLI.

**Comment by christian-kreuzberger-dtx** [comment]
`keptn expose bridge` should expose the bridge and print credentials (e.g., admin, password, URL)

**Comment by grabnerandi** [comment]
Hi
I think its very important that we make it as easy as possible for users to access the bridge as the bridge is the "official face" and interface to Keptn. The current primary use case of Quality Gates also only makes sense if the users can access the bridge.
As I start I think it would be sufficient if we simply prompt the user for a secret that we auto-generate during installation. This is similar to what Argo or Jenkins are doing. We could either create a random key and print it out at the end of keptn install. When running on k8s this key could be the name of the pod that the bridge uses. When not running on k8s it can be a random generated string/key.
I suggest that our bridge prompts the user for this UI secret and if correct - sets a cookie that tells us that the user is authorized.
This would be a fast and easy way to prevent access to everyone in case the bridge is exposed to the public. As the project matures I agree we need to find more sophisticated options of authentication but at this time I think we are good with this approach

Andi

**Comment by checkelmann** [comment]
Hi, 

we need at least a basic auth for the bridge within our Environment. A pre generated user/password would do the job. Or a command line parameter on keptn install. 

> Hi
> I think its very important that we make it as easy as possible for users to access the bridge as the bridge is the "official face" and interface to Keptn. The current primary use case of Quality Gates also only makes sense if the users can access the bridge.
> As I start I think it would be sufficient if we simply prompt the user for a secret that we auto-generate during installation. This is similar to what Argo or Jenkins are doing. We could either create a random key and print it out at the end of keptn install. When running on k8s this key could be the name of the pod that the bridge uses. When not running on k8s it can be a random generated string/key.
> I suggest that our bridge prompts the user for this UI secret and if correct - sets a cookie that tells us that the user is authorized.
> This would be a fast and easy way to prevent access to everyone in case the bridge is exposed to the public. As the project matures I agree we need to find more sophisticated options of authentication but at this time I think we are good with this approach
> 
> Andi

**Comment by robertjahn** [comment]
I think this is an important feature too.  In one of my examples, I had made this script to put in a proxy with basic auth if you want to check that out for an idea.  https://github.com/keptn-orders/keptn-orders-setup/blob/master/8-setupBridgeProxy.sh

**Comment by akirasoft** [comment]
I concur. Simple auth would be a great first start and allow Bridge to be exposed by default. perhaps jwt auth via istio would be worth looking into as well?

**Comment by avodaqstephan** [comment]
> I think this is an important feature too. In one of my examples, I had made this script to put in a proxy with basic auth if you want to check that out for an idea. https://github.com/keptn-orders/keptn-orders-setup/blob/master/8-setupBridgeProxy.sh

That looks pretty good. Will try it this week.

**Comment by jetzlstorfer** [comment]
Absolutely agree. Everytime I see a Keptn installation one would expose the Bridge to see what is going on inside Keptn. A public accessible Bridge with a simple auth mechanism would be very helpful.
