### ISSUE TITLE
keptn_deployment needs to be available in Lighthouse and SLI services (dynatrace, prometheus)

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#1161]
When using a direct deployment strategy the Helm Service uses "Direct" for .Values.keptn.deployment and for blue green we get Canary or Primary.
The Dynatrace SLI service however seems to have a limitation and cant get the same deployment values which leads to problems as we cant define SLI queries that pull out the correct Dynatrace Entities based on the deployment type. This breaks the quality gate use case for Dynatrace right now

**Comment by christian-kreuzberger-dtx** [comment]
In Lighthouse Service:

```
if deployment_strategy == 'blue_green' {
    if test_strategy == 'real-user' { // e.g., remmediation use case -> wait-service
        deployment = 'primary'
    } else {
         deployment = 'canary'
    }
} else {
    // assert deployment_strategy == 'direct'
    deployment = 'direct'
}
```

In SLI Provider: use `$DEPLOYMENT`
