### ISSUE TITLE
Update CloudEvents Spec to 1.0

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#1178]
Currently, we are using CloudEvents in version 0.2. Since Oct, 24th there is a 1.0 spec (https://github.com/cloudevents/spec/tree/v1.0) available. 

**Task:**
- Update of all Keptn CloudEvent specs to use this stable version
- Update of the structs in go-utils to reference the new CloudEvent package

**Definition of Done:**
- [ ] CloudEvents 1.0 is used in Keptn core

**Comment by christian-kreuzberger-dtx** [comment]
Do we need to change any of our implementation for this?

**Comment by christian-kreuzberger-dtx** [comment]
Moved to 0.7.0 as this would cause a change within our spec.

**Comment by agrimmer** [comment]
Closing because it is a duplicate to #2254
