### ISSUE TITLE
Document how to run Keptn on MicroKube (in a VM)

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1186]
Keptn needs to run in a VM, at least in a minimum use-case (e.g., quality-gates standalone with nginx as an ingress).

The bigger picture for this is that we separate control-plane from actual deployments.

We aim to support at least one of the following:

- MicroKube
- MiniKube
- K3S
- something similar

This task requires changes in:

- [x] Installer and configurations applied
- [x] Documentation
- [x] Shell Script for automatic installation (microkube + keptn)

**Comment by bacherfl** [comment]
With Keptn 0.6.0, we have just tested the quality-gates standalone installation on microk8s with the help of the following tutorial: https://tutorials.ubuntu.com/tutorial/install-microk8s-on-mac-os

```
multipass launch --name microk8s-vm --mem 8G --disk 40G --cpus 2
multipass exec microk8s-vm -- sudo snap install microk8s --classic
multipass exec microk8s-vm -- sudo iptables -P FORWARD ACCEPT
multipass exec microk8s-vm -- sudo microk8s.enable dns
multipass exec microk8s-vm -- sudo microk8s.enable dns ingress
multipass exec microk8s-vm -- sudo microk8s.enable storage
# multipass exec microk8s-vm -- sudo microk8s.enable istio
multipass exec microk8s-vm -- sudo /snap/bin/microk8s.config > kubeconfig

export KUBECONFIG=./kubeconfig
kubectl apply -f https://raw.githubusercontent.com/google/metallb/v0.8.3/manifests/metallb.yaml
multipass exec microk8s-vm -- sudo ifconfig

keptn install --platform=kubernetes --keptn-installer-image=keptn/installer:0.6.0 --use-case=quality-gates --gateway=NodePort
```

NOTE: These instructions are specific for macOS. On Ubuntu, the setup should be easier because microk8s can be run directly without multipass
