### ISSUE TITLE
Keptn CLI: Check if a new CLI version is available once a day (with opt out)

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1190]
The Keptn CLI should check if a new CLI version is available once per day, e.g., by fetching the latest CLI version from `get.keptn.sh/version`, and notify the user about the new version.

Something similar to `minikube` could work:

```console
$> minikube start
🎉  minikube 1.5.2 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v1.5.2
💡  To disable this notice, run: 'minikube config set WantUpdateNotification false'

```

## Definition of Done

Whenever the keptn cli is executed, we need to check if we already performed a version-check **today** (or within the last **24h**), e.g.:

```console
$> keptn send event ...
Note: A new version of the CLI (0.6.1) is available. Please visit https://keptn.sh for more information. You can disable automatic version checks with keptn config set AutomaticVersionCheck false
```

This functionality should be automatically active, but it should be be possible to turn it off, e.g., by executing `keptn config set AutomaticVersionCheck false` (if you have a better name recommendation for this flag in the CLI, feel free).

In addition, when calling `keptn version` it should show the current version, and, if an update is available, it should display that information, e.g.:

```console
$> keptn version
CLI version: 0.5.1 (Update available: 0.5.2)
```

Please note: It might be possible that the user does not have a working Internet connection (e.g., firewall restrictions, being offline on purpose, etc...). If there is no connection, the user should only see a warning, e.g.:

```console
$> keptn send event ...
Note: Could not fetch latest version information. You can disable automatic version checks with keptn --automatic-version-check=disable
```

**Please note**: Semantic versioning is used, therefore:

* 0.5.2 is newer than 0.5.1
* 0.6.x is newer than 0.5.x
* 0.6.0.beta is newer than 0.5.x
* 0.6.0 is newer than 0.6.0.beta
* 0.6.0.beta2 is newer than 0.6.0.beta

## Actions

For this to work, we need the following changes:

- [x] Add a file at `get.keptn.sh` with the current stable CLI version (e.g., 0.5.2, but feel free to use JSON, e.g. `{"cli": {"stable": "0.5.2", "latest": "0.6.0.beta"}}`) - see ```curl -sL https://get.keptn.sh/version.json```
- [x] CLI needs to know its current version (probably already does, see `keptn version`)
- [x] Adapt the CLI to fetch the version file from `get.keptn.sh` and to compare the version fetched with the local version (note: do not send the local version to `get.keptn.sh`)
- [x] Store a flag in the CLI configuration that enables/disables this automatic check
- [x] Store the last execution timestamp of the check in CLI configuration (do not check more than once within 24 hours)

## Data Protection and GDPR considerations

To avoid issues and letting the user click "okay" on a privacy agreement (we all love those on websites), we require this functionality

* to use a secure connection (https),
* to not send any user- or host-specific data (e.g., username, hostname, API url, kubernetes host, etc...),
* to not send any secret tokens (e.g., keptn api token, kubernetes access tokens),
* to allow to be disabled (opt-out).

**Comment by agrimmer** [comment]
We cannot use semantic versioning considering the CLI only:
Currently, the CLI version always has to match the Keptn cluster version.
For example, a CLI in version 0.6.0 cannot be used with a Keptn cluster in version 0.5.0 and vice versa.
In fact, a CLI version A.B.x is only compatible to a Keptn cluster version A.B.y.

Therefore, the CLI must not suggest the user to update the CLI if this update would result in incompatibilities.

**Comment by agrimmer** [comment]
Going forward, the CLI versions have to follow [semantic version v2.0](https://semver.org/).
For example, `0.6.0.beta2` or `0.6.0.beta` are invalid versions.
Instead `0.6.0-beta2` or `0.6.0-beta` should be used.
**Note:** In the CLI, we therefore have to adapt the `IsOfficialKeptnVersion` check.

**Comment by christian-kreuzberger-dtx** [comment]
> Instead 0.6.0-beta2 or 0.6.0-beta should be used.

that's okay I guess. Let's go that way.

> We cannot use semantic versioning considering the CLI only:
> Currently, the CLI version always has to match the Keptn cluster version.
> For example, a CLI in version 0.6.0 cannot be used with a Keptn cluster in version 0.5.0 and vice versa.
> In fact, a CLI version A.B.x is only compatible to a Keptn cluster version A.B.y.
> 
> Therefore, the CLI must not suggest the user to update the CLI if this update would result in incompatibilities.

That's a valid point. We should avoid such breaking changes in the future (as in: the Keptn CLI for 0.5 should be compatible with 0.6 and vice versa - minus "new features" obviously).

For now I'd recommend that we tell the user that a new version is available, warn the user that this new version might not be compatible, and show a link to the release notes on GitHub.

**Comment by agrimmer** [comment]
I would propose to extend the `https://get.keptn.sh/version.json` with lists of available stable and prerelease versions. For example:
`{
    "cli": {
        "stable": ["0.5.2", "0.6.2"],
        "prerelease": ["0.7.0.beta"]
    }    
}`

With this information, we can always inform the user if there is a new, compatible version of the CLI.
For example, if the user currently has the CLI in version 0.5.1, we can inform the user that there is a CLI in version 0.5.2 available.

Of course, we can also inform the user that there is 0.6.2 available as you mentioned.


Furthermore, we should also think of adding the available Keptn server versions. For example: 
"server": {
    "stable": ["0.5.2","0.6.0"],
   "prerelease": ["0.6.1.beta"]
}

**Comment by christian-kreuzberger-dtx** [comment]
Agree on both of that. Feel free to make a PR to https://github.com/keptn/get.keptn.sh/

**Comment by agrimmer** [comment]
In the description above, the command `keptn config set AutomaticVersionCheck false` is used changing the configuration. The CLI, however, uses in most cases the syntax `keptn action/verb object/noun`. 
Hence, I would propose to implement `keptn set config AutomaticVersionCheck false`.

**Comment by christian-kreuzberger-dtx** [comment]
Good idea, make it so :+1:
