### ISSUE TITLE
Keptn Installer: Improve waiting times for ingress (and improve installer)

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1199]
1. The installer is currently set to `restartPolicy: onFailure` which I believe is not optimal. If we do a cluster-upgrade (or if we restart the cluster ;)) and the installation has previously failed it will be restarted right at that time, which can lead to problems.
2. Right now the installer waits a lot of certain things.
3. We are waiting for a hostname and then we wait for an IP. we could do both at the same time.

Example:  `wait_for_k8s_ingress`

```
Deployment nginx-ingress-controller in ingress-nginx namespace available.
Retry: 1/24 - Wait 5s for hostname of ingress to be available ...
Retry: 2/24 - Wait 5s for hostname of ingress to be available ...
...
Retry: 23/24 - Wait 5s for hostname of ingress to be available ...
Retry: 24/24 - Wait 5s for hostname of ingress to be available ...
Could not get ingress gateway domain name. Trying to retrieve IP address instead.
```

I believe we do not have to wait for 2 minutes to get a hostname/ip for our ingress, and we should lower that value.
In most cases the domain should be available almost immediately, and only in cases where there are problems we will not be able to retrieve the hostname or the ip address.

## Definition of Done

1. Use restartPolicy never
2. Reduce the waiting time to a value that we believe is realistic plus some safety (maybe +100% safety?) - IMHO waiting for 30 seconds should be more than enough time.
3. refactor wait for hostname and wait for ip such that whatever comes first is used

**Comment by johannes-b** [comment]
I did some tests for figuring out how long it takes to get an IP address for the ingress - on average it takes 60 seconds. This is the reason why I would leave the wait time at a max of 120 seconds. (+100% safety)
