### ISSUE TITLE
Need better commit messages when Keptn changes configuration

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#1204]
**Problem:** Right now when Keptn changes configuration, e.g, when sending a new-artifact event, the commit message says "Added resources". This is not really telling what has changed

**Solution:** I am suggesting a better commit message that indicates what triggered the change, e.g.: `version update to 2.0.0 of service myservice in stage staging by Keptn`

**Comment by christian-kreuzberger-dtx** [comment]
I agree, however this is not a small change, we need to introduce this gradually.
