### ISSUE TITLE
Keptn specification - example of sh.keptn.events.problem doesn't match the specification

### ISSUE THREAD

**Issue by dirkwall** [keptn/keptn#1211]
The specification includes project, service, and stage: https://github.com/keptn/spec/blob/0.1.1/cloudevents.md#data-9

The example doesn't:
https://github.com/keptn/spec/blob/0.1.1/cloudevents.md#example-9

**Comment by christian-kreuzberger-dtx** [comment]
Those fields are not required, and might be omitted depending on the installation (so this is not a bug).

I will however add a second example that contains project service and stage.
