### ISSUE TITLE
Lighthouse Service fails if no SLI has a criteria defined in the SLO

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#1213]
If you have an SLO and all your objective SLIs are "informational only" then the Lighthouse Service fails when sending the Evaluation Done Event. HEre is the log message we can see in the Lighthouse Service:
```
{"level":"warn","ts":1575903745.4349759,"logger":"fallback","caller":"http/transport.go:337","msg":"got an error from receiver fn: %s","error":"Failed to send cloudevent:, json: unsupported value: NaN"}{"level":"warn","ts":1575903745.435064,"logger":"fallback","caller":"http/transport.go:421","msg":"error returned from invokeReceiver","error":"Failed to send cloudevent:, json: unsupported value: NaN"}
```

Once we add a criteria it starts working again.
I assume something goes wrong with calculating the totalscore. Could be that this field ends up being Null or NaN which then causes the send event to fail!

**Comment by christian-kreuzberger-dtx** [comment]
Fixed in current sprint
