### ISSUE TITLE
Dynatrace Service Installation failes if OneAgent Operator already installed

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#1217]
When installing the Dynatrace Service the deploy scripts stop in case a dynatrace oneagent is already installed. I rather suggest the deploy scripts simply skip that step in case the dynatrace namespaces is already there and just continue installing the Dynatrace Service and creating the tagging rules, ...

There is also a related feature request I created [One Step Dynatrace Installer](https://github.com/keptn/keptn/issues/1216) that should consider this step as well

**Comment by christian-kreuzberger-dtx** [comment]
Skipping installation of the oneagent if it is already there is going to be part of #443 which is being handled in the current sprint.
