### ISSUE TITLE
Dynatrace SLI Service incorrectly escapes Metrics API query string

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#1220]
When specifying an SLI that uses the advanced MetricsAPI capabilities such as Dimension Filter it can lead to a situation where the SLI passes incorrectly escaped query strings to Dynatrace.
We ran into this when defining a query that filters on a dimension name that has spaces in it, e.g: "Test Name". 

Here the SLI definition:
```
calc:service.teststepfailurerate:filter(eq(Test Step,invoke)):merge(0):avg?scope=tag(keptn_project:$PROJECT)&...
```

The space must be escaped with %20 but its not - leading to an error from the Dynatrace API. The "workaround" of adding %20 to the query like this
```
calc:service.teststepfailurerate:filter(eq(Test%20Step,invoke)):merge(0):avg?scope=tag(keptn_project:$PROJECT)&...
```
also doesnt sovle the problem as the SLI service escapes the % sign

**Comment by bacherfl** [comment]
This seems to be fixed already since spaces are encoded with the current version (tested with https://github.com/keptn-contrib/dynatrace-sli-service/tree/d76e0ebff648f53a18ef97da1cd4a0f0e9632dc5)

**Comment by christian-kreuzberger-dtx** [comment]
Please test once we release the next version of dynatrace-sli-service.
