### ISSUE TITLE
Dynatrace SLI: Query multiple metrics at once to reduce API roundtrips

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#1222]
The Dynatrace Metrics API allows querying multiple metrics with a single API Call. The Dynatrace SLI Service shoudl leverage that capability as it will reduce the number of API Roundtrips and with that avoid a potential problem with rate limiting

**Comment by namratachaudhary** [comment]
It seems like using metrics v2, we can read multiple data points - 
the documentation is available here - 

https://www.dynatrace.com/support/help/extend-dynatrace/dynatrace-api/environment-api/metric-v2/get-data-points/?list-of-data-points%3C-%3Eaggregated-data-point=list-of-data-points
