### ISSUE TITLE
Helm Service does not send Deployment Event Fail event in case of helm upgrade error

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#1229]
**Problem:** 
* There are multiple reasons why a Helm upgrade could fail. One of them is by providing an invalid image name when sending a new-artifact event. This eventually leads to containers not starting and Helm upgrade running into a timeout

* When this happens, Keptn never sends any events that indicate that error. The only way to find out about it is by looking into the logs of the helm-service container.

**Proposed solution:**
I propose that errors during a deployment will be sent as `deployment failed events`. Not sure if this event exists at the moment, but either introduce a new `deployment failed event` or change the deployment event to include a status field and status message indicating success or failure including a status message for more details.

**Comment by christian-kreuzberger-dtx** [comment]
I have seen the same problem. You only get an error on the CLI, but not within Keptn's Bridge.

This is also related to #1225

**Comment by christian-kreuzberger-dtx** [comment]
Regarding deployment failed events and/or a status flag: This is something we are considering with the workflow engine.

**Comment by agrimmer** [comment]
Will be implemented by #2265 and #2262

**Comment by johannes-b** [comment]
I closed this issue since the problem has been addressed in #2265 and #2262.
