### ISSUE TITLE
Keptn Bridge doesnt show "all root" events

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#1230]
Right now the Keptns bridge only shows "Root Events" which are Configuration Change Events that have no stage field specified. This are the events sent through a keptn send event new-artifact.
As it is possible to send a Configuration Change Event through the API that contains a stage, e.g: direct deployment into a specific stage which kicks of a new pipeline run -> the user never gets to see these events in the keptns bridge. Not even when searching for that specific keptnContext.

Proposal: Whether there is a root event or not - if we search for a keptnContext we should always be able to list all events that belong to that keptn context.

**Comment by christian-kreuzberger-dtx** [comment]
This has been fixed in #1234 and will also be recognized by the updated bridge (in #1276).
