### ISSUE TITLE
Update Dynatrace SLI Service to use new GA version of Metricsv2 API Endpoint

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#1236]
This is an enhancement/todo request for Q1/2020. Thats the time when Dynatrace will go GA with the Metricsv2 API which we currently use in Beta to query data from Dynatrace for SLI/SLO validation.
The current endpoints will be available until end of Q1/2020. The new endpoints which also include a small number of payload changes will be available with either Sprint 185 or 186.

This ticket is to make sure we update to the new Metrics API Endpoint once the GA'd version is available

**Comment by christian-kreuzberger-dtx** [comment]
Thanks for reporting. Closing this in favor of #1282
