### ISSUE TITLE
Wording in evaluation in Keptn's bridge misleading

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#1242]
When taking a look at the evaluation results in the Keptn's bridge, the following wording is misleading IMHO.

![image](https://user-images.githubusercontent.com/7677092/70921865-6181d980-2025-11ea-8bc4-ec2f6093bcba.png)

Take a look at the left-hand side of the image. The result is "pass" and therefore in the evaluation criteria I would assume "true" or "pass" for the individual criteria (or maybe better "criterion"). Instead, the negative form is used, i.e., `violated = false`. I would have assumed something like `pass = true`.
In the right-hand side of the image it is the other way round. The evaluation is "failed" and for each individual criterion it says `violated = true` where I personally would assume something like `pass = false`.

When color-coding this would also make more sense that `pass = true` can be green and `pass = false` can be red. Would make it even easier to see at first sight which ones did pass and which ones did not.

**Comment by christian-kreuzberger-dtx** [comment]
We are in the process of creating a new version of the bridge and we will take that feedback into the next design session for the event display.

**Comment by christian-kreuzberger-dtx** [comment]
The comparison of SLIs within the new Keptn's Bridge will be handled in #1323, therefore I'm closing this issue.
