### ISSUE TITLE
Dynatrace-Service: Create synthetic tests after deployment of service

### ISSUE THREAD

**Issue by bacherfl** [keptn/keptn#1243]
**To be defined**

https://www.dynatrace.com/news/blog/making-ops-life-easier-automating-sla-monitoring-for-deployed-services-on-kubernetes/

**Comment by christian-kreuzberger-dtx** [comment]
As a reference, this has been implemented by @checkelmann in https://github.com/keptn-sandbox/dynatrace-synthetic-service
