### ISSUE TITLE
Hide token for WebSocket communication when not needed

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#1251]
**Is your feature request related to a problem? Please describe.**
When sending a request to the Keptn API, the corresponding response contains a `token` and `keptnContext`. This token is used for WebSocket communication. However, the purpose of the token is confusing to the end-user when no WebSocket communication is needed. 

Definition of the response: https://github.com/keptn/keptn/blob/0.6.0.beta2/api/response_model.yaml#L6

By default hide the token in the response. 

**Describe the solution you'd like**
To get the token, a query parameter could request it explicitly.

**Comment by christian-kreuzberger-dtx** [comment]
I don't think that we should change the behavior. We need to document the purpose of the token, and how to use the token (for websocket communication). We can also document that it is not required to use the token.

I think we can add that information to this page: https://keptn.sh/docs/0.6.0/reference/api/
