### ISSUE TITLE
Investigate joint CloudEvents with Tekton

### ISSUE THREAD

**Issue by AloisReitbauer** [keptn/keptn#1259]
**Describe the solution you'd like**
Right now Keptn CloudEvents are designed for Keptn only. We want to work with the Tekton team to agree on a see of shared events that can be reused. 

**Additional context**
Issue in Tekton: https://github.com/tektoncd/pipeline/issues/742

**Comment by bobcatfish** [comment]
Very exciting!!! 😻

**Comment by agrimmer** [comment]
We have to check out the catalog of tasks, i.e. https://github.com/tektoncd/catalog

Here we can find information on the inputs for tasks. These inputs are similar to Keptn's events.

**Comment by christian-kreuzberger-dtx** [comment]
What has been the outcome of this issue?

**Comment by agrimmer** [comment]
As we are actively working on standardizing events in CI/CD in the ["Events in CICD Workstream"](https://github.com/cdfoundation/sig-interoperability/blob/master/workstreams/events_in_cicd/meetings.md) of the CDF Sig on Interoperability where I am a member, I am closing this issue.
