### ISSUE TITLE
Keptn-service name must match Kubernetes-service name

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#1261]
Currently, the Keptn-service name has to be equals to the Kubernetes-service name contained in the Helm chart because the JMeter-service assumes an endpoint available under `Keptn-service.Project-stage` but the Helm-service generates the VirtualServices based on the Kubernetes-service names. See here:
https://github.com/keptn/keptn/blob/7c3d1a9a80c751825dce4cd0ba0d1db26c456db6/jmeter-service/main.go#L142

If the Keptn-service name and the k8s-service name do not match, the functional tests fail.

@christian-kreuzberger-dtx: I assume the Lighthouse service would run into a similar issue, right?

I see two possible solutions:
- Check whether the provided Keptn-service name is equal to the name of the K8s service contained in the Helm-chart. This is currently *not* checked in the CLI. Furthermore, one could ask why this Keptn-service name has to be provided at all, i.e. it can be derived from the Helm-chart.
- Create the VirtualServices using the Keptn-service name.

**Comment by agrimmer** [comment]
Fact: A Keptn-service always represents a single k8s service/deployment. 
Hence, we should not introduce a new resource "Keptn-service" with its own name.

Therefore, the helm-service has to check whether the service name in the event matches the service name of the Helm chart.
If they are unequal, the helm-service should throw an error and should abort the onboarding.
Furthermore, if the service name in the event is empty, the helm-service has to use the service name of the Helm chart.

**Comment by christian-kreuzberger-dtx** [comment]
Yes, we should definately avoid having a situation where the deployment has a different name than the service. IMHO the optimum would be that helm-service validates the chart and respond with an error message.

> @christian-kreuzberger-dtx: I assume the Lighthouse service would run into a similar issue, right?
No, lighthouse is not affected by this issue, as lighthouse does not access any services directly. However, dynatrace-sli-service expects certain tags to be set which are set via environment variables within deployment.yaml
