### ISSUE TITLE
Remediation Service: Add information to cloudevent about which remediation action is performed

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1268]
Right now when a problem event is received by the remediation service and it is defined in a remediation.yaml, a remediation action is performed.

It is however unclear for the end-user which remediation action has been performed (e.g., scale up). I believe this is an information that an end-user needs to know. In addition, future services might want to know which remediation has been performed in case of the remediation failing.

![Screenshot from 2020-01-09 16-00-47](https://user-images.githubusercontent.com/56065213/72078358-3bd0b300-32f9-11ea-9513-1adac074a817.png)

In addition, a remediation action does not need to cause a configuration-change event. For instance,  feature-flag toggle with unleash will only have a problem event, but no other follow up events.

**Comment by johannes-b** [comment]
This will be addressed with the implementation of #1849 because then each action.triggered event contains the action name as specified here: https://github.com/keptn/spec/pull/31

I will close this issue.
