### ISSUE TITLE
Show last deployed image and URL to service in Bridge

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1278]
Within Keptn's Bridge the user should see the last successful deployed image for a service, as well as the URL to the service.

**Comment by christian-kreuzberger-dtx** [comment]
This feature requires a proper user-story. Let's define what a user wants to see for each service in Bridge.

**Comment by ermin-muratovic** [comment]
Could display the `deploymentURIPublic` from the last successful deployment in the stage tile on the left side?  See #1402 and #1404.
But I don't know if that is always the correct URL? Maybe there is a better way to determine the current deployed image and URL?

![image](https://user-images.githubusercontent.com/6098219/75449527-6a6c2100-596d-11ea-8eb6-56045f5e182b.png)
