### ISSUE TITLE
Retry sending cloudevents on failure/error

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1279]
I just had a deployment with 0.6.0.beta2 getting stuck because the `helm-service` was unable to send an event to the event-broker:

```
{"timestamp":"2020-01-14T12:33:11.169017581Z","logLevel":"ERROR","message":"Cannot send deployment finished event: Failed to send cloudevent:, Post http://event-broker.keptn.svc.cluster.local/keptn: EOF"}
```

As far as I was able to investigate, it seems that the eventbroker has crashed or K8s has re-scheduled the pod or something like that.

In such an event we need to be able to perform a retry (with exponential back off) such that an event like this doesn't get stuck.

**Comment by agrimmer** [comment]
I experienced a similar issue in the `prometheus-sli-service`.
I see the following log messages
```
{"level":"warn","ts":1583326693.7711232,"logger":"fallback","caller":"http/transport.go:337","msg":"got an error from receiver fn: %s","error":"Failed to send cloudevent:, json: unsupported value: NaN"}
{"level":"warn","ts":1583326693.7712023,"logger":"fallback","caller":"http/transport.go:421","msg":"error returned from invokeReceiver","error":"Failed to send cloudevent:, json: unsupported value: NaN"}
```
In my case, the eventrbroker was not restarted.
