### ISSUE TITLE
Onboarding service stuck at inject Istio  into namespace

### ISSUE THREAD

**Issue by pahofmann** [keptn/keptn#1294]
**Environment**
* Client OS (e.g., Linux, OSX, Windows): **Linux**
* Keptn Version (`keptn version`): **0.6.0.beta2**
* Kubernetes Cloud Provider (e.g., GKE, AKS):  **AKS**
* Kubernetes version (`kubectl version`): **v1.14.8**
* istio version: 1.3.1 (installed by keptn)

**Affected Component**
* [ ] Docs
* [ ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [x] Istio
* [ ] Bridge
* [ ] Gatekeeper
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**
When onboarding a new service it  gets stuck at `inject Istio to the amcssp-prod namespace for blue-green deployments` indefinetly.

**To Reproduce**
1. Create a new AKS Cluster
2. Install keptn 
3. Onboard service

**Expected behavior**
Onboarding process finishes.

**Current behavior**
CLI is stuck with above message as last output (with -v flag).

**Additional context**
I checked the logs of the istio pods. citadel keeps looping the following error every second:
`istio.io/istio/security/pkg/k8s/controller/workloadsecret.go:231: Failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:istio-system:istio-citadel-service-account" cannot list resource "namespaces" in API group "" at the cluster scope`

Looks like https://github.com/istio/istio/issues/16684, but that should be fixed in istio 1.3.

**Comment by agrimmer** [comment]
Thanks for reporting! I already fixed this issue. 
I added a nil check for the labels-map, see here
https://github.com/keptn/keptn/blob/3fe80ba2dd9e33cd9d4e024481989b1218a96f7a/helm-service/controller/onboarder.go#L126
This fix is available in version 0.6.0, which will be available next week.

**Comment by pahofmann** [comment]
Great to hear, is there a work around by any chance to get the service deployed on the current beta?

**Comment by agrimmer** [comment]
I prepared an image containing this fix, which is available under `keptn/helm-service:init-labels-map`
Please edit the deployment of the `helm-service` and set this image.
