### ISSUE TITLE
Update Istio version to 1.4.3

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#1298]
If we do not use our minimal Istio installation, the currently used Istio version can cause problems.

Google informed us about the following issue:

![Screen Shot 2020-01-20 at 10 43 58](https://user-images.githubusercontent.com/10980861/72716001-cd4de980-3b71-11ea-834b-67e4af2a0513.png)

We should update the Istio version.

**Comment by christian-kreuzberger-dtx** [comment]
We believe Keptn 0.6 and 0.5 are not affected as we use an older istio version. We will document this as a potential "known issue" for 0.6.

**Comment by christian-kreuzberger-dtx** [comment]
This has been documented in the release notes of 0.6.0: https://github.com/keptn/keptn/releases/tag/0.6.0

I'm closing this issue now.
