### ISSUE TITLE
Bridge: Comparison of evaluation results

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#1323]
When reviewing a test evaluation result, it should be possible to compare, for example: evaluation B4 with B1, or evaluation B4 with last milestone X. As a result, the reviewer wants to see a diff of the two builds, i.e., which metrics have changed between these builds and how.

**Comment by ermin-muratovic** [comment]
![image](https://user-images.githubusercontent.com/6098219/74167230-392ee980-4c28-11ea-8f16-709e7cef4ebf.png)

**Comment by ermin-muratovic** [comment]
![image](https://user-images.githubusercontent.com/6098219/74167418-8317cf80-4c28-11ea-9ab0-405792e3fb8c.png)

**Comment by ermin-muratovic** [comment]
![image](https://user-images.githubusercontent.com/6098219/74246102-45787c80-4ce4-11ea-805e-1d2511b9c691.png)
Each indicator (objective) can be included in the chart either as bar or line. But with a large number of objectives that might not be a good idea.

**Comment by johannes-b** [comment]
![image](https://user-images.githubusercontent.com/729071/74414043-e7ad7700-4e40-11ea-9aee-6edfa82f50fe.png)

I had a conversation with a member of the CPE team regarding the comparison view of evaluation results. I showed him option A and B and he provided the following feedback: 

**Option B:** The information gain of this visualization is high and gives already a detailed look into the evaluation result. Even more than the team currently has in the tool they are using. He prefers this view when it comes to his role as performance engineering. However:

**Option A:** Is required too. Especially, when it comes to getting an overall picture of trends. This is important for someone how owns the responsibility for multiple test objects (in their case: clusters):

Overall feedback: There should be a way to flip between both views (A and B).

**Comment by ermin-muratovic** [comment]
![image](https://user-images.githubusercontent.com/6098219/75011649-6da07200-5480-11ea-85b7-6eb9df601a41.png)

There is now an option to switch between Heatmap and Chart, when viewing the Evaluation comparison.

The Heatmap shows the overall Score in the top-most row and then all the SLIs follow. As there are problems with displaying a tooltip, for the time being you can click on any tile and see the details of that specific evaluation that you clicked.

The latest image to test this feature is available on dockerhub:
`keptn/bridge2:feature.1323.20200220.1805`
