### ISSUE TITLE
Dynatrace Keptn Dashboard Improvements

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#1329]
The "keptn configure monitoring dynatrace" is a great way to enable automatica generation of dashboards. Here a couple of improvements I would like to see

1: Use label "Services in dev", "Services in prod" for the headers where you list the links to the onboarded services
2: Filter the infrastructure tiles on top with the hosts that actually run this keptn instance. This probably requires you to install the OneAGent operator with a dedicated HOST_GROUP property that indicates the keptn installation name, e.g: "keptn k8s pre-prod" - with that you can then filter these tiles based on host group name
3: The section name "Operations" doesnt make sense when it just shows the link to the keptns bridge. I would simply call the section "Keptn" and change the link to "Open Bridge"
4: I would add a Disk and Memory Tile to the "Infrastucture" section as the dashboard then includes all major resources: cpu, network, disk, memory. Or consider
5: Add a section called "Environment Availability" - this would show synthetic tests that are testing the availablity of servies deployed in each stage

Following is a screenshot that includes my suggestions
![image](https://user-images.githubusercontent.com/675886/73251114-98b4e000-41b8-11ea-9223-a5643554ebe0.png)

**Comment by agrimmer** [comment]
Closing this issue because it is managed here https://github.com/keptn-contrib/dynatrace-service/issues/153
