### ISSUE TITLE
Simplify the setup of Dynatrace monitoring

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#1332]
As a user, I do not want to manually create a secret containing the DT_API_TOKEN, DT_TENANT, and DT_PAAS_TOKEN.
Furthermore, I do not want to manually apply the manifests for the `dynatrace-service`.

*Solution:*
In the CLI command `keptn configure monitoring dynatrace`, we can automatically generate the secret and apply the manifests.
For the tenant and tokens, we can introduce new flags or prompt the user like `keptn install` does.

*Note:* 
- Make sure that the installed Keptn version matches the dynatrace-service.
- Make sure that the local .kube config points to the desired cluster (see `keptn configure domain`)

**Comment by grabnerandi** [comment]
Additional I suggest that the CLI automatically validates whether the Endpoint and the Tokens are valid by making a call to the Dynatrace API and querying, e.g: the version information. This is an extra validation step that makes sure that the passed information is correct

**Comment by christian-kreuzberger-dtx** [comment]
This will be handled by the new uniform/shipyard format.
