### ISSUE TITLE
Provide access to up-stream configuration repository per project

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#1335]
For most projects I assume that users will define an upstream git repo. If we have this information I want to see this in the projects overview page. Right there on the top.

![image](https://user-images.githubusercontent.com/675886/73363249-af3a6480-42a8-11ea-9dbe-c9ab21c4dc3c.png)

**Comment by christian-kreuzberger-dtx** [comment]
Before we show that in Bridge we need to have authentication within Bridge. If right now you publicly expose Keptn's Bridge and show the upstream repo, you would show the following publicly:

* Your upstream repo (imagine this being a URL that you don't want everyone to know)
* Potentially your credentials

Anyway, from a technical point of view, we can and should provide the git upstream repo URL via the configuration-service API (and going forward, it should also be available via the api-service).

**Comment by grabnerandi** [comment]
As we have authentication of the bridge I would like to discuss whether we can add this link to the upstream git. All I am really asking is just a link - so - whoever clicks that link needs to have access to that git repo anyway which is why I dont really see any harm displaying that link as the link itself doesnt contain any sensitive information

**Comment by johannes-b** [comment]
Since we provide authentication per default and the GET endpoint of /projects returns the information of the git-upstream, showing this link brings a value-add for a Keptn user. 

Response of GET /projects:
```
 "projects": [
    {
      "creationDate": "1595250760696208217",
      "gitRemoteURI": "https://github.com/keptn-deploy/xyz.git",
      "gitUser": "xyz",
      "projectName": "sockshop",
      ... 
  }
```
 
However, I propose to add it to the project tile: 
![image](https://user-images.githubusercontent.com/729071/88166027-e44fc000-cc16-11ea-90e8-7aca4b74bf48.png)

**Comment by johannes-b** [comment]
We should also add the Git link to a stage: 
![image](https://user-images.githubusercontent.com/729071/91835815-2fafb200-ec4a-11ea-9edf-51c5c841b7f1.png)
