### ISSUE TITLE
Provide Browsing Capabilities of Project Specific Git Repo

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#1336]
Keptn keeps an internal Git Repo but - unless you have specified an upstream - there is no option to see or edit these files.
Through the Keptns Bridge I want to be able to explore & browse that git repo. I want to be able to make changes to individual files, e.g: SLIs, SLOs ...

I am not suggesting that we re-implement a full Git Browser but I assume those viewers/editors are available for standard Git which is what we should deploy with keptn

**Comment by christian-kreuzberger-dtx** [comment]
I did a quick research and I believe we could ship [Gitea](https://gitea.io/en-us/) with Keptn and use it as  the default upstream.
Resource footprint seems to be okay-ish (131 MegaByte without any git repos in it).

**Comment by johannes-b** [comment]
This is also very useful info: https://medium.com/@jmarhee/running-gitea-on-kubernetes-d1ca5bcf0a4e

**Comment by agrimmer** [comment]
Alternatively, we can implement a tiny HTTP server which allows cloning and pushing our internal repo. Therefore, we can use the small go library [gitkit](https://github.com/AaronO/go-git-http).

This would minimize external dependencies and also the resource overhead.

**Comment by christian-kreuzberger-dtx** [comment]
gitkit seems unmaintained, the git repo was last updated over 4 years ago.

But I agree, implementing a tiny http server in front of configuration-service to expose git would be enough as it allows access to the git repository via other tools (e.g., vs-code, git cli, ...).

**Comment by agrimmer** [comment]
We can postpone/close this issue because implementing https://github.com/keptn/keptn/issues/1517 allows to set an upstream any time, which afterward allows editing the GIT repo.
