### ISSUE TITLE
Filter events in list of root events

### ISSUE THREAD

**Issue by ermin-muratovic** [keptn/keptn#1342]
Allow filtering events by selecting certain event types, as shown here: 
![image](https://user-images.githubusercontent.com/729071/79861787-347b7400-83d5-11ea-8f14-1b8d65a943c0.png)

The list of filters is pre-defined with: 
- Create Service
- Configuration Change
- Deployment Finished
- Tests Finished
- Start Evaluation
- Problem Open

Could make use of https://github.com/keptn/keptn/issues/1316

**Definition of Done**
- [ ] Based on the selected events, the list of root events is then is reduced.

**Comment by christian-kreuzberger-dtx** [comment]
Needs further clarification and definition of the workflow.

**Comment by johannes-b** [comment]
I provided a wireframe for implementing the filter on root events.
