### ISSUE TITLE
Keptn`s bridge: Collection of Enhancements

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#1343]
As a user of the Keptn's bridge, I would like to propose a minor enhancement that would have a great impact on the understandability and in general on the usability of the Keptn's bridge.

--- 

**Actions:** 
- Please use this issue, to propose an idea that helps achieve a better experience when using the Keptn's bridge. 
- Feel free to comment on any idea.

**Comment by johannes-b** [comment]
When clicking on an event stream that contains a failed Keptn action (e.g., evaluation failed, which is marked as red), I want to get directly to the failed Keptn action without scrolling on the right-hand side.

**Comment by johannes-b** [comment]
It is hard to tell this is a service: 
![image](https://user-images.githubusercontent.com/729071/73658864-f5494c80-4649-11ea-9d2e-e22ebf60fc1e.png)

**Comment by johannes-b** [comment]
It is not really clear what this item is: 
![image (1)](https://user-images.githubusercontent.com/729071/73658998-38a3bb00-464a-11ea-9f50-129552b23667.png)

We should think of giving it a better name.

**Comment by johannes-b** [comment]
The JSON payload of each event should be hidden and not that prominent. Maybe just show important meta-data of each event.

**Comment by johannes-b** [comment]
_Getting started with your first project:_ When no Keptn project is available because the user opened the bridge right after the installation of Keptn, a guide should be provided: how to set up a project and onboard a sample app.

**Comment by johannes-b** [comment]
Filter and search option for Problem/Deployment events.

**Comment by ermin-muratovic** [comment]
@johannes-b 
May I close this issue, since I created a separate issue in github for each request for easier planning?
