### ISSUE TITLE
Keptn CLI: Improve error message when no connection to API could be made

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1349]
**Problem:** When trying to connect to the API via the CLI, e.g., using `keptn add-resource`, the error message is confusing and misleading:

```console
$ keptn add-resource --project=sockshop --service=carts --stage=production --resource=remediation_feature_toggle.yaml --resourceUri=remediation.yaml 
Adding resource remediation_feature_toggle.yaml to service carts in stage production in project sockshop
Error: Resource remediation_feature_toggle.yaml could not be uploaded: Post https://my-endpoint/v1/project/sockshop/stage/production/service/carts/resource: dial tcp: lookup my-endpoint on 127.0.0.53:53: server misbehaving
```

**Solution:** The error message needs to be more meaningful, e.g., like it is with `keptn status`:

```console
$ keptn status
Starting to authenticate
Authentication was unsuccessful. Post https://my-endpoint/v1/auth: dial tcp: lookup my-endpoint on 127.0.0.53:53: server misbehaving
CLI cannot be authenticated against Keptn cluster https://my-endpoint
``` 

However, I'm not sure where the `my-endpoint` is coming from, this needs to be investigated as well.

In addition, possible reasons for the problem should be stated: 
```console
Possible reasons:
* The Keptn API server is currently not available. Check if your Kubernetes cluster is available.
* Your Keptn CLI points to the wrong API server (verify using `keptn status`)
```

**Comment by supra08** [comment]
Hi @johannes-b! If this issue has not already been taken up, I would like to try it out. I'm just starting out with `keptn`

**Comment by supra08** [comment]
Hi @johannes-b, is the scope of this update only the `add-resource` CLI command or it includes other commands as well that interacts with the API?

**Comment by johannes-b** [comment]
Hi @supra08, `add-resource` works as an example meaning that the scope includes the other CLI commands too. The best way would be a generic utility function that deals with a non-reachable API and can be reused when an API call is made.
