### ISSUE TITLE
Use icons for certain event types

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1352]
We can use the barista icons (see https://barista.dynatrace.com/resources/icons/ )

1. If we highlight something with red or green, we should use an icon anyway to improve accessibility (just think about dyschromatopsia, in german "Rot-Grün Schwäche")

Examples where we should use icons in this case: failed tests, failed evaluations, problem events, failed stages. 

2. Map event types (e.g., root events) to icons.
Example:
* configuration-change
* problem open

All others can have a generic "log" or "info" icon

**Comment by christian-kreuzberger-dtx** [comment]
Needs definition of which icon should be used.

**Comment by johannes-b** [comment]
I vote for: 
- **deployment**: https://barista.dynatrace.com/resources/icons/deploy/
- **evaluation**: https://barista.dynatrace.com/resources/icons/traffic_light/
- **test** (performance): https://barista.dynatrace.com/resources/icons/perfromance_health/
- **get-sli**: https://barista.dynatrace.com/resources/icons/collector/

**Comment by christian-kreuzberger-dtx** [comment]
* *configuration-change*: https://barista.dynatrace.com/resources/icons/duplicate/
* *get-sli*: https://barista.dynatrace.com/resources/icons/analyze/ or https://barista.dynatrace.com/resources/icons/summary/
* *problem.open*: https://barista.dynatrace.com/resources/icons/criticalevent/ or https://barista.dynatrace.com/resources/icons/applicationhealth/
* *problem.closed*: No idea :)
* *default icon for all other events*: https://barista.dynatrace.com/resources/icons/information/

**Comment by ermin-muratovic** [comment]
I used the defined icons next to the event label

**Comment by robertjahn** [comment]
For inspiration. This is how AWS shares their icons.  https://aws.amazon.com/architecture/icons/

**Comment by robertjahn** [comment]
perhaps the icon can be colored.  RED for when a step failed.  YELLOW for warning.  Black maybe ok for GOOD as to not be too distracting.

**Comment by checkelmann** [comment]
I like the Idea with the Icons and Colored borders on the event itself. Is the red border-color on the left (staging) only when an error occurs on the event stream?

**Comment by pahofmann** [comment]
The colored icons look good, I like that. I would keep the  colored border aswell though, makes it a bit easier to catch.  
Ror the _Tests Finished_ that is green, its easy to miss if only the icon is green.

**Comment by robertjahn** [comment]
Also, consider how other tools do it.  I like the unique icon but we dont want to make the UI to distracting by having too make things to decipher and read.  Someone just wants to see all green and focus on exceptions when.  Other tools just do show the same icon with green/red status and the summary then you can expand the step if there is an issue. Here are a few examples of other tools 
![image](https://user-images.githubusercontent.com/24907089/76854407-5fe2d000-6825-11ea-8b88-7f961096a6a3.png)
![image](https://user-images.githubusercontent.com/24907089/76854474-86087000-6825-11ea-9f54-416f47820a92.png)
![image](https://user-images.githubusercontent.com/24907089/76854505-97517c80-6825-11ea-9f47-b82f38e80fef.png)
![image](https://user-images.githubusercontent.com/24907089/76854686-ee575180-6825-11ea-89eb-0bc164c9d73e.png)
![image](https://user-images.githubusercontent.com/24907089/76854699-f57e5f80-6825-11ea-9377-e2da218464d6.png)
