### ISSUE TITLE
API: Allow to set keptnContext in events sent to API endpoint

### ISSUE THREAD

**Issue by bacherfl** [keptn/keptn#1355]
When a new event is sent to the API, it should check wether the field `shkeptncontext` is set, and if it is a valid UUID. If yes, this value will be used. 
If the value is set, but is not a valid UUID, a new UUID should be generated using the provided value as a random seed
If no value is provided, a new random UUID should be generated

**Comment by christian-kreuzberger-dtx** [comment]
>  If the value is set, but is not a valid UUID, a new UUID should be generated using the provided value as a random seed

I'm not so sure if this is a good idea. 

a) it could be abused (if you know the random seed, you can do a lot of bad things), and
b) it is not intuitive.

I would suggest that, if the value set but not a valid UUID, we should return a validation error.
