### ISSUE TITLE
yq: command not found

### ISSUE THREAD

**Issue by collinjlesko** [keptn/keptn#136]
**Describe the bug**
yq: command not found.  Did not see this as a pre-req. Install the yq libraries, and re-ran ./setupInfrastructure.sh.

**To Reproduce**
1. run ./setupInfrastructure.sh
2. It's the last few lines that execute yq commands

**Expected behavior**
Finishes normally.

**Environment**
1.11.7-gke.4

**Comment by bacherfl** [comment]
Hi Colin,
do you recall which revision of the keptn repo you checked out before encountering this issue? Did you check out the 0.1 release, or the master branch?

**Comment by collinjlesko** [comment]
Master branch at the time. Deployed it on a fresh Kubernetes cluster.

**Comment by bacherfl** [comment]
Ok, thanks for clarifying. The prerequisites will be extended in the documentation for the 0.2 release, since 0.1 does not require yq to be installed

**Comment by bacherfl** [comment]
Closing this for now, since it will be delivered in the 0.2 release
