### ISSUE TITLE
The Amazon EKS installer file defineCredentials.sh contains Azure folder reference 'aks' instead of 'eks'

### ISSUE THREAD

**Issue by johnrusaw** [keptn/keptn#1371]
**Environment**
* Client OS (e.g., Linux, OSX, Windows): Linux
* Keptn Version (`keptn version`): latest version of master branch (2020, Feb 10)
* Kubernetes Cloud Provider (e.g., GKE, AKS): EKS
* Kubernetes version (`kubectl version`): N/A

**Affected Component**

* [ ] Docs
* [x] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [ ] Bridge
* [ ] Gatekeeper
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter
* [x] Installer

**Describe the bug**
The Amazon EKS  installer script "defineCredentials.sh" seems to refer to the Azure AKS credentials file folder referencing...
`cat ./aks/creds.sav`
instead of the Amazon EKS file folder I would expect as...
`cat ./eks/creds.sav`
refer to...
https://github.com/keptn/keptn/blob/master/installer/scripts/eks/defineCredentials.sh#L22

**To Reproduce**
View the file from the latest commit, currently 4ec8d6f on Aug 12, 2019, that can be viewed here...
https://github.com/keptn/keptn/blob/4ec8d6f88fbe130c69eb0430b6541c766dc70132/installer/scripts/eks/defineCredentials.sh#L22

Steps to reproduce the behavior: N/A

**Expected behavior**
I would expect line 22 to contain the folder name 'eks' instead of 'aks' like so...
`    cat ./eks/creds.sav | sed 's~CLUSTER_NAME_PLACEHOLDER~'"$CLN"'~' | \`

**Current behavior**

**Screenshots**

**Additional context**

**Comment by christian-kreuzberger-dtx** [comment]
Thanks fo rthe report. has been fixed in https://github.com/keptn/keptn/pull/1372
