### ISSUE TITLE
`keptn delete project` should also delete events of project stored in the MongoDB

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#1384]
When a project is deleted, all corresponding events which are related to this project have to be deleted. 
Currently, only the internal Git repository containing the configuration is deleted but the corresponding events in the Mongo DB are not.

## Technical Details
When a project is deleted, the `mongodb-datastore` has to delete all events related to this project. Therefore, the `mongodb-datastore` also has to listen to `sh.keptn.internal.event.project.delete` events.

## Definition of Done
When a Keptn project is deleted, the MongoDB must not contain any events related to this project.

**Comment by SVilgelm** [comment]
@agrimmer @christian-kreuzberger-dtx Correct me if I I'm wrong.

This task requires to add even receiver for the mongo-storage project, like it's done in the lighthouse:

```go
	ctx := context.Background()
	t, err := cloudeventshttp.New(
		cloudeventshttp.WithPort(env.Port),
		cloudeventshttp.WithPath(env.Path),
	c, err := client.New(t)
	log.Fatalf("failed to start receiver: %s", c.StartReceiver(ctx, gotEvent))
```

then filter an event, like:
```go
	switch event.Type() {
	case keptnevents.InternalProjectDeleteEventType:
		...delete related events from db
```

**Comment by agrimmer** [comment]
Thanks for your question! You are on a good track! 

However, I see one problem:
The `mongodb-datastore` service uses go-swagger, which already has an open server on port 8080. Therefore, we cannot open another server on port 8080 using the cloudevents-library (like it is done in the lighthouse service).
One possible solution would be to add a swagger-middleware and check if the request contains a cloudevent with type `sh.keptn.internal.event.project.delete`.
I used the swagger-middleware here:
https://github.com/keptn/keptn/blob/26bd9873ab1eab7fda76eba54bacf8dc9753aa78/api/restapi/configure_empty.go#L126

Using the swagger-middleware is one possible way but we are open for alternative solutions!

Finally, you also need to deploy a `distributor`. This distributor receives all events from NATS for a specific topic (here it is `sh.keptn.internal.event.project.delete`) and forwards them to the `mongodb-datasore` via a HTTP POST-request.
See https://github.com/keptn/keptn/blob/master/installer/manifests/keptn/core.yaml#L338 as reference (the`PUBSUB_RECIPIENT` has to be `mongodb-datastore`).

If you have further questions, please let me know.

**Comment by SVilgelm** [comment]
thank you for the explanation, will see what can I do here

**Comment by agrimmer** [comment]
I have a better solution in mind:

We extend the swagger api of the `mongodb-datastore` with a `/project/{projectName}` DELETE endpoint.
Then, the `shipyard-service` (which already listens on `sh.keptn.internal.event.project.delete`)  calls this new endpoint.

Fortunately, we already have such an endpoint in the `configuration-service`, which is also called by the `shipyard-service` when a project should be deleted. 

You can find the endpoint of the `configuration-service` here: https://github.com/keptn/keptn/blob/26bd9873ab1eab7fda76eba54bacf8dc9753aa78/configuration-service/swagger.yaml#L305
This endpoint is also needed in the `mongodb-datastore`.

Finally, this new endpoint is called in the `shipyard-service` similar as we do for the `configuration-service`, i.e. https://github.com/keptn/keptn/blob/26bd9873ab1eab7fda76eba54bacf8dc9753aa78/shipyard-service/main.go#L270

**Comment by SVilgelm** [comment]
Yeah, I agree, it will be easier to implement, but on the other hand we can use a different port 
(8081?) for the event receiver:
```go
	var gracefulStop = make(chan os.Signal, 1)
	defer close(gracefulStop)
	signal.Notify(gracefulStop, os.Interrupt, syscall.SIGINT, syscall.SIGTERM)

	go func() {
		if err := c.StartReceiver(ctx, gotEvent); err != nil { // 8081
			log.Fatalln(err)
		}
	}()

	go func() {
		if err := server.Serve(); err != nil { // 8080
			log.Fatalln(err)
		}
	}()
	<-gracefulStop
	ctx.Done()
	server.Shutdown(...)
```
In this case we will get a true async solution.
But, as you said, it requires a new distributor, and maybe something else. It is more complicated, but it may bring additional value in the future.

**Comment by christian-kreuzberger-dtx** [comment]
Thinking about how Keptn will work in the future we should work with the event receiver on port 8081 (or if anyhow possible accept the event on port 8080 with a middleware).

Anything else would just create additional dependencies between our microservices.

**Comment by SVilgelm** [comment]
I agree, but there is a problem, I'm not sure I will be really able to properly test the changes without dev environment. I will need your help in testing.

**Comment by agrimmer** [comment]
We can help with testing!

**Comment by christian-kreuzberger-dtx** [comment]
Hi @SVilgelm,

as @agrimmer already noted we can help with testing.

Alternatively you can run Keptn on Minikube 1.2 on your local machine:
* Setup and configure minikube: https://keptn.sh/docs/0.6.0/installation/setup-keptn/#setup-kubernetes-cluster
* Run Keptn Install on Minikube: https://keptn.sh/docs/0.6.0/installation/setup-keptn/#install-keptn

**Comment by yul14nrc** [comment]
Currently you can't add a stage (to the shipyard file) to a project. According to @AloisReitbauer updated behavior for shipyards is planned for 0.8. So in that case, you should give an option when deleting the project ask to the user if requires delete all the events or no until we can update the stages on a project on version 0.8

**Comment by agrimmer** [comment]
Thank you for bringing this up, @yul14nrc!
I implemented this issue and now a `keptn delete project` also deletes the corresponding events. That means if you delete the project you also delete the events.
