### ISSUE TITLE
Make more Keptn context information available (GitUrl, Bridge Url, Labels ...) in core Keptn services such as helm-service

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#1386]
When pushing a new artifact or when processing a problem, Keptn has a lot of additional context information about that artifact or problem, e.g., stage, project, service, deployment type, test strategy, service endpoint, up-stream GitUrl, link to the bridge, labels, user or tool who initiated that current workflow, etc.

**Idea:** Similar to what other tools are doing, e.g., Jenkins provides all its context via environment variables, it would be useful to make this data easily available in core Keptn services such as the helm-service. This could be done by exposing this data via values so that I can easily reference this context data in my helm charts and then pass it on to my application or any other tool

Here is an example on how I could envision passing this information to e.g: _Dynatrace_ deployment.yaml
```
...
  name: DT_CUSTOM_PROP
  value: keptn_labels={{ .Values.keptn.labels }} keptn_giturl={{ .Values.keptn.giturl }}  keptn_bridgelink={{ .Values.keptn.bridgelink }} keptn_context={{ .Values.keptn.context }}
```

Besides the helm-service, this information can be passed to the JMeter script as additional parameters so that the script can include these links in the load testing report at the end.

**Advantage:** By making this context data available, new use-cases, e.g: _Dynatrace can automatically link back to the GitUrl or the Bridge_ can get implemented.

**Comment by johannes-b** [comment]
In Keptn 0.8, the meta-data generated by the executing services will be aggregated and passed on to the next event. This means that a service gets the data from a task executed before. This should resolve this issue.
