### ISSUE TITLE
Minor Doc Wording in Note for "keptn send event new-artifact"

### ISSUE THREAD

**Issue by johnrusaw** [keptn/keptn#1399]
The note in https://keptn.sh/docs/0.6.0/reference/cli/#keptn-send-event-new-artifact says...
`Therefore, the used Docker registry has to accessible form your cluster.`
but I think the word "be" is missing and word "form" should be "from" and was intended to be...
`Therefore, the used Docker registry has to be accessible from your cluster.`

**Comment by agrimmer** [comment]
Thank you for reporting the spelling issues!
I corrected it with https://github.com/keptn/keptn.github.io/pull/446
