### ISSUE TITLE
Support keptn v0.1 on Amazon EKS

### ISSUE THREAD

**Issue by AloisReitbauer** [keptn/keptn#14]
Provide documentation on how to install keptn v 0.1 on EKS

**Comment by grabnerandi** [comment]
Currently testing keptn0.1 on AWS EKS based on documentation provided for GKE

**Comment by grabnerandi** [comment]
First version online: https://keptn.sh/docs/0.1.0/setup/eks/install-keptn-v.0.1/

**Comment by AloisReitbauer** [comment]
Should we close this one as the description is already in the doc?

**Comment by dirkwall** [comment]
Closing, doc is there.
