### ISSUE TITLE
JMeter-Service: Use deploymentURILocal or deploymentURIPublic instead of guessing the service url

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1403]
This implements a part of [KEP 0005](https://github.com/keptn/enhancement-proposals/blob/master/text/0005-deployment-finished-with-deployed-endpointurl.md).

In #1402 we implement Helm-Service to send two new attributes in the deployment-finished event. 

Jmeter service should now use those fields in the following order:

* If `deploymentURILocal` is set ( contains the local url, e.g., http://carts.sockshop-staging.svc.cluster.local), JMeter should use this as the base url for the tests (Hint: in the future we can use this for dark tests)
* If `deploymentURILocal` is not set, but  `deploymentURIPublic` is set( contains the public url, e.g., http://carts.sockshop-staging.MY_KEPTN_DOMAIN), then that's the URL to use.
* fallback: if none of the above is set, we use the current educated guess of the service url based on stage, service name, deployment type, etc...

**Comment by christian-kreuzberger-dtx** [comment]
I'm moving this back to in progress, as the implementation is not 100% done.

While the current implementation is as described in the original issue, it does not work properly. The reason is that jmeter tests are currently called like this:

```go
	res, err := keptnutils.ExecuteCommand("jmeter", []string{"-n", "-t", "./" + scriptName,
		// "-e", "-o", resultsDir,
		"-l", resultsDir + "_result.tlf",
		"-JSERVER_URL=" + serverURL,
		"-JDT_LTN=" + LTN,
		"-JVUCount=" + strconv.Itoa(vuCount),
		"-JLoopCount=" + strconv.Itoa(loopCount),
		"-JCHECK_PATH=" + checkPath,
		"-JSERVER_PORT=" + strconv.Itoa(serverPort),
		"-JThinkTime=" + strconv.Itoa(thinkTime)})

```

We do set serverPort (= 80) and serverUrl (= the rules from above). This is certainly not correct in all cases. In addition, looking at the JMX file for carts, we do not support using another protocol (e.g.,  HTTPS):

https://github.com/keptn/examples/blob/d8eecef9e07225afeb11b874450b570025610895/onboarding-carts/jmeter/load.jmx#L120-L122

If we now have `deploymentURIPublic` set to `https://carts.sockshop-staging.some-keptn-host.example.com` the tests will fail.

**Comment by christian-kreuzberger-dtx** [comment]
1. Introduce new param: PROTOCOL (http or https)
2. Parse server url:
  * Protocol
  * host
  * port
3. Adapt JMX file for sockshop

**Comment by agrimmer** [comment]
Additionally, we have to parse the path (i.e. `/health`).
