### ISSUE TITLE
setupIstio.sh pretends to install Istio minimal profile while it is a mixture of minimal and default 

### ISSUE THREAD

**Issue by avodaqstephan** [keptn/keptn#1406]
Hi, 

because I already had Istio installed, I wanted to reconfigure it to the needs of the keptn installation. I looked at the setupIstio.sh to find the correct profile I need to install:

https://github.com/keptn/keptn/blob/09687a62affe6f0be03771e0cfccc22df0481910/installer/scripts/common/setupIstio.sh#L29

Which points to the depending values.yaml: https://github.com/keptn/keptn/blob/master/installer/manifests/istio/helm/istio/values-istio-minimal.yaml

It says "minimal" but actually it is a mixture of minimal and default installation from Istio if you compare it to the Istio Docs: https://istio.io/docs/setup/additional-setup/config-profiles/ 

This can lead to problems if a user - like me - is using `istioctl` to define the profile. Because with istioctl compared with minimal setup, keptn won't work.

So my proposal would be, to rename the `values-istio-minimal.yaml` or use a current Istio profile from the offical docs. 

Kind regards, 
Stephan

**Comment by christian-kreuzberger-dtx** [comment]
@agrimmer @bacherfl any opinion on that? Can we just rename that yaml file?

**Comment by avodaqstephan** [comment]
My proposal would be to switch to the default installation of Istio v1.5. This version has some great improvements and works perfectly with keptn. 
You also should consider to install it via istioctl, because helm installation will be deprecated in the future > https://istio.io/docs/setup/install/helm/

**Comment by agrimmer** [comment]
We should be careful when we update Istio to v1.5 as there is a known bug as described here https://github.com/istio/istio/issues/22463
@avodaqstephan thanks for reporting!

**Comment by christian-kreuzberger-dtx** [comment]
This issue will become obsolete once we implement [KEP 18](https://github.com/keptn/enhancement-proposals/pull/18).

**Comment by christian-kreuzberger-dtx** [comment]
Closing this as it is implemented in KEP 18.
