### ISSUE TITLE
Quality Gates use case attempts to create namespaces for stages defined in shipyard file

### ISSUE THREAD

**Issue by jonathansd1** [keptn/keptn#1417]
**Environment**
Running _**keptn v0.6.0**_ on _**macOS Catalina 10.15.3**_. Target is _**GKE**_ running _**K8s 
 v1.15.9-gke.9**_. 

**Affected Component**

* [ ] Docs
* [X] CLI
* [x] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [ ] Bridge
* [ ] Gatekeeper
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**
After an initial install of Keptn with Quality Gates use case only, creating a project causes an error if namespaces already exist for the stages defined in `shipyard.yaml`.  This is undesirable especially in cases where the Lighthouse service is being added to existing application environments and CI/CD tooling.

**To Reproduce**
Assume `shipyard.yaml` contains the following:
```
stages:
  - name: dev
```
Next, run the following commands:
```
kubectl create ns manhattan-dev
keptn install --platform=gke --use-case=quality-gates
keptn create project manhattan --shipyard=shipyard.yaml
```

**Expected behavior**
```
$ keptn create project manhattan --shipyard=shipyard.yaml
Starting to create project
Project manhattan created
Stage dev created
Shipyard successfully processed
```

**Current behavior**
```
$ keptn create project manhattan --shipyard="/Users/jonathan.duggan/workspace/shipyard.yaml"
Starting to create project
Namespace manhattan-dev already exists. Please first delete this namespace with 'kubectl delete ns manhattan-dev' and all contained Helm releases with 'helm del $(helm ls --namespace manhattan-dev --short) --purge'
Namespaces are not available anymore.
```

**Screenshots**
N/A

**Additional context**
It's my thinking that 9 times out of 10, the Lighthouse service (aka, Keptn Quality Gates, KQG, etc., etc) will be deploy to fill the gap in an existing development lifecycle. This means that environments likely already exist, and thus the Keptn CLI should refrain from trying to create these namespaces.

**Comment by christian-kreuzberger-dtx** [comment]
Thanks for the report. This behaviour is implemented in our shipyard-service:
https://github.com/keptn/keptn/blob/17637cfe905d04350a5de76f2ec08689b1da30a1/shipyard-service/main.go#L195-L205

Right now the shipyard-service can NOT distinguish between a quality-gates only installation and a full installation.

The right place to do this would be the helm-service. We will see if this can easily be fixed, and we'll get back to you.
