### ISSUE TITLE
Improve JSON payload visualization

### ISSUE THREAD

**Issue by ermin-muratovic** [keptn/keptn#1420]
_JSON payload:_ The JSON payload of each event should be hidden and not that prominent. Maybe just show important meta-data of each event.

**Comment by christian-kreuzberger-dtx** [comment]
I also dislike the fact that everytime you click anywhere in the event, the json payload is expanded at the bottom.

I'd like to see a button/icon (e.g., https://barista.dynatrace.com/resources/icons/coding/ ) that opens a modal dialog when clicking it.

**Comment by christian-kreuzberger-dtx** [comment]
I also dislike the fact that everytime you click anywhere in the event, the json payload is expanded at the bottom.

I'd like to see a button/icon (e.g., https://barista.dynatrace.com/resources/icons/coding/ ) that opens a modal dialog when clicking it.

**Comment by christian-kreuzberger-dtx** [comment]
I also dislike the fact that everytime you click anywhere in the event, the json payload is expanded at the bottom.

I'd like to see a button/icon (e.g., https://barista.dynatrace.com/resources/icons/coding/ ) that opens a modal dialog when clicking it.
