### ISSUE TITLE
keptn cli :Keptn create service not accepting  Capital letters in Service Name

### ISSUE THREAD

**Issue by leonvzGit** [keptn/keptn#1421]
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
keptn 0.6.0
My customer has quite long service names which they capitalize for readability, when using the keptn cli statement to create a service (Quality Gates use case) it rejects service names that are capitalized for example keptn create service GetAllPointsHistoryRestProvider --project=foo

the service name is rejected.

**Describe alternatives you've considered**

**Additional context**

**Comment by christian-kreuzberger-dtx** [comment]
Thanks for the report. We will take a look at it.

**Comment by leonvzGit** [comment]
thanks, Christian

**Comment by agrimmer** [comment]
The keptn service name has to match the k8s service name.
k8s service names do not allow upper case letters, see https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names
Instead of capitalized letters, you can use dashes, i.e. "-"

**Comment by leonvzGit** [comment]
Thanks  @agrimmer , I will investigate this and get back to you, I will verify if the Dynatrace Detected name corresponds with this rule.

**Comment by leonvzGit** [comment]
This service is detected by dynatrace as :
Detected name GetAllPointsHistoryRestProvider , and is also tagged with the k8s namespace.

I do not have access to the k8s env , so I cannot confirm anything from a k8s perspective. I will chat to the DevOps Engineers tomorrow to get the name in k8s

**Comment by christian-kreuzberger-dtx** [comment]
Dynatrace does not only use the K8s service name, but the class-names etc... of the implemented service. For instance, the **carts** microservice that we onboard in our tutorial is not detected as "carts" in Dynatrace, but as multiple entities:

* ItemsController
* VersionController
* HealthController

**Comment by leonvzGit** [comment]
ok this is good to know , thanks for the information.👍

**Comment by christian-kreuzberger-dtx** [comment]
As @agrimmer has explained, we're depending on K8s about service names. Therefore I'm closing this issue.

**Comment by leonvzGit** [comment]
ok , I accept that you're closing this but: what if I will only ever use the Quality Gates use Case. My customer has multiple k8s clusters with 100s of services each... We have tested installing keptn on one of their existing clusters and it failed. Is there some literature on deploying on existing K8s clusters

**Comment by christian-kreuzberger-dtx** [comment]
If you just use quality-gates, I recommend setting up a fresh K8s cluster (this could even run on a [VM using Microk8s](https://keptn.sh/docs/0.6.0/reference/microk8s/)). You can install it on the same cluster in most cases (though see issue #1417 for a limitation - we are currently working on a fix for that), though I don't see a benefit from doing that.

There is no dedicated literature for deploying on a K8s cluster with existing services. We recommend going through the official tutorial for quality-gates: https://keptn.sh/docs/0.6.0/usecases/quality-gates/

Last but not least: If you have (follow-up) questions or ideas, please come to our [slack space](https://github.com/keptn/community#communication) and discuss them with us!
