### ISSUE TITLE
WebSocket communication between CLI and GitHub Service

### ISSUE THREAD

**Issue by bacherfl** [keptn/keptn#143]
Allow the CLI to receive live updates during the onboarding process.
Proposed solution:
1. CLI sends command to control-service
1. Control service creates a new WebSocket topic via a WebSocket service in the keptn namespace
1. Control Service pushes the command sent by the CLI into the queue, together with a topic ID
1. Control service sends the connection information to the CLI
1. GitHub Service executes the command and sends updates to the WebSocket server
1. CLI connects to WebSocket service, based on the connection information, and receives updates during the command execution

**Comment by dirkwall** [comment]
dup of #203
