### ISSUE TITLE
Bridge shows "0 more ..." for labels/stages

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1442]
When accessing the dashboard of the Bridge it currently shows this information:

![Screenshot from 2020-03-03 15-08-54](https://user-images.githubusercontent.com/56065213/75783487-efd24580-5d60-11ea-8bd9-e2f37e255f50.png)

I believe the "0 More..." is wrong at this place.

This error also sometimes occurs in the project screen:

![Screenshot from 2020-03-03 15-09-36](https://user-images.githubusercontent.com/56065213/75783549-0b3d5080-5d61-11ea-8873-10f56a5db95b.png)

I've seen it occur especially when there was no stage defined yet (e.g., when only the initial configuration-change event without a stage was available).

**Comment by ermin-muratovic** [comment]
This is a bug in `@dynatrace/barista-components`
https://github.com/dynatrace-oss/barista/issues/695
