### ISSUE TITLE
Show SLOs as integers or floats?

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1457]
Right now in Keptn's Bridge EAP we are showing all numbers as integers:

![Screenshot from 2020-03-06 12-15-31](https://user-images.githubusercontent.com/56065213/76079058-32d02b00-5fa4-11ea-9ef0-9853f67289ac.png)

![Screenshot from 2020-03-06 12-13-17](https://user-images.githubusercontent.com/56065213/76078903-e258cd80-5fa3-11ea-82b1-201e7775fe66.png)

We acknowledge that some numbers might require us to show floating points, but we also see that some numbers are nicer displayed as integers.

We would like to collect some feedback from everyone regarding this issue.

Should we display floating points? integers? Should this be dynamic? E.g., if the number is less than 100, we should display one decimal place, if it is less than 10 we display two decimal places, etc...

**Comment by Dynatrace-BrianWilson** [comment]
I vote for dynamic float, though I'd say <=100 >0  two places to keep some visual consistency. 0 and down 3 or more

**Comment by robertjahn** [comment]
related to these charts if you are in the code.....

1) can you sort the SLI list. Right now there appears to be no sort.

![image](https://user-images.githubusercontent.com/24907089/76660795-2291f000-6550-11ea-94ea-f3ee6503ce9b.png)

2) provide the data label in the charts. even if it is just a hover over.

![image](https://user-images.githubusercontent.com/24907089/76660909-6edd3000-6550-11ea-8e03-e697b28d4c40.png)

**Comment by christian-kreuzberger-dtx** [comment]
I've deleted the last comment. Please keep discussion in this issue regarding the integer/floating point topic. Thank you.
