### ISSUE TITLE
Azure DevOps git repos supported?

### ISSUE THREAD

**Issue by bitsofinfo** [keptn/keptn#1494]
are Azure DevOps git repos supported?

**Comment by agrimmer** [comment]
Thank you for your question!
Keptn allows any derivative of Git. 
May we ask you to test it and extend our documentation for Azure DevOps Git, i.e. make a PR?
https://keptn.sh/docs/0.6.0/manage/project/#select-git-based-upstream
https://github.com/keptn/keptn.github.io/blob/master/content/docs/0.6.0/manage/project/index.md

In the future, we ask you to put your questions into our Slack channel:
https://join.slack.com/t/keptn/shared_invite/enQtNTUxMTQ1MzgzMzUxLWMzNmM1NDc4MmE0MmQ0MDgwYzMzMDc4NjM5ODk0ZmFjNTE2YzlkMGE4NGU5MWUxODY1NTBjNjNmNmI1NWQ1NGY
