### ISSUE TITLE
Prometheus service: Handle queries for which no data points are available

### ISSUE THREAD

**Issue by bacherfl** [keptn/keptn#1496]
Currently, if we receive a result from prometheus containing an empty array, such as the following:

```
{
    "status": "success",
    "data": {
        "resultType": "vector",
        "result": []
    }
}
```

we assume that the value for the queried metric is 0. Example: if we query the error rate, and the error rate of the service was 0, the prometheus API will send the object listed above.
However, for other queries, such a result might have different semantics ( i.e. it could mean that no data is available and we cannot retrieve a value.

**Comment by christian-kreuzberger-dtx** [comment]
Not a Keptn issue, but a Prometheus-Service issue -> https://github.com/keptn-contrib/prometheus-service/issues/41
