### ISSUE TITLE
Add data labels for the Keptn Bridge Evaluation done line graphs

### ISSUE THREAD

**Issue by robertjahn** [keptn/keptn#1501]
**Is your feature request related to a problem? Please describe.**
I would like to see that actual values in the graph for the previous builds. Now I need to click on each result and view in the table.  

**Describe the solution you'd like**
Perhaps have a checkbox to toggle showing the data points.  There might be too much data when there are multiple SLOs being displayed.  This is more relevant for a viewing a single SLO.

**Describe alternatives you've considered**
None

**Additional context**
Mockup
![image](https://user-images.githubusercontent.com/24907089/76702352-7e1ec380-669f-11ea-87e5-f477817f25f1.png)

**Comment by christian-kreuzberger-dtx** [comment]
Thanks for the suggestion, this is currently Work in Progress and we will come up with a better solution for presenting SLI historic values.

**Comment by johannes-b** [comment]
I need to verify, but you can now use the label `buildId:xyz` to set the name `xyz` on the horizontal axis.
