### ISSUE TITLE
Refactor API-Service to only act as a proxy for other services

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1510]
At the moment our API-Service implements many things that are already implemented in the backend services such as the configuration-service.

In an ideal scenario we could switch to a more proxy-like approach, where the API-service only proxies certain endpoints of the backend services.

Important: Swagger-UI in API still needs to show the exposed endpoints, without having to duplicate code!

Please research this and create a prototype.

**Comment by grabnerandi** [comment]
Important use case would be to retrieve the evaluation results that are currently shown in the heatmap in the bridge. If we provide a new API Endpoint that allows a user to retrieve the e.g: last X results for a service and stage then our partners / users can implement their own heatmap visualization in external tools such as Azure DevOps, Jenkins ...

**Comment by agrimmer** [comment]
@grabnerandi This issue addresses no new end-points instead we would like to directly access the API from e.g. the `configuration-service`.

**Comment by grabnerandi** [comment]
ok - @agrimmer -  shall I create a new issue then?

**Comment by agrimmer** [comment]
Can you please formulate a mini KEP for this and make a PR? https://github.com/keptn/enhancement-proposals

**Comment by agrimmer** [comment]
One possible solution would be to make the routing in the VirtualService and/or Ingress.
See https://github.com/keptn/keptn/blob/feature/1510/refactor-api-service/installer/manifests/keptn/keptn-api-virtualservice.yaml
for a possible implementation of the VS.

Pros:
- No new service for distributing the events
- Easy to configure and maintain

Drawbacks:
- No centralized authentication. Therefore, also other services like the `configuration-service` have to implement the authentication.

**Comment by agrimmer** [comment]
Research Outcome:
- We introduced an NGINX as new k8s deployment and service. This NGINX allows to route the traffic and ensures that all requests are authenticated using the /auth endpoint of the `api-service`.
- The `api-service` now does not implement endpoints of the `configuration-service` anymore.
- The `configuration-service` is exposed to the public. Endpoints that are not intended to be used from the public (e.g. deleting a project) are marked and the description is accordingly adapted.

**Architecture for the full installation:**
![full](https://user-images.githubusercontent.com/10980861/78262547-03f49880-7501-11ea-9974-0f70bee617c4.png)

**Architecture for the quality gates installation:**
![qg](https://user-images.githubusercontent.com/10980861/78262560-09ea7980-7501-11ea-8720-edf8d3234766.png)

**Comment by christian-kreuzberger-dtx** [comment]
Nicely done.

The image and the description should be put into the [docs/](docs/) folder.
