### ISSUE TITLE
Allow specify an upstream git for existing projects

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#1517]
As it is today you can only define a remote-git-url during keptn create project. I have had users that were not aware of that option or forgot about it. In order to define an upstream git they then had to start from scratch by creating a new project again and loosing their work on their current project.

I suggest to provide an option to set the upstream git even for existing projects. something like
keptn update project --git-user=xxx --git-token=yyy --git-remote-url=zzz

**Comment by agrimmer** [comment]
Valid point! 
For a quick improvement, we could simply swap the without Git- and with Git-option. See https://keptn.sh/docs/0.6.0/usecases/onboard-carts-service/#create-project-sockshop
If you like it, can you please file an PR on keptn/keptn.github.io?

**Comment by christian-kreuzberger-dtx** [comment]
configuring the upstream afterwards seems a better solution to me.

I'd say ``keptn update project --git-user=xxx --git-token=yyy --git-remote-url=zzz`` sounds good.

**Comment by johannes-b** [comment]
The assumption for implementing this issue: We assume that the repository is empty.

**Comment by checkelmann** [comment]
Will take this one
