### ISSUE TITLE
Mongodb fails on start with certain PVs

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#1519]
**Environment**
* Keptn Version (`keptn version`): 0.6.0 > upgrade to 0.6.1
* Kubernetes Cloud Provider (e.g., GKE, AKS): Rancher
* Kubernetes version (`kubectl version`): v1.16.6

**Affected Component**
* [ x ] Datastore

**Describe the bug**
When running the upgrading job for 0.6.1, the job runs into a queue when importing the data from the old mongodb to the new mongodb. The problem is that the mongodb pod is not available. The logs of the pod show:
``` 
=> Waiting for MongoDB daemon up MongoDB shell version v3.6.3 connecting to: mongodb://127.0.0.1:27017/localhost 
2020-03-18T07:01:19.991+0000 W NETWORK [thread1] Failed to connect to 127.0.0.1:27017, in(checking socket for error after poll), reason: Connection refused 
2020-03-18T07:01:19.992+0000 E QUERY [thread1] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed : connect@src/mongo/shell/mongo.js:251:13 @(connect):1:6 exception: connect failed
```
When deploying the deployment manifest for mongodb from Keptn 0.6.0, the pod is available and working fine. 

**To Reproduce**
- Exactly this problem: Install Keptn 0.6.0 and run the 0.6.1 upgrade job. 
- The same problem may occur when just installing 0.6.1 on a Rancher as specified above. 

**Expected behavior**
MongoDB deployment in keptn-datastore is working fine so that the upgrade job runs through.

**Comment by agrimmer** [comment]
Closing this issue as we will soon release Keptn 0.7.0

**Comment by agrimmer** [comment]
The reason why mongodb cannot start is as follows:
MongoDB tries to set `mongodb` as the owner for the files in `/var/lib/mongodb/data`.
However, this is not allowed for some PVCs with the assigned rights.

Therefore, as a workaround for this issue, we provide an image that runs MongoDB as root.
You can update the image with 
`kubectl set image deployment/mongodb mongodb=keptn/mongodb-privileged:latest -n keptn`

**Comment by grabnerandi** [comment]
Hi. I assume the kubectl command should for for -n keptn-datastore instead of -n keptn?

**Comment by thschue** [comment]
> Hi. I assume the kubectl command should for for -n keptn-datastore instead of -n keptn?
This is true for keptn 6.x, in 7.0 it will be in the keptn namespace
