### ISSUE TITLE
Duplicate entries in Bridge

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#1520]
**Environment**

* Client OS (e.g., Linux, OSX, Windows): mac os (austrian date settings)
* Keptn Version (`keptn version`): 0.6.1
* Kubernetes Cloud Provider (e.g., GKE, AKS): gke
* Kubernetes version (`kubectl version`): not relevant

**Affected Component**

* [ ] Docs
* [ ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [x] Bridge
* [ ] Gatekeeper
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**
When the bridge is auto-fetching the latest events, some of them are duplicated.

**To Reproduce**
Start a deployment and open the bridge.
You will see some of the events are duplicated, like in this screenshot:
![image](https://user-images.githubusercontent.com/7677092/76941087-b15d8e80-68fb-11ea-846c-88fb5049fa57.png)

**Expected behavior**
No duplicated events.

**Additional context**

I am running Chrome 80.x on Mac OS 10.14.6 with these regional settings:
![image](https://user-images.githubusercontent.com/7677092/76941175-d7832e80-68fb-11ea-9ed4-f3d18b6b0948.png)

**Comment by jetzlstorfer** [comment]
Thanks to @ermin-muratovic - we found the issue!
My local time was about 40 seconds behind the correct time, which caused some events to be duplicated:
- the left hand side of the bridge has a auto-reload of 30 seconds, so sometimes new events showed up twice here
- the right hand side has a auto-reload of 10 seconds causing about 2-4 events to be duplicated, depending on the velocity of new events coming in.

We fixed it for now by setting the correct time on my local machine. 
However, a more generic fix should be taken for consideration since this could happen to any other user as well. Also, if the local time would be in the future, events could be lost (or at least not shown until a manual reload of the bridge).

**Comment by ermin-muratovic** [comment]
I tested using the response time provided in the headers of the API request, instead of using the Date functionality in the browser. But this is not working, because the response time in the headers is also depending on the browser (client) time setting and does not represent the server time.

I will provide the timestamp in the response in the bridge's node application, so we don't have any breaking changes, since that is an internal API only used by the bridge itself.
