### ISSUE TITLE
Configure Monitoring for Dynatrace should configure k8s Monitoring

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#1524]
Right now keptn configure monitoring dynatrace installs the OneAgent, creates tags, management zones and dashboards. 
One of our users gave us feedback that it should additionally setup Kubernetes Monitoring by using the kubernetes configuration API of Dynatrace. This would automate an additional step

**Comment by christian-kreuzberger-dtx** [comment]
This is issue is related to the [Dynatrace-Service](https://github.com/keptn-contrib/dynatrace-service) which is hosted in the keptn-contrib org. Please raise the issue there, as we can not move it. Thanks.
