### ISSUE TITLE
setupScript does not check for success criteria

### ISSUE THREAD

**Issue by AloisReitbauer** [keptn/keptn#153]
--------------------------
Setup Infrastructure 
--------------------------
Fetching cluster endpoint and auth data.
ERROR: (gcloud.container.clusters.get-credentials) ResponseError: code=404, message=Not found: projects/sai-research/zones/us-central1-a/clusters/XXXXXXXXXXXXX-research_us-central1-a_XXXXXX.
No cluster named 'gke_sai-research_us-central1-a_keptn-alois' in sai-research.
clusterrolebinding.rbac.authorization.k8s.io/dynatrace-cluster-admin-binding created
namespace/cicd created
namespace/keptn created
configmap/docker-registry created
persistentvolumeclaim/docker-registry created
Error from server (AlreadyExists): error when creating "../manifests/container-registry/k8s-docker-registry-configmap.yml": configmaps "docker-registry" already exists
deployment.extensions/docker-registry created
service/docker-registry created
Wait 100s for docker service to get public ip...

**Comment by bacherfl** [comment]
The script will now exit if the gcloud get-credentials command fails

**Comment by AloisReitbauer** [comment]
Should we close this one?

**Comment by bacherfl** [comment]
Yep, just made its way into the master branch
