### ISSUE TITLE
KQG only - helm service should not call helm init --client-only 

### ISSUE THREAD

**Issue by kristofre** [keptn/keptn#1532]
Your issue may already be reported! Please search on the [issue tracker](https://github.com/keptn/keptn/issues) before creating a new one.

**Environment**

* Keptn Version (`keptn version`): 0.6.1
* Kubernetes Cloud Provider (e.g., GKE, AKS): OpenShift

**Affected Component**

* [ ] Docs
* [ ] CLI
* [ ] Kubernetes Integration
* [X] Openshift Integration
* [X] Helm
* [ ] Istio
* [ ] Bridge
* [ ] Gatekeeper
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**

Installing KQG only on an OS cluster without direct internet access causes a crashloop on the helm-service pod due to the following: 
helm pod:
`pod/helm-service-6494857cd7-87t6p 0/1 CrashLoopBackOff  5  3m`
The logs show the following:
```
#  oc logs pod/helm-service-6494857cd7-87t6p
##########
branch: release-0.6.1
repository: https://github.com/keptn/keptn
commitlink: https://github.com/keptn/keptn/commit/723eab650d3e08ce5fc8d5b96b003cd4c05862da
repolink: https://github.com/keptn/keptn/tree/723eab650d3e08ce5fc8d5b96b003cd4c05862da
travisbuild: https://travis-ci.org/keptn/keptn/jobs/663467853
timestamp: 20200317.1328
##########
2020/03/20 12:01:07 Error executing command helm init --client-only: exit status 1
Creating /root/.helm
Creating /root/.helm/repository
Creating /root/.helm/repository/cache
Creating /root/.helm/repository/local
Creating /root/.helm/plugins
Creating /root/.helm/starters
Creating /root/.helm/cache/archive
Creating /root/.helm/repository/repositories.yaml
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com
Error: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Get https://kubernetes-charts.storage.googleapis.com/index.yaml: dial tcp: lookup kubernetes-charts.storage.googleapis.com on 10.99.73.17:53: server misbehaving
```
This is due to the openshift cluster not having direct internet access. 

**To Reproduce**

Install KQG only on an OpenShift cluster without direct internet access.

**Expected behavior**
KQG only can be installed on an OS cluster without direct internet access.

**Current behavior**

KQG cannot be installed on an OS cluster without direct internet access.

**Comment by christian-kreuzberger-dtx** [comment]
This issue can be reproduced locally using
```console
docker run --rm --network none keptn/helm-service:0.6.1 
```

**Comment by christian-kreuzberger-dtx** [comment]
I've created a fix for this, could you please try out the following image: ``keptn/helm-service:0.6.1-bug1532``

You should be able to change the image using the following command:
``kubectl -n keptn set image deployment/helm-service helm-service=keptn/helm-service:0.6.1-bug1532 --record``
