### ISSUE TITLE
Validate Keptn to work on EKS 1.15

### ISSUE THREAD

**Issue by robertjahn** [keptn/keptn#1538]
**Is your feature request related to a problem? Please describe.**
AWS's newest EKS version is 1.15.  As part of this and 1.14 the extra step to install CoreDNS is not required.

**Describe the solution you'd like**
Validate and update the Keptn Docs on this page: https://keptn.sh/docs/0.6.0/installation/setup-keptn/ to not mention the extra step to install CoreDNS

**Describe alternatives you've considered**
None

**Additional context**
https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html
https://docs.aws.amazon.com/eks/latest/userguide/getting-started-eksctl.html

**Comment by christian-kreuzberger-dtx** [comment]
@jetzlstorfer @grabnerandi can one of you please verify that and update our docs?

**Comment by grabnerandi** [comment]
FYI - @jetzlstorfer will validate!

**Comment by jetzlstorfer** [comment]
Thanks Rob for pointing this out. I've validated with Keptn 0.6.1 full installation and EKS version 1.14. It is working as @robertjahn described. 
Will update the docs.

**Comment by jetzlstorfer** [comment]
https://github.com/keptn/keptn.github.io/pull/477

**Comment by jetzlstorfer** [comment]
Website is now updated. Closing issue.
