### ISSUE TITLE
Pass project name when querying event trace

### ISSUE THREAD

**Issue by bacherfl** [keptn/keptn#1540]
Currently, the bridge retrieves the events for a given contextID by loading all events with that ID from the mongodb-datastore. Due to the changes made in #1490, the bridge should, in addition to the contextID also pass the name of the project in the query, so the mongodb-datastore knows which collection to load the events from.

**Comment by johannes-b** [comment]
Related to #1490

**Comment by johannes-b** [comment]
#1490
