### ISSUE TITLE
MongoDB Directory Permissions Causes API to fail

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [keptn/keptn#1546]
**Environment**

AWS EC2 instance running quality gates scenario on minikube with keptn exposed on the public IP.
Instance Creation Instructions: https://github.com/grabnerandi/keptn-qualitygate-examples/blob/master/aws_instructions.txt

* Client OS (e.g., Linux, OSX, Windows): Ubuntu
* Keptn Version (`keptn version`): CLI version: master+20200311.1053
* Kubernetes Cloud Provider (e.g., GKE, AKS): AWS EC2 Instance with Minikube
* Kubernetes version (`kubectl version`):
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

**Affected Component**

* [ ] Docs
* [x] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [ ] Bridge
* [ ] Gatekeeper
* [x] Datastore
* [x] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**
Calls to `get event` fail with a timeout message, both from the CLI and API. The API pod logs show: `{"timestamp":"2020-03-24T00:52:58.421853364Z","logLevel":"ERROR","message":"context deadline exceeded"}`

Looking at the Mongo pod, I see:
```
kubectl get pods -n keptn-datastore
NAME                                             READY   STATUS    RESTARTS   AGE
mongodb-578b4d8bcd-dhgb8                         0/1     Error     45         4d2h
```

Looking a the `mongdb` logs:
```
$ kubectl logs -n keptn-datastore mongodb-578b4d8bcd-dhgb8
=> sourcing /usr/share/container-scripts/mongodb/pre-init//10-check-env-vars.sh ...
=> sourcing /usr/share/container-scripts/mongodb/pre-init//20-setup-wiredtiger-cache.sh ...
=> sourcing /usr/share/container-scripts/mongodb/pre-init//30-set-config-file.sh ...
=> sourcing /usr/share/container-scripts/mongodb/pre-init//35-setup-default-datadir.sh ...
ERROR: Couldn't write into /var/lib/mongodb/data
CAUSE: current user doesn't have permissions for writing to /var/lib/mongodb/data directory
DETAILS: current user id = 184, user groups: 184 0
stat: failed to get security context of '/var/lib/mongodb/data': No data available
DETAILS: directory permissions: drwxr-xr-x owned by 0:0, SELinux: ?
```

**Comment by christian-kreuzberger-dtx** [comment]
Hi,

for troubleshooting purposes, please use an official Keptn version (e.g., 0.6.1), install it with that version on Minikube and provide  the detailed `keptn install` command.

We have Keptn Quality Gates running fine on Minikube 1.2, which is the only version that we currently support.

**Comment by Dynatrace-Adam-Gardner** [comment]
Hi Christian,
Everything is OK during a `minikube stop && sudo minikube start` but I get a `CrashLoopBackoff` in the `mongodb` pod in `keptn-datastore` after a reboot.

Here's my current installation script (note usage of `0.6.1`):

```
# Running on AWS Ubuntu Server 18.04 t3.medium 10GB HDD
sudo apt-get update -y
sudo apt-get install bc docker.io-y
curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
chmod +x kubectl && sudo mv kubectl /usr/local/bin/kubectl
curl -sL https://get.keptn.sh | sudo -E bash
curl -Lo minikube https://storage.googleapis.com/minikube/releases/v1.2.0/minikube-linux-amd64 && chmod +x minikube && sudo cp minikube /usr/local/bin/ && rm minikube
sudo minikube start --cpus 2 --memory 4000 --vm-driver none
sudo chown -R $USER $HOME/.kube $HOME/.minikube
echo '{"clusterName": "minikube"}' > creds.json
keptn install --platform=kubernetes --use-case=quality-gates --gateway=NodePort --creds=creds.json --verbose
```

**Comment by JoelStuart** [comment]
Hi team,

I can replicate Adam's problem with 0.6.1 and Minikube 1.2 with Ubuntu 18.04. This is a day-2 problem for me, where as soon as the host is restarted the MongoDB pod can no longer start.

See https://github.com/kubernetes/minikube/issues/1184

and Minikube 'none' driver: https://minikube.sigs.k8s.io/docs/reference/drivers/none/

I tried MicroK8s instead and had no such problems.

**Comment by Dynatrace-Adam-Gardner** [comment]
Thanks Joel. Confirmed that pods run successfully after `sudo microk8s stop && sudo microk8s start`.

Can also confirm that all pods run successfully after a machine reboot on microk8s (t3.medium Ubuntu 18.04 w/ 10GB HDD).

Creation script for this machine:

```
sudo apt-get update -y
sudo snap install microk8s --classic
sudo iptables -P FORWARD ACCEPT
sudo microk8s.enable dns
sudo microk8s.enable dns ingress
sudo microk8s.enable storage
sudo /snap/bin/microk8s.config > /home/$USER/.kube/config
export KUBECONFIG=./kubeconfig
curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
chmod +x kubectl && sudo mv kubectl /usr/local/bin/kubectl
kubectl apply -f https://raw.githubusercontent.com/google/metallb/v0.8.3/manifests/metallb.yaml
curl -sL https://get.keptn.sh | sudo -E bash
echo "{\"clusterName\": \"$(kubectl config current-context)\"}" > creds.json
keptn install --platform=kubernetes --use-case=quality-gates --gateway=NodePort --creds=creds.json
```

**Comment by Dynatrace-Adam-Gardner** [comment]
`/var/lib/mongodb/data` is owned by `root:root` rather than (presumably) `mongodb:mongodb`.

Perhaps all that's needed here is a `chown` in [mongodb-datastore Dockerfile](https://github.com/keptn/keptn/blob/master/mongodb-datastore/Dockerfile) to `mongodb`?

**Comment by christian-kreuzberger-dtx** [comment]
Interesting behaviour, we will dig into that. Thanks for the troubleshooting! And yeah, Microk8s seems to work much better :D

**Comment by christian-kreuzberger-dtx** [comment]
I still believe we should investigate this. Adding `next-sprint` label so we get this done.

**Comment by checkelmann** [comment]
Hi,

I've got the same problem running minikube (1.10.1) on ubuntu 20.04, as development Environment. So I ended up with a script which is automatically destroying the minikube cluster, spin up a new minikube, install keptn and configuring test projects.

So this is not really a keptn issue, it's a minikube host path provisioner error.

There is a really dirty workaround for this. Add the following initContainer to the mongodb deployment...

```
      initContainers:
        - name: volume-mount-hack
          image: busybox
          command: ["sh", "-c", "chown -R 184:184 /var/lib/mongodb/data"]
          volumeMounts:
          - name: mongodata
            mountPath: /var/lib/mongodb/data
```

This container will be executed before the actual mongodb container and will fix the permissions for you.

This workaround should NOT be included within the keptn installation as IMHO this is really not a keptn issue.

Now I ended with using K3s ;) which is much more reliable.

Cheers!

**Comment by johannes-b** [comment]
As Christian mentioned, K3s is (now) the preferred way of running Keptn on a standalone-K8s distribution. 

Nevertheless, I summarized the discussion of this issue into a troubleshooting guide for the keptn/docs **Troubleshooting** page.

**Comment by debuggerpk** [comment]
Hi @johannes-b i am running k3d on osx. I am getting the same error.
