### ISSUE TITLE
Notify user of new available Keptn Bridge in UI

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#1547]
We are doing a great job of putting our new versions of the Keptns bridge via the [Early Access Program](https://keptn.sh/docs/0.6.0/reference/keptnsbridge/#early-access-version-of-keptn-s-bridge).

However, a user should be informed about a new available version when they are navigating through their currently installed Keptn Bridge. 

My suggestions is that we put a json file on our keptn.sh website that contains the latest version of the Keptn Bridge in EAP - could looks something like this:
```
https://keptn.sh/latestversions.json
{
  "bridge" : "bridge:0.6.1",
  "bridge_eap" : "bridge:0.6.1.EAP2"
}
```` 

If the bridge pulls this file on a regular basis and there is a new EAP entry with a version that doesn't match the current version of the bridge, the end-user should get informed. Here are two options
1. Show it in the text next to the current version and make that text link to the EAP Doc page, e.g.: 0.6.1 (get latest)
1. Show a banner at the top indicating that there is a new bridge available
![image](https://user-images.githubusercontent.com/675886/77405302-43114400-6db3-11ea-9090-c3b620284d7f.png)

This approach with the version.json is also easily extendable for other Keptn components and allows us to also notify about available updates of official releases and EAPs.

**Comment by christian-kreuzberger-dtx** [comment]
We could do this via our [version.json](https://get.keptn.sh/version.json) file (which is stored here: https://github.com/keptn/get.keptn.sh/blob/master/src/version.json ). 

The new format of the file would then be
```json
{
    "cli": {
        "stable": [ "0.5.2", "0.6.1"],
        "prerelease": ["0.6.0-beta2"]
    },
    "bridge": {
        "stable": ["0.6.1"],
        "prerelease": ["0.6.1-EAP1"]
    }
}
```

We just need to figure out which version string we are going to use, as we do not generate version strings with EAP in them right now.

**Comment by agrimmer** [comment]
Agree, the [version.json](https://github.com/keptn/get.keptn.sh/blob/master/src/version.json) file should be also used for the bridge.

**Comment by johannes-b** [comment]
A user must be able to disable this feature. The proposed suggestion is a feature flag in the user menu: 
![image](https://user-images.githubusercontent.com/729071/79872476-1f5b1100-83e6-11ea-8fb2-d94bfd6089f0.png)

To-be-defined:The message shown when the feature is on/off.

**Comment by johannes-b** [comment]
Based on feedback from @checkelmann, it would make sense to not only enable/disable version check, but also to select the kind of version (e.g., EAP, stable, alpha, etc.) you want to get notified for. For example by using a check-box: 
- Version check: enabled 
  - [ ] Keptn Bridge - *EAP*
  - [ ] Keptn Bridge - *Stable*
  - [ ] Keptn - *Beta*
  - [ ] Keptn - *Stable*

For this feature, I would like to create a follow-up issue.
