### ISSUE TITLE
Create a support-archive that contains logfiles and other relevant information for troubleshooting

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1549]
The CLI should create a support archive using the following steps:

1. Collect information about local OS and Keptn CLI version
1. API URL
1. Check if API is reachable
1. Check if kubectl context is set to the correct Keptn installation // https://keptn.sh/docs/0.6.0/reference/troubleshooting/#verify-kubernetes-context-with-keptn-installation
1. kubectl version
1. Log and status of installer (if available) // see https://keptn.sh/docs/0.6.0/reference/troubleshooting/#troubleshooting-the-installer
1. List of namespaces
1. List of configmaps and secrets (though not their content!) within the keptn namespace
1. Keptn Domain
1. List of all deployments and the deployed image name/tag in namespaces keptn (e.g., `kubectl -n keptn get deployments -owide`) as well as keptn-datastore
1. Check if all pods are up and running // see https://keptn.sh/docs/0.6.0/reference/troubleshooting/#verifying-a-keptn-installation
1. Log output of all services in the namespaces keptn and keptn-datastore
1. If possible, list of all projects, services and stages
1. Maybe some Kubernetes events? `kubectl get events  --sort-by='.metadata.creationTimestamp' -n keptn` and `kubectl get events  --sort-by='.metadata.creationTimestamp' -n keptn-datastore`
1. Maybe some Kubernetes metadata? `kubectl get nodes` and `kubectl describe nodes`

All of this should be packed into a support-archive (e.g., a zip file). We need to alert the user that this support archive might contain personal or secret information, and that they should review the archive before sending it to anyone.

# Definition of Done

- [x] User gets a warning if the kubectl context does not match the configured keptn api
- [x] User can use `keptn` CLI to create a support archive of the Kubernetes cluster that they are currently connected to.
- [x] User can manually inspect the support archive
- [ ] Documentation about the support archive is in the trouble shooting guide
- [x] User gets informed about the Slack channel and to get support there.

**Comment by grabnerandi** [comment]
This is great. The most important thing are the outputs we are always asking - but I think you have all of them covered, e.g: deployed pods & status, logs of pods
The CLI should capture all this and zip it up into a single file so that it is easy to send for the user
