### ISSUE TITLE
Extend CLI or Swagger UI to generate curl commands for cloud events

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#1551]
In order to integrate with Keptn on CloudEvent level, e.g: calling the REST API, etc. one has to figure out the exact cloud-native event structure and the necessary fields.

One option is to open up the Keptns Bridge and look at previously sent events - then copy/paste and modify them to your needs. It would be very helpful to make this easier for users to get the CURL command for sending a specific CloudEvent that contains all the relevant fields.

_Here are two options I have in mind:_
**1. Swagger UI:**
Not sure if this is possible - but - if the Swagger UI could be extended to not only test the POST /event but also provide an option to test the individual CloudEvents (config change, deployment-finished ...) where the user simply fields out all necessary fields and then gets the actual command. This would be very helpful as someone that wants to know how the CloudEvents needs to look like.

**2. Keptn CLI:**
Another option could be to extend the CLI and provide a `generate-event` command. Here is an example:
```
$ keptn generate-event start-evaluation --project=PROJECTNAME --stage=STAGE --service=SERVICENAME --timeframe=[duration]m --start=[2019-10-24T10:17:12]
```
This would be similar to the send-event, but instead of sending it, it could simply print out the CloudEvent or the full CURL command.
```
POST http://api.keptn.mykeptndomain.com/events
Content-Type: application/json
X-token: YOURTOKEN

{
  "type": "sh.keptn.event.start-evaluation",
  "data": {
   ...
  }
```

This would be a very convenient way for end-users to start building integrations with Keptn.

**Comment by agrimmer** [comment]
This issue contains #1550 

I see the need for this functionality. 
Another option how we could ease the integration would be to improve the examples in our [spec](https://github.com/keptn/spec/blob/master/cloudevents.md)
