### ISSUE TITLE
Smart default when WebSocket communication is not possible

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#1554]
**Problem:** When a Keptn-service can not open a WebSocket communication, it stops working. 

**Proposed solution:** When a Keptn-service can not open a WebSocket communication to the API component, the service should log this problem and continue its functionality. In other words, a WebSocket communication should be optional and not mandatory for a service to work.  

_Example:_
When executing the command `keptn create project xyz --shipyard=shipyard.yml` -> It is okay when the user does not see the log messages in the shell, but it is a problem when the project is not created. 

*The services that need to be checked:*
- shipyard-service
- helm-service
- dynatrace-service
- prometheus-service

**Definition of Done:**
- [ ] Implementation of the proposed solution

**Comment by christian-kreuzberger-dtx** [comment]
btw, we do have the `--suppress-websocket` option for this

**Comment by agrimmer** [comment]
@johannes-b describes the perspective of the keptn-service, i.e. shipyard-service, helm-service, dynatrace-service, etc.
The option `--suppress-websocket` is only for the CLI.

**Comment by christian-kreuzberger-dtx** [comment]
Thanks for clarification, I was reading it too fast :)
