### ISSUE TITLE
Keptn Core (CLI): Implement 'keptn configure bridge' command 

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#1560]
After issue #1153 is implemented, this has to be done to provide the following user experience (and definition of done). 

As a user, I can use the Keptn CLI to:
- expose Keptn's Bridge: `keptn configure bridge –action=expose` 
  - Output: Link to Keptn's Bridge:`http://bridge.keptn.xxx.xip/`
- lockdown Keptn's Bridge: `keptn configure bridge –action=lockdown`

The CLI should not execute any kubectl commands in this case, but call the API. The API is then responsible for executing kubectl commands.

**Comment by robertjahn** [comment]
Include the verb `get bridge` or `describe bridge` to get the details for the setup (i.e. image version and URL)
