### ISSUE TITLE
keptn configure monitoring via API

### ISSUE THREAD

**Issue by kristofre** [keptn/keptn#1563]
**Is your feature request related to a problem? Please describe.**
In some environments, access to the keptn CLI is not always possible.
It is possible to create project/service and upload sli/slo via the API, however one missing piece is the ability to initiate the `keptn configure monitoring dynatrace --project=XXX` command via the API

**Describe the solution you'd like**
An endpoint to configure monitoring

**Comment by christian-kreuzberger-dtx** [comment]
configure monitoring is implemented as a cloud-event.
You can find the spec here:
https://github.com/keptn/spec/blob/master/cloudevents.md#configure-monitoring

You can find the implementation as it is done in the CLI here:
https://github.com/keptn/keptn/blob/0.6.1/cli/cmd/configure_monitoring.go#L85-L109
