### ISSUE TITLE
CLI: Use k8s golang library instead of kubectl commands

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1566]
In Keptn 0.6.1 and older, the `keptn` CLI uses `kubectl` to install Keptn and to determine whether the installation was successful.

https://github.com/keptn/keptn/blob/b5e6be42dd069a7874e59a592bd67ddd07b904e2/cli/cmd/install.go#L201-L206

https://github.com/keptn/keptn/blob/b5e6be42dd069a7874e59a592bd67ddd07b904e2/cli/cmd/install.go#L351-L377

**Proposed refactoring:** Use the K8s golang library instead of `kubectl`. Consequently, the `keptn` CLI does not require `kubectl` locally.

**Comment by agrimmer** [comment]
I see the benefits of using the k8s libraries.
However, when using `kubectl`, it is likely that a user already has a valid kube/config.

**Comment by christian-kreuzberger-dtx** [comment]
Good point. I think having `kubectl` and a valid context will still be a requirement for `keptn install`.

**Comment by christian-kreuzberger-dtx** [comment]
Regarding this issue: The CLI only needs K8s for isntalling (and some other smaller things), nothing else. We can keep this issue open and on our list, but I think this problem will be resolved due to other means in the near future (e.g., using an operator).

**Comment by christian-kreuzberger-dtx** [comment]
This issue is no longer valid, cli has been restructured quite a bit.
