### ISSUE TITLE
Automate version numbers in Keptn-Service Deployments

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1573]
Right now we have to manually create PRs for all Kubernetes Manifests with the version numbers of each service.

For instance, if we create a release-branch (e.g., release-0.6.1), we have to adapt all versions (e.g., mongodb-datastore) from `:latest` to `:0.6.1`.

This process should be automated via an automatic Pull Request.

* **Resarch task:** Maybe we can do this one of the following GitHub actions?
  * https://github.com/marketplace/actions/find-and-replace
  * https://github.com/ad-m/github-push-action
  * https://github.com/vsoch/pull-request-action

* Implementation of the chosen automation approach

* Documentation (or comment) in the manifest files to indicate the part that gets automatically replaced

**Definition of Done**
- [x] Setting the image tag for Keptn core services is automated
- [x] Manual steps from the release process are removed

**Comment by johannes-b** [comment]
It is likely that in the future this automation step is not needed since an operator will take care of that task.

**Comment by johannes-b** [comment]
Closed due to the automation implemented by Keptn's Helm Chart.

**Comment by agrimmer** [comment]
This was implemented in https://github.com/keptn/keptn/pull/2064
