### ISSUE TITLE
Configuration-service: TotalCount of number of projects is wrong

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#1590]
When querying the list of projects, the API returns the correct list of projects but the returned `totalCount` is wrong. See image
<img width="1424" alt="Screen Shot 2020-04-03 at 11 36 04" src="https://user-images.githubusercontent.com/10980861/78347021-225da100-75a0-11ea-929f-8159eb2a7411.png">

**Comment by christian-kreuzberger-dtx** [comment]
Good catch. Relevant piece of code:
https://github.com/keptn/keptn/blob/1c21207b95eb2aee430bd680de9b1ad45daad8f3/configuration-service/handlers/project.go#L25-L54

**Comment by agrimmer** [comment]
Addressed with https://github.com/keptn/keptn/pull/1651
