### ISSUE TITLE
Typo in Reference Documentation for Creating Process Group Naming Rule in Dynatrace

### ISSUE THREAD

**Issue by johnrusaw** [keptn/keptn#1595]
Under the section "Create a process group naming rule in Dynatrace" (refer to https://keptn.sh/docs/0.6.0/reference/monitoring/dynatrace/#create-a-process-group-naming-rule-in-dynatrace) the third step says to set the Condition to "exits"...
`Condition: keptn_deployment (Environment) > exits`
when it should indicate "exists"...
`Condition: keptn_deployment (Environment) > exists`

**Comment by johannes-b** [comment]
Hi John, 
many thanks for the hint! I fixed the typo with this PR: https://github.com/keptn/keptn.github.io/pull/494
