### ISSUE TITLE
Switch GitHub integration to use Deploy Keys

### ISSUE THREAD

**Issue by AloisReitbauer** [keptn/keptn#1608]
**Is your feature request related to a problem? Please describe.**
Switch Github integration from personal access keys to Deployment keys.  This will also limit the access Keptn is getting on a specific GitHub account.  https://developer.github.com/v3/guides/managing-deploy-keys/#deploy-keys

**Comment by christian-kreuzberger-dtx** [comment]
I like the idea, as this restricts the potential issues that one could have when such a token/key is leaked by accident.

Some things to add from my side:

1. We can not "just remove" the old implementation. We need to add the new integration to the existing ones (see https://keptn.sh/docs/0.6.0/manage/project/#select-git-based-upstream ).
2. Generating deploy keys requires you to use yet another tool ([ssh-keygen](https://help.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#generating-a-new-ssh-key)), and we should link to the existing tutorials.
3. Authentication using SSH keys is nothing specific to GitHub. We should not make this implementation GitHub specific, but generic for all platforms.

Also, the following issues are related:
* https://github.com/keptn/keptn/issues/1335
* https://github.com/keptn/keptn/issues/1336
