### ISSUE TITLE
Add upstream repo support for Azure devops repos

### ISSUE THREAD

**Issue by robertjahn** [keptn/keptn#1618]
**Is your feature request related to a problem? Please describe.**
You get an error when trying the create a keptn project with azure devops as upstream repo

**Describe the solution you'd like**
Add upstream repo support for Azure devops repos like there is support for github

**Describe alternatives you've considered**
None

**Additional context**
Must deal with the Azure DevOps authentication that is required.

Here is error you get when trying the create a keptn project.
![image](https://user-images.githubusercontent.com/24907089/78709293-683ca100-78e1-11ea-9c8f-83050e54de9c.png)

**Comment by johannes-b** [comment]
Hi, I just want to double-check: Is the repository (configured for the upstream) initialized? (E.g., by adding an initial README.md)

**Comment by agrimmer** [comment]
I added instructions for Azure DevOps repos with this PR https://github.com/keptn/keptn.github.io/pull/530
