### ISSUE TITLE
Configure Monitoring Dynatrace fails on minikube and minishift

### ISSUE THREAD

**Issue by cjmckenna** [keptn/keptn#1619]
After installing keptn 0.6.1 and trying to configure monitoring for dynatrace, the following error comes in the dynatrace-service log.

{"timestamp":"2020-04-07T19:59:40.856309878Z","logLevel":"DEBUG","message":"Received event: sh.keptn.event.monitoring.configure"}
{"timestamp":"2020-04-07T19:59:40.947887455Z","logLevel":"INFO","message":"Configuring Dynatrace monitoring"}
{"timestamp":"2020-04-07T19:59:40.960072395Z","logLevel":"ERROR","message":"Could not create Dynatrace Helper: invalid or no Dynatrace credentials found"}
2020/04/07 19:59:40 http: panic serving 172.17.0.37:39994: runtime error: invalid memory address or nil pointer dereference
goroutine 19 [running]:
net/http.(*conn).serve.func1(0xc0005d2000)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x15e9920, 0x27a9e10)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/keptn-contrib/dynatrace-service/pkg/event_handler.ConfigureMonitoringEventHandler.configureMonitoring(0x1a297c0, 0xc00041c040, 0x1a7aa80, 0xc0006f44e0, 0x1535aa0, 0xc000233960, 0x1, 0x0, 0x1, 0xc0005aa160, ...)
	/go/src/github.com/keptn/dynatrace-service/pkg/event_handler/configure_monitoring.go:90 +0x14d
github.com/keptn-contrib/dynatrace-service/pkg/event_handler.ConfigureMonitoringEventHandler.HandleEvent(0x1a297c0, 0xc00041c040, 0x1a7aa80, 0xc0006f44e0, 0x1535aa0, 0xc000233960, 0x1, 0x0, 0x1, 0xc0005aa160, ...)
	/go/src/github.com/keptn/dynatrace-service/pkg/event_handler/configure_monitoring.go:64 +0x1a1
main.gotEvent(0x1a3ad00, 0xc0005c5980, 0x1a7aa80, 0xc0006f44e0, 0x1535aa0, 0xc000233960, 0x1, 0x0, 0x0)
	/go/src/github.com/keptn/dynatrace-service/cmd/main.go:67 +0x188
reflect.Value.call(0x15a8140, 0x1872f80, 0x13, 0x17c6129, 0x4, 0xc0005c5a40, 0x2, 0x2, 0xc0006c32b0, 0xc0005c5a70, ...)
	/usr/local/go/src/reflect/value.go:447 +0x461
reflect.Value.Call(0x15a8140, 0x1872f80, 0x13, 0xc0005c5a40, 0x2, 0x2, 0xc0005c5980, 0xc0006c3240, 0x1)
	/usr/local/go/src/reflect/value.go:308 +0xa4
github.com/cloudevents/sdk-go/pkg/cloudevents/client.(*receiverFn).invoke(0xc0005c4ea0, 0x1a3ad00, 0xc0005c5980, 0x1a7aa80, 0xc0006f44e0, 0x1535aa0, 0xc000233960, 0x1, 0xc0005c5860, 0x1a3ad00, ...)
	/go/pkg/mod/github.com/cloudevents/sdk-go@v0.0.0-20190509003705-56931988abe3/pkg/cloudevents/client/receiver.go:87 +0x224
github.com/cloudevents/sdk-go/pkg/cloudevents/client.(*ceClient).obsReceive(0xc000478300, 0x1a3ad00, 0xc0005c58c0, 0x1a7aa80, 0xc0006f44e0, 0x1535aa0, 0xc000233960, 0x1, 0xc0005c5860, 0xc0006c3498, ...)
	/go/pkg/mod/github.com/cloudevents/sdk-go@v0.0.0-20190509003705-56931988abe3/pkg/cloudevents/client/client.go:129 +0xef
github.com/cloudevents/sdk-go/pkg/cloudevents/client.(*ceClient).Receive(0xc000478300, 0x1a3ad00, 0xc0005c57a0, 0x1a7aa80, 0xc0006f44e0, 0x1535aa0, 0xc000233960, 0x1, 0xc0005c5860, 0xc00025c928, ...)
	/go/pkg/mod/github.com/cloudevents/sdk-go@v0.0.0-20190509003705-56931988abe3/pkg/cloudevents/client/client.go:117 +0xc7
github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http.(*Transport).obsInvokeReceiver(0xc0005798c0, 0x1a3ad00, 0xc0005c57a0, 0x1a7aa80, 0xc0006f44e0, 0x1535aa0, 0xc000233960, 0x1, 0x1, 0xc0005c5770, ...)
	/go/pkg/mod/github.com/cloudevents/sdk-go@v0.0.0-20190509003705-56931988abe3/pkg/cloudevents/transport/http/transport.go:335 +0x10c
github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http.(*Transport).invokeReceiver(0xc0005798c0, 0x1a3ad00, 0xc0005c5770, 0x1a7aa80, 0xc0006f44e0, 0x1535aa0, 0xc000233960, 0x1, 0x3, 0xc000048070, ...)
	/go/pkg/mod/github.com/cloudevents/sdk-go@v0.0.0-20190509003705-56931988abe3/pkg/cloudevents/transport/http/transport.go:319 +0xc5
github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http.(*Transport).ServeHTTP(0xc0005798c0, 0x1a36300, 0xc0005ec000, 0xc0005e8000)
	/go/pkg/mod/github.com/cloudevents/sdk-go@v0.0.0-20190509003705-56931988abe3/pkg/cloudevents/transport/http/transport.go:419 +0xab6
net/http.(*ServeMux).ServeHTTP(0xc000478340, 0x1a36300, 0xc0005ec000, 0xc0005e8000)
	/usr/local/go/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc0006f4340, 0x1a36300, 0xc0005ec000, 0xc0005e8000)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc0005d2000, 0x1a3ac40, 0xc00022e200)
	/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4

**Comment by grabnerandi** [comment]
Did some research on this yesterday with Chris. Turned out the problem was related to a typo in the DT_PAAS_TOKEN variable that was stored in the dynatrace secret.
It would be easier to troubleshoot if the error message would indicate this. Right now the message says "no or invalid configuration". if it would say "Couldnt find required configuration DT_PAAS_TOKEN in dynatrace secret" it would be easier to troubleshoot

**Comment by christian-kreuzberger-dtx** [comment]
Thanks for the report. I've moved the issue towards the dynatrace-service, as that's where the issue belongs to: https://github.com/keptn-contrib/dynatrace-service/issues/126

I'll close this issue here.
