### ISSUE TITLE
Have a color for the ICON in bridge for missing SLO

### ISSUE THREAD

**Issue by robertjahn** [keptn/keptn#1631]
**Is your feature request related to a problem? Please describe.**
When there is missing SLO file, the pipeline will stop, but the ICON and task shows no indication unless you review the JSON results.

**Describe the solution you'd like**
To make it stand out, have the ICON in bridge be RED when missing SLO file and/or other issues with quality gate processing

**Describe alternatives you've considered**
None

**Additional context**

![image](https://user-images.githubusercontent.com/24907089/79135587-9442a100-7d7d-11ea-86e7-71cdb0960f4b.png)

**Comment by christian-kreuzberger-dtx** [comment]
It's not an error if the SLO file is missing. However Keptn's Bridge should show the result message more prominent.
