### ISSUE TITLE
Provide links to tutorials, docs, and/or slack channel in Keptn Bridge

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#1635]
Add links to useful resources directly into the bridge.
- how to extend Keptn with services from keptn-contrib or keptn-sandbox
- tutorials
- docs
- slack channel to get help and discuss with others
- survey (current or upcoming surveys)

**Ideas:**
* A possible solution for this would be to link to a dedicated _Keptn Ecosystem_ webpage that provides this information.
* Another solution is to list the resources in the Keptn Bridge and highlight them so the user can get the most out of his/her Keptn installation.

This issue is related to #1503

**Comment by johannes-b** [comment]
Please consider https://github.com/keptn/keptn/issues/1503 for additional details.

**Comment by johannes-b** [comment]
The issue #2429 addresses the points: 

- [x] how to extend Keptn with services from keptn-contrib or keptn-sandbox
- [ ] tutorials
- [x] docs
- [ ] slack channel to get help and discuss with others
- [ ] survey (current or upcoming surveys)

and will be implemented by dynamically fetching the content that is displayed. In other words, it can be customized afterwards for adding more information (links) if needed.
