### ISSUE TITLE
Enable highlighting in heatmap chart

### ISSUE THREAD

**Issue by ermin-muratovic** [keptn/keptn#1640]
Contribution to barista-components charts to enable highlighting and tooltip in the heatmap chart.

**Definition of Done:**

- [x] Highlighting of the currently selected evaluation result in the Heatmap Chart:
![image](https://user-images.githubusercontent.com/729071/79880090-d3ad6500-83ef-11ea-99d2-135401afc543.png)

- [ ] ~~Tool Tip for element in HeatMap~~
![image](https://user-images.githubusercontent.com/729071/79879760-67cafc80-83ef-11ea-9e9a-3d2e5ee9715a.png)

**Comment by johannes-b** [comment]
Please see this link for more details: https://www.highcharts.com/forum/viewtopic.php?t=43488
