### ISSUE TITLE
HeatMap runs in JS error due to long list of SLIs 

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#1641]
Environment: Keptn 0.6.1 + Bridge EAP: 20200402:1046

In this Keptn a list of 100+ SLIs is configured. 

**HeadMap Isssue:** 
For the first ~4 test evaluations, the HeatMap worked fine with this high number of SLIs. After a click on the HeatMap button the bridge runs in an error: `Highcharts error #12: www.highcharts.com/errors/12` 

The reason might be that the setting `plotOptions.series.turboThreshold` has a default of 1000 and in this case the default is exceeded.  

Problematic HeatMap (result): 
![image](https://user-images.githubusercontent.com/729071/79328074-c7b83380-7f15-11ea-8791-9022138c1123.png)

**Definition of Done:**  
- [ ] BugFix for the JS error caused by the default value:  `plotOptions.series.turboThreshold`

**SLI Breakdown Issue**
In the SLI breakdown, three columns are created for the list of SLIs. 

![image](https://user-images.githubusercontent.com/729071/79330984-bf162c00-7f1a-11ea-812f-75bbce938898.png)

**Definition of Done:**  
- [x] Enforce the component to not create multiple columns, but to show the list of SLIs in one column.

**Comment by ermin-muratovic** [comment]
![image](https://user-images.githubusercontent.com/6098219/80707567-73eb4400-8aea-11ea-8787-902045e2ff2a.png)

**Comment by johannes-b** [comment]
I tested out the bridge in version 0.6.2 and the HeatMap is still broken:

![image](https://user-images.githubusercontent.com/729071/80729497-a4da7180-8b08-11ea-9f9a-4af9693172f7.png)

@ermin-muratovic Can you please fix the JS error `Highcharts error #12: www.highcharts.com/errors/12` for Keptn release 0.6.2.
