### ISSUE TITLE
Source of cloud event not correctly shown

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#1643]
When defining the source of the cloud event in my custom code, it seems that it does not show it correctly in the keptn's bridge, as can be seen in the screenshot.

![image](https://user-images.githubusercontent.com/7677092/79328902-187c5c00-7f17-11ea-9717-d3f692fc8892.png)

**Environment**

* Keptn Version (`keptn version`): 0.6.1
* Bridge version: 20200326.0744

**Expected behavior**
Would have expected to see the source where the event was coming from, in my case `https://github.com/keptn-sandbox/slackbot-service` - instead the `keptn/keptn/api` is shown as source.

**Comment by christian-kreuzberger-dtx** [comment]
How is the event sent to Keptn? Via the public API, or via the internal event-broker?
