### ISSUE TITLE
Enhance validation when creating projects via JSON

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [keptn/keptn#1647]
`keptn create project this!!Project --shipyard=shipyard.yaml` doesn't allow uppercase or special characters) but there is no validation on the project field of JSON files.

So `keptn send event -f project.json` where `project="this!!Project"` works.

The rules should apply equally to both scenarios.

**Comment by johannes-b** [comment]
This issue is related to #1654.

**Comment by johannes-b** [comment]
With the implementation of the shipyard-controller a REST endpoint is provided for creating a project. Hence, this is not covered by an event anymore what was the problem mentioned here. 

I closed this issue.
