### ISSUE TITLE
YAML input support for URIs

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [keptn/keptn#1648]
It'd be a great feature to allow URI-based YAML files as input for commands that expect a `yaml` file.

For example `keptn create project sockshop --shipyard=https://example.com/shipyard.yaml`

**Comment by Dynatrace-Adam-Gardner** [comment]
When evaluating this, also consider #1654

**Comment by shouri007** [comment]
@johannes-b I'd like to take this up. Do you recommend any standard yaml parsing libraries for golang?
I found the following ones:
[go-yaml/yaml](https://github.com/go-yaml/yaml)
[go-gypsy](https://github.com/kylelemons/go-gypsy)
[goccy/go-yaml](https://github.com/goccy/go-yaml)

**Comment by agrimmer** [comment]
@shouri007 great and thank you!

We already have [go-yaml/yaml](https://github.com/go-yaml/yaml) as a dependency in the CLI. Therefore, I would prefer to use this.

**Comment by johannes-b** [comment]
Hello @shouri007, 
I'm just asking if you still want to work on this issue? 
(Every contribution is highly appreciated. :smiley: )

**Comment by shouri007** [comment]
Hi @johannes-b , apologies for the delay. I'm still interested in working on this issue. Need some more time in ramping up on the whole infrastructure and go ahead with the implementation. Thanks!

**Comment by shouri007** [comment]
@johannes-b Please feel free to assign this issue if anybody is interested in working on this. I currently don't have the bandwidth to attend to this. Apologies for the delay!

**Comment by anukul** [comment]
Hi!
Just to confirm, `keptn create project --shipyard=<here>` is currently the only argument that accepts a YAML file, right?

**Comment by johannes-b** [comment]
Hi @anukul! Yes, `keptn create project` is the only argument that takes a YAML which will then be processed.
