### ISSUE TITLE
API: Swagger UI is inconsistent for create service

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#1656]
See the following screenshot. The Swagger UI - while great to get an overview of the available endpoints - is inconsistent with the documentation of the parameters. This makes it hard for somebody that develops extensions based on the Keptn API

![image](https://user-images.githubusercontent.com/675886/79804870-2e4daf00-8365-11ea-9fd2-fad87e046bcc.png)

**Comment by agrimmer** [comment]
Can you please describe in more details what is inconsistent?
I agree that we should describe the expected format of the `serviceName` and `helmChart`.

**Comment by grabnerandi** [comment]
please ignore this one. my mistake as I wasnt reading the swagger ui correctly
