### ISSUE TITLE
Show SLO goals (pass/warn) in HeatMap

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#1661]
The Heatmap currently only displays the overall score of a run and changes the color to red in case of a failed build. What we dont show is the actual SLO pass & warn threshold, e.g: 90%pass and 50% warning. The heatmap should visualize that threshold

![image](https://user-images.githubusercontent.com/675886/79858887-63dbb200-83d0-11ea-8492-ad973b6d4c40.png)

**Comment by johannes-b** [comment]
I would propose to implement like this:
![image](https://user-images.githubusercontent.com/729071/81167172-0c733f80-8f95-11ea-9f1a-ec578d537257.png)

**Comment by johannes-b** [comment]
More details about implementing this feature are provided here: https://github.com/keptn/keptn/issues/2305

**Comment by johannes-b** [comment]
This will be implemented by #2305
