### ISSUE TITLE
Extend horizontal axis of the bar chart from a timeline to fixed distances

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#1668]
It should be possible to extend the horizontal axis of the bar chart used for the evaluation comparison from a timeline: 
![image](https://user-images.githubusercontent.com/729071/79876729-b1b1e380-83eb-11ea-90f7-368b33d4db5f.png)

to a representation with a fixed distance between the bars: 

![image](https://user-images.githubusercontent.com/729071/79878225-7b756380-83ed-11ea-82fc-3dc9de62c0cc.png)

On the horizonal axis we can not show a number yet, instead we will show a date/time label (tilted).

**Definition of Done:**
- [ ] A switch is provided that allows changing the horizontal axis.

**Comment by christian-kreuzberger-dtx** [comment]
On the x-axis, we will use the label `buildId`. If it is not there, we will use the datetime.

```json
{
     "...": "...",
     "labels": {
          "buildId": "1234"
     }
}
```
