### ISSUE TITLE
Add support for passing labels for keptn cli send event

### ISSUE THREAD

**Issue by robertjahn** [keptn/keptn#1669]
**Is your feature request related to a problem? Please describe.**
To support more integrations and add support for passing labels for `keptn send event`. These labels can then be parsed out in keptn-services for supporting various use-cases.

**Describe the solution you'd like**
* Add one argument for all labels - `--labels={"source": "bitbucket","build": "118"}`

*Or perhaps one argument per label:*
* Add one argument for all labels - `--label="source": "bitbucket" --label="build": "118"`

**Describe alternatives you've considered**
* Use the Keptn REST API

**Additional context**
Here is an example REST call with labels:
```
{
  "data": {
    "start": "2020-04-13T18:14:38Z",
    "end": "2020-04-13T18:15:45Z",
    "project": "bitbucket-demo",
    "service": "simplenodeservice",
    "stage": "staging",
    "teststrategy": "manual",
    "labels": {
      "source": "bitbucket",
      "build": "118"
    }
  },
  "type": "sh.keptn.event.start-evaluation",
  "source": "https://bitbucket.org/dynatracedemos/simplenodeservice/addon/pipelines/home#!/results/118"
}
```

**Comment by johannes-b** [comment]
Hi @robertjahn,
In the REST call I can see that you are sending a `sh.keptn.event.start-evaluation` event with `labels`. 

The keptn CLI does support your use-case: `keptn send event start-evaluation --project=sockshop --stage=hardening --service=carts --start=2020-03-31T11:59:59  --labels=id=1234,test-name=performance-test` 

* see the flag: `--labels=id=1234,test-name=performance-test`. This becomes:
```
    "labels": {
      "id": "1234",
      "test-name": "performance-test"
    }
```

* in your case it would be: `--labels=source=bitbucket,build=118`

Does this help and resolve the issue?

**Comment by robertjahn** [comment]
Yes -- I did not see that help listing.  Thank you, closing ticket.
