### ISSUE TITLE
Dynatrace secret credentials per stage

### ISSUE THREAD

**Issue by yul14nrc** [keptn/keptn#1670]
I have the following project-stage-services structure on keptn:

project: ecommerce
     stage: uat2
          service: BookingEngine
          service: Itinerary
     stage: prod
          service: BookingEngine
          service: Itinerary

We have currently two dynatrace tenants, one for uat2 env and another for prod env. It will be a great feature for us, if we could set dynatrace secret credentials per stage.

**Comment by christian-kreuzberger-dtx** [comment]
Hi,

this does not directly affect Keptn, but the [dynatrace-service](https://github.com/keptn-contrib/dynatrace-service) as well as the [dynatrace-sli-service](https://github.com/keptn-contrib/dynatrace-sli-service).

The *dynatrace-sli-service* is already able to take credentials per project, so splitting this further up by stage should be something we can implement. Please open a feature-request (new issue) [within that service](https://github.com/keptn-contrib/dynatrace-sli-service).

For the *dynatrace-service* itself the is a little bit more complicated, as this services primary task is to connect the Kubernetes cluster where Keptn runs with Dynatraces OneAgent (therefore we take exactly ONE set of tenant + credentials).

**Comment by christian-kreuzberger-dtx** [comment]
This has been implemented in dynatrace-service, I'm closing the issue here.
