### ISSUE TITLE
Get HeatMap of evaluation-done event including deep link into Bridge

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#1677]
When integrating Keptn Quality Gate into a Jenkins pipeline, it should be possible to get the HeatMap of the `sh.keptn.events.evaluation-done` event, which will then be displayed in an iFrame of the Jenkins pipeline. 

![image](https://user-images.githubusercontent.com/729071/79985588-197b3380-84ab-11ea-9f6f-236ae7d3eec8.png)

**Out of scope**
- Authentication
- CORS Issue
- Iframe issues
- Iframes issues (twice on purpose, because iframes generate lots of issues)

**Definition of done**
- [x] Provide a separate view that only shows the heatmap
- [x] Provide a deep-link to that view
- [x] Within the evaluation-done event in the normal screen, provide a "open in new window" button
![image](https://user-images.githubusercontent.com/56065213/85402926-cd0cac80-b55c-11ea-8d50-68836b7c7e4a.png)

**Comment by grabnerandi** [comment]
Thanks Johannes for creating that ticket. This would be great as it will allow us to do several integrations with external tools such as Jenkins, Azure DevOps, ...

I think the link should be to the bridge - and - just as we have it for the deep links it would be great to provide a shortlink to a specific keptnContext or even the eventId of the evaluation-done event. Here some thoughts
bridge.keptn.mykeptndomain/evaluation-result/{keptn-context} -> would visualize the last evaluation-done event for that keptn-context if exists
bridge.keptn.mykeptndomain/evaluation-result/{keptn-context}/{evaluation-done-event-id} -> will show exactly the heatmap for that event id of that keptn-context

As an "extended request" we could either return an HTML page or allow the user to specify a content-type, e.g: PDF, PNG, JPG ... which would allow us to build integrations where we can "archive" the heatmap as a build artifact

**Comment by christian-kreuzberger-dtx** [comment]
I'm not sure if this is possible for two reasons:
* SSL certificates (if they are invalid, the iframe won't work)
* Basic Authentication on Keptn Bridge
