### ISSUE TITLE
Bridge Icon and text for start-evaluation is not formatted properly

### ISSUE THREAD

**Issue by robertjahn** [keptn/keptn#1678]
Your issue may already be reported! Please search on the [issue tracker](https://github.com/keptn/keptn/issues) before creating a new one.

On the left hand side of bridge, it shows text sh.keptn.event.start-evaluation and default icon and not text and right icon
![image](https://user-images.githubusercontent.com/24907089/80020389-f2226780-84a6-11ea-8a40-c137abdd6ea1.png)

**Environment**

Keptn 0.6.1 - Bridge. 20200402.1046

**Affected Component**

* [ ] Docs
* [ ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [x ] Bridge
* [ ] Gatekeeper
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**

**To Reproduce**

**Expected behavior**
Shows 'start evaluation' as text and  and evaluation icon

**Current behavior**
Shows internal text sh.keptn.event.start-evaluation and default icon

**Screenshots**

**Additional context**

**Comment by johannes-b** [comment]
Hi Rob, one day earlier I have created an issue for exactly the same. Please see #1667 
I closed this issue since it is a duplicate.
