### ISSUE TITLE
API: Extend /events API with more filter options to allow more use cases

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#1690]
Events hold a lot of information but right now one can only query events for a particular `keptnContext` or of a particular type. In order to allow a Keptn-user to build more advanced use cases on top of events, Keptn should provide a public `/event` endpoint that provides additional filter options.

Based on a discussion on Slack, we know that the Bridge is using internal API calls like this: 
```
/event?type=sh.keptn.events.evaluation-done&projectName=sockshop&serviceName=carts&stageName=staging&source=lighthouse-service&pageSize=50
```
This allows the bridge to retrieve a list of events that match these filter options with a single call.

This capability would be needed in order to leverage extensions such as the keptnReport sandbox project that assumes we can get easy access to historical events on a specific project.

Here is the slack conversation as a reference: https://keptn.slack.com/archives/CGS5TA283/p1585989904014200

**Comment by christian-kreuzberger-dtx** [comment]
In the background, mongodb-datastore already has such an endpoint.

We can easily expose this endpoint via our API gateway.

**Comment by johannes-b** [comment]
In Keptn 0.7, the `/event` endpoint of the mongodb-datastore is now publically exposed. Please check out about the API by selecting `mongodb-datastore` in the top right corner: 

![image](https://user-images.githubusercontent.com/729071/88366397-56481680-cd89-11ea-929b-cdf4feb85038.png)
