### ISSUE TITLE
Labels are being dropped between the get-sli and the get-sli.done keptn events

### ISSUE THREAD

**Issue by robertjahn** [keptn/keptn#1693]
Your issue may already be reported! Please search on the [issue tracker](https://github.com/keptn/keptn/issues) before creating a new one.

**Environment**

* Keptn Version (`keptn version`): 0.6.1
* Kubernetes Cloud Provider (e.g., GKE, AKS): EKS

**Affected Component**

- [x] SLI keptn services

**Describe the bug**

Labels are being dropped between the get-sli and the get-sli.done keptn events.

**To Reproduce**

Add a label to a start evaluation event and then review the sli done event.

**Expected behavior**
The labels in the event are not dropped.

**Current behavior**
The labels are being dropped between the get-sli and the get-sli.done events. The jira-service listens for the sh.keptn.internal.event.get-sli.done and will use the label with the JIRA issue # to then use that to update the right ticket who made the request for the performance as a self-service.
 
I pass labels (with the JIRA ticket #) in the sh.keptn.event.start-evaluation event
I see the labels ok in the sh.keptn.internal.event.get-sli event
But in the sh.keptn.internal.event.get-sli.done event, the labels show ("labels": null,)

If this is still up, here is an example:
https://bridge.keptn.jahn-keptn-quality-gate.alliances.dynatracelabs.com/project/bitbucket-demo/simplenodeservice/b5edb095-65ec-4f33-aec0-a6a7e4427ce0/e9e7fdbe-84fb-4e23-8a0a-75361b942611

**Screenshots**

Here is data from one keptn-context flow...see the  ("labels": null,) in the last image.

![image](https://user-images.githubusercontent.com/24907089/80105392-8bed2180-8546-11ea-97f7-934376eef2cb.png)

![image](https://user-images.githubusercontent.com/24907089/80105434-9c050100-8546-11ea-9570-26b0fd5e43c0.png)

![image](https://user-images.githubusercontent.com/24907089/80105452-a1624b80-8546-11ea-9d8d-9e83a5437bcf.png)

**Additional context**

**Comment by johannes-b** [comment]
This issue is for the [prometheus-sli-service](https://github.com/keptn-contrib/prometheus-sli-service) and the [dynatrace-sli-service](https://github.com/keptn-contrib/dynatrace-sli-service). Both don't add the labels from a `sh.keptn.internal.event.get-sli` to a `sh.keptn.internal.event.get-sli.done`.
