### ISSUE TITLE
Add ProblemURL to the keptn problem events

### ISSUE THREAD

**Issue by robertjahn** [keptn/keptn#1694]
**Is your feature request related to a problem? Please describe.**
The Dynatrace problem webhook can send the ProblemURL as part of the payload to Keptn. By having this, it will support Keptn integrations.

![image](https://user-images.githubusercontent.com/729071/82186909-e0888000-98eb-11ea-841b-6bed2b9b7c08.png)

**Describe the solution you'd like**
I would like to see `ProblemURL` as payload in the `sh.keptn.event.problem.open` event as in this example

```
"data": { 
  "ImpactedEntity": "frontend AVAILABILITY_EVENT 2020-04-23T00:50:16.538Z on Web request service k8-bitbucket-demo-production-simplenodeservice-", 
  "PID": "-1661189226184765289", 
  "ProblemDetails": { ... ... }
  "ProblemURL": "https://xyzabc.live.dynatrace.com/#problems/problemdetails;pid=-1661189226184765289_1587603016852V2", 
  "ProblemID": "289", 
  "ProblemTitle": "frontend AVAILABILITY_EVENT 2020-04-23T00:50:16.538Z", 
  ... 
},
```

**Describe alternatives you've considered**
None

**Additional context**

**Comment by johannes-b** [comment]
Hi Rob, I created a spec change proposal for introducing `ProblemURL` as an additional (but optional) field of a problem.open event: https://github.com/keptn/spec/pull/30

**Comment by johannes-b** [comment]
**Definition of Done:**
- [ ] The property `ProblemURL` is added to the payload of a problem notification: https://github.com/keptn-contrib/dynatrace-service/blob/master/pkg/lib/dynatrace_api_models.go#L23

**Comment by johannes-b** [comment]
I need approval for: 
- [ ] prometheus-service: https://github.com/keptn-contrib/prometheus-service/pull/54
- [ ] dynatrace-service: https://github.com/keptn-contrib/dynatrace-service/pull/144
- [ ] go-utils: https://github.com/keptn/go-utils/pull/168
