### ISSUE TITLE
Enable installation using --gateway=NodePort to use an external IP, which can be reached from the outside

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1708]
Installing keptn using `--gateway=NodePort` results in the ingress gateway being exposed with an Internal IP, e.g., 10.128.0.40.

As already explained in #1482, this behaviour might not be desirable, and the only way around this is to use the K8s nodes public IP address (which might not be known by the end-user by the time of the installation).

What does however work (e.g., on GKE) is the approach using `$DOMAIN=$(curl ifconfig.me)`, or if you already installed, you could determine it using jmeter-service:

```console
kubectl -n keptn exec -it svc/jmeter-service -- curl ifconfig.me
```

and then apply it using

```console
keptn configure domain api.keptn.PUT_IP_ADDRESS_HERE.nip.io:31390
```

On Linux and MacOS we should be able to combine this using

```console
PUBLIC_IP=$(kubectl -n keptn exec -it svc/jmeter-service -- curl ifconfig.me)
keptn configure domain api.keptn.${PUBLIC_IP}.nip.io:31390
```

# Definition of Done

- [ ] Installation using `--gateway=NodePort` works for setups with Internal IPs as well as public IPs (we could change the installer option `--domain=...` like this: `--domain={INTERNAL_IP_PLACEHOLDER}.nip.io` or `--domain={EXTERNAL_IP_PLACEHOLDER}.nip.io`)
- [ ] Documentation of the installer options `--gateway` and `--domain`, as well as the type of ingress gateways used (nginx vs istio)

**Comment by christian-kreuzberger-dtx** [comment]
The issue seems to only occur for nginx ingress, not when using istio virtualservices.

**Comment by agrimmer** [comment]
The installer could also try to retrieve the external node IP using
`kubectl get nodes -o jsonpath='{ $.items[0].status.addresses[?(@.type=="ExternalIP")].address }'`.

**Comment by agrimmer** [comment]
With the implementation of KEP 18 and especially with my PR https://github.com/keptn/keptn/pull/2022, the user now has full control of the used gateway. Therefore, I am closing this issue.
