### ISSUE TITLE
Fix writing of `keptn CLI` within the CLI code (comments) and validation of comments

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1718]
There are several occurrences of *Keptn CLI*  in the code of the CLI, which need to be changed to a lowercase `k`.

**Comment by agrimmer** [comment]
Why should we use a lower case? We write Keptn always with a capital letter.

**Comment by christian-kreuzberger-dtx** [comment]
When we refer to the CLI, we are supposed to write a lowercase `k`. /CC @johannes-b

**Comment by johannes-b** [comment]
I would like to extend the focus of this issue. The comments for all Keptn CLI commands should be validated in regard to their meaning and streamlined with the other comments. 

**Definition of Done:**
- [ ] Comments for CLI commands are validated
- [ ] The documentation for the develop folder in: keptn/docs/develop/reference/cli is up-dated.
