### ISSUE TITLE
Use image:tag from latest root event regardless of event-type in stage overview

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#1732]
**Issue:** When using Quality Gate only use case where an external tool sends in a start-evaluation event, the bridge does not show any information in the stage overview about the last evaluation.

**Suggestion:** I suggest we allow every external tool to provide a value for "tag" and "image" and then display that value both in the root event as well as in the stage overview. here is a screenshot of the current version - what I am asking for is just show the last root events tag:image (if available) in the top 

![image](https://user-images.githubusercontent.com/675886/80714869-d5fd7680-8af5-11ea-9c51-474ac13496b0.png)

**Comment by christian-kreuzberger-dtx** [comment]
Let's discuss this internally. cc @johannes-b

**Comment by johannes-b** [comment]
This issue should be already addressed. Let's validate with a fresh Keptn project.

**Comment by johannes-b** [comment]
This is solved with Bridge 0.8.0
