### ISSUE TITLE
When installing Keptn, allow the user to specify a pre-defined domain or a wildcard DNS resolver, and add a warning

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1742]
While it is already possible to specify a domain, e.g., `keptn install ... --domain=my-server.some-company.net`, it is currently not possible to pre-select a DNS wildcard resolver, such as `nip.io` or `xip.io`.

From a security and legal standpoint, end-users might not want to use nip.io and xip.io per default (which we currently do in Keptn), therefore specifying a custom domain upfront is good.

However, should customers still want to use nip.io/xip.io, we need to provide a warning (to be defined):
> Warning: Using a DNS wildcard resolver is only recommended for demos and workshop-settings, definately NOT for production setups. By continuing you are using the selected service at your own risk. Find out more on https://keptn.sh/docs/wildcard-dns-resolver/.

# Definition of Done

- [ ] Page on keptn.sh/docs that provides more information about wildcard DNS resolvers and the risks behind them (IP spoofing, data is being sent to a third party which is GDPR relevant, ...)
- [ ] If the `--domain` flag is not specified during installation, `keptn install` actively queries the user to provide a domain (**DEFAULT**), or to select a Wildcard DNS Resolver (pre-defined ones will be xip.io, nip.io, as well as "specify your own wildcard dns resolver"). Selecting a Wildcard DNS Resolver must print a warning message.
- [ ] If the `--domain` option contains a wildcard dns resolver, the CLI needs to print a warning.
- [ ] `keptn configure domain` provides the same mechanism as `keptn install` for specifying a domain
- [ ] The Keptn installer image prints a warning in the logs if usage of a wildcard dns resolver (e.g., nip.io, xip.io) is detected.
- [ ] Keptn Bridge provides a warning in the UI which can be dismissed if usage of a wildcard dns resolver (e.g., nip.io, xip.io) is detected.

Related to #1708

**Comment by christian-kreuzberger-dtx** [comment]
This might be obsolete with KEP 18.

**Comment by agrimmer** [comment]
With the implementation of KEP 18 and especially with my PR https://github.com/keptn/keptn/pull/2022, the user now has full control of using any domain or wilcard DNS resolver, etc. Therefore, I am closing this issue.
