### ISSUE TITLE
Typo in bridge icon reference

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#1761]
As shown in the screenshot there is a typo when referencing the icon for the `tests-finished` event.

![image](https://user-images.githubusercontent.com/7677092/81159477-476f7600-8f89-11ea-8859-6d0e17167820.png)

**Environment**

* Bridge version: 202003260744

**Affected Component**

* [ ] Docs
* [ ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [x] Bridge
* [ ] Gatekeeper
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Comment by christian-kreuzberger-dtx** [comment]
The icon is called `perfromance-health` in barista components. So I guess the typo is in barista components, we're just victims :D

**Comment by johannes-b** [comment]
No action required.
