### ISSUE TITLE
Keptn CLI to generate secrets

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#1768]
Right now some parts of Keptn have the user to manually create a kubernetes secret in their cluster, e.g., the basic authentication for the Keptn's bridge or the secret to access SLI providers or to setup monitoring. 

A desired solution is that the Keptn CLI will create these secrets for the user. E.g., the command `keptn configure bridge --action=expose` will ask the user for credentials or auto-generates credentials to remove the need to manually create a kubernetes secret.
A similar approach would be great for `keptn configure monitoring`.

*Example*:
```
$ keptn configure bridge --action=expose
Your bridge will be exposed at https://bridge.keptn.xxx.xx.xx.com 
Please provide a username and password to setup basic authentication
username: 
password: 

Keptn's bridge has been successfully exposed at https://bridge.keptn.xxx.xx.xx.com with the given credentials! 
Happy shipping with Keptn!
```

**Comment by christian-kreuzberger-dtx** [comment]
This is alraedy on our roadmap: https://github.com/orgs/keptn/projects/1

**Comment by agrimmer** [comment]
With the PR https://github.com/keptn/keptn/pull/2022, we now distribute the installer as Helm chart. This Helm chart now contains also the secret for Basic-Auth for Bridge. Therefore, this issue was addressed for Keptn-core.
