### ISSUE TITLE
Rename installer job to keptn-installer to avoid confusion

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#1770]
Right now the keptn installer job is called "installer". 
We should rename it to something that is more keptn specific, e.g.: "keptn-installer" to avoid confusion or to make it more clear what this job is really doing.

**Comment by cavejay** [comment]
In poking my head around - Is this just as simple as updating [this line](https://github.com/keptn/keptn/blob/70acdf43a3e7280fda5e45d1f1288a9d022a0772/installer/manifests/installer/installer.yaml#L4) and then ensuring everything else continues to work?

**Comment by johannes-b** [comment]
Hi, thanks for reaching out on that issue!

For clarification, the line (file) you are referencing is used to support the installation of Keptn 0.5.2. With Keptn 0.6, we moved the job into the install command of the CLI. This is also the place where the job need to be renamed. Please take a look at: 

- installerJob: https://github.com/keptn/keptn/blob/master/cli/cmd/install.go#L70
- deleteKeptnInstallerPod: https://github.com/keptn/keptn/blob/master/cli/cmd/uninstall.go#L130

**Tasks:**
- [ ] Renaming the installer job from `installer` to `keptn-installer` in the code referenced above.
- [ ] Adding the comment `## This installer job is deprecated and needed for Keptn 0.5 only. It will be removed in the future` to the [file](https://github.com/keptn/keptn/blob/70acdf43a3e7280fda5e45d1f1288a9d022a0772/installer/manifests/installer/installer.yaml).

Would you like to work on that?

**Comment by agrimmer** [comment]
With my PR #2022, the Keptn installer is now distributed as Helm-chart and not as installer job anymore. Therefore, I am closing this issue.
