### ISSUE TITLE
The Job "upgrader" is invalid when updating 0.6.1 to 0.6.2

### ISSUE THREAD

**Issue by pahofmann** [keptn/keptn#1785]
**Environment**
* Client OS (e.g., Linux, OSX, Windows): Linux
* Keptn Version (`keptn version`): 0.6.2
* Kubernetes Cloud Provider (e.g., GKE, AKS): AKS
* Kubernetes version (`kubectl version`): 1.14.8

**Affected Component**

* [X] CLI
* [X] Upgrader

**Describe the bug**
When trying to upgrade from 0.6.1 to 0.6.2 I get an error message  `The Job "upgrader" is invalid:`

`The Job "upgrader" is invalid: spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name: "", GenerateName: "", Namespace: "", SelfLink: "", UID: "", ResourceVersion: "", Generation: 0, CreationTimestamp:v1.Time{Time:time.Time{wall: 0x0, ext: 0, loc:(*time.Location)(nil)
            }
        }, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string
        ]string{
            "app": "upgrader",
            "controller-uid": "e296cd2b-686e-11ea-b4e8-def6b5e73522",
            "job-name": "upgrader"
        }, Annotations:map[string
        ]string(nil), OwnerReferences: []v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers: []string(nil), ClusterName: "", ManagedFields: []v1.ManagedFieldsEntry(nil)
    }, Spec:core.PodSpec{Volumes: []core.Volume{core.Volume{Name: "kubectl", VolumeSource:core.VolumeSource{HostPath:(*core.HostPathVolumeSource)(nil), EmptyDir:(*core.EmptyDirVolumeSource)(0xc0065407a0), GCEPersistentDisk:(*core.GCEPersistentDiskVolumeSource)(nil), AWSElasticBlockStore:(*core.AWSElasticBlockStoreVolumeSource)(nil), GitRepo:(*core.GitRepoVolumeSource)(nil), Secret:(*core.SecretVolumeSource)(nil), NFS:(*core.NFSVolumeSource)(nil), ISCSI:(*core.ISCSIVolumeSource)(nil), Glusterfs:(*core.GlusterfsVolumeSource)(nil), PersistentVolumeClaim:(*core.PersistentVolumeClaimVolumeSource)(nil), RBD:(*core.RBDVolumeSource)(nil), Quobyte:(*core.QuobyteVolumeSource)(nil), FlexVolume:(*core.FlexVolumeSource)(nil), Cinder:(*core.CinderVolumeSource)(nil), CephFS:(*core.CephFSVolumeSource)(nil), Flocker:(*core.FlockerVolumeSource)(nil), DownwardAPI:(*core.DownwardAPIVolumeSource)(nil), FC:(*core.FCVolumeSource)(nil), AzureFile:(*core.AzureFileVolumeSource)(nil), ConfigMap:(*core.ConfigMapVolumeSource)(nil), VsphereVolume:(*core.VsphereVirtualDiskVolumeSource)(nil), AzureDisk:(*core.AzureDiskVolumeSource)(nil), PhotonPersistentDisk:(*core.PhotonPersistentDiskVolumeSource)(nil), Projected:(*core.ProjectedVolumeSource)(nil), PortworxVolume:(*core.PortworxVolumeSource)(nil), ScaleIO:(*core.ScaleIOVolumeSource)(nil), StorageOS:(*core.StorageOSVolumeSource)(nil), CSI:(*core.CSIVolumeSource)(nil)
                }
            }
        }, InitContainers: []core.Container(nil), Containers: []core.Container{core.Container{Name: "upgrader", Image: "keptn/upgrader:0.6.2", Command: []string(nil), Args: []string(nil), WorkingDir: "", Ports: []core.ContainerPort(nil), EnvFrom: []core.EnvFromSource(nil), Env: []core.EnvVar(nil), Resources:core.ResourceRequirements{Limits:core.ResourceList(nil), Requests:core.ResourceList(nil)
                }, VolumeMounts: []core.VolumeMount(nil), VolumeDevices: []core.VolumeDevice(nil), LivenessProbe:(*core.Probe)(nil), ReadinessProbe:(*core.Probe)(nil), Lifecycle:(*core.Lifecycle)(nil), TerminationMessagePath: "/dev/termination-log", TerminationMessagePolicy: "File", ImagePullPolicy: "Always", SecurityContext:(*core.SecurityContext)(nil), Stdin: false, StdinOnce: false, TTY: false
            }
        }, RestartPolicy: "Never", TerminationGracePeriodSeconds:(*int64)(0xc015a16258), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy: "ClusterFirst", NodeSelector:map[string
        ]string(nil), ServiceAccountName: "", AutomountServiceAccountToken:(*bool)(nil), NodeName: "", SecurityContext:(*core.PodSecurityContext)(0xc00b183c70), ImagePullSecrets: []core.LocalObjectReference(nil), Hostname: "", Subdomain: "", Affinity:(*core.Affinity)(nil), SchedulerName: "default-scheduler", Tolerations: []core.Toleration(nil), HostAliases: []core.HostAlias(nil), PriorityClassName: "", Priority:(*int32)(nil), DNSConfig:(*core.PodDNSConfig)(nil), ReadinessGates: []core.PodReadinessGate(nil), RuntimeClassName:(*string)(nil), EnableServiceLinks:(*bool)(nil)
    }
}: field is immutable`

**To Reproduce**
Try to upgrade an existing 0.6.1 keptn installation with `kubectl apply -f https://raw.githubusercontent.com/keptn/keptn/release-0.6.2/upgrader/upgrade-061-062/upgrade-job.yaml`

**Expected behavior**
Upgrade to 0.6.2 is performed

**Current behavior**
Upgrade job is not started.

**Comment by christian-kreuzberger-dtx** [comment]
Did you delete the existing upgrader `kubectl delete job upgrader`, as described in the [tutorial](https://keptn.sh/docs/0.6.0/installation/upgrade-keptn/#upgrade-from-0-6-1-to-0-6-2)?

Please verify using `kubectl get jobs`

**Comment by pahofmann** [comment]
Yes I did but there was none.  
I just checked again an realized that the upgrader is created in the **_default_**, not the **_keptn_** namespace.   
After deleting it there it worked. Maybe add the information about the namespace or change it to `kubectl delete job upgrader -n default` to avoid other running into this :)

Thanks!

**Comment by christian-kreuzberger-dtx** [comment]
Reopening and labelling this as a doc issue. Thanks for reporting!

**Comment by christian-kreuzberger-dtx** [comment]
Fixed in PR https://github.com/keptn/keptn.github.io/pull/545
