### ISSUE TITLE
Provide a “COPY JSON" button on the Bridge UI

### ISSUE THREAD

**Issue by robertjahn** [keptn/keptn#1794]
**Is your feature request related to a problem? Please describe.**
I often need to copy-and-paste the JSON from bridge and I need to carefully do this and can miss data.

**Describe the solution you'd like**
Perhaps a button on the popups or events details to just copy to clipboard.

**Describe alternatives you've considered**
None.  Manually do it.

**Additional context**

**Comment by christian-kreuzberger-dtx** [comment]
This is the modal dialog: 
![Screenshot from 2020-05-18 08-47-02](https://user-images.githubusercontent.com/56065213/82182197-2b05fe80-98e4-11ea-9846-7c45a45f3194.png)

We could add a `copy to clipboard` button there.

**Comment by sandroschmid** [comment]
@christian-kreuzberger-dtx @ermin-muratovic I would like to take care of this one
