### ISSUE TITLE
Provide a feature to delete the Keptn event history 

### ISSUE THREAD

**Issue by robertjahn** [keptn/keptn#1795]
**Is your feature request related to a problem? Please describe.**
After testing and demos I would like to have the data removed from Keptn.

**Describe the solution you'd like**
Perhaps the CLI or an API call to specify project and time range or all data.

**Describe alternatives you've considered**
None.  Reinstall Keptn.

**Additional context**

**Comment by christian-kreuzberger-dtx** [comment]
Hi, and thanks for your feature request.

In the master branch (not yet released) we have implemented a feature that automatically deletes all cloud-events of a project on deletion of the project (`keptn delete project sockshop`). 
Issue: https://github.com/keptn/keptn/issues/1384
Pull Request: https://github.com/keptn/keptn/pull/1676

Is removing cloud-events of a project by deleting the project what you were asking for, or is there more to this?

**Comment by christian-kreuzberger-dtx** [comment]
@johannes-b This feature request has gone stale two times now, and did not receive any upvotes at all, nor any comments since May. Is this still something we need?

**Comment by johannes-b** [comment]
Please let this issue open. 
- The `keptn delete project xyz` command a solution is provided
- The `keptn delete service xyz` command does not delete the events of that service. But I got feedback on adding a `--purge` flag that also deletes the history.

**Comment by christian-kreuzberger-dtx** [comment]
> The keptn delete service xyz command does not delete the events of that service. But I got feedback on adding a --purge flag that also deletes the history.

Is there an issue for that already? I'd like to do house-keeping and close duplicates.

**Comment by johannes-b** [comment]
Let's use this issue for implementing the `keptn delete service --purge` command.

**Comment by johannes-b** [comment]
This issue relates to #2776 and can be closed when the other is implemented.
