### ISSUE TITLE
Installation with --gateway=NodePort: keptn configure domain breaks local configuration

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1796]
I installed Keptn 0.6.2 on MiniKube using

```
keptn install --platform=kubernetes --use-case=quality-gates --gateway=NodePort --verbose
```

Which resulted in the Keptn api being available via the following domain/ip configuration: `https://192.168.99.100.xip.io:31415`.

I decided to switch from xip.io to nip.io, hence I ran
```
keptn configure domain "192.168.99.100.nip.io"
```

which resulted in the following output
```
Your kubernetes current context is configured to cluster: minikube
Would you like to update the keptn domain for this cluster? (y/n)
y
Please note that the domain of already onboarded services is not updated!
Starting to configure domain
Received Keptn Domain: 192.168.99.100.nip.io
Starting to authenticate
Authentication was unsuccessful. Post https://api.keptn.192.168.99.100.nip.io/v1/auth: dial tcp 192.168.99.100:443: connect: connection refused
Retrying...
Authentication was unsuccessful. Post https://api.keptn.192.168.99.100.nip.io/v1/auth: dial tcp 192.168.99.100:443: connect: connection refused
Retrying...
```

I then checked the configmap containing the Keptn Domain: 
```
kubectl get cm -n keptn keptn-domain -ojsonpath={.data.app_domain}
```
which returned
```
192.168.99.100.nip.io
```

In addition, the API was fully accessible and working using the URL `https://api.keptn.192.168.99.100.nip.io:31415/swagger-ui/`.

So the problem is that my local Keptn CLI is missing the port 31415 in the configuration.

# Workaround

For now, the workaround is to adapt the domain in the configmap manually using
```
kubectl -n keptn edit cm keptn-domain
```
and then authenticate again.

# Fix

I believe that when calling `keptn configure domain` we should properly set the port in the keptn-domain configmap.

**Comment by agrimmer** [comment]
For clarification: 
When you would have called `keptn configure domain "192.168.99.100.nip.io: 31415" including the port, would this properly set the port in the config map?

**Comment by bacherfl** [comment]
looking at the code for that command, the port number would have been set properly in the ConfigMap, but it would also have been included in the VirtualService, or the Ingress specification. Considering this, we should add a sanitation check that removes the Port from the provided domain before using that value for the VirtualService/Ingress
