### ISSUE TITLE
Setup keptn core (no demo app, just core components)

### ISSUE THREAD

**Issue by AloisReitbauer** [keptn/keptn#18]

**Comment by johannes-b** [comment]
To finish this issue, I see following tasks to be completed:
- [ ] Add additional script to setup knative and knative-based core components 
- [ ] Add core component EventBroker
- [ ] Disable deployment of demo application (sockshop)
- [ ] Add tests to Travis build that check knative installation and EventBroker 

PR https://github.com/keptn/keptn/pull/28 contains the first three items of the bullet list. Tests are missing.

**Comment by dirkwall** [comment]
Tests have been moved to #163, rest is done.
