### ISSUE TITLE
Environment Variable CONFIGURATION_SERVICE is not evaluated in helm-service

### ISSUE THREAD

**Issue by thschue** [keptn/keptn#1808]
**Environment**

* Keptn Version (`keptn version`): 0.6.2
* Kubernetes Cloud Provider (e.g., GKE, AKS): GKE
* Kubernetes version (`kubectl version`): v1.15.9-gke.24

**Affected Component**

* [ x ] Helm Service

**Describe the bug**
When specifying the configuration service url using the environment variable, it is not used. Furthermore, when specifying no environment variable, no error message is thrown (according to the code, it should)

**To Reproduce**

* Use another service name than configuration-service for the configuration service
* specify a value for the Environment variable in the helm service other than "configuration-service:8080" 
* try to create a new service

**Expected behavior**
* Service should be created
* environment variable should be used

**Current behavior**
* Service does not get created
* Error message that the url "http://configuration-service:8080" (Fallback) does not exist, appears

**Additional context**
* It seems, that the environment variable does not get evaluated (helm-service:/controller/helm/onboarder.go:40

**Comment by christian-kreuzberger-dtx** [comment]
Hi @thschue , any progress on this issue? Please let us know if you have the time to finish this.

**Comment by thschue** [comment]
Sorry, I think I won't be able to do this in time ...

**Comment by christian-kreuzberger-dtx** [comment]
Thanks for the reply, I'll put it back into our backlog!
