### ISSUE TITLE
Validation of CloudEvent spec on keptn/spec:master with implementation 

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#1815]
Before releasing Keptn 0.7, it is required to validate the CloudEvent spec against the implementation of the two use-cases:
- manual approval
- remediation

Inconsistencies need to be discussed and addressed.

**Definition of Done:**
- [x] It is verified that the CloudEvents are correctly implemented in the master branch

**Comment by agrimmer** [comment]
Implemented with https://github.com/keptn/spec/pull/34
