### ISSUE TITLE
Keptn Installer: OpenShift installation does not allow to reuse Istio

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#1820]
The Openshift installation does not allow to reuse Istio, i.e. the Openshift installation ignores the flag `--ingress-install-option` and always creates an `istio-system` namespace and tries to install Istio.

**Tasks:** 
- Evaluate whether the functionality in https://github.com/keptn/keptn/blob/master/installer/scripts/common/setupIstio.sh can be reused for OpenShift.

**Definition of Done:**
- [ ] Allow reusing an existing Istio installation for a Keptn installation on OpenShift.

**Comment by christian-kreuzberger-dtx** [comment]
This will be obsolete if we implement [KEP 18](https://github.com/keptn/enhancement-proposals/pull/18)

**Comment by christian-kreuzberger-dtx** [comment]
I'll leave this one open, until we can verify that the approach of KEP 18 works with OpenShift. Please close it once you believe this is ready.

**Comment by johannes-b** [comment]
Obsolete due to KEP 18.
