### ISSUE TITLE
Keptn CLI: Delivery assistant for approving a deployment

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#1835]
With the implementation of this CLI feature, a Keptn user should get assistance for delivering an artifact that is waiting for approval. Therefore, an interactive CLI command is proposed that first retrieves open approvals (for a service in the specified stage/project) that can be confirmed by a user (e.g., in the role of a release manager).

:grey_question: To-be-defined: As this command is the first one that provides an interactive approach, I'm not sure how to call the command. Consequently, I propose the following options: 

* *Option A: Re-use `send new-artifact`, `get event approval.triggered` or `send event approval.finished`*
```
keptn send event approval.finished --project=sockshop --stage=hardening  --service=carts

OPTION     VERSION         EVALUATION  
(1)        0.10.2          88 (warning)
(2)        0.10.1          92 (passed)

Select the option to approve or decline: 2
Do you want to (a)pprove or (d)ecline: a 
``` 

* ~~*Option B: New command `approve [carts] --project=sockshop --stage=hardening`*~~
```
keptn approve carts --project=sockshop --service=carts

OPTION     VERSION         EVALUATION  
(1)        0.10.2          88 (warning)
(2)        0.10.1          92 (passed)

Select the option to deliver in hardening:
Do you want to (a)pprove or (d)ecline: a 
``` 

* ~~*Option C: Another command?*~~

**Poll: Which option to implement?**
- [x] Option A: Re-use command: `keptn send event approval.finished`
- [ ] ~~Option B: New command~~
- [ ] ~~Option C: Another command~~

**Definition of Done:**

- [ ]  Keptn CLI provides command
- [ ] Auto-gen CLI documentation on keptn.sh/docs

**Comment by agrimmer** [comment]
I vote for `keptn send event approval.finished` because this is the action the user would like to do.

When the user executes `keptn send event approval.finshed` without id, the CLI should interactively ask the user which artifact he/she wants to approve.
Therefore, the `id` flag has to be optional.

**Comment by johannes-b** [comment]
Re-using the `keptn send event approval.finshed` command and making the `id` an optional flag is a great idea! With the following reasoning:
1. We still provide the possibility to use the command in "silent" mode, meaning that the user has to provide the `id` then.
1. We are compliant with Keptn's eventing approach (i.e.: it is the same approach like using the API for this task)

**Comment by johannes-b** [comment]
In the example of the issue description, I added the question: 
- `Do you want to (a)pprove or (d)ecline: a `

Is it a good approach to answer this question with an `a` / `d`?

Please see: https://github.com/keptn/spec/blob/master/cloudevents.md#approval-finished for the a/d options: 
* approve = result:pass
* decline = result:failed
