### ISSUE TITLE
Show warning when creating a project without Git upstream

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#1840]
This is a follow-up issue on: #1517 

*Creating a keptn project **with** Git upstream must become the default and recommended approach.*

When the user creates a project without specifying the credentials for a Git upstream repo, the CLI shows a warning that this is not recommended and provides the command to set the upstream.

```
> keptn create project sockshop --shipyard=shipyard.yaml
WARNING: Creating a project without Git upstream repository is not recommended. 
You can configure a Git upstream repository using: 

keptn update project sockshop --git-user=xxx --git-token=yyy --git-remote-url=zzz
```

**Definition of Done**
- [ ] The documentation of the cli command `keptn create project` indicates the recommended approach.
- [ ] Implementation of the feature explained by the above example.

**Comment by christian-kreuzberger-dtx** [comment]
Good point. I'd say we rephrase 
> You can configure a Git upstream repository using: 

to

> To configure a Git upstream repository afterwards, use the following command:
...
> Find out more about Git upstream repositories at https://keptn.sh/docs/develop/manage/git_upstream/
