### ISSUE TITLE
Keptn API: Retrieve metadata of Keptn installation

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1843]
Right now there is no way to retrieve meta-data information from Keptn via the API, such as:

* Which namespace Keptn is installed in (e.g., passed as an environment-variable to the api)
* (Future / not yet available) Name/Label of the Keptn installation - please define the variable and set it to "keptn" for now
* Installed Keptn Version (e.g., api-service has an environment variable for it)
* Installed Keptn Bridge Version (can be the image tag of the docker image) - This might require an RBAC rule
* (Future / not yet available) List of Keptn-services + which version they are installed in

However, this information can be manually collected using a lot of `kubectl` commands.

# Definition of Done

- [ ] Create an authenticated endpoint in the Keptn api that returns the above information
- [ ] Also add this endpoint as a check that is executed when calling  `keptn generate support-archive` command
- [ ] Create an integration test for it (or edit an existing one)

**Comment by checkelmann** [comment]
I could take this one.

**Comment by christian-kreuzberger-dtx** [comment]
@agrimmer can you support with any RBAC issues here?

**Comment by agrimmer** [comment]
Sure! Will help.

**Comment by checkelmann** [comment]
Hey,

I've some questions regarding the API...

What I did so far:

- Added a /metadata definition in the swagger.yaml
- Added a response model in `"response_model.yaml#/definitions/metadata"`
- Executed as described in the README.md `swagger generate server -A api -P models.Principal -f ./swagger.yaml`

After running the swagger generate command a lot of not related files are changed [diff.txt](https://github.com/keptn/keptn/files/4844857/diff.txt)

So my questions:
Was my approach to add the endpoint to the API Service wrong? 
Which version of the swagger should I use (I've installed v0.19.0)

swagger.yaml
```yaml
  /metadata:
    get:
      tags:
        - Metadata
      operationId: metadata
      summary: Get keptn installation metadata
      responses:
        200:
          description: Success
          schema:
            $ref: "response_model.yaml#/definitions/metadata"       
```

response_model.yaml
```
  metadata:
    type: object
    required:
      - token
    properties:
      token:
        type: string
      namespace:
        type: string
      keptnversion:
        type: string
      bridgeversion:
        type: string      
```

Christian

**Comment by agrimmer** [comment]
Hi @checkelmann,

thank you for implementing this issue and your question!
Your `swagger.yaml` looks good. Also the `response_model.yaml` looks good except for the `token`. Which token would you like to return here? I guess you can remove it.

I have installed swagger version v0.22.0.
It is normal behavior that swagger generates many changes. But can you please point me to your branch? Then I could have a closer look at the generated source code?

Thanks,
Andreas

**Comment by checkelmann** [comment]
Hi @agrimmer 

> thank you for implementing this issue and your question!
> Your `swagger.yaml` looks good. Also the `response_model.yaml` looks good except for the `token`. Which token would you like to return here? I guess you can remove it.

Ah ok, then I misunderstood the required parameter, I thought I need the token for the Authentication.

> I have installed swagger version v0.22.0.
> It is normal behavior that swagger generates many changes. But can you please point me to your branch? Then I could have a closer look at the generated source code?

I will try with your swagger version and push it to my https://github.com/checkelmann/keptn repo later. When I've done it, I will ping you on Slack.

Cu Later...

**Comment by agrimmer** [comment]
Hello again,

what you defined in the `response_model` is the return of the API call. Furthermore, you automatically get an authenticated endpoint because of the `securityDefinitions` in https://github.com/keptn/keptn/blob/master/api/swagger.yaml#L14, i.e. without providing a correct `x-token` in the header, no metadata will be returned.

I will check out your code. 
Cheers, Andreas

**Comment by checkelmann** [comment]
Hi,

as discussed in the community meeting we should talk about the purpose of this endpoint.
@christian-kreuzberger-dtx mentioned this endpoint should be used for the `create support archive` command, but when the API is not reachable, this support archive will not be able to capture all the data as it does right now using `kubectl` commands.

If it should be an endpoint for other purposes, it will be slow and more expensive when scanning all deployments within the keptn namespace from the API Service.

@christian-kreuzberger-dtx @agrimmer @bacherfl 

What are your thoughts?

**Comment by christian-kreuzberger-dtx** [comment]
My opinion: I think we should still add it to the support-archive, even though the information is redundant. 

In the future we might add new information to that endpoint, therefore this could contain non-redundant information. In addition, it helps in trouble-shooting as we could spot mismatches between what the API endpoint returns vs. what the CLI was able to detect locally.

**Comment by bacherfl** [comment]
I also think it would make sense to have both the information from the CLI and the API Endpoint to detect any discrepancies between those.
