### ISSUE TITLE
 Testing: Integration test for the use-case of scaling a ReplicaSet based on Prometheus alert

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#1847]
Platform and integration test for the use-case of scaling a ReplicaSet based on a Prometheus alert. For this scenario, the helm-service must be deployed which provides the remediation action of scaling a ReplicaSet.  

**Benefit:** 
- This integration test reduces the testing effort when releasing Keptn. 

**Test scenario:** 
- The description of this test scenario is perfectly explained in https://tutorials.keptn.sh/tutorials/keptn-full-tour-prometheus/#0 

- The tutorial should be used to implement the integration test 

- For the sake of keeping the integration test focused on testing the self-healing capabilities, the SLO validation can be excluded.  

- Final check: The number of pods for the carts service have to be increased by 1.  

**Definition of Done:** 

- [ ] Travis-CI is extended by the test script `test_self_healing_prometheus.sh` covering the above test scenario 
- [ ] Test script is executed as part of a Keptn test on GKE: https://github.com/keptn/keptn/blob/master/.travis.yml#L111

**Comment by christian-kreuzberger-dtx** [comment]
I won't be able to do this issue, I'm un-assigning myself.
