### ISSUE TITLE
Upgrader: Helm v2 to v3 upgrade

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#1850]
The current version of the upgrader from 0.6.2 to 0.7.0 upgrades _all_ Helm releases.
See
https://github.com/keptn/keptn/blob/77ffeb0973057ad5e69642cd51a50559fe541416/upgrader/upgrade-062-070/scripts/upgradeKeptn.sh#L9

However, the upgrader **must not** upgrade Helm releases which are not managed by Keptn.

**Definition of Done:**
- [ ] All Helm releases created and managed by Keptn are upgraded.
- [ ] Other Helm releases remain unchanged.

**Comment by christian-kreuzberger-dtx** [comment]
I'd like to discuss this, before we make a final decision or implement anything.

* As a matter of fact, Keptn installs and upgrades Helm on the cluster. 
* As another matter of fact, we upgrade Helm from v2 to v3 with Keptn 0.7.0.
* The upgrader is responsible for doing that, therefore the upgrader is also responsible for upgrading helm releases (else Keptn onboarded services won't work anymore).

So far, so good. Now lets assume that the end-user has used Keptn 0.6.x and the Keptn-managed helm v2 installation for their own releases.

If we upgrade Keptn and Helm, but we don't upgrade ALL helm v2 releases that are managed by helm/tiller at that time, we will leave the end-user with helm releases that are incompatible with the cluster.

However, I can also see the point that the upgrader should not modify stuff that's not managed by Keptn.

So in my opinion we have two choices:

1. Leave the upgrader as it is and upgrade all helm chart (+ document this behaviour with a big fat warning in our docs)
2. Change the upgrader as proposed in the issue text above, and document the steps needed for anyone to upgrade their helm releases (e.g., `kubectl -n keptn exec -it svc/helm-service ...`).

**Comment by agrimmer** [comment]
When we choose option 2, we must not delete tiller.

But, after a Keptn upgrade to 0.7, the user cannot use the helm-service for upgrading Helm releases because it only contains Helm 3.

**Comment by christian-kreuzberger-dtx** [comment]
> When we choose option 2, we must not delete tiller.

That's correct, and that suggests to me that option 2 is not good.
I'll update my comment above.

**Comment by johannes-b** [comment]
Also consider mentioning that in release notes.
