### ISSUE TITLE
Keptn Installer: Remove dependency of yq (for openshift)

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1853]
The Keptn installer requires `yq` (a yaml process, similar to `jq`), as seen in the Dockerfile:

https://github.com/keptn/keptn/blob/77ffeb0973057ad5e69642cd51a50559fe541416/installer/Dockerfile#L22-L26

and

https://github.com/keptn/keptn/blob/77ffeb0973057ad5e69642cd51a50559fe541416/installer/scripts/openshift/installOnOpenshift.sh#L27
as well as
https://github.com/keptn/keptn/blob/77ffeb0973057ad5e69642cd51a50559fe541416/installer/scripts/openshift/setupIstio.sh#L52

We should be able to refactor the two occurances of `yq` to use the also installed `jq` which is usually used in our installer. In addition, we can most likely use `jsonpath` filtering instead of `sed`.

# Definition of Done

- [ ] Remove `yq` from Dockerfile
- [ ] Refactor all occurances of `yq` in the installer to use `jq` (and use `-oyaml` instead of `-ojson`)
- [ ] If possible/applicable, use `jsonpath`
- [ ] Test the updated installer on OpenShift (or MiniShift)

**Comment by agrimmer** [comment]
With my PR https://github.com/keptn/keptn/pull/2022, the Keptn installer is now distributed as Helm-chart and does not require yq anymore. Therefore, I am closing this issue.
