### ISSUE TITLE
Show status information in stages when stage is empty (no service deployed)

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#1860]
In case a user has created a project (+ onboarded a service), but not yet deployed an artifact, the stages are empty and might cause doubt.

![image](https://user-images.githubusercontent.com/729071/83224573-04668400-a17e-11ea-8cd8-5f2550456df2.png)

To inform the user about the current status and to provide help, two info messages are required as shown in the definition of done.

**Definition of Done:**
If no deployment.finished event has been received for a stage, 
- [ ] show an info message on the stage.
- [ ] provide a help message with a link to the `keptn send new-artifact` command (see details page on the right)  

![image](https://user-images.githubusercontent.com/729071/83224263-43e0a080-a17d-11ea-9b29-0936e8aa8c65.png)

**Comment by ermin-muratovic** [comment]
If there is no services onboarded yet, I show a different message with a link to instructions "how to onboard a service". This message is displayed in the "services" and in the "environment" tab. See images below.

![no-service-onboarded](https://user-images.githubusercontent.com/6098219/85740130-a89e0500-b701-11ea-86f2-c921c1b514cb.jpg)

![no-service-onboarded-2](https://user-images.githubusercontent.com/6098219/85740202-b6ec2100-b701-11ea-98a7-98da8e54acb8.jpg)

When there is a service onboarded, but no deployment available yet on that stage, then I show the instructions how to deploy a service using "keptn send new-artifact".

![no-service-onboarded-but-not-deployed](https://user-images.githubusercontent.com/6098219/85740375-ddaa5780-b701-11ea-9938-c07447ee9d3e.jpg)
