### ISSUE TITLE
Keptn support for multiple plans

### ISSUE THREAD

**Issue by pcjeffmac** [keptn/keptn#1863]
**Current situation:**
* If you install on EKS, Keptn install writes the authentication information to the  ~/.keptn/.keptn 
* If you then install on gcloud, you loose the authentication information to EKS. As a result, you would need to backup the ~/.keptn/.keptn manually, then revert or change this file for each cloud environment.

**Idea:**
Provide a way to switch from EKS to gcloud or any other vendor without loosing the authentication information.  

**Describe alternatives you've considered**
* I like the approach that kubectl offers by setting an environment variable KUBECONFIG, which can then point to a Keptn config file. So we could have KEPTNCONFIG which by default points to ~/.keptn/.keptn (that would already be the default for linux) and if the user chooses to overwrite it, it would look like this:
`KEPTNCONFIG=./my-cluster-keptn-config  | keptn send-event new-artifact ...`
* Creating a symlink to the necessary file with the relevant authentication information.

**Comment by supra08** [comment]
I would like to take up this issue to gain some insight.
@christian-kreuzberger-dtx @johannes-b

**Comment by christian-kreuzberger-dtx** [comment]
Reopening this, linking PR #2468
