### ISSUE TITLE
Version checker interrupts user when there's an error

### ISSUE THREAD

**Issue by gabrielprioli** [keptn/keptn#1864]
**Environment**

* Client OS (e.g., Linux, OSX, Windows): 
Windows 10 running WSL 1.
Linux 4.4.0-18362-Microsoft #836-Microsoft Mon May 05 16:04:00 PST 2020 x86_64 GNU/Linux
Description:    Debian GNU/Linux 9.12 (stretch)
* Keptn Version (`keptn version`): CLI version: 0.6.2
* Kubernetes Cloud Provider (e.g., GKE, AKS): AKS
* Kubernetes version (`kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-13T17:40:34Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}

**Affected Component**

* [ ] Docs
* [x] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [ ] Bridge
* [ ] Gatekeeper
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**

When I issued the command

`keptn create project sockshop --shipyard=./shipyard.waml`

to create a project, I got the error message below:

_error when fetching CLI version infos: Get https://get.keptn.sh/version.json: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)_

**To Reproduce**

I don't know how to reproduce, because @grabnerandi told me on Slack that the version checker runs once a day, so I don't know how to anticipate when it will run.

**Expected behavior**

I would expect that the version checker should not be running in the middle of a user command.

**Current behavior**

Currently, the version checker runs at a time out of control from the user.

**Screenshots**

![image](https://user-images.githubusercontent.com/836297/83580562-be5d4780-a512-11ea-9ce1-53ac9aa946be.png)

**Additional context**

When looking in https://github.com/keptn/keptn/blob/efe9eb839c8f4d6b38b5a6a6301aa8503d14557b/cli/pkg/version/version_checker.go#L123 tells me the error message is from the method `getNewerCLIVersion`. I

As a user it's not very friendly to have this interrupt something I was doing. Furthermore, it's not clear to the user if everything is alright. Should I run the "create project" again? Should I ignore the error?

**Comment by agrimmer** [comment]
Hi @gabrielprioli,
thanks for reporting! 

You are right, the version check is executed before the actual user command is executed in order to inform the user of a new CLI version.

However, a failing version check does not have any impact on the executed user command.
In order to clarify this, we should change the error message as follows:
"Failed to check CLI version updates: ERR_MSG"
"This has no impact on the in the following executed command".

@gabrielprioli : Would this clarify the behavior?

**Comment by gabrielprioli** [comment]
@agrimmer in a scenario where the following command is successful, adding the second message as you proposed would make it clear.

However, suppose another scenario where the subsequent user command does, in fact, fail. Then this is what the user would see:

"Failed to check CLI version updates: ERR_MSG"
"This has no impact on the in the following executed command".
"Timeout while connecting to Kubernetes cluster"

Based on this output, do you agree that even though the message is true (version checker has no impact), it is not helpful to the user? In this situation, the user could become skeptical, specially because they didn't start the version checking process. Precisely because the version checker is independent, a message from it cannot "predict" what's going to happen with the next command.

---
An alternative solution I would like to propose is to not run the version checker. Shouldn't we use the established paradigm that the user needs to maintain it's software up-to-date by running something like "keptn update"?

**Comment by agrimmer** [comment]
You are right that any error message which could occur when checking the CLI version could be confusing.
Therefore, I propose to not log any error message of the CLI version check.

However, automatically checking the CLI version once a day and informing the user is very useful. Furthermore, also other CLIs follow this approach.

**Comment by grabnerandi** [comment]
Agree. We should keep the version check but just dont display an error message. The only exception I see would be for "keptn version" where a user intentionally wants to know the installed keptn version and I think here - checking for a newer version and potentially reminding them that the online check failed is good

**Comment by gabrielprioli** [comment]
> Therefore, I propose to not log any error message of the CLI version check.
Ok! That is better.

> However, automatically checking the CLI version once a day and informing the user is very useful. Furthermore, also other CLIs follow this approach.
Cool, thanks!

**Comment by gabrielprioli** [comment]
Would this be a good first issue?

**Comment by johannes-b** [comment]
From the context of the problem, I would consider it as `good-first-issue`. 

**Tasks:**
- [ ] Don't log an error message of the CLI version check
- [ ] Except for the command `keptn version`

@gabrielprioli: Would you like to implement it?

**Comment by gabrielprioli** [comment]
Yes @johannes-b let me give it a shot!

Here's my quick assessment:

Here we should output everything to the user, because it is the version command:
https://github.com/keptn/keptn/blob/4f346e7b4bddc241a83aeef9255c34da6ced8b2c/cli/cmd/version.go#L51

Here we want to suppress if there is an error message
https://github.com/keptn/keptn/blob/d118d835287ada4d154abb28961a17c0545e6401/cli/cmd/root.go#L47

There are 3 possible points of error in https://github.com/keptn/keptn/blob/efe9eb839c8f4d6b38b5a6a6301aa8503d14557b/cli/pkg/version/version_checker.go#L140

1) if loading the current cli config fails

https://github.com/keptn/keptn/blob/efe9eb839c8f4d6b38b5a6a6301aa8503d14557b/cli/pkg/version/version_checker.go#L145

2) if checking the new version fails

https://github.com/keptn/keptn/blob/efe9eb839c8f4d6b38b5a6a6301aa8503d14557b/cli/pkg/version/version_checker.go#L153

3) if storing the new cli config fails

https://github.com/keptn/keptn/blob/efe9eb839c8f4d6b38b5a6a6301aa8503d14557b/cli/pkg/version/version_checker.go#L181

Questions:
1. Do we supress all 3 messages?
2. Should I add a third argument to CheckCLIVersion to determine if error messages should be printed? That is in terms of code structure, how you guys would want the end result to be.

**Comment by johannes-b** [comment]
Great assessment of the issue!

1. Yes, let's suppress all three messages.
2. I agree that a third argument for controlling the log output would make sense, for example, a boolean called `verbose`. `verbose=true` ... shows messages, `verbose=false` hides them.

**Comment by agrimmer** [comment]
Alternatively to introducing a new argument, would be temporarily increasing the `LogLevel` to `QuietLevel` (https://github.com/keptn/keptn/blob/efe9eb839c8f4d6b38b5a6a6301aa8503d14557b/cli/pkg/logging/log_printer.go#L9).
This would save lots of if/else statements.

**Comment by agrimmer** [comment]
I proposed to only temporarily set the `LogLevel` to `QuietLevel`.
More precisely, in the Execute function here https://github.com/keptn/keptn/blob/b0180c31bd7cfcd0539ab87cb5beb6ca28b0d0b6/cli/cmd/root.go#L45 set the `LogLevel` to `QuietLevel` and restore the value of the `LogLevel` after the CheckCLIVersion check.

Using this strategy, we do not change the log level for e.g. a `create project`.

If you have any further questions, please let me know.

**Comment by johannes-b** [comment]
@gabrielprioli - Andreas' approach of managing the log output by controlling the `LogLevel` is a good idea since we don't need to add if-else statements for each log message. Can you please go this way.

**Comment by christian-kreuzberger-dtx** [comment]
Hi @gabrielprioli , has there been progress on this issue? Please let us know if you still plan to finish this. Thanks!

**Comment by gabrielprioli** [comment]
Hi Christian, I apologize for the lack of update. I have started reading the documentation related to development and understanding what I need to install to be able to compile and test an issue like this.

But then I actually left on vacation and was not able to continue, I got too distracted. I'll be back in the office next monday, then I'll be able to focus.

**Comment by christian-kreuzberger-dtx** [comment]
Thanks for the update! 

In case you don't find the time in doing it (which is perfectly fine), just let us know and we will re-assign it ;)

**Comment by gabrielprioli** [comment]
Ok Christian, thanks!

**Comment by gabrielprioli** [comment]
@christian-kreuzberger-dtx I apologize for the delay again, but I really won't be able to focus on this one right now. Coming back from vacation I have multiple things to take care so with regards to keptn I'll focus only on the ansibletower-service so please reassign this issue?

**Comment by christian-kreuzberger-dtx** [comment]
Thanks, I'll get this re-assigned!

**Comment by checkelmann** [comment]
I will take this one.
