### ISSUE TITLE
Prometheus service uses deprecated API

### ISSUE THREAD

**Issue by thschue** [keptn/keptn#1869]
**Is your feature request related to a problem? Please describe.**
On kubernetes 1.16, some apis got deprecated (https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/). As this has not been adapted in the prometheus-service, the service is currently not working on k8s 1.16+
 
**Describe the solution you'd like**
Prometheus Service deploys objects with a supported API

**Comment by johannes-b** [comment]
Moved issue to: https://github.com/keptn-contrib/prometheus-service/issues/51
