### ISSUE TITLE
Premature version check in CLI when installing

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#1871]
When installing Keptn, the version check for supported Kubernetes versions is done before the actual cluster is selected. 

```
keptn install --platform=aks
Used Installer version: docker.io/keptn/installer:0.6.2
Error: Keptn requires Kubernetes Server Version: >= 1.13, <= 1.15
```

Executing this command checks if the cluster that is *currently* configured in the kubeconfig is conforming to the supported kubernetes version. the check fails if either the cluster is unavailable or the version is not supported.

the desired solution is that the installer asks *first* for the cluster credentials to make sure the right cluster is checkd and *second* checks the cluster version.

right now the workaround is to configure kubectl manually to point to the correct cluster and then execute the installer again. unfortunately this is not documented.  

**Environment**

* Keptn Version (`keptn version`): 0.6.2

Additional info in the Slack thread: https://keptn.slack.com/archives/CNRCGFU3U/p1590629823308900

**Comment by christian-kreuzberger-dtx** [comment]
This is the relevant section of the CLI code:
https://github.com/keptn/keptn/blob/35dc8240b3988bc31b2beb63427591556f55d09e/cli/cmd/install.go#L220-L227

and I believe it just needs to be moved after this section:
https://github.com/keptn/keptn/blob/35dc8240b3988bc31b2beb63427591556f55d09e/cli/cmd/install.go#L230-L244
