### ISSUE TITLE
Bridge/CI: Add automated linting and prettier checks

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1885]
Same as with GoLang, we should automatically lint the code for Keptn Bridge, and decline PRs that contain linting errors.

This will also require fixing existing linting/code-style errors in Keptn Bridge.

In addition, also [prettier](https://prettier.io/) should be introduced together with an [`.editorconfig`](https://editorconfig.org/) file to get achieve a common code style.

# Definition of Done

- [ ] Introduce similar or same linting rules to as https://github.com/dynatrace-oss/barista for the `bridge/` subfolder and apply them to the code
- [ ] GitHub Action that rejects PRs if they have linting add/or prettier errors
- [ ] add editorconfig to the Bridge

**Comment by ermin-muratovic** [comment]
I would suggest the Angular CLI, which provides built-in support for Typescript code linting. The default tool used by angular CLI is TSlint. The basic CLI command used for linting an angular project is
· `ng lint <project> [options]`

I reported #2915 as duplicate. Will close that one as duplicate of this issue.

**Comment by thisthat** [comment]
This will be done after the linting is migrated to ESLint (#4648).

**Comment by ermin-muratovic** [comment]
Added one more task here, to document IDE setup for developers to have same settings and have easier onboarding of new developers and contributors.
https://github.com/keptn/keptn/issues/4739

**Comment by thisthat** [comment]
Closed in favor of #4648
