### ISSUE TITLE
AKS resource groups checks are too strict?

### ISSUE THREAD

**Issue by gabrielprioli** [keptn/keptn#1895]
We are validating the resource group name with the following regex

https://github.com/keptn/keptn/blob/f0098529b4722079a4b6ca70e38cfdfaa45ebacb/cli/cmd/installAKS.go#L90

which would accept only letters or numbers separated by dash. 

I have created a resource group using underscores:

![image](https://user-images.githubusercontent.com/836297/84046753-e28cae80-a980-11ea-9eb2-8b2176ec6efd.png)

The keptn installer won't let the user continue because of that.

![image](https://user-images.githubusercontent.com/836297/84046839-f89a6f00-a980-11ea-9ecb-ded10cda171a.png)

It is true that **cluster** names cannot have underscores but resource groups can.

**Comment by christian-kreuzberger-dtx** [comment]
Thanks for bringing this up.

In addition to the check being too strict, an error message suggesting that the resource group contains invalid characters would help too.

Though IMHO we should remove the check, if the user enters a wrong azure resource group I'm sure azure CLI will tell us.

**Comment by agrimmer** [comment]
Right, the CLI checks for the cluster, resource group, etc. are too restrictive. Let's remove them.

**Comment by christian-kreuzberger-dtx** [comment]
We are simplifying our CLI in https://github.com/keptn/keptn/issues/1967, and will no longer use azure cli and the options resource groups, but rely on the `kubectl` context that is currently set.

I'l lleave this open, but once #1967 is implemented this issue should disappear ;)

**Comment by agrimmer** [comment]
Closing this issue because issue https://github.com/keptn/keptn/issues/1967 is completed.
