### ISSUE TITLE
Clicking the lighthouse heatmap, details of wrong column 

### ISSUE THREAD

**Issue by heydenb** [keptn/keptn#1911]
When clicking on the HeatMap in Keptn 0.6.2, the results appear of two columns earlier.

![image](https://user-images.githubusercontent.com/2580178/84498312-bc347f00-acb0-11ea-9fae-f69f16ef5121.png)

Clicked on the last column, top row in screenshot above. Results of 3 days ago.

**Comment by christian-kreuzberger-dtx** [comment]
Hi Bert,

we released an EAP version of Keptn's Bridge last week. Could you do us a favour and check if the bug still exists in the EAP version?
you can find instructions on how to install it here: https://keptn.sh/docs/0.6.0/reference/keptnsbridge/#early-access-version-of-keptn-bridge

**Comment by johannes-b** [comment]
As shown by Rob here https://github.com/keptn/keptn/issues/2094, sending a `sh.keptn.event.start-evaluation` without teststrategy results in the fault state mentioned here.

**Comment by heydenb** [comment]
> As shown by Rob in #2094, sending a `sh.keptn.event.start-evaluation` without teststrategy results in the fault state mentioned here.

I don't think this has anything to do with this issue #1911 which is already fixed.

**Comment by agrimmer** [comment]
Thank you Bert @heydenb for validating the fix!
As it is fixed, I am closing this issue.
