### ISSUE TITLE
quality-gates integration test randomly fails: Failed to check that the project exists via the API.

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1918]
It appears that the following check whether a project exists via configuration-service fails in the quality-gates integration test:

https://github.com/keptn/keptn/blob/15978523db13e22c64923cccee9e8cc4d7c98647/test/test_quality_gates_standalone.sh#L60-L79

Output is:
```
Creating a new project without git upstream
WARNING: Creating a project without Git upstream repository is not recommended. 
You can configure a Git upstream repository using: 
keptn update project PROJECTNAME --git-user=GIT_USER --git-token=GIT_TOKEN --git-remote-url=GIT_REMOTE_URL
Starting to create project
ID of Keptn context: b679c585-09db-4862-ab69-f447d43e4b27
Project musicshop created
Stage hardening created
Shipyard successfully processed
Failed to check that the project exists via the API.
```

What's weird is that it randomly fails, e.g.: https://travis-ci.org/github/keptn/keptn/builds/698829804
![Screenshot from 2020-06-16 12-40-36](https://user-images.githubusercontent.com/56065213/84764820-9a980800-afce-11ea-901c-d8c476a55ea1.png)

I don't think it's a timing issue, because we have a `sleep 10` after the create project CLI call.

**Comment by agrimmer** [comment]
We do not see this issue anymore.
