### ISSUE TITLE
configuration-service: Implement GET ​/project​/{projectName}​/stage​/{stageName}​/service​/{serviceName}​/resource

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#1924]
**Problem statement:**
We have received extension requests for, e.g., jmeter-service, where a user wants the jmeter-service to have access to additional uploaded resources such as data files. The approach would be to let users upload resources to a particular folder, e.g: `/jmeter`, and then have the jmeter-service download ALL resources in its subfolder before executing the test. The problem right now is that there is no way for a Keptn-service to say: _Give me all uploaded resources_. That's why we would need a new API call that can list resources in a particular project/stage/service and optionally specify a resourceURI pattern, e.g: /jmeter

**Proposed feature:**
I would like to propose a call similar to this: `GET /project/{projectName}/stage/{stageName}/resource/{resourceURI}?retrieveList=true`

This would extend the existing endpoint and returns those resources matching the resourceURI. This call should then also work for the other GET resource calls such as the one on project and stage level

**Describe alternatives you've considered**
Alternatively, we would need to specify another file, e.g: jmeter.conf where we list all data files that should be downloaded. While this is doable it means additional configuration efforts

**Comment by agrimmer** [comment]
Thanks for the issue!

We already have these endpoint with the URL
`GET
​/project​/{projectName}​/stage​/{stageName}​/service​/{serviceName}​/resource`
`GET /project/{projectName}/stage/{stageName}/resource`
`GET /project/{projectName}/resource`.

While the GET on project- and stage-level are already implemented, this is **not** true for the service level. You currently get the following message:
**"operation service_resource.GetProjectProjectNameStageStageNameServiceServiceNameResource has not yet been implemented"**

Of course, you can start using the endpoint for the stage and filter only resources that are contained e.g. in `jmeter` (see screenshot).
<img width="1071" alt="Screen Shot 2020-06-17 at 12 38 01" src="https://user-images.githubusercontent.com/10980861/84888426-9257cf80-b097-11ea-9d2d-a4008903f521.png">

**Comment by imrenagi** [comment]
Can I take this?

**Comment by johannes-b** [comment]
Hi @imrenagi, 
many thanks for working on that one! I have assigned you this issue and pulled it into our Kanban board for [Working Items](https://github.com/keptn/keptn/projects/29).

If you have questions regarding the issue, please post a comment.

**Comment by imrenagi** [comment]
Hi @johannes-b , I cant find good time to start working on this. Im still using my time to understand the code base and the interaction between these code. If somebody else would like to tackle this problem, feel free to reassign it to them. so sorry about this.

**Comment by johannes-b** [comment]
Hi @imrenagi, 
no rush! Take the time you need. :)

**Comment by johannes-b** [comment]
Hello @imrenagi, 
I'm just asking if you still want to work on this issue? 
(Every contribution is highly appreciated. :smiley: )

**Comment by imrenagi** [comment]
Hi @johannes-b,

I havent had enough time to work on this yet. Please assign this to someone else if you want. So sorry for this 🙏

**Comment by grabnerandi** [comment]
Hi Team. I am just running into a blocker because this endpoint is not available. I am trying to extend the JMeter service as described here - - but because this API is not implemented - PLUS - because the GoUtils also dont implement GetAllProjectResources (even though the API Endpoint) works -it makes it a bit hard right now

**Comment by daemon1024** [comment]
Hello. Can I work on this?

From what I understand right now, I need to implement 
https://github.com/keptn/keptn/blob/1c121959b492c3e42bfbdd60f32eb17cb47bcda6/configuration-service/handlers/service_resource.go#L25-L27

with something similar to

https://github.com/keptn/keptn/blob/1c121959b492c3e42bfbdd60f32eb17cb47bcda6/configuration-service/handlers/stage_resource.go#L19

so that it returns all resources at service level.
