### ISSUE TITLE
Make installer more robust (platform AKS)

### ISSUE THREAD

**Issue by roman-ferstl** [keptn/keptn#1927]
We ran into the issue that "keptn install" failed on AKS as we did not perform "`az login`" beforehand. We then had corrupt configurations for kubectl and keptn cli resulting in errors on each retry of keptn-install. Our solution was to make a new connection manually via:
`az aks get-credentials --resource-group myResourceGroup --name myAKSCluster`
Note that the errors occured on the client side before reaching the AKS instance.

Maybe a "keptn reset" command or a sanity check before the actual installation is peformed would help already.

**Comment by christian-kreuzberger-dtx** [comment]
Hi!

This is most likely related to https://github.com/keptn/keptn/issues/1871, where we fixed an issue that we executed the version check of the Kubernetes Cluster before we actually made sure that we are connected to the correct cluster.

That being said, I agree that the installation process needs to be simpler and less error-prone. For me it would make perfect sense to skip anything platform specific (e.g., azure, aws, gcloud) and just use the current Kubernetes context.

**Comment by agrimmer** [comment]
This issue can be closed due to https://github.com/keptn/keptn/pull/2005, which will be available with Keptn 0.7.0

Technically, the CLI now only differentiates between kubernetes (requires your kube-config to point to the cluster where Keptn should be installed) and OpenShift but not AKS, GKE, etc.
