### ISSUE TITLE
Switch Keptn Installation Option --use-case=quality-gates vs. --use-case=continuous-delivery vs. control-plane

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1940]
~The installer option `--use-case=quality-gates` is misleading in certain cases, and we should rename it to `--control-plane` or `--use-case=control-plane` (I vote for `--control-plane` though).~

~Regarding the naming of the option: In the future there might also be an installer option called `--delivery-plane` or `--execution-plane`.~

I have updated my text based on the comments below (including [this comment](https://github.com/keptn/keptn/issues/1940#issuecomment-648022352)).

The installer option `--use-case=quality-gates` is misleading in certain cases. In addition, `keptn install` installs everything (including helm-service, jmeter-service, ...), which in the future might be applied using a uniform (e.g., `keptn uniform apply continous-delivery.yaml`).

The keptn CLI and the installer need to reflect the following options/workflows in the **future**:

1. Install just Keptn Control-Plane (allows quality-gates and remediation use-cases)
    ```console
    keptn install control-plane
    ```
1. Install Keptn Excecution-Plane (whatever that is) and connect it to the control-plane
    ```console
    keptn install execution-plane --api-url=$API_URL --api-token=$API_TOKEN
    ```
1. Install continous delivery stuff like helm, helm-service, jmeter, ... on the execution-plane
    ```console
    keptn uniform apply -f continous-delivery.yaml
    ```

As of 0.7, we don't have a separation of control-plane and execution-plane, and we don't have uniform support. In addition, 0.7 lists the following **core operations/integrations** in the [docs](https://keptn.sh/docs/develop/):

* Continuous Delivery
* Quality Gates
* Automated Operations

IMHO those three should be supported by the installer, however there is a certain overlap (e.g., lighthouse is needed for all three of them), and we should not make the installation options too complicated:

Therefore the installation options should look as follows:

* `keptn install` will install a MVP of Keptn, which is the control-plane including lighthouse-service and remediation-service. This allows implementation of the quality gates and automated operations use-cases.
* `keptn install --use-case=quality-gates` is just an alias for `keptn install`
* `keptn install --use-case=continuous-delivery` will apply our CD manifest (and we document that if one wants to install this afterwards, it's required to install Istio, Helm and do a `kubectl apply -f https://raw.github.com/keptn/.../continuous-delivery.yaml`).

**Defintion of Done**: 

- [ ] Introduce a new option `--use-case=continuous-delivery`
- [ ] `keptn install` installs JUST the control-plane, not the full installation
- [ ] `keptn install --use-case=quality-gates` still needs to work (but installs the control-plane)
- [ ] Deprecate the `--use-case=quality-gates` option in `keptn install`
- [ ] Installer scripts/image adapted to reflect the changes in `keptn install`
- [ ] Docs regarding installation updated 
- [ ] Tutorials updated

**Comment by christian-kreuzberger-dtx** [comment]
Open question: I believe that remediation-service should be part of the control-plane installation, therefore allowing the self-healing use-case (e.g., with feature-toggle) to be used.

**Comment by agrimmer** [comment]
Thanks for the proposal! I would like to propose an alternative:

Going forward, I think `keptn install` without any option should "only" install the control-plane. Therefore, I would propose to not introduce a flag `--control-plane`. That means, when a user uses `keptn install` w/o any flag, he/she can do the quality gates as well as remediation UC.
In order to support the delivery use case, I would introduce a flag `--use-case=delivery` or `--delivery`.

Does this make sense?

**Comment by christian-kreuzberger-dtx** [comment]
That makes perfect sense.

So `--use-case=delivery` could install `helm-service` (though I think we might have a dependency on helm-service for create service?) and `jmeter-service`, while anything else (lighthouse, remediation-service, api, mongodb, ...) is considered to be installed by default?

**Comment by thschue** [comment]
Would it be possible to introduce something as

**Comment by grabnerandi** [comment]
I also like the idea of "keptn install" simply installing the control plan. On top of that I assume our "uniform" concept and future implementation of it will take care of all the rest so that nothing else is really needed.
For a quality gate only installation this would mean that "keptn install" is all I need
For a "Performance as a Service" I need to additionally install the testing tool support, e.g: Jmeter-service
To enable support for a monitoring tool I need to install the respective monitoring tool services.
As I said - in the future these additionall installs will be handled by our better support for uniforms. But - in the meantime I can live with it. We have done something simliar with our k3s install use case where a separate installation script installs additonal components such as jmeter, dynatrace or prometheus
The big question is how someone would install the "helm service" after running "keptn install"

**Comment by christian-kreuzberger-dtx** [comment]
> Would it be possible to introduce something like keptn install control-plane|execution-plane|all? We could also default to all (to be compatible to the current mechanism), but i think this would be more straight-forward than specifying a use-case

I also fancy the idea of not specifying a use-case, though right now this is what we support.

In addition, the term execution-plane is not something that Keptn is using as of right now (we know it is possible and we know what we need to do it, and it's on the roadmap, just saying it's not fully specified and support at the moment).

Anyway, as @grabnerandi  mentioned: our uniform concept might solve many of the aforementioned problems. For now, we need to find the option that will be compatible with our uniform concept in the future.

IMHO this is what we should aim for (as of right now):

* `keptn install` - will install the control-plane
* `keptn install --use-case=delivery` will install the battery-included services for delivery (Jmeter, helm), which in the future will be solved by a uniform that is applied (e.g., `keptn uniform apply delivery.yaml`)
  * Maybe we should rename the option to `--uniform=delivery`? We don't have uniform implemented as of right now, but the Kubernetes Manifest with all the required services is as close as it gets.

**Comment by christian-kreuzberger-dtx** [comment]
Had a quick discussion with @thschue and we had the following conclusions:

* `keptn install --use-case=quality-gates` should still work (but print a deprecation warning)
* In the future, we might want to have a mechanism in place similar to Kubernetes worker nodes, e.g.:
  * Step 1: Install Keptn Control-Plane: `keptn install [control-plane]`, store `API_URL` and `API_TOKEN`
  * Step 2: Install Keptn Execution-Plane on a separated cluster: `keptn install [execution-plane] --api-url=$API_URL --api-token=$API_TOKEN`
  * Step 3: On the execution-plane install the delivery uniform: `keptn uniform apply continous-delivery.yaml`
