### ISSUE TITLE
Keptn CLI uses wrong Kubernetes Context/Profile

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1942]
Right now integration tests on K3s fail as the installer fails to check if the keptn namespace exists:

```console
$ test/test_install_kubernetes_quality_gates.sh
Installing keptn on cluster
Availability of provided image cannot be checked.
Used Installer version: keptn/installer:latest
Installing Keptn ...
Error: Failed to check if namespace keptn already exists: stat /home/travis/.kube/config: no such file or directory
[keptn|ERROR] [2020-06-19 16:04:47] keptn install failed
[keptn|ERROR] [2020-06-19 16:04:47] Keptn Test failed.
```

Please note that for K3s to work, we export `KUBECONFIG` as follows:
```
export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
```

However, the error message coming from the CLI suggests that we are trying to access `/home/travis/.kube/config`, which is definately something else.

Funny enough, if I try the same locally, the CLI tells me that I already have Keptn installed:
```
$ keptn install --platform=kubernetes --use-case=quality-gates
Used Installer version: docker.io/keptn/installer:latest
Installing Keptn ...
Please enter the following information or press enter to keep the old value:

Please confirm that the provided information is correct: 
Cluster: default

Is this all correct? (y/n)
y
Using a file-based storage for the key because the password-store seems to be not set up.
Error: Existing Keptn installation found in namespace keptn.
```

This is definately not the case, I'm pretty sure we are using the wrong Kubernetes Context here.

This error started appearing after the RBAC changes were merged.

**Comment by agrimmer** [comment]
This bug is caused by using the Kubernetes libraries for checking and creating namespaces (for the rest of the install, `kubectl` is used). However, our Kubernetes library assumes that the kube-config is located in the home directory, i.e. see https://github.com/keptn/kubernetes-utils/blob/9c7eb9b64a2698dd61bd1fb21b3fc7f48f442c1c/pkg/kubernetes-utils.go#L246.
In order to fix this bug, we can either also use the `KUBECONFIG` env-var in our library or use `kubectl`.

**Comment by christian-kreuzberger-dtx** [comment]
Thanks for analyzing. I don't think relying **just** on `KUBECONFIG` will work. We should mimic the same behaviour that `kubectl` is doing, I wonder if that's something that Kubernetes library is able to do?
