### ISSUE TITLE
CLI: kubectl version check incorrectly reports if no connection to cluster could be made

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1944]
Source: https://keptn.slack.com/archives/CNRCGFU3U/p1592334110459600

In 0.6.2, the version check reports that the Kubernetes Version is invalid in the case that no connection to the Kubernetes server could be made:

```
$ kubectl get nodes
Unable to connect to the server: net/http: TLS handshake timeout 
```

However, when the user tries to install, they only see this:

```
$ keptn install ...
Used Installer version: docker.io/keptn/installer:0.6.2
Error: Keptn requires Kubernetes Server Version: >= 1.13, <= 1.15
```

---

The relevant part of the code is here:
https://github.com/keptn/keptn/blob/5e444816db7626d51ef588e874a23df1b387dafa/cli/cmd/install.go#L201-L207

https://github.com/keptn/keptn/blob/5e444816db7626d51ef588e874a23df1b387dafa/cli/pkg/kube/kube_utils.go#L43-L46

https://github.com/keptn/keptn/blob/5e444816db7626d51ef588e874a23df1b387dafa/cli/pkg/kube/kube_utils.go#L29-L32

An easy fix would be to check the error value of `CheckKubeServerVersion`. If it returns an error, we need to return that error (right now we create a new error object and only print the error when verbose logging is active).

**Comment by imrenagi** [comment]
I will take this
