### ISSUE TITLE
Openshift installation: start of api-gateway-nginx fails with Permission denied error

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#1951]
With the current RBAC rules of the master, the `api-gateway-nginx` fails to start on Minishift 1.34.2 with 
`2020/06/23 19:10:35 [warn] 1#1: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:1
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:1
2020/06/23 19:10:35 [emerg] 1#1: mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)
nginx: [emerg] mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)`

A short Google search pointed me to https://medium.com/bitnami-perspectives/non-root-containers-to-show-openshift-some-love-3b32d7218ac6

**Definition of Done**:
- [ ] *Master* version of Keptn can be installed on Minishift

**Comment by christian-kreuzberger-dtx** [comment]
For debugging purposes, this is the manifest that we apply:
https://github.com/keptn/keptn/blob/master/installer/manifests/keptn/api-gateway-nginx.yaml

In particular, the following information might be needed:

Image: `nginx:1.17.9`

```
  nginx.conf: |
    user nginx;
```

**Comment by christian-kreuzberger-dtx** [comment]
I found that nginx inc. provides an alternative non-privileged docker image:

* https://hub.docker.com/r/nginxinc/nginx-unprivileged
* https://github.com/nginxinc/docker-nginx-unprivileged

We should give that one a try, too.
