### ISSUE TITLE
CLI: When onboarding a helm chart, check for Kubernetes recommended labels

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1958]
Based on https://github.com/keptn/examples/issues/103 and https://github.com/keptn/examples/issues/91, a check in the Keptn CLI should be added to the onboarding command for checking Kubernetes recommended labels.

This does not need to be a strict check, but at least a warning would be nice.

**Definition of Done**

- [ ] CLI checks for Kubernetes recommended labels and prints a warning if they are not found (or only partially found)
- [ ] Update documentation regarding Helm charts and add the recommended labels to it

**Comment by anukul** [comment]
What is the expected level of information returned by the CLI in the warning? e.g. a generic message vs list of missing labels for each resource

**Comment by christian-kreuzberger-dtx** [comment]
I think in the CLI a warning message that contains the following output would be enough:
```
$> keptn onboard service ... --chart=my-chart/

Warning: You do not have Kubernetes recommended labels in your deployment template. Please checkout https://keptn.sh/docs/0.8.x/continuous_delivery/deployment_helm/#recommended-labels

```

Regarding docs, we can use the content from this PR to describe what it should look like: https://github.com/keptn/examples/pull/95/files, as well as refer to https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

**Comment by anukul** [comment]
I see that the Kubernetes docs mention the following:

> In order to take full advantage of using these labels, they should be applied on every resource object.

Do we only intend to enforce this for `Deployment` objects?

**Comment by christian-kreuzberger-dtx** [comment]
Good point.

We added these labels initially to deployment objects, as they are being picked up by monitoring tools, making it easier to configure those tools.

I believe it is sufficient for now if we just check and ~enforce~ recommend it on Deployment objects, as the main purpose of onboarding a service in Keptn is our continuous delivery use-case. We can always re-use the same logic later.

**Comment by christian-kreuzberger-dtx** [comment]
Please add output like this in case the labels are missing:

```
...
In case you want to fix this, please delete your service using keptn delete service, and onboard it again with labels in your helm chart.
```

**Comment by utibeabasi6** [comment]
hey, i would love to work on this @thisthat, if theres any way i can help let me know thanks

**Comment by thisthat** [comment]
Hey @utibeabasi6, this ticket is not relevant anymore since we deprecated the `onboarding` command
