### ISSUE TITLE
Installer: Remove anything related to istio, nginx and re-using those

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1960]
Details of KEP 18: https://github.com/keptn/enhancement-proposals/pull/18/files

Basically, the installer should only be responsible for installing the couple of manifests we need to run Keptn, similar to what is described in the [Manifest Installation](https://keptn.sh/docs/0.6.0/reference/manifest_installation/).

There is no need to wait for an IP address, Domain, or such.

CLI related things are in this issue: https://github.com/keptn/keptn/issues/1961

For the full installation we will require istio, however we do not check for Istio anymore within the installer pod. This is something that the CLI can do.

We will also no longer configure the ConfigMap which contains `KEPTN_DOMAIN`. This will break things - follow-up issues for this will be created.

**Mantra**: Less logic, more YAML files

# Definition of Done

- [x] Remove any manifests and any scripts that make use of Istio or nginx-ingress
- [x] Introduce a placeholder for the service-type of `api-gateway-nginx` which is then applied based on the CLi flag `--keptn-api-service-type` (note: the placeholder should default to `ClusterIP`
- [x] After creating the service `api-gateway-nginx` change the service-type to whatever the user has defined
- [x] Do not set `KEPTN_DOMAIN`
- [x] Do not generate SSL certificates
- [x] Remove installation options regarding gateway and ingress-install-option
- [x] Cleanup openshift installation and also reduce it to a bare minimum (Note: The manifest installation should also work with OpenShift)
- [x] Reduce RBAC roles of installer (e.g., istio, nginx), if needed/possible (attention: Installer needs at least to have the roles that helm-service requires)

**Comment by agrimmer** [comment]
I've temporarily uploaded the helm chart to https://storage.googleapis.com/keptn-installer/latest.
In order to use use it (e.g. for implementing issue #1961), you can use the following commands:
`helm repo add keptn https://storage.googleapis.com/keptn-installer/latest`
`helm install keptn keptn/keptn -n keptn --set continuous-delivery.enabled=true --create-namespace`
`helm uninstall keptn -n keptn`
