### ISSUE TITLE
CLI: keptn Install - Remove anything related to istio, nginx and re-using those

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1961]
Details of KEP 18: https://github.com/keptn/enhancement-proposals/pull/18/files

This is the pendant issue for https://github.com/keptn/keptn/issues/1960

The CLI will play a more important role in installing by providing convenience features for the end-user.

# Definition of Done

- [x] Remove the install option `--ingress-install-option` and its related code
- [x] Remove the install option `--gateway` and its related code
- [x] Introduce new options in the CLI for Keptn Install `keptn-api-service-type` (default to `ClusterIP`)
- [x] Installation should be considered successful if all deployments/pods have been started
- [ ] After successful installation, try to figure out how `api-gateway-nginx` is exposed:
  - ClusterIP: Bad luck, tell the user to use port-forward
  - NodePort: Try to get the external and internal IP address of the Node, as well as the port of `api-gateway-nginx` and try to reach the API via those
  - LoadBalancer: Try to get IP or Domain of the LoadBalancer (we might need to wait and retry depending on the cloud provider) and try to reach the API via that
  - Anything that is tried, notify the user about it (e.g., trying to access API via http://1.2.3.4:32111/)
  - If anything fails, show a link to the docs, and suggest the user to try a `kubectl port-forward ...`
- [x] **Only If the full installation is performed** (`keptn install --use-case=continuous-delivery`), make a sanity check if namespace `istio-system` exists and whether `istio-ingressgateway` is available. If not, show a warning and a link to our docs.
- [ ] Update installation docs such that installation requires istio, refer to the istio docs (see KEP 18 for details)

**Comment by agrimmer** [comment]
I started implementing this feature in the branch https://github.com/keptn/keptn/tree/feature/1961/remove-ingress-functionality but it heavily depends on #1960

**Comment by agrimmer** [comment]
Let's us the Helm-library in order to install Keptn. We already have this functionality in the `helm-service` https://github.com/keptn/keptn/blob/master/helm-service/controller/helm/helmv3_executor.go#L114
