### ISSUE TITLE
CLI: Remove or simplify --platform flag in keptn install

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1967]
Now that we are getting rid of things like ingress-gateways for our installer, I believe the `--platform` flag will be not needed anymore.

Instead, it's important that the user is currently connected to the Kubernetes cluster before installing Keptn, which is easy to check using `kubectl get nodes` and alike.

So IMHO the default for Keptn should be `--platform=Kubernetes`, which will ask the user if the current Kubernetes context is the correct one to install Keptn.
If anyone wants to override that and use e.g. `--platform=GKE`, then we can still ask the user for details and use the `gcloud` CLI.

The only exception to all of this might be OpenShift, as we deploy the openshift-route-controller (I believe this is only for the full installation).

# Definition of Done

- [ ] If no `--platform` flag is provided, we need to default to `--platform=kubernetes`
- [ ] If `--platform=kubernetes` is selected (it is, by default), we need to print information to the user about the cluster that `kubectl` is connected to, e.g., `kubectl get nodes`
- [ ] `--platform=openshift` needs to be available
- [ ] All other `--platform` flags are removed

**Comment by imrenagi** [comment]
I would like to take this one. is there any due date? im new to this project and would like to learn about it more.

**Comment by christian-kreuzberger-dtx** [comment]
Hi, and thank you for volunteering!

We would like to see this done within the next 7-10 days. If you need any help, please let us know!

**Comment by imrenagi** [comment]
Cool! 

@christian-kreuzberger-dtx 
can you elaborate more on these two DoDs?
- [ ]  `--platform=openshift` needs to be available
- [ ]  All other `--platform` flags are removed

**Comment by christian-kreuzberger-dtx** [comment]
the install command is currently split into the following files:

* https://github.com/keptn/keptn/blob/master/cli/cmd/install.go (root command)
* https://github.com/keptn/keptn/blob/master/cli/cmd/installAKS.go
* https://github.com/keptn/keptn/blob/master/cli/cmd/installEKS.go
* https://github.com/keptn/keptn/blob/master/cli/cmd/installGKE.go
* https://github.com/keptn/keptn/blob/master/cli/cmd/installKubernetes.go
* https://github.com/keptn/keptn/blob/master/cli/cmd/installOpenShift.go
* https://github.com/keptn/keptn/blob/master/cli/cmd/installPKS.go

we only need the root command, and the installs for kubernetes and openshift.
Also, in the root command, platform=kubernetes should be the default.

Does that help?

**Comment by imrenagi** [comment]
Yes. Thanks!

**Comment by imrenagi** [comment]
Since the PR for Definiton of Done num 1,3 and 4 has been merged, I will continue with the 2nd DoD.
