### ISSUE TITLE
Upgrader: Support the upgrade of 0.6.2 to 0.7.0 w.r.t. the simplification of the installer

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#1976]
With Keptn 0.7.0, we are implementing https://github.com/keptn/enhancement-proposals/pull/18/files, which could also have implications for our upgrader.
**This issue can be used to collect open issues for the upgrader.**

**Comment by johannes-b** [comment]
To be discussed: How to create a Helm release during the upgrade process?

**Comment by bacherfl** [comment]
As discussed, we agreed on the following workflow for the upgrader:

1. retrieve values needed for ingress-config (from "keptn-domain" ConfigMap)

2. delete keptn core components (kubectl delete -f …) -> keptn-datastore namespace still available

3. apply helm chart (distinguish between control-plane and continuous delivery)

4. set up ingress-config ConfigMap

5. move data from mongodb.keptn-datastore to mongodb.keptn

6. delete mongodb-datastore namespace
