### ISSUE TITLE
Add Kubernetes recommended labels to the Keptn Installation

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1996]
Same as in our examples, when installing Keptn the deployments should have [recommended labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/), especially the version.

Related: https://github.com/keptn/examples/issues/103, https://github.com/keptn/examples/issues/91

# Definition of Done

- [ ] The manifests that the Keptn Installer is applying have been extended with the recommended labels `version`, `part-of`, `component`, `name` (others, if applicable)

**Comment by imrenagi** [comment]
I will take this

**Comment by johannes-b** [comment]
Thanks for working on that!
