### ISSUE TITLE
COPY button SLO content

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#1997]
Similar to issue #1794, it would be great to have the COPY button also for the content of SLO file on the evaluation done events.

![image](https://user-images.githubusercontent.com/7677092/86376522-65a2db00-bc87-11ea-864f-7288bda0e38d.png)

**Comment by christian-kreuzberger-dtx** [comment]
Implementing this should be quite easy. Please look at PR #1977 to see how it's done for the JSON Payload.

**Comment by pahofmann** [comment]
I'd like to work on this issue.
