### ISSUE TITLE
Project creation failed when using Git-upstream for GitHub

### ISSUE THREAD

**Issue by imrenagi** [keptn/keptn#1998]
**Environment**

* Client OS (e.g., Linux, OSX, Windows): OSX 10.15.4
* Keptn Version (`keptn version`):  0.6.2
* Kubernetes Cloud Provider (e.g., GKE, AKS): GKE
* Kubernetes version (`kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-dispatcher", GitCommit:"f2a77f678d6baccda27740d700f6cba2754dfacf", GitTreeState:"clean", BuildDate:"2020-04-21T04:44:03Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.12-gke.3", GitCommit:"01ae07ff8c4f7336c34801b8611287fd7c370348", GitTreeState:"clean", BuildDate:"2020-06-05T18:13:14Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Affected Component**

* [ ] Docs
* [x] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [ ] Bridge
* [ ] Gatekeeper
* [ ] Datastore
* [x] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**
I tried to follow basic setup for keptn (https://keptn.sh/docs/0.6.0/installation/setup-keptn/). Unfortunately I got problem while trying this tutorial https://keptn.sh/docs/0.6.0/usecases/onboard-carts-service/

When I run:
```
keptn create project sockshop --shipyard=./shipyard.yaml --git-user=imrenagi --git-token=****** --git-remote-url=https://github.com/keptn-onboarding-carts-example/sockshop.git
```
I got logs as shown below:
```
Starting to create project
ID of Keptn context: 0585a47e-84c5-4a63-a06a-a10757c4657b
Creating project sockshop failed. Post http://configuration-service.keptn.svc.cluster.local:8080/v1/project: net/http: request canceled (Client.Timeout exceeded while awaiting headers).
```

**To Reproduce**

1. Install keptn for GKE (https://keptn.sh/docs/0.6.0/installation/setup-keptn/)
2. Try onboarding service tutorial
3. Run `keptn create project sockshop --shipyard=./shipyard.yaml --git-user=imrenagi --git-token=****** --git-remote-url=https://github.com/keptn-onboarding-carts-example/sockshop.git`

**Expected behavior**
There should not be any connection timeout when keptn do internal call to its component.

**Current behavior**
Request timeout

**Comment by christian-kreuzberger-dtx** [comment]
We have seen this before, it has something to do with the git remote not working as expected (I guess in this case it was GitHub having hickups again). Could you provide us a the logs of `configuration-service`?
```console
kubectl -n keptn logs svc/configuration-service
```
Also, can you try to do it again and see if the error persists?


**Some more details**

The worst thing about this is that it creates an inconsistent state, because if you now try to delete the project using
```console
keptn delete project sockshop
```
you will end up getting this error:
```
Starting to delete project
error when getting shipyard: {"code":404,"message":"Project resource not found"}
```

This was already reported in issue #1625 and we fixed it in our current master branch (which will be released as 0.7.0 soon).

In addition, we have improved troubleshooting for such issues in #1637 which is also going to be in 0.7.0.

**Comment by imrenagi** [comment]
If I try to create the project once again, I dont see any new logs coming to the `svc/configuration-service`.

Also, If i run 
```
keptn delete project sockshop
```

I didnt get error you gave above. instead:
```
Starting to delete project
Shipyard of project sockshop cannot be retrieved anymore. After deleting the project, the namespaces containing the services are still available. This may cause problems if a project with the same name is created later.
Project sockshop cannot be retrieved anymore. Any Git upstream of the project will not be deleted.
Project successfully deleted
```

**Comment by johannes-b** [comment]
Another Keptn user reported the same issue and we figured out that cloning a repository from GitHub takes now longer than 5 seconds. Unfortunately, the shipyard-service in version 0.6.2 has a timeout of 5 resulting in a timeout issue as mentioned above: 

```
Starting to create project
ID of Keptn context: 0585a47e-84c5-4a63-a06a-a10757c4657b
Creating project sockshop failed. Post http://configuration-service.keptn.svc.cluster.local:8080/v1/project: net/http: request canceled (Client.Timeout exceeded while awaiting headers).
```

The upcoming Keptn 0.7 release does not have this timeout anymore and will wait until the `git clone` is done. 

I will create a PSA in which is explained how to deal with the problem.

**Comment by johannes-b** [comment]
Thanks for reporting the issue, please see the PSA: #2021 to address your problem.
