### ISSUE TITLE
Keptn/CLI: Link point to non existing keptn/docs page

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#2007]
The link in the CLI command description points to a non-existing page: https://github.com/keptn/keptn/blob/master/cli/cmd/configure_domain.go#L51

**Definition of Done**:
- Update the link
- Provide a unit test to verify the link works

**Comment by imrenagi** [comment]
can i take this one?

**Comment by johannes-b** [comment]
Hi @imrenagi, 
great and thanks for implementing this issue!
