### ISSUE TITLE
As a CLI user, I want to get constant status updates during the execution of a command

### ISSUE THREAD

**Issue by dirkwall** [keptn/keptn#203]
When issuing CLI commands, as a user I want to have a constant stream of status updates that inform me about the progress and details on what is currently being worked on. Similar to what the output of `kubectl apply -f stuff` offers.

**Acceptance criteria**
- **Given** I'm a keptn CLI user
  **When** I issue and command using the keptn CLI
  **Then** I want to receive a constant stream of updates about the current operation and not only a success message at the end.

**Comment by jetzlstorfer** [comment]
Constant update stream working for 
- create project
- onboard service

Still working on 
- configure

**Comment by robertjahn** [comment]
Please ensure that the creation of a project validates the proper creation of the kubernetes configmap keptn-orgs.  We have seen issues when we onboard, but this does not get created and I have to manually fix using ```kubectl -n keptn edit configmap keptn-orgs```

**Comment by robertjahn** [comment]
Please ensure that the onboarding of a service validates that the repo was updated with the all the manifest files.  We have seen issues when we onboard that not all the files are created.  Out work around was to wait 30 seconds between each invocation of create project & onboard service.

**Comment by jetzlstorfer** [comment]
Constant update stream now also working for 
- configure

**Comment by jetzlstorfer** [comment]
Thanks @robertjahn for mentioning. The validation of the creation of k8s resources has to handled by the services themselves which report the status to the CLI. The CLI itself prints this information to the terminal but does not validate.
