### ISSUE TITLE
External PRs can be automatically merged [research only]

### ISSUE THREAD

**Issue by dirkwall** [keptn/keptn#204]
When an external contributor works on a fork of keptn, the PRs can't be merged automatically right now. The goal of this story is to enable automatic merging of PRs from forks.

**Acceptance criteria**
- **Given** I'm an external developer working in a fork of the keptn repository
  **When** I create a PR for keptn
  **Then** I want to see the results of the status checks build in the PR on GitHub

**Comment by dirkwall** [comment]
Reevaluate after architecture switch and monorepo switch.

**Comment by johannes-b** [comment]
Secret environment variables in Travis Build require special handling to accept external PR: https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions

**Comment by christian-kreuzberger-dtx** [comment]
This should work now. Closing this issue.
