### ISSUE TITLE
Show failed quality gate in Environment screen

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#2086]
When the last quality gate validation of a service in a particular stage failed:

![image](https://user-images.githubusercontent.com/729071/88032622-8059c880-cb3e-11ea-912a-7964109b26fa.png)

* The environment screen displays this by a red icon and the current number of failed quality gates in this stage.

(see stage: prod-cluster-A)
![3_delivery_overview](https://user-images.githubusercontent.com/729071/88031080-61f2cd80-cb3c-11ea-81b6-4fd8c32ce29c.PNG)

When clicking on the stage:
- The legend on the top right corner shows the number of currently failed quality gates, e.g. 1 Quality gate(s) failed (The click functionality of this label will be addressed in #2087)
- The service tile shows a message: 
   - if direct: `SLO evaluation of xyz:0.0.2 failed`
   - if blue/green: `SLO evaluation of xyz:0.0.2 failed and rollback to xyz:0.0.1 performed`
- The achieved score of the quality gate evaluation is shown with a link to the evaluation board. 
- The `Evaluation` label provides the link.

![image](https://user-images.githubusercontent.com/729071/89865377-e2da3d80-dbad-11ea-8feb-93cca5f40e59.png)

**Definition of Done:**
- [x] Failed quality gate evaluations are shown in the environment screen with a link to the evaluation board.
- [x] If the last evaluation of a service (in a particular stage) was successful, the failed quality gate is not shown in the environment screen.

**Comment by ermin-muratovic** [comment]
The environment screen now allows to easily see failed quality gates on a specific stage.
The stage tile shows the lighthouse icon in red and a count how many services on this stage are "broken".
By clicking on the stage and expanding the details for a service you get the details about the image that failed and the evaluation score. By hovering over the score, you can see the evaluation details in a popup.

![image](https://user-images.githubusercontent.com/6098219/91426880-6312cb00-e85d-11ea-8904-20411dfb2e49.png)

**Comment by johannes-b** [comment]
Currently, the label for "Services are out-of-sync" is inconsistent: 
![image](https://user-images.githubusercontent.com/729071/91799797-15fd7300-ec28-11ea-89ac-710cdf907d6b.png)


The label for "Services are out-of-sync" should work as follows:
- 0 Services are out-of-sync
- 1 Service is out-of-sync
- x Service is out-of-sync
