### ISSUE TITLE
Multi-cluster support

### ISSUE THREAD

**Issue by dirkwall** [keptn/keptn#211]
For example, I have three stages: dev, staging, production. Each stage runs in a separate Kubernetes cluster.

**Comment by dirkwall** [comment]
![image](https://user-images.githubusercontent.com/15996364/55083346-af277200-50a3-11e9-9531-f25470ed7265.png)

**Comment by johannes-b** [comment]
I closed this issue because it does not reflect the architecture of Keptn anymore.

**Comment by tolleiv** [comment]
As this is still the no#1 search result on the topic - maybe it's helpful for others that the official documentation for that is found >[here](https://keptn.sh/docs/0.8.x/operate/multi_cluster/)<.

**Comment by jmell-slg** [comment]
Seems to be removed in current version 0.18.x is this no longer supported? Thanks!
