### ISSUE TITLE
Misleading message in bridge if no deployment was done but evaluations happened

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#2112]
Love the new bridge and the information it gives me when no deployment has yet been done on a service.
However, there are two things as you can see in this screenshot:

![image](https://user-images.githubusercontent.com/675886/88286757-87750800-ccf1-11ea-9415-ff328aa8e753.png)

1: As I am using Keptn only for evaluation, the message "service not deployed yet" could be a bit misleading. It should say that - to get started send in some keptn send xxx events

2: If we want to let them know about delivery then we should fix the text. it should say "keptn send event new-artifact" and not "keptn send new-artifact"

**Definition of Done:**
- [x] Link text is changed to `keptn send event new-artifact` 
- [x] Don't show "Use keptn send event new-artifact ..." in case there is an open approval. This is shown in services and environments screen. 
- [x] Messages shows processed artifact for deployment.finished and evaluation.started (especially for evaluation.started, the image and tag must be provided; deployment.finished has it as default)
- [x] Document in keptn.sh/docs/bridge how to provide image and tag for evaluation use-case

**Comment by johannes-b** [comment]
I had to re-open this issue because there is still a problem with the label:

![image](https://user-images.githubusercontent.com/729071/91838502-e6616180-ec4d-11ea-9f0a-81b17fe1cb00.png)


Actually, the `sh.keptn.events.evaluation-done` does not contain the image/tag as required for this label:
```
{
  "contenttype": "application/json",
  "data": {
    "deploymentstrategy": "",
    "evaluationdetails": { }
    "labels": null,
    "project": "sockshop",
    "result": "fail",
    "service": "carts",
    "stage": "staging",
    "teststrategy": "real-user"
  },
  "id": "9cbd37ea-bd0e-45c7-981a-fcb2fb158ff2",
  "source": "lighthouse-service",
  "specversion": "0.2",
  "time": "2020-09-01T10:14:39.735Z",
  "type": "sh.keptn.events.evaluation-done",
  "shkeptncontext": "52b020e3-0fe5-45e9-9335-20ba546a93b8"
}
```

Instead, the `sh.keptn.event.start-evaluation` should be used to get the image/tag:
```
{
  "contenttype": "application/json",
  "data": {
    "deploymentstrategy": "",
    "end": "2020-09-01T08:36:06Z",
    "eventContext": null,
    "image": "docker.io/keptnexamples/carts",
    "labels": null,
    "project": "sockshop",
    "service": "carts",
    "stage": "staging",
    "start": "2020-09-01T08:31:06Z",
    "tag": "0.11.1",
    "teststrategy": "real-user"
  },
  "id": "7e2dbff7-4141-4052-a147-0d4284b99e51",
  "source": "remediation-service",
  "specversion": "0.2",
  "time": "2020-09-01T10:14:38.519Z",
  "type": "sh.keptn.event.start-evaluation",
  "shkeptncontext": "52b020e3-0fe5-45e9-9335-20ba546a93b8"
}
```

**Comment by ermin-muratovic** [comment]
@johannes-b fixed that in https://github.com/keptn/keptn/pull/2259
