### ISSUE TITLE
Inconsistency in installation setup docs

### ISSUE THREAD

**Issue by imrenagi** [keptn/keptn#2120]
Context: I was trying to follow installation setup in macos.

If we take a look to this [documentation](https://keptn.sh/docs/0.7.x/operate/install/#option-3-expose-keptn-via-an-ingress) about exposing the keptn, there are some inconsistency of env var naming. Sometimes, it use `KEPTN_API_ENDPOINT` and in other places it use `KEPTN_ENDPOINT`.

This leads to an issue while I want to follow steps for authenticating keptn [here](https://keptn.sh/docs/0.7.x/operate/install/#authenticate-keptn-cli) because it use
```
keptn auth --endpoint=$KEPTN_ENDPOINT --api-token=$KEPTN_API_TOKEN
```

is `KEPTN_ENDPOINT` specified on the cli above is the same as `KEPTN_API_ENDPOINT` ?

**Comment by johannes-b** [comment]
Hi Imre, 
thanks for pointing that out. 
I fixed the inconsistency by now using `KEPTN_ENDPOINT` for all references to the endpoint of Keptn.
