### ISSUE TITLE
Error in keptn tutorial

### ISSUE THREAD

**Issue by imrenagi** [keptn/keptn#2121]
I tried to follow this [tutorial](https://tutorials.keptn.sh/tutorials/keptn-full-tour-prometheus-07/index.html?index=..%2F..index#5) (6. Configure Istio and Keptn), but I got an error while running:

```
kubectl create configmap -n keptn ingress-config --from-literal=ingress_hostname_suffix=$(kubectl -n keptn get ingress api-keptn-ingress -ojsonpath={.spec.rules[0].host}) --from-literal=ingress_port=${INGRESS_PORT} --from-literal=ingress_protocol=${INGRESS_PROTOCOL} --from-literal=istio_gateway=${ISTIO_GATEWAY} -oyaml --dry-run | kubectl replace -f -
```

Isn't it supposed to be:
```
kubectl create configmap -n keptn ingress-config --from-literal=ingress_hostname_suffix=$(kubectl -n keptn get ingress api-keptn-ingress -ojsonpath='{.spec.rules[0].host}') --from-literal=ingress_port=${INGRESS_PORT} --from-literal=ingress_protocol=${INGRESS_PROTOCOL} --from-literal=istio_gateway=${ISTIO_GATEWAY} -oyaml --dry-run | kubectl replace -f -
``` 
?

the correct one is using `'` 
```
-ojsonpath='{.spec.rules[0].host}'
```

and also, what is the value for `INGRESS_PORT`, `INGRESS_PROTOCOL` and `ISTIO_GATEWAY` ? I dont see it setup in previous steps of the tutorial

**Comment by agrimmer** [comment]
Thank you @imrenagi, you are right!
This needs to be addressed in the tutorial.

**Comment by johannes-b** [comment]
To not get it lost in the backlog of the keptn/keptn repo, I moved it to keptn/tutorials: https://github.com/keptn/tutorials/issues/61

Hence, I close this one.
