### ISSUE TITLE
Add labels parameter to all keptn send events

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#2126]
Labels are a powerful feature in Keptn. Right now you can pass them with [keptn send event start-evaluation](https://keptn.sh/docs/0.7.x/reference/cli/commands/keptn_send_event_start-evaluation/), but you can't do it for [keptn send event new-artifact](https://keptn.sh/docs/0.7.x/reference/cli/commands/keptn_send_event_new-artifact/)

**Idea:** It would be powerful to extend that CLI command as it will allow sending in labels such as `buildId`, which allows us to link the CI's `buildId` with the delivery process of Keptn. One of the major benefits is that the quality gate HeatMap can display the `buildId` instead of the timestamp

Here is an example for how I would like to send a new artifact event:
```
keptn send event new-artifact --project=keptn07project --service=simplenode --image=docker.io/grabnerandi/simplenodeservice --tag=1.0.0 --labels=buildId=101,sourceCi=Jenkins
```

These labels will then show up in the Keptn Bridge and will be used in the HeatMap (as proposed here #2131) to identify the evaluation run.

**Definition of Done:**
- [ ] The `keptn send event new-artifact` allows passing in labels by the `--lables` flag. See example above.

**Comment by johannes-b** [comment]
This is related to: #1149

**Comment by DarthBenro008** [comment]
Hey! I would like to work on this issue, can you please assign this to me?

**Comment by christian-kreuzberger-dtx** [comment]
Sure. Please be aware that there are multiple "send event" commands right now: 
![image](https://user-images.githubusercontent.com/56065213/106743311-7ef57680-661e-11eb-941b-e0ad91ba908b.png)

**Comment by DarthBenro008** [comment]
@christian-kreuzberger-dtx my understanding is that this issue is specific to the command `keptn send event new-artifact` (specific to new-artifact event only)

Hence I believe only the files, `send_event_newArtifact.go` and `send_event_newArtifact_test.go` would be relevant?

**Comment by christian-kreuzberger-dtx** [comment]
At the time this issue was written we only had start-evaluation and new-artifact.

As we have added others (approvalFinished to be exact), please also add it there ;)
