### ISSUE TITLE
Helm Services does not forward labels of configuration change event

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#2128]
When sending a configuration change event to keptn including labels, e.g: buildId=123,triggerTool=Jenkins, ... then these labels are supposed to be forwarded by every service that handles this event to the next event it sends out, e.g: deployment finished event.

Keptn's Helm Service is not adhering to this de-facto standard when sending a deployment-finished event. The responsible code can be found in **workflow_engine_replace.go:sendDeploymentFinishedEvent**. This function should get a list of incoming labels or the receiving event and then make sure that these labels are added to the new deployment finished event.

Right now this misbehavior is breaking one key use case of Keptn where an external tool, e.g: Jenkins can pass its BuildID to Keptn to allow full end-2-end tracing across the complete Keptn Workflow

**Comment by agrimmer** [comment]
Similar to https://github.com/keptn/keptn/issues/1149
