### ISSUE TITLE
Bridge: Show buildId also in Heatmap and not just in charts

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#2131]
Since Keptn 0.7 the bridge not only looks at the evaluation timestamp, but is also able to use a label called `buildId` to display in "Chart Mode" as the label on the x-axis. See image:

![image](https://user-images.githubusercontent.com/675886/88558341-a940f880-d02b-11ea-8320-4b8734a7ebcb.png)

**Idea:** This information should also be used in the HeatMap as it makes navigating through the data easier. I can envision to either have it as part of the score heatmap tile or as part of the header information above the table - see here:

![image](https://user-images.githubusercontent.com/675886/88558259-94fcfb80-d02b-11ea-8a53-6f14e2897428.png)

**Comment by johannes-b** [comment]
Based on feedback from @ermin-muratovic, this information (the buildId) should be placed on the horizontal axis of the heatmap. (no tooltip or overlay in the heatmap) 

Like it is implemented for the chart:
![image](https://user-images.githubusercontent.com/729071/93893143-9aa25500-fced-11ea-8ab6-fa3bf7916577.png)
