### ISSUE TITLE
Do not show HeatMap if evaluation done never had historical data because of missing SLO or missing SLI Provider

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#2134]
Some stages will not have an SLO or maybe there will be entire projects without an SLI provider. In that case the bridge should not display the heatmap/chart as it takes a way a lot of space and takes the focus away from what the main result of this event is, e.g: **no evaluation performancd by lighthouse** -> see screenshot

![image](https://user-images.githubusercontent.com/675886/88633278-0cc33880-d0b5-11ea-91a8-ea0ad1fa99cc.png)

**Comment by johannes-b** [comment]
This will be implemented by #2305
