### ISSUE TITLE
View event payload option in Bridge does not show labels

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#2138]
This is just a minor issue: But its a bit misleading when analyzing & diagnosing Keptn Events.

**Problem:** While labels are clearly present in the Keptn CloudEvent, they are not shown when clicking on the "event payload" view. See the following screenshots:

![image](https://user-images.githubusercontent.com/675886/88659768-e1047a80-d0d5-11ea-8ab8-5b692cd28290.png)

**Definition of Done:**
- [ ] Labels are shown in event payload

**Comment by johannes-b** [comment]
Please take a look here: https://github.com/keptn/keptn/commit/20fe6d9e9d9302e1ae28680db5f4ae8d28ac9efd (and maybe refactor to map.ToString).
