### ISSUE TITLE
Wrong color-coding in Keptn Bridge for problem.resolved event

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#2139]
For a *problem resolved* event the color coding in the left column is incorrect.

![image](https://user-images.githubusercontent.com/7677092/88660458-09d93f80-d0d7-11ea-968d-e1cd2032aa81.png)

I would expect both columns to show a green icon.

**Comment by johannes-b** [comment]
I would go one step further. 
When a remediation workflow ends with a `sh.keptn.event.remediation.finished` with `status: success` and `result: pass` the red icon and event border must turn into green.  

**Definition of Done**
- [ ] When Keptn receives a "Problem resolved" event (detached from a remediation workflow), the event is displayed with a green icon 
- [ ] A successful remediation.finished turns the color from red to green.
