### ISSUE TITLE
Provider better indication and workflow for artifacts waiting for approval

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#2142]
The Service view shows an artifact to be deployed into a stage even when it is waiting for approval. This is misleading and does not reflect the actual state. There is also not a good workflow for a user to get to approve or reject the artifact at that point. Either allow approval/reject in that view as described in #2135 or provide a link to the environment view.

The following screenshot should highlight the current implementation and how to make it better:

![image](https://user-images.githubusercontent.com/675886/88689089-613cd700-d0fa-11ea-8f0e-1bea78fbc939.png)

**Definition of Done**
- [ ] When an approval is required, add a blue border (same color as used in environment screen) to the stage that is waiting for approval
- [ ] When an approval is required, use a blue border (same color as used in environment screen) to highlight the event in the event stream 
- [ ] Added the accept/decline button to the **Approval.triggered** event - this closes: #2135

**Comment by johannes-b** [comment]
This is related to #2135

**Comment by johannes-b** [comment]
In the community meeting from 6th August, we discussed to add a confirmation dialog to the action of accepting/declining an approval. I propose to not add the additional click, but rather show the user the artifact version that is going to be overridden: 

![image](https://user-images.githubusercontent.com/729071/89762484-d512b280-daf0-11ea-8c2e-1898f8766c93.png)

**Comment by ermin-muratovic** [comment]
> In the community meeting from 6th August, we discussed to add a confirmation dialog to the action of accepting/declining an approval. I propose to not add the additional click, but rather show the user the artifact version that is going to be overridden:
> 
> ![image](https://user-images.githubusercontent.com/729071/89762484-d512b280-daf0-11ea-8c2e-1898f8766c93.png)

I like that idea. Showing that information, already indicates what will happen, when you click on approve button. So I also think we don't need an additional confirmation dialog for that.

**Comment by johannes-b** [comment]
Due to the fact, that we know the evaluation result (score) we can show the user more details: 

![image](https://user-images.githubusercontent.com/729071/90009361-2f04ab00-dc9e-11ea-942a-9dd0df358c8d.png)

**Comment by ermin-muratovic** [comment]
As discussed with @johannes-b, I provide now the Score from the last evaluation next to the deployable artifact and on hover you see details from that evaluation.

![image](https://user-images.githubusercontent.com/6098219/90107571-4cdb1a00-dd49-11ea-8070-5290e7a32a2d.png)
