### ISSUE TITLE
Multiple approvals to pass stage

### ISSUE THREAD

**Issue by trevex** [keptn/keptn#2144]
**Is your feature request related to a problem? Please describe.**
For production environments there is often the requirement of four eye principle for any changes.
The requirement can either come from compliance or company processes.
In addition to this it is vital to know who approved as well.

**Describe the solution you'd like**
Rather than a single approval, multiple different engineers have to approve. For both approvals events are created which contain the approver as part of a label.
This is dependent on a grouping concept as provided by OIDC, LDAP or AD, but it would be great to limit approvals for a certain service to groups (blocked by efforts to add support for identity providers).

**Describe alternatives you've considered**
An alternative is to hand control back to a CI/CD system like Gitlab. So instead of handling the approval itself, keptn will open an PR/MR, which will kickoff the deployment to the next environment.

**Comment by johannes-b** [comment]
Hi @trevex, 

great idea and many thanks for thoughts on getting Keptn production-ready.

As you have correctly identified, the default behavior or Keptn requests one approval that accepts/declines the deployment into a stage. However, based on the event-driven approach of Keptn, it is possible to extend the approval step by a custom *Keptn-service*. This service needs to have a subscription to: `sh.keptn.event.approval.triggered` that triggers its implementation. Finally this custom *Keptn-service* sends out an event of type:  `sh.keptn.event.approval.finished` when the approval process is completed. The implementation of that *Keptn-service* would then access LDAP, AD, or any other user management system for getting the user accounts that are allowed for approval. Besides, the process of the approval process can also be modeled and implemented in this custom *Keptn-service*. 

**Keptn-service for approval step:**
- listens to: **sh.keptn.event.approval.triggered**
- access OIDC, LDAP, AD + execute the approval process
- sends out: **sh.keptn.event.approval.finished [ approved | declined ]**

Do you need such a custom implementation for your Keptn?
