### ISSUE TITLE
NGINX doc for 0.7.0 - Error in kubectl command.

### ISSUE THREAD

**Issue by checkelmann** [keptn/keptn#2163]
**Environment**

* Keptn Version (`keptn version`): 0.7.0

**Affected Component**

* [X ] Docs
* [ ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [ ] Bridge
* [ ] Gatekeeper
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**
In the docs on this page https://keptn.sh/docs/0.7.x/operate/install/#install-keptn the NGINX Ingress command to get the service is wrong.

Change from 
`kubectl -n ingress-nginx svc ingress-nginx`

to
`kubectl -n ingress-nginx get svc ingress-nginx`

![image](https://user-images.githubusercontent.com/584370/89267235-3e994980-d637-11ea-9b3d-9a16b33b7df2.png)

**Comment by johannes-b** [comment]
Thanks for reporting this issue. I filed a PR to get it fixed: https://github.com/keptn/keptn.github.io/pull/622

FYI: On Keptn Slack: [slack.keptn.sh](https://slack.keptn.sh) there is a #keptn-docs channel in which you can post such *one-liner* issues. I will take care of getting those addressed when posted there.

**Comment by checkelmann** [comment]
> Thanks for reporting this issue. I filed a PR to get it fixed: [keptn/keptn.github.io#622](https://github.com/keptn/keptn.github.io/pull/622)
> 
> FYI: On Keptn Slack: [slack.keptn.sh](https://slack.keptn.sh) there is a #keptn-docs channel in which you can post such _one-liner_ issues. I will take care of getting those addressed when posted there.

Right, you told us last thursday, I totally forget about this channel ;)
