### ISSUE TITLE
keptn get event: Provide a implementation of this command that takes any event type

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#2171]
In Keptn 0.7, the Keptn CLI provides two commands to retrieve a CloudEvent from Keptn that are: 
- keptn get event approval.triggered
- keptn get event evaluation-done

Besides, the `keptn get event` command is not implemented. 

**Problem:** As a result, it is not possible to retrieve any kind of event from Keptn using the CLI.  

**Proposal:** Implementation of the `keptn get event` command as follows:

Command supports the flags:
- `--project` - is mandatory
- `--stage`
- `--service`
- `--output` (short form `-o`) [ json | yaml] - prints the payload of the event in JSON or YAML.  (use YAML as default)
- `--keptn-context`

Example: To print the last event of [event-type] as JSON from a project, stage, service:
```console
keptn get event [event-type] --project=xyz --stage=xyz --service=xyz -o=json
```

Example: To print the last event of [event-type] as YAML from a specific keptn-context:
```console
keptn get event [event-type] --project= xyz --keptn-context=[xyz] -o=yaml
```

- It is possible to mix `--keptn-context` with `--project --stage --service`. 
- The [event-type] takes the full qualified event name, e.g., `sh.keptn.event.deployment-finished`

**Definition of Done:**
- [ ] The command `keptn get event` returns events as proposed above. 
- [ ] Unit tests are provided in the file `get_event_test.go`

**Comment by TannerGabriel** [comment]
I will take this one!
