### ISSUE TITLE
Add option to have json output for the keptn cli get command

### ISSUE THREAD

**Issue by robertjahn** [keptn/keptn#2177]
**Is your feature request related to a problem? Please describe.**
I would like to have ability to use the keptn get command output in scripts.  Right now the output is 'human readable'.

```
jahnadmin@jahn-keptn-070-2:~$ keptn get service
NAME			PROJECT		STAGE		CREATION DATE
simplenodeservice	demo		dev		2020-07-30T14:59:19Z
```

**Describe the solution you'd like**
Like we can do with kubectl, just add option like `-o json` to have the results be in json format.  For example:

```
{
	"projects": [{
		"projectname": "demo",
		"stages": [{
			"stagename": "dev",
			"services": [{
				"service": "abc",
				"service": "xyz"
			}]
		}]
	}]
}
```

**Describe alternatives you've considered**
None

**Additional context**
Also see the feedback to the improving the output naming in this issue.  https://github.com/keptn/keptn/issues/2152.

**Comment by johannes-b** [comment]
Hi @robertjahn 
actually this feature is supported. (Please see: https://keptn.sh/docs/0.7.x/reference/cli/commands/keptn_get_service/#options)

Just add the `--output=json|yaml` flag (short form: `-o`) to your command.

**Comment by robertjahn** [comment]
Very good, I see it now in the CLI help running `keptn get service --help`.  I had just done `keptn get  --help`.  I will close this issue.
