### ISSUE TITLE
Handle the delete command to remove a service from a Keptn project

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#2199]
As a Keptn user, I would like to delete a service by executing the following command: 
```
keptn delete service carts --project sockshop
```

**Tasks:**
- Specify the event: `sh.keptn.internal.event.service.delete` in https://github.com/keptn/go-utils/blob/master/pkg/lib/events.go#L31
- Implement a `DELETE` endpoint in the api-service: `/project/{projectName}/service/{serviceName}` 
  - This endpoint sends out the event `sh.keptn.internal.event.service.delete`, like for deleting a project. 
- Implement/verify the implementation of the `DELETE` endpoint in the configuration-service: `/project/{projectName}/stage/{stageName}/service/{serviceName}` 
  - This endpoint deletes the service in the repo by removing the folders in the branches. 
  - If a Git upstream is defined, sync to upstream. 
  - Remove the service from the materialized view (<- this is already implemented) 
- shipyard-service listens to: sh.keptn.internal.event.service.delete
  - If event is received, it calls the DELETE service endpoint from the configuration-service for all stages

**Definition of Done:**
- [ ] `keptn delete service` successfully removes a service from a Keptn project 
- [ ] Implementation of the command is covered by a test (like in: https://github.com/keptn/keptn/blob/master/test/test_delete_project.sh)

**Comment by agrimmer** [comment]
I've prepared a data structure for https://github.com/keptn/go-utils/pull/193

**Comment by agrimmer** [comment]
If a user deletes a project with `keptn delete project` but has not deleted the services before, the `shipyard-service` should delete all services before deleting the project, i.e. by sending out `sh.keptn.internal.event.service.delete` events for all services.

**Comment by johannes-b** [comment]
I agree! As a user, I would expect to get the services deleted when deleting a project, which is per definition the enclosing entity of services.
