### ISSUE TITLE
Install fails when AG is deployed

### ISSUE THREAD

**Issue by alipatton10** [keptn/keptn#222]
When you have an AG installed the install fails as ISTIO creation doesn't seem to like having ports included in the endpoints. You receive the following error
Error from server: error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"networking.istio.io/v1alpha3\",\"kind\":\"ServiceEntry\",\"metadata\":{\"annotations\":{},\"name\":\"dynatrace-oneagent-hostnames\",\"namespace\":\"default\"},\"spec\":{\"hosts\":[\"pgr59512.live.dynatrace.com\",\"activegate.us-central1-a.c.acl-gsi.internal:9999\",\"10.128.0.37:9999\",\"sg-eu-west-1-18-202-8-23-prod23-ireland.live.ruxit.com\",\"sg-eu-west-1-52-31-108-81-prod23-ireland.live.ruxit.com\",\"sg-eu-west-1-34-241-182-103-prod23-ireland.live.ruxit.com\",\"sg-eu-west-1-34-241-58-226-prod23-ireland.live.ruxit.com\",\"sg-eu-west-1-52-214-86-21-prod23-ireland.live.ruxit.com\"],\"location\":\"MESH_EXTERNAL\",\"ports\":[{\"name\":\"HTTPS\",\"number\":443,\"protocol\":\"HTTPS\"}],\"resolution\":\"DNS\"}}\n"}},"spec":{"hosts":["pgr59512.live.dynatrace.com","activegate.us-central1-a.c.acl-gsi.internal:9999","10.128.0.37:9999","sg-eu-west-1-18-202-8-23-prod23-ireland.live.ruxit.com","sg-eu-west-1-52-31-108-81-prod23-ireland.live.ruxit.com","sg-eu-west-1-34-241-182-103-prod23-ireland.live.ruxit.com","sg-eu-west-1-34-241-58-226-prod23-ireland.live.ruxit.com","sg-eu-west-1-52-214-86-21-prod23-ireland.live.ruxit.com"]}}
to:
&{0xc420105080 0xc420180af0 default dynatrace-oneagent-hostnames ../manifests/gen/service_entries_oneagent.yml 0xc420d0c000 176401 false}
for: "../manifests/gen/service_entries_oneagent.yml": admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: 4 errors occurred:

* domain name "us-central1-a.c.acl-gsi.internal:9999" invalid (label "internal:9999" invalid)
* domain name "128.0.37:9999" invalid (label "37:9999" invalid)
* hosts must be FQDN if no endpoints are provided for discovery mode DNS
* hosts must be FQDN if no endpoints are provided for discovery mode DNS
Error from server: error when applying patch:

**Comment by dirkwall** [comment]
Starting with Istio 1.1 all calls to external systems are allowed by default (https://istio.io/docs/tasks/traffic-management/egress/#envoy-passthrough-to-external-services). I think we should allow all calls to external systems in the version we're using, so we don't have to make a lot of changes during an upgrade to version 1.1+ of Istio. We need to point that out in the documentation so that people are aware of that and take care of t configuring the ServiceEntries on their own if the chose to not allow all external calls out of the service mesh by default.

ToDo
- [ ] allow all calls to external systems by default
- [ ] update documentation accordingly

**Comment by bacherfl** [comment]
Did this error occur with version 0.1 or 0.2? In 0.2 we already configure Istio to allow all outgoing traffic by default

**Comment by dirkwall** [comment]
No feedback for over a month, closing. Please reopen if the issue still exists.

**Comment by johannes-b** [comment]
Peter pointed out that this issue still exists. 
In other words, the createServiceEntry.sh script fails because the AG has no fully qualified domain name, which is expected by Istio.

Do we need to create service entries even though we allow all outgoing traffic?

**Comment by dirkwall** [comment]
@bacherfl please advise.

**Comment by johannes-b** [comment]
- [ ] test on an empty DT tenant missing
