### ISSUE TITLE
Unleash changes to have events on changes and control which env is changed 

### ISSUE THREAD

**Issue by alipatton10** [keptn/keptn#2233]
**Is your feature request related to a problem? Please describe.**

When running the unleash demo there are 2 issues. 1 the feature is toggled for all environments, it would be better if this was either just production or controllable. 
The second issue is that currently we don't send this as a configuration event to dynatrace like we used to with the script approach. This mean the problem detected by DAVIS has no root cause. This really limits the story. Really it should be more like DAVIS detects root cause and in that root cause is the remediation action. That is then used by keptn to trigger it. Currently we are just triggering it if we have the failure instead of properly utilising DAVIS.

**Describe the solution you'd like**

Any config change made by keptn sends an event to Dynatrace. I guess in this instance what we need is the unleleash process to send a cloud event to keptn when it is triggered so the dynatrace service can pick it up. In DT we really need an event when the feature is first enabled and when it is disabled again

Second we need the ability to control which environments the feature is turned on for. Perhaps this is already a possibility but i couldn't find any docs on it.

**Describe alternatives you've considered**

I considered either reverting to script based enablement but this seems like a backwards step or writing a keptn service to handle it but the service would only really work for the remediation event as it seems we don't have one for the initial enablement of the feature flag. Plus this really shouldn't be a need service but rather an enhancement to this and the dynatrace one.

**Additional context**

**Comment by johannes-b** [comment]
Hi @alipatton10 

Let me address your first issue first (as the second one takes more time to think about).

#### _The feature is toggled for all environments, it would be better if this was either just production or controllable._

The app deployed into dev/staging/production must have an environment variable for calling the unleash server like: 
```
   - name: UNLEASH_SERVER_URL
      value: "http://unleash.unleash-dev/api"
```
By removing this environment variable from the deployment manifest in `dev` and `staging`, toggling the feature flag will affect only the app running in `production`. Removing the environment variable means that you go to your Git upstream repo, navigate to the `dev`/`staging` branch and into the app/helm folder. In this /helm folder you will find **two** Helm charts and in both charts you need to remove the env variable. 

Finally,  re-deploy your app by using: `keptn send event new-artifact ...`

Can you test it out and let us know if it works?

**Comment by alipatton10** [comment]
Thanks @johannes-b as discussed I have now tested this and it is working. I delete both line 55 and 56 in dev and staging and the FF is now only enabled in prod. I think we need to update this though with a proper solution as I don't think it is very real world like to enable all stages with the same FF.

On the events side i'll look forward to hearing what can be done when you have had a chance to discuss with the team.

**Comment by christian-kreuzberger-dtx** [comment]
Can we get an update on this issue?

What is the task at hand to do or has the problem been fixed?

**Comment by christian-kreuzberger-dtx** [comment]
Closing this as there has been no comments, responses, and apparently there is nothing to do.
