### ISSUE TITLE
As a keptn user, I would like to see the dynatrace tenant details in the bridge used for evaluating SLIs.

### ISSUE THREAD

**Issue by ragrawal-humana** [keptn/keptn#2236]
**Is your feature request related to a problem? Please describe.**
We are using two Dynatrace environments for SLI evaluation (NonProd and Prod) with the help of dynatrace.conf.yaml. Looking at the event in bridge, it is not possible to determine which Dynatrace environment was used for evaluation.

**Describe the solution you'd like**
Some metadata that would indicate the Dynatrace environment i.e. Tenant ID/URL or credential secret name. Ideally this information should be displayed in bridge for the event.

**Describe alternatives you've considered**
Currently, logs do provide this information but having this information right on the bridge will make it more accessible.

**Comment by johannes-b** [comment]
Hi @ragrawal-humana, 
an approach for implementing this feature is by adding labels to the payload of the `sh.keptn.internal.event.get-sli.done` event. 
Example of a `sh.keptn.internal.event.get-sli.done` event:  https://github.com/keptn/spec/blob/master/cloudevents.md#example-11

I know that @grabnerandi is currently working on that issue. I will let you know when the feature is ready.

**Comment by johannes-b** [comment]
The PR https://github.com/keptn-contrib/dynatrace-sli-service/pull/69 implements the requested feature, which is coming with the new 0.6.0 release of the dynatrace-sli-service.
