### ISSUE TITLE
Heatmap doesnt show score if there are no SLOs/SLOs defined

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#2277]
If we have a quality gate without an SLO then Keptn marks that evaluation as "pass" with a score of 0!
The problem is that this is not visualized well. The heatmap currently looks like something is missing - see here

![image](https://user-images.githubusercontent.com/675886/91975016-06148a80-ed1f-11ea-82d8-19c97692c34d.png)

It would be better to show the SCORE row as we actually do have a score even though it is 0

![image](https://user-images.githubusercontent.com/675886/91975151-407e2780-ed1f-11ea-8d18-d398c5d8d923.png)

In this special case it would also be great to put more emphasize on the text that explains that there is no SLO defined. Right now the text is gray and doesnt stick out. I suggest we highlight it somehow

**Comment by alipatton10** [comment]
I think this would be really useful but I would go further than this as this is similar to an issue i raised in 0.2 
If i have specified a test but have not provided the SLO then surely the build should fail. To me it should be promote only with explicit pass where as we seem to currently only stop the promotion on an explicit fail. If i forget to supply the SLOs or something causes them to become unavailable then I would not want builds to still be promoted.

**Comment by johannes-b** [comment]
I will close this issue, as it has been addressed: 

![image](https://user-images.githubusercontent.com/729071/112847620-8af23780-90a7-11eb-9992-46e1f5319d23.png)
