### ISSUE TITLE
Prefix namespaces with project name (e.g. bookshop-dev, bookshop-staging, ...)

### ISSUE THREAD

**Issue by dirkwall** [keptn/keptn#229]
When onboard services to a project, the namespaces are created according to the information in the shipyard file. If previously a different project with the same namespaces has been created, those namespaces would already exist and two different projects would deploy in the same namespace. To prevent that, we should create the namespaces by using a combination of the project name and the stage name of the shipyard file. For example:

**Acceptance criteria**
**Given** the following `shipyard.yml`
```
registry: cars
stages:
  - name: "dev"
    ...
  - name: "staging"
    ...
  - name: "production"
    ...
```
  **When** I issue the command
```
keptn create project cars shipyard.yml
```
**Then**
The following Kubernetes namespaces should have been created.
- "cars-dev"
- "cars-staging"
- "cars-production"

**Comment by johannes-b** [comment]
The K8s namespaces are now created based on project name and stage name: 

![Capture](https://user-images.githubusercontent.com/729071/57508734-a5c83100-7302-11e9-875f-1d5849d86e3c.PNG)

- [ ] DT events are send correctly to Dynatrace tenant (when Dynatrace monitoring is active)
- [ ] Self-healing use cases also sends a DT event that is adapted according to the new namespace name

**Comment by johannes-b** [comment]
While running through the deploying with quality gates use case, it has been figured out that the config for destination-rule and virtual-service need to be adapted to consider the prefix in the namespace.
