### ISSUE TITLE
keptn configure monitoring dynatrace - Websocket connection timed out issue

### ISSUE THREAD

**Issue by JebasinghLuccas** [keptn/keptn#2290]
I am setting up the Keptn full Tour on Dynatrace  .

Platform : AKS 
Kuebernetes version : 1.16.10

I am stuck at the 11 steps: Install Dynatrace Integration and when i issue the below command  , I am getting websocket connection timeout issue . 
**keptn configure monitoring dynatrace**

**ID of Keptn context: f600d160-d72f-482e-9329-a3945d7fcdb9
Warning: Websocket connection timed out**

I am using free trail dynatrace tenant .  Please support what could be the cause of this . 

Thanks
jba

**Comment by johannes-b** [comment]
Hi Jba,
can you please verify that the `dynatrace-service` is deployed and running. I assume you deployed it into the `keptn` namespace. Then execute: `kubectl get pods dynatrace-service -n keptn`.

If the service is running, please take a look into the logs: `kubectl logs dynatrace-service-xxx-xxx -n keptn`

Does the logs tell you the problem?

**Comment by JebasinghLuccas** [comment]
Hello Johannes , 

when i say kubectl get pods -n keptn , i see below related to dynatrace-service and one is not even running . 

dynatrace-service-55dc8cf558-2pr6l                               0/1     CrashLoopBackOff   840        2d23h
dynatrace-service-distributor-f59bd95fb-8qksb                    1/1     Running            0          2d23h

and the below is the log of the broken one
**kubectl logs dynatrace-service-55dc8cf558-2pr6l -n keptn**

branch: 0.8.0
repository: https://github.com/keptn-contrib/dynatrace-service
commitlink: https://github.com/keptn-contrib/dynatrace-service/commit/72d11a24357fd4d6529d9c8608b62a961698dd30
repolink: https://github.com/keptn-contrib/dynatrace-service/tree/72d11a24357fd4d6529d9c8608b62a961698dd30
timestamp: 20200723.1120
version: 0.8.0
##########
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x10ccf49]

goroutine 1 [running]:
github.com/keptn-contrib/dynatrace-service/pkg/common.CheckKeptnConnection(0xc00000e600, 0x0, 0x0)
        /go/src/github.com/keptn/dynatrace-service/pkg/common/common.go:78 +0x159
main._main(0xc0000ea1c0, 0x0, 0x0, 0x1f90, 0x12d57c8, 0x1, 0x0)
        /go/src/github.com/keptn/dynatrace-service/cmd/main.go:46 +0x54
main.main()
        /go/src/github.com/keptn/dynatrace-service/cmd/main.go:35 +0x165

goroutine 19 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x2131320)
        /go/pkg/mod/k8s.io/klog@v1.0.0/klog.go:1010 +0x8b
created by k8s.io/klog.init.0
        /go/pkg/mod/k8s.io/klog@v1.0.0/klog.go:411 +0xd6

goroutine 8 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc00010a230)
        /go/pkg/mod/go.opencensus.io@v0.22.0/stats/view/worker.go:154 +0x100
created by go.opencensus.io/stats/view.init.0
        /go/pkg/mod/go.opencensus.io@v0.22.0/stats/view/worker.go:32 +0x57

Am i missing anything here . 

the below are the services running under dynatrace namespace 

**D:\workspace>kubectl get pods -n dynatrace**
NAME                                           READY   STATUS    RESTARTS   AGE
dynatrace-oneagent-operator-65fbb9fdc7-r5j7j   1/1     Running   0          2d23h
dynatrace-oneagent-webhook-84558965b7-2c29j    2/2     Running   0          2d23h
oneagent-zlnd2                                 1/1     Running   0          2d23h

**Comment by johannes-b** [comment]
Hi, we need to get the dynatrace-service running. 
Can you please deploy the latest version, which is `0.9.0`. 
```
kubectl apply -f https://raw.githubusercontent.com/keptn-contrib/dynatrace-service/0.9.0/deploy/service.yaml -n keptn
```

**Comment by christian-kreuzberger-dtx** [comment]
Hi, can anyone provide an update on this? Has it been fixed with the latest version of dynatrace-service?

**Comment by JebasinghLuccas** [comment]
yes the latest version fix the issue
