### ISSUE TITLE
Limit API response with filter

### ISSUE THREAD

**Issue by alipatton10** [keptn/keptn#2292]
**Is your feature request related to a problem? Please describe.**
I am polling api/configuration-service/v1/project as i want to know how many projects I have and to grab their names. The response body is quite large and even includes events for each service and stage

**Describe the solution you'd like**
A way to limit the response of the APIs with something like a includeDetails=false? The same way we can in dynatrace

**Describe alternatives you've considered**
Currently i poll the whole thing and do client side filtering but this adds an unnecessary overhead on both sides and slows down the request.

**Additional context**
Really if i could even just excluded all the events in that request i think it would be fine

**Comment by agrimmer** [comment]
Hi @alipatton10,
thank you for the issue! We see the problem and plan to improve the API in this regard.
