### ISSUE TITLE
DockerHub Pull Rate Limit starting November 1st 2020 might break our CI builds

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#2294]
As announced on docker.com recently, they will introduce pull rate limits for docker images hosted on hub.docker.com as follows:

* **Free plan – anonymous users: 100 pulls per 6 hours**
* **Free plan – authenticated users: 200 pulls per 6 hours**
* Pro plan – unlimited
* Team plan – unlimited

Keptn is using the free plan at the moment, hence I've marked those two in bold above. See https://www.docker.com/pricing for the pro and team plan.

According to [their blog post](https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress) they have defined the limits such that it should not be an issue if you use docker as a developer.

However, I believe that we need to carefully look at our travis-ci builds regarding the 100/200 pulls per 6 hours limit. Please note, that pushing and building an image usually also requires pulling the base-image. In addition, sometimes building an image pulls cached images from dockerhub as well. Depending on how often we build our images, we might end up hitting those limits, which will cause our CI pipeline to fail.

### Authenticated user

We currently use DockerHub tokens to authenticate against DockerHub. This is stored a secret on travis-ci. However, this is the same user for many of our repositories, and it might create problems when we hit the limit.

Suggestion: Create and configure separate service-accounts/users per repository.

### Anonymous user

While we store the secret on travis-ci, pull requests from forks are not considered secure, therefore secrets on travis-ci are not available, and we need to deal with the limit of an anonymous user. This could go even further, as docker might intrudce rate limitng by IP for anonymous users, and therefore we might end up having to share the rate limit with other travis-ci users.

### Open Source Plan

They also state in their blog post that open source projects can apply for an open source plan:

> Finally, as part of Docker’s commitment to the open source community, before November 1 we will be announcing availability of new open source plans. To apply for an open source plan, please complete the short form [here](https://forms.gle/vvKURDTYwok7Pc4r5).

I believe we should do that, but we should still be aware that we might end up running into some rate limit related problems temporarily.

**Comment by johannes-b** [comment]
Is it possible to figure out how many Docker pulls the `master`, `cron`, `pr` jobs perform for one run? 
Would be quite important to assess the likelihood of running into a rate limit.

**Comment by christian-kreuzberger-dtx** [comment]
Good question, I'll see if we can get this from log files easily. I guess we won't be the only project that will be affected by this.

So far I found this comment which is actually helping us: https://github.com/GoogleContainerTools/skaffold/issues/4432#issuecomment-652634953
> we've temporarily added Travis IPs to an override list so you should be good now.
> Our product team will reach out to the folks at Travis to work on a more long-term solution.

**Comment by christian-kreuzberger-dtx** [comment]
Starting today, this might become an issue. We're monitoring the situation.

**Comment by christian-kreuzberger-dtx** [comment]
They have announced their open source program: https://www.docker.com/blog/expanded-support-for-open-source-software-projects/?utm_campaign=IT+Pro&utm_content=1604355555&utm_medium=social&utm_source=Organic

**Comment by christian-kreuzberger-dtx** [comment]
One alternative for companies is a docker pull through cache: https://docs.docker.com/registry/recipes/mirror/

**Comment by christian-kreuzberger-dtx** [comment]
@checkelmann pointed out this script provided on gitlab.com: https://gitlab.com/gitlab-com/marketing/corporate_marketing/developer-evangelism/code/check-docker-hub-limit

This can be used to check how big the limit currently is.

For Google Kubernetes Engine, it seems that there already is a cache in place, so everything is fine.

```
OK - Docker Hub: No limits found. You are safe and probably use a caching proxy already.
```

locally (e.g., in k3s) this script outputs
```
OK - Docker Hub: Limit is 2500 remaining 2490|'limit'=2500 'remaining'=2490
```

**Comment by christian-kreuzberger-dtx** [comment]
Update regarding travis-ci: https://blog.travis-ci.com/docker-rate-limits

> Travis CI has a built in registry cache for Docker builds - you can find out more about how to include Docker in your builds in the Travis CI docs.

Also, they recommend authenticating against DockerHub (which we do).

**Comment by christian-kreuzberger-dtx** [comment]
Some updates regarding this issue:

1. we are not using travis-ci anymore, but GitHub actions. We have not yet run into the issue though.
2. using the check script from above now reports a limit of 100 on my local K3s, so the limit should be present right now.

**Comment by jetzlstorfer** [comment]
Today we had a training session (with 10+ participants) using Keptn and one participant ran into the Docker rate limiting. It was not during the installation of Keptn itself, but during our lab we also onboarded some applications and then it happened. 
Would strongly recommend hosting our images on a different provider to overcome these limitations.

**Comment by christian-kreuzberger-dtx** [comment]
This issue is still present (but rare) in our CI, and there is currently no way to properly monitor it. I'll close this issue as the CI part seems to not be a problem right now.

For end-users that run into the problem as well, the most obvious fix would be to use a different registry (or even to provide the images on multiple registries).

This would also require our keptn-install helm chart to be configurable to use a different registry/repository. I'll create a follow-up issue for that.
