### ISSUE TITLE
CII Badge: Secret for generating WebSocket session token with 256-bit size

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#2295]
**Session token for WebSocket communication:** `token`/`keptnContext`

- Struct: https://github.com/keptn/go-utils/blob/release-0.7.0/pkg/api/models/event_context.go#L17
- Generation:
  * `SECRET_TOKEN`: Is the `keptn-api-token` = 160-bit secret.
  * `token`: To generate this session token, the HS256 (Hash-based Message Authentication Code (HMAC) and SHA-256) is applied on the secret `SECRET_TOKEN`: https://github.com/keptn/keptn/blob/master/api/ws/client.go#L210
  * `keptnContext`: Is an UUID of the format: `xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`
- Storing: Is not stored, but rather part of the server response and then used by the client to open a WebSocket communication. 

*Note on HS256:*
* Hash-based Message Authentication Code (HMAC) is an algorithm that combines a certain payload with a secret using a cryptographic hash function like SHA-256. The result is a code that can be used to verify a message only if both the generating and verifying parties know the secret. In other words, HMACs allow messages to be verified through shared secrets.

* The [JSON Web Algorithms RFC 7518](https://tools.ietf.org/html/rfc7518#page-7) states that a key of the same size as the hash output (for instance, 256 bits for "HS256") or larger MUST be used with the HS256 algorithm.

**Issue:**
- The used secret must have a size of 256-bit and it must not be the `keptn-api-token`. 

**Task:**
- A research task has to figure out whether it is possible to not use a persistently stored secret but rather create a random secret that is stored in memory and has a lifetime according to the lifetime of the corresponding WebSocket channel. If the WebSocket channel terminates, the secret has to expire. 
- The random secret MUST have a size of 256-bit. 

**Definition of Done:**
- [ ] Secret used for generating the WebSocket token is not the `keptn-api-token`. Instead, an individual token with size of 256-bit.

**Comment by christian-kreuzberger-dtx** [comment]
Separating the websocket token generation from the api token is good, however we need to be aware that our websocket communication uses JWT in the background. The benefit is that multiple independent systems should be able to verify that the JWT is correct, therefore they need to know `SECRET_TOKEN` (but not necessarily the api token).

IMHO to make this whole thing more reliable, we should have a strong master token which we use 
* as the `SECRET_TOKEN` for generating websocket tokens,
* as a seed for creating the api token

As a reference I want to point to the Django Framework, which uses the setting `SECRET_KEY` for all cryptographic functions (see https://docs.djangoproject.com/en/2.2/ref/settings/#secret-key ).

**Comment by christian-kreuzberger-dtx** [comment]
I just took a look at our [docs](https://keptn.sh/docs/0.7.x/operate/api_token/#create-api-token), we do generate our api token like this:
```console
KEPTN_API_TOKEN=$(head -c 16 /dev/urandom | base64)
kubectl create secret generic -n keptn keptn-api-token --from-literal=keptn-api-token="$KEPTN_API_TOKEN"
```
This indicates that we use 16 random bytes, which should be sufficient (1 byte = 8 bit --> 16*8 = 256 bit)

though in the source code of the installer I found this:
https://github.com/keptn/keptn/blob/a8871e327082aaeee6f11a24d8cd183f9e52274a/installer/manifests/keptn/charts/control-plane/templates/core.yaml#L1

This generates 20 random alphanumeric characters (where one character can have 62 possible values = roughly 6 bit --> 120 bit).

**Comment by johannes-b** [comment]
Many thanks for the details. 
It was just an idea to keep the secret for the WebSocket token in memory. If it is best practice is to have a strong master key ("SECRET_KEY"), we should follow this practice.

Was just wondering whether I did the math wrong, but I think @christian-kreuzberger-dtx there is a mistake in your last comment: 8*16 = 128 (and not 256).
Nevertheless, the "SECRET_KEY" must have a length of  256 bit.

**Comment by christian-kreuzberger-dtx** [comment]
You're correct, it's 128 - my math was wrong here.

**Comment by christian-kreuzberger-dtx** [comment]
Going forward, I can easily improve the API Token to have an entropy of 256 Bit.

However, do we want to go forward and also introduce a separate secret (master token, secret token) for the websocket communication? Or do we want to keep using the api token for now?

I'm asking because in the future we will end up re-doing things like api-token, authentication, etc... anyway, and we'll have to touch this again.

Also, seeing https://github.com/helm/helm/issues/3053, we need to check if upgrading the helm chart overwrites the API Token / secrets.

**Comment by agrimmer** [comment]
I think we should now do the quick fix and increase the entropy of the API token. 
As soon as we have the full requirements for authentication, user management, etc. we will likely improve this issue as well.
