### ISSUE TITLE
Multi-architecture support for CLI (32 bit, ARM, ...)

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#2297]
Right now our release on GitHub builds and contains the following binaries for the CLI:

![Screenshot from 2020-09-07 13-33-01](https://user-images.githubusercontent.com/56065213/92383471-ae0ac900-f10e-11ea-8cbf-9c1dbcf6855e.png)

As far as I can tell, we are building each of these for Linux, MacOS and Windows on 64 Bit for AMD/Intel:

* [darwin amd64](https://github.com/keptn/keptn/blob/0e49d8d74c29736329448535ca65e1c673306c73/travis-scripts/build_cli.sh#L10-L11)
* [linux amd64](https://github.com/keptn/keptn/blob/0e49d8d74c29736329448535ca65e1c673306c73/travis-scripts/build_cli.sh#L36-L37)
* [windows amd64](https://github.com/keptn/keptn/blob/0e49d8d74c29736329448535ca65e1c673306c73/travis-scripts/build_cli.sh#L62-L63)

Knowing that Apple is switching to ARM CPUs, we will end up losing users that can not use our binaries (unless MacOS has some magic in it to emulate AMD64 binaries, though I wouldn't to rely on that).
In addition, looking at other projects they provide multiple architectures and platforms for their binaries, e.g., [helm](https://github.com/helm/helm/releases):
![Screenshot from 2020-09-07 13-37-04](https://user-images.githubusercontent.com/56065213/92383798-3e490e00-f10f-11ea-9e94-dc0be40ed9b9.png)

I'm not sure if we need to support all of these, though if we touch this aspect or our build process anyway, why not? Let's discuss...

# To be discussed

## ARM support (Linux & MacOS)

Though compiling for ARM would make a lot of sense, as this would allow us to run the CLI on Raspberry PIs (with Linux) and later on MacBooks/etc... (once they release the first Mac with ARM CPUs), so adding those makes a lot of sense to me.

## 32 Bit

I don't have a strong opinion on 32 bit support (I do not see a reason to add it nor to not add it).

## PowerPC

I have no idea whether this is needed at all

## MIPS

Same as with PowerPC, I have no idea whether this is needed at all.

# Definition of Done

- [x] Have an agreement of which architectures should be supported
- [ ] Potentially add binaries for additional architectures to older releases (e.g., 0.7.0, 0.7.1)
- [x] The architectures that we agree on are added to the build job, and the artefacts are uploaded to Google Cloud or whereever we store the CLIs at that point in time

**Comment by christian-kreuzberger-dtx** [comment]
We should consider this for 0.8.0 final, now that MacBooks with ARM chipsets are a thing.

**Comment by christian-kreuzberger-dtx** [comment]
Apple silicon support will be available starting with Go 1.16 (which is to be released in February). I've added it as a task here: https://github.com/keptn/keptn/issues/2936

**Comment by jfdona23** [comment]
Thanks @christian-kreuzberger-dtx for your efforts to get CLI running in ARM :partying_face:. Is there any plan to get the Docker images available for ARM as well, or just the CLI?

**Comment by christian-kreuzberger-dtx** [comment]
While the CLI does not seem to cause any problems, Docker Images are another thing. It's going to be non-official / experimental release at best.
I've been trying to do some stuff on Raspberry Pi 3 (B+) last night, and it seems to not go very well (memory...).

But Raspberry Pi 4 (arm64) should be possible :crossed_fingers:

**Comment by jfdona23** [comment]
RPi 4 is indeed quite capable, I'm running an empty k3s cluster without any issues and low resources consumption. I'll see to find an old amd64 machine to get my hands on Keptn asap :smile: 

Thanks!! :wave: :argentina:

**Comment by christian-kreuzberger-dtx** [comment]
So technically it should be enough to download the source code and run
```
make build-docker
```
to build the images locally.

Installing Keptn from a local docker registry though is a different story.
