### ISSUE TITLE
Keptn Bridge: UI support for remediation actions

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#2299]
**Problem statement:**
Keptn supports the automatic execution of so-called "remediation actions" in response to alerts (aka. problem events) from external sources (e.g., Prometheus). Remediation actions are linked to these alerts via a dedicated `remediation.yaml` file. A `remediation.yaml` file is mapped to a service running in a stage: 

`remediation action` --- *many to one mapping to* -- `remediation.yaml` file --- *one to one mapping to* --- `service/stage`

Please find the specification of a remediation.yaml here: [https://github.com/keptn/spec/blob/master/remediation.md](https://github.com/keptn/spec/blob/master/remediation.md)

The problem is that right now there is no way in the Keptn Bridge to visualize which actions will be triggered by Keptn in response to alerts. As the `remediation.yaml` file can hold multiple actions and is attached to one service, the need for visualization of this file is given.

**Potential solution**:
Re-use the environment screen in the Keptn Bridge that displays all stages and services. When clicking on a stage and then on a service, I see the remediation file from the service (please see mock below). When clicking on the remediation file, all remediation actions should be shown and customizable. 

*Screenshots*:

- In this mockup, the service `carts` in stage `prod-cluster-A` is selected.

![image](https://user-images.githubusercontent.com/729071/96552223-c1838500-12b3-11eb-82ac-27605e6cdf75.png)

- When clicking on *Show:* **Remediation**  (as highlighted in yellow), the remediation is displayed by its problem type and the remediation actions. For an initial MVP, a representation of the plain yaml file works too.  
- As a user, I would like to add/delete/update a remediation action
- As a user, I would like to add a remediation

Support: UI components are provided by the open-source framework [Barista](https://github.com/dynatrace-oss/barista).

**Optional**

- If the feature of editing remediation for a service is implemented, the SLI/SLO file could be customizable too; at least the plain yaml file.

**Comment by Mayank4git** [comment]
I am interested in this projects.i am good enough in working with js framework like in this one i.e. angular.so please assign this task to me

**Comment by jetzlstorfer** [comment]
Thanks all for your interest (either here or in Slack). The issue has been proposed to the CNCF Community Bridge program and the selected mentee will be assigned to the issue. 
You can still contribute to Keptn, e.g., by taking a look at our good first issues here: https://github.com/keptn/keptn/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

**Comment by ayushnawal** [comment]
I have been selected as a mentee under the CNCF community bridge program and I would like to take this up. 
@jetzlstorfer could you please assign it to me?

**Comment by johannes-b** [comment]
Hi @ayushnawal and @jetzlstorfer, 

I slightly updated the content of the issue by providing a new wireframe. As you can see in the new wireframe, the remediation of a file should be editable through the *Environment* screen (before we thought to introduce a new screen).

**Comment by jetzlstorfer** [comment]
FYI @ayushnawal 

resources like the `remediation.yaml` and the `sli.yaml`/`slo.yaml` can be fetched via this endpoint from the `configuration-service` (can be found in the Swagger UI of your Keptn installation)

![image](https://user-images.githubusercontent.com/7677092/96580691-f5bd6c80-12d8-11eb-8f9c-f4d3621b2663.png)

**Comment by ayushnawal** [comment]
ON IT

**Comment by christian-kreuzberger-dtx** [comment]
This issue is available again!

**Comment by johannes-b** [comment]
I closed this issue because this is not the way we envision displaying remediations in the future. Please see here: https://github.com/keptn/enhancement-proposals/issues/40 for more details.
