### ISSUE TITLE
Incorrect mimetypes in Bridge

### ISSUE THREAD

**Issue by drzero42** [keptn/keptn#2301]
Your issue may already be reported! Please search on the [issue tracker](https://github.com/keptn/keptn/issues) before creating a new one.

**Environment**

* Client OS (e.g., Linux, OSX, Windows): Ubuntu 20.04
* Keptn Version (`keptn version`): 0.7.1
* Kubernetes Cloud Provider (e.g., GKE, AKS): minikube
* Kubernetes version (`kubectl version`): v1.18.8
* Web Browser: Firefox 80.0.1 / Chrome 85

**Affected Component**

* [ ] Docs
* [ ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [x] Bridge
* [ ] Gatekeeper
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**

I am experimenting with Keptn for the first time, by going through the "Onboarding a Service" tutorial. When running the CLI steps, I wanted to follow along in the Bridge web interface. As I reloaded the page, it gave me a blank page. Looking in the Developers Console it shows that various Javascript and CSS files are served with the `text/html` mimetype, which under normal conditions in both newest versions of Firefox and Chrome are not allowed.

Errors from Firefox:
```
The stylesheet http://localhost:8080/bridge/project/styles.4a1fff46217792f8c732.css was not loaded because its MIME type, “text/html”, is not “text/css”.
Loading module from “http://localhost:8080/bridge/project/runtime-es2015.0dae8cbc97194c7caed4.js” was blocked because of a disallowed MIME type (“text/html”).
Loading module from “http://localhost:8080/bridge/project/polyfills-es2015.d553c958fffc2cabaa70.js” was blocked because of a disallowed MIME type (“text/html”).
Loading module from “http://localhost:8080/bridge/project/main-es2015.77429ba456a3f39fe698.js” was blocked because of a disallowed MIME type (“text/html”).
```

Errors from Chrome:
```
Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
```

**To Reproduce**

1. Deploy Keptn to a cluster
2. Onboard at least one service with the CLI
3. Go to the web interface in the latest version of either Chrome or Firefox
4. Click on your onboarded project
5. Open the developer console (F12)
6. Reload page
7. Observe errors in developer console

**Comment by ermin-muratovic** [comment]
@drzero42 thank you for reporting the Issue.

Could you please provide me the link to the tutorial page, that you have used? Just to make sure, that there is no mistake in the tutorials page and to make sure you used the right tutorial for that specific keptn version. Thanks.

**Comment by drzero42** [comment]
@ermin-muratovic https://keptn.sh/docs/0.6.0/usecases/onboard-carts-service/
And I installed following the Quickstart available here: https://keptn.sh/docs/0.7.x/operate/install/#create-or-bring-kubernetes-cluster
I used Minikube with Kubernetes v1.18.8 and used a port-forward to access the Bridge webinterface.
