### ISSUE TITLE
Upgrader from 0.6.2 to 0.7.0 accidentally applies the "latest" helm chart

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#2303]
**Environment**

* Client OS (e.g., Linux, OSX, Windows): Linux
* Keptn Version (`keptn version`): 0.6.2 (and 0.7.0)
* Kubernetes Cloud Provider (e.g., GKE, AKS): GKE
* Kubernetes version (`kubectl version`): 1.15

**Affected Component**

* [x] Docs
* [x] CLI
* [x] Kubernetes Integration
* [x] upgrader

**Describe the bug**

I tried to ugprade from 0.6.2 to 0.7.0 according to the docs here: https://keptn.sh/docs/0.7.x/operate/upgrade/#upgrade-from-keptn-0-6-2-to-0-7

The result was that my Keptn installation was upgraded to 0.7.1 instead of 0.7.0

**To Reproduce**

1. Install Keptn 0.6.2
2. Upgrade to Keptn 0.7.0

**Expected behavior**

Keptn 0.7.0 is installed

**Current behavior**

Keptn 0.7.1 is installed

**Analysis**

The problem lies here: 
https://github.com/keptn/keptn/blob/0.7.0/upgrader/upgrade-062-070/upgrade-job.yaml specifies `HELM_CHART_URL` as `https://storage.googleapis.com/keptn-installer`, while the upgrader would have used the manifest with version 0.7.0:
https://github.com/keptn/keptn/blob/0.7.0/upgrader/upgrade-062-070/scripts/upgradeKeptn.sh#L31-L32

This leads to the "latest" version being installed, which currently is 0.7.1

**Fix**

We need to re-release the upgrader for 0.7.0 to ensure that 0.7.0 is installed, not latest.

**Comment by johannes-b** [comment]
We will fix this issue with a re-release of Keptn 0.7 on GitHub.
