### ISSUE TITLE
Wrong version number for api endpoints

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#2315]
While the version for the general `api` endpoint in the swagger docs is set correctly, the version numbers for the `configuration-service` and the `mongodb-datastore` are set to 0.1.0.

Please adjust the version numbers accordingly.

![image](https://user-images.githubusercontent.com/7677092/92689662-aed67180-f33f-11ea-977b-34c0fadce8b6.png)

![image](https://user-images.githubusercontent.com/7677092/92689672-b564e900-f33f-11ea-9b88-a42e4360f1c3.png)

**Comment by christian-kreuzberger-dtx** [comment]
The mechanism is quite easy to implement. As an example, this is what we do in api-service:

https://github.com/keptn/keptn/blob/0.7.1/api/Dockerfile#L30-L31

https://github.com/keptn/keptn/blob/0.7.1/api/swagger.yaml#L5
