### ISSUE TITLE
Missing documentation on how to use Keptn Quality Gates

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#2316]
While the documentation on https://keptn.sh/docs list the concept of Keptn Quality Gates as well as the structure of SLI and SLO files, details on how to actually set up a quality gate and how to trigger the evaluation are missing.

Would be great to have detailed information on:
- what is needed to set up a quality gate with Keptn
- how to integrate a quality gate in an existing pipeline
- how to trigger a quality gate with the Keptn CLI
- how to get the evaluation of a quality gate with the Keptn CLI
- how to trigger a quality gate with the Keptn API
- how to get the evaluation of a quality gate with the Keptn API

**Comment by johannes-b** [comment]
Thanks for creating it. Without looking at your issue, I created the same issue too. 
Let me close that one with a reference to the issue here: https://github.com/keptn/keptn.github.io/issues/636
