### ISSUE TITLE
Keptn Bridge: Download CLI link in user menu

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#2319]
In the *Get started* section, a link `Download Keptn CLI` is provided that points to an external URL (e.g., https://github.com/keptn/keptn/releases/tag/0.7.1) that hosts the CLIs for Mac, Windows, Linux. 

![image](https://user-images.githubusercontent.com/729071/92733069-879b9680-f377-11ea-8b78-10f72208de55.png)

**Task**
- Show the Download Keptn CLI link in the user menu
- The link to the CLI is not hard-coded, but rather configurable by an environment variable

**Comment by agrimmer** [comment]
Can we please make the Download Link configurable in the values file of the Helm chart.
