### ISSUE TITLE
As a keptn user, I want to use plain K8s deployment and service manifests to onboard a service

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#236]
Helm should not be used, when onboarding a service by using plain K8s deployment and service manifests.

**Acceptance criteria**
- **Given** I'm a keptn user and I've created a project to which I want to onboard a service
  **When** I have the plain K8s deployment and service manifest. 
  **Then** I can use the keptn CLI to onboard this service: `keptn onboard service --project=xy --deployment=carts_depl.yaml --service=carts_svc.yaml`

**Comment by dirkwall** [comment]
Closing, we can already provide service and deployment files when onboarding a new service.
