### ISSUE TITLE
helm-service: Make public deployment URI configurable

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#2362]
With Keptn 0.7.x we introduced the option for continuous deployments to configure the ingress port, protocol, and suffix, e.g.:
https://keptn.sh/docs/0.7.x/continuous_delivery/expose_services/#create-configmap-with-ingress-information

This is already used here:
https://github.com/keptn/keptn/blob/a8871e327082aaeee6f11a24d8cd183f9e52274a/helm-service/controller/helm/generated_chart_handler.go#L139
and here
https://github.com/keptn/keptn/blob/a8871e327082aaeee6f11a24d8cd183f9e52274a/helm-service/controller/workflow_engine_replacer.go#L95

This generates hostnames that look as follows:
```
${INGRESS_PROTOCOL}://${service}.${project}-${stage}.${INGRESS_HOSTNAME}:${INGRESS_PORT}
```
Example: https://carts.sockshop-dev.127.0.0.1.nip.io:443

# Enhancement

I believe that we can go one step further and make the hostname generation fully configurable, by introducing a config with placeholders, e.g.:

```
HOSTNAME_TEMPLATE=${INGRESS_PROTOCOL}://${service}.${project}-${stage}.${INGRESS_HOSTNAME}:${INGRESS_PORT}
```

In addition, this allows users to change certain parts of the logic, e.g., 
* `...${service}-${stage}.${project}...` (carts-dev.sockshop.127.0.0.1.nip.io)
* `...${service}-${stage}-${project}...` (carts-dev-sockshop.127.0.0.1.nip.io)

The later has the benefit that you can use a wildcard certificate for `${INGRESS_HOSTNAME}`, instead of having to generate wildcard certificates for each stage.

# Definition of Done

- [ ] extend [ingress_config.go](https://github.com/keptn/keptn/blob/1614949ddeb1f66821619fbcdf2a20c55fb0bf9f/helm-service/controller/mesh/ingress_config.go) with a function to read `HOSTNAME_TEMPLATE`
- [ ] Change the URL generation in helm-service such that it uses and processes the hostname template (please use a built-in templating syntax of GoLang)
- [ ] The default behaviour (service.project-stage....) must still work as it was

**Comment by dsam82** [comment]
Hi, If someone is not working on this issue. Can I take it?

**Comment by dsam82** [comment]
If anyone is not working on this, then I would like to take the issue. I may need some guidance on how to approach this.

**Comment by christian-kreuzberger-dtx** [comment]
Hi! Thanks for approaching us, I've assigned this ticket to you.

> I may need some guidance on how to approach this.

For organizational questions and processes, please go through our [Contribution Guide](https://github.com/keptn/keptn/blob/master/CONTRIBUTING.md).

For coding, first thing I recommend  is installing Keptn with continuous delivery enabled on a Kubernetes cluster (either in the Cloud or locally using K3s) - see https://keptn.sh/docs/0.7.x/operate/install/ for options.

Fork and clone this repo, branch away from master (e.g., `git checkout -b feature/2362/helm_deployment_uri`) and start coding in the `helm-service` directory ;)

I've linked two files and the respective lines of code in the issue above, this should be a good starting point. If you need any more guidance, please let us know.

**Comment by dsam82** [comment]
@christian-kreuzberger-dtx I am not able to understand how are we going to define `HOSTNAME_TEMPLATE` and how would we use it? Is it going to be an env variable also? Or do we have to define a new struct for `HOSTNAME_TEMPLATE`?
Can you elaborate a bit more?

**Comment by christian-kreuzberger-dtx** [comment]
For now `HOSTNAME_TEMPLATE` is going to be an environment variable, same as [here](https://github.com/keptn/keptn/blob/1614949ddeb1f66821619fbcdf2a20c55fb0bf9f/helm-service/controller/mesh/ingress_config.go)

**Comment by christian-kreuzberger-dtx** [comment]
Re-assigning this issue to @warber
