### ISSUE TITLE
Misleading error message after upstream synchronization

### ISSUE THREAD

**Issue by neox5** [keptn/keptn#2363]
**Environment**

* Client OS (e.g., Linux, OSX, Windows): **Ubuntu 18.04**
* Keptn Version (`keptn version`): **v0.7.1**
* Kubernetes Cloud Provider (e.g., GKE, AKS): **n.a. / azure VM**
* Kubernetes version (`kubectl version`): **k3s v1.18.8+k3s1**

Using a azure devOps repository

**Affected Component**

* [ ] Docs
* [X] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [ ] Bridge
* [ ] Gatekeeper
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**
Missleading error message after synchronization with upstream, although action was correctly performed (changes are in repo and logs show no further errors): e.g:
```shell
triscon@ubuntu-1804:~$ keptn create service frontend-ttt --project=ttt
# Output
Starting to create service
ID of Keptn context: b78bcb58-94e9-413d-9e63-fa5009713218
Opening websocket failed
Error: websocket: bad handshake
```
```shell
❯ k logs configuration-service-769bc757df-n8fsb -n keptn -c configuration-service
##########
branch: release-0.7.1
repository: https://github.com/keptn/keptn
commitlink: https://github.com/keptn/keptn/commit/0e49d8d74c29736329448535ca65e1c673306c73
repolink: https://github.com/keptn/keptn/tree/0e49d8d74c29736329448535ca65e1c673306c73
travisbuild: https://travis-ci.org/keptn/keptn/jobs/724087561
timestamp: 20200904.1204
##########
{"timestamp":"2020-09-16T05:24:48.779990109Z","logLevel":"DEBUG","message":"Configuring git user.email"}
{"timestamp":"2020-09-16T05:24:49.636341333Z","logLevel":"DEBUG","message":"Configuring git user.name"}
2020/09/16 05:24:49 Serving configuration service at http://[::]:8080
No MongoDB client has been initialized yet. Creating a new one.
Adding stage dev to project ttt
{"timestamp":"2020-09-16T06:36:39.339707092Z","logLevel":"INFO","message":"Added stage dev to project ttt"}
{"timestamp":"2020-09-16T06:36:39.341669007Z","logLevel":"DEBUG","message":"Creating new resource(s) in: /data/config/ttt"}
{"timestamp":"2020-09-16T06:36:39.341690307Z","logLevel":"DEBUG","message":"Checking out master branch"}
{"timestamp":"2020-09-16T06:36:39.470226677Z","logLevel":"DEBUG","message":"Adding resource: /data/config/ttt/shipyard.yaml"}
{"timestamp":"2020-09-16T06:36:39.495705869Z","logLevel":"DEBUG","message":"Staging Changes"}
{"timestamp":"2020-09-16T06:36:41.054740725Z","logLevel":"DEBUG","message":"Successfully added resources"}
{"timestamp":"2020-09-16T13:41:13.552180569Z","logLevel":"DEBUG","message":"Creating new resource(s) in: /data/config/ttt in stage dev"}
{"timestamp":"2020-09-16T13:41:13.552235069Z","logLevel":"DEBUG","message":"Checking out branch: dev"}
{"timestamp":"2020-09-16T13:41:16.754826555Z","logLevel":"INFO","message":"Adding frontend-ttt to stage dev in project ttt in database"}
{"timestamp":"2020-09-16T13:41:16.755592255Z","logLevel":"INFO","message":"Service frontend-ttt has been added to stage dev in project ttt"}
```

**To Reproduce**

ingress configuration:
```yaml
# keptn-api-ingress-manifest.yaml
---
apiVersion: networking.k8s.io
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  namespace: keptn
  name: keptn-api-ingress
spec:
  rules:
  - host: keptn.<YOUR-SERVER-IP>.nip.io
    http:
      paths:
      - backend:
        serviceName: api-gateway-nginx
        servicePort: 80
```
GIT_REMOTE_URL=https://dev.azure.com/.../.../_git/keptn-ttt
```
keptn create project PROJECTNAME --shipyard=FILEPATH --git-user=GIT_USER --git-token=GIT_TOKEN --git-remote-url=GIT_REMOTE_URL
```

**Expected behavior**
Better error message which explains the cause, or even better, gives a hint to solve this issue.

**Current behavior**
Error message is misleading, as it would indicate that the action was not performed correctly.

**Screenshots**

**Additional context**
API-Gateway is only exposed through port 80, so any backend service trying to use HTTPS would have troubles.

**Comment by christian-kreuzberger-dtx** [comment]
Although we have documented this behaviour (see https://keptn.sh/docs/0.7.x/operate/install/#authenticate-keptn-cli ), I agree with you that the error message is misleading.

Here is my proposal for a better message:
```
$ keptn create service frontend-ttt --project=ttt
# Output
Starting to create service
ID of Keptn context: b78bcb58-94e9-413d-9e63-fa5009713218
Failed to connect to websocket (error: bad handshake). Log messages will not be shown. This is expected to happen if you Keptn API is exposed by a port-forward and/or without HTTPS support.
Use --suppress-websocket to avoid trying to connect to the websocket.
```

@agrimmer @johannes-b is that okay for you?

**Comment by neox5** [comment]
FYI: I got the same error message with the configure command too.

```shell
triscon@ubuntu-1804:~$ keptn configure monitoring dynatrace --project=ttt
ID of Keptn context: 4b1957af-73aa-483e-a2a1-386e1807abb5
Opening websocket failed
Error: websocket: bad handshake
```

**Comment by grabnerandi** [comment]
Hi @neox5 - you can double check by opening dynatrace and validating if you can see some auto-tagging rules (Settings -> Tags -> Auto-Tagging Rules). You can also validate if you have a new dashboard being created as well as a management zone and an alerting profile (settings -> ingreation -> problem notification)
What configure monitoring also does is creating a config map entry so that the lighthouse services knows that you want to use dynatrace as the sli provider for your project ttt. for that - check if you have a config map in the keptn namespace called lighthouse-config-ttt and validate that the sli provider is set to dynatrace within that config map

**Comment by johannes-b** [comment]
@christian-kreuzberger-dtx providing guidance for the user when WebSocket is not possible is definitely an improvement we should tackle by implementing this issue.

**Comment by agrimmer** [comment]
I would be interested in why the WebSocket does not work.
Do you have any proxy which prevents upgrading an HTTP connection to WebSocket?

**Comment by neox5** [comment]
- auto-tagging-rules set ✔️ 
- dashboard created ✔️ 
- management zone created ✔️ 
- Keptn alerting profile ✔️ 
- lighthouse config map with Dynatrace sli provider ✔️ 
@grabnerandi  Thx for the additional verification points!

**Comment by neox5** [comment]
@agrimmer We use no proxy in front of our cluster, but as mentioned in the original post Keptn can only be accessed through port 80 via the gateway as you can see in the ingress manifest.

**Comment by agrimmer** [comment]
It is on purpose that Keptn can only be accessed through port 80. If you want https, then please do the required TLS termination using the Ingress.
