### ISSUE TITLE
Support custom-values.yaml in keptn install

### ISSUE THREAD

**Issue by neox5** [keptn/keptn#2364]
**Is your feature request related to a problem? Please describe.**
Currently `keptn install` can only be customized with different flags like:
--plattform
--use-case
--endpoint-serivice-type
etc.
which then are used as input for the helm client:

```go
values := map[string]interface{}{
		"continuous-delivery": map[string]interface{}{
			"enabled": installParams.UseCase == ContinuousDelivery,
			"openshift": map[string]interface{}{
				"enabled": *installParams.PlatformIdentifier == "openshift",
			},
		},
		"control-plane": map[string]interface{}{
			"enabled": true,
			"apiGatewayNginx": map[string]interface{}{
				"type": installParams.EndPointServiceType.String(),
			},
		},
	}

	if err := helm.NewHelper().UpgradeChart(keptnChart, keptnReleaseName, keptnNamespace, values); err != nil {
		logging.PrintLog("Could not complete Keptn installation: "+err.Error(), logging.InfoLevel)
		return err
	}
```

The problem is that underlying values for example `control-plane.prefixPath` can not be configured that way and one has to use keptn's helm charts for a custom deployment.

Example: PR #2172 

**Describe the solution you'd like**
I would suggest to replace current flags related with the helm chart with one --values flag to accept a custom-values.yaml file. So you can use the keptn cli right away for new features and you would not depend on helm and there would be no additional development effort to bring new features to the cli.

If no values file is specified, fall back to keptn/installer/manifests/keptn/values.yaml.

Maybe add a custom-values-template.yaml with all customizable values to give a better overview on which parameters are experimental/stable. 

**Describe alternatives you've considered**
I tried to add a custom flag for the prefixPath to cobra, but helm had an issue with a missing value in the core.yaml file. Maybe a missing env variable.

**Additional context**

**Comment by christian-kreuzberger-dtx** [comment]
> I would suggest to replace current flags related with the helm chart with one --values flag to accept a custom-values.yaml file. So you can use the keptn cli right away for new features and you would not depend on helm and there would be no additional development effort to bring new features to the cli.

I like this idea.

> Maybe add a custom-values-template.yaml with all customizable values to give a better overview on which parameters are experimental/stable.

Good thinking, we could provide some examples in our [keptn/examples repo](https://github.com/keptn/examples).

@agrimmer @johannes-b  what's your take on this?

**Comment by agrimmer** [comment]
Agree; nice and easy enhancement for the CLI!

**Comment by anukul** [comment]
Hi, I would like to try this!

**Comment by adigeak** [comment]
@johannes-b i can work on this.

**Comment by johannes-b** [comment]
Hello @adigeak 
while this issue would have had a strong value a year ago, it turned out that many users directly deploy the `helm chart` for a customized deployment of Keptn. (see: https://keptn.sh/docs/0.8.x/operate/advanced_install_options/#advanced-install-options-install-keptn-using-the-helm-chart) 

Since the value is not that high anymore, I would like to close this issue.
