### ISSUE TITLE
Hovering over the score in an approval.triggered events leads to a scroll-up / jump-up in Firefox

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#2369]
I'm using Keptn 0.7.1, and this is my event chain:
![Screenshot from 2020-09-17 14-58-22](https://user-images.githubusercontent.com/56065213/93473392-3ef35880-f8f6-11ea-99d8-075beb398242.png)

This is my approval.triggered event:
```
{
  "contenttype": "application/json",
  "data": {
    "deploymentstrategy": "blue_green_service",
    "image": "docker.io/keptnexamples/carts",
    "labels": null,
    "project": "ck-sockshop",
    "result": "warning",
    "service": "carts",
    "stage": "production",
    "tag": "0.11.2",
    "teststrategy": "performance"
  },
  "id": "28e1f667-3489-4860-8690-8fd5131a5534",
  "source": "gatekeeper-service",
  "specversion": "0.2",
  "time": "2020-09-17T12:38:08.253Z",
  "type": "sh.keptn.event.approval.triggered",
  "shkeptncontext": "6b2b8682-05a5-431c-8cf9-a38e61f56486"
}
```

Hovering over the score (50) should look as follows (and does look as follows on Chrome):
![image](https://user-images.githubusercontent.com/56065213/93473499-5fbbae00-f8f6-11ea-83b1-a116a00950c4.png)

But when I open this on Firefox 80.0.1 (64-bit, Ubuntu 20.04), I don't see the overlay, but the browser jumps up a couple of pixels

Docs of Tooltip component: https://barista.dynatrace.com/components/overlay

**Comment by johannes-b** [comment]
I can confirm the same issue on my Windows machine with Firefox: 80.0.1
When hovering over the icon, the browser jumps up a couple of pixels

**Comment by christian-kreuzberger-dtx** [comment]
@johannes-b Please add this to known issues in the release-notes.

**Comment by christian-kreuzberger-dtx** [comment]
Docs of Tooltip component: https://barista.dynatrace.com/components/overlay

**Comment by ermin-muratovic** [comment]
This can't be reproduced in 0.8.x, since the Approval item is the first element in a stage and now displayed on top always.

See:
![image](https://user-images.githubusercontent.com/6098219/108724173-55e14b00-7525-11eb-8cd9-872c0d5b2838.png)
