### ISSUE TITLE
CI: Include pluto to automatically check for deprecated K8s apiVersions

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#2382]
@thschue pointed out this open source project to me: https://github.com/FairwindsOps/pluto

Essentially this tries to detect outdated apiVersions (such as with k8s 1.16 which we already had to look at, see https://github.com/keptn/keptn/issues/1529 ) and reports them, e.g.:

```
helm template e2e/tests/assets/helm3chart | pluto detect -
KIND         VERSION              DEPRECATED   DEPRECATED IN   RESOURCE NAME
Deployment   extensions/v1beta1   true         v1.16.0         RELEASE-NAME-helm3chart-v1beta1
```

This is beneficial for our CI, as we will get an early notice whether one of our Helm Charts or K8s manifests is outdated or might become outdated soon.

**Comment by christian-kreuzberger-dtx** [comment]
@anukul is working on this issue

**Comment by anukul** [comment]
Please assign this to me 😬
