### ISSUE TITLE
Introduce an endpoint in the api-service, which allows to trigger an evaluation

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#2387]
As a user, I would like to have a dedicated API endpoint that allows to start an evaluation. More precisely, currently, the `/event` endpoint can be used to start evaluations but this is too generic and, hence, complicated to use. Instead, as a user, I would like to have a dedicated endpoint, which allows triggering an evaluation and specifying the start, end, and timeframe as parameters similar to the CLI.

**Tasks:**
- Introduce a POST endpoint /project/{projectName}/stage/{stageName}/service/{serviceName}/evaluation/ with the following parameters:
    - start: The starting point from which to start the evaluation in UTC
    - end: The endpoint to which the evaluation data should be gathered in UTC (can not be used together with --timeframe)
    - timeframe: The time frame from which the evaluation data should be gathered (can not be used together with --end)
    All those parameters should be optional and there should be the same defaults as in the CLI (e.g. do the evaluation for the last 5 minutes)
- This endpoint returns the keptnContext and token (similar to `/event`)
- The api-service creates the appropriate CloudEvent and sends it to the event-broker (for 0.7.2) and to NATS for (0.8.0)
- Use this endpoint in the CLI command `keptn send event start-evaluation`
- The api-service has to check whether the project, service and stage exists.

**Note:** This endpoint does not return the evaluation data but only triggers the evaluation.

**Definition of Done:**
- A user can trigger an evaluation with `curl -X POST "HOST/api/v1/project/{projectName}/stage/{stageName}/service/{serviceName}/evaluation" -H "accept: application/json" -H "x-token: TOKEN"`

**Comment by johannes-b** [comment]
I tried out the new endpoint and figured out that the model in the Swagger-UI is broken:

![image](https://user-images.githubusercontent.com/729071/94415727-3a446500-017e-11eb-9748-5d69e3b35bdc.png)

Can we also please rename the properties `from` and `to` to `start` and `end`, respectively? Otherwise, it is different compared to the CLI.
