### ISSUE TITLE
As a keptn user, I do not want keptn to use my private Github user 

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#239]
The Github-service uses a private GitHub user for managing the configuration repository.
Research: Investigate whether [GitHub Apps](https://developer.github.com/apps/building-github-apps/) can be used.

**Acceptance criteria**
  **Given** I'm a keptn user 
  **When** I call `keptn configure` from the command line
  **Then** I do not want to use my private Github user and token

**Comment by dirkwall** [comment]
Closing for now. Will be reworked with the refactoring of the github-service. No relevance right now.
