### ISSUE TITLE
Add build and run targets in the Makefile

### ISSUE THREAD

**Issue by supra08** [keptn/keptn#2405]
Currently, the Makefile available in the `keptn` codebase has no targets, and building different components such as the bridge, CLI, etc is a manual task.

A Makefile containing commands for building all of these targets will come handy for quick setup and development. Besides building stuff, this Makefile can be used as a general-purpose task runner. To name a few:
* Format using `gofmt`
* Various tests such as e2e and unit
* Code lint
* Prepare-for-pr that would combine some of the above options to make the committed code ready for PR.
* Prepare for release.
This list is not exhaustive and a number of things can be added more. This can also handle better management of the actual `keptn` binary and the development binary.

**Comment by supra08** [comment]
Also, I would like to be assigned and take this up.

**Comment by christian-kreuzberger-dtx** [comment]
Thanks, assigned!
