### ISSUE TITLE
Make log level output configurable in go-utils

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#2413]
**Is your feature request related to a problem? Please describe.**
When using Go-Utils Logger we potentially end up with log floods becuase we cannot control which log level actually makes it to the log output. I am currently working on the dynatrace-sli-service and it does a lot of debug and info logging.
A single evaluation will produce hundreds of log entries which is great for troubleshooting but not needed in normal operation

**Describe the solution you'd like**
I would like to be able to set the Log Level of a container through an environment variable, e.g: KEPTN_LOG_LEVEL=ERROR
this would mean only ERROR and TERMINATE will make it to the log file

**Comment by anukul** [comment]
Hi, I would like to try this!

> e.g: KEPTN_LOG_LEVEL=ERROR
this would mean only ERROR and TERMINATE will make it to the log file

Can you please confirm this example?

I see that [`Logger.Terminate()`](https://github.com/keptn/go-utils/blob/master/pkg/lib/keptn/logger.go#L54-L57) emits logs with level `INFO`.
Separately, it sets `LogData.Terminate = True` for the CLI, when writing logs  through [`CombinedLogger`](https://github.com/keptn/go-utils/blob/189e0ad20c270fa7556faaf24816bdeb38490745/pkg/lib/keptn/combined_logger.go#L10-L15).

**Comment by bacherfl** [comment]
Hi @anukul! 
yes, the mentioned example is correct.
And you are right, we need to make sure that the messages sent by `Logger.Terminate()` make it to the CLI, independently from the configured LogLevel.
If you would like to, feel free to tackle this Issue, we are always happy about contributions :-)

**Comment by anukul** [comment]
@bacherfl Thanks. Is there a specific reason that it uses level `INFO`?  
Can we change it to a new level that has a higher numeric value, so that it's not a special case?

**Comment by agrimmer** [comment]
As we currently do not support to dynamically configure the log level, I would always print any log message to STDOUT regardless of its log level. This could really help when we have to debug any service running in production.
But I also see the need for some external tool, which allows us to import the logs and then to filter on log levels.

@anukul You are right that the terminate message should have a dedicated log level and not reuse `INFO`. But please be aware that changing this would also require changes in the CLI.

**Comment by christian-kreuzberger-dtx** [comment]
@bacherfl @warber The two of you have done a lot of refactoring in go-utils lately. Especially as we have removed the websocket communication, I was thinking that this might not be an issue anymore for `go-utils`? 

Or do we actually advise users to use a different logging mechanic now, e.g., the built-in logging from GoLang?
