### ISSUE TITLE
Add a feature to get and validate Keptn monitoring configuration

### ISSUE THREAD

**Issue by robertjahn** [keptn/keptn#2415]
**Is your feature request related to a problem? Please describe.**
There are times when I want to view and validate my monitoring configuration.  For example, viewing what projects are enabled for a given monitoring provider or to ensure my Dynatrace configuration for all auto-tagging rules are enabled.

**Describe the solution you'd like**
1. Add a `keptn get monitoring` and command.  This would output all the projects configured.  Have an option to filter with `--project [project name]`

```
type             project             service
====             =======            ===========
promethius       projectA           service 1
promethius       projectA           service 2
promethius       projectA           service 3
dynatrace        projectB           n/a
```

2) Add an automated check to verify ALL the setup is valid such as `keptn verify monitoring <monitoring provider>`.  The implementation will need to be done within each monitoring provider.    

For example, here is mockup of the output from  dynatrace check `keptn verify monitoring dynatrace --project=sockshop`.    

```
Validating dynatrace configuration
Project: sockshop
Keptn dynatrace service version=0.8.0
Dynatrace URL: http://[my tenant].live.dynatrace.com
Keptn URL: http://[my keptn host]/bridge/dashboard
Keptn Bridge URL: http://[my keptn host]/api
-----
Tagging rule keptn_service - DISABLED
Tagging rule keptn_stage  - OK
Tagging rule keptn_project  - MISSING
Tagging rule keptn_deployment  - OK
Setting up problem notifications in Dynatrace Tenant
Keptn alerting profile - OK
Dashboard for project sockshop - MISSING
Creating custom metric events for project SLIs - OK
```

For example, here is mockup of the output from  dynatrace check `keptn verify monitoring prometius --project=sockshop`.    

```
Validating prometius configuration
Keptn promethius service version=0.3.5
-----
Configured Endpoints for Project: sockshop
http://carts.sockshop-dev.svc.cluster.local/promethius   UP
http://carts.sockshop-staging.svc.cluster.local/promethius   UP
http://carts.sockshop-production.svc.cluster.local/promethius   UP
```

The check will return a unix exit code of zero if all checks pass and a non-zero code if it does not.

**Describe alternatives you've considered**
manually triage and review rules

**Additional context**
None

**Comment by christian-kreuzberger-dtx** [comment]
Your request is very specific to Dynatrace. Could you formulate it such that it is also valid for a generic monitoring solution? If not, we'll have to move this issue over to **keptn-contrib/dynatrace-service**.
