### ISSUE TITLE
Improve post-installation steps by including Keptn API endpoint IP

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#2444]
When installing Keptn with the option NodePort or LoadBalancer it would be useful to print the concrete `keptn auth` instructions after the installation. 

**Status quo:**
The instructions that are provided right now include a  `port-forward` which means that if the terminal is closed the Keptn CLI can not communicate to the Keptn installation anymore. 

*Current situation:*
```
$ keptn install --endpoint-service-type=NodePort
Helm Chart used for Keptn installation: https://storage.googleapis.com/keptn-installer/keptn-0.7.1.tgz

Please confirm that the provided cluster information is correct:
Cluster: keptn
Is this all correct? (y/n)
y
Installing Keptn ...
Start upgrading Helm Chart keptn in namespace keptn
Finished upgrading Helm Chart keptn in namespace keptn
Keptn has been successfully set up on your cluster.
---------------------------------------------------
* To quickly access Keptn, you can use a port-forward and then authenticate your Keptn CLI (in a Linux shell):
 - kubectl -n keptn port-forward service/api-gateway-nginx 8080:80
 - keptn auth --endpoint=http://localhost:8080/api --api-token=$(kubectl get secret keptn-api-token -n keptn -ojsonpath={.data.keptn-api-token} | base64 --decode)

* To expose Keptn on a public endpoint, please continue with the installation guidelines provided at:
 - https://keptn.sh/docs/0.7.x/operate/install#install-keptn
```

**Improvement:**
Since for NodePort and LoadBalancer the IPs can be retrieved via `kubectl` commands, it would be useful if this is done during the installation and the result is printed to the user at the end of the installation. 

*Desired solution (for NodePort and LoadBalancer installations):*
```
...
Finished upgrading Helm Chart keptn in namespace keptn
Keptn has been successfully set up on your cluster.
---------------------------------------------------
* To quickly access Keptn, you can use a port-forward and then authenticate your Keptn CLI (in a Linux shell):
 - keptn auth --endpoint=http://43.56.32.3:31090/api --api-token=xxx123
```

**Comment by johannes-b** [comment]
Find the manual instructions (that should be automated by this improvement) here:
- NodePort: https://keptn.sh/docs/0.7.x/operate/install/#option-2-expose-keptn-via-a-nodeport
- LoadBalancer: https://keptn.sh/docs/0.7.x/operate/install/#option-1-expose-keptn-via-a-loadbalancer

**Comment by ankitjain28may** [comment]
@jetzlstorfer I would like to pick this up.

**Comment by christian-kreuzberger-dtx** [comment]
Thanks @ankitjain28may !
