### ISSUE TITLE
Improve CLI auth command by including endpoint in output

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#2445]
When authenticating the Keptn CLI to the Keptn cluster, I often use something like:

```
KEPTN_ENDPOINT=http://<ENDPOINT_OF_API_GATEWAY>/api
KEPTN_API_TOKEN=$(kubectl get secret keptn-api-token -n keptn -ojsonpath={.data.keptn-api-token} | base64 --decode)

keptn auth --endpoint=$KEPTN_ENDPOINT --api-token=$KEPTN_API_TOKEN
```
Output:
```
Starting to authenticate
Successfully authenticated
```

It would be great if the output after this command also includes the `$KEPTN_ENDPOINT`. I know it is easy to retrieve it by `echo $KEPTN_ENDPOINT` but it is an extra step that I would like to get rid of.

The output of `keptn status` would be the right solution in my mind:
```
$ keptn status
Starting to authenticate
Successfully authenticated
CLI is authenticated against the Keptn cluster http://91.xxx.1xx.182:31090/api
```

**Definition of Done:**
- [ ] `keptn auth` shows the endpoint (like the `keptn status` command)

**Comment by ankitjain28may** [comment]
@jetzlstorfer I would like to work on this issue. Thanks
