### ISSUE TITLE
Create project fails on OpenShift due to missing write permissions

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#2453]
When executing `keptn create project` it fails on OpenShift 4.5.8 since the `configuration-service` is not allowed to create the git repository. Seems that it fails on the first write operation. 

Error message:
```
{"timestamp":"2020-09-30T20:05:44.598966413Z","logLevel":"ERROR","message":"Could not create mystage branch for project myphpservice2-qualgate"}
{"timestamp":"2020-09-30T20:05:44.59899139Z","logLevel":"ERROR","message":"Error executing command git checkout master: exit status 1\nerror: pathspec 'master' did not match any file(s) known to git\n"}
```

In this case it is not possible to run the pod as root as this is against the policy of the users organization. 

Is there any workaround available?

**Comment by christian-kreuzberger-dtx** [comment]
Is this related to https://github.com/keptn/keptn/issues/2455 ?

**Comment by cjmckenna** [comment]
No.  This is a different issue.  2455 is for an issue during the install that requires manual intervention to get the PVs bound, this issue is for once keptn is up and running and you try to create a project.  The filesystem in the pod is all owned by root but in a real openshift production enterprise, you can not run containers as root and they have to run as a random user.  So the filesystems being owned by root means that the configuration service can not write to the local git

**Comment by christian-kreuzberger-dtx** [comment]
Ok, thanks for the reply.

As far as I understand, the issue at hand is that we should not run containers on OpenShift as root users, but as random non-root users.

This has several implications on our architecture, such as changing Dockerfiles, writing integration tests, etc..., but will definately help us with hardening our product and increasing adoption towards restrictive Kubernetes environments (not just OpenShift).

I will create follow-up issues and reference back to this issue, so we can get this fixed.

**Comment by christian-kreuzberger-dtx** [comment]
I have created a separate issue that should fix the problem you described: https://github.com/keptn/keptn/issues/2479

I'll leave this open in case anyone else also runs in this problem.

**Comment by cjmckenna** [comment]
I was able to work around this issue by cloning the repo and hacking the dockerfile for the configuration service to chmod 777 the /data/config directory. I then built the container and pushed it to my docker repo and deployed it. This allowed me to create projects after I deployed my custom version of this service. Its a hack and not a solution but got us up and running for now.
