### ISSUE TITLE
Refer user to K3s tutorial in README.md

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#2454]
Based on user feedback, the README.md of keptn/keptn does not help to get started using Keptn since it just explains how to download the CLI. 

The user proposed to refer to the K3s tutorial in the **Usage** section: https://github.com/keptn/keptn#usage

Link to the [K3s tutorial](https://tutorials.keptn.sh/tutorials/keptn-installation-k3s-07/index.html?index=..%2F..index#0)

**Comment by christian-kreuzberger-dtx** [comment]
I'd go as far as making the quickstart in the README.md here:

Getting started:
1. Install K3s
```console
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.18.3+k3s1 K3S_KUBECONFIG_MODE="644" sh -s - --no-deploy=traefik
export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
```
2. Install Keptn
```console
curl -sL https://get.keptn.sh | sudo -E bash
keptn install
```

**Comment by pahofmann** [comment]
I'd take this issue.
