### ISSUE TITLE
Configuration service not starting on OpenShift 4

### ISSUE THREAD

**Issue by cjmckenna** [keptn/keptn#2455]
Testing keptn on our enterprise openshift 4 platform we encountered an issue where the configuration service was getting a crash loop backoff because it could not bind to the PV.  In researching, we found that the configuration-volume was stuck in a pending state as when it was created by keptn there was no way to specify a storage class.  In order to get the configuration service running, we had to drop the PV and recreate it manually making sure to set the storage class to one of the ones available to us.

**Comment by christian-kreuzberger-dtx** [comment]
Hi! Please let us know which Keptn CLI Version you are using, which OpenShift version, and how you installed keptn (e.g., `keptn install --platform=openshift`).

**Comment by jetzlstorfer** [comment]
Waiting for feedback from @cjmckenna if that workaround does the trick

**Comment by cjmckenna** [comment]
I am at the end of a sprint I need to focus on.  I will try to get to this before end of week or early next week

**Comment by cjmckenna** [comment]
We are not able to run the fix due to this line: --create-namespace

In our environment, namespaces can only be created using Hermes.

**Comment by christian-kreuzberger-dtx** [comment]
I'm not an expert with `helm`, but can you just leave out the `--create-namespace` in this case? Helm doesn't need to create the namespace it's just the default option in our installation process to avoid having to manually create it, but in your use-case it makes sense to manually create it.
