### ISSUE TITLE
Show the true count of compared evaluations in evaluation-tile

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#2457]
With PR https://github.com/keptn/keptn/pull/2406 we added this line to the evaluation details tile:

*Compared with last $x passed/... evaluations", whereas $x was taken from the respective SLO.yaml

https://github.com/keptn/keptn/blob/20482b9a6d8d4a17103d05da81f5d528b15fc64c/bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.html#L72

We should improve on that, as the CloudEvent now contains the evaluation-details cloudevent `comparedEvents` as a list, and we can use the length of that list.

**Comment by johannes-b** [comment]
Besides, I saw that the label shows `filter: objectives` when a comparison with multiple evaluation results is configured. 

![image](https://user-images.githubusercontent.com/729071/94893760-3b300c00-0488-11eb-9676-02d42cff0f38.png)
