### ISSUE TITLE
Add status from last event to artifacts list

### ISSUE THREAD

**Issue by neox5** [keptn/keptn#2458]
**Is your feature request related to a problem? Please describe.**
All Evaluation artifacts show "Evaluation started", although all of them are done: 
![evaluation_before](https://user-images.githubusercontent.com/16066812/94840423-b0fc8f00-0418-11eb-86d0-2f9d3c2c707a.png)

**Describe the solution you'd like**
I would be great if the last event status would be displayed in the artifact column like for example:
![evaluation_feature](https://user-images.githubusercontent.com/16066812/94840308-86123b00-0418-11eb-82a5-c31bd7b074c0.png)

Colors for an evaluation with a positive outcome would be great too... otherwise only failed evaluations are marked.
-> Not management friendly 😉
I can write an additional issue if it helps to keep track.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by johannes-b** [comment]
Thanks for proposing this improvement. 
As we are going to implement the new Shipyard format (Shipard v.0.2 see here: https://github.com/keptn/enhancement-proposals/pull/6) this improvement will be taken into consideration.

**Comment by ermin-muratovic** [comment]
Actually the bridge now shows the status of a sequence. If the sequence/task is ongoing, it shows a loading icon and the title says "_Sequence_ started". Once the sequence is finished, it will show the icon and "_Sequence_ succeeded" or "_Sequence_ failed", depending on the result of the sequence.
