### ISSUE TITLE
Makefile: Introduce Git Pre-Commit Hooks for Linting

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#2463]
As a follow-up to https://github.com/keptn/keptn/pull/2418:

Our makefile should introduce a command to install pre-commit hooks for linting code for GoLang and NodeJS, e.g.:

https://github.com/dnephin/pre-commit-golang
https://medium.com/@satya164/improving-nodejs-workflow-with-git-hooks-40996830619f

The pre-commit hooks will be optional, but they should be easy to understand, don't require additional software (except for the linting tools itself).

# Definition of Done

- [ ] Pre-Commit Hooks can be installed using Makefile (e.g., `make install-pre-commit-hooks`) on Windows (e.g., using PowerShell?), MacOS and Linux
- [ ] Pre-Commit Hooks can be uninstalled using Makefile
- [ ] Pre-Commit hooks only try to lint the code of the current commit
- [ ] Installation of linting tools is handled outside of the commit hook, e.g., `make install-golint`

**Comment by andyyaldoo** [comment]
Hi, I'd like to take this. Could you assign the issue to me? Will create PR in the next 72 hours. If no PR by then, feel free to unassign

**Comment by christian-kreuzberger-dtx** [comment]
Thanks! Take your time ;)

**Comment by andyyaldoo** [comment]
@christian-kreuzberger-dtx should I also add a standard `.pre-commit-config.yaml`?

**Comment by christian-kreuzberger-dtx** [comment]
The issue actually asks for a way to use linters etc... within the pre-commit hook, so some sort of `.pre-commit-config.yaml` that satisfies the Definition of Done is required

**Comment by christian-kreuzberger-dtx** [comment]
As there has not been progress on this issue, I'm unassigning it and making it available to everyone again.

**Comment by thisthat** [comment]
We don't have anymore a Makefile. Closing this issue
