### ISSUE TITLE
Makefile: Add a way to build all Dockerfile

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#2464]
As a follow-up to https://github.com/keptn/keptn/pull/2418:

Our makefile should introduce a command to build all Dockerfiles within the repo.

Our Dockerfiles live in sub-directories:

```
./helm-service/Dockerfile
./platform-support/openshift-route-service/Dockerfile
./mongodb-datastore/Dockerfile
./remediation-service/Dockerfile
./lighthouse-service/Dockerfile
./api/Dockerfile
./eventbroker/Dockerfile
./distributor/Dockerfile
./gatekeeper-service/Dockerfile
./shipyard-service/Dockerfile
./bridge/Dockerfile
./shipyard-controller/Dockerfile
./jmeter-service/Dockerfile
./upgrader/upgrade-061-062/Dockerfile
./upgrader/upgrade-062-070/Dockerfile
./upgrader/upgrade-060-061/Dockerfile
./configuration-service/Dockerfile
```

Please apply the following rules:
* Images are named after the parent-directory of the Dockerfile, e.g., when building `./platform-support/openshift-route-service/Dockerfile` the image should be name `${docker-org-name}/openshift-route-service`
  * The exception to that rules are:
    * `bridge` should be named `${docker-org-name}bridge2` (sorry for that, we'll clean that up at some point)
    * anything in the `upgrader` folder should be left out on purpose (it will be removed in the future)
* Images should be tagged using the following command: `git describe --abbrev=1 --tags` (or if you come up with something better, that's fine)

# Definition of Done

- [ ] Introduce a new variable called `DOCKER_ORG_NAME` (or something similar, if that makes more sense) which defaults to `keptn`
- [ ] Introduce a new command to the makefile, e.g., `make build-docker` according to the rules above
- [ ] If any error happens, the script should stop and print the error

**Comment by Amab** [comment]
Hi, I would like to help with this task.
