### ISSUE TITLE
Show key SLI in bold

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#2475]
**Improvement:**
SLIs that are marked as [key_sli](https://github.com/keptn/spec/blob/master/service_level_objective.md#objectives):`true` has to be highlighted by bold in the Heatmap and SLI breakdown.

**Task:**
- Enhance the lighthouse-service to send the information (`key_sli:[true or false]) in the `sh.keptn.events.evaluation-done payload: data.evaluationdetails.indicatorResults[].value` 
- Use the info from the `key_sli` property to set the font to bold in the Heatmap
- Use the info from the `key_sli` property to set the font to bold in the SLI Breakdown

**Definition of Done:**
- [ ] Update of keptn/spec (for additional property key_sli), see here: https://github.com/keptn/spec/blob/master/cloudevents.md#evaluation-done
- [ ] Representation in Keptn Bridge - `repsonse_time_p95` is a key SLI (_Note_: The Heatmap does not show all SLIs as depicted by the SLI breakdown) 
![image](https://user-images.githubusercontent.com/729071/95076244-d12a9780-0711-11eb-96cb-6705f41071ff.png)

**Comment by Godtide** [comment]
I’d like to take up this issue

**Comment by Kirdock** [comment]
Adjusting the style in the heatmap seems not possible.
KeySli for SLI-breakdown is fixed via #2935 
KeySli in cloudevents is fixed via #3340
