### ISSUE TITLE
Add Hacktoberfest label topic to the repository

### ISSUE THREAD

**Issue by andyyaldoo** [keptn/keptn#2477]
New rule was added

https://github.com/digitalocean/hacktoberfest/pull/596

**Comment by christian-kreuzberger-dtx** [comment]
Done for keptn/keptn, keptn/go-utils and keptn/kubernetes-utils

![Screenshot from 2020-10-05 18-37-29](https://user-images.githubusercontent.com/56065213/95107211-e61b2100-0739-11eb-8c7c-da6214085da4.png)

I'll assign the issue to @jetzlstorfer to verify that everything is compliant.

**Comment by jetzlstorfer** [comment]
looks good! thank you!

**Comment by christian-kreuzberger-dtx** [comment]
Alright, thanks.
