### ISSUE TITLE
SLI breakdown in table

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#2478]
**Status quo**
The SLI breakdown of a quality gate result is shown as a list. Each entry of this list has the SLI name on the left and the value/criteria on the right. Criteria that are not met are strikethrough with a font color in red:
![image](https://user-images.githubusercontent.com/729071/95090447-96caf580-0725-11eb-89ce-c6d3667c9c59.png)

**Improvement:** 
Change this list to a table that allows sorting for the different columns. The columns should be: 

- Name
- Value
- pass Criteria
- warning Criteria
- Result 
- Score (default column for sorting) 

**Tasks**
- Get familiar with the table component from: https://barista.dynatrace.com/components/table
- Show SLIs in a table
- If the objective of an SLI resulted in a warning, show the score in orange; if failed --> red.
- By default sort the table based on the score
 
**Definition of Done**
![image](https://user-images.githubusercontent.com/729071/95090592-bc57ff00-0725-11eb-843a-295ce219063b.png)

**Comment by pahofmann** [comment]
I'd like to work on this.

**Comment by johannes-b** [comment]
Hi @pahofmann, this would be really great if you can work on that issue! Thanks! 👍 
I assigned it to you.

If you have a first preview of the table you would like to discuss, please ping me or @ermin-muratovic.

**Comment by pahofmann** [comment]
I finally had time to start working on this and have a first version with the table:
![image](https://user-images.githubusercontent.com/5699104/98277792-0b4cba80-1f98-11eb-822d-85f711684b7b.png)

However I ran into a problem with the criteria. In the mock-up it's separated by pass and warning.
We do have that information in the SLO file, but not in the targets that a returned for display in the SLI table.

```javascript
0:
  name: "response_time_p90"
  score: 0.5
  status: "warning"
  targets: Array(3)
    0: {criteria: "<=5000", targetValue: 5000, violated: false}
    1: {criteria: "<3000", targetValue: 3000, violated: true}
    2: {criteria: "<=+200%", targetValue: 1448.7341558353953, violated: true}
  value: 4210 
```

Without that information we couldn't tell if the third (relative) criteria is a warning or pass criteria in the example above .

Would it be feasible to add the information if the criteria is pass/warning to the target?

**Comment by johannes-b** [comment]
Hi @pahofmann
wow, that looks already great!

I see your problem and like your idea of differentiating between a pass or a warning target. I spotted the line of code where this needs to be addressed: https://github.com/keptn/keptn/blob/master/lighthouse-service/event_handler/evaluate_sli_handler.go#L208
There, already two separate lists one for `passTarget` and the other for `warningTarget` are maintained. 

Would you like to extend the `keptnv2.SLITarget` struct with a property that holds `pass`, or `warning`?

**Comment by pahofmann** [comment]
Thanks for pointing out the correct part, I'll add a property (maybe _objectiveType_ ?).  
Should I also make a PR to add it in the [spec for the evaluation done event](https://github.com/keptn/spec/blob/master/cloudevents.md#evaluation-done)  once it's finished?

**Comment by johannes-b** [comment]
I would prefer to name it `criteriaType` or `criteriaCategory` since the entity that is in focus is the `criteria`. 

Example with `criteriaType`: 

```
"targets":[
{
  "criteria":"<=800",
  "targetValue":800,
  "violated":true,
  "criteriaType": "pass"
},
{
  "criteria":"<=+10%",
  "targetValue":549.1967956487127,
  "violated":true
  "criteriaType": "warning"
}
]
```

What do you think, @pahofmann ?


Would be great if you can also file a PR for the CloudEvent in the keptn/spec.

**Comment by pahofmann** [comment]
Sounds good, will use `criteriaType` then, and also file the PR for the spec.

**Comment by johannes-b** [comment]
Hi @pahofmann, 
I just want to ask you about your status on the issue? If you need help, please let us know.

**Comment by neox5** [comment]
I think the most important informations in this table would be
* value
* result
* Score

as @pahofmann showed in his preview and in addition:
* criteria
* targetValue

Everything else, for example called "details", I would show on hovering or click in a
simple modal as mentioned in #2757.

Otherwise it would be too cluttered, especially when you have multiple pass or warning criterias.

If something fails you want to know which critiria was violated or in a positive case which critiria passed, all others I think are irrelevant for that moment.

Any thoughts from your point of view?

**Comment by pahofmann** [comment]
Hi @johannes-b,
I haven't found time the last weeks, but will so starting next week. 
I ran into an issue with testing the modified lighthouse service. The field added to the cloud event is not there yet, so I can't test it properly. How can I test my lighthouse service with the changes from https://github.com/keptn/spec/pull/48

**Comment by johannes-b** [comment]
Hi @pahofmann, 
as we have released a Keptn 0.8.0-alpha, which is used for testing the UX of new features, it would be great to see your enhancement too. :) 

I know that you are working on the issue to get the `criteria` into the table. If you want, we should try to merge your current status and then define a follow-up issue for the `criteria` columns. Would this work for you?

**Comment by pahofmann** [comment]
Hey @johannes-b,
yes that would be fine. 
have some issues getting my lokal setup working again, hope to fix it this week. Once I can properly test the actual changes for the criteria shouldn't take long.

**Comment by Kirdock** [comment]
At the moment it is not possible to split criteria into warning and pass, because of a missing indicator.
Information provided are just
`criteria` (e.g. "<600")
`targetValue` (e.g. 600)
`violated` (`true` or `false`)

Correct me if I am wrong

**Comment by johannes-b** [comment]
Hi @Kirdock, 
you are right; this is not possible at the moment. Please focus on the other aspects of this issue first and let's have a meeting next week to discuss the required changes.

**Comment by johannes-b** [comment]
To address the above-mentioned problem, we should add the properties `passTargets` and `warningTargets` to the struct of an SLIEvaluationResult: https://github.com/keptn/go-utils/blob/master/pkg/lib/v0_2_0/evaluation.go#L63

In the lighthouse-service, don`t merge the *targets* but rather separate them here: https://github.com/keptn/keptn/blob/master/lighthouse-service/event_handler/evaluate_sli_handler.go#L243
