### ISSUE TITLE
No info or timeout while installing if there aren't renough resources available

### ISSUE THREAD

**Issue by cwtrsld** [keptn/keptn#2485]
**Environment**
- Client OS (e.g., Linux, OSX, Windows): WSL2, Ubuntu 20.04.1 LTS
- Keptn Version (```keptn version```): 0.7.1
- Kubernetes Cloud Provider (e.g., GKE, AKS): Azure Kubernetes Service, v1.16.13
- Kubernetes version (```kubectl version```): v1.19.2

**Affected Component**
- [ ] Docs
- [x] CLI
- [x] Kubernetes Integration
- [ ] Openshift Integration
- [ ] Helm
- [ ] Istio
- [ ] Bridge
- [ ] Gatekeeper
- [ ] Datastore
- [ ] REST API
- [ ] eventbroker / distributor
- [ ] jmeter

**Describe the bug**
If the (aks) cluster hasn't enough resources and you try to install keptn at some point the installation is stuck and nothing happens. The deployed pods are in a pending state and nothing happens anymore.

**Expected behavior**
Error message with information about a timeout or a long lasting pending state.

**Current behavior**
Stuck in message "Start upgrading Helm Chart keptn in namespace keptn message"

**Screenshots**
/

**Additional context**
I started the installation of keptn not knowing that there is only one node with small sizing present in the cluster. It was my fault but because of the missing timeout/info i've waited for some time.

**Comment by cwtrsld** [comment]
The troubleshooting page (https://keptn.sh/docs/0.7.x/troubleshooting/) mentions this problem for EKS.

**Comment by christian-kreuzberger-dtx** [comment]
Thanks for bringing this up.

I'm not sure if we can improve the installation procedure in this use-case, as we are relying on helm to return a value, but maybe we can configure a timeout for this.

For anyone wanting to take a look at this, the relevant lines of codes are here:
https://github.com/keptn/keptn/blob/40399ec765dff258b4946e59257b0bcfce6bbf39/cli/cmd/install.go#L230-L236
and
https://github.com/keptn/keptn/blob/40399ec765dff258b4946e59257b0bcfce6bbf39/cli/pkg/helm/helm_helper.go#L133-L181

**Comment by Godtide** [comment]
I’d like to take this issue

**Comment by Godtide** [comment]
[timeout](https://github.com/Godtide/keptn/tree/feature/2485/timeout)

**Comment by christian-kreuzberger-dtx** [comment]
As there was no progress in the PR, I'll remove the current assignee and the issue is available again for contributors!

**Comment by christian-kreuzberger-dtx** [comment]
AFAIK this was fixed in 0.8.0, I'll leave this issue closed.
