### ISSUE TITLE
Address the GitHub branch renaming from `master` to `main`

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#2487]
**Problem:**
As announced by GitHub, the `master` branch will be renamed to `main` for new GitHub repositories. However, the configuration-service still has hard-coded dependencies to the repo-name `master`. See: https://github.com/github/renaming

Users might run into the following error when creating a project:
```console
$ keptn create project sockshop --shipyard=./shipyard.yaml --git-user=$GIT_USER --git-token=$GIT_TOKEN --git-remote-url=$GIT_REMOTE_URL
Starting to create project
ID of Keptn context: 1-2-3-4
Project sockshop created
Failed to create stage dev: Could not create stage.
```

Logs of configuration-service show the following output:
```
"timestamp":"2020-10-06T17:15:39.953110713Z","logLevel":"ERROR","message":"Could not create dev branch for project sockshop"}
{"timestamp":"2020-10-06T17:15:39.953132649Z","logLevel":"ERROR","message":"Error executing command git checkout master: exit status 1\nerror: path
spec 'master' did not match any file(s) known to git\n"}
```

**Fix:**
- Change the implementation of the configuration-service to support both names: `master` and `main`

**Comment by christian-kreuzberger-dtx** [comment]
Oh great... I wonder if any other projects that follow a GitOps approach are affected by this :D

> Change the implementation of the configuration-service to support both names: master and main

I see the following options:

* Create a `master` branch if it does not exist
* Check if `master` exists, if not, fallback to `main`, if this does not exist, error out

**Comment by checkelmann** [comment]
> Oh great... I wonder if any other projects that follow a GitOps approach are affected by this :D
> 
> > Change the implementation of the configuration-service to support both names: master and main
> 
> I see the following options:
> 
> * Create a `master` branch if it does not exist
> * Check if `master` exists, if not, fallback to `main`, if this does not exist, error out

Another option would be checking the default branch name with
`git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@'
master` (StackOverflow :D )

But I don't know how "reliable" this would be.

**Comment by christian-kreuzberger-dtx** [comment]
Thanks @checkelmann . I think fetching the default branch name would be a good idea. Source: https://stackoverflow.com/questions/28666357/git-how-to-get-default-branch
