### ISSUE TITLE
Automated Upscaling with Dynatrace is not happening with GKE

### ISSUE THREAD

**Issue by JebasinghLuccas** [keptn/keptn#2495]
**Environment**

* Client OS (e.g., Linux, OSX, Windows):  Windows
* Keptn Version (`keptn version`): 0.7.0
* Kubernetes Cloud Provider (e.g., GKE, AKS): GKE
* Kubernetes version (`kubectl version`): 
**Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.401", GitCommit:"eb94c181eea5290e9da1238db02cfef263542f5f", GitTreeState:"clean", BuildDate:"2020-09-09T00:57:35Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}**

I am setting up Automated Upscaling with Dynatrace(https://tutorials.keptn.sh/tutorials/keptn-upscaling-dynatrace-07/index.html?index=..%2F..index#20). Everything went well till the step 21. Watch self-healing in action.

**Observation :** Dynatrace created the problem "response time degradation" and even after 50 minutes it is not creating the problem open event in the sockshop keptn project.  I did configure the step 19 "Configure your dynatrace tenant" as explained. 
Infact all the Pods are running without any issue

```console
D:\workspace\gcp\examples\load-generation\cartsloadgen\deploy>**kubectl get pods -n keptn**
NAME                                                              READY   STATUS    RESTARTS   AGE
api-gateway-nginx-5b865b66b8-5sztx                                1/1     Running   0          5h42m
api-service-6d86cb4f88-vwd6h                                      1/1     Running   0          5h42m
bridge-6594f6b8c-m2w4n                                            1/1     Running   0          5h42m
configuration-service-66f59c65f9-4sllg                            2/2     Running   2          5h42m
dynatrace-service-f8bd7ff8d-d42np                                 2/2     Running   0          90m
dynatrace-sli-service-699d6559bb-zl2mc                            1/1     Running   0          60m
dynatrace-sli-service-monitoring-configure-distributor-6fftftn5   1/1     Running   0          60m
eventbroker-go-5674d9646d-xdbdx                                   1/1     Running   0          5h42m
gatekeeper-service-c6f9f75cc-j2fmr                                2/2     Running   2          5h42m
helm-service-85f8bf5fd6-vm52s                                     2/2     Running   2          5h42m
helm-service-continuous-deployment-distributor-55fc6bb66-8gmt4    1/1     Running   2          5h42m
jmeter-service-644c7f9468-v9wdp                                   2/2     Running   2          5h42m
keptn-nats-cluster-0                                              3/3     Running   0          5h42m
lighthouse-service-6d4b5dcd9-4789v                                2/2     Running   2          5h42m
mongodb-7b6957fb57-5jttx                                          1/1     Running   0          5h42m
mongodb-datastore-647b5bc584-tmgs4                                2/2     Running   2          5h42m
remediation-service-cf4b7b97f-bzxv5                               2/2     Running   2          5h42m
shipyard-service-5c98f89f4c-lvzv2                                 2/2     Running   2          5h42m

D:\workspace\gcp\examples\load-generation\cartsloadgen\deploy>**kubectl get pods -n dynatrace**
NAME                                           READY   STATUS    RESTARTS   AGE
dynatrace-oneagent-operator-55cfcdcb5d-d4xk5   1/1     Running   0          97m
dynatrace-oneagent-webhook-6dbb9ccc85-w6mdl    2/2     Running   0          97m
oneagent-lwd7k                                 1/1     Running   0          96m
```

How do i debug this?  Please suggest.

**Comment by christian-kreuzberger-dtx** [comment]
If you don't see the problem / response time degradation in Keptn Bridge, I guess that the Problem Notification configured for Dynatrace is not working as expected.

On your Dynatrace Tenant, can you navigate to Settings, Integration, Problem notification, and double check that a *Keptn Problem Notification* has been created with the correct URL to the API?
You can also "Send test notification" to see if the API URL is reachable (this will not appear in Bridge, though) .
