### ISSUE TITLE
View carts service is not browsable

### ISSUE THREAD

**Issue by JebasinghLuccas** [keptn/keptn#2496]
Environment

Client OS (e.g., Linux, OSX, Windows): **Windows**
Keptn Version (keptn version): **0.7.0**
Kubernetes Cloud Provider (e.g., GKE, AKS): **GKE**
Kubernetes version (kubectl version):
**Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.401", GitCommit:"eb94c181eea5290e9da1238db02cfef263542f5f", GitTreeState:"clean", BuildDate:"2020-09-09T00:57:35Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}**

I am setting up Automated Upscaling with Dynatrace(https://tutorials.keptn.sh/tutorials/keptn-upscaling-dynatrace-07/index.html?index=..%2F..index#20).  The URL provided in this step 15. View carts service is not able to browse. i tried in both IE & chorme. Any specific setting should be followed in local machine or cluster level? please suggest.

**Comment by christian-kreuzberger-dtx** [comment]
The URLs displayed in Step 15 heavily depend on the settings done in step 6, where you configure the istio ingress gateway.

Can you show us the URL that has been generated in Step 15 (feel free to replace any sensitive IP addresses or hostnames in that URL with something similar). Also, please compare the output of the following commands (note: the external IP of istio-ingressgateway should match with the URLs you use for the deployed services):

```
$ kubectl get services -n istio-system
AME                   TYPE           CLUSTER-IP    EXTERNAL-IP    PORT(S)                                                                      AGE
istio-ingressgateway   LoadBalancer   10.0.84.37   12.34.56.78   15021:30833/TCP,80:32168/TCP,443:32385/TCP,31400:32121/TCP,15443:30626/TCP   30d

```


```
$ kubectl -n keptn get configmaps ingress-config -oyaml
apiVersion: v1
data:
  ingress_hostname_suffix: 12.34.56.78.nip.io
  ingress_port: "80"
  ingress_protocol: http
  istio_gateway: public-gateway.istio-system
kind: ConfigMap

```
