### ISSUE TITLE
Smooth installation of keptn

### ISSUE THREAD

**Issue by dirkwall** [keptn/keptn#250]
Installation of keptn follows the keptn walkthrough

**Comment by johannes-b** [comment]
- [ ] consider managed environments (see: #255 )

**Comment by robertjahn** [comment]
Please simply the steps needed for "keptn auth".  If it can automatically get the keptn token and endpoint this saves a step for the user to not look them up and pass them in.

From https://keptn.sh/docs/0.2.0/reference/cli/ 
![image](https://user-images.githubusercontent.com/24907089/57003364-2e70ff80-6b94-11e9-99c4-0c61155840d5.png)
