### ISSUE TITLE
Keptn CLI: commands are taking too long to return when no connection to a cluster can be established 

### ISSUE THREAD

**Issue by warber** [keptn/keptn#2505]
`keptn` cli commands are hanging for approx. 30 seconds in case the target cluster is not reachable.

```
$ ./keptn version

Keptn CLI version: develop
Keptn cluster version: Error occurred with response code 0 with message Get http://172.31.118.52:31090/api/v1/metadata: dial tcp 172.31.118.52:31090: i/o timeout
```

This also affects commands containing the `--help` flag.

The cli shall return and fail early, and connections to the cluster shall only be established as soon as it is necessary.

**Affected Component**

*  CLI

**To Reproduce**
Given an already configured keptn environment.
Change the target cluster IP address in `.keptn` config file to something not reachable.
Execute a keptn command (e.g.: `keptn --help`) and observer that the command only returns after approx. 30 seconds

**Expected behavior**
Commands that do not require a connection to the cluster may return immediately.
Fail as early as possible for other commands.

**Comment by christian-kreuzberger-dtx** [comment]
This happened after merging #2419 (Print Keptn API version). Right now this is handled in the root command of the CLI: 
https://github.com/keptn/keptn/blob/05c86f6f887c5325c590524fea1a5d9597fd2efb/cli/cmd/root.go#L112-L136

I think to fix this, we should

a) not run the version check for the cluster connection in the root command at all (only when executing `keptn version`), and
b) introduce a timeout of 5 seconds (or so) for the HTTP connection checks.

**Comment by pedroandrade** [comment]
HI @christian-kreuzberger-dtx, I'd like to pick this one, could you assign to me?

**Comment by christian-kreuzberger-dtx** [comment]
Thanks! also paging @warber on this

**Comment by agrimmer** [comment]
In order to get a daily version check, I think running this check in the root command is fine.
