### ISSUE TITLE
Create integration test that tests the Git upstream functionality for create and update project

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#2509]
As a follow-up for #2493 we need an integration test that tries to

* create a project with upstream to GitHub (and maybe even other providers such as GitLab, Bitbucket?)
  * with existing branches and files
  * without any existing branches
* update a project (both, without having an upstream configured previously, and with having it configured previously)

I don't think we need to have a full test with onboard service etc..., just `keptn create project` should be sufficient.

**Comment by christian-kreuzberger-dtx** [comment]
Looking at PR https://github.com/keptn/keptn/pull/2888, we should also create an integration test for `keptn update project`. I've added it to the issue description above.

**Comment by christian-kreuzberger-dtx** [comment]
Next issue that could have been detected earlier with a proper integration test: https://github.com/keptn/keptn/issues/3334

**Comment by thisthat** [comment]
This issue can be closed since at each integration test run, we create projects using gitea.
