### ISSUE TITLE
Keptn CLI: using create project with --shipyard pointing to an URL does not properly work

### ISSUE THREAD

**Issue by warber** [keptn/keptn#2511]
With PR #1648 the `--shipyard` flag was enhanced to make the distinction between a file path and a URL pointing to s shipyard file. However, when passing in a URL, the cli still tries to read the shipyard file from disk.

**Affected Component**

* [ ] CLI

`keptn create project <projectname> --shipyard=https://url.com/path/to/shipyard.yaml`

**Expected behavior**
The shipyard.yaml is downloaded from the location given by the `--shipyard` flag and used throughout the further proccess.

**Current behavior**
The cli tries to load the file from disk and fails

**Comment by ankitjain28may** [comment]
Hi @warber Thanks for bringing this up. I cross-checked, it just silently fails without throwing any error. It would be great if you can attach more information like the logs and the keptn cli version.
