### ISSUE TITLE
Move helm charts away from Google Cloud, to github.io

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#2532]
Right now our helm charts are published at https://storage.googleapis.com/keptn-installer, which is in accordance to what the [Helm Docs](https://helm.sh/docs/topics/chart_repository/) state (it's actually the first option that they list).

We automated the process of building and uploading to google cloud in
* https://github.com/keptn/keptn/blob/master/travis-scripts/build_latest_installer.sh
* https://github.com/keptn/keptn/blob/master/travis-scripts/build_release_installer.sh

This is suboptimal for several reasons:

1. It's completely intransparent for the maintainers and end-users (as in: who uploaded the helm chart, when, etc...).
2. If the Google Cloud owner ever forgets to pay the bill, the repo is gone, and all `keptn install` commands will fail. Even worse, someone else could register the same storage space and upload something else (e.g., viruses, ...)
3. It's an external dependency that's not in our control
4. Last but not least: It costs money - it might be cheap, but it certainly can be done for free.

I propose to move away from google cloud for storing the helm charts for Keptn. One good alternative would be to host them on a website (e.g., keptn.sh, or even keptn.github.io). See [Tutorial for GitHub Pages on Helm Docs](https://helm.sh/docs/topics/chart_repository/#github-pages-example) for details.

In the end, this is what it should feel like for the user:
```
helm repo add keptn https://keptn.github.io/helm-charts/
helm install keptn/keptn --version 0.7.2
```

# Examples

* [Dynatrace Oneagent](https://www.dynatrace.com/support/help/technology-support/cloud-platforms/kubernetes/deploy-oneagent-k8/?deploy-with-kubectl%3C-%3Edeploy-with-helm=deploy-with-helm) via Helm Chart
![Screenshot from 2020-10-13 15-33-15](https://user-images.githubusercontent.com/56065213/95867467-77f1e200-0d69-11eb-8c26-b88a4e600b00.png)

* Istio via [Helm Chart](https://istio.io/v1.5/docs/setup/install/helm/#helm-chart-release-repositories)
![Screenshot from 2020-10-13 15-39-32](https://user-images.githubusercontent.com/56065213/95868245-51807680-0d6a-11eb-878d-0e6bb4730c4b.png)

# Definition of Done

- [ ] Create a dedicated space (e.g., a git repo) where the helm charts are stored in
- [ ] Put in the existing helm charts (0.7.0, 0.7.1, 0.7.2)
- [ ] Adapt the aforementioned travis-scripts to upload the charts to the new chart repository
- [ ] Adapt the docs and tutorials for installing keptn using helm upgrade/install
- [ ] Adapt the CLI `keptn install` command

**Comment by johannes-b** [comment]
Would it make sense to use the [get.keptn.sh](https://github.com/keptn/get.keptn.sh) repo?

**Comment by christian-kreuzberger-dtx** [comment]
I like the idea, the repo could be "https://get.keptn.sh/helm-charts/".

However, get.keptn.sh is currently synced to AWS S3, so we kind of just move the problem.

Maybe we need another issue before we do this one:

* move get.keptn.sh from AWS S3 to GitHub Pages
