### ISSUE TITLE
Shell completion for Keptn CLI using Cobra

### ISSUE THREAD

**Issue by warber** [keptn/keptn#2539]
Currently, the keptn CLI does not support shell auto completion for all its commands.

The Cobra library used by keptn cli supports this feature quite neatly: 

https://github.com/spf13/cobra/blob/master/shell_completions.md
https://github.com/spf13/cobra/blob/master/bash_completions.md

Having shell auto completion available would have a positive effect on the usability of the  keptn cli tool.

**Comment by tripathyprateek** [comment]
Hi  @christian-kreuzberger-dtx can I work on this issue. I am getting used to Cobra and this might take some time on my end.

**Comment by christian-kreuzberger-dtx** [comment]
Sure :)

**Comment by DarthBenro008** [comment]
Hey @christian-kreuzberger-dtx @tripathyprateek, is this issue still bring worked on or is a work in progress? If not, I would like to work on it !

**Comment by christian-kreuzberger-dtx** [comment]
@tripathyprateek hasn't said anything, so I'll re-assign it to you!
