### ISSUE TITLE
Keptn Bridge ignores deployed service artifact 

### ISSUE THREAD

**Issue by gabrielprioli** [keptn/keptn#2543]
**Environment**

* Client OS (e.g., Linux, OSX, Windows): Windows
* Keptn Version (`keptn version`): Keptn version: 0.7.1
* Kubernetes Cloud Provider (e.g., GKE, AKS): AKS
* Kubernetes version (`kubectl version`): 
  - Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
  - Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.10", GitCommit:"afea77eefe3272c0f53c4552183ecb16c091db41", GitTreeState:"clean", BuildDate:"2020-09-17T06:32:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**Affected Component**

* [x] Bridge

**Describe the bug**

**To Reproduce**

1. Onboard a new service
1. Send new artifact
1. Send 20+ events
1. Open the bridge
1. Verify that the Bridge will stop recognizing that the service was deployed with the message
_Service not deployed yet. Use keptn send event new-artifact to trigger a deployment._

**Expected behavior**

Keptn Bridge should show the message "Last processed artifact: ..."

**Screenshots**

![image](https://user-images.githubusercontent.com/836297/96007146-97921480-0e14-11eb-9ff1-31199c4eae97.png)

**Current behavior**

Keptn Bridge shows the message "Service not deployed yet. Use keptn send event new-artifact to trigger a deployment."

**Screenshots**

![image](https://user-images.githubusercontent.com/836297/96007318-c0b2a500-0e14-11eb-91e0-d5435bb53d17.png)

**Additional context**

Spotted while on a meeting with @johannes-b and @jetzlstorfer and they suspect it has to do with how many events the bridge looks back in the past to find a deployment change event.

**Comment by christian-kreuzberger-dtx** [comment]
@johannes-b please add to known issues in release-notes.
