### ISSUE TITLE
Misleading/incorrect information for quality gate only projects

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#2544]
Hi

I am testing the latest Keptn bridge 0.7.2 and have one project that I only use for Test Execution & Quality Gates - so - I am not using it for delivery.
As you can see from the screenshot the information is rather misleading and actually incorrect as this project has and will never see a deployment - yet - the message tells me that I should do a deployment. We should fix this by detecting whether a project is only used for e.g: quality gates or testing as a service and then show relevant information for those use cases

Here is what I see - it shows me no deployment and a final score of 0
![image](https://user-images.githubusercontent.com/675886/96085272-df6e7580-0ec0-11eb-8477-2856677a362f.png)

And here is the view in my services view where I can see my latest test executions and quality gates
![image](https://user-images.githubusercontent.com/675886/96085379-088f0600-0ec1-11eb-8061-7cc926e4726b.png)

The initial event that I am sending is actually a deployment event as you can see here:
![image](https://user-images.githubusercontent.com/675886/96085435-18a6e580-0ec1-11eb-89fa-fc5f4b204486.png)

And here is the event content:
```json
{
  "contenttype": "application/json",
  "data": {
    "deploymentURIPublic": "http://simplenode.keptn07project-staging.keptn07-agrabner.demo.keptn.sh/",
    "eventContext": null,
    "image": "Keptn Performance as a Service",
    "labels": {
      "buildId": "47",
      "jobname": "Keptn Performance as a Service",
      "joburl": "https://angr-jenkins.apps.lab.dynatrace.org/job/Keptn%20Performance%20as%20a%20Service/47/"
    },
    "project": "perfaasproject",
    "service": "perfaasservice",
    "stage": "performance",
    "tag": "47",
    "teststrategy": "performance"
  },
  "id": "79000c5f-575f-4537-b0ec-2d32598fbe05",
  "source": "jenkins-library",
  "specversion": "0.2",
  "time": "2020-10-14T14:18:57.857Z",
  "type": "sh.keptn.events.deployment-finished",
  "shkeptncontext": "4d90f1f3-284e-4b18-a6d7-9437f93a83ce"
}
```

Would be great if we could improve the environment screen

**Comment by johannes-b** [comment]
This issue is partly implemented by 0.8.x, but a final adjustment will happen with: https://github.com/keptn/keptn/issues/4172
