### ISSUE TITLE
"Compared with ..." info in evaluation tile shows wrong information

### ISSUE THREAD

**Issue by ermin-muratovic** [keptn/keptn#2545]
* Keptn Version (`keptn version`): 0.7.2

**Affected Component**
* [ ] Docs
* [ ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [x] Bridge
* [ ] Gatekeeper
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**
The evaluation tile shows the message "Compared with last evaluation", although `include_result_with_score` in the SLO file is set to `pass`.

**Expected behavior**
The info message should be "Compared with last passed evaluation".

**Current behavior**
The message "Compared with last passed evaluation" is showing up correctly if the value for `include_result_with_score` is set under quotation marks. But if the quotation marks are missing, that information is not parsed correctly.

**Screenshots**
![image (4)](https://user-images.githubusercontent.com/6098219/96127756-c8497b00-0ef4-11eb-8bb3-8cc028080cda.png)
![image (2)](https://user-images.githubusercontent.com/6098219/96127797-caabd500-0ef4-11eb-9c6c-8414badee0fa.png)

**Comment by anusha5695** [comment]
Hello @christian-kreuzberger-dtx I can pick this
