### ISSUE TITLE
Chart Tooltip should show all active metrics

### ISSUE THREAD

**Issue by ermin-muratovic** [keptn/keptn#2546]
The tooltip in the Chart currently shows only the Score value. It should also include all other active metrics (SLIs) and there values of the hovered element.

The current situation can be seen in the screenshot below. `Score`, `throughput_sc` and `response_time_p95` are active, but only the Score is showing in the tooltip.

![image (3)](https://user-images.githubusercontent.com/6098219/96128354-85d46e00-0ef5-11eb-8431-3b57092827f2.png)

**Comment by johannes-b** [comment]
I figured out that the first selected element determines what is shown in the toolbox. For example, I have `response_time` and `Score` and get the value of the `response_time`: 

![image](https://user-images.githubusercontent.com/729071/112846815-bde7fb80-90a6-11eb-8f8c-33ed694ab346.png)
