### ISSUE TITLE
Support for Dynatrace Managed in 0.2

### ISSUE THREAD

**Issue by dirkwall** [keptn/keptn#255]
- [x] check pitometer-service
- [x] check servicenow-service
- [x] update the Jenkins pipelines (deploy, evaluation_done, run_test) when checking the DT_TENANT_URL (obsolete when #268 is done and pipelines don't send DT events any more)
- [x] update [keptn/docs](https://keptn.sh/docs/0.2.1/monitoring/dynatrace/)
   - [x] Setup Dynatrace
   - [x] Runbook Automation 
      - DT_TENANT_ID -> DT_TENANT
      - production --> sockshop.production

**Check list for testing changes**
- [x] setup on fresh cluster
- [x] new version of services (pitometer: pitometer-service:2c22eea, servicenow: servicenow-service:ae78417, github: github-54c6208) 
- [x] pipelines in jenkins-service (*/feature/255/managed-support, */develop)
- [x] DT_TENANT_URL in Jenkins
- [x] onboard service completed
- [x] quality gates use case completed
- [x] self-healing use case completed

**Comment by johannes-b** [comment]
Make sure to update the Jenkins pipelines (deploy, evaluation_done, run_test) when checking the DT_TENANT_URL.
