### ISSUE TITLE
Adapt CLI command “send event new-artifact” to CloudEvents spec of 0.8.0

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#2558]
https://github.com/keptn/spec/blob/ca6fdc22d2a8ba865c9f883b3d101207b6d7c3dc/shipyard.md#example-of-a-shipyard-in-yaml

The helm-service can handle configuration-changes in the values.yaml of a Helm chart. Therefore, the helm-service expects a configuration-change in the following format:

```
"data": {
    "project": "sockshop",
    "stage": "dev",
    "service": "carts",
    "labels": {
      "testId": "4711",
      "buildId": "build-17",
      "owner": "JohnDoe"
    },
    "status": "succeeded",
    "result": "pass",

    "configurationChange": {
      "values": {
        "image": "docker.io/keptnexamples/carts:0.11.2"
      }
    },
    "deployment": {
      "deploymentstrategy": "blue_green_service"
    }
  }
```

**Tasks:**
- [ ] Introduce a domain/root event for the configuration-change, which contains an object `configurationChange` specifying Helm values
- [ ] Adapt the CLI command “send event new-artifact” to send a configuration-change domain/root event, which eventually allows triggering a delivery sequence

**Comment by agrimmer** [comment]
With https://github.com/keptn/keptn/issues/2557, different delivery strategies (e.g. direct or blue-green) for services within the same project are now modeled as dedicated delivery sequences in the shipyard file. 
Therefore, we need a mapping between the `keptn send event new-artifact` command and the name of the domain (root) event. 
One option would be to introduce a new flag `--sequence`, which allows specifying the to be executed sequence.
