### ISSUE TITLE
Distributor: Having a subscription topic does not have to be a requirement

### ISSUE THREAD

**Issue by bacherfl** [keptn/keptn#2562]
In previous versions (<0.8.x), the distributor's only responsibility was to receive events for a certain topic (defined by the env var `PUBSUB_TOPIC` and forward them to the recipient defined in the env var `PUBSUB_RECIPIENT`. Due to the changes made in #2220, the distributor now also allows services to forward events to the NATS Server/Keptn API, so the services do not have to send their events directly to the event broker (which has been removed in #2220).
Therefore, a `PUBSUB_TOPIC` does not necessarily has to be defined anymore when using the distributor as a sidecar for a service. E.g., when a service only needs the distributor to send events to the NATS Server/Keptn API, but does not need to subscribe to a topic - this will be the case for the api-service.
However, the distributor currently still requires a `PUBSUB_TOPIC` to be set, or otherwise it will shut down immediately. The implementation needs to be adapted so that it is also possible to use the distributor only as a forwarder for sending events to the NATS Server/Keptn API, in addition to subscribing to topics.

**Suggested Solution:** 

Currently, the listener for incoming CloudEvents for a certain topic coming from NATS, or the Keptn API is started in the `main` routine, while the HTTP endpoint for listening for events coming from the service using the distributor is started in a goroutine. This should be changed so that both listeners are started in separate goroutines as part of a `sync.WaitGroup`. This way, when the `main` routine waits for both listeners to finish, using the `Wait()` func of the `WaitingGroup`, the completion/termination of one listener does not cause the service to shut down.

**Definition of done**

- [ ] It's possible for services to use the distributor for sending events, without having to subscribe to a topic
- [ ] Subscribing to topics and using the distributor to send events can be used simultaneously 
- [ ] Re-add distributor to api-service, as api-service needs to be able to send events

**Comment by Godtide** [comment]
I’d like to take this issue

**Comment by johannes-b** [comment]
Hi @Godtide, 
great and thanks for taking it. I assigned it to you.
