### ISSUE TITLE
Extend keptn send event with deployment finished event

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#2566]
As of Keptn 0.7.2 the Keptn CLI provides a great and easy way to send specific events to trigger the following use cases via the CLI: new-artifact, start-evaluation, approval.finished

The use case "Performance as a Self-Service" requries a user to send a deployment finished event which is currently only possible by creating an event.json file and then use keptn send event --file=event.json

I suggest to extend keptn send event to include the option for deployment-finished. Here is my proposal on how such a call should look like:
```console
keptn send event deployment-finished --project=MYPROJECT --service=MYSERVICE --stage=MYSTAGE --deploymentUri=http://myapp --testStrategy=performance --image=myapp --version=1.1
```

This should send a deployment finished event and using the passed values to fill the cloud events manadatory fields. This enables a user to use keptn and start triggering the workflow when an external tool, e.g: Jenkins has deployed an app in a particular version. In a default Keptn installation with testing tool support enabled the above mentioned keptn CLI command would then trigger test execution followed by a quality gate evaluation

**Comment by christian-kreuzberger-dtx** [comment]
In general I think it would be good to be able to send all cloud-events via the CLI without having to specify a file (`keptn send event -f ...`). As we are changing all our cloud-events with 0.8.x I have removed the *good first issue* label, and I'll refine the issue once we have our new cloud-events for 0.8.x ready.

Also paging @johannes-b on this.

**Comment by christian-kreuzberger-dtx** [comment]
Reopening this and putting it on the agenda for 0.8
