### ISSUE TITLE
Re-add the version check into the root command

### ISSUE THREAD

**Issue by bacherfl** [keptn/keptn#2571]
In PR #2540 , the version check has been removed from the root command since it prevented commands that do not require a connection to the cluster the stall when no connection to the cluster could be established. The version check should be included again. However, commands that do not require a cluster connection should still work even if a connection to the cluster cannot be established.
In addition, commands like `keptn ... --help` should not run any version check at all. 

edit:  As mentioned in #2590, we also need to add a check if CLI version == API version, and print a warning if it doesn't.

**Comment by christian-kreuzberger-dtx** [comment]
@johannes-b As mentioned in #2590, should we add a check if CLI version == API version, and print a warning if it doesn't?

**Comment by johannes-b** [comment]
Yes, let's go this way.
