### ISSUE TITLE
keptn cli on windows - Wrong command for keptn auth command

### ISSUE THREAD

**Issue by checkelmann** [keptn/keptn#2576]
**Environment**

* Client OS (e.g., Linux, OSX, Windows): Windows
* Keptn Version (`keptn version`): 0.7.2
* Kubernetes Cloud Provider (e.g., GKE, AKS):  KinD
* Kubernetes version (`kubectl version`): 1.18

**Affected Component**

* [ ] Docs
* [X] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [ ] Bridge
* [ ] Gatekeeper
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**

After installing keptn using the keptn cli on windows, a quick access guide is printed out.
```
keptn install
Helm Chart used for Keptn installation: https://storage.googleapis.com/keptn-installer/keptn-0.7.2.tgz

Please confirm that the provided cluster information is correct:
Cluster: kind-kind
Is this all correct? (y/n)
y
Installing Keptn ...
Start upgrading Helm Chart keptn in namespace keptn
Finished upgrading Helm Chart keptn in namespace keptn
Keptn has been successfully set up on your cluster.
---------------------------------------------------
* To quickly access Keptn, you can use a port-forward and then authenticate your Keptn CLI (in a Linux shell):
 - kubectl -n keptn port-forward service/api-gateway-nginx 8080:80
 - keptn auth --endpoint=http://localhost:8080/api --api-token=$(kubectl get secret keptn-api-token -n keptn -ojsonpath={.data.keptn-api-token} | base64 --decode)

* To expose Keptn on a public endpoint, please continue with the installation guidelines provided at:
 - https://keptn.sh/docs/0.7.x/operate/install#install-keptn
```

The base64 decode command is not present on windows and so you can't authenticate the cli against your keptn installation with the guide.

A possible command for encoding the String in powershell could be
` [Text.Encoding]::Utf8.GetString([Convert]::FromBase64String('BASE64STRING))`

Also in powershell the jsonpath argument needs to be in quotes like ` -ojsonpath="{.data.keptn-api-token}"`

**Comment by johannes-b** [comment]
When running the CLI on Linux/MacOS, then show: 
```
* To quickly access Keptn, you can use a port-forward and then authenticate your Keptn CLI in a bash:
 - kubectl -n keptn port-forward service/api-gateway-nginx 8080:80
 - keptn auth --endpoint=http://localhost:8080/api --api-token=$(kubectl get secret keptn-api-token -n keptn -ojsonpath={.data.keptn-api-token} | base64 --decode)

```

**Note:** Remove (in a Linux shell)

Always show a reference to *Authenticate Keptn CLI*: 
https://keptn.sh/docs/0.7.x/operate/install/#authenticate-keptn-cli
