### ISSUE TITLE
Wrong indicator for missing Git upstream

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#2577]
All my projects indicate that the Git upstream is missing. This is not true, since I created the Git upstream when I created the project. The original Keptn installation is from around Keptn 0.5 or 0.6 - maybe some service lost the information about the git upstream?
![image](https://user-images.githubusercontent.com/7677092/96872865-75337300-1474-11eb-971c-dccabe72a048.png)

For clarification: the git upstream is still working as you can see here: https://github.com/keptn-public-demo (recent updates each day) 

Is there any way to fix this issue? Do I have to restart a service?

**Comment by christian-kreuzberger-dtx** [comment]
After a quick analysis, it seems that when using `keptn update project` the materialized view that holds the information is not updated.

To fix this:

* adapt the configuration-service update project endpoint to insert changes into the materialized view
* adapt the configuration-service "get git credenitals" function to insert the upstream repository into the materialized view (if it doesn't exist already)
