### ISSUE TITLE
As a keptn user, I want to find additional information at the keptn docs page

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#258]
**Acceptance criteria**
  **Given** I'm a keptn user 
  **When** I open the keptn.sh/docs/0.2.0/ page
  **Then** I want find information for elements outlined below: 

**Concepts** - Understanding the basics - learn about keptn and its fundamental concepts:
- What is keptn?
- Use Cases 
  - <This is just an overview…not how to do it with the carts example>
  - <Have all the keys use cases like self-healing, quality gates, etc.>
- Architecture 
  - Diagram
  - Core control plane
  - Keptn services
  - Platform
  - Application & pipelines
  - Supporting components (Keptn CLI and logs)
- Shipping through Unbreakable Continuous Delivery Pipelines --- (talk about the diagrams from Andi’ PPT)
  - Pushing an artifact and deploy to dev
  - Promoting an artifact to staging
  - Promoting an artifact to production: Blue/Green
- Road map
- Keptn services overview – provides some details for each service not covered in the architecture section.  More details found in reference section.
  - Git
  - Container registry
  - Test automation
  - Pitometer
- Keptn supporting components overview – provides some details for each service not covered in the architecture section.  More details found in reference section.
  - Keptn CLI
  - Keptn Log
  - Keptn environment definition overview – provides some details for each service not covered in the architecture section.  More details found in reference section.
  - Shipyard – project/pipeline definition
  - Uniform - tooling definition

**Install keptn** – Instruction for how to prepare your environment for onboarding applications
- Pre-reqs overview
- Install keptn
  - GKE
  - AWS
- Install Keptn CLI

**Try keptn** - Follow tutorials to learn how to deploy applications in Keptn
- Carts – single microservice app – keep a lot of what is there but just have this be instructions for following the setup and how.  Add more details than there now for how to validate what happens when keptn does its processing. 
  - Overview of the pipeline design – i.e. what is Keptn going to do when pipelines run
  - Onboard project
  - Fork repo & setup the build pipeline 
  - Review what it did – Jenkins jobs, Perf Test, Dynatrace results, perfspec, Keptn logs
  - Canary deployments with a slowdown that will be detected
  - Run book automation
- Order app
- Sockshop – multiple microservice app

**Reference** – This is to have more details beyond the overview section.  
- Glossary
- Writing your own keptn service
- Keptn CLI Cheatsheet
- Keptn Shipyard – what is the SPEC
- Keptn Uniform – what is the SPEC
- Keptn Events – list out each event type and the SPEC
- PerfSpec – this may not be part of keptn, but add a link to where it resides
- Keptn services – more details on where source code it and how to use it/triage it
  - Github
  - Pitometer

**Contribute** - Anyone can contribute, whether you’re new to the project or you’ve been around a long time.
- Put some of same info that is on https://github.com/keptn/community  -- plus a link to community repo
- Coding standards
- Development process

**Comment by johannes-b** [comment]
Besides, provide guidance to verify the successful completion of a use case: 

- # this was way to see if the project got onboarded
  - describe configmap keptn-orgs -n keptn
 
- # this gives the pods names for inspection
  - kubectl -n keptn get pods
 
- # look at this to see if registry making events after a push
  - kubectl logs docker-registry-754b7797bd-h9mpx registry -n keptn
 
- # look at this to see if some events are happening
  - kubectl k logs event-broker-v44hx-deployment-5cd8477479-zmpct user-container -n keptn

**Comment by dirkwall** [comment]
Closing. Won't restructure now. We extend the doc as we go.
