### ISSUE TITLE
Keptn CLI: keptn install --help for use-case is not clear

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#2584]
When displaying the help for `keptn install`, it shows: 
```
  ...
  -u, --use-case string                The use case to install Keptn for [continuous-delivery]
```

The help message of the --use-case flag is not intuitive for end-users what will be installed.

**Suggestion:**

```
  ...
  -u, --use-case string                Use `--use-case=continuous-delivery` to install the execution plane for continuous delivery. Without this flag, your Keptn is capable of the quality gate and automated remediations use-case.  
```

**Task**
- Change the help comment for the flag: `--use-case` here: https://github.com/keptn/keptn/blob/master/cli/cmd/install.go#L168

**Comment by nanikjava** [comment]
@johannes-b you working on this ? if not happy to take it.

**Comment by johannes-b** [comment]
Hey @nanikjava, 
thanks for asking - I assigned it to you. 
Please ping me in case of any questions.

**Comment by nanikjava** [comment]
@johannes-b PR submitted. Thanks.
