### ISSUE TITLE
Wrong evaluation timeframe displayed when switching evaluations

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#2585]
In the evaluation screen in the bridge, when switching from one evaluation to another, the timeframe is not calculated correctly. It seems that the initial timeframe is stuck and not replaced with the timeframe of the clicked evaluation event. 

In the example, the timeframe of the preselected event is 5 minutes and it doesn't change, no matter which event is clicked.

![image](https://user-images.githubusercontent.com/7677092/97004164-ed656b80-153c-11eb-9796-efc9650ee1c1.png)

![image](https://user-images.githubusercontent.com/7677092/97004129-daeb3200-153c-11eb-8b52-a203743cec1e.png)

![image](https://user-images.githubusercontent.com/7677092/97004043-b5f6bf00-153c-11eb-9d64-76d70ee2224c.png)

**Comment by Godtide** [comment]
Assign to me

**Comment by christian-kreuzberger-dtx** [comment]
Hi @Godtide , can you give us an ETA when this is ready?

**Comment by ermin-muratovic** [comment]
@Godtide as discussed last thursday in our community meeting, I'll take this issue, since we need it for our 0.7.3 release.
