### ISSUE TITLE
Keptn CLI not backward compatible. Missing Keptn cluster version checks result in unclear error messages

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#2590]
Its possible to use a new Keptn CLI as the connected Keptn cluster, e.g: using CLI version 0.7.2 against a 0.7.1 Keptn Cluster.
This for instance leads to an unclear error message when executing ```keptn send event start-evaluation``` as the 0.7.2 CLI assumes the new /evaluation API endpoint which doesnt exist on a 0.7.1 installation. The error message simply returns that the /evaluation endpoint returned an error which is not very telling for the end user for troubleshooting.

I suggest that the CLI should do some version checks and either
1: warn the user that the CLI is newer or older then the keptn cluster and that an update on either side is suggested
2: is backward compatible, e.g: use the OLD API endpoints if the Keptn version is older

**Comment by christian-kreuzberger-dtx** [comment]
@johannes-b we seem to have missed this breaking change of the CLI in the release notes (we listed the new API endpoint though).

@grabnerandi I agree that this is a change that is unexpected for a patch release, like from 0.7.1 to 0.7.2.

>  1: warn the user that the CLI is newer or older then the keptn cluster and that an update on either side is suggested

We can extend issue https://github.com/keptn/keptn/issues/2571 such that we print a warning if CLI version is different from the API version. However, this means that in the case of a slow response from the Keptn API, the CLI will have to wait for the response, for every time you call the CLI.

>  2: is backward compatible, e.g: use the OLD API endpoints if the Keptn version is older

Being backward (and potentially forward compatible) for API and CLI requires quite some development effort. **IMHO** as long as our major version is `0`, we do not need to be backwards compatible. We do however need to document such breaking changes.

**Comment by johannes-b** [comment]
@christian-kreuzberger-dtx I would go with the approach of checking the API version before executing a command with the risk of slowing down the command. Thanks for referencing it with #2571 that should be implemented with this issue.
