### ISSUE TITLE
Create a sequence diagram for helm-service

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#2592]
With Keptn 0.8.x new cloud-events have been introduced (e.g., deployment, release), which lead to a huge refactoring of helm-service.

While the code is now better structured, it's now not so easy to figure out what each step of helm-service should do, and we need to document this using a sequence diagram.

IMHO we need a [sequence diagram](https://sequencediagram.org/) for every single cloud-event that helm-service can process, with the following participants:

* api/nats/distributor (entry point for the cloud-event)
* helm-service
* helm
* kubernetes cluster (k8s)
* configuration-service (git)

The following cloud-events come to my mind:

* onboard service / create service
* delete service
* deployment:promote (for both, blue-green and direct deployments)
* deployment:rollback (for both, blue-green and direct deployments)
* release (for both, blue-green and direct deployments)
* remediation action (e.g., scaling)

Using the sequence diagram, one needs to be able to figure out the following things easily:

1. When is `helm install/upgrade` called
1. When something is read from the git repo
1. When is something updated in the git repo
1. When is traffic shifted and to which service
1. When is values.yaml file updated
1. When a cloud-event is sent back to the api/nats/distributor

# Definition of Done

- [ ] The aforementioned sequence diagram and any necessary documentation for it is placed in a `docs` folder in `helm-service`.

**Comment by agrimmer** [comment]
Sequence diagram for handling `service.created` events (i.e. onboarding a service):
![Untitled (3)](https://user-images.githubusercontent.com/10980861/97708260-c5d04f00-1ab8-11eb-9012-e0c5cec60444.png)

Sequence diagram for handling `service.deleted` events:
![Untitled (4)](https://user-images.githubusercontent.com/10980861/97708312-df719680-1ab8-11eb-92d4-fa54429f5251.png)

Sequence diagram for handling `deployment.triggered` events:
![Untitled (5)](https://user-images.githubusercontent.com/10980861/97708406-0def7180-1ab9-11eb-9d08-7f18ba141121.png)

Sequence diagram for handling `release.triggered` events for a direct deployment:
![Untitled (6)](https://user-images.githubusercontent.com/10980861/97708509-31b2b780-1ab9-11eb-9877-de17cdf0d922.png)

Sequence diagram for handling `release.triggered` events for a b/g deployment which is promoted:
![Untitled (7)](https://user-images.githubusercontent.com/10980861/97708617-5eff6580-1ab9-11eb-940b-71d0391b7e73.png)

Sequence diagram for handling `release.triggered` events for a b/g deployment which is rolled back:
![Untitled (8)](https://user-images.githubusercontent.com/10980861/97708711-835b4200-1ab9-11eb-9af8-e3f42a160b86.png)

Sequence diagram for handling `action.triggered` events (i.e. scaling the deployment):
![Untitled (9)](https://user-images.githubusercontent.com/10980861/97708819-a8e84b80-1ab9-11eb-84e9-2c1dabb0b0f9.png)

I used https://sequencediagram.org/ for the following sequence diagrams. Furthermore, I have attached the sources. 
[helm-service_action-triggered.txt](https://github.com/keptn/keptn/files/5465265/helm-service_action-triggered.txt)
[helm-service_deployement-triggered.txt](https://github.com/keptn/keptn/files/5465266/helm-service_deployement-triggered.txt)
[helm-service_release-triggered-bg-promote.txt](https://github.com/keptn/keptn/files/5465267/helm-service_release-triggered-bg-promote.txt)
[helm-service_release-triggered-bg-rollback.txt](https://github.com/keptn/keptn/files/5465268/helm-service_release-triggered-bg-rollback.txt)
[helm-service_release-triggered-direct.txt](https://github.com/keptn/keptn/files/5465269/helm-service_release-triggered-direct.txt)
[helm-service_service-created.txt](https://github.com/keptn/keptn/files/5465270/helm-service_service-created.txt)
[helm-service_service-deleted.txt](https://github.com/keptn/keptn/files/5465271/helm-service_service-deleted.txt)

**Comment by christian-kreuzberger-dtx** [comment]
Thanks. We will need this in the repo in the helm/docs folder! 
@warber you have been working a lot with helm-service lately, can you also please take a look at the sequence diagrams and let us know if you believe that they are representing the current implementation?
