### ISSUE TITLE
Bridge should highlight the fact if remediation is disabled for a project

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#2601]
I am currently exploring the auto-remediation capabilities of keptn.
I created my own project and sending dynatrace problem events to that project. All works well as you can see from this screenshot

![image](https://user-images.githubusercontent.com/675886/97445888-08195500-192e-11eb-8417-088c37ea5c9a.png)

The problem however is that no remediation actions are executed even though I have uploaded a remediation yaml. Looking into the log files of the remediation service I figured out why - its because I havent enabled remediation in my shipyard file

```
{"timestamp":"2020-10-28T13:55:36.676944012Z","logLevel":"DEBUG","message":"Received problem notification"}
{"timestamp":"2020-10-28T13:55:36.677154129Z","logLevel":"DEBUG","message":"Received problem event with state OPEN"}
{"timestamp":"2020-10-28T13:55:36.690883596Z","logLevel":"INFO","message":"Remediation disabled for project demo-remediation in stage production"}
```

I propose that this should be indicated in the bridge. If we are sending problems to a keptn project and no auto-remediation is enabled we should make the user aware of this as otherwise troubleshooting can be really tough

**Comment by christian-kreuzberger-dtx** [comment]
I think this is going to be hanlded in https://github.com/keptn/keptn/issues/2299
