### ISSUE TITLE
Remediation Workflow Status not showing correctly in Bridge

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#2602]
Currently working on keptn 0.7.2 and playing with auto-remediation

When sending a problem to my keptn project the problem shows up correctly - but - then I was surprised that the remediation finsihed immediately without executing any of my actions. 
Here is the screenshot of my bridge
![image](https://user-images.githubusercontent.com/675886/97447191-97733800-192f-11eb-85ac-825d5963fc87.png)

When looking at the remediation finished event I see though what really happened - seems the remediation.yaml was not correctly formatted. I think this information should be visible in the UI because basically this says my auto-remediaiton is broken right now due to configuration problems. So - this information should be made clear in the UI:
```
{
  "contenttype": "application/json",
  "data": {
    "labels": {
      "Problem URL": "https://example.com"
    },
    "problem": {
      "PID": "",
      "ProblemDetails": null,
      "ProblemID": "",
      "ProblemTitle": ""
    },
    "project": "demo-remediation",
    "remediation": {
      "message": "remediation.yaml file does not conform to remediation spec spec.keptn.sh/0.1.4",
      "result": "failed",
      "status": "errored"
    },
    "service": "allproblems",
    "stage": "production"
  },
  "id": "00653418-24b3-4d82-9a20-104dbce59b78",
  "source": "remediation-service",
  "specversion": "0.2",
  "time": "2020-10-28T14:04:55.600Z",
  "type": "sh.keptn.event.remediation.finished",
  "shkeptncontext": "6d356cce-8a4f-4614-9854-3d75303f39d5"
}
```

Also seems that this "remediation.finished" event misses some relevant data, e.g: the problem details of the initial problem that triggered the workflow.

**Comment by christian-kreuzberger-dtx** [comment]
@grabnerandi does this still occur in 0.8.0?

**Comment by johannes-b** [comment]
With keptn `0.13.x`, a failed remediation action is displayed more prominently informing the user why it did not work.

![image](https://user-images.githubusercontent.com/729071/158125576-cda596cf-4390-4092-bc4b-e5b55b73063e.png)
