### ISSUE TITLE
Add environment variable to Helm chart for Keptn Bridge and set the value when doing a `keptn install`

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#2609]
The Keptn Bridge added the environment variable: `KEPTN_INSTALLATION_TYPE`: https://github.com/keptn/keptn/pull/2606/files#diff-f344a35654d53c1345c4d1f1734511437661440c90654afc144d955d38a900c5R49 to control the supported use-cases. 

The supported values are:
- `QUALITY_GATES`
- `CONTINUOUS_OPERATIONS` 
- `CONTINUOUS_DELIVERY`

**Task**
* This environment variable has to be added to the Helm Chart with the Bridge deployment, available here: 
https://github.com/keptn/keptn/blob/master/installer/manifests/keptn/charts/control-plane/templates/core.yaml#L165
* Add the environment variable to the list: https://keptn.sh/docs/0.7.x/operate/advanced_install_options/
* Depending on the install option chosen for `keptn install` the environment variable needs to be set.
  * `keptn install` --> CONTINUOUS_OPERATIONS
  * `keptn install --use-case=continuous-delivery` --> CONTINUOUS_DELIVERY

**Comment by johannes-b** [comment]
Idea: Instead of assuming that the CONTINUOUS_OPERATIONS includes QUALITY_GATES, and CONTINUOUS_DELIVERY includes CONTINUOUS_OPERATIONS as well as QUALITY_GATES - should we just store a list as value for `KEPTN_INSTALLATION_TYPE`?

`keptn install` --> QUALITY_GATES,CONTINUOUS_OPERATIONS
`keptn install --use-case=continuous-delivery` --> QUALITY_GATES,CONTINUOUS_OPERATIONS,CONTINUOUS_DELIVERY

**Comment by ermin-muratovic** [comment]
> Idea: Instead of assuming that the CONTINUOUS_OPERATIONS includes QUALITY_GATES, and CONTINUOUS_DELIVERY includes CONTINUOUS_OPERATIONS as well as QUALITY_GATES - should we just store a list as value for `KEPTN_INSTALLATION_TYPE`?
> 
> `keptn install` --> QUALITY_GATES,CONTINUOUS_OPERATIONS
> `keptn install --use-case=continuous-delivery` --> QUALITY_GATES,CONTINUOUS_OPERATIONS,CONTINUOUS_DELIVERY

I like the idea and agree on providing a list of supported use-cases in the current keptn installation.
