### ISSUE TITLE
JMeter service should do a sanity check on passed URL before running the test

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#2618]
If the JMeter serivce gets called with a deployment URI that is not accessible it doesnt make sense to launch the test at all as the test will result in an error anyway - but - due to the nature of JMeter may take a long time as every request will run into a timeout. That could lead to very long tests that actually dont do a whole lot

I propose to do a quick sanity check on the passed URIs. If the URIs are not accessible then throw an error right away

**Comment by johannes-b** [comment]
This feature request has been implemented as part of: https://github.com/keptn/keptn/pull/3685
