### ISSUE TITLE
Make JMeter configurable whether to use Local or Public Deployment URI

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#2619]
The JMeter service by default uses the deploymentURILocal if it is passed. There might be scenarios where we however want to test the public URI that is passed through deploymentURIPublic.
I suggest to make this configurable through the jmeter.conf.yaml. Simply add a flag that allows the user to define whether to use local or public

**Comment by christian-kreuzberger-dtx** [comment]
In

https://github.com/keptn/keptn/blob/558710292b2433f9467957daf0a7aa6d60e5c9fb/jmeter-service/main.go#L171-L181

we prefer local over public. Labeling this as a feature request.

**Comment by thisthat** [comment]
JMeter has been moved out of this repo
