### ISSUE TITLE
Allow to load more than 20 services/projects in the Bridge

### ISSUE THREAD

**Issue by ermin-muratovic** [keptn/keptn#2631]
The Keptns Bridge is using GET `​/project​/{projectName}​/stage​/{stageName}​/service` of the `configuration-service` to get the list of services. This API endpoint has a pageSize parameter and the default is 20. Therefore if a project has more than 20 services, you see only the first 20 and you currently don't have an option to increase the pageSize, neither to "load more". But the Bridge should show all services of a project, or at least provide a "load more" option.

![image](https://user-images.githubusercontent.com/6098219/98087325-2b895600-1e80-11eb-8db7-eb600396eb29.png)

**Comment by grabnerandi** [comment]
fyi- this was reported by Leon Van Zyl via our slack channel: https://keptn.slack.com/archives/CNRCGFU3U/p1604428621225200

**Comment by ermin-muratovic** [comment]
The same problem exists when loading projects. It would currently load a maximum of 20 projects.
