### ISSUE TITLE
CLI does not work when using gpg pass

### ISSUE THREAD

**Issue by bacherfl** [keptn/keptn#2638]
**Environment**

* Client OS (e.g., Linux, OSX, Windows): Linux (Ubuntu)
* Keptn Version (`keptn version`): latest

**Affected Component**

* [ ] Docs
* [x] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [ ] Bridge
* [ ] Gatekeeper
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**
When using [gpg pass](https://www.passwordstore.org/), the CLI is not able to manage the credentials needed for the access to the Keptn API.

**To Reproduce**

First, install pass using the following commands:

```
sudo apt-get install gpg pass -y
gpg --generate-key (Use your name and e-mail); Use "find / | xargs file" for generating random bytes; Copy generate pub key
pass init [generated pub key]
```

Then try to use the CLI, e.g.

```
keptn auth --endpoint=$KEPTN_ENDPOINT --api-token=$KEPTN_API_TOKEN
```

This should return the following error:

```
Starting to authenticate
Successfully authenticated against the Keptn cluster <SERVER_URL>
Error: exit status 1: gpg: rsa3072: skipped: No public key
gpg: [stdin]: encryption failed: No public key
Password encryption aborted.
```

**Expected behavior**
The CLI should work when using gpg pass

**Comment by ankitjain28may** [comment]
I would like to work on this

**Comment by jetzlstorfer** [comment]
happened again to one of our community members:
```
./main install --platform=kubernetes -u=continuous-delivery
Helm Chart used for Keptn installation: https://storage.googleapis.com/keptn-installer/latest/keptn-0.1.0.tgz
Please confirm that the provided cluster information is correct:
Cluster: aks-cicd-prod-002
Is this all correct? (y/n)
y
Error: exit status 1: gpg: 179AE881CAC03F6B: skipped: No public key
gpg: [stdin]: encryption failed: No public key
Password encryption aborted.
```
