### ISSUE TITLE
Changing the admin password in Jenkins breaks the keptn-service

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#264]
When changing the Jenkins admin password as noted in the [docs](https://keptn.sh/docs/0.2.0/installation/setup-keptn-gke/#verifying-the-installation), the jenkins-service can't trigger a pipeline because the password in the jenkins-secret does not get updated.

**Solution**: Use an API token that is part of the Jenkins image.

To curl this token during the installation: `curl --silent --basic http://<username>:<password>@<jenkins-url>/me/configure | hxselect ‘#apiToken’ | sed ‘s/.*value=“\([^“]*\)“.*/\1\n/g’`

**Comment by dirkwall** [comment]
Closing, Jenkins is not part of keptn core installation anymore, so changing the password is out of scope.
