### ISSUE TITLE
Distributor: handle empty values of ENV variables more reliably

### ISSUE THREAD

**Issue by warber** [keptn/keptn#2646]
It was observed that the distributor container of the api-service pod crashes due an invalid value of the `PUPBSUB_TOPIC` environment variable (which was set to `''`).

The distributor crashes with:
`failed to subscribe to topic: nats: invalid subject`

However, the distributor does not crash, if the `PUBSUB_TOPIC` env var is explicitly set to `none` or if it is not present at all.

PR #2643 fixed the problem by removing the environment variable(s), however a more reliable solution should be to make the handling of the env var variables more robust.

**Comment by christian-kreuzberger-dtx** [comment]
We should refine this issue (or dismiss it, if it's no longer needed).

**Comment by johannes-b** [comment]
Before working on this issue, let's merge: https://github.com/keptn/keptn/pull/2884

**Comment by johannes-b** [comment]
Has been fixed with: https://github.com/keptn/keptn/pull/2884
