### ISSUE TITLE
github-service does not support hyphen in service names

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#265]
If a service contains a hyphen, the github-service does not find the `istio-virtual-service-?.yaml` for this particular service.

**Comment by robertjahn** [comment]
We found this issue by triaging this keptn log message.  I suggest if you are in this code to update the log level from INFO to ERROR and perhaps add more details the file it tried to find.  {"keptnContext":"55cfe8d0-a837-4a46-be4e-37ee33b586f5","keptnService":"github-service","logLevel":"INFO","message":"Could not find shipyard file for project."}

**Comment by johannes-b** [comment]
Good idea! The new version now differentiates between ERROR and INFO logs.
