### ISSUE TITLE
Installing Keptn in AKS Via Helm command, getting exception

### ISSUE THREAD

**Issue by SaveethaRavi** [keptn/keptn#2662]
Hi team,

I tried installing keptn in AKS via HELM upgrade command, getting issues as "Error: validation: chart.metadata is required". Can anyone please suggest to overcome this issue and installing keptn in AKS.

Please refer attached screenshot.
<img width="887" alt="keptn error" src="https://user-images.githubusercontent.com/57527241/98673870-fbf5b480-237d-11eb-8c91-f695abbafcc1.PNG">

**Comment by christian-kreuzberger-dtx** [comment]
Can you please tell us which helm version you are using?
```
helm version
```

**Comment by SaveethaRavi** [comment]
version.BuildInfo{Version:"v3.3.0-rc.1", GitCommit:"5c2dfaad847df2ac8f289d278186d048f446c70c", GitTreeState:"dirty", GoVersion:"go1.14.4"}

**Comment by christian-kreuzberger-dtx** [comment]
I don't know if this is AWS specific, but it could be a problem of your helm cli version (3.3.0-rc.1). I am using 3.4.0 locally, and it seems to work.
See https://helm.sh/docs/intro/install/ for installation instructions for the helm cli.

**Comment by SaveethaRavi** [comment]
I have installed helm cli version (3.3.0) in VM and connected AKS. Tried installing keptn via helm upgrade command. Getting timed out error. 

Please provide your suggestion on this to get resolve.
<img width="782" alt="Keptn error VM" src="https://user-images.githubusercontent.com/57527241/98900915-c5807c80-24d8-11eb-9f3f-0eeb0ddada42.PNG">

**Comment by christian-kreuzberger-dtx** [comment]
This sounds like there is a problem with your Kubernetes cluster.

Please have a look at our Troubleshooting Steps: https://keptn.sh/docs/0.7.x/troubleshooting/#troubleshooting-the-installer-job

Also, make sure you have a cluster with enough resources (VCPUs and memory) - see https://keptn.sh/docs/0.7.x/operate/install/#create-or-bring-a-kubernetes-cluster (expand the *Azure Kubernetes Service* section).

If anything is unclear, please come to our [Keptn Slack](https://slack.keptn.sh).
