### ISSUE TITLE
Add service URL for CLI command: keptn get service

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#2678]
When executing `keptn get service` or `keptn get service --project=xxx` it would be great to also retrieve the service endpoint.

Right now this is the output:
![image](https://user-images.githubusercontent.com/7677092/98823162-0bced080-2432-11eb-853f-68d4e3139f97.png)

Desired output:
Include one additional column with the service endpoint (URL + port) to make it easier to navigate to the service.

**Comment by ankitjain28may** [comment]
I would like to pick this up

**Comment by christian-kreuzberger-dtx** [comment]
Sorry ankit, this issue actually needs to be refined, before anyone can implement this. 

Our deployment-finished cloud-events have the internal and external deployment URL in their payload, we can certainly use this information. Nevertheless, this is a topic that needs to be addressed at several levels:

* api
* cli
* wherever we have a materialized view for our services

I'll schedule it for refinement.

**Comment by johannes-b** [comment]
API is handled in #2692 - this issue depends on #2692 and just needs to print the service URL; which can be fetched from the configuration-service API.

**Comment by christian-kreuzberger-dtx** [comment]
I'm not 100% sure that this is already handled in API.

I just tried to fetch service information from configuration-service (using Keptn 0.8.0-alpha), and I only get a list of cloudevents, e.g.:
```
GET /api/configuration-service/v1/project/sockshop/service?pageSize=20

{
  "nextPageKey": "0",
  "services": [
    {
      "creationDate": "1608735908346370799",
      "serviceName": "carts",
      "stageInfo": [
        {
          "lastEventTypes": {
            "sh.keptn.event.deployment.started": {
              "eventId": "4f7c40ef-20de-451d-a24a-f050b462d0c0",
              "keptnContext": "3141665c-dc68-4afb-8831-d70d762e7b0d",
              "time": "1609144600603155343"
            },
            ...
          },
          "stageName": "dev"
        },
        {
          "lastEventTypes": {
            "sh.keptn.event.deployment.started": {
              "eventId": "bbeb8734-624f-4319-8b6a-39b0039bdb9d",
              "keptnContext": "3141665c-dc68-4afb-8831-d70d762e7b0d",
              "time": "1609144683728966038"
            },
            ...
          },
          "stageName": "staging"
        },
        {
          "lastEventTypes": {
            "sh.keptn.event.action.finished": {
              "eventId": "eaca9735-5324-487b-b95f-d1ff3e75754f",
              "keptnContext": "38646432-6333-4161-b437-636632653738",
              "time": "1609172704186273261"
            },
            ...
          },
          "stageName": "production"
        }
      ]
    },
    {
      "creationDate": "1608735933618651267",
      "serviceName": "carts-db",
      ...
    }
  ],
  "totalCount": 2
}
```
