### ISSUE TITLE
Dynatrace service that sends deployment/configuration events

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#268]
When a configuration change in the config repo of a monitored service happens, I want to see an event in Dynatrace. 
Besides, the deployment event in Dynatrace should have a more informative name (e.g.: New deployment on green) instead of the service name currently used.

**Comment by dirkwall** [comment]
We could implement this as a Dynatrace service that is subscribed to keptn channels and forwards events.

**Comment by johannes-b** [comment]
See the pipelines in https://github.com/keptn/jenkins-service/tree/feature/268/dt-pipelines/pipelines
These pipelines contain nice DT events.
