### ISSUE TITLE
Link to azure dev ops tutorial in integrations page not working

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#2686]
https://github.com/keptn/get.keptn.sh/blob/4bdbea7c23163b3d715b35eea60e1db8097af7a3/src/integrations.html#L4

The link to the azure devops tutorial which is loaded from https://get.keptn.sh/integrations.html is not working.

Original issue where this link was introduced: https://github.com/keptn/keptn/issues/2429

**Comment by johannes-b** [comment]
The link itself is working, but the tutorial is broken. When I click on **Azure DevOps ...** in https://tutorials.keptn.sh/keptn06x, it shows a 404. 

@jetzlstorfer can you help out to fix the 404 for the **Azure DevOps** tutorial. 

In the meanwhile, we can remove the link from: https://github.com/keptn/get.keptn.sh/blob/master/src/integrations.html#L4

**Comment by christian-kreuzberger-dtx** [comment]
Fixed in https://github.com/keptn/get.keptn.sh/pull/21
