### ISSUE TITLE
keptn upgrade command: Avoid the version check via a flag

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#2689]
When executing `keptn upgrade` using a nightly version or a preview of a release branch (e.g., with 0.7.3), we always get the following message:
```
$ keptn upgrade
Error: No upgrade path exists from Keptn version 0.7.2 to 0.7.3
```

We should however provide the user the option to overwrite this, e.g., using
```
$ keptn upgrade --skip-upgrade-check
```

# Definition of Done

- [ ] Introduce a new parameter/flag for the upgrade command to disable the upgrade path check
- [ ] Unit test added the existing and new behaviour

**Comment by gdsoumya** [comment]
Is this feature still needed? If it's still required I would like to take this up @christian-kreuzberger-dtx

**Comment by christian-kreuzberger-dtx** [comment]
Yes, still needed. I'll assign it to you! Do you know where to start?

**Comment by gdsoumya** [comment]
Thanks for assigning, I do have some idea. I think this is where the change should go : https://github.com/keptn/keptn/blob/26b57f50cd53578ddda51e1c2fb03e4163ba767b/cli/cmd/upgrade.go#L61 

I'll have to add a new flag and check if the `skip-upgrade-check` is set, if it is set I skip the above check else I continue as it is. 

Is this the requirement?

**Comment by christian-kreuzberger-dtx** [comment]
Yes, taht's the right file, and within the doUpgradePreRunCheck function we have a call for checking if the release is compatible:
https://github.com/keptn/keptn/blob/26b57f50cd53578ddda51e1c2fb03e4163ba767b/cli/cmd/upgrade.go#L87-L98

**Comment by gdsoumya** [comment]
Do you want to skip the `doUpgradePreRunCheck` completely or just the `isUpgradeCompatible` check?

**Comment by christian-kreuzberger-dtx** [comment]
I think it should only be the check for `isUpgradeCompatible`, the other checks will still need to be performed.

**Comment by gdsoumya** [comment]
Got it, I'll raise a PR with the changes. About the testing I don't see any existing test file for the upgrade command can you guide me regarding that?

**Comment by christian-kreuzberger-dtx** [comment]
You can create a file called `upgrade_test.go` in the same folder.
You can use https://github.com/keptn/keptn/blob/master/cli/cmd/generate_docs_test.go as a template.

Make sure to use the `--mock` flag.

**Comment by gdsoumya** [comment]
hi @christian-kreuzberger-dtx, I have raised a PR for this issue #3020 please take a look and let me know if any changes are required.
