### ISSUE TITLE
Fetching resources from folder via API not working

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#2707]
Talked to @sergiohinojosa regarding a bug, here are his words:

> I found a small bug that annoyed me this afternoon and was driving me crazy (thinking that something in the datastore was corrupt or the customer messed up the sli.yaml file). Downloading resources over the API is not possible if the ressource is behind a folder (meaning having a slash /). It always returns 404. I tried fetching the /dynatrace/sli.yamlin 0.7.2 and also on 0.7.3 with the same results. Also tried other ressources like the jmx file behind the jmeter folder with the same results. I was not succesfull to escape the slash or code it in a different way with curl or postman.

![image](https://user-images.githubusercontent.com/7677092/99665040-61762f00-2a69-11eb-97c7-57f8d3c755b1.png)

**Comment by jetzlstorfer** [comment]
@sergiohinojosa please add more information to clarify the issue

**Comment by sergiohinojosa** [comment]
Nothing more to add, if something is unclear, glad to assist. 
I tested on microk8s with 0.7.2 and 0.7.3.

**Comment by christian-kreuzberger-dtx** [comment]
After a quick discussion, it sounds like that our `api-gateway-nginx` might be converting the `%2F` to a `/`, and then configuration-service doesn't really know how to handle this.

Quick way to verify that `api-gateway-nginx` is blocking us here:
Let's try to fetch the resource directly from `configuration-service` (not via `api-gateway-nginx`). 

We also need to provide a workaround for now.

**Comment by sergiohinojosa** [comment]
well the easiest workaround I found was to have the cluster with k9s connected. So I can easily shell into the configuration service and with `ls/cat/vi `and `git `commands inspect the customer projects and it's resources available.

**Comment by agrimmer** [comment]
I did a quick research and NGINX decodes the URL, see https://stackoverflow.com/questions/28684300/nginx-pass-proxy-subdirectory-without-url-decoding/37584637#37584637 and https://stackoverflow.com/questions/8264239/nginx-unescapes-2f-to-a-forward-slash-how-can-i-stop-it
We can fix this in our NGINX configuration, which, however, can be error-prone and can introduce security vulnerabilities. 
Therefore, we should consider using a query parameter instead of the path parameter for at least the `resourceURI`.

**Comment by christian-kreuzberger-dtx** [comment]
>  Therefore, we should consider using a query parameter instead of the path parameter for at least the resourceURI.

Fully agree. @johannes-b let's change this for 0.8.x.

> I did a quick research and NGINX decodes the URL
That's what I thought.

Can we easily fix this for 0.7.3 or at least provide a workaround?

**Comment by bacherfl** [comment]
A possible solution that could also be implemented for 0.7.3 is implemented in [this Draft PR](https://github.com/keptn/keptn/pull/2736)

As a workaround, fetching the resources does work when accessing the configuration-service via port-forwarding, but this might of course not be possible in all cases
