### ISSUE TITLE
Updating existing upstream not working

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#2708]
Talked to @sergiohinojosa and here are his words:

> is it possible to update the repo of a project for a second time? By moving from the internal datastore to a git repo works like a charm. But let’s say you are migrating and have another remote URL that you want to change (for whatever reason, change of provider, moving the cluster, firewall, etc…) I tried to update the project a second time and I get the error
```
$keptn update project xxxxxx xxxxx.git
Starting to update project
Error: Update project was unsuccessful. Could not store git credentials
But the git credentials are ok and the repo is new.
```

Logs from the configuration service:
```
{"timestamp":"2020-11-18T18:41:28.90737245Z","logLevel":"DEBUG","message":"Storing Git credentials for project sockshop"}
{"timestamp":"2020-11-18T18:41:28.916984244Z","logLevel":"ERROR","message":"Could not store git credentials during creating project sockshop: secrets \"git-credentials-sockshop\" already exists"}
```

If I delete the credentials it wont be able to migrate from A to B since the credentials from the first repo are missing.
```
{"timestamp":"2020-11-19T08:10:52.771693577Z","logLevel":"DEBUG","message":"Updating project sockshop"}
{"timestamp":"2020-11-19T08:10:52.771725871Z","logLevel":"INFO","message":"Project sockshop not updated as Git credentials were missing."}
```

**Desired behavior**:
Even if a git upstream is already set, the command should allow to set a new git upstream. (This mean the existing secret has to be deleted and a new one created)

**Comment by jetzlstorfer** [comment]
@sergiohinojosa please add more details to clarify this issue

**Comment by sergiohinojosa** [comment]
Nothing more to add, if something is unclear, glad to assist. 
I tested on microk8s with 0.7.2 and 0.7.3.

**Comment by sergiohinojosa** [comment]
If I delete the secret 
`kubectl delete secret -n keptn git-credentials-sockshop`

and update the project it also fails:

```
Starting to update project
Error: Update project was unsuccessful. Error executing command git remote add origin http://keptn:********@git.18-134-155-138.nip.io/keptn/sockshop-migrate.git: exit status 128
fatal: remote origin already exists.
```
log of configuration service pod
```
{"timestamp":"2020-11-19T12:30:39.862220677Z","logLevel":"DEBUG","message":"Storing Git credentials for project sockshop"}
{"timestamp":"2020-11-19T12:30:39.870681301Z","logLevel":"DEBUG","message":"Add Git origin and push changes for project sockshop"}
{"timestamp":"2020-11-19T12:30:39.87748581Z","logLevel":"ERROR","message":"Could not add upstream repository while updating project sockshop: Error executing command git remote add origin http://keptn:********@git.18-134-155-138.nip.io/keptn/sockshop-migrate.git: exit status 128\nfatal: remote origin already exists.\n"}
```

I believe that we should add the possibility to migrate to a git upstream as much as needed and whenever the git repository is not available we fall-back to the internal data-store. When the git-upstream is available again, we synchronize with the new changes from git and the datastore.

**Comment by sergiohinojosa** [comment]
I tried to remove the remote branch from within the configuration pod and it is not listed.

/data/config/sockshop # git remote rm origin
fatal: No such remote: 'origin'

git remote -v also delivers an empty answer
