### ISSUE TITLE
DockerHub: Stale images are going to be deleted soon

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#2710]
I just discovered that some of our images are "stale" (no pulls for 6 months?) and they might be [deleted soon (mid 2021)](https://www.docker.com/blog/docker-hub-image-retention-policy-delayed-and-subscription-updates/), according to DockerHubs new image retention policy.

![image](https://user-images.githubusercontent.com/56065213/99787127-a197e900-2b1f-11eb-9b6e-bb602d985779.png)

Immediate action: I will try to verify which images are affected. In addition, I will try to pull images that we know that are still in use.

I did this by visiting our repositories on docker hub and manually looked for those stale images. 
I also cleaned up some old stales images (such as feature/bugfix/patch images) which made it easier to find the real stale images.
Once cleaned up, I used `docker pull $repo --all-tags` (which obviously will create a huge problem if you pull 5000 tags)

Note: clean up of unused images is described in this issue: https://github.com/keptn/keptn/issues/1037

# Confirmed Affected Repos

* [keptn/upgrader](https://hub.docker.com/repository/registry-1.docker.io/keptn/upgrader/tags?page=1) *status: temporarily fixed*
* [keptn/installer](https://hub.docker.com/repository/registry-1.docker.io/keptn/installer/tags?page=1) *status: temporarily fixed*
* [keptn/bridge (old bridge)](https://hub.docker.com/repository/registry-1.docker.io/keptn/bridge/tags?page=1) *status: temporarily fixed*

# Definition of Done

- [ ] Create a CI job that monitors/detects if any release images are becoming stale. If they are about to become stale, `docker pull` the image.

**Comment by johannes-b** [comment]
This will also affect us on keptn/contrib and keptn/sandbox. We need to create an issue for that.

**Comment by christian-kreuzberger-dtx** [comment]
Update:
It is possible to query https://hub.docker.com/v2/repositories/keptn/bridge/tags/ and manually go through all images `tag_last_pulled` value. Unfortunately we can not query based on the date via the API.
What we could do however is to query by name, and just look at tags named after releases, e.g.:

https://hub.docker.com/v2/repositories/keptn/bridge/tags/?name=0.5

My strategy in implementing this is to query all releases of Keptn via GitHub API, and based on the tag in the release, I can query the tags on DockerHub, and check for `tag_last_pulled`.
