### ISSUE TITLE
Travis CI builds are disabled due to negative credit balance

### ISSUE THREAD

**Issue by warber** [keptn/keptn#2715]
Follow-up of https://github.com/keptn/keptn/issues/2356
At the moment Travis CI builds seems to be temporarily disabled.

See: https://travis-ci.com/github/keptn/keptn

![2020-11-23_11-01](https://user-images.githubusercontent.com/72415058/99949468-63970100-2d7b-11eb-89e2-d7a462f4398b.png)

**Comment by christian-kreuzberger-dtx** [comment]
We are getting 10k units (per day?) for free. Here are the usage costs:
![image](https://user-images.githubusercontent.com/56065213/99953464-8f1cea00-2d81-11eb-9920-785d9e7f2a47.png)

**Comment by christian-kreuzberger-dtx** [comment]
> We will be offering an allotment of OSS minutes that will be reviewed and allocated on a case by case basis. Should you want to apply for these credits please open a request with Travis CI support stating that you’d like to be considered for the OSS allotment. 

I will be contacting travis-ci support.

**Comment by christian-kreuzberger-dtx** [comment]
As another step, I have created two issues #2716 #2717 to migrate certain jobs from travis-ci to GitHub Actions. This should help us for merging PRs.

**Comment by christian-kreuzberger-dtx** [comment]
Some people have similar issues https://twitter.com/travisci/status/1330866192316309504
![image](https://user-images.githubusercontent.com/56065213/99971853-0d878500-2d9e-11eb-9eeb-7fa1dcdb01e4.png)

**Comment by christian-kreuzberger-dtx** [comment]
Travis has granted us a free contingent **once** for now, but this is only going to last us 2-3 weeks. I've created follow-up issues to start migrating away from Travis (to GH actions).

**Comment by christian-kreuzberger-dtx** [comment]
Travis has granted us a free contingent **once** for now, but this is only going to last us 2-3 weeks. I've created follow-up issues to start migrating away from Travis (to GH actions).

**Comment by christian-kreuzberger-dtx** [comment]
Re-opening this issue, as we are close to running out of credits again :(

**Comment by christian-kreuzberger-dtx** [comment]
We have migrated away from travis-ci to GH actions.
