### ISSUE TITLE
Remove hard-dependency of MacOS builds in travis-ci

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#2719]
Due to the current limitations of Travis-CI https://github.com/keptn/keptn/issues/2715, we are forced to change some of our jobs.

One big issue is that MacOS is required to build the CLIs:

- https://github.com/keptn/keptn/blob/f89f31c5a5d95b80b4c933f9312b4598a1da92ee/.travis.yml#L324-L338
- https://github.com/keptn/keptn/blob/f89f31c5a5d95b80b4c933f9312b4598a1da92ee/.travis.yml#L355-L373
- https://github.com/keptn/keptn/blob/f89f31c5a5d95b80b4c933f9312b4598a1da92ee/.travis.yml#L456-L470

Unfortunately, we will need to keep building at least the MacOS binary on MacOS (see #2738), but we should move Windows and Linux builds to a Linux based job (either on Travis-CI or GitHub actions), as MacOS builds are expensive.

# Definition of Done

- [ ] CLI builds for Linux and Windows are running on Linux on GH Actions for each PR if any file in the `cli` folder has changed (does not matter which branch name; release, feature, patch, bugfix)
- [ ] CLI build for MacOS is still running on MacOS, but on GH Actions for each PR if any file in the `cli` folder has changed (does not matter which branch name; release, feature, patch, bugfix)
- [ ] Every push/commit on master branch should build the "latest" CLI
- [ ] Resulting binaries are still uploaded to Google Cloud

**Comment by kadirselcuk** [comment]
I think this problem is exactly what I'm talking about, thank you.
