### ISSUE TITLE
Continue working with current Keptn context and remove Keptn context switch from keptn --help

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#2721]
While testing out the new feature of the keptncontext, I observed the following behavior. 
* Keptn CLI is authenticated to Keptn 1
* I switch the Kubernetes Cluster (with Keptn 2 installed)
* I expected a keptn command `keptn status` - it is asking whether to switch to the other Kubernetes Cluster (with Keptn 2) 
* I want to work with Keptn 1 - that`s why I say `n`
* The command terminates with the message: `stopping installation`

![image (2)](https://user-images.githubusercontent.com/729071/100058415-82ec6780-2e29-11eb-9e90-cb662087e70b.png)

**Expected behavior:** When denying the switch to the other Kubernetes cluster, I expect to continue the command against the Keptn I'm currently authenticated to. 

---

```
$ ./keptn --help
Kube context has been changed to gke_sai-research_europe-west1-b_keptn-060-internal-demo-cluster
Do you want to continue with this? (y/n)
```

Additionally, the `keptn --help` command should not contain the context switch of the Keptn context. It should just print the help page.

**Comment by johannes-b** [comment]
Hi @ankitjain28may, can you please leave a comment here so that I can assign this issue to you (since you already filed a PR for that).

**Comment by ankitjain28may** [comment]
@johannes-b Please assign this to me.

**Comment by johannes-b** [comment]
Hi @christian-kreuzberger-dtx, 

can you please check which Keptn CLI version you are using? Because Ankit and I cannot reproduce your problem with `keptn --help`. For us, the question for the context switch does not show up:

![image](https://user-images.githubusercontent.com/729071/100193440-14281080-2ef4-11eb-8eee-14280dc78959.png)

**Comment by johannes-b** [comment]
- [ ] Change the question: "Do you want to continue with this? (y/n)" to "Do you want to switch to the new Kube context with the Keptn running there?"
