### ISSUE TITLE
Fix LICENSE file

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#2725]
The license file has to be fixed to adhere to the CNCF guidelines.
https://github.com/cncf/foundation/blob/master/copyright-notices.md

Suggestion: 
change copyright to:
**The Keptn authors** 

Scope: 
- Update of LICENSE files in the entire keptn organization

**Comment by jetzlstorfer** [comment]
@christian-kreuzberger-dtx @johannes-b 
what are your thoughts on this?

**Comment by johannes-b** [comment]
Your suggestion sounds good and is aligned with the CNCF guidlines.

**Comment by johannes-b** [comment]
Please make sure to also consider surrounding repos (examples, keptn.github.io, community)

**Comment by jetzlstorfer** [comment]
Updated the LICENSE file for

- [ ] keptn/enhancement-proposals https://github.com/keptn/enhancement-proposals/pull/27 
- [ ] keptn/get.keptn.sh https://github.com/keptn/get.keptn.sh/pull/22 
- [ ] keptn/kubernetes-utils https://github.com/keptn/kubernetes-utils/pull/14
- [ ] keptn/community https://github.com/keptn/community/pull/30
- [ ] keptn/spec https://github.com/keptn/spec/pull/49 
- [ ] keptn/keptn.github.io https://github.com/keptn/keptn.github.io/pull/699 
- [ ] keptn/tutorials https://github.com/keptn/tutorials/pull/109 
- [ ] keptn/go-utils https://github.com/keptn/go-utils/pull/220 
- [ ] keptn/examples https://github.com/keptn/examples/pull/151 
- [ ] keptn/keptn https://github.com/keptn/keptn/pull/2781




keptn

**Comment by christian-kreuzberger-dtx** [comment]
everything except for keptn/tutorials has been approved and merged.

**Comment by jetzlstorfer** [comment]
all merged 👍🏼
