### ISSUE TITLE
List Keptn project(s) configuration (with it's stages, services and files) tree

### ISSUE THREAD

**Issue by sergiohinojosa** [keptn/keptn#2742]
Hi dear Keptns,

I would like to see and list the projects configuration with a single command. Even if I configure a git upstream (and for beginners normally that's not the case), **it is hard to get an overview of what is configured** and how many stages/services a project has. With simple tools like `tree` we can display the different stages, services and its folders with file names. Here is a sample how to display the sockshop project with one stage:

Showing master and dev branches with tree (which are inside the configuration-pod in the data directory)
```
$ keptn list project sockshop

sockshop
    |-------master
    │        ├── dynatrace
    │        │   └── sli.yaml
    │        ├── metadata.yaml
    │        └── shipyard.yaml
    │
    └──-------dev
            ├── Chart.yaml
            ├── carts
            │   ├── helm
            │   │   ├── carts
            │   │   │   ├── Chart.yaml
            │   │   │   ├── templates
            │   │   │   │   ├── deployment.yaml
            │   │   │   │   └── service.yaml
            │   │   │   └── values.yaml
            │   │   └── carts-generated
            │   │       ├── Chart.yaml
            │   │       └── templates
            │   │           ├── carts-istio-destinationrule.yaml
            │   │           └── carts-istio-virtualservice.yaml
            │   ├── jmeter
            │   │   └── basiccheck.jmx
            │   └── metadata.yaml
            ├── carts-db
            │   ├── helm
            │   │   ├── carts-db
            │   │   │   ├── Chart.yaml
            │   │   │   ├── templates
            │   │   │   │   ├── carts-db-deployment.yaml
            │   │   │   │   └── carts-db-service.yaml
            │   │   │   └── values.yaml
            │   │   └── carts-db-generated
            │   │       ├── Chart.yaml
            │   │       └── templates
            │   │           ├── carts-db-istio-destinationrule.yaml
            │   │           └── carts-db-istio-virtualservice.yaml
            │   └── metadata.yaml
            ├── metadata.yaml
            ├── requirements.yaml
            └── values.yaml


```

This is very simple but powerful and performant. This information can be implemented in the Keptn CLI or over the API. Something like `keptn list project` . This information can be added as well in supportarchives so we can understand the logical view of the implementation. 

We could filter with flags the level to display, meaning if we dont specify projects as default we list all projects, with all stages and services. 

Thanks & best
Sergio

P.S: The listing I did manually with two tree commands. Tree only shows the files on the disk. But with simple bash functions we could list the branches (stages), and with `tree` or doing it the hard way with `ls` checking folders and recursively navigating into them we could achieve the desired result.

**Comment by christian-kreuzberger-dtx** [comment]
I like the idea, and I believe it shouldn't be too hard to implement within API.

However, I would like to discuss whether we should implement such a basic `git` functionality directly in Keptn. We have had some discussions already where we came to the conclusion that it is bad practice to hide git functionality, and to create wrappers (like `keptn add-resource`). For one thing, it creates code that we need to maintain. In addition, users are fully capable of working with git, we don't need to explain them how git works (but we need to explain them how `keptn add-resource` works and why there is no `keptn delete-resource` command...).

IMO it would be better to provide users with the possibility to access the Git Repo as suggested here: https://github.com/keptn/keptn/issues/1336, e.g., using gitea.

I would even go as far as stating that we *should* be able to deploy a tool like [gitea](https://try.gitea.io/) using `keptn create project` and `keptn create service`, and users can then just update their git upstream.
