### ISSUE TITLE
Build Automation: Execute integration tests before merging changes into master

### ISSUE THREAD

**Issue by warber** [keptn/keptn#2748]
Currently, integration tests are executed right after a pull request has been merged into the master branch.
This has the risk of breaking the master branch any time a new feature or bug fix gets merged and is in contrast to our goal of having a stable master branch.

Let's discuss possible solutions. Integration tests shall be executed before the actual merge e.g. when opening a pull request.

**Comment by christian-kreuzberger-dtx** [comment]
> This has the risk of breaking the master branch any time a new feature or bug fix gets merged and is in contrast to our goal of having a stable master branch.

100% agreed!

> Let's discuss possible solutions. Integration tests shall be executed before the actual merge e.g. when opening a pull request.

Ideally the test would run "as if the PR was merged". With GH Actions and Travis-CI this is currently not 100% possible, we would only run the test based on the commit history of the branch (so it depends on when the branch was created). By forcing users to rebase we would get a good way, but not 100% sure if this is a viable option.

**Comment by warber** [comment]
> Ideally the test would run "as if the PR was merged". With GH Actions and Travis-CI this is currently not 100% possible, we would only run the test based on the commit history of the branch (so it depends on when the branch was created). By forcing users to rebase we would get a good way, but not 100% sure if this is a viable option.

agree, this is an inherent characteristic of this workflow. I think it is okay to advise the PR contributor to do a rebase/merge in order to not deviate too much from the current master branch.

**Comment by christian-kreuzberger-dtx** [comment]
One thing we could introduce right now would be to run the integration test "Linking Stages" as shown in the workflow here:
https://github.com/keptn/keptn/blob/26b57f50cd53578ddda51e1c2fb03e4163ba767b/.github/workflows/integration_tests.yml#L316-L322

We could run that with GH actions via K3s. It's reasonably fast (setup + Keptn install via K3s on GH Actions takes roughly 4 minutes, the test itself takes 30 seconds), and it would show whether something major was broken.
One thing though: it requiers a full CLI + Docker build, which takes 40 minutes (or longer, when MacOS builds are hanging...).
As a pre-requesit we could work on getting tests and our helm-chart comaptible with partial builds (so we don't need full builds).

**Comment by christian-kreuzberger-dtx** [comment]
This might be fixed with https://github.com/keptn/keptn/issues/2986
