### ISSUE TITLE
Move docker builds from travis-ci to GitHub Actions

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#2752]
Our docker full builds consume roughly 35 minutes on travis-ci every time we push to master.

Options:
a) not build everytime we push to master, but maybe only 4 times a day (and only if there was a commit on master)
b) move the build to GH action to save some credits on Travis-CI (and maybe also only run it 4 times a day?)

**Update:** 
Option a) is not possible on Travis-CI.

**Definition of Done:** 
- [ ] Build tasks are moved to GH actions

**Comment by johannes-b** [comment]
@ankitjain28may would like to work on it.

**Comment by ankitjain28may** [comment]
@johannes-b Please assign it to me

**Comment by christian-kreuzberger-dtx** [comment]
@ankitjain28may please take a look at https://github.com/christian-kreuzberger-dtx/hello-api-go/blob/master/.github/workflows/docker_build.yml for inspiration ;)

Also, please mind that we already have DOCKER Hub credentials available via 
https://github.com/keptn/keptn/blob/881adf2c5a1e90de90fd2c486994a55cdfc313db/.github/workflows/cleanup_images.yml#L15-L16

**Comment by christian-kreuzberger-dtx** [comment]
Hi @ankitjain28may, did you start this issue yet? If not, I'd like to take it.

**Comment by ankitjain28may** [comment]
Hi @christian-kreuzberger-dtx Not yet, sure I might take this up by the end of the week. Please go ahead, Thanks
