### ISSUE TITLE
Extend JMeter to also download data files before executing a test

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#2756]
Currently the jmeter service only downloads the jmx file and executes it. 
This is limiting the use of JMeter because its not possible to reference any e.g: data files

We should exted jmeter.conf.yaml to reference additional files that should be downloaded into the same local directory in the jmeter pod so that the .jmx file can reference them without an issue

**Comment by christian-kreuzberger-dtx** [comment]
> We should exted jmeter.conf.yaml to reference additional files that should be downloaded into the same local directory in the jmeter pod so that the .jmx file can reference them without an issue

Would it also work if jmeter-service downloads everything that's in the `jmeter` folder (including sub-folders)?

**Comment by grabnerandi** [comment]
Yes. That would even be better. And - a feature that every service could benefit from. In the end we say that files should be uploaded to a specific folder in the config repo. If there would be an easy way to "clone" either the full repo or get that partial directory tree it would be great help and would also reduce the need to additoinally configure which files to download!

**Comment by christian-kreuzberger-dtx** [comment]
@grabnerandi it looks like you are working on this? If so I would like to assign it to you :)
