### ISSUE TITLE
Add a show command to keptn cli auth and configure options

### ISSUE THREAD

**Issue by robertjahn** [keptn/keptn#276]
**Is your feature request related to a problem? Please describe.**
I dont know where to see if and what I am configured to.  I have multiple clusters and projects and I dont know if I need to re-run these commands

**Describe the solution you'd like**
show output to console with what is current configuration.  if not configured, then show that output

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by dirkwall** [comment]
will be resolved by #215
