### ISSUE TITLE
Investigate possibility to reduce number of API calls to mongodb-datastore

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#2760]
In order to troubleshoot https://github.com/keptn/keptn/issues/2744 I have spammed my Keptn 0.7.3 with a lot of cloud-events:

1. start-evaluation cloud-events in project ck-keptn-qg (probably around 200 start-evaluation root events per service for 12 services = 2400 root events)
1. new-artifact cloud-events in project ck-sockshop (probably around 80 configuration-change root events, one service)

See https://pastebin.com/qVqSZFH9 for output of statistics-service.

I noticed that Keptn's Bridge is heavily affected by the performance of the mongodb-datastore, and I was wondering if we can reduce or even avoid certain API calls.

# Investigation

## Result 1: Opening Bridge (with 3 projects) is quick as always, the following API calls are quick (enough)
api/version.json
api/bridgeInfo
api/swagger-ui/swagger.yaml
api/configuration-service/v1/project?disableUpstreamSync=true&pageSize=50
api/configuration-service/v1/project/ck-sockshop/stage/dev/service?pageSize=50
api/configuration-service/v1/project/ck-sockshop/stage/staging/service?pageSize=50
api/configuration-service/v1/project/ck-sockshop/stage/production/service?pageSize=50
api/configuration-service/v1/project/foobar/stage/dev/service?pageSize=50
api/configuration-service/v1/project/foobar/stage/staging/service?pageSize=50
api/configuration-service/v1/project/foobar/stage/production/service?pageSize=50
api/configuration-service/v1/project/ck-keptn-qg/stage/hardening/service?pageSize=50

## Result 2: Opening ck-sockshop (a project with two services and not too many events) leads to many API calls (but it's quick)

This is "okay-ish", the following API Calls are happening
To avoid having to copy paste all the URLs, here is just a screenshot
![image](https://user-images.githubusercontent.com/56065213/101137509-3c5bf180-360f-11eb-808e-7bd5e1a54202.png)

However, at this point I'm already wondering why we need so many API Calls for a very simplistic view:
![image](https://user-images.githubusercontent.com/56065213/101137549-4b42a400-360f-11eb-9088-e66bbe14982b.png)

## Result 3: Opening ck-keptn-qg (a project with 12 services and a lot of start-evaluation events) is leading to performance problems

Here we really get into trouble. 
first we do a lot of API calls for root events (red rectangle), and then we do even more API calls afterwards which eventually lead to a performance bottleneck
![image](https://user-images.githubusercontent.com/56065213/101137756-98bf1100-360f-11eb-85e1-469be12f95b8.png)

This is the resulting UI:
![image](https://user-images.githubusercontent.com/56065213/101138036-f05d7c80-360f-11eb-8d8d-1cf42a43ae2f.png)

# Next steps

Let's identify if we need all those API calls for certain (UI) features within Keptn Bridge, or if we can do something different and save some API calls, which would overall have a benefit on performance.

**Comment by ermin-muratovic** [comment]
Please consider and review this API calls:
https://github.com/keptn/keptn/blob/3026c60191db339efdd39339d774e6573003ad87/bridge/client/app/_services/data.service.ts#L71-L72

See also:
https://github.com/keptn/keptn/pull/3200#discussion_r573542034

**Comment by thisthat** [comment]
We need to verify if this ticket is still valid.
