### ISSUE TITLE
CLI: Replace current logging with logging framework

### ISSUE THREAD

**Issue by warber** [keptn/keptn#2763]
In order to have more standardized logging behavior both for the user and for developers as well as for automatic processing of the CLI output, we should switch to an established logging framework, instead of using our own logging facade. I propose to switch logging to [logrus](https://github.com/sirupsen/logrus) as it is widely used and 100% compatible with the golang log package.

**Definition of done**

- [ ] introduce logrus in CLI code for all log messages with appropriate log level
- [ ] make sure that processable CLI output is written to `std::out`
- [ ] adapt integration tests that might fail because of expecting old CLI outputs

**Comment by DarthBenro008** [comment]
Hey There!
Logrus looks like a nice package!
I do have some queries regarding this, when this is being implemented,
 1. Will be changing the codebase in `cli/package/logging/logging.go` and `cli/package/logging/log_printer.go` or will we be refactoring the whole cli to directly import and use the logger in thier packages?
 2. There _might_ be some disadvantages by using logrus as described [here](`cli/package/logging/logging.go`), I would like to suggest that we can make use of [zap](https://github.com/uber-go/zap), which is performance friendly and is also widely used and stable. 

Please let me know your thoughts on this!

**Comment by christian-kreuzberger-dtx** [comment]
@warber @bacherfl what's your opinion?

**Comment by warber** [comment]
ad1)  I would vote for refactoring the CLI. Well, it's not really a heavy refactoring but rather using `logrus` directly at places where we currently use our own logging struct. When we do this we should also pay attention on what are logs and what is regular output of the CLI. Also we should decide whether we want to use a global logger, or passing around instances of that logger. I am kind of more attracted to the first option.

ad2) I don't know `zap` so I cannot say much about it. From what I see it avoids stuff like reflection and does other tricks to gain better performance. However, my gut feeling tells me that we are fine with `logrus` though.

**Comment by christian-kreuzberger-dtx** [comment]
Thanks! I think `logrus` should be fine. Regarding deciding on having a global logger and passing it around vs. one logger per command/... I found this: https://le-gall.bzh/post/go/integrating-logrus-with-cobra/

Apparently we don't need an instance of logrus, we can just use it as it is?

**Comment by warber** [comment]
> Apparently we don't need an instance of logrus, we can just use it as it is?

Well, under the hood it uses an instantiation. Yes I would just use it "as is" like in the link you've posted and avoid passing around that thing.

**Comment by DarthBenro008** [comment]
Hey @warber @christian-kreuzberger-dtx ,

I think I am able to grasp the idea of shifting to a new logging framework, and yes even I agree on the fact that we should use logrus as is without passing it around, as it is designed and intended to be used like that, as a global logger.

I would really like to give this issue an try, if that's alright 😄

**Comment by warber** [comment]
@DarthBenro008 Sure, go for it. If you have questions during implementation, I am happy to help.
