### ISSUE TITLE
helm-service: Support for `deployment_strategy: user_managed`

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#2764]
The helm-service currently supports two deployment strategies:
- `direct`: Here the chart of the user is installed and additionally a VirtualService as well as a DestinationRule are generated in the `generated-chart` and also installed.
- `blue_green_service`: Here the chart of the user is installed as `canary`-version and additionally a second Deployment, Service, VirtualService, DestinationRules are generated in the `generated-chart` and also installed.

In order to disable the automatic resource generation (i.e. the generation of the `generated-chart`) as well as to overcome the dependency of having Istio installed on the cluster, this issue proposes to introduce a new deployment strategy named `user_managed`. 
In case the user chooses `user_managed` as deployment strategy, no `generated-chart` should be generated and installed.

Additionally, when the user selects `user_managed` as deployment strategy, there should not be any requirements for the used chart (i.e. the Helm chart had to consist of exactly 1 Deployment and 1 Service). 
The `helm-service` does not need this requirement for deployment strategy `user_managed` because it does not need to generate a `generated-chart`.

**Supported use cases:**
- The `helm-service` allows Keptn services that contain multiple Deployments and Services within one Helm-chart. The Helm-chart can even contain e.g. an Argo Rollout which can be used for B/G deployments or Canary releases.

**Restrictions:**
- In case the chart contains multiple Deployments or Services, the deployment strategies `direct` and `blue_green_service` are not supported.
- As the `helm-service` does not generate any Istio configuration, it cannot infer `deploymentURIsLocal` and `deploymentURIsPublic` which are used for e.g. testing. Those URLs can however be set by the user in the domain event.

**Tasks:**
- `onboard service` command in the CLI: Relax the check for the Helm-chart and only print a warning in case the onboarded chart cannot be used for deployment strategy `direct` or `blue_green_service`. Here we cannot decide which deployment strategy will be used.
- `helm-service` file `onboarder.go`: Remove the check whether the k8s service name matches the Keptn service name. In the generated VirtualServices, we use the name of the provided K8s service anyway.
- `helm-service` file `deployment_handler.go`:  Introduce the new deployment strategy `user_managed`
- `helm-service`: Introduce a check for Helm-chart requirements when `deployment_strategy` is equals to `direct` or `blue_green_service`. Therefore, move the `helm_validator.go` functionalities into the `kubernetes-utils` so that it can be used by the CLI as well as the `helm-service`.
- Update and extend docs

**Comment by checkelmann** [comment]
I like the idea of the user-managed chart. We are using some helm charts within our Environment which is creating two deployments, two services, and one ingress for example, and we don't have any service mesh in place right now. This would help us a lot in utilizing keptn for deployments and not only quality gates. 

Sure, we can not use any kind of blue green or canary deployment with this solution, but it's better than nothing ;)

**Comment by christian-kreuzberger-dtx** [comment]
I think we need to be careful with the naming and the use-cases. Our existing helm-service does not only apply helm manifests, but also istio  manifests. In addition, it handles certain remediation use-cases. At the same time our helm-service updates things in the git repo.

I think the proposed changes should be included in a completely new independent service, and our existing (simple-)helm-service should be renamed to helm-gitops-service.

**What if we merge both services**

I believe we would confuse end-user as to why "user_managed" deployments can not be used for quality-gates, istio routing, remediation actions, etc...

**Comment by checkelmann** [comment]
> I believe we would confuse end-user as to why "user_managed" deployments can not be used for quality-gates, istio routing, remediation actions, etc...

Just for my understanding, what do you mean by "can not be used for quality gates"? If you refer to the tags for the deployment like stage, it would be possible to have a user-managed helm chart, where I add some placeholder for my DT_CUSTOM_PROPS like I'm doing in my "manual" deployments right now, and if the helm service could just replace this values it would be working, right?

Unfortunately, if this is not possible, we can not keptn for our deployments in the future.

As an example please take a look at my GitLab Demo:
https://gitlab.com/checkelmann/keptn-demo/-/blob/master/chart/templates/deployment.yaml#L44

Here I'm overwriting my keptn tags with some chart values which I'm passing over via helm install. 
```
"keptn_project={{ .Values.ci_project_name }} keptn_service={{ .Values.ci_service_name }} keptn_stage={{ .Values.ci_environment_slug }} DEPLOYMENT_GROUP_NAME={{ .Values.ci_project_name }}-{{ .Values.ci_service_name }}-{{ .Values.ci_environment_slug }} 
 keptn_deployment=direct"
```

**Comment by christian-kreuzberger-dtx** [comment]
Thanks @checkelmann  for this example. You're right, I can overwrite those variables.

My statement is incomplete, I wanted to state that the existing quality-gate integration will need some additional work (as we kind of rely on the `keptn_deployment` tag for dynatrace and prometheus), but I guess that's doable, as you have shown.
