### ISSUE TITLE
Timeout issue in Keptn

### ISSUE THREAD

**Issue by SaveethaRavi** [keptn/keptn#2769]
Hi team,

We are facing issue timeout issue, while running the keptn commands in AKS cluster. 

We would have reached our organization internal kubernetes team on this issue. We received feedback like this issue is from application end. So I have raised here.

Could you please let me know, how the connection established between Keptn and Istio? This issue is anything related to this?

Which causes timeout issue? Whether it routes request to Istio or not?

<img width="659" alt="TimeoutError" src="https://user-images.githubusercontent.com/57527241/101468975-20878100-396a-11eb-97e9-3c60ee942412.PNG">
[keptn-support-archive042666792.zip](https://github.com/keptn/keptn/files/5658463/keptn-support-archive042666792.zip)

"Error: Get http://20.65.16.223/api/configuration-service/v1/project/: dial tcp 20.65.16.223:80: i/o timeout"

Please refer attached files and screenshot for your reference and let me know what is the issue to resolve.

**Comment by jetzlstorfer** [comment]
From our first support session we know that Istio is not the problem as the routing is not done via Istio, but via a LoadBalancer in AKS. 
Connections to the Keptn cluster are very flaky. It seems that `keptn status` commands mostly succeed but commands like `keptn get projects` or `keptn get services` fail quite often, though not always.

![image](https://user-images.githubusercontent.com/7677092/101761406-65cbc000-3adc-11eb-9565-30bd9a2eabfb.png)
![image](https://user-images.githubusercontent.com/7677092/101761372-59dffe00-3adc-11eb-97f8-e732c7567bbf.png)

We already tried to connect to the cluster via a Linux VM as well as via the machine of the user.

Further investigation of why the timeout occurs is needed.

**Comment by SaveethaRavi** [comment]
Hi team,

Any update on this issue? 

Regards,
Saveetha.R
