### ISSUE TITLE
Highchart Chart/Heatmap values appear rotated

### ISSUE THREAD

**Issue by mark-dt** [keptn/keptn#2773]
Your issue may already be reported! Please search on the [issue tracker](https://github.com/keptn/keptn/issues) before creating a new one.

**Environment**

* Client OS (e.g., Linux, OSX, Windows):
* Keptn Version (`0.7.2`):
* Kubernetes Cloud Provider (GKE):
* Kubernetes version (`v1.19.4`):

**Affected Component**

* [ ] Docs
* [ ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [x] Bridge
* [ ] Gatekeeper
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**

Values on the Evaluation chart and heatmap appear rotated

**To Reproduce**

Open a heatmap or chart and see values are rotated, please see attached screenshot

**Expected behavior**

Values should not appear rotated

**Current behavior**

Values appear rotated

**Screenshots**

![image](https://user-images.githubusercontent.com/70218474/101638691-a66d0000-3a2e-11eb-8580-bbb152b986e0.png)

**Additional context**

I believe this should fix the issue:
```
diff --git a/bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts b/bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts
index d2e0be6b..18343244 100644
--- a/bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts
+++ b/bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts
@@ -82,7 +82,7 @@ export class KtbEvaluationDetailsComponent implements OnInit, OnDestroy {
     xAxis: {
       type: 'category',
       labels: {
-        rotation: -45
+        rotation: 0
       }
     },
     yAxis: [
@@ -132,7 +132,7 @@ export class KtbEvaluationDetailsComponent implements OnInit, OnDestroy {
       categories: [],
       plotBands: [],
       labels: {
-        rotation: -45
+        rotation: 0
       },
     }],

```

**Comment by johannes-b** [comment]
Hi @mark-dt, 
thanks for being so proactive and that you already filed a PR for that.
We intentionally added the rotation of the label since the label can take any string value. Hence it felt better for us to have it slightly rotated.  

Can you please post a screenshot of your change and then we will ask the community for the preferred approach?

**Comment by mark-dt** [comment]
Hi @johannes-b,
I see, I was not aware this was implemented intentionally. It just looked strange to me and some of my colleagues and I just thought this may have been a mishap.
The strings below the chart can indeed get long but because they include the full date. Maybe the time is already enough since the date can be found on some more place in the same tile, then we could leave the rotation and have it just horizontally ?
![image](https://user-images.githubusercontent.com/70218474/102213611-46b3a080-3ed7-11eb-9a59-bd893cba6687.png)
