### ISSUE TITLE
CLI: The <service-name> argument of the "keptn onboard" command is useless

### ISSUE THREAD

**Issue by warber** [keptn/keptn#2788]
The `keptn onboard` command expects the service name to be passed as a command argument, e.g., `keptn onboard my-service --chart=./carts-db --project=myproject`. However, the service name is also specified in the chart and needs to be the same as defined there. If it's not you get an error message:

```
Provided Keptn service name "my-service" does not match Kubernetes service name "carts-db"
Error: The provided Helm chart is invalid. Please checkout the requirements
```
Hence, the service name as an argument is redundant and useless.

As a first step, to maintain backwards compatibility, it shall be *ignored* and a warning message shall indicate that the service name command argument will be removed in future releases.

**Comment by christian-kreuzberger-dtx** [comment]
> Hence, the service name as an argument is redundant and useless.

Kind of agree on the redundancy. But I disagree on it being useless and on removing the argument.

Pre-requesit: The service-name is also used as the directory name in the git config repo of the project.

In that sense, consider my arguments:

1. You wouldn't want to create a service without specifying a name, hence `keptn create service` requires the name, and so should `keptn onboard service`.
2. The restriction of the service name comes from `helm-service`, not Keptn itself. If we replace `helm-service` with something else, the `onboard service` option might need the argument again.
3. Thinking on step ahead, what if we ever want to onboard a service of an existing git config repo?

In the end, `keptn onboard service` is really just a convenience wrapper for `keptn create service` and "onboard the service using helm". I would actually go as far and say that we should not use it as a wrapper, and Keptn itself should not distinguish between onboarded or created services. This should be controlled via Uniform and Shipyard. Hence, eventually, we will not need `keptn onboard service`.

Let's hear some more opinions on that though.

**Comment by warber** [comment]
> I would actually go as far and say that we should not use it as a wrapper, and Keptn itself should not distinguish between onboarded or created services. This should be controlled via Uniform and Shipyard. Hence, eventually, we will not need keptn onboard service.

:+1: totally agree on this :)
