### ISSUE TITLE
Welcome screen in bridge & create project

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#2815]
I'd love to see a welcome screen in the bridge that clearly shows my next steps. 
The screen should explain (minimal version):
1. how to create a new project
1. how to onboard a service
1. how to enable a quality gate for it

![image](https://user-images.githubusercontent.com/7677092/102333247-71f8c700-3f8d-11eb-882b-fdef2d9bb638.png)

Besides, a dedicated predefined section of "**demo projects**", i.e., some demo data in the bridge, should help the user to see how a successfully created project can look like. These demo projects should contain
- project for quality gates with some sample evaluation to take a look at
- project for auto-remediation with some remediation actions to investigate
- project for multi-stage delivery with Keptn + quality gates

Also, if I already have some projects created, it would be great to reuse this screen behind a "create new project" button and again display it when the user clicks on this.
![image](https://user-images.githubusercontent.com/7677092/102325781-de6ec880-3f83-11eb-9cc1-3dc40b2578b7.png)

Let's use this issue to discuss our ideas!

**Comment by johannes-b** [comment]
This is implemented by: https://github.com/keptn/keptn/issues/4493
