### ISSUE TITLE
JMeter Service: Allow dynamic loading of extensions

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#2832]
Follow up of #2552 

In PR #2825 @grabnerandi has implemented variant 1 of #2552, where he included an extension statically in the Docker Image.

The scope of this issue is to make this dynamic, e.g., by including it in the configuration repo. Original text below.

> 
> Another option could be to allow our Keptn users to upload their extensions to the Keptn Project Configuration Repo. I would suggest to upload them on the master/main branch into a directory called jmeter/lib/ext. The Keptn JMeter Service can then pull all extensions before launching JMeter and copy them into the lib/ext directory.
> This solution would however require the Keptn Configuration API to provide an option to get the list of all files in a directory which is currently not possible. Without that capability its not possible to know which files have been uploaded

**Comment by thisthat** [comment]
JMeter has been moved out of this repo
