### ISSUE TITLE
GitFlow branching strategy for all keptn projects

### ISSUE THREAD

**Issue by dirkwall** [keptn/keptn#286]
- https://datasift.github.io/gitflow/IntroducingGitFlow.html
- master holds stable code
- development is done in a `develop` branch
- rest according to the document provided in the link

**Comment by johannes-b** [comment]
- [ ] keptn
  - [ ] `develop branch`
- [ ] github-service
  - [ ] `develop branch`
- [ ] jenkins-service
  - [ ] `develop branch`
- [ ] servicenow-service
  - [ ] `develop branch`
- [ ] keptn.github.io
  - [ ] `develop branch`
- [ ] pitometer-service
  - [ ] `develop branch`
- [ ] pitometer
  - [ ] `develop branch`
- [ ] pitometer-grader-thresholds
  - [ ] `develop branch`
- [ ] pitometer-source-dynatrace
  - [ ] `develop branch`
- [ ] pitometer-source-prometheus
  - [ ] `develop branch`

**Comment by johannes-b** [comment]
To continue working on this issue, the #327 issue has to be completed. Afterwards, the branching strategy according to the GitFlow approach for the following repos need to established: 
[ ] auth 
[ ] control 
[ ] event-broker 
[ ] event-broker-ext 
[ ] install
