### ISSUE TITLE
CLI & Bridge: Automatically determine doc version

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#2863]
From https://github.com/keptn/keptn/pull/2862

We are setting the version of the docs like this:
https://github.com/keptn/keptn/blob/d0d96e79fbde9377c173ade3cef4bc21984ab0b2/cli/cmd/version.go#L46

And we use this to print doc URLs:
https://github.com/keptn/keptn/blob/da351d0a2fb39c2a6b66e1d5bd4c19d41f7326f3/cli/pkg/common/quick_access_instructions.go#L15

We are already setting the version of the CLI as a parameter during build:
```
go build -v -x -ldflags="-X 'main.Version=$VERSION'
```

Based on `main.Version` we can infer the version for the docs, as in `{MAJOR}.{MINOR}.x`.

# Definition of Done

- [ ] Doc Version String in version.go is automatically determined based on `main.Version` using the format `{MAJOR}.{MINOR}.x`

**Comment by johannes-b** [comment]
The same needs to be considered for the bridge. Some work in this regard has already been implemented by: https://github.com/keptn/keptn/issues/3205
