### ISSUE TITLE
Install Keptn Cli via Homebrew 

### ISSUE THREAD

**Issue by solidnerd** [keptn/keptn#2864]
**Is your feature request related to a problem? Please describe.**
As a mac user I want to install the cli via Homebrew.

```sh
brew tap keptn/keptn
brew install keptn-cli
```

**Describe the solution you'd like**

1. Create a repository in `keptn/homebrew-keptn` 

This is required for doing the `brew tap` command or we need to see how to get a formula into the upstream.

2. Create a homebrew formula to build the keptn cli.

**Describe alternatives you've considered**
/

**Additional context**
/

If you need help here. I would like to contribute to the related steps. I need mostly only the repository so that I can start the work and testing it.

**Comment by christian-kreuzberger-dtx** [comment]
Hi,

thanks for the suggestion. I looked at the docs for homebrew and I see that there is two options, either adding it as a formula (which then requires it to be compiled locally), or adding it as a cask.

Knowing that compiling Go programs might not be something everyone is fancy to do (not everyone has go installed), I'm wondering if it would be easier to just add Keptn as a *Cask*  to the homebrew-cask git repo?
A good example for a cask would be firefox: 
https://github.com/Homebrew/homebrew-cask/blob/master/Casks/firefox.rb

This essentially does not require a repository to be created on our side. In addition, it would allow users to install Keptn using `brew install keptn` (without tap)

**Comment by solidnerd** [comment]
Hey @christian-kreuzberger-dtx, 
I also looked in the docs. From my understanding, we should rather use a formula.
> Homebrew Cask extends Homebrew and brings its elegance, simplicity, and speed to the installation and management of GUI macOS applications such as Atom and Google Chrome.

 I agree with you to try a first to get directly in the upstream repository for better UX.  In the case of formula, the Home would be than https://github.com/Homebrew/homebrew-core

It would also be better to recompile it because then we can also support `darwin/arm64` for the new M1 and multiple os. 

Here is a direct GoLang CLI Formula:

- https://github.com/Homebrew/homebrew-core/blob/master/Formula/glab.rb


For future maintenance, there is also a GitHub action for updating the formula. https://github.com/mislav/bump-homebrew-formula-action

**Comment by christian-kreuzberger-dtx** [comment]
Understood.

So going forward with the Formula, do you still need a separate repository to work on for now?

**Comment by solidnerd** [comment]
No, I think everything is fine :+1: . I'll respond when PR is created and ready for merge.

**Comment by christian-kreuzberger-dtx** [comment]
Nice, thanks!

**Comment by solidnerd** [comment]
@christian-kreuzberger-dtx  Here we go: https://github.com/Homebrew/homebrew-core/pull/67886

**Comment by christian-kreuzberger-dtx** [comment]
Nice, thanks. I've added a comment there ;) And we'll definately need an auto-update workflow that you linked.

**Comment by solidnerd** [comment]
Okay it was successfully deployed and is now available with

```sh
brew install keptn
```

**Comment by jetzlstorfer** [comment]
Great stuff @solidnerd - thanks for this contribution. Do you fancy to also present this in a Keptn developer meeting? :)
