### ISSUE TITLE
Extend CLI with remove-resource option

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#2867]
**Is your feature request related to a problem? Please describe.**
The CLI enables users to upload resources to the configuration repo but doesnt provide the corresponding remove option.
This makes it hard to write e.g: automation scripts that leverage the CLI

**Describe the solution you'd like**
Extend keptn cli with a "remove-resource" option which is the counterpart of "add-resource"

**Describe alternatives you've considered**
The API is an alternative and will be used in most use cases - however - there are users relying on the CLI and those are currently limited bc of the missing functionality

**Comment by christian-kreuzberger-dtx** [comment]
I've removed the *good first issue* label for now, and I've added the *ready-for-refinement* label, as we need to talk about this in our backlog refinement.

In my opinion we need stop wrapping git commands with Keptn. Long term, adding and deleting a file should be handled via the git upstream repo by using `git add` and `git rm` respectively (or via a Git UI).
