### ISSUE TITLE
Ensure Bridge shows configuration-change events and its content

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#2872]
In Keptn 0.7.x, we used the CLI to send a config-change which looked as follows:
![image](https://user-images.githubusercontent.com/56065213/103229208-e5f28200-4932-11eb-8e2f-a20dd7ef972b.png)

```
{
  "contenttype": "application/json",
  "data": {
    "canary": {
      "action": "set",
      "value": 100
    },
    "eventContext": null,
    "labels": null,
    "project": "ck-sockshop",
    "service": "carts",
    "stage": "",
    "valuesCanary": {
      "image": "keptnexamples/carts:0.11.2"
    }
  },
  "id": "1d2d3a6b-400e-4b66-82b8-7e95ff997e83",
  "source": "https://github.com/keptn/keptn/cli#configuration-change",
  "specversion": "0.2",
  "time": "2020-12-15T16:41:03.443Z",
  "type": "sh.keptn.event.configuration.change",
  "shkeptncontext": "fcfb0581-84b6-4952-a0f4-de3a91b2f5a5"
}
```

For Keptn 0.8.x, the cloud-event has changed, and bridge shows literally nothing:
![image](https://user-images.githubusercontent.com/56065213/103229252-fa367f00-4932-11eb-85c7-63f059398688.png)
```
{
  "data": {
    "configurationChange": {
      "values": {
        "image": "docker.io/keptnexamples/carts:0.12.2"
      }
    },
    "deployment": {},
    "labels": null,
    "message": "",
    "project": "sockshop-dt",
    "result": "",
    "service": "carts",
    "stage": "dev",
    "status": ""
  },
  "id": "e563ab05-a4cf-4a58-98ed-115ad5e33431",
  "source": "https://github.com/keptn/keptn/cli#configuration-change",
  "specversion": "1.0",
  "time": "2020-12-28T16:26:12.576Z",
  "type": "sh.keptn.event.dev.artifact-delivery.triggered",
  "shkeptncontext": "a7a964e6-5fc1-445d-9b5d-8cd07700f49c"
}
```

The same is true for the environment screen, this is what it should look like:
![image](https://user-images.githubusercontent.com/56065213/103229430-45509200-4933-11eb-9965-51c180c33220.png)
And this is what it currently looks like:
![image](https://user-images.githubusercontent.com/56065213/103229454-526d8100-4933-11eb-8534-a6b3cf8170ca.png)

# Definition of Done
- [ ] Bridge shows image name and tag which is deployed / passed via cloud-event in "Services screen"
- [ ] Bridge shows image name and tag which is deployed / passed via cloud-event in "Environment screen"

**Comment by johannes-b** [comment]
This issue should resolve: #2740
