### ISSUE TITLE
Extend keptn auth with more doc output to explain how to obtain token & endpoint

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#2877]
This could be an easy win for user experience. When doing a keptn auth the current output says 
```
Error: required flag(s) "api-token", "endpoint" not set
```

Would be better to reflect some of the documentation or at least point to the doc where we explain how to get token and endpoint
Here is a version that I think would help:
```
$ keptn auth
keptn auth requires api-token and endpoint.

For more information on how to obtain token and endpoint to go https://keptn.sh/docs/0.7.x/reference/cli/#authenticate-keptn-cli
```

**Comment by DarthBenro008** [comment]
I agree with this, we could also the same message that is displayed once keptn has been successfully setup in a cluster
```terminal
* To quickly access Keptn, you can use a port-forward and then authenticate your Keptn CLI:
 - kubectl -n keptn port-forward service/api-gateway-nginx 8080:80
 - keptn auth --endpoint=http://localhost:8080/api --api-token=$(kubectl get secret keptn-api-token -n keptn -ojsonpath={.data.keptn-api-token} | base64 --decode)

* Alternatively, follow the instructions provided at: https://keptn.sh/docs/0.7.x/operate/install/#authenticate-keptn-cli
```

The final result may end up as:

```terminal
$ keptn auth

keptn auth requires api-token and endpoint.

For more information on how to obtain token and endpoint to go https://keptn.sh/docs/0.7.x/reference/cli/#authenticate-keptn-cli

 Alternatively,To quickly access Keptn, you can use a port-forward and then authenticate your Keptn CLI:
 - kubectl -n keptn port-forward service/api-gateway-nginx 8080:80
 - keptn auth --endpoint=http://localhost:8080/api --api-token=$(kubectl get secret keptn-api-token -n keptn -ojsonpath={.data.keptn-api-token} | base64 --decode)

```

I believe this would easily improve user experience. Please feel free to suggest regarding the same.

I would like to contribute and work on this 😄

**Comment by jetzlstorfer** [comment]
Sounds good @DarthBenro008 , thanks for taking this one!

**Comment by DarthBenro008** [comment]
Hey There!

I was working on this issue and _might_ have stumbled on a potential bug.

My understanding is that in  `cli/cmd/auth.go` , the particular function below, checks for namespace, kubeconfig, and if there is more than 1 valid keptn installation is present.
https://github.com/keptn/keptn/blob/83d04b4285d5fae5942fd54e55f4a65996522b2c/cli/cmd/auth.go#L225-L254

However, when we call it at `line 158`, it won't throw an error if there is a valid keptn installation and hence would proceed and fail at line `line 168`
https://github.com/keptn/keptn/blob/83d04b4285d5fae5942fd54e55f4a65996522b2c/cli/cmd/auth.go#L156-L175


This causes the following issue, which isn't present in 0.7.x release:
```terminal
$ ./keptn auth
Error: Error in fetching the endpoint
It doesn't support ClusterIP & NodePort type service for fetching endpoint automatically
CLI is not authenticated
```
I would like to confirm if its an intended behaviour, because ideally we want it produce a message such as

```
$ keptn auth

keptn auth requires api-token and endpoint.

For more information on how to obtain token and endpoint to go https://keptn.sh/docs/0.7.x/reference/cli/#authenticate-keptn-cli

 Alternatively,To quickly access Keptn, you can use a port-forward and then authenticate your Keptn CLI:
 - kubectl -n keptn port-forward service/api-gateway-nginx 8080:80
 - keptn auth --endpoint=http://localhost:8080/api --api-token=$(kubectl get secret keptn-api-token -n keptn -ojsonpath={.data.keptn-api-token} | base64 --decode)
```

**Proposed Solution:** Run the function `smartKeptnCLIAuth()` once we confirm both the `api-token` and `endpoint` have been provided instead of running it when both the parameters are not provided.

Please feel free to correct me!


Additional Details:

Keptn CLI version:  develop
Codebase pulled from master branch, git head at 83d04b4285d5fae5942fd54e55f4a65996522b2c

**Comment by christian-kreuzberger-dtx** [comment]
@ankitjain28may @agrimmer any chance you can take a look at this?

**Comment by DarthBenro008** [comment]
So I took a closer look at the codebase, which mentioned this:

https://github.com/keptn/keptn/blob/b8ef56c833235450721b12edbaa46c9325726419/cli/cmd/auth.go#L57

It says _automatically fetch endpoint and api-token from kube context_

I realised that I shouldn't run the `smartKepthCLIAuth()` after ensuring both the parameters (api-token and endpoint) is received as shown [here](https://github.com/keptn/keptn/pull/3039#discussion_r567779607). Instead, we should write logic such that incase If either of the conditionals at `line 167` *OR* `line 179` are satisfied, then we must display the pretty message of asking the user to provide with both api-token and endpoint manually.

If both the conditions does not satisfy, then it means that the required parameters (api-token and endpoint) have already been smartly obtained.

https://github.com/keptn/keptn/blob/b8ef56c833235450721b12edbaa46c9325726419/cli/cmd/auth.go#L150-L185

Please feel free to correct me!

**Comment by christian-kreuzberger-dtx** [comment]
Pinging @agrimmer and @bacherfl for feedback on this

**Comment by ankitjain28may** [comment]
@grabnerandi Can you please point to the keptn CLI version you are using, keptn auth is smart enough to fetch the endpoints and API token automatically. If not it will show the proper error where it failed.

@DarthBenro008 I went through your proposed solution.
>  I realised that I shouldn't run the smartKepthCLIAuth() after ensuring both the parameters (api-token and endpoint) is received as shown here. Instead, we should write logic such that in case If either of the conditionals at line 167 OR line 179 are satisfied, then we must display the pretty message of asking the user to provide with both api-token and endpoint manually.
This is more appropriate, we should display the pretty message explaining the user both the error and commands to fetch the endpoint if it can't be fetched automatically.

**Comment by grabnerandi** [comment]
Hi. I am currently on 0.7.3
