### ISSUE TITLE
Update event traces of projects created with Keptn 0.7.x

### ISSUE THREAD

**Issue by bacherfl** [keptn/keptn#2889]
Since we will introduce a new event format in Keptn v0.8, we will need an upgrade mechanism for previously created projects and their event traces.

Approach for updating a project:

1. Retrieve all event traces (root events)

1. For each root event: Get all associated events based on the `shkeptncontext` property

1. Transform each event into a combination of `.started`, `.triggered` and `.finished` events. Note that also the event types are different, so we have to try to maintain as much data as possible.

In Keptn v0.7, a continuous delivery task sequence consists of the following events:

- `sh.keptn.event.configuration.change` (with image to be deployed)
- `sh.keptn.events.deployment-finished`
- `sh.keptn.events.tests-finished`
- `sh.keptn.internal.event.get-sli`
- `sh.keptn.internal.event.get-sli.done`
- `sh.keptn.events.evaluation-done`
- `sh.keptn.event.approval.triggered`
- `sh.keptn.event.approval.finished`
- `sh.keptn.event.configuration.change` (with canary action)

In Keptn 0.8, an equivalent sequence will contain the following events:

- `sh.keptn.event.deployment.(triggered|started|finished)`
- `sh.keptn.event.test.(triggered|started|finished)`
- `sh.keptn.event.evaluation.(triggered|started)` -> `sh.keptn.event.get-sli.(triggered|started|finished)` -> `sh.keptn.event.evaluation.triggered
- `sh.keptn.event.approval.(triggered|started|finished)`
- `sh.keptn.event.release.(triggered|started|finished)`

**Suggested approach:** similarly to the upgrade command for a project's shipyard file, provide an upgrade command to update the event traces, e.g. `keptn upgrade project <projectName> --events`

This command will transform each event trace as described above. Note that this command will modify existing data, so we have to make sure to create a backup of the previous events in case something goes wrong during the upgrade. This could be done by creating a copy of the collection containing the original events.

**User perspective:**

To upgrade the project, call

```
$ keptn upgrade project <projectName> --events

This will transform the event traces of project <projectName> to be compliant with Keptn 0.8.0. Do you want to continue?

y

All event traces of project <projectName> have been updated. You can inspect them at <bridge-url>. If you would like to restore the event traces to their previous state, execute 'keptn upgrade project <projectName> --events --restore'
```

If something goes wrong, and the user would like to restore the previous state:

```
$ keptn upgrade project <projectName> --events --restore

This will restore the previous format of the event traces of project <projectName>. This format will be compatible with Keptn 0.7.x, but not with 0.8.x. Do you want to continue?

y

Event traces of project <projectName> have been restored to their original state.
```

**Comment by johannes-b** [comment]
The `--restore` feature should be covered by an official backup/restore process.

**Comment by johannes-b** [comment]
This issue will not be implemented. 
Instead, Keptn 0.8.0 will provide this functionality: https://github.com/keptn/keptn/issues/2949
