### ISSUE TITLE
Merge jmeter feature from release-0.7.3-patch1 into master

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#2893]
With the `release-0.7.3-patch1` release, we have released a jmeter-related feature **JMeter Dynatrace OSS and Data File Support** as implemented here: https://github.com/keptn/keptn/pull/2825

To not lose this feature in Keptn 0.8, it has to be merged into master. At this point, it is not obvious whether a simple cherry-pick works or parts of the above-mentioned PR must be re-implemented based on the progress on `master`. 

**Definition of Done:**
- [ ] The jmeter feature (from https://github.com/keptn/keptn/pull/2825) is also available on `master`
- [ ] Validate that the feature works as expected (double-check with Andi)

**Comment by christian-kreuzberger-dtx** [comment]
We can try to cherry-pick the respective merge commit using
```
git cherry-pick d1f20d67f1de1ed4779d92cbc6083e39e08f0540
```
