### ISSUE TITLE
Change annotation `managed-by` for Keptn namespace

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#2894]
In testing out the new 0.8.0-alpha release, concerns about the name of the label/annotation for the namespace arose. 

The name of the annotation/label, which is `managed-by`, is misleading. The reason is that the recommendation of Kubernetes (see: 
https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels) says:
*  `app.kubernetes.io/managed-by` : `The tool being used to manage the operation of an application`

In the namespace in which Keptn is installed, no application is deployed. 

**To-be-discussed:**
- What is a proper name for the label?

**Comment by christian-kreuzberger-dtx** [comment]
For which deployments is this the case?
Keptn itself is installed using the following labels:

```
app.kubernetes.io/component=mongodb app.kubernetes.io/instance=keptn app.kubernetes.io/managed-by=Helmapp.kubernetes.io/name=mongodb app.kubernetes.io/part-of=keptn-keptn app.kubernetes.io/version=1 helm.sh/chart=mongodb-0.1.0
```

```
app.kubernetes.io/component=control-plane app.kubernetes.io/instance=keptn app.kubernetes.io/managed-by=Helm app.kubernetes.io/name=bridge app.kubernetes.io/part-of=keptn-keptn app.kubernetes.io/version=0.8.0-alphahelm.sh/chart=control-plane-0.1.0
```

And in my opinion this is exactly what it should be.

**Comment by johannes-b** [comment]
I think I need to clarify, it is not about the namespaces we create for a deployed application, but rather for the namespace we create for a Keptn deployment. The corresponding col is here: https://github.com/keptn/keptn/blob/master/cli/cmd/install.go#L215

There we set: `managed-by: keptn` for the Keptn namespace and this is not right.

**Comment by christian-kreuzberger-dtx** [comment]
Okay, I see. Though I still think that's okay, because we create the namespace using the `keptn` cli. 

But let's discuss this topic, I can see two discussion points here:
1. Why are we using `keptn.sh/managed-by` instead of `app.kubernetes.io/managed-by`? 
2. Should we set `managed-by` to `keptn` when we install it via the `keptn` CLI?

**Comment by johannes-b** [comment]
I think I was always a little bit blinded because I thought that we are using the label `app.kubernetes.io/managed-by` but in fact we are setting `keptn.sh/managed-by`. @christian-kreuzberger-dtx thanks for the hint!

- I think that we can leave the label as it is since we are using the prefix `keptn.sh` and not `app.kubernetes.io`

For me, two additional points arise: 
1. How can we set the flag, when installing Keptn via Helm chart? (see: https://keptn.sh/docs/0.8.x/operate/advanced_install_options/#advanced-install-options-install-keptn-using-the-helm-chart) 
  * When possible, should we move the label management from the CLI to the Helm chart (to cover both install options)?
2. We need documentation for that feature.
