### ISSUE TITLE
Keptn tabular cli output breaks automation with too long project, stage or service names

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#2899]
In some of my automation scripts I use the Keptn CLI to e.g: iterate over projects or services.
The problem though is that parsing the CLI output breaks as there is no space between columns when names get too long. See the following output

![image](https://user-images.githubusercontent.com/675886/104374395-2270d100-5522-11eb-8dd7-807f7e3e19fa.png)

This for instance breaks the following script that wants to just get the project names but ends up merging project name + creation date:
![image](https://user-images.githubusercontent.com/675886/104374517-46ccad80-5522-11eb-9f20-be4ab0a14cf9.png)

Automation can obviously be done through the API as well - but - I think this should be an easy fix which enables automation through the CLI as well

**Environment**
* Keptn Version (`keptn version`): 0.7.3

**Comment by christian-kreuzberger-dtx** [comment]
I agree about fixing the CLI. 

For automation however, I recommend using `keptn get projects -ojson`.

**Comment by johannes-b** [comment]
- Make sure that padding with 2 characters is set. 
- We set the column width based on the longest name (this is done automatically) (drawback: we can run into a line break)

**Comment by johannes-b** [comment]
When fixing this bug, please implement the issue: https://github.com/keptn/keptn/issues/2908
