### ISSUE TITLE
Create stage-timeline component

### ISSUE THREAD

**Issue by ermin-muratovic** [keptn/keptn#2907]
When clicking on a sequence, the details are displayed next to the sequence list. The sequence list is then shown in one stacked column, with the selected sequence on top. The stages which the sequence went through, should be displayed on top in a timeline with stage name and start time of the task sequence in this stage.

**Component behavior:**
* Display stages in a timeline with stage name and start time of the task sequence in this stage.
* If the sequence is still active for a stage, show a loading icon 
* By default, the last stage of the sequence is selected, e.g., dev - staging - prod --> prod is selected, but the component should allow to select any of the displayed stages by clicking on the element

This component is required for #2627

![100993577-df503500-3555-11eb-8345-ff2620e5e787-stages](https://user-images.githubusercontent.com/6098219/105020517-ad345d00-5a47-11eb-85ec-2712b0f43a73.png)

**Comment by johannes-b** [comment]
Is part of: #2627
