### ISSUE TITLE
Add the pitometer JSON results to keptn logs

### ISSUE THREAD

**Issue by robertjahn** [keptn/keptn#291]
**Is your feature request related to a problem? Please describe.**
Currently, the keptn logs just show pass/fail for the pitometer processing

**Describe the solution you'd like**
Add the full JSON result output.  And show the repo/file path used as input.

**Describe alternatives you've considered**
None

**Additional context**
This is example of all you get now in logs:  {"keptnContext":"f5cddaf3-120b-4bd0-be4b-0e1b689ac704","logLevel":"INFO","message":"Evaluation passed: false","keptnService":"pitometer-service"}

**Comment by bacherfl** [comment]
fixed in version 0.1.1 of pitometer service
