### ISSUE TITLE
Discussion for go-utils: Provide an interface to easily send cloudevents

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#2911]
Right now sending CloudEvents is handled differently by almost every microservice we have. They all use [go-utils Keptn Handler SendCloudEvent function](https://github.com/keptn/go-utils/blob/51257d664f819c10230a329ff458f82f0fe7075e/pkg/lib/v0_2_0/events.go#L70), but the handling around it is very different all the time, e.g.: 

https://github.com/keptn/keptn/blob/b2a14418997bebf87aeaa0e054189b1c0eb8b7b3/api/utils/event.go#L26-L50

https://github.com/keptn/keptn/blob/558710292b2433f9467957daf0a7aa6d60e5c9fb/shipyard-controller/common/keptn_helpers.go#L83-L110

https://github.com/keptn/keptn/blob/b9eca15c3fa4ed35ecfc1f284d9a4958ddac604f/lighthouse-service/event_handler/common.go#L115-L130

https://github.com/keptn-contrib/unleash-service/blob/4cf382c522dedee37a55a52ee0fdd15a09c354f5/pkg/event_handler/action_triggered_handler.go#L107-L130

https://github.com/keptn/keptn/blob/f5d2838d8d0d0ba6a3740dbd12d945f16692a385/jmeter-service/main.go#L321-L350

https://github.com/keptn-contrib/dynatrace-service/blob/2c84ce11000e70ef635ff96871839655d4f71e2c/pkg/event_handler/configure_monitoring.go#L165-L170

As you can see, there is a lot of code duplication, which makes it harder to maintain the code. If we just add a single attribute, we will have to adapt it everywhere.

Within this issue we will be proposing a change such that most cases for sending CloudEvents are covered, and should only be a single function call.

**If you like an approach, please use the react-emjois e.g., :+1: on the comment**
**Please don't discuss/comment on the proposed changes in this issue (it will get cluttered with comments), only propose new ones. We can openly discuss them in a Dev meeting**

**Comment by christian-kreuzberger-dtx** [comment]
IMHO the biggest issues with our current implementation are:
* setting triggeredid requires the incomingCloudEvent (this is something KeptnHandler should store!)
* `shkeptncontext` also always needs to be set, though this is already stored in KeptnHandler
* `SetDatacontentType(cloudevents.ApplicationJSON)` - this should really just be the default provided by KeptnHandler - if anything, the user can overwrite it, but I don't see a reason why
* Setting the source (e.g., dynatrace-service, helm-service, jmeter-service, ...) is also something that could be automatically handled by KeptnHandler

This is what it should feel like for the developer:

**one time setup for KeptnHandler:**
```
var keptnOptions = keptn.KeptnOpts{}

keptnOptions.ConfigurationServiceURL = env.ConfigurationServiceUrl
keptnOptions.EventBrokerURL = env.EventBrokerUrl

// initialize Keptn Handler with incomingEvent and keptnOptions
myKeptn, err := keptnv2.NewKeptn(&incomingEvent, keptnOptions)
if err != nil {
    return errors.New("Could not create Keptn Handler: " + err.Error())
}
```

**sending a CloudEvent**
```
// generate an action.started event
actionStartedData := keptnv2.ActionStartedEventData{}

actionStartedData.EventData = incomingEventData.EventData
actionStartedData.Status = keptnv2.StatusSucceeded // alternative: keptnv2.StatusErrored
actionStartedData.Result = keptnv2.ResultPass      // alternative: keptnv2.ResultFailed

// Create CloudEvent
startedEvent := cloudevents.NewEvent()
startedEvent.SetType(keptnv2.GetStartedEventType(keptnv2.ActionTaskName))
startedEvent.SetData(cloudevents.ApplicationJSON, actionStartedData)

// send action.started event
myKeptn.SendCloudEvent(startedEvent)

```

For this to work, `SendCloudEvent` and KeptnHandler needs to be a bit smarter, as in:
* `KeptnHandler` should store the `incomingEvent` (or its event-id) and automatically set it as `triggeredid` in `Keptnhandler.SendCloudEvent`: `event.SetExtension("triggeredid", k.incomingEvent.Context.GetID())`
* `KeptnHandler.SendCloudEvent` needs to automatically set `shkeptncontext` if it is available: `event.SetExtension("shkeptncontext", k.KeptnContext)`
* `KeptnHandler.SendCloudEvent` needs to automatically set the data content type (if it's not already set) `SetDatacontentType(cloudevents.ApplicationJSON)`
* `KeptnHandler.SendCloudEvent` should automatically set source (if it's not already set) based on the following logic
  * We could introduce a configuration in `keptnOptions` that specifies serviceName
  * If this is empty, it could try to determine it based on the executeable-name (e.g., using `os.Executeable()`)
  * If this is still empty, it should fail and ask the user to specify `source` by themselves
* `KeptnHandler.SendCloudEvent` should automatically generate IDs if they are not set, e.g., `event.SetID(uuid.New().String()) `
* `Keptnhandler.SendCloudEvent` should automatically set the time if it's not already set, e.g., `event.SetTime(time.Now()) `

**Comment by bacherfl** [comment]
I fully agree with your suggestion. One thing we have to consider as well is how to best support the initial sending of an event - i.e., sending an event via the `KeptnHandler` when we do not have an incoming CloudEvent as a base. An example for that would be the `api-service` where we provide an HTTP endpoint to create a new evaluation. But this should be manageable by checking if the `incomingEvent` is `nil` when the `KeptnHandler` is initialized.

**Comment by johannes-b** [comment]
Having a centralized approach for sending CloudEvents is also the basis for https://github.com/keptn/keptn/issues/2913. 
IMHO, both ideas go well hand-in-hand and help us reducing complexity and improve code maintainability for all Keptn-services.

**Comment by christian-kreuzberger-dtx** [comment]
Based on #3035 I have implemented the changes in keptn-service-template-go, and it feels really good now, e.g.:
```golang
func HandleActionTriggeredEvent(myKeptn *keptnv2.Keptn, incomingEvent cloudevents.Event, data *keptnv2.ActionTriggeredEventData) error {
	log.Printf("Handling Action Triggered Event: %s", incomingEvent.Context.GetID())
	log.Printf("Action=%s\n", data.Action.Action)

	// check if action is supported
	if data.Action.Action == "action-xyz" {
		// -----------------------------------------------------
		// 1. Send Action.Started Cloud-Event
		// -----------------------------------------------------
		myKeptn.SendTaskStartedEvent(data, ServiceName)

		// -----------------------------------------------------
		// 2. Implement your remediation action here
		// -----------------------------------------------------
		time.Sleep(5 * time.Second) // Example: Wait 5 seconds. Maybe the problem fixes itself.

		// -----------------------------------------------------
		// 3. Send Action.Finished Cloud-Event
		// -----------------------------------------------------
		myKeptn.SendTaskFinishedEvent(&keptnv2.EventData{
			Status: keptnv2.StatusSucceeded, // alternative: keptnv2.StatusErrored
			Result: keptnv2.ResultPass, // alternative: keptnv2.ResultFailed
			Message: "Successfully sleeped!",
		}, ServiceName)

	} else {
		log.Printf("Retrieved unknown action %s, skipping...", data.Action.Action)
		return nil
	}
	return nil
}
```

This hides the implementation details of keptn send cloud-event and makes it really easily accessible for the developer. Therefore I'm closing this discussion as resolved.
