### ISSUE TITLE
Discussion for go-utils: Easier way of generating .started/.status.changed/.finished events

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#2913]
Right now generating a .started, .status.changed or .finished event is quite tedious:

E.g., if `incomingEvent` is an `action.triggered` event, it takes multiple lines of code to just send a `.started` event (which means that the service acknowledges that it has started execution for this .triggered event):

```golang
// sh.keptn.event.action.triggered
if incomingEvent.Type() == keptnv2.GetTriggeredEventType(keptnv2.ActionTaskName) {
    log.Printf("Processing Action.Triggered Event")
    
    data := &keptnv2.ActionTriggeredEventData{}
    parseKeptnCloudEventPayload(event, data)

    // generate an action.started event
    actionStartedData := keptnv2.ActionStartedEventData{}
    
    actionStartedData.EventData = data.EventData
    actionStartedData.Status = keptnv2.StatusSucceeded // alternative: keptnv2.StatusErrored
    actionStartedData.Result = keptnv2.ResultPass      // alternative: keptnv2.ResultFailed
    
    // Convert To CloudEvent
    startedEvent := cloudevents.NewEvent()
    startedEvent.SetType(keptnv2.GetStartedEventType(keptnv2.ActionTaskName))
    startedEvent.SetData(cloudevents.ApplicationJSON, actionStartedData)
    
    // send cloud-event / https://github.com/keptn/keptn/issues/2911
    myKeptn.SendCloudEvent(startedEvent)

    // continue to process the event, e.g., executing a remediation action
    // ...

    // generate an action.finished event
    actionFinishedData := keptnv2.ActionFinishedEventData{}
    
    actionFinishedData.EventData = data.EventData
    actionFinishedData.Status = keptnv2.StatusSucceeded // alternative: keptnv2.StatusErrored
    actionFinishedData.Result = keptnv2.ResultPass      // alternative: keptnv2.ResultFailed
    actionFinishedData.Message = "Successfully executed action xyz!"
    
    // Convert To CloudEvent
    finishedEvent := cloudevents.NewEvent()
    finishedEvent.SetType(keptnv2.GetFinishedEventType(keptnv2.ActionTaskName))
    finishedEvent.SetData(cloudevents.ApplicationJSON, actionFinishedData)

    // send cloud-event / https://github.com/keptn/keptn/issues/2911
    myKeptn.SendCloudEvent(finishedEvent)
}
```

Given that the focus of implementation should be the part where it says
```
    // continue to process the event, e.g., executing a remediation action
    // ...
```

and not the creation of CloudEvents, we should ease the handling for creating and sending Started/Finished events.
In addition, some microservices have already started doing that, and have created helper functions for doing this:

https://github.com/keptn-sandbox/echo-service/blob/a90207bc119c0aca18368985c7bb80dea47309e9/cmd/eventhandling/event_processor.go#L81-L131

but in the end, every service seems to have its own utility functions that help in generating and sending cloud-events for started and finished ...

**If you like an approach, please use the react-emjois e.g., :+1: on the comment**
**Please don't discuss/comment on the proposed changes in this issue (it will get cluttered with comments), only propose new ones. We can openly discuss them in a Dev meeting**

**Comment by christian-kreuzberger-dtx** [comment]
IMHO we should provide utility functions in KeptnHandler that allow sending a `.started`, `.status.changed`, and `.finished` event with a single line of code, which should eventually reduce above code example to

```golang
// sh.keptn.event.action.triggered
if incomingEvent.Type() == keptnv2.GetTriggeredEventType(keptnv2.ActionTaskName) {
    log.Printf("Processing Action.Triggered Event")
    
    data := &keptnv2.ActionTriggeredEventData{}
    parseKeptnCloudEventPayload(event, data)

    // send an action.started event
    err := keptn.SendTaskStartedCloudEvent(incomingEvent, keptnv2.StatusSucceeded, keptnv2.ResultPass, "", keptnv2.ActionStartedEventData{})

    if err != nil { ... } 

    // continue to process the event, e.g., executing a remediation action
    // ...

    // send an action.finished event
    err := keptn.SendTaskFinishedCloudEvent(incomingEvent, keptnv2.StatusSucceeded, keptnv2.ResultPass, "Successfully executed action xyz!", keptnv2.ActionFinishedEventData{})

    if err != nil { ... } 
}
```

Whereas we would need to implement the following functions in `KeptnHandler`:

* `SendTaskStartedCloudEvent`
* `SendTaskStatusChangedCloudEvent`
* `SendTaskFinishedCloudEvent`

Regarding the function signature, I beleive that they require
* the `incomingEvent` (actually, this could be taken from KeptnHandler depending on the implementation of https://github.com/keptn/keptn/issues/2911 )
* `status` (e.g.,  `keptnv2.StatusSucceeded`)
* `result` (e.g., `keptnv2.ResultPass`)
* `message` 
* Event Payload, e.g., `keptnv2.ActionFinishedEventData{}`, or `interface{}`?

I believe my proposed change in combination with #2911 will reduce code complexity and improve code maintenability for all microservices. 
In addition, this will help keptn-contrib/keptn-sandbox service maintainers to adapt to Keptn 0.8.0 without having to write a lot of new code.

**Comment by johannes-b** [comment]
Really like the idea of having a one-liner to send a `started`/`status.changed`/`finished` event. This supports the adoption of Keptn-services and improves maintainability when we are under the control of these helper functions. 

Just for my understanding, the mentioned `KeptnHandler` module is part of `go-utils` or the `keptn-service-template-go`? (I hope for `go-utils` ;) )

What would be the concrete follow-up issue when we all agree on going this way?

**Comment by christian-kreuzberger-dtx** [comment]
This is being implemented by @bacherfl , so I'm closing this discussion. Thanks everyone!
