### ISSUE TITLE
API allows creating projects with special characters while CLI does not - leads to issues

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#2914]
Check the following screenshot. This project was created by accident by using the Keptn API. the CLI would never allow this as it does a name sanity check. We should enforce the same checks on the API because this project can now no longer be deleted

![image](https://user-images.githubusercontent.com/675886/104707955-654ac880-571d-11eb-943d-35fd0ed20dcb.png)

**Environment**
* Keptn Version (`keptn version`): 0.7.3

**Comment by johannes-b** [comment]
In Keptn 0.8 (current master) this is already addressed:
- [ ] Please check if the code is removed from the CLI (we do not want to duplicate the code (the check) should be moved) 
- [ ] Please check the error message that should contain the chars that are allowed (please see the function validateKeptnEntityName in go-utils)
