### ISSUE TITLE
go-utils: Deprecate event-broker, introduce better error handling for failed SendingCloudEvents

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#2919]
For Keptn 0.8.0, do we still need event-broker as a config option in go-utils (in keptnOptions)?
As far as I know we are not using event-broker anymore, but go-utils still refers to it as a Keptn Configuration Option and uses it somehow...

I just ran into the problem that my cloudevents would not appear in Keptn, and the reason was that I have set eventbroker in my service.yaml manifest to
```
          env:
            - name: EVENTBROKER
              value: 'http://event-broker/keptn'
```

Also, I did not get an error message when using keptnHandler.SendCloudEvent.

**Comment by johannes-b** [comment]
Clean-up task:
- [ ] Please check the manifests of keptn/keptn whether there is an env for the event broker. If there is, please remove it.
