### ISSUE TITLE
The rollback of blue/green deployment following a pitometer 'fail' status fails to find the istio-virtual-service YAML file

### ISSUE THREAD

**Issue by robertjahn** [keptn/keptn#292]
**Describe the bug**
The rollback of blue/green deployment following a pitometer 'fail' status fails to find the istio-virtual-service YAML file, thus stopping the "evaluation_done" pipeline

**To Reproduce**

Failure is because the YAML files for the keptn project are in "camelCase" and the jenkins job is looking for actual name.  In my scenario the service names is "front-end".   Project Yaml his ```istio-virtual-service-frontEnd.yaml``` but Jenkins job looking for ```istio-virtual-service-front-end.yaml```

1. run a build where the pitometer result is a fail.  Here is sample message.
```
{"keptnContext":"f5cddaf3-120b-4bd0-be4b-0e1b689ac704","logLevel":"INFO","message":"Sending event: {\"id\":\"e1fb220a-180a-46a3-af46-f0bbeb10e577\",\"specversion\":\"0.2\",\"time\":\"2019-04-26T12:58:57+00:00\",\"datacontenttype\":\"application/json\",\"shkeptncontext\":\"f5cddaf3-120b-4bd0-be4b-0e1b689ac704\",\"data\":{\"githuborg\":\"jahn-keptn-orders\",\"project\":\"orders-project\",\"deploymentstrategy\":\"blue_green_service\",\"stage\":\"staging\",\"service\":\"front-end\",\"image\":\"10.23.246.81:5000/orders-registry/front-end\",\"tag\":\"1-3\",\"evaluationpassed\":false},\"type\":\"sh.keptn.events.evaluation-done\"}","keptnService":"pitometer-service"}
```

2. the "evaluation_done" jenkins job runs.  It then attempts to update the manifest file and can't find it, thus failing the job.

```+ cd orders-project
+ git checkout staging
Branch 'staging' set up to track remote branch 'staging' from 'origin'.
Switched to a new branch 'staging'
[Pipeline] sh
+ cd orders-project
+ sed -i 's#weight: 0#weight: swap_100#' helm-chart/templates/istio-virtual-service-front-end.yaml
sed: helm-chart/templates/istio-virtual-service-front-end.yaml: No such file or directory
```

**Expected behavior**
Job will find the YAML file for the service.

**Screenshots**
![image](https://user-images.githubusercontent.com/24907089/56816226-17878180-6811-11e9-800b-3276be2daf19.png)

![image](https://user-images.githubusercontent.com/24907089/56816880-6550b980-6812-11e9-979e-66d41d9f2bab.png)

**Environment**
Using ```git clone --branch release-0.2.x https://github.com/keptn/keptn``` as of 4-25-2019

**Additional context**

**Comment by johannes-b** [comment]
Before working on this issue, I will work on #295 since then it is easier to finish this one.

**Comment by johannes-b** [comment]
The upcoming release of the jenkins-service can deal with service names that contain a hyphen. For example, carts-service > Log file from "evaluation_done" pipeline:
```
Switched to a new branch 'staging'
[Pipeline] sh
+ cd sockshopxy
+ sed -i 's#weight: 0#weight: swap_100#' helm-chart/templates/carts-service-istio-virtual-service.yaml
[Pipeline] sh
+ cd sockshopxy
+ sed -i 's#weight: 100#weight: 0#' helm-chart/templates/carts-service-istio-virtual-service.yaml
[Pipeline] sh
+ cd sockshopxy
+ sed -i 's#weight: swap_100#weight: 100#' helm-chart/templates/carts-service-istio-virtual-service.yaml
```
