### ISSUE TITLE
go-utils: Remove dependency on old Cloud-Events library

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#2922]
From [Slack](https://keptn.slack.com/archives/CGS63H8G6/p1610620692000300)

We use different verisons of cloudevents-sdk in go-utils. I'm not sure if this is problematic, but it looks wrong:
 
https://github.com/keptn/go-utils/blob/3a846009dff4479b1dde64f5f2f0237cbbe34758/go.mod#L6-L7

Can we reduce this such that we only use the newest/latest v2 version?

**Comment by bacherfl** [comment]
I think this dependency can be removed now. We left it in there in earlier versions because of backwards compatibility needed for Keptn v0.7.x

**Comment by warber** [comment]
will be done as part of #2830
