### ISSUE TITLE
Improve mongodb datastore performance

### ISSUE THREAD

**Issue by bacherfl** [keptn/keptn#2925]
Based on the outcome of the performance investigation reported in PR #2812, we can take some measures to improve the performance of the mongodb/mongodb-datastore to avoid performance issues in case the number of events within a project has grown to a certain point.

On the API-side, the following enhancements have shown a promising impact:

 - Collection *project-rootEvents*: Add an index for data.service
 - Collection *project*: Add indexes for data.service and shkeptncontext

On the client side, we need to avoid sending too many requests at once - i.e., by only loading root events for a service when the user has clicked on that service

**Comment by johannes-b** [comment]
For the Bridge, the issue is here: https://github.com/keptn/keptn/issues/2760
