### ISSUE TITLE
helm-service: Check length of release name

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#2948]
The Helm release name is limited to 53 characters. See e.g. https://github.com/helm/helm/issues/6006#:~:text=Jump%20to%20bottom-,Why%20Helm%20release%20name%20is%20a%20DNS,max%20length%20of%2053%20characters%3F

If now the release name is too long, the `helm-service` cannot successfully execute the upgrade. Furthermore, Helm does not give a good error message here (I do not have any at hand)

**Implementation details:**
The `helm-service` uses the following release name patterns:
- [NAMESPACE]-[SERVICE-NAME]
- [NAMESPACE]-[SERVICE-NAME]-generated

With these release names, we can easily run into the 53 character limit.

A possible solution that would lower the risk of running into the limit would be to remove the namespace from the release name. Please let's use this issue to discuss this.

**Tasks:**
- Add a check for the length of the release name

**Comment by christian-kreuzberger-dtx** [comment]
> A possible solution that would lower the risk of running into the limit would be to remove the namespace from the release name.

1. We would run into an issue with duplicate service names in different projects/namespaces, right? (Or can we distinguish helm-releases by namespace)
2. If we change the naming, do we need to migrate old service names (before Keptn 0.8.x)?


As a counter-proposal, we could keep the same naming format, but automatically limit the service-name to, e.g.:
```
max_len_service_name=53 - len(NAMESPACE) - 1 - len("generated") - 1
SERVICE_NAME=SERVICE_NAME[0:max_len_service_name]
```

In fact, we could even save some strings if we change `generated` to `gen` (though I believe our service names sometimes are called primary/canary, right?).

> Add a check for the length of the release name
We should definately add a check.

**Comment by agrimmer** [comment]
Thanks for your input!

A Helm release lives in a namespace. Hence, there should be no collisions.

But, the migration will not be easy and needs in-depth research.

Furthermore, using only a substring of the Keptn service name could lead to collisions.

**Comment by christian-kreuzberger-dtx** [comment]
As a quick-fix I would recommend that we limit `SERVICE_NAME` as I posted it above.
This won't break anything, but fix the problem for now.

We should furthermore make sure that this gets documented.

**Comment by johannes-b** [comment]
Please add the length check to the shipyard-controller.

**Comment by cpanato** [comment]
hello, this is open for contribution?

**Comment by christian-kreuzberger-dtx** [comment]
Yes it is! The consens is that there should be a length-check for service-name to be added in shipyard-controller, somewhere around the existing validate entity name function for services:
https://github.com/keptn/keptn/blob/feb4eb7a989d4ec17884719dfdaf411a591130bd/shipyard-controller/api/service.go#L129-L139

It should validate the length of the service name based on the project name, all stage names, and the template `[NAMESPACE]-[SERVICE-NAME]-generated

Please also add a failing unit test for a service name that is too long.
