### ISSUE TITLE
Add timeout in shipyard controller for unhandled tasks

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#2953]
If any "task.triggered" event is not picked up any Keptn service, the shipyard-controller should have a timeout after which it sends an automated "task.finished" event with status/result failed. 
Reason: consider users making a typo, e.g., misspelling "depolyment" - how will they get notified that the task has never started? Besides, if a new task is introduced and no service is picking in it, the shipyard controller should send the task.finished event and end the task.

**Comment by johannes-b** [comment]
This is a duplicate to https://github.com/keptn/keptn/issues/3778
