### ISSUE TITLE
Update Jenkins service to not have security violations in manage jenkins admin page

### ISSUE THREAD

**Issue by robertjahn** [keptn/keptn#296]
**Is your feature request related to a problem? Please describe.**
Update Jenkins service to not have security violations in manage jenkins admin page

**Describe the solution you'd like**
No security violations messages in manage jenkins admin page

**Describe alternatives you've considered**
n/a

**Additional context**
![image](https://user-images.githubusercontent.com/24907089/57002766-b6a0d600-6b8f-11e9-807f-7488d32cb36b.png)

**Comment by dirkwall** [comment]
Obsolete, Jenkins is not part of the keptn core installation anymore.
