### ISSUE TITLE
Time format on evaluation endpoint differs from event endpoint

### ISSUE THREAD

**Issue by heydenb** [keptn/keptn#2972]
Using:
`{ url: 'https://......./api/v1/project/test-project/stage/hardening/service/test-service/evaluation',
   method: 'post',
   data: {"start":"2021-01-23T16:01:56+01:00","timeframe":"15m","labels":{"buildId":"i don\'t know","definition":"i don\'t know","runby":"i don\'t know","environment":"i don\'t know","pipeline":"i don\'t know"}
},...
`
Result: `{ code: 400,  message: 'parsing time "2021-01-23T16:01:56+01:00": extra text: +01:00' }`

I use this timeformat for the "event" endpoint and that works fine.
Using different formats for different endpoints makes it difficult to work with the API.

**Comment by christian-kreuzberger-dtx** [comment]
I'm guessing this is with Keptn 0.7.x?
can you please provide an example of how you use the other timeformat with the event endpoint?

As a workaround for now, please convert your datetime into UTC without any extra options like timezone information, e.g. `2020-09-28T07:00:00`.

Looking at our docs, we also have a mismatch there: https://keptn.sh/docs/0.7.x/quality_gates/integration/

![image](https://user-images.githubusercontent.com/56065213/105676018-333e2100-5eea-11eb-9d1c-b3b7bfc97737.png)

**Comment by heydenb** [comment]
Yes, it's with 0.7.3 and this is the format I use with the event endpoint: "2021-01-23T16:01:56+01:00"
It's indeed the timezone which is required with the event enpoint and unsupported at the evaluation endpoint.
