### ISSUE TITLE
Remove unused code and update Jenkinsfile name for keptn use case carts app example

### ISSUE THREAD

**Issue by robertjahn** [keptn/keptn#298]
**Is your feature request related to a problem? Please describe.**
going through the onboarding example app use case, there is an extra step to rename Jenkinsfile to Jenkinsfile.ci.   This is not needed if the Jenkins file in the cart repo was renamed to just Jenkinsfile.  Also, in the carts repo having unused files and folders like monspec leads to confusion.

**Describe the solution you'd like**
1. in keptn-sockshop/carts repo, remove unused Jenkinsfile, rename Jenkinsfile.ci to just Jenkinsfile.
2. in keptn-sockshop/carts repo, remove the unused files and sub-folders
* monspec sub-directory 
* manifest sub-directory
* ci sub-directory
* manifest.yml file
3. update the keptn docs for the use case to remove the step to rename the Jenkinsfile.

**Describe alternatives you've considered**
n/a

**Additional context**
https://keptn.sh/docs/0.2.0/usecases/onboard-carts-service/
![image](https://user-images.githubusercontent.com/24907089/57002972-31b6bc00-6b91-11e9-8311-171bb7e644d7.png)

**Comment by dirkwall** [comment]
keptn use cases won't use Jenkins going forward. Closing for now.
