### ISSUE TITLE
Remove the functionality to listen to service.create.finished event from helm-service

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#2989]
The helm-service will no longer take care of uploading the Helm chart of a service that is going to be onboarded. 

**Tasks:**
* Remove the event subscription in the distributor of the helm-service
* Remove the event handler that uploads the provided Helm chart
* Update the documentation to reflect the current implementation: https://keptn.sh/docs/0.8.x/continuous_delivery/deployment_helm/#clean-up-after-deleting-a-project 
* Update the **Know Limitations** section of the release notes for Keptn 0.8.0:
 
```
The helm-service does not support listening on sh.keptn.event.service.delete.finished
events when running on the execution plane. This leads in the limitation that deleting deployed services on the execution plan becomes a manual task. To delete a deployed service, execute: 
`helm ls -n <NAMESPACE>`
`helm delete <HELM_RELEASE> -n <NAMESPACE>`
`kubectl delete <NAMESPACE>`
```

**Note:**
- To ensure feature parity with Keptn 0.7.3, issue #2990 must be implemented. --> Consider merging the change of this issue with #2990. 

**Definition of Done:**
- [ ] helm-service does not react on a `service.create.finished`

**Comment by warber** [comment]
To avoid conflicts, the removal of the mentioned functionality from the helm service should be done **after** #2966 got merged.

**Comment by christian-kreuzberger-dtx** [comment]
Also, this task has a hard dependency on https://github.com/keptn/keptn/issues/2990

**Comment by christian-kreuzberger-dtx** [comment]
ToDo: Docs (see Tasks)

**Comment by christian-kreuzberger-dtx** [comment]
Regarding updating the docs and the "known limitations":

It is not necessary to delete the helm release with helm v3. Helm releases live in a namespace, and when deleting that namespace, the release is also deleted. I verified this:

```
$ helm ls -n sockshop-dev
NAME                           	NAMESPACE   	REVISION	UPDATED                                	STATUS  	CHART                   	APP VERSION
sockshop-dev-carts             	sockshop-dev	2       	2021-02-19 13:07:16.829641727 +0000 UTC	deployed	carts-0.1.0             	           
sockshop-dev-carts-db          	sockshop-dev	1       	2021-02-19 12:57:48.288736926 +0000 UTC	deployed	carts-db-0.1.0          	           
sockshop-dev-carts-db-generated	sockshop-dev	1       	2021-02-19 12:58:15.050547149 +0000 UTC	deployed	carts-db-generated-0.1.0	           
sockshop-dev-carts-generated   	sockshop-dev	2       	2021-02-19 13:08:35.504916097 +0000 UTC	deployed	carts-generated-0.1.0   	           
```

```
$ kubectl delete namespace sockshop-dev
namespace "sockshop-dev" deleted
```

```
$ helm ls -n sockshop-dev
NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART	APP VERSION
```

**Comment by christian-kreuzberger-dtx** [comment]
Docs have been merged: https://github.com/keptn/keptn.github.io/pull/752
