### ISSUE TITLE
Keptn CLI: `keptn onboard service` becomes `keptn create service + add resources`

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#2990]
With the change that the helm-services will no longer upload the Helm charts of a service, this functionality must be moved to the CLI. 

Since the `keptn onboard service` command is opinionated in the way this command limits a Keptn service to be deployed with a Helm chart, this command will become deprecated and replaced by the simpler `keptn create service` followed by `keptn add-resource`.

`keptn onboard service carts --project=sockshop --chart=./carts`

```
Output:

This command is deprecated and is replaced by: 

1.) keptn create service carts --project=sockshop
2.) keptn add-resource --project=sockshop --stage=all --service=carts  --resource=./carts --resourceUri=helm/carts

Please execute these commands sequentially. 
```

**Tasks:**
* Change the `keptn onboard service` command to print the sub-commands: `keptn create service + keptn add-resource` and a note showing that this command has been deprecated
* (!) Provide the CLI commands that do the onboarding (create + add-resource) in a way that copy-paste is possible
* (!) When executing `keptn onboard` return exit-code != 0
* Mark the command as depreciated - to see it on: https://keptn.sh/docs/0.8.x/reference/cli/commands/keptn_onboard_service/
* Update of integration tests: change `keptn onboard` to `keptn create svc` + `keptn add-resource`
* Update of documentation: https://keptn.sh/docs/0.8.x/manage/service/#onboard-a-service

**Note:**
- To ensure feature parity with Keptn 0.7.3, issue #2989 must be implemented. --> Consider merging the change of this issue with #2989. 

**TBD:**
To upload the helm chart, I see two options: 
1. `keptn add-resource` supports `--stage=all` which adds the resource to all stages
2. `keptn add-resource --project=sockshop --service=carts  --resource=./carts --resourceUri=helm/carts` - without `stage`

**Definition of Done:**
- [ ] `keptn onboard` has been replaced
- [ ] Documentation (https://keptn.sh/docs/0.8.x/manage/service/#onboard-a-service) is up-to-date

**Comment by christian-kreuzberger-dtx** [comment]
I think we should not call it `--stage=all`, as this means we can never create a stage called `all` (which is not obvious to the user).

Not having the argument in `--stage` provided seems to be suboptimal, because (IMO) this should push resources to the master/main branch.

How about new argument called `--allStages` or `--all-stages` (similar to `kubectl get pods --all-namespaces`).

**Comment by johannes-b** [comment]
Let's go with `--all-stages`

**Comment by christian-kreuzberger-dtx** [comment]
While implementing this, I stumbled across a major blocker:

```
keptn onboard service carts --project=sockshop --chart=./carts
```

would lead to these commands:
```
keptn create service carts --project=sockshop
keptn add-resource --project=sockshop --service=carts --resource=./carts --resourceUri=helm/carts
```

In `onboard service` this was handled by the following code
```
		chart, err := keptnutils.LoadChartFromPath(*onboardServiceParams.ChartFilePath)
		if err != nil {
			return err
		}

		chartData, err := keptnutils.PackageChart(chart)
		if err != nil {
			return err
		}

		helmChart := base64.StdEncoding.EncodeToString(chartData)
		service := apimodels.CreateService{
			ServiceName: &args[0],
			HelmChart:   helmChart,
		}
```

However, `add-resource` does not support this, it expects a file (e.g., a `.tgz` file).

Should we extend `add-resource` to allow `--resource` to contain the path to a directory? And how would we add a directory? This is not supported in go-utils either.

**Comment by christian-kreuzberger-dtx** [comment]
After a short discussion with @bacherfl , @agrimmer and @warber we came up with the following points:

1. to remove `onboard service`, the `add-resource` command needs support for adding a directory
  * this either means that `add-resource` needs to recursively add files from a directory (which will be slow in case of git-upstream and many files, but it would work)
  * or that configuration-service needs an endpoint to take an archive file, extract it and add it to git
2. In addition, we don't want `keptn add-resource` to be a replacement for `git add` and `git commit`, we want to make sure users know what is happening in the git repo (and in addition have full control of what is happening in the git repo).


ad 1: Regardless of what the result is, the changes will take one to two days in addition to what has happened so far, and we are introducing code that we will remove at some point.

---

Counter proposal:

* `add-resource` gets the `--all-stages` param (it's already implemented, it doesn't break anything), and we allow users to easily add helm chart IF it is a single .tgz file  (e.g., `keptn add-resource --project=keptn --service=control-plane --all-stages --resource=keptn-installer-0.7.3.tgz --resourceUri=control-plane/helm`
* `onboard service` will still work as it does right now, but
  * it will print a deprecation warning (this command will be deprecated soon)
  * and it will print a message, telling the user the steps that are necessary to do it themselves (e.g., git add, git commit, git push)
* In addition, we extend the tutorials with the needed git add, git commit, git push commands for adding a helm chart

---

Last but not least, we need to take issue https://github.com/keptn/keptn/issues/2989 into consideration, where the onboard-service functionality is removed from `helm-service`.
We know the idea was to remove the functionality of helm-service, and ensure that `add-resource` does the trick.

Instead, our proposal (in combination with the above proposal) would be that `keptn onboard service` calls the relevant code, e.g.:
https://github.com/keptn/keptn/blob/5ee8390489b1eeb9043439c4570df4b9e7e8c3c6/helm-service/controller/onboarder.go#L118-L124

and
https://github.com/keptn/keptn/blob/5ee8390489b1eeb9043439c4570df4b9e7e8c3c6/helm-service/controller/onboarder.go#L206-L225

**Comment by christian-kreuzberger-dtx** [comment]
ToDo: Doc

**Comment by christian-kreuzberger-dtx** [comment]
Docs have been merged: https://github.com/keptn/keptn.github.io/pull/752
