### ISSUE TITLE
Hide implementation details in the API

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#3001]
The goal of this issue is to hide implementation details (e.g. the name of the services providing the API) in the API.

**Tasks:**
- Move endpoints of shipyard-controller into path `/api/controlPlane/v1`
- Move endpoints of `/api/configuration-service/v1` into path `/api/resources/v1`
- Move endpoints of `/api/mongodb-datastore` into path `/api/eventStore/v1`
- Remove NGINX backward-compatible rules

**Comment by johannes-b** [comment]
Just one remark, should we call the `api/eventStore/v1` endpoint just `api/events/v1` to have it aligned with  `/api/resources/v1` ?

**Comment by johannes-b** [comment]
We agreed on: 
~`/api/controlplane/v1`~ --> `/api/v1/` 
`/api/events/v1`
`/api/resources/v1`

**Comment by johannes-b** [comment]
Task: 
- [ ] Rename endpoint of `shipyard-controller`  to `/api/controlPlane/v1`

--> We agreed on non-touching the other endpoints.
