### ISSUE TITLE
shipyard-controller: Trigger next stage regardless of evaluation result

### ISSUE THREAD

**Issue by GustavAT** [keptn/keptn#3008]
If the evaluation of one stage does not result in `pass` (e.g. `warning`), the next stage is not triggered ([see shipyard controller](https://github.com/keptn/keptn/blob/9f5823f96f18e5a309be568be28e8c043d3cc88b/shipyard-controller/api/event.go#L604)). 

More specifically, if the task-sequence of e.g. *staging* does not have the result `pass` (qualtiy gate results in `warning`), the next task sequence in the  *production* stage is not triggered.

I would like to have the next stage triggered regardless of the evaluation result - since I have a manual approval step in the next stage. (could also be configurable if this behavior is not desired all the time)

**Comment by johannes-b** [comment]
@GustavAT spotted it here: https://github.com/keptn/keptn/blob/9f5823f96f18e5a309be568be28e8c043d3cc88b/shipyard-controller/api/event.go#L604

**Comment by johannes-b** [comment]
When discussing this issue, please consider #3027
