### ISSUE TITLE
Add return values for CLI

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#304]
Depending on the result of the executed command, the CLI should return proper exit codes.

**Comment by dirkwall** [comment]
We'll need this for integrating Keptn in other tools for the quality gate use case. Integrations will want to check for errors after executing the Keptn CLI.
Verify that all commands have appropriate return values.

**Comment by agrimmer** [comment]
I double-checked if Cobra returns expected error types in case we exit a command with an error and yes, it does. So we can close this issue.
