### ISSUE TITLE
Mongodb-datastore: When a service is deleted, delete all related events from the event collection

### ISSUE THREAD

**Issue by bacherfl** [keptn/keptn#3040]
Currently, only deleting a project leads to the deletion of its related events in the mongodb (by deleting the collection containing all events related to the project).
However, also when deleting a single service from a project, it does not make sense to keep its related events in the collection. Therefore, we should extend the mongodb-datastore to also subscribe to `sh.keptn.event.service.delete.finished` events and delete the events for the deleted service.

**Comment by christian-kreuzberger-dtx** [comment]
Is this a duplicate of https://github.com/keptn/keptn/issues/2776 ?

**Comment by bacherfl** [comment]
> Is this a duplicate of #2776 ?

yes, seems I have overlooked that other issue. I will close this one
