### ISSUE TITLE
Format the Go imports

### ISSUE THREAD

**Issue by cpanato** [keptn/keptn#3150]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
When working on this PR https://github.com/keptn/keptn/pull/3005 notice the go import was not well formated and not following a good practice.

My proposal is to go over all files and format that to organize the imports and make it clear

the possible format can be

```
import (
  <go std libs>
   ...

  <other libs>
   ...

  <project/org libs>
   ...
)
```

for example 

```
import (
	"errors"
	"fmt"

	"github.com/google/uuid"

	keptnv2 "github.com/keptn/go-utils/pkg/lib/v0_2_0"
	"github.com/keptn/keptn/shipyard-controller/common"
	"github.com/keptn/keptn/shipyard-controller/operations"
)
```

from https://github.com/keptn/keptn/blob/master/shipyard-controller/handler/servicemanager.go

I also volunteer myself to work on this

/cc @christian-kreuzberger-dtx 

**Describe alternatives you've considered**
n/a
**Additional context**
n/a

**Comment by christian-kreuzberger-dtx** [comment]
This should really be automated, maybe via our GoLang IDE.

The main problem I see is that we will get 100s of merge conflicts. I think we could create PRs for each sub-directory, to avoid having huge merge conflicts.

**Comment by cpanato** [comment]
yes, agree!
I will start the work :)
/assign

**Comment by christian-kreuzberger-dtx** [comment]
For now, please avoid the following directories

* helm-service
* cli
* api-service
* shipyard-controller

**Comment by christian-kreuzberger-dtx** [comment]
also
* configuration-service
* remediation-service

**Comment by cpanato** [comment]
TODO:
- [ ] api
- [ ] distributor
- [ ] gatekeeper-service
- [ ] jmeter-service
- [ ] lighthouse-service
- [ ] mongodb-datastore
- [ ] platform-support
- [ ] statistics-service

Out of scope for now:
- [ ] helm-service
- [ ] cli
- [ ] api-service
- [ ] shipyard-controller
- [ ] configuration-service
- [ ] remediation-service

**Comment by cpanato** [comment]
the defined work is done so will close this Issue 🎉

**Comment by christian-kreuzberger-dtx** [comment]
thanks a lot!
