### ISSUE TITLE
cli: keptn version checking on install

### ISSUE THREAD

**Issue by DarthBenro008** [keptn/keptn#3158]
**Environment**

* Client OS (e.g., Linux, OSX, Windows): `linux`
* Keptn Version (`keptn version`): `develop` (pulled latest from master at git head 22ec97a7d988c0b13f8ff9fb62730a438534c587 )
* Kubernetes Cloud Provider (e.g., GKE, AKS): `minikube` (local cluster)

**Affected Component**

* [ ] Docs
* [x] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [ ] Bridge
* [ ] Gatekeeper
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**

keptn cli attempts to check keptn cluster version while installation of keptn.

This would always throw an error, because keptn cluster wouldn't be there in the first place without installation.

**To Reproduce**
```bash
git clone https://github.com/keptn/keptn
cd keptn/cli
minikube start
go build -o keptn
./keptn install
```

1. The error would be visible as soon as you run `./keptn install`

**Expected behavior**
Ask confirmation for the cluster and proceed with keptn installation.

**Current behavior**
First checks keptn cluster version, which will always fail, then asks for confirmation for cluster and proceeds with keptn installation.

**Screenshots**
![keptn_cli_version_error](https://user-images.githubusercontent.com/31009634/106847806-ace9c200-66d5-11eb-96c8-1b3a5540de79.png)

If this is deemed as an actual bug, I would like to investigate and send a PR regarding the same :smiley:

**Comment by DarthBenro008** [comment]
On further investigation, I found out that the same issue persists not only in installation process, but overall cli as it is being checked in root, before any command is executed.

I think we need to whitelist and not print these in few commands such as:
- install
- auth

Please let me know your thoughts

**Comment by christian-kreuzberger-dtx** [comment]
The issue at hand is that you have been connected to a Keptn installation which is no longer available.

I agree though that the error messages / warnings are misleading at best when using `keptn install`.

For other commands like `keptn auth`, `keptn uninstall`, etc..., I believe that the messages should be there.

**Comment by DarthBenro008** [comment]
@christian-kreuzberger-dtx if we could check that the CLI is connected to a Keptn installation that is no longer available, we could prompt the user about the same and disconnect it from that installation (the one that is no longer available) and proceed with the command? I personally think that would certainly improve the user experience!
