### ISSUE TITLE
Upgrade go-utils in statistics-service to latest version from master

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#3160]
When upgrading go-utils in statistics-service I noticed that we are still using some outdated stuff like the old logging from 0.7.1.

# Definition of Done

- [ ] statistics-service uses go-utils@master and all tests succeed

**Comment by christian-kreuzberger-dtx** [comment]
@warber @bacherfl it looks like this has already been done?

**Comment by johannes-b** [comment]
I close this issue because go-utils is already updated for the statistics-service.
