### ISSUE TITLE
Deep Links in Bridge for 0.8.x

### ISSUE THREAD

**Issue by ermin-muratovic** [keptn/keptn#3207]
Keptn's Bridge allows to access the views directly via deep links since 0.7.1. Those deep links currently only apply on the Service-screen and since we introduced two new Tabs (Environment and Sequences) they need to be refined:

**Current deep links:** https://keptn.sh/docs/0.8.x/reference/bridge/deep_linking/#title

Tasks:
- ~~`project/:projectName` should show Environment-Screen instead of Service-Screen~~
- ~~`project/:projectName/:serviceName/:contextId` should show the sequence in the Sequence-Screen with the _keptn context_ specified by `contextId`~~
- ~~`project/:projectName/:serviceName/:contextId/:eventId` should show the sequence in the Sequence-Screen with the _keptn context_ specified by `contextId` and select the correct stage and focus the event with `eventId`~~

After some Discussion, we will actually change the Deep-Links, see my comment below.

**Definition of Done**
- [ ] Update of docu + screenshots in https://keptn.sh/docs/0.8.x/reference/bridge/deep_linking

**Comment by ermin-muratovic** [comment]
After a discussion with @Kirdock we actually decided to introduce some changes to the deep-Links:

- `/project/{projectName}/service/{serviceName}` should open the service tab and expand the service with {serviceName}
- `/project/{projectName}/service/{serviceName}/event/{eventId}` should open the service tab, expand the service with {serviceName} and select the root event with {eventId}
- `/project/{projectName}/service/{serviceName}/event/{eventId}/stage/{stage}` should open the service tab, expand the service with {serviceName}, select the root event with {eventId} and select the stage {stage}

- `/project/{proejctName}/sequence/{sequenceId}` should open the sequence tab and select the sequence with {sequenceId}
- `/project/{proejctName}/sequence/{sequenceId}/stage/{stage}` should open the sequence tab, select the sequence with {sequenceId} and select the stage {stage}
- `/project/{proejctName}/sequence/{sequenceId}/event/{eventId}` should open the sequence tab, select the sequence with {sequenceId} and expand the event with {eventId} (also checking that the correct stage is selected)


We will try to keep the old deep Links compatible:

**Comment by johannes-b** [comment]
The proposed change looks good to be, except of one question: In the second example: 
- `/project/{projectName}/service/{serviceName}/event/{shkeptncontext}` should open the service tab, expand the service with {serviceName} and select the root event with {shkeptncontext}

the event is referenced by the `shkeptncontext`. However, in the third example: 

- `/project/{projectName}/service/{serviceName}/event/{eventId}/stage/{stage}` should open the service tab, expand the service with {serviceName}, select the root event with {eventId} and select the stage {stage}

the event is referenced by `eventId`. 

How can we streamline this problem?

**Comment by ermin-muratovic** [comment]
> The proposed change looks good to be, except of one question: In the second example:
> 
> * `/project/{projectName}/service/{serviceName}/event/{shkeptncontext}` should open the service tab, expand the service with {serviceName} and select the root event with {shkeptncontext}
> 
> the event is referenced by the `shkeptncontext`. However, in the third example:
> 
> * `/project/{projectName}/service/{serviceName}/event/{eventId}/stage/{stage}` should open the service tab, expand the service with {serviceName}, select the root event with {eventId} and select the stage {stage}
> 
> the event is referenced by `eventId`.
> 
> How can we streamline this problem?

With eventId actually the shkeptncontext is ment. I updated my comment.
