### ISSUE TITLE
Discussion: Propagation of event payload to next stage

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#3209]
Currently, the event payload of a task sequence is propagated through all stages meaning that the result of a task in one stage is visible in the next stage. Hence, when the next stage has not an identical task, the payload will not be overridden. For example, if a production stage does not perform an `evaluation`, the  `evaluation` result from the previous stage is visible. 

**Option A:** Just propagate a configurationChange to the next stage and remove the rest. 
- *Advantage:* Clear separation of stages
- *Disadvantage:* If a task requires a payload from the previous stage, it does not get it. 

**Option B:** Propagate the entire payload through all stages.
- *Disadvantage:* It can be misleading (or even unclear) from which stage, e.g., the `evaluation` result is coming from. 

This situation needs to be discussed.

**Comment by warber** [comment]
Another topic for discussion is the current concept of **accumulating event data**:

Currently, the data of cloud events get accumulated/enriched by data from previous tasks to make sure that the next tasks have access to the information they eventually need from already completed tasks. The benefit is, that the "event trace" is encoded in the current cloud event and services do not need to make an explicit lookup in the database. However, this information is stored as top level data right below the `.data` block. Hence, this data can easily be overwritten by any service, by accident (e.g., when any field name matches with the field name the service is using). Thus, it's worth considering putting the accumulated event information in a separeate block of the cloud event. (e.g., `keptn-event-trace`, or `keptn-history`,...). The only restriction is, that no service can use fields with this name as event payloads. Having this, it would be clear, why this information is present in the cloud events (currently it is not, and you can just guess which information might be relevant for any service and which is not). Further, we would avoid the risk of services overwriting important event trace information.

What are your thoughts on this? 

@agrimmer @johannes-b  @ermin-muratovic @Kirdock @bacherfl @christian-kreuzberger-dtx

**Comment by ermin-muratovic** [comment]
I don't like the concept of accumulating event data, because you can not say from which service the data block was written and additionally as @warber said it can be overwritten by any service. I know that this would change a lot, but I would prefer a separate `response` or `trace` block, which contains only the response of that one service that executed that event or if it really is necessary, then a `responses` or `traces` block with the accumulated event information.
