### ISSUE TITLE
Keptn CLI completion activation fails (zsh)

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#3212]
When executing `keptn completion zsh` it fails with a lengthy error message.

**Environment**

* Client OS (e.g., Linux, OSX, Windows): Mac OSX 11.2
* Keptn Version (`keptn version`): Keptn CLI version (0.8.0-dev.202102091052) and Keptn cluster version (0.8.0-dev)
* Kubernetes Cloud Provider (e.g., GKE, AKS): GKE
* Kubernetes version (`kubectl version`): v1.17.14-gke.1600

**Affected Component**

* [ ] Docs
* [x] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [ ] Bridge
* [ ] Gatekeeper
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

Script output (excerpt):
```
./keptn completion zsh
* Warning: Your Keptn CLI version (0.8.0-dev.202102091052) and Keptn cluster version (0.8.0-dev) don't match. This can lead to problems. Please make sure to use the same versions.
#compdef _keptn keptn


function _keptn {
  local -a commands

  _arguments -C \
    '--mock[Disables communication to a Keptn endpoint]' \
    '(-n --namespace)'{-n,--namespace}'[Specify the namespace where Keptn should be installed, used and uninstalled in (default keptn).]:' \
    '(-q --quiet)'{-q,--quiet}'[Suppresses debug and info messages]' \
    '(-v --verbose)'{-v,--verbose}'[Enables verbose logging to print debug messages]' \
    "1: :->cmnds" \
    "*::arg:->args"

  case $state in
  cmnds)
    commands=(
      "add-resource:Adds a local resource to a service within your project in the specified stage"
      "auth:Authenticates the Keptn CLI against a Keptn installation"
      "completion:Generate completion script"
      "configure:Configures one of the specified parts of Keptn"
      "create:Creates a new project or service"
      "delete:Deletes a project"
      "generate:Generates the markdown CLI documentation or a support archive"
      "get:Displays an event or Keptn entities such as project, stage, or service"
      "help:Help about any command"
      "install:Installs Keptn on a Kubernetes cluster"
      "onboard:Creates a new service and uploads its Helm chart to the branches in the Git repository"
      "send:Sends an event to Keptn"
      "set:Sets flags of the CLI configuration"
      "status:Checks the status of the CLI"
      "uninstall:Uninstalls Keptn from a Kubernetes cluster"
      "update:Updates an existing Keptn project"
      "upgrade:Upgrades Keptn on a Kubernetes cluster"
      "version:Shows the version of Keptn and Keptn CLI"
    )
    _describe "command" commands
    ;;
  esac

  case "$words[1]" in
  add-resource)
    _keptn_add-resource
    ;;
  auth)
    _keptn_auth
    ;;
  completion)
    _keptn_completion
    ;;
  configure)
    _keptn_configure
    ;;
  create)
    _keptn_create
    ;;
  delete)
    _keptn_delete
    ;;
  generate)
    _keptn_generate
    ;;
  get)
    _keptn_get
    ;;
  help)
    _keptn_help
    ;;
  install)
    _keptn_install
    ;;
  onboard)
    _keptn_onboard
    ;;
  send)
    _keptn_send
    ;;
  set)
    _keptn_set
    ;;
  status)
    _keptn_status
    ;;
  uninstall)
    _keptn_uninstall
    ;;
  update)
    _keptn_update
    ;;
  upgrade)
    _keptn_upgrade
    ;;
  version)
    _keptn_version
    ;;
  esac
}

...
```

**Comment by jetzlstorfer** [comment]
Command to be executed should actually be:
```
source <(keptn completion zsh)
```

Doing so, it does not result in this "error" message, but nevertheless, I couldn't get it to work.

**Comment by jetzlstorfer** [comment]
Documentation also needs to be updated to explain this feature: https://github.com/keptn/keptn.github.io/issues/729

**Comment by christian-kreuzberger-dtx** [comment]
IMHO the feature is implemented similar to what Kubernetes and Helm offer, e.g.:
```
$ kubectl completion
error: Shell not specified.
See 'kubectl completion -h' for help and examples

$ kubectl completion -h
Output shell completion code for the specified shell (bash or zsh). The shell
code must be evaluated to provide interactive completion of kubectl commands.
This can be done by sourcing it from the .bash_profile.

 Detailed instructions on how to do this are available here:
https://kubernetes.io/docs/tasks/tools/install-kubectl/#enabling-shell-autocompletion
```

```
$ helm completion

Generate autocompletion scripts for Helm for the specified shell.

Usage:
  helm completion [command]

Available Commands:
  bash        generate autocompletion script for bash
  fish        generate autocompletion script for fish
  zsh         generate autocompletion script for zsh

Flags:
  -h, --help   help for completion
```

But I agree that some more information might be helpful, especially considering that running `keptn completion SHELLNAME` outputs a lot of code.

While this is not a bug, I would like to ask for the following improvement:

* Docs for `keptn completion` available, as defined in https://github.com/keptn/keptn.github.io/issues/729
* When running `keptn completion` (without -h), users should see a link to the docs

**Comment by DarthBenro008** [comment]
@christian-kreuzberger-dtx you are absolutely right, I had followed similar to what Helm and kubectl offer while implementing this feature. 

@jetzlstorfer I believe you had missed the command to autoload the completion on startup, which can be done by executing `keptn completion zsh > "${fpath[1]}/_keptn`

 At the moment the docs for the same can be accessed when you run the following command:
`keptn completion -h`
It will let you know how to enable completion depending on your shell and OS, like this:
<img width="960" alt="keptn_autocompletion" src="https://user-images.githubusercontent.com/31009634/108330647-dafdf480-71f3-11eb-9173-ac8dd38537d7.png">

Hence I think, once keptn/keptn.github.io#729 been resolved, we can then provide the link to docs when users run the command without the `-h` flag.
