### ISSUE TITLE
Restarted pods during Keptn installation

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#3213]
When installing Keptn, it shows a couple of restarted pods after the finished installation. Although this does not break the Keptn installation, I am not sure if it is the expected installation experience. Would be great to have Keptn installed without restarted containers.

**Environment**

* Client OS (e.g., Linux, OSX, Windows):  MacOS 11.2
* Keptn Version (`keptn version`): Keptn CLI version (0.8.0-dev.202102091052) and Keptn cluster version (0.8.0-dev)
* Kubernetes Cloud Provider (e.g., GKE, AKS): GKE
* Kubernetes version (`kubectl version`): v1.17.14-gke.1600

**Affected Component**

* [ ] Docs
* [ ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [x] Helm
* [ ] Istio
* [ ] Bridge
* [ ] Gatekeeper
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

Output once installation is finished:

```
% kubectl get pods -n keptn
NAME                                     READY   STATUS    RESTARTS   AGE
api-gateway-nginx-684d979598-bgwgk       1/1     Running   0          4m2s
api-service-5b4cd6785d-lqlcf             2/2     Running   0          4m2s
bridge-6dc56858f7-bz6hr                  1/1     Running   0          4m3s
configuration-service-75df6c6fc4-5f6vn   2/2     Running   0          4m3s
gatekeeper-service-648446d884-dwdjp      2/2     Running   0          4m3s
helm-service-64bfcf9bcb-2b7mc            2/2     Running   2          4m3s x
jmeter-service-6787cbcb57-rvm7d          2/2     Running   0          4m3s
keptn-nats-cluster-0                     3/3     Running   0          4m3s
lighthouse-service-fc8d4bb7d-pvdr9       2/2     Running   0          4m3s
mongodb-56d759658b-tjnx7                 1/1     Running   0          4m3s
mongodb-datastore-5bdf9fb8ff-45xrh       2/2     Running   2          4m3s x
remediation-service-857df6f794-ffcr8     2/2     Running   2          4m3s x
shipyard-controller-74698bc876-6pgsf     2/2     Running   0          4m3s
statistics-service-869f64fb9b-mfh88      2/2     Running   0          4m3s
```
Restarted pods marked with `x`.

**Comment by christian-kreuzberger-dtx** [comment]
Thanks.

I'm not sure what the root-cause of these restarts is, but I guess it has to do with the fact that helm-service, mongodb-datastore and remediation-service try to access something that's not (yet) available.
Maybe we can add some dependencies in the helm-chart or lift the liveness probes?

**Comment by christian-kreuzberger-dtx** [comment]
We looked into this, as of right now it is not possible to fix this easily. Nevertheless, as it does not cause any **actual problems**, this is just a cosmetic thing, and I'll close this issue.
