### ISSUE TITLE
Keptn Bridge: Root events are limited to 20

### ISSUE THREAD

**Issue by GustavAT** [keptn/keptn#3223]
**Environment**

* Client OS (e.g., Linux, OSX, Windows): `Ubuntu 20.04`
* Keptn Version (`keptn version`): `0.8.0-alpha`
* Kubernetes Cloud Provider (e.g., GKE, AKS): `GKE`
* Kubernetes version (`kubectl version`): `v1.16.15-gke.6000`
* Bridge image: `bridge2:0.8.0-dev-PR-3169`

**Affected Component**
* [ ] Docs
* [ ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [X] Bridge
* [ ] Gatekeeper
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**

The Keptn Bidge initially only loads the latest **20** root events per project.

Example request:
```
/api/mongodb-datastore/event?root=true&pageSize=20&project=foobar
```

Example response (20 root events but 28 in total):
```json
events: [,…]
nextPageKey: "20"
pageSize: 20
totalCount: 28
```

In this case, 8 root events are missing.
This could lead to certain service having no event-feeds at all.
This also causes missing approval confirmations in the environments screen. They can still be approved via the CLI.

**Expected behavior**

My suggestion: Last X root events could be loaded for each service

**Current behavior**

Last 20 root events are loaded per project.

fyi @ermin-muratovic

**Comment by johannes-b** [comment]
Will be addressed by #3224
