### ISSUE TITLE
Keptn Bridge: Deployed services is displayed as "not deployed"

### ISSUE THREAD

**Issue by GustavAT** [keptn/keptn#3224]
**Environment**

* Client OS (e.g., Linux, OSX, Windows): `Ubuntu 20.04`
* Keptn Version (`keptn version`): `0.8.0-alpha`
* Kubernetes Cloud Provider (e.g., GKE, AKS):`GKE`
* Kubernetes version (`kubectl version`): `v1.16.15-gke.6000`
* Bridge image: `bridge2:0.8.0-dev-PR-3169`

**Affected Component**

* [ ] Docs
* [ ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [X] Bridge
* [ ] Gatekeeper
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**

After a service has been deployed and released successfully in a stage, the environment screen still shows "Services not deployed yet" for that service.

It can still be accessed thought by its public URL (received from the `released.finished` event)

**To Reproduce**

I was using a minimal shipyard with 1 stage, 1 sequence and 2 tasks: deploy and release.
Onboard and deploy any service.

**Expected behavior**

The services is shown as "deployed" and I can access it using the public URL.

**Current behavior**

A successfully deployed services is shown as "Service not deployed yet" in the environment screen.

**Screenshots**

Environment screen shows that the service is not deployed:
![bridge_service_not_deployed_environment_screen](https://user-images.githubusercontent.com/6452952/107502861-862a0080-6b99-11eb-9231-20a5668bd474.png)

The payload for the `release.finished` event is successful and shows the public URL:
![bridge_service_not_deployed_release_payload](https://user-images.githubusercontent.com/6452952/107502864-875b2d80-6b99-11eb-8672-0cc4ee07ca09.png)

The sequence screen for that service and stage shows no errors/warnings:
![bridge_service_not_deployed_sequence_screen](https://user-images.githubusercontent.com/6452952/107502867-875b2d80-6b99-11eb-8d8f-c8d0cc848b6d.png)

fyi @ermin-muratovic

**Comment by ermin-muratovic** [comment]
I think this is related to #3223 and will be fixed with that.

**Comment by ermin-muratovic** [comment]
Fixed with #3337
