### ISSUE TITLE
Approval does not work neither in Bridge nor CLI

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#3225]
In Bridge, I see the approval.triggered but I cannot use the Bridge to approve or reject:
<img width="1599" alt="Screen Shot 2021-02-10 at 12 36 30" src="https://user-images.githubusercontent.com/10980861/107505340-da82af80-6b9c-11eb-922d-1e514c1916ac.png">

In the CLI, I get the following output
```
keptn send event approval.finished --project=appgw-mc --stage=prod-gke --service=gateway
Starting to send approval.finished event

 OPTION	GIT COMMIT	EVALUATION	
 (1)	n/a		n/a		
 (2)	n/a		n/a		
 (3)	n/a		n/a		
Select the option to approve or decline: 
```

**Comment by christian-kreuzberger-dtx** [comment]
Please use the Bug Report template and specify  a Keptn version.
