### ISSUE TITLE
Keptn CLI: Allow Values.keptn.service as service name in helm-template when onboarding a service

### ISSUE THREAD

**Issue by GustavAT** [keptn/keptn#3230]
**Environment**

* Client OS (e.g., Linux, OSX, Windows): `Ubuntu 20.04`
* Keptn Version (`keptn version`): `0.8.0-alpha`
* Kubernetes Cloud Provider (e.g., GKE, AKS): `GKE`
* Kubernetes version (`kubectl version`): `v1.16.15-gke.6000`

**Affected Component**

* [ ] Docs
* [X] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [ ] Bridge
* [ ] Gatekeeper
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**

The problem occurs when using `{{ Values.keptn.service }}` as the serivce-name in the helm chart's service.yaml.
When onboarding e.g. the `frontend` service, the following error occurs:

```bash
keptn onboard service frontend --project=service-demo --chart=./helm
Provided Keptn service name "frontend" does not match Kubernetes service name "svc"
Error: The provided Helm chart is invalid. Please checkout the requirements
```

The problems seems to be related to a life-cycle issue: the chart is validated before helm-values are replaced. When having the service-name hard-coded and other values such as the app-selector or labels use the helm-values, they are set correctly.

**To Reproduce**
I've attached a minimal example (shipyard.yaml + helm chart) to reproduce the error:

[example.tar.gz](https://github.com/keptn/keptn/files/5958962/example.tar.gz)

```bash
keptn create project service-demo
keptn onboard service frontend --project=service-demo --chart=./helm
```

**Expected behavior**

The service is onboarded correctly.

**Current behavior**

Got said error message - the service is not onboarded.

**Comment by christian-kreuzberger-dtx** [comment]
I think the check happens locally, in the CLI:

https://github.com/keptn/keptn/blob/b2a14418997bebf87aeaa0e054189b1c0eb8b7b3/cli/pkg/validator/helm_validator.go#L102-L106

For now, you can try adding the helm chart using `keptn add-resource`, .e.g.:
```
keptn add-resource --project=service-demo --service=frontend --all-stages --resource=your-helm-chart.tgz --resourceUri=helm/frontend.tgz
```
