### ISSUE TITLE
Create Helm Chart for helm-service and jmeter-service

### ISSUE THREAD

**Issue by thschue** [keptn/keptn#3253]
To make the deployment of the keptn execution plane gets easier, a simple helm chart for the deployment of the execution plane components (at least helm-service and jmeter service) should be created.

Acceptance criteria:
- The keptn (0.8) execution plane components can be installed by a helm chart
- The helm-charts should be provided within the microservices folder (e.g., deploy/ or charts/)
- The container repository is configurable
- The keptn-token and the connection to the control plane components can be defined in the helm-chart (e.g., `helm upgrade ... --values=keptnApiToken=...,keptnApiUrl=...`)

**Comment by johannes-b** [comment]
*Automatically create the Helm Charts:*

- [ ] In the scope of this issue, the CI automation should be provided that automatically creates the Helm Charts via GitHub action and to stores it as part of the build artifacts.
