### ISSUE TITLE
Verify: How does helm-service behave on a faulty, user_managed Helm Chart?

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#3258]
Please verify the following use case: As a user, I provide a Helm Chart that I want to deploy using the deployment strategy: `user_managed`. Hence I'm responsible for uploading it to the corresponding stage (Git branch). 

* The Helm Chart is "broken" meaning that, e.g., the referenced image is not available - resulting in an ImagePullError. 

**Definition of Done:**
- [x] **Verification:** How does Helm-library behave when deploying a "broken" Chart? Do we get an error code?
- [ ] Based on the learning, write a unit test that covers all returned errors from Helm.

**Comment by warber** [comment]
Helm lib returns an error in case the deployment (i.e. pods)  are not `ready` (for whatever reason, including `imagePullerror`)  within the specified timeout.

**Comment by warber** [comment]
Each call to [UpgradeChart(...)](https://github.com/keptn/keptn/blob/master/helm-service/pkg/helm/helm_executor.go#L10) correctly returns any error possibly thrown by the helm lib.
Each of these errors is passed to [handleError(...)](https://github.com/keptn/keptn/blob/master/helm-service/controller/handler_base.go#L62) which then ultimately sends an error event.

IMO ok, nothing to do here.

**Comment by warber** [comment]
Agreed with @bacherfl that extensive unit testing will be done in a follow-up issue (after 0.8.0 release), as it requires some bigger refactorings.

@johannes-b ok?

**Comment by johannes-b** [comment]
@warber thanks for verifying that errors are caught up and translated into valid finished events. This was the goal of this story. 

It is okay, to write the unit tests when the service gets refactored.
