### ISSUE TITLE
As a keptn user I would like to use the CLI to send a new-artifact event

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#326]
**Is your feature request related to a problem? Please describe.**
This feature request simulates the web-hook to a container registry.  

**Describe the solution you'd like**
I would like to use the keptn cli similar to: `keptn send event new-artifact repo/image:tag` to send a new-artifact event to keptn, which triggers the delivery pipeline.

**Comment by agrimmer** [comment]
**New CLI commands:**

For sending a new artifact event, the user can specify an image, e.g.
```
keptn send new-artifact --image=docker.io/keptn/keptn-authenticator:7e48486 --project=sockshop --service=carts
keptn send new-artifact --image=quay.io/keptn/keptn-authenticator:7e48486 --project=sockshop --service=carts
```



For sending arbitrary CloudEvents, the user should be able to pass a cloud event as json file, e.g.
`keptn send --cloudevent=ce.json`

**Comment by agrimmer** [comment]
This issue can be closed after merging 
- https://github.com/keptn/github-service/pull/25
- https://github.com/keptn/keptn/pull/393
- https://github.com/keptn/keptn.github.io/pull/147
