### ISSUE TITLE
Keptn Bridge: Wrong event feed if task and sequence share the same name

### ISSUE THREAD

**Issue by GustavAT** [keptn/keptn#3293]
**Environment**
* Client OS (e.g., Linux, OSX, Windows): `Ubuntu 20.04`
* Keptn Version (`keptn version`): `0.8.0-dev`
* Kubernetes Cloud Provider (e.g., GKE, AKS): GKE
* Kubernetes version (`kubectl version`): `v1.16.15-gke.6000`
* Bridge version: branched from commit ea7421f670b719918495f78a95802eec048085b9

**Affected Component**
* [ ] Docs
* [ ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [X] Bridge
* [ ] Approval
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**
Events are not grouped correctly if the sequence and a task within that sequence share the same name.

The issue is located in the [traceMapper](https://github.com/keptn/keptn/blob/8a1bd89c144800ebf4e3c5dd95a8b8d01bd91a75/bridge/client/app/_services/data.service.ts#L300) function:

```typescript
return t.getShortType() == trace.getShortType() && t.data.stage == trace.data.stage;
```

Two triggering events, e.g., `sh.keptn.event.production.delivery-analytics.triggered` (sequence root event) and `sh.keptn.event.delivery-analytics.triggered` (task event) have the same short-type and get related although they shouldn't.
Assigning the remaining events (`started`, `finished`) is then messed up.

**To Reproduce**

Create a shipyard file with one sequence named `deployment` and a task `deployment`. (stage name is not relevant)

**Expected behavior**

Event feed:

```
- stage.sequence-name.triggered
- task-name.triggered
- stage.sequence-name.finished
```

**Current behavior**

```
- stage.sequence-name.triggered
- task-name.started
- task-name.finished
```

**Additional context**

Discussed with @ermin-muratovic IRL.

**Comment by ermin-muratovic** [comment]
Will be fixed with #3329
