### ISSUE TITLE
Build trigger: poll service repo for code changes to not trigger Jenkins build job manually

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#334]
Currently, the build job for the service used to demonstrate onboarding (i.e., carts) need to be triggered manually. 

Adapt the Jenkins configuration to trigger the build job whenever a commit is pushed to the carts repository.

**Comment by agrimmer** [comment]
This functionality is not needed anymore as the CI pipeline is not required anymore, i.e. see
https://github.com/keptn/keptn/issues/326.
