### ISSUE TITLE
Create travis builds for all components

### ISSUE THREAD

**Issue by dirkwall** [keptn/keptn#336]
Those travis builds will build docker images and push those to docker hub on commit.

node-example: https://github.com/dirkwall/github-service
java-example: https://github.com/keptn-sockshop/carts

Following files are needed in the repository:
- **.travis.yml**: contains the build information and is preconfigured to work with the git flow branching model and name restrictions for branches (if the names are not correct, no build is triggered)
- **MANIFEST**: template file for including artifact information within the container
- **./writeManifest.sh**: script that is used during the build to populate the MANIFEST with values
- **version**: this holds the current version of the artifact; irrelevant to feature, bugfix, hotfix, and develop branches; relevant for release/x.x.x branches and master

Furthermore, a small change in the Dockerfile is necessary that prints the content of the MANIFEST in the logs, e.g. changing from

```
FROM java:openjdk-8-alpine
WORKDIR /usr/src/app
COPY target/*.jar ./app.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/urandom","-jar","./app.jar", "--port=8080"] 
```
to
```
FROM java:openjdk-8-alpine
WORKDIR /usr/src/app
COPY ./target/*.jar ./app.jar
COPY ./MANIFEST /
CMD ["sh", "-c", "cat /MANIFEST && java -Djava.security.egd=file:/dev/urandom -jar ./app.jar --port=8080"]
```

or from
```
FROM node:10-alpine
ENV NODE_ENV "production"
ENV PORT 8080
EXPOSE 8080
RUN addgroup mygroup && adduser -D -G mygroup myuser && mkdir -p /usr/src/app && chown -R myuser /usr/src/app

# Prepare app directory
WORKDIR /usr/src/app
COPY package.json /usr/src/app/
RUN npm install -g tsc 
RUN npm install -g concurrently 
RUN npm install -g typescript
RUN npm install -g copyfiles

COPY . /usr/src/app
RUN ls -la /usr/src/app/*
RUN npm install
RUN npm run build-ts
USER myuser

# Start the app
CMD ["/usr/local/bin/npm", "start"]
```
to
```
FROM node:10-alpine
ENV NODE_ENV "production"
ENV PORT 8080
EXPOSE 8080
RUN addgroup mygroup && adduser -D -G mygroup myuser && mkdir -p /usr/src/app && chown -R myuser /usr/src/app

# Prepare app directory
WORKDIR /usr/src/app

COPY package.json /usr/src/app/
RUN npm install -g tsc 
RUN npm install -g concurrently 
RUN npm install -g typescript
RUN npm install -g copyfiles

COPY . /usr/src/app

RUN ls -la /usr/src/app/*

RUN npm install
RUN npm run build-ts

USER myuser

# Start the app
CMD ["sh", "-c", "cat MANIFEST && /usr/local/bin/npm start"]
```

**Comment by johannes-b** [comment]
Repos in which the travis build is setup:

- [ ] github-service
- [ ] jenkins-service
- [ ] servicenow-service
- [ ] ...
