### ISSUE TITLE
Nightly build for develop version

### ISSUE THREAD

**Issue by dirkwall** [keptn/keptn#337]
Over night all latest artefacts of keptn components are used to setup keptn on a dedicated cluster. The onboarding use case should be executed automatically.
This clusters is used for sprint reviews.

Related to #205 and #206

**Comment by dirkwall** [comment]
Missing due to dependencies on issue #327:

- The nightly cluster should be set up using the versions contained in the dev-branches of the core components.
- Extend end-to-end tests: (1) test which pushes an artifact into dev, staging and prod, (2) test with quality gates in place
- Rename scripts: Currently, the scripts are named 'pr_main' and 'master_main'. These names are misleading.

**Comment by christian-kreuzberger-dtx** [comment]
We have nightly builds of all images in place (they are build from the develop branch). The latest version of the CLI is being built within travis as well. The latest version of the CLI is automatically uploaded to gcloud and we could provide a link to that if anyone asks.

A very simplistic end-to-end test is also executed (onboarding new service and sending a new artifact). More sophisticated end-to-end/integration tests will follow later.
