### ISSUE TITLE
Label of input in menu is not readable (grey on grey)

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#3370]
Following screenshot was taken after a fresh install of Keptn 0.7.3 and viewing the Keptns Bridge in a Safari on Mac. It is a minor issue but the text "Keptn API Token" & "keptn auth command" in the two text boxes is dark grey on grey which is hard to read. 

![image](https://user-images.githubusercontent.com/675886/109004762-7afec680-76a9-11eb-948d-03a72b3454bf.png)

Choosing better colors would improve UX slightly

**Comment by christian-kreuzberger-dtx** [comment]
For comparison, this is what it looks like on Ubuntu 20.04 in Firefox:
![image](https://user-images.githubusercontent.com/56065213/109012925-d97c7280-76b2-11eb-8935-a1d3b1a6afdd.png)

Not sure if this is a system specific color, but we surely can optimize this on our side.

**Comment by Kirdock** [comment]
Just to explain the reason: The color is different because Safari renders colors differently. Both colors, in Chrome and Safari, are `#B7B7B7`
