### ISSUE TITLE
Allow JenkinsService to react to ProblemEvent

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#338]
**Is your feature request related to a problem? Please describe.**
The current JenkinsService reacts to deploy, run_test and evaluate events and for those calls a Pipeline. I would like to extend this to also react on problem events so that we can use Jenkins Pipelines for auto-remediation. This would be a "1-stop-shop" solution for demoing all key keptn-capabilities with no other tool dependencies other than Jenkins, e.g: that pipeline could do the same thing as the evlauation_done pipeline does right now in case the evaluation fails -> rollback blue/green

**Comment by johannes-b** [comment]
When working on this issue, I would go one step further. Currently, the names of the pipelines are hard-coded in the jenkins-service, e.g., if a `configuration-changed` event comes in, the `deploy` pipeline gets triggered. 

I would like to have a way to configure the relationship between the event and the pipeline using, for example, a config map or environment variables. Thus, customers can re-use their pipelines. 

**[channel]:[pipeline]**
configuration-changed: deploy
deployment-finished: run_tests
evaluation-done: evaluation_done
problem: _recover_

**Comment by dirkwall** [comment]
Will be addressed by #450. Closing.
