### ISSUE TITLE
Bridge: Duplicated Tasks in sequence screen

### ISSUE THREAD

**Issue by warber** [keptn/keptn#3382]
After triggering a delivery from the CLI I've noticed that in the bridge the **test** task of a sequence appeared twice:

![duplicated-test](https://user-images.githubusercontent.com/72415058/109145170-6c281a80-7762-11eb-9a55-3972fb2aebe3.png)

The ID of both events is identical, so it's clearly a duplicate which might be caused by a flaw in the event polling logic in the bridge. Further, the duplicated task does not turn green/red and keeps showing a rotating icon.

**Workaround:** Pressing **F5** :smile_cat:

**Comment by christian-kreuzberger-dtx** [comment]
Just ran into the same issue with 0.8.0-rc1

![image](https://user-images.githubusercontent.com/56065213/109286278-55e19380-7822-11eb-82ff-29d1ba9ae1bb.png)

**Comment by locopol** [comment]
> 
> 
> After triggering a delivery from the CLI I've noticed that in the bridge the **test** task of a sequence appeared twice:
> 
> ![duplicated-test](https://user-images.githubusercontent.com/72415058/109145170-6c281a80-7762-11eb-9a55-3972fb2aebe3.png)
> 
> The ID of both events is identical, so it's clearly a duplicate which might be caused by a flaw in the event polling logic in the bridge. Further, the duplicated task does not turn green/red and keeps showing a rotating icon.
> 
> **Workaround:** Pressing **F5** 😸

Hi,

 Im tested the latest version of Keptn (0.10.0) and the issue about duplicate tasks persists, im tested on Chrome and Firefox and have the same results

**Comment by locopol** [comment]
this is the original task.
![imagen](https://user-images.githubusercontent.com/50225514/141027772-ba6af841-864c-4f0f-aee9-2e0fae48faa0.png)

And the top tasks have the same id but with empty information

![imagen](https://user-images.githubusercontent.com/50225514/141027890-7f364da1-4478-41a1-bde5-d2485b9ca4a3.png)
