### ISSUE TITLE
Automatically create Dynatrace Request Attributes when deploying keptn0.1

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#34]
**Describe the solution you'd like**
For our "Performance as a Service" use case we ask Dynatrace users to create 3 Request Attribute tags for better analysis of executed performance tests. We should automatically create these rules through the Dynatrace Configuration API

**Additional context**
Here is the link to the Configuration API: https://www.dynatrace.com/support/help/extend-dynatrace/dynatrace-api/configuration/service-api/request-attributes-api/

**Comment by jetzlstorfer** [comment]
request attributes get now automatically generated in v0.1.1
