### ISSUE TITLE
After upgrade from 0.7.3 to 0.8.0-rc1, helm-service was not updated, eventbroker is still there

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#3400]
To replicate:

* Install Keptn 0.7.3
* Upgrade to 0.8.0-rc1 using `keptn upgrade --skip-upgrade-check`
* Verify pods using `kubectl -n keptn get pods` 
* Verify which images are used using `kubectl -n keptn get deployments -owide`

Problem:

* eventbroker-go is still there
* helm-service has not been updated
* jmeter-service has not been updated
* gatekeeper-service is still there

**Comment by christian-kreuzberger-dtx** [comment]
Together with @warber we are unable to reproduce this behaviour on a fresh installation of 0.7.3 (I tested it locally on k3s 1.19).

However, I am currently having this issue with my production cluster (GKE), and I'm happy to provide more insights.

**Comment by warber** [comment]
I cannot confirm a faulty behavior, also not on GKE. Here is the deployment state after an upgrade from 073 to 080rc1 on GKE:
![after-upgrade (1)](https://user-images.githubusercontent.com/72415058/109517341-6f484100-7aa9-11eb-87c5-1093c6431955.png)

**Comment by johannes-b** [comment]
@warber and @christian-kreuzberger-dtx , I upgraded my Keptn 073 on GKE to 0.8.rc1 without issues: 

**1) Upgrade of Keptn**
```
api-gateway-nginx-5f9f74c475-c7hqz       1/1     Running   0          26m
api-service-5cd9f6bdd8-lrcx7             2/2     Running   0          26m
approval-service-69f46d88d6-9ppz4        2/2     Running   0          26m
bridge-6f9fbb687c-bcdzl                  1/1     Running   0          26m
configuration-service-6b8c5c6d59-rb6gc   1/1     Running   0          25m
dynatrace-service-5cbc548d7f-gphxx       2/2     Running   0          44d
dynatrace-sli-service-755d5f994-rflb6    2/2     Running   0          44d
helm-service-9c644bb5b-5cfcx             2/2     Running   0          26m
jmeter-service-86f78db795-pv2dv          2/2     Running   0          26m
keptn-nats-cluster-0                     3/3     Running   0          44d
lighthouse-service-8757f4b64-pttf7       2/2     Running   0          26m
mongodb-56d759658b-7bsbg                 1/1     Running   0          26m
mongodb-datastore-76dd75fbbc-dhsvf       2/2     Running   0          26m
notification-service-9887c8788-hm9z4     2/2     Running   0          44d
remediation-service-5cfb57c595-vlfdb     2/2     Running   0          26m
shipyard-controller-f646498d4-nn7pc      2/2     Running   0          26m
statistics-service-6fdc5dd664-znxxn      2/2     Running   0          26m
```


**2) Upgrade of Shipyard for Project** - copy-paste.

**3) `keptn trigger delivery --project=sockshop --service=carts --image=docker.io/keptnexamples/carts --tag=0.11.1` successfully worked. 

--> I did not run into this issue either.

**Comment by christian-kreuzberger-dtx** [comment]
Closing this as we did not manage to reproduce it.
