### ISSUE TITLE
Unable to authenticate to keptn endpoint

### ISSUE THREAD

**Issue by jyothi-y** [keptn/keptn#3401]
Hi Team, 

We have installed keptn through helm upgrade command and exposed it via Ingress.We followed the below steps:
a) run the helm upgrade with the option "ClusterIP".
b) Install an Ingress-Controller and create an Ingress through istio option as per doc- https://keptn.sh/docs/0.7.x/operate/install/#option-3-expose-keptn-via-an-ingress.
c)Get the HOST of the api-keptn-ingress using the command below.

 kubectl -n keptn get ingress api-keptn-ingress

NAME                HOSTS                  ADDRESS         PORTS   AGE
api-keptn-ingress   x.x.x.x.nip.io   x.x.x.x   80      50s

d)Authenticating Keptn API. But when trying to authenticate the host facing below issue

KEPTN_ENDPOINT='https://x.x.x.x.nip.io/api'
KEPTN_API_TOKEN=$(kubectl get secret keptn-api-token -n keptn -ojsonpath={.data.keptn-api-token} | base64 --decode)
keptn auth --endpoint=$KEPTN_ENDPOINT --api-token=$KEPTN_API_TOKEN

Starting to authenticate
Authentication was unsuccessful. Post https://X.X.X.X.nip.io/api/v1/auth: dial tcp X.X.X.X:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Retrying...
Authentication was unsuccessful. Post https://X.X.X.X.nip.io/api/v1/auth: dial tcp X.X.X.X:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Retrying...
Authentication was unsuccessful. https://X.X.X.X.nip.io/api/v1/auth: dial tcp X.X.X.X:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Retrying...

**Comment by christian-kreuzberger-dtx** [comment]
> KEPTN_ENDPOINT='https://x.x.x.x.nip.io/api'

Can you try to use http instead of https?

**Comment by jyothi-y** [comment]
The same issue is arising when tries with http:
 $Env:KEPTN_ENDPOINT = 'http://x.x.x.x.nip.io/api'
 $tokenEncoded = $(kubectl get secret keptn-api-token -n keptn -ojsonpath='{.data.keptn-api-token}')
>> $Env:KEPTN_API_TOKEN = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($tokenEncoded))
 keptn auth --endpoint=$Env:KEPTN_ENDPOINT --api-token=$Env:KEPTN_API_TOKEN

Starting to authenticate
Authentication was unsuccessful. Post http://x.x.x.x.nip.io/api/v1/auth: dial tcp x.x..x.x: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Retrying...

**Comment by jyothi-y** [comment]
The same issue is arising when tried with http:
 $Env:KEPTN_ENDPOINT = 'http://x.x.x.x.nip.io/api'
 $tokenEncoded = $(kubectl get secret keptn-api-token -n keptn -ojsonpath='{.data.keptn-api-token}') 
 $Env:KEPTN_API_TOKEN = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($tokenEncoded))
 keptn auth --endpoint=$Env:KEPTN_ENDPOINT --api-token=$Env:KEPTN_API_TOKEN

Authentication was unsuccessful. Post http://x.x.x.x.nip.io/api/v1/auth: dial tcp x.x.x.x:80: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Retrying...

**Comment by christian-kreuzberger-dtx** [comment]
Just to rule out a problem with Istio or DNS, could you setup Keptn using a Loadbalancer - https://keptn.sh/docs/0.7.x/operate/install/#option-1-expose-keptn-via-a-loadbalancer 

Other then that, what's your Kubernetes Platform?

**Comment by jyothi-y** [comment]
We have tried with Load balancer before ingress option only. But as per infosec rules we are unable to use it. Below is the error we faced.

Error: UPGRADE FAILED: failed to create resource: admission webhook "validation.gatekeeper.sh" denied the request: [denied by k8s-no-public-ip-loadbalancers] Service api-gateway-nginx of type LoadBalancer should not use public ip, use the annotation service.beta.kubernetes.io/azure-load-balancer-internal:true to create an internal load balancer.

**Comment by jyothi-y** [comment]
We have tried with Load balancer before ingress option only. But as per infosec rules we are unable to use it. Below is the error we faced.

Error: UPGRADE FAILED: failed to create resource: admission webhook "validation.gatekeeper.sh" denied the request: [denied by k8s-no-public-ip-loadbalancers] Service api-gateway-nginx of type LoadBalancer should not use public ip, use the annotation service.beta.kubernetes.io/azure-load-balancer-internal:true to create an internal load balancer.

**Comment by christian-kreuzberger-dtx** [comment]
My guess is that you are running into the same problem with Istio, as Istio requires you to use a LoadBalancer. You can verify if Istio ingressgateway gets an external IP, e.g.:
```console
$ kubectl -n istio-system get services
NAME                   TYPE           CLUSTER-IP     EXTERNAL-IP     PORT(S)                                                                      AGE
istio-ingressgateway   LoadBalancer   10.24.49.176   3.7.1.6   15021:31275/TCP,80:32206/TCP,443:31369/TCP,15012:30289/TCP,15443:31370/TCP   3h11m
istiod                 ClusterIP      10.24.50.250   <none>          15010/TCP,15012/TCP,443/TCP,15014/TCP                                        3h12m
```

You can then verify if something is responding when querying that IP, e.g.:
```
$ curl http://3.7.1.6
* TCP_NODELAY set
> GET / HTTP/1.1
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< date: Mon, 01 Mar 2021 11:49:40 GMT
< server: istio-envoy
< content-length: 0
```

Here you can see a 404 Not Found sent by `server: istio-envoy`.

Regarding setup of Istio on AKS, please take a look at https://istio.io/latest/docs/setup/platform-setup/azure/ for more information.

Please note, Keptn is only a consumer of Istio.
