### ISSUE TITLE
Cannot checkout main|master in AWS CodeCommit

### ISSUE THREAD

**Issue by thschue** [keptn/keptn#3403]
Your issue may already be reported! Please search on the [issue tracker](https://github.com/keptn/keptn/issues) before creating a new one.

**Environment**

* Client OS (e.g., Linux, OSX, Windows):
OSX

* Keptn Version (`keptn version`):
0.8.0-rc1

* Kubernetes Cloud Provider (e.g., GKE, AKS):
EKS

* Kubernetes version (`kubectl version`):
v1.19.6-eks-49a6c0

**Affected Component**

configuration service

* [ ] Docs
* [ ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [ ] Bridge
* [ ] Approval
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**

When trying to use a CodeCommit repository in keptn, an error message indicating that the branch could not get checked out is shown.

**To Reproduce**

* Create CodeCommit Repository
* Use this in keptn

```keptn create project <project-name> -t "<password>" -u "<username>" -s ./shipyard.yaml -r https://git-codecommit.us-east-1.amazonaws.com/v1/repos/<repo-name>```

**Expected behavior**

Branches are created and project is created

**Current behavior**

Branches are created and an error message is shown
```
Error: Create project was unsuccessful.
{"code":400,"message":"Could not check out branch"}

```

The Log of the configuration service contains:
```{"timestamp":"2021-03-01T06:27:46.670905304Z","logLevel":"DEBUG","message":"Checking out default branch"}
{"timestamp":"2021-03-01T06:27:46.876116179Z","logLevel":"ERROR","message":"Could not check out  branch of project <project>"}
{"timestamp":"2021-03-01T06:27:46.876140161Z","logLevel":"ERROR","message":"Error executing command git checkout : exit status 128\nfatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths\n"}
```

As there are two whitespaces between "check out" and "branch" in the second line of the log output, it seems like the default branch can not be determined. This is currently "master" and will be "main" after 2021-03-04 (on initial commits)

**Comment by warber** [comment]
The problem here is, that the codecommit repository gives back multiple HEAD branches:

```
$ git remote show origin
[...]
 HEAD branch (remote HEAD is ambiguous, may be one of the following):
    entry
    master
  Remote branches:
    entry  new (next fetch will store in remotes/origin)
    master tracked
[...]
```

which will break the logic for determining the default branch used for `git checkout` in the configuration-service.
Note, that this problem *seems* to occur only for CodeCommit repositories (not **absolutely** sure though, I cannot reproduce it on using Github as upstream).
