### ISSUE TITLE
Provide a hub for Keptn integrations, extensions & services

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#3406]
Currently, Keptn services and integrations can be found on an overview page at https://keptn.sh/docs/integrations/ 
While this served fine as a central overview of all currently supported integrations, a more sophisticated "integrations hub" is desired.

The hub should list all available integrations including their name, status, install numbers/github stars, description, installation instructions, ... 

The hub should be part of Keptn's bridge.

An inspiration for the integration hub could be the following screenshot.
![image](https://user-images.githubusercontent.com/7677092/109483378-6f334b80-7a7f-11eb-9af7-41b73505f0d2.png)

Implementation details such as data source and data structure for the hub have to be defined and need discussion.

**Idea for extension**
- define a process of how to get the Keptn services from contrib&sandbox into the Artifact hub https://artifacthub.io/ . They should be available from there as well.

**Comment by jetzlstorfer** [comment]
This issue will be reserved for Google Summer of Code participation. 
Link TBA

**Comment by iraj465** [comment]
@jetzlstorfer I'm interested to work on this issue as a Google Summer of Code project. I wanted to discuss as to how the implementation of the hub is to be carried out. Let me know if you have any other silo on your mind for discussions or here on the issue itself. Thanks

**Comment by iraj465** [comment]
Hi. Is this project still on for GSoC?

**Comment by jetzlstorfer** [comment]
Hi @iraj465 - yes this project is submitted for GSoC. I'm happy to answer questions here or in the Keptn slack - please reach out via https://slack.keptn.sh

**Comment by MetalDent** [comment]
Hi, is this project open to apply for the LFX mentorship?

**Comment by jetzlstorfer** [comment]
the open was open for application in LFX mentorship but no student was selected in the current period

**Comment by P-riyanka-prasad** [comment]
Hey @jetzlstorfer I am New TO this i have applied for this but no response.
Can you guide me how to resolve this

**Comment by jetzlstorfer** [comment]
Hi @P-riyanka-prasad the project has not been assigned for a mentorship, therefore you might have not gotten a response from the LFX. 
The implementation details have not been defined yet, therefore it might be a bit hard to get started on this. If you want to contribute to the project, please have a look at our [good first issues](https://github.com/keptn/keptn/contribute)
