### ISSUE TITLE
jmeter-service needs to send TestStrategy in Test.Finished CloudEvent

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#3419]
With Keptn 0.8.0-rc1, jmeter-service does not send `testStrategy` in the `test.finished` CloudEvent.

It is however sent in the `test.triggered` CloudEvent:

**test.triggered** with `teststrategy`
```
{
  "data": {
    "project": "mockshop",
    "service": "carts",
    "stage": "staging",
    "test": {
      "teststrategy": "performance"
    }
  },
  "source": "shipyard-controller",
  "specversion": "1.0",
  "type": "sh.keptn.event.test.triggered",
}
```

# Definition of Done

- [ ] go-utils struct has to contain the property: `teststrategy`
- [ ] jmeter-service sends `teststrategy` in `test.finished`

**Comment by johannes-b** [comment]
By taking a closer look at this issue, I think that we should not force the jmeter-service to return the property but rather make sure that the shipyard-controller merges the payload: 

"type": "sh.keptn.event.test.triggered"

```
    "test": {
      "teststrategy": "performance"
    }
```

"type": "sh.keptn.event.test.finished"

```
    "test": {
      "end": "2021-03-31T14:46:28Z",
      "gitCommit": "",
      "start": "2021-03-31T14:44:46Z"
    }
```

--> the next task is `evaluation`: "type": "sh.keptn.event.evaluation.triggered" (and the current result)

```
    "test": {
      "end": "2021-03-31T14:46:28Z",
      "gitCommit": "",
      "start": "2021-03-31T14:44:46Z"
    }
```

I would expect:

```
    "test": {
      "end": "2021-03-31T14:46:28Z",
      "gitCommit": "",
      "start": "2021-03-31T14:44:46Z",
      "teststrategy": "performance"             < containing the "teststrategy" 
    }
```
