### ISSUE TITLE
SlackService: auto subscribe to problem event

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#342]
**Is your feature request related to a problem? Please describe.**
The default slack-service.yaml definition misses the subscription to the problem channel. I would like to see this event as well in my slack channel as it then allows me to see ALL events processed by keptn

**Comment by dirkwall** [comment]
keptn/slack-service:0.1.1 supports events from the problem channel
slack-service.yaml on master branch includes subscription for problem channel
