### ISSUE TITLE
Swagger-UI: Share Authorization/API Token between services

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#3423]
With 0.7.x it was enough to authenticate once in our Swagger-UI, and the token was shared between all other microservices (mongodb, configuration-service):

![image](https://user-images.githubusercontent.com/56065213/109768709-8b5af800-7bf9-11eb-89fe-9d2b6ec768b6.png)

With 0.8.0-rc1 we have introduced new microservices (e.g., control-plane, statistics-service) that use a different Token Name, therefore we lose authentication in those two microservices within swagger-ui:

![image](https://user-images.githubusercontent.com/56065213/109768790-a4fc3f80-7bf9-11eb-80ce-ec469135fa6a.png)

An easy fix would be to ensure that all microservices use the same token name in swagger-ui.

# Definition of Done

- [ ] When authenticating in swagger-ui, the auth token is shared across all microservices

**Comment by christian-kreuzberger-dtx** [comment]
We found an issue:
apiKeyAuth is still used within the endpoints, which leads to HTTP 401 errors

**Comment by warber** [comment]
won't fix / cannot be fixed easily
