### ISSUE TITLE
Prometheus Self Healing Example based on Response Time does not work

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#3439]
With Keptn 0.8.0, I noticed that the self-healing example using Prometheus does not work (quality-gates does work though).

In particular, I noticed that in keptn/examples we are using this SLI File: https://github.com/keptn/examples/blob/release-0.8.0/onboarding-carts/sli-config-prometheus-selfhealing.yaml

Whereas the querystring looks as follows:
```
  response_time_p90: histogram_quantile(0.9, sum by(le) (rate(http_response_time_milliseconds_bucket{handler="ItemsController.addToCart",job="$SERVICE-$PROJECT-$STAGE-primary"}[3m])))
```

I'm wondering, why are we referencing to `3m` at the end?

Also, I've looked at this metric using Prometheus Query Page, and it looks weird...
![image](https://user-images.githubusercontent.com/56065213/109967989-6ac29900-7cf2-11eb-9041-7fa58a4ee057.png)

For quality-gates the querystring looks a bit different:
```
  response_time_p90: histogram_quantile(0.9, sum by(le) (rate(http_response_time_milliseconds_bucket{handler="ItemsController.addToCart",job="$SERVICE-$PROJECT-$STAGE-canary"}[$DURATION_SECONDS])))
```

Here we are referencing to `$DURATION_SECONDS`, which seems to be more consistent with our approach of evaluations (e.g., for Self Healing we evaluate 10 minutes).

Last but not least, in the [tutorial step 22](https://deploy-preview-112--keptn-tutorials.netlify.app/tutorials/keptn-full-tour-prometheus-08/index.html?index=..%2F..keptn08x#21) we are telling the user to watch the metric using
```
histogram_quantile(0.9, sum by(le) (rate(http_response_time_milliseconds_bucket{job="carts-sockshop-production-primary"}[3m])))
```

which is a completely different metric than what we evaluate in the SLI.

**Comment by jetzlstorfer** [comment]
Regarding the tutorial: Feature toggle sounds perfectly fine for me as we also have it for the other tutorial. 
No need to come up with a completely new story for this tutorial.

**Comment by johannes-b** [comment]
https://github.com/keptn-contrib/prometheus-service/pull/177

**Comment by thisthat** [comment]
Both PR got merged. I am closing this issue.
