### ISSUE TITLE
Support custom MongoDB connection string

### ISSUE THREAD

**Issue by tobernguyen** [keptn/keptn#3457]
**Is your feature request related to a problem? Please describe.**
I'm trying to setup Keptn to use an external MongoDB Cluster (a replica set) instead of the embedded MongoDB. However, I couldn't get it to work because of (at least) these 2 problems:
- The connection string for MongoDB ReplicaSet is different from what is being hard-coded here https://github.com/keptn/keptn/blob/5ee8390489b1eeb9043439c4570df4b9e7e8c3c6/mongodb-datastore/handlers/config.go#L13. It has to be started with `mongodb+srv://`
- My MongoDB Cluster uses a self-signed cert and the client will fail to connect if not specifying `?ssl=false` at the end of the connection string (to disable TLS) or we need to provide certs to the mongo client.

**Describe the solution you'd like**
Update `mongodb-datastore` component to accept an environment variable like `MONGODB_CONNECTION_STRING` in which users can specify everything about the connection including username, password, connection types, and connection parameters... And when users provide `MONGODB_CONNECTION_STRING`, other `MONGODB...` environment variables can be omitted.

**Describe alternatives you've considered**
There is no workaround at the moment.

**Additional context**
None for now.

**Comment by christian-kreuzberger-dtx** [comment]
Sounds like a good improvement. I would say if `MONGODB_CONNECTION_STRING` is set, all the other variables should be ignored (this obviously needs to be documented).

One more thing though: this needs to be implemented not just in MongoDB, but also in the helm chart (values.yaml) and in the following services:
* [statistics-service](https://github.com/keptn/keptn/blob/26b57f50cd53578ddda51e1c2fb03e4163ba767b/statistics-service/deploy/service.yaml)
* [remediation-service](https://github.com/keptn/keptn/blob/c026679d0da5da0beef38d4e3a325a9af5384f6f/remediation-service/db/mongodb_connection.go)
* [shipyard-controller](https://github.com/keptn/keptn/blob/b2595a322001c4d42a9b0ba7ddad612c20cf43c2/shipyard-controller/db/mongodb_connection.go)

and potentially others (which I didn't find).

**Comment by thisthat** [comment]
This issue should have been fixed by #5369. Please, feel free to reopen if something is still missing.
