### ISSUE TITLE
Update pitometer example

### ISSUE THREAD

**Issue by robertjahn** [keptn/keptn#346]
**Describe the bug**
The example has the wrong modules names on these sites
https://keptn.github.io/pitometer/
https://github.com/keptn/pitometer/blob/master/README.md

** current example
![image](https://user-images.githubusercontent.com/24907089/57642920-7b86a580-7586-11e9-90d8-48a07b3ae92f.png)

** should be
![image](https://user-images.githubusercontent.com/24907089/57642940-86413a80-7586-11e9-99b7-230a63d2fe6d.png)

**Comment by danielkhan** [comment]
Fixed
