### ISSUE TITLE
Research: How to manage secrets for execution plane service?

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#3463]
Please see discussion for more context info: https://github.com/keptn/keptn/discussions/2829 

While the end-user view is clear (implementation of #3465 allows to create, update and delete a secret), the backend implementation of managing secrets requires some research. 

Research question: 
- Find an abstraction layer that allows you to manage secrets with different secret providers:
  - Vault
  - K8s
- Is SOPS a way to go? (https://github.com/mozilla/sops)  

**Definition of Done:**
- [ ] Concept to implement the secret management to allow different providers

**Comment by thschue** [comment]
As a first workaround, this works perfectly fine with sealed secrets (https://github.com/bitnami-labs/sealed-secrets).
