### ISSUE TITLE
Create/Delete/Update secret using Keptn API/CLI

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#3465]
Please see discussion for more context info:  https://github.com/keptn/keptn/discussions/2829 

**API** 
- Add a `/secret` endpoint to the api-service to create/delete/update a secret
  - Is the `api-service` the right place?
- A secret is represented by a **unique** secret name and a key-value-map
- If the secret is already available, the POST endpoint returns the user message: `The secret xyz is already available, please use another name.` 

**CLI** new CLI commands for: 
- `keptn create secret xyz --from-literal="key1=value1" --from-literal="key2=value2"`: If the secret has a unique name (not already available and the key-value pairs are valid, the secret will be created.
- `keptn delete secret xyz`: If the secret is available, it will be deleted. 
- `keptn update secret xyz --from-literal="key1=value1" --from-literal="key3=value3"`: If the secret is available, the key-value pairs are updated (i.e., key1) or added (i.e., key3). 

Example, the command:

```
kubectl -n keptn create secret generic dynatrace --from-literal="DT_API_TOKEN=$DT_API_TOKEN" --from-literal="DT_TENANT=$DT_TENANT" --from-literal="KEPTN_API_URL=$KEPTN_API_URL" --from-literal="KEPTN_API_TOKEN=$KEPTN_API_TOKEN"
```

can be replaced with:

```
keptn create secrete dynatrace -from-literal="DT_API_TOKEN=$DT_API_TOKEN" --from-literal="DT_TENANT=$DT_TENANT" --from-literal="KEPTN_API_URL=$KEPTN_API_URL" --from-literal="KEPTN_API_TOKEN=$KEPTN_API_TOKEN"
```

**Backend**
- Based on the research from #3463, implement the secret management with K8s secrets.
- To be clarified: Can we use RBAC to restrict the read access? (does it conflict with updating?)
- A secret is created in the namespace in which Keptn is installed 
- Component test: Run the secret service, use (to create/update/delete) the service, check the result (on K8s): https://github.com/testcontainers/testcontainers-go

**Definition of Done**
- [x] Clean Swagger UI (param definition, description)
- [ ] Docu for CLI is updated on keptn.sh/docs
- [x] By using the Keptn API or CLI, I can create/delete/update a secret
- [x] Component test validate the behavior of the service

**Comment by warber** [comment]
Integration test still TBD
