### ISSUE TITLE
Different manifests for Keptn core services

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#3478]
I realized that different Kubernetes manifests for the the same services exist in the Keptn repo. As an example I found that manifest for the bridge in the `bridge/deploy` folder which is different from the manifest that is used by the installer in the `installer/manifests` folder.

For example, a difference in the **bridge manfest** that I've spotted are the environment variables:

In the `bridge/deploy` folder:
https://github.com/keptn/keptn/blob/release-0.8.0/bridge/deploy/bridge.yaml#L49

In the `installer/manifests` folder: 
https://github.com/keptn/keptn/blob/release-0.8.0/installer/manifests/keptn/charts/control-plane/templates/core.yaml#L189

For example, this lines are different/missing:
```
         - name: PROJECTS_PAGE_SIZE
           value: "50"
         - name: SERVICES_PAGE_SIZE
           value: "50"
```

Please provide the same versions of the manifests as this will lead to confusion about how the services should be deployed and which ones are the correct manifests.

**Comment by christian-kreuzberger-dtx** [comment]
Generally speaking: Whatever is in the installer manifest is what should be deployed.

For developers though, you usually install keptn using the CLI, and then you overwrite it using the manifests in the specific repository.

It's easy to forget to sync those, and there is right now no automation for this, so there is not much we can do other than manually sync the contents.
FYI @johannes-b

**Comment by jetzlstorfer** [comment]
Would it make sense to place a readme inside the folder that might have potential outdated versions? It really requires insider knowledge to look for the manifests in the install directory.

**Comment by christian-kreuzberger-dtx** [comment]
Experience shows that people don't read README files.

In the future we will provide helm-charts for all microservices, and then aggregate them together into the installer chart. That way this issue will disappear sooner or later.

**Comment by johannes-b** [comment]
I agree that putting this info into a README won't work since it can be overlooked and is an additional artifact to maintain. However, I propose to add a COMMENT to the manifests that live in `./deploy` in order to indicate that this file is used for development purpose while the "important" one is in: `../installer`
