### ISSUE TITLE
CI chain ails when building docker images

### ISSUE THREAD

**Issue by warber** [keptn/keptn#3486]
Noticed on one of my PRs (*) that the docker build is failing with the following error:

```
ERROR: unsatisfiable constraints:
  git-2.24.4-r0:
    breaks: world[git=2.24.3-r0]
The command '/bin/sh -c apk --update add --no-cache git=2.24.3-r0' returned a non-zero code: 1
Failed to build Docker Image keptn/shipyard-controller:0.8.1-dev-PR-3480.202103100837, exiting
Error: Failed to build Docker Image
Error: Process completed with exit code 1.
```

(*) https://github.com/keptn/keptn/pull/3480/checks?check_run_id=2075031060

**Comment by christian-kreuzberger-dtx** [comment]
This most likely affects shipyard-controller and configuration-service, as both of them are using the specified `git` version.

**Comment by warber** [comment]
ok, I'll bump the version in the ConfigurationService image and remove the GIT installation from the ShipyardController image as I think it is not needed there.
