### ISSUE TITLE
Bridge: Inconsistent stage color

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#3492]
Using Keptn 0.8.0, I managed to produce the following:

![image](https://user-images.githubusercontent.com/56065213/110626971-b0271080-81a1-11eb-984f-f279ab47c965.png)

The interesting fact is that production is red (indicating an error), while dev and staging are green (indicating that it worked).

Looking at the stages itself, they all look similar (one test.finished event failed, but all the others are okay).
**dev**
![image](https://user-images.githubusercontent.com/56065213/110627071-cd5bdf00-81a1-11eb-8c1c-59465b98fa41.png)

**staging**
![image](https://user-images.githubusercontent.com/56065213/110627101-d77ddd80-81a1-11eb-913c-6c224a0e6c7c.png)

**production**
![image](https://user-images.githubusercontent.com/56065213/110627131-dfd61880-81a1-11eb-9204-81f2f7d88a5f.png)

**Shipyard.yaml / Config Repo**
https://github.com/christian-kreuzberger-dtx/keptn-ck-sockshop/blob/master/shipyard.yaml

**Installed Services**
* dynatrace-service
* dynatrace-sli-service
* litmus-service (`kubectl apply -f https://raw.githubusercontent.com/keptn-sandbox/litmus-service/patch/upgrade-080/deploy/service.yaml`)

**Reproduce**
* Install the aforementioned services
* Onboard sockshop, trigger a delivery of carts

**Expected behaviour**
I'm not sure whether the stages should be red or green, but I believe it should be consistent across all stages (so either all stages red or all stages green).
I'm pretty sure the behaviour here is triggered by the fact that there is a failed cloud-event in the sequence, but the sequence continues to the next stage regardless (this is described as a bug in https://github.com/keptn/keptn/issues/3493)

**Comment by johannes-b** [comment]
Depends on #3493

**Comment by johannes-b** [comment]
Can we please validate that this fix: https://github.com/keptn/keptn/pull/3639 resolved this issue too?

**Comment by ermin-muratovic** [comment]
Fixed by #3639 
the tiles are showing already the correct state and the sequence execution stops.
