### ISSUE TITLE
Auto-remediation does not work with remote execution plane

### ISSUE THREAD

**Issue by bacherfl** [keptn/keptn#3498]
Services executing auto-remediation actions are subscribed to the event type `sh.keptn.event.action.triggered`, which are currently sent by the `remediation-service`.  If the execution plane services that are responsible for executing the action are subscribed to this event type directly via NATS, this is not a problem. However, when running the execution plane remotely, the distributor of the service will try to poll open `action.triggered` events from the shipyard-controller's `GET /event/triggered/:eventType` endpoint, which only contains events that are sent out by the shipyard controller. This means that the `action.triggered` events sent by the `remediation-service` will not be included in the response of this API endpoint.

A potential fix could be to adapt the `handleTriggeredEvent()` function of the `shipyard-controller`:

https://github.com/keptn/keptn/blob/f3ab833dce78ef7dc615041e73a200446b62ca33/shipyard-controller/handler/shipyardcontroller.go#L344

In this function, `action.triggered` events coming from the `remediation-service` could be stored in the collection containing the open `.triggered` events, as it is done later in the function, if the incoming `.triggered` event triggered an available task sequence:

https://github.com/keptn/keptn/blob/f3ab833dce78ef7dc615041e73a200446b62ca33/shipyard-controller/handler/shipyardcontroller.go#L422
 

EDIT: This also afffects `get-sli.triggered` and `configure-monitoring.triggered` events

**Comment by johannes-b** [comment]
Based on the implementation of KEP 37, this issue can be closed.
