### ISSUE TITLE
Additional API call for sequenceState

### ISSUE THREAD

**Issue by Kirdock** [keptn/keptn#3536]
In order to minimize API calls for the feature [#2506](https://github.com/keptn/keptn/issues/2506), we need to add a new API endpoint to get for a specified project a defined amount of sequences with more information.

The following information should be provided - **subject to change** (proposal): 
```json
[
  {
    "sequenceState": {
      "name": "SequenceName",
      "time":  "", // sequence triggered
      "shKeptnContext": "",
      "state": "triggered" | "started" | "finished",
      "latestTask": {
        "name": "",
        "stage": "",
        "service": "",
      }
    }
  }
]
```

**Endpoint/Params:** /state
- Query params: 
  - `project`  
  - `pageSize`

**Tasks:**
- Research how to design the response of the `controlPlane/v1/state`
- Implement the endpoint based on the research outcome

**Definition of Done:**
- [ ] Provide solid documentation on the swagger UI
- [ ] Cover the implementation with unit tests

**Comment by warber** [comment]
This issue is not up to date anymore and needs a re-estimate: new issue: #3796
