### ISSUE TITLE
Go-Utils: Generate go model out of JSON schema

### ISSUE THREAD

**Issue by warber** [keptn/keptn#3539]
Currently, we have "handcrafted" our go structs used to implement the Keptn Cloudevents Spec.
From there on we generate the JSON schema which again should actually be the central specification to create language-specific implementations from.

The `go` implementation of the Keptn Cloudevents Spec (as well as an implementation in any other programming language) shall be generated from the JSON schema describing the Spec and not the other way around. 

Definition of done:
- [ ] Evaluate different libraries for generating go structs out of JSON schema (potential candidate: https://github.com/a-h/generate)
- [ ] Use an appropriate library to generate the go structs for the Keptn Cloudevents Spec in `go-utils`
- [ ] Decide how to go on with the current behavior of `keptn generate cloud-events-spec`

**Comment by thisthat** [comment]
Not needed at the moment
