### ISSUE TITLE
Better sequence visualization when having more than one sequence in a stage

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#3542]
The new sequence visualization is great - but - when someone has more than one sequence that gets executed within a stage the bridge doesnt show us which sequence was responsible for which tasks

The following is a screenshot that visualizes this where I have two seqeuences in my testing stage. Would be easier for the user to see the span of a sequence in the bridge as well

![image](https://user-images.githubusercontent.com/675886/111169438-3cbb3f80-85a3-11eb-9d5d-58f9c5ea27ba.png)

**Comment by grabnerandi** [comment]
Wanted to add one more thought as just discussed with @ermin-muratovic 

In most cases a stage will most likely only execute a single sequence - but - I want to easily see when the sequence started, when it ended and also want to have access to the triggered and finished event. If we have more than one sequence the same information is relevant but its even more relevant to have a good grouping of tasks within the sequences

HEre is a new screenshot on how that could look like - this will work for single sequence stages as well as multi-sequence stages
![image](https://user-images.githubusercontent.com/675886/111293260-5dd66b80-8649-11eb-913b-ade9d62bccaf.png)

**Comment by johannes-b** [comment]
To reproduce the situation, just trigger a deployment of `carts:0.11.2` that will cause a rollback. The rollback sequence is a separate sequence: 

![image](https://user-images.githubusercontent.com/729071/112147375-ea020900-8bdc-11eb-88e5-de6a9ea7f524.png)
