### ISSUE TITLE
Need better JMeter result other than just fail

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#3559]
When running JMeter and things fail there is no way right now to know why it failed. Did it fail because the testing script is not there that is configured in jmeter.conf.yaml? or is it because a too high error rate?

Right now we only see this in the sequence screen
![image](https://user-images.githubusercontent.com/675886/111483326-feee2080-8734-11eb-89f1-72b2b1f054fa.png)

I suggest that JMeter - and hopefully all other tools that handle "test" events - to add a good "message" that explains why it failed

**Comment by grabnerandi** [comment]
Want to add one more thing to this.
Many errors in JMeter are a result that JMeter cant access the passed URL. I therefore suggest that the JMeter service does a quick sanity check on resolving the DNS of the deploymentURI. If the there are any issues with DNS resolution the JMeter service could immediately return an error with a message saying "Cant reach URL a.b.com from JMeter-Service". This will especially be interesting in scenarios where we have a keptn execution plane that hosts the test infrastruture which is testing against an app running in a different environment

**Comment by johannes-b** [comment]
To improve, the function https://github.com/keptn/keptn/blob/master/jmeter-service/main.go#L260 has to recive a message and set the property: `testFinishedData.Message = msg` like the `sendErroredTestsFinishedEvent` function does.
