### ISSUE TITLE
Isuue in Dynatrace Keptn integration

### ISSUE THREAD

**Issue by jyothi-y** [keptn/keptn#3560]
Hi Team, When I'm trying to integrate dynatrace the below issue is arising. Keptn authentication is successfull, but unable to configure dynatrace.

<img width="933" alt="auth" src="https://user-images.githubusercontent.com/79640292/111581198-d6bafc00-87de-11eb-88e8-fbda8e9aa263.PNG">
<img width="571" alt="403Error" src="https://user-images.githubusercontent.com/79640292/111581244-e9353580-87de-11eb-884e-3af1c14726ac.PNG">

**Comment by johannes-b** [comment]
Hi, have you created the `dynatrace` secret as explained here: https://keptn.sh/docs/0.8.x/monitoring/dynatrace/install/#install-dynatrace-keptn-integration

**Comment by jyothi-y** [comment]
Hi johannes, yes I have created the dynatrace secret as per above link.
![image](https://user-images.githubusercontent.com/79640292/111585677-acb90800-87e5-11eb-9ec0-9e6912a07021.png)

**Comment by johannes-b** [comment]
I assume that you set the Dyanatrace API token permissions as explained by the above link, right? 

What is actually confusing me is the error you get: 
`403 Forbidden` - `Microsoft-Azure-Application-Gateway` 

* Are you running on AKS? 
* Might it be a gateway configuration that you can`t do outbound API calls?

**Comment by jyothi-y** [comment]
API token permissions are also provided accordingly.
Yes, I'm running on AKS.
Dynatrace URL has also been whitelisted, that is the reason i'm able to download oneagent from dynatrace.

**Comment by johannes-b** [comment]
Can you please take a look at the logs of the dynatrace-service? 

You get them using: 
```
kubectl get pods -n keptn > to the the pod name
kubectl logs dynatrace-service-[YOUR_ID] -n keptn -c dynatrace-service
```

Hopefully, they can tell more.
