### ISSUE TITLE
SLI display name - Fallback to raw name is not implemented

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#3567]
I'm using `keptn-0.8.1-alpha`, with the SLO file: 

```
---
spec_version: "1.0"
comparison:
  aggregate_function: "avg"
  compare_with: "single_result"
  include_result_with_score: "pass"
  number_of_comparison_results: 1
filter:
objectives:
  - sli: "response_time_p95"
    key_sli: false
    pass:             # pass if (relative change <= 10% AND absolute value is < 600ms)
      - criteria:
          - "<=+10%"  # relative values require a prefixed sign (plus or minus)
          - "<600"    # absolute values only require a logical operator
    warning:          # if the response time is below 800ms, the result should be a warning
      - criteria:
          - "<=800"
    weight: 1
total_score:
  pass: "90%"
  warning: "75%"
```

* In this SLO, I have not `displayName` defined. 

Consequently, no name is shown in the Heatmap / SLI breakdown:

![image](https://user-images.githubusercontent.com/729071/111654547-257d8b80-8809-11eb-99b7-18e7f248327c.png)

**Expected behavior:** I see the "raw" SLI name which is `response_time_p95`

--- 

FYI: When setting the `displayName`, it works nice: 
![image](https://user-images.githubusercontent.com/729071/111656464-d6d0f100-880a-11eb-818c-4abbc2a48cc2.png)

**Comment by johannes-b** [comment]
The original issue is here: https://github.com/keptn/keptn/issues/3345

**Comment by ermin-muratovic** [comment]
@johannes-b could you add also the payload of the evaluation.finished event?
