### ISSUE TITLE
Length of service names is too restrictive

### ISSUE THREAD

**Issue by warber** [keptn/keptn#3585]
A Helm Release's name is limited to 53 characters, which is correctly checked by the ShipyardController when a new Service is created. The Helm release name is generated following the scheme:
`<projectname>-<stagename>-<servicename>[-generated]`, leaving not much room for the length of the service name in practice. Thus, it is way too easy to hit that limit.

Further, many Keptn projects don't use Helm at all (quality gates, performance testing, delivery with other tools than helm,...) where enforcing such strict naming conventions is too restrictive.

Finally, the user is confronted with the error message `[...] service name needs to be less than x characters [...]` without further context. Hence, users are wondering why the same service name is too short in project X, while it is fine in project Y.

> The helm Chart name can be reduced to: `<service_name>[-gen]` ... this results in a service length of 53-4 = 49.

Note: The solution needs to be backward compatible (especially keeping in mind `helm-service` and Keptn installations before 0.8.2)

Tasks:
- [ ] Come up and implement a less restrictive template for helm release names 
- [ ] Adapt the name checks in the CLI/shipyard-controller

Definition of done:
- [ ] Implementation of new helm release naming scheme leaving significantly more room for service name lengths.
- [ ] Solution is well documented and all tests are adapted

**Comment by christian-kreuzberger-dtx** [comment]
My proposed solution to stay backward-compatible is as follows:

1. **Release Name stay as they are**, if everything fits (therefore, if it fits now, it will always fit in the future -> backwards compatible)
2. From left, start dropping `${PROJECT}` and `${STAGE}` until it fits (e.g., ${STAGE}-${SERVICE}[-generated])
3. If it still doesn't fit, slice the service name at the right side, such that servicename + generatedsuffix fits

Please note: Reducing `-generated` suffix to `-gen` would lead to not being backward compatible (unless I introduce extra code checks).

Step 3 is the most dangerous one, as it could lead to ambiguous release names, e.g., 

* service 1: `my-super-long-microservice-service-name-is-foobar` (49 chars) -> `my-super-long-microservice-service-name-is-generated`
* service 2: `my-super-long-microservice-service-name-is-barfoo` (49 chars) -> `my-super-long-microservice-service-name-is-generated`

Therefore I propose that we keep the restriction of `len(${SERVICENAME} + "-generated") < 52`, meaning that service names can be max. 43 characters.

Given that the task was to get a 

> new helm release naming scheme leaving significantly more room for service name lengths

I believe 43 characters is good enough.
