### ISSUE TITLE
Bridge Sequence Icon Colours Represent Status

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [keptn/keptn#3591]
**Is your feature request related to a problem? Please describe.**
Currently the bridge sequence (i) icon remains black.

**Describe the solution you'd like**
This suggestion is to change the icon colour based on the status of the sequence (just as tasks already do). So that failed sequences have a red icon and successful sequence runs have a green icon.

For example:
![image](https://user-images.githubusercontent.com/13639658/111973929-b7a7cb80-8b4a-11eb-9b51-d47243013a38.png)

**Comment by Dynatrace-Adam-Gardner** [comment]
Perhaps a different (or additional) solution:
The `border-left` value of failed sequences is already set to `3px solid #dc172a` so perhaps set the `border-left` value of `succeeded` to a green colour?
![image](https://user-images.githubusercontent.com/13639658/111976044-ed4db400-8b4c-11eb-92c7-326cf94d0a9c.png)

**Comment by johannes-b** [comment]
@Dynatrace-Adam-Gardner many thanks for this idea. The next release will contain the improvement. 
If you want to use it earlier, just use the image: https://github.com/keptn/keptn/pull/3680#issuecomment-811833448
