### ISSUE TITLE
Support multiple new-artifact events that are chronologically close

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#360]
Currently, a new-artifact event has to be completed (i.e. until eval and promote) before the next new-artifact event can be sent.

**Expected behavior:** Allow sending multiple, chronologically close new-artifact events, which do not interfere.

**Solution:** Track the config changes of the new artifact through all steps (config-update, deployment, test, eval, and promote). Therefore, use the Git commit hashes of the changed config.

**Comment by dirkwall** [comment]
This will be fixed with the KeptnEngine.

**Comment by warber** [comment]
I close this, as this will be implemented in #3776
