### ISSUE TITLE
JMeter service fails if deploymentURI doesnt end with a / or a proper path!

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#3612]
The JMeter-service assumes that the passed url in deploymentURI ends with a path, e.g: / - if that path is not there the JMeter service will call the script with an incorrect CHECK_PATH variable which can cause issues. e.g the default jmeter script basicCheck.jmx relies on the CHECK_PATH variable

To give you an example. When the deploymentURI looks like this everything is fine:
```
"deploymentURIsPublic": [
  "http://yourappdomain.abc/"
]
```

however - when the URI doesnt include the path at the end it will fail
```
"deploymentURIsPublic": [
  "http://yourappdomain.abc"
]
```

## DoD

- [x] Check for a correct URI and append `/` if missing
- [x] Unit Tests
- [x] Update the documentation addressing #4513

**Comment by RealAnna** [comment]
can I try this one?
