### ISSUE TITLE
Derive the list of deployments that are currently running for a service

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#3629]
The revamped service screen has to answer the question: *Which deployments are currently running for service xyz?*

*For example*: As a user, I open the service screen and select the service *carts*. Then I can see that 3 deployments are actively running which are distributed across the stages of my project. 
- carts:0.11.1 with commit `c123ab9` runs in: `dev`
- carts:0.10.1 with commit `82341b` runs in: `staging`
- carts:0.9.5 with commit `98ab123` runs in: `pre-production`, `production`

**Task:**
- Implement the logic to derive the list of currently deployed services
- Implement a concept to show older deployments (not running once)
- Assumption, a delivery (delivery-direct) sequence is responsible for deploying a service
- (Interim solution to show the result/behavior) Display the list of deployments in the "service tile"

![image](https://user-images.githubusercontent.com/729071/112595810-3a5eae00-8e0b-11eb-8a4c-1c6eaec509dc.png)

**Definition of Done**
- [ ] The service tile is telling me which deployments are running in which stage.

**Comment by Kirdock** [comment]
At the moment `gitCommit` is not available. It could be derived in loaded sequences, but this is not always the case (only 20 sequences are loaded and they could have not a single delivery sequence). The commit could be fetched later, but this would result in `stages x services   API-Calls`.
