### ISSUE TITLE
Some Deep-Links are broken

### ISSUE THREAD

**Issue by Kirdock** [keptn/keptn#3631]
- When accessing `/project/{project}/sequence/{shkeptncontext}/event/{eventId}`, `/event/{eventId}` is removed and the right stage is not selected.
- `project/{project}/service/{service}/context/{shkeptncontext}` does not select the last stage
- (optional) When a sequence/service is selected the latest stage isn't set in the URL. Without it refreshing/accessing would be inconsistent and could select a different stage.

**Comment by johannes-b** [comment]
❓ Can we write "unit" tests to check the functionality of the deep links?
