### ISSUE TITLE
Text in notification is hard to read and link is not working

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#3634]
My Keptn shows that a new release is available in the notification bar:

![image](https://user-images.githubusercontent.com/729071/112628496-46f6fc80-8e33-11eb-9858-c7d67df015e1.png)

**Improvements:**
- [x] Change the color of the header to blue (the Keptn logo has two flavors of blue (dark/bright) - pick one of these) 
- [x] Change the text color to white to increase the contrast and make it easier to read
- [x] The link to the Upgrade instructions should be clickable. 
- [x] Combine multiple notifications (Keptn + Keptn Bridge) if they reference the same version -> just one notification

**Comment by laneli** [comment]
@johannes-b if you are several versions behind, the message is shown for each version increment. I suppose this should also be merged into one version?

**Comment by johannes-b** [comment]
@laneli merging several versions into one notification would make the most sense.

Besides, can you please delete the sentence: `It might contain incompatible changes.` ... If it is incompatible, we will state that in the upgrade docu.
