### ISSUE TITLE
Service view misses a link to the deploymentURI to quickly access a service

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#3635]
The service screen is nice as it only gives me the data that is typically relevent for me, e.g: Evaluation Results and Approvals per stage.
What is however missing is the DeploymentURI because I quickly want to access the deployed URI for that service

See the following screenshot. It would be great to also get a link to the deploymentURI as I get it in the environment and sequence view
![image](https://user-images.githubusercontent.com/675886/112632834-ecf93580-8e38-11eb-9d2e-1c8bd8502952.png)

**Comment by johannes-b** [comment]
Totally agree, and I want to get it into the revamped service screen too! (#3630)

**Comment by johannes-b** [comment]
The link to the deploymentURL is now here: 
![image](https://user-images.githubusercontent.com/729071/126127525-6893a1b3-1320-4ad4-a812-d7fb422555ca.png)
