### ISSUE TITLE
Show buildId more prominently as it makes it easy to find your deployments

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#3636]
The "buildId" is a special label that is already used in e.g: SLO evaluation heatmap. The buildId would also make the event list better to read as we could immediately see which version was deployed in case the deployment wasnt triggered through a keptn trigger delivery --image --tag

see here a screenshot when I trigger a delivery workflow with Argo rollouts
![image](https://user-images.githubusercontent.com/675886/112633286-7577d600-8e39-11eb-9b92-fff895c03d33.png)

**Comment by johannes-b** [comment]
Many thanks for the feedback! 

The service screen will be revamped and this is great input therefore. 
I cross-link it with the *research* issue on how we can improve the UX for that screen: #3630
