### ISSUE TITLE
Extend keptn cli trigger delivery with --deploymentURI parameter. this will enable user_managed delivery workflows

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#3637]
The Keptn CLI currently supports keptn trigger delivery with the parameters --tag and --image which will end up in the configurationChange data block.
When using Keptn for user_managed helm charts there is a need to manually pass the deploymentURI as the Helm-Service cant extract that from the deployment in the moment.

I am therefore proposing an extension to the keptn cli to optionally allow --deploymentURIsPublic and --deploymentURIsLocal. This would then allow everyone to use the keptn cli to trigger a delivery sequence even when not using Keptns Helm Service with Istio but for instance just user_managed helm charts

Here is an example that would for instance work for my tutorial on argo rollouts
```
keptn trigger delivery --project=demo-delivery --stage=prod --service=simplenode --tag=simplenode --version=1.0.0 --deploymentURIsPublic=http://simplenode.prod.mykeptnserver
```

**Comment by christian-kreuzberger-dtx** [comment]
I think this has been handled via the `endpoints.yaml` as described in the docs: https://keptn.sh/docs/0.8.x/continuous_delivery/deployment_helm/#user-managed-deployments-experimental

In addition, the proposed CLI feature does not work for multi-stage deployments, as the deployment URI would stay the same for every stage.
