### ISSUE TITLE
Keptn API: `configure monitoring` not functioning according to spec 

### ISSUE THREAD

**Issue by pcjeffmac** [keptn/keptn#3638]
**Environment**
Keptn 0.8.1 

* Client OS (e.g., Linux, macOS, Windows):
* Keptn Version (`keptn version`): 0.8.1
* Kubernetes Cloud Provider (e.g., GKE, AKS): microk8
* Kubernetes version (`kubectl version`): 1.19

istio 1.9.1

**Affected Component**

* [ ] Docs
* [ ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [ ] Bridge
* [ ] Approval
* [ ] Datastore
* [X] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**

1. Created project in Keptn.
2. Call API to configure Dyntrace monitoring.
3. Then run a quality gate check.

This message is presented. 

Status: no evaluation performed by lighthouse because no SLI-provider configured for project qualitygate

Then I tried to use the swagger interface to add the Dyntrace monitoring. 
Calling the /v1/event API with the following payload.

```
{
 "data": {
  "project": "qualitygate",
  "configureMonitoring": {
     "type": "dynatrace"
   }
},
"datacontenttype": "application/json",
 "source": "Jenkins",
 "specversion": "1.0",
 "type": "sh.keptn.event.configure-monitoring.triggered"
}
```
This does return a keptnContext.

![Screen Shot 2021-03-26 at 1 34 41 PM](https://user-images.githubusercontent.com/19553291/112672609-0ea6ec80-8e3a-11eb-857d-133ca11ad784.png)

So, one would think it worked.

However, if you run the test again the same message appears. 
![Screen Shot 2021-03-26 at 1 36 26 PM](https://user-images.githubusercontent.com/19553291/112672716-3433f600-8e3a-11eb-88c3-7b3ce33a2637.png)

Next, I used the keptn CLI.
Running this command,
`keptn configure monitoring dynatrace --project=qualitygate`
You get:
```
ID of Keptn context: ee0c05a2-25e9-48a8-bb76-10a8926dfcf1
Dynatrace monitoring setup done.
The following entities have been configured:

---Management Zones:---
  - Keptn: qualitygate: Created successfully
  - Keptn: qualitygate hardening: Created successfully


---Automatic Tagging Rules:---
  - keptn_service: Created successfully
  - keptn_stage: Created successfully
  - keptn_project: Created successfully
  - keptn_deployment: Created successfully


---Problem Notification:---
  - Successfully set up Keptn Alerting Profile and Problem Notifications

---Dashboard:---
  - Dynatrace dashboard created successfully. You can view it here: https://ibg73613.live.dynatrace.com/#dashboards
```

Now, if you run the test, everything works as expected.

**Expected behavior**
Expectation is for the API call to function the same as the CLI.

This call to the API should configure the Dynatrace monitoring.

![Screen Shot 2021-03-26 at 1 34 19 PM](https://user-images.githubusercontent.com/19553291/112673098-b8867900-8e3a-11eb-882e-74bccddbfcce.png)

**Additional context**
Please inform me if the API endpoint is incorrect. Everything I checked, indicates it is correct. 

Also note, this causes an issue for the Jenkins Library as it uses the API to configure the Dynatrace Monitoring.
As of now, the Jenkins Library would appear broken to most users.

**Comment by johannes-b** [comment]
Hi @pcjeffmac,
can you please set the property: `type: sh.keptn.event.monitoring.configure`
Please let me know if it worked then.

**Comment by pcjeffmac** [comment]
It is closer, but the lighthouse service does not get the SLI provider, 
I see this in the bridge,
![Screen Shot 2021-03-29 at 10 09 47 AM](https://user-images.githubusercontent.com/19553291/112849463-18696380-9077-11eb-8a1c-fc564f22bc71.png)

This is what shows up in the lighthouse log,
```
{"timestamp":"2021-03-29T14:03:58.598516548Z","logLevel":"DEBUG","message":"SLI provider for project qualitygate is: "}
{"timestamp":"2021-03-29T14:03:58.598653194Z","logLevel":"DEBUG","message":"Send event: sh.keptn.event.get-sli.triggered"}
{"timestamp":"2021-03-29T14:05:29.500883059Z","logLevel":"DEBUG","message":"Received event: sh.keptn.event.monitoring.configure"}
{"timestamp":"2021-03-29T14:09:05.904068101Z","logLevel":"DEBUG","message":"Received event: sh.keptn.event.evaluation.triggered"}
{"timestamp":"2021-03-29T14:09:05.904271178Z","logLevel":"DEBUG","message":"Send event: sh.keptn.event.evaluation.started"}
```
You can see by the log, the SLI provider is not set.

So, I again used the CLI, 
`keptn configure monitoring dynatrace --project=qualitygate`

Now it works, with this in the lighthouse log,
```
{"timestamp":"2021-03-29T14:09:06.14927593Z","logLevel":"DEBUG","message":"SLI provider for project qualitygate is: dynatrace"}
{"timestamp":"2021-03-29T14:09:06.149425787Z","logLevel":"DEBUG","message":"Send event: sh.keptn.event.get-sli.triggered"}
{"timestamp":"2021-03-29T14:09:09.416196622Z","logLevel":"DEBUG","message":"Received event: sh.keptn.event.get-sli.finished"}
{"timestamp":"2021-03-29T14:09:09.426890456Z","logLevel":"DEBUG","message":"Start to evaluate SLIs"}
{"timestamp":"2021-03-29T14:09:09.721868406Z","logLevel":"DEBUG","message":"Evaluation result: pass"}
```
You can now see that the SLI provider is set to Dynatrace.

This is the output in the bridege,
![Screen Shot 2021-03-29 at 10 14 13 AM](https://user-images.githubusercontent.com/19553291/112849935-8c0b7080-9077-11eb-88ee-5f6e6525ac03.png)

**Comment by johannes-b** [comment]
@pcjeffmac can you please change the payload for your API call to how it is defined here: https://github.com/keptn/spec/blob/0.1.7/cloudevents.md#configure-monitoring

(just remove the `configureMonitoring` property and add `service`). 

I think there happened a mistake with the auto-generation of the keptn/spec, since the implementation still uses the old format which is version 0.1.7.

**Comment by pcjeffmac** [comment]
Looks like this payload works,

{
 "data": {
  "project": "qualitygate-simpletest",
  "service":  "eval",
  "type": "dynatrace"
},
"datacontenttype": "application/json",
 "source": "Jenkins",
 "specversion": "1.0",
 "type": "sh.keptn.event.monitoring.configure"
}

Should I change the "specversion"?

Thanks,

**Comment by johannes-b** [comment]
No, you do not have to change the `specversion`.

**Comment by johannes-b** [comment]
**Task**:
- [ ] Update of the keptn/spec to use the old format of `sh.keptn.event.monitoring.configure`
- [ ] Mark this event as deprecated
- [ ] File an issue that proposes to solve the "problem" of the misused event.
