### ISSUE TITLE
Bridge Menu: Use icons instead of text labels

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#3643]
To free up some space in the Bridge, the menu can be reduced by using icons instead of text labels. This could save about 2/3 of the width. 

**Proposal:**

![image](https://user-images.githubusercontent.com/729071/112840708-f59f7500-909f-11eb-83b1-426356c7ddfd.png)

**Task**
- Research: What are meaningful and semantically correct icons? 
- Replace the text with the icons
- Provide an alt-text (hover over) that refers to the content of the particular screen

**Comment by johannes-b** [comment]
Mikele H. could help with the icons.

**Comment by laneli** [comment]
Icons will be needed for:
* Environment
* Service
* Sequence
* Integration (may get integrated to Uniform or Settings)
* Uniform
* Settings
