### ISSUE TITLE
Incorrect behavior of keptn cli for trigger delivery in handling tag and image parameter

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#3657]
The keptn trigger delivery CLI command allows to pass --image and --tag. When both are passed they get concatenated and are passed as image value in the configurationChange.values map. Here is an example

```
keptn trigger delivery --project=demo-rollout --service=simplenode --stage=staging --image=docker.io/grabnerandi/simplenodeservice --tag=1.0.0
```

This results in
```json
"data": {
    "configurationChange": {
      "values": {
        "image": "docker.io/grabnerandi/simplenodeservice:1.0.0"
      }
    },
```

AS the configurationChange data block allows to define any type of value contruct which will then be updated e.g: in the helm-charts values.yaml I suggest that the Keptn CLI also treats --image and --tag as individual values properties and not merge them. In the example above I would much rather expect the following keptn event being sent:
```json
"data": {
    "configurationChange": {
      "values": {
        "image": "docker.io/grabnerandi/simplenodeservice",
        "tag": "1.0.0"
      }
    },
```

This gives the user also more flexibility in using Keptns CLI to trigger updates as both image and tag can be used independantly in the Helm chart, e.g: tag can be used for version annotations, ...

If we change this behavior we should also change the behavior in the bridge as the bridge should then use both image and tag values when displaying the version information of deployed artifacts. Right now the bridge only looks at the "image" property

**Comment by johannes-b** [comment]
As discussed, this improvement is addressed by the implementation of https://github.com/keptn/keptn/issues/3341

This is why I closed it.
