### ISSUE TITLE
Keptn CLI: Disable Kube context check

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#3666]
As a Keptn user, I frequently work with a Keptn running on a K8s cluster where I do not have a Kube context for. However, the CLI keeps asking me 
```
Kube context has been changed to XYZ
Do you want to switch to the new Kube context with the Keptn running there? (y/n)n
```
As a Keptn user, I would like to disable this Kube context check.

**Comment by agrimmer** [comment]
I changed the type of this issue into a bug, as this question makes the CLI user-unfriendly.

**Comment by warber** [comment]
@agrimmer The current CLI supports the the `y/--yes    Assume yes for all user prompts` flag.
Does this solve your ptoblem?
