### ISSUE TITLE
Integration Test for Keptn Upgrade Command

### ISSUE THREAD

**Issue by bacherfl** [keptn/keptn#3669]
Currently we do a manual test for the `keptn upgrade` command during our release process.
However, this should be tested regularly as part of our integration tests.

The steps that should be performed in the test are as follows:

1. Install the last stable release of Keptn
2. Upgrade to the current version (e.g. the latest version of the master branch, or the next release when the tests are executed on a release branch) using the `keptn upgrade` command.
3. Verify that everything as been upgraded correctly and all expected K8s resources have been applied

This should be checked for the `control-plane-only`, as well as the `continuous-delivery` installation

**Comment by thisthat** [comment]
We run this test on local cluster. No need for an automated test
