### ISSUE TITLE
Ability for service to respond to .finished events

### ISSUE THREAD

**Issue by agardnerIT** [keptn/keptn#3676]
**Is your feature request related to a problem? Please describe.**
My services triggers due to an `evaluation.finished`. My service is technology specific so doesn't live in the shipyard file.

**Describe the solution you'd like**
My custom services needs to response to a `.finished` event and I need it's workflow shown in the Keptn's bridge.
Note that my `do work` phase relies on the output of `evaluation.finished` so I cannot just respond to the `evaluation.triggered` instead.

**Alternatives**
I've tried listening for `evaluation.triggered` and sending `my-service.started`. This works and I see `my-service.started` in the bridge. But then the `evaluation.finished` fires and Keptn automatically finishes `my-service`. This means that I never get to see the `message` or result or **my** `my-service.finished` in the bridge.

I have important information in this output which needs to be presented to the user in the bridge.

**Additional context**
Workflow. Key here is that `my-service.started` and `my-service.finished` appears under the sequence trace inside the evaluation workflow to show that something
```
evaluation.finished
                               >> my-service.started
                                   >> do work
                                       >> my-service.finished
                                           >> Important information sent in the message which must be displayed in the bridge
```

**Comment by grabnerandi** [comment]
Can you give us some insights into what your services is doing? does it have to send a start & finished event or can it simply do its task without reporting back, e.g: for notification integrations (such as slack) - we also dont send back start/finished as it is not necessary

**Comment by agardnerIT** [comment]
This particular service creates a JIRA ticket so the return value (that needs to be presented in the bridge) is the hyperlink to the ticket value.

Furthermore, if the bridge & sequence list is the "source of truth" for everything that happens in Keptn then I believe we should see that a service has executed due to a response. Otherwise, if I was new to the a project and looked at the bridge, how would I even know that a slack message had been sent (for example)? Perhaps that is visualised elsewhere, but as it is, you'd need to know what's listening to what to have that "full picture".

**Comment by thisthat** [comment]
Hi @agardnerIT, your use case can be solved by having your integration listening to both `evaluation.triggered` and `evaluation.finished`. When it receives the `.triggered` events, it answers with a `.started` event and waits until it receives the `evaluation.finished` event from the `lighthouse-service` to answer with its `.finished` event on its own that contains the JIRA ticket URL.
Feel free to reach out to me over our public slack if you need further help
