### ISSUE TITLE
When executing 'keptn version' the CLI should return build information

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#368]
Currently, `keptn version` returns: `CLI version: 0.2.x`

To get more details about the used `keptn` binary, build information like the
* _branch_, 
* _repository_, 
* _commitlink_, 
* _repolink_, 
* _travisbuild_, (?)
* _timestamp_, 
* and meta-information about the _Go version_ should be returned. 

For instance: 
**keptn version** >> 
`keptn CLI Version: version.Info{Major:"0", Minor:"2", GitVersion:"0.2.2", Branch:"release-0.2.x", Repository:"https://github.com/cli", CommitLink:"https://github.com/cli/commit/97834234", RepoLink:"https://github.com/cli/tree/97834234", TimeStamp:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}`

**TBD**: Should this feature use an additional option: `keptn --detailed-version`?

**Comment by peterhack** [comment]
It should also return the versions of the keptn core services and deployed uniform services

**Comment by dirkwall** [comment]
> It should also return the versions of the keptn core services and deployed uniform services

This would be a different CLI command for me, like `keptn show uniform` or something along those lines.

**Comment by dirkwall** [comment]
No immediate need for that.
