### ISSUE TITLE
Show bridge URL when executing keptn configure bridge --output

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#3688]
It would be great to also see the bridge URL when executing
```
keptn configure bridge -o
```

The current output shows:
```
user: keptn
password: Axxxxxxxx
````

To access the bridge, another command, such as `keptn status` is needed that gives you the URL of the Keptn installation.

It would be great to have the output such as
```
$ keptn configure bridge -o

Your Keptn Bridge is available under: https://yourkeptn.com/bridge

These are your credentials
user: keptn
password: Axxxxxxxx
```

**Comment by PrayagS** [comment]
Can I submit a PR for this issue?

I faced the same problem while going through the quick start guide. I went through `cli/cmd/configure_bridge.go` and it seems like we just need to print out the endpoint string.

**Comment by johannes-b** [comment]
@PrayagS a PR is highly appreciated!

**Comment by PrayagS** [comment]
@johannes-b I just submitted a PR (#4102). Please have a look.
