### ISSUE TITLE
Keptn Health Check: Alert user when unmappedKeptnEvents are generated

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#3707]
When external tools send events to Keptn it can happen that those events are not correctly formatted or miss important information, e.g: keptn project, stage, service, ... -> those events currently end up in the unmappedKeptnEvents collection in the mongo datastore.

We recently chatted with a user who had more than 800k of those events in mongo which was a clear indicator that somebody is sending bogus data to Keptn.

As the information about those unmappable events is not apparent to the user unless you dig into logs or the database I suggest we include this as part of a "Keptn Health Check" or "Keptn Health Alert". I could either see this as a metric that is exposed, an API call that provides this information or even better a Keptn Status Page in the bridge that could highlight general informaiton about Keptn including this "health indicator". Besides that number if would then be good to get access to the e.g: Last 50 unmapped events as this will help the end user find the "root cause" of those unmapped events

**Comment by crapson0889** [comment]
I am still looking into how to access the mongodb to hopefully get some more insights into the source of these events. We just broke 1 million unmapped events over the weekend.
