### ISSUE TITLE
NATS reloader container causes the keptn-nats-cluster-0 pod to fail

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#3748]
When installing Keptn, it occurs that the NATS reloader container causes the `keptn-nats-cluster-0` pod to fail.

Since the Keptn Helm Chart for installing Keptn just references the NATS Helm Chart, it is not possible to control this. 

**Workaround:**
However, a workaround is to deploy Keptn with Helm and to set the `control-plane.nats.reloader=false`

**Task:**
* Provide documentation here https://keptn.sh/docs/0.8.x/operate/advanced_install_options/#advanced-install-options-install-keptn-using-the-helm-chart that explains who to disable the `reloader`

**Comment by thisthat** [comment]
With #6322, we disable the reloader by default. I am closing the issue.
