### ISSUE TITLE
MongoDB specifies a security group that is forbidden in restrictive environments

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#3751]
**Problem:** When deploying the mongodb pod, the following error occurs - `Error creating: pods "mongodb-6b97d4fb96-" is forbidden: unable to validate against any security context constraint: [fsGroup: Invalid value: []int64{184}: 184 is not an allowed group]` 

**Workarounds:** There are different workarounds for this like:
* Setting the security context to `null` on this yaml: https://github.com/keptn/keptn/blob/release-0.8.1/installer/manifests/keptn/charts/control-plane/charts/mongodb/templates/deployment.yaml#L33 on this yaml 
* Updating security context constraints: https://docs.openshift.com/container-platform/3.11/admin_guide/manage_scc.html#updating-security-context-constraints

Ideally, it would be helpful if we could just set the security-context via the mongodb helm chart similar to how it is done here: https://github.com/nats-io/k8s/tree/master/helm/charts/nats#security-context 

**Tasks:**
* Add a variable (value) in the Helm Chart here: https://github.com/keptn/keptn/blob/release-0.8.1/installer/manifests/keptn/charts/control-plane/charts/mongodb/templates/deployment.yaml#L33 
* Which can then be controlled via the `values.yaml` here: https://github.com/keptn/keptn/blob/master/installer/manifests/keptn/charts/control-plane/charts/mongodb/values.yaml
* Provide docu for this flag here: https://keptn.sh/docs/0.8.x/operate/advanced_install_options/#advanced-install-options-install-keptn-using-the-helm-chart

**Definition of Done:**
- [ ] When using the advanced install option of Keptn (via Helm Chart) I can set the security group of the mongodb

**Comment by thisthat** [comment]
We changed the mongo image, please reopen the issue if the problem still occurs
