### ISSUE TITLE
Documentation: Escape $FILE variable in reset-git-repos.sh

### ISSUE THREAD

**Issue by checkelmann** [keptn/keptn#3754]
**Environment**

* Client OS (e.g., Linux, macOS, Windows): Linux
* Keptn Version (`keptn version`): 0.8.1
* Kubernetes Cloud Provider (e.g., GKE, AKS): K3s

**Affected Component**

* [X] Docs
* [ ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [ ] Bridge
* [ ] Approval
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**

Within the Backup and Restore Documentation, there is a little error at the step where the reset-git-repos.sh script is written.

When creating the file like in the documentation, the `$FILE` Variable will be replaced with a non-existent shell variable.

```
cat <<EOT >> reset-git-repos.sh
#!/bin/sh

cd /data/config/
for FILE in *; do
    if [ -d "$FILE" ]; then
        cd "$FILE"
        git reset --hard
        cd ..
    fi
done
EOT
```

The generated reset-git-repos.sh:
```
#!/bin/sh

cd /data/config/
for FILE in *; do
    if [ -d "" ]; then
        cd ""
        git reset --hard
        cd ..
    fi
done
```

The File Variable should be escaped like `\$FILE`:
```
cat <<EOT >> reset-git-repos.sh
#!/bin/sh

cd /data/config/
for FILE in *; do
    if [ -d "\$FILE" ]; then
        cd "\$FILE"
        git reset --hard
        cd ..
    fi
done
EOT
```

**Comment by johannes-b** [comment]
Is fixed by: https://github.com/keptn/keptn.github.io/pull/788
