### ISSUE TITLE
Display running remediations in the service screen

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#3761]
## User story

As a user, I would like to see that there is a remediation running when opening the service screen and selected a deployment. When I click on the stage with the "problem icon", I can see the running remediation on the deployment including a link to the remediation sequence.

![image](https://user-images.githubusercontent.com/729071/114385359-3b743700-9b90-11eb-86ce-cf5be0facbf5.png)

## Acceptance criteria
- [ ]  Show problem icon in the list of deployments
- [ ] Show problem icon next to the stage where the remediation is running
- [ ] When clicking the stage, show the running remediation on the deployment
- [ ] (Similar to `Show SLO` for the evaluation heatmap) add a button `Show remediation config` that allows displaying the configured `remediation.yaml`. 
- [ ] A link is provided to get to the remediation sequence

## Definition of done
- [ ] Bridge implements this component
- [ ] Documentation is updated
- [ ] Manual tests

**Comment by johannes-b** [comment]
*) Remark: It is not possible to close the link between the deployment (of a new artifact) and a remediation since they are two independent sequences (`delivery` and `remediation`) with just the properties of `project`, `stage`, and `service` that match. We can only make a guess that the remediation in a particular `stage` and for a particular `service` affects the deployment that is currently deployed there. 

Assumption: 
- `sh.keptn.event.production.delivery.finished`
  - `sh.keptn.event.deployment.finished` [result: pass] > this determines that a particular deployment happened on time stamp: hh:mm:ss. 
- `sh.keptn.event.production.remediation.triggered` > this relates to a running remediation sequence. 

Consequently, it would be possible to get all `remediation.triggered` sequences in stage `production` and service `xyz` after the deployment happened (hh:mm:ss). This would allow getting the remediation history.

**Comment by Kirdock** [comment]
Depends on #3926
