### ISSUE TITLE
Automatically run Keptn Tutorials

### ISSUE THREAD

**Issue by warber** [keptn/keptn#3770]
## Action Item

Investigate the possibility to run Keptn Tutorials automatically.

We lose a lot of time when manually going through the Keptn tutorials to see if everything still works.
In the past, some work has been done to convert the tutorials into executable bash scripts which can then be executed.

## Tasks
* [x]  Contact @TannerGabriel for the tool that extracts tutorial commands in form of `bash` script
* [ ]  In case, adapt [the tutorial][1], so that it can be used for automatic tests

[1]: https://tutorials.keptn.sh/tutorials/keptn-quality-gates-prometheus-08/index.html?index=..%2F..keptn08x#0

**Comment by mowies** [comment]
Findings so far:
I tried to implement automation by directly using the GH actions runner to execute the tutorial commands but did not manage to fully get it up and running.
The main problems are limited accessibility of the runner machine. Also the commands from the tutorial needed to be changed so much that it does not actually fully test what should be tested in the tutorial.

Also: The solution would not be generic enough to also use it for other tutorials, which means that all of them would need separate maintenance with new keptn versions to keep the automation running. This means in turn, that the automation commands in the tutorial would need to be maintained by someone else than the tutorial maintainer.


Ideas for a solution that could work but needs more time:
* Try to standardize, what pre-requisites are needed for tutorials (VM?, K8s Cluster?, Nothing?)
  This would make automation much easier and would enable us to use the same automation for multiple tutorials
* Set up automation to bring up a test cluster/VM to run the tutorial against.
* Make the command extraction tool more intelligent to be able to have more options in the tutorials (https://github.com/keptn-sandbox/tutorial-testing-automation)

**Comment by mowies** [comment]
I will put this ticket on hold until there is more time and maybe a better setup to realize this ticket
