### ISSUE TITLE
Integration test: create issue if integration tests on master branch are failing

### ISSUE THREAD

**Issue by warber** [keptn/keptn#3772]
## Action Item

 The CI pipeline shall only create a new Github Issue iff the (daily) integration test on the master branch is failing.

It seems like the current CI pipeline is also creating new issues whenever integration tests on a PR branch are failing (e.g. https://github.com/keptn/keptn/issues/3771). Only integration tests from the master shall be considered.

**Comment by christian-kreuzberger-dtx** [comment]
I agree with what you say.

However, we should add that a PR comment should be posted if integration tests on a PR (branch) fail.

Example for finding a PR to a given commit/push event: https://github.com/marketplace/actions/find-current-pull-request

**Comment by mowies** [comment]
working on this

**Comment by christian-kreuzberger-dtx** [comment]
Seems to not work properly yet. Please use the input variables:
![image](https://user-images.githubusercontent.com/56065213/122020012-ade9d900-cdc4-11eb-9b7a-420d0b90520f.png)
