### ISSUE TITLE
ShipyardController: Handle Sequences sequentially per stage

### ISSUE THREAD

**Issue by warber** [keptn/keptn#3776]
## User Story 
As a user, I can trigger a sequence multiple times while Keptn queues the sequences to avoid parallel executions in the same stage.

The *ShipyardController* shall handle `.triggered` events of sequences *sequentially* on a "per-stage" level.
Meaning that, if two successive `.triggered` events of the same sequence are received, the second sequence execution is postponed until the first sequence execution has left the first stage. The same applies to all the other stages of the project.

In short: **At any time, for each sequence, there is at most **one** sequence execution in a given stage.**

*Example:* 
```
keptn trigger delivery --project=sockshop --service=carts --image=docker.io/keptnexamples/carts --tag=0.11.1
keptn trigger delivery --project=sockshop --service=carts --image=docker.io/keptnexamples/carts --tag=0.11.2
```
*Behavior:* 
* The delivery of `carts:0.11.1` kicks off for the first stage, e.g.: dev.
* The delivery of `carts:0.11.2` is waiting as long as the delivery of `carts:0.11.1` in dev is not finished. 
* ...

## Acceptance Criteria
* [ ] The user can trigger multiple executions of a sequence at "the same time", however, the execution of the sequences is handled *sequentially* per stage.

## Definition of Done
* [ ] Changes implemented in *ShipyardController*
* [ ] Integration tests

**Comment by johannes-b** [comment]
Two updates on this issue: 

## 1. Allow parallel sequence executions on different services

As described above and based on the current implementation of this issue, the shipyard-controller queues all sequences as long as one is running in a stage (regardless of which service). This results in the following behavior, where each delivery is queued: 

![image](https://user-images.githubusercontent.com/729071/125413072-bb0e5a7b-9e22-4843-8ee3-f76944e722f7.png)

**Update**: The desired behavior should allow parallel executions of the same sequence in the same stage for different service:

![image](https://user-images.githubusercontent.com/729071/125414320-89041d0b-9bde-46c0-bf38-f7965c1ed612.png)
 
As a conclusion: There is at most one service execution in a given stage **per service**. 

## 2. A triggered approval task is not blocking other sequences.

If a sequence is in an approval state, meaning that it has a `approval.triggered` without the corresponding `approval.finished`, other sequences are allowed to get executed: 

![image](https://user-images.githubusercontent.com/729071/125416285-6bc02966-5cf6-4e3b-b246-2a9f9a4b245a.png)
