### ISSUE TITLE
Controls for pausing/resuming/aborting task sequences

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#3798]
## User Story
As a user, I want to be able to pause/resume or abort task sequences via the Keptn Bridge.

### Details

The Bridge shall support the controls to `pause`, `resume`, and `abort` a sequence. 

Implementation detail: Please decide which option works best and is the most user-friendliest approach. 

*Bridge - Option 1:*
![image](https://user-images.githubusercontent.com/729071/114419170-7fc4fe80-9bb3-11eb-836b-7a7f445cb76e.png)

*Bridge - Option 2:*
![image](https://user-images.githubusercontent.com/729071/114507376-5350c700-9c33-11eb-98a7-167619c02c30.png)

*Bridge - Option 3:* 
![image](https://user-images.githubusercontent.com/729071/122428882-9c562c00-cf92-11eb-8721-ee29d9b0ecc3.png)

*Expected behavior:*
- When clicking the `pause` button: 
  - The current (last triggered) task will finish, but the next task in the sequence will not be triggered. 
  - The Bridge shows the `resume` button.
  - The Bridge displays the status of the sequence: *delivery paused*
- When clicking the `resume` button:
  - The next task in the current sequence will be triggered and the sequence execution continues. 
  - The Bridge displays the status of the sequence: *delivery resumed* 
- When clicking the `abort` button:
  - The current (last triggered) task will finish, but the next task will not be triggered. Instead, the sequence ends with an aborted status.
  - The Bridge displays the status of the sequence: *delivery aborted* 

## Acceptance Criteria

* [ ] User is able to see the pause/resume/abort  buttons. When the user clicks a button the respective event is sent
* [ ] Feature can be disabled / enabled with a feature flag

## Definition of Done
* [ ] Story is implemented in th Bridge
* [ ] Documentation is updated

## Dependencies
#3783

**Comment by johannes-b** [comment]
Poll: which Option 1 - 3  should we use?

**Comment by laneli** [comment]
We are going to implement 1 and 3 and additionally add a confirmation to abort the sequence, so that it cannot be aborted accidentally.
