### ISSUE TITLE
Allow importing a project from an existing Git upstream

### ISSUE THREAD

**Issue by donovanmuller** [keptn/keptn#3809]
**Is your feature request related to a problem? Please describe.**
Currently there is no command to import and existing Keptn project from an existing Git upstream. For example, you may deploy Keptn to a cluster and create new projects with Git upstreams (GitHub). If you install Keptn on another cluster, you cannot import the Keptn project based on the existing Git upstream (as far as I could see).

**Describe the solution you'd like**
A new `keptn import project` command that would import a Keptn project by specifying the Git upstream. As an example:

```console
$ keptn import project pod-tato-head \
    --git-user=$GIT_USER \
    --git-token=$GIT_TOKEN \
    --git-remote-url=$GIT_REMOTE_URL
Starting to import project
Project imported successfully
```

**Comment by donovanmuller** [comment]
This would still be very useful in an environment where Keptn is being installed on a new cluster that will replace an existing cluster etc.

**Comment by johannes-b** [comment]
A very similar idea of this feature is currently discussed here: https://github.com/keptn/keptn/issues/4335

**Comment by ekarlso** [comment]
Any idea on when development will be started on this? We've got lots of existing gitops repos and having to re-init alot would be a great hassle :)

**Comment by ekarlso** [comment]
@johannes-b If you can point me to how I can get started I can look at contributing to this myself :)

**Comment by johannes-b** [comment]
Hello @ekarlso, 

Sorry, I missed the comment.
To get started on that issue, I would propose to build the CLI command `keptn import project` analog to: `keptn create project` you can find here: https://github.com/keptn/keptn/blob/master/cli/cmd/create_project.go

In this case, the shipyard is not provided when executing the `keptn import` command, since it is already stored in the git repo.

**Comment by ekarlso** [comment]
Note from @johannes-b 
I have to correct myself, the CLI just checks the input data, but the actual job is then done by calling the API of the shipyard-controller. The implementation of the create project you can find here: https://github.com/keptn/go-utils/blob/master/pkg/api/utils/apiUtils.go#L77

**Comment by Im5tu** [comment]
Hey - as mentioned on [Slack](https://keptn.slack.com/archives/CNRCGFU3U/p1637574615180900) - we have the following scenario that would greatly benefit from this, and what I suspect will be a growing use case as the project grows in popularity:

- All of our k8s manifests are managed in a GitOps methodology using ArgoCD using the app of apps pattern
- We deploy N clusters via an orchestration cluster which keptn lives on
- We want to be able to declaratively define our layout for repeatability and auditability (financially regulated business)
- We would like to store things like Git credentials using sealed-secrets

Having the above would mean that we are able to drop and recreate the cluster(s) at will - thereby keeping an essence of immutability. I know this is kinda out of scope for this specific issue, but it would be great if for most commands (eg: create project) there was a corresponding resource that we could declaratively setup - this issue would be a great start of that :)

**Comment by bacherfl** [comment]
> Hey - as mentioned on [Slack](https://keptn.slack.com/archives/CNRCGFU3U/p1637574615180900) - we have the following scenario that would greatly benefit from this, and what I suspect will be a growing use case as the project grows in popularity:
> 
> * All of our k8s manifests are managed in a GitOps methodology using ArgoCD using the app of apps pattern
> * We deploy N clusters via an orchestration cluster which keptn lives on
> * We want to be able to declaratively define our layout for repeatability and auditability (financially regulated business)
> * We would like to store things like Git credentials using sealed-secrets
> 
> Having the above would mean that we are able to drop and recreate the cluster(s) at will - thereby keeping an essence of immutability. I know this is kinda out of scope for this specific issue, but it would be great if for most commands (eg: create project) there was a corresponding resource that we could declaratively setup - this issue would be a great start of that :)
> 
> Happy to answer any questions on our setup or scenario if helpful

Hi @Im5tu, I like the idea of having a declarative API for Keptn related entities. Actually, I have started a discussion around that topic a while back that I think goes into a similar direction, if you would like to check it out and maybe provide some ideas :) https://github.com/keptn/keptn/discussions/5296
