### ISSUE TITLE
Last Evaluation label is not visible in case of too many evaluations in the chart

### ISSUE THREAD

**Issue by Gevorgisk** [keptn/keptn#3811]
**Environment**

* Client OS (e.g., Linux, macOS, Windows):
* Keptn Version (`keptn version`):
* Kubernetes Cloud Provider (e.g., GKE, AKS):
* Kubernetes version (`kubectl version`):

**Affected Component**

**Describe the bug**
There are 50 number of evaluations generated on my Keptn instance. In this case the label of last generated evaluation is not visible (see screenshot.)

**To Reproduce**
1. Generate evaluations via API 50 or more
2. open Evaluations chart and take a look to the label of the last evaluation

**Expected behavior**
The label of last evaluation should be displayed successfully.

**Current behavior**
The label of last evaluation is not displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/14317365/115195055-978a0e80-a0ee-11eb-87fb-c04f7c3ed5c2.png)

**Comment by laneli** [comment]
Looks fine to me.
![image](https://user-images.githubusercontent.com/2674029/116236495-6bf6cc00-a75f-11eb-9343-6db35c181b1e.png)

When you reduce the width of the window every nth label is shown, which is also fine I think.
![image](https://user-images.githubusercontent.com/2674029/116236636-9b0d3d80-a75f-11eb-8378-93e2c3229f32.png)

But I fixed a small bug I encountered that is trying to read something of undefined. The heatmap is therefore not loading properly.
![image](https://user-images.githubusercontent.com/2674029/116237231-41594300-a760-11eb-8d8c-4970a19bbe0d.png)

**Comment by Gevorgisk** [comment]
I understand that the chart shows the label only for every nth result.
Question: Would it be better if we show the same way but started from the end and not the beginning? Which means the last result would always have a label.
I think this is important since customer would be interested more often in the last result and the label accordingly would be needed.
This is also important for e2e automation tests.

**Comment by laneli** [comment]
@Gevorgisk I filed a new issue regarding the change: https://github.com/keptn/keptn/issues/3943
