### ISSUE TITLE
Switch between the tabs Environment-Services, the expand/collapse icon is changed but Evaluation items remain expanded 

### ISSUE THREAD

**Issue by Gevorgisk** [keptn/keptn#3814]
**Environment**

* Client OS (e.g., Linux, macOS, Windows):
* Keptn Version (`keptn version`):
* Kubernetes Cloud Provider (e.g., GKE, AKS):
* Kubernetes version (`kubectl version`):

**Affected Component**

* [ ] Docs
* [ ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [x] Bridge
* [ ] Approval
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**
There is "getting-started" panel in Services page which expands/collapses evaluation menu items. And there is also arrow-icon which direction (up/down) shows the expand/collapse status of the menu. After switch between the tabs Environment-Services, the expand/collapse icon is changed but Evaluation items remained expanded.

**To Reproduce**

1. Go to Services page 
2. Click on "Getting-started"
3. Now the menu is expanded and the arrow points up(which is fine) see the 1st screenshot
![image](https://user-images.githubusercontent.com/14317365/115233789-9e2d7b80-a118-11eb-9acd-cefed3d424b3.png)

4. Now click on Environment and then back to Services tab
![image](https://user-images.githubusercontent.com/14317365/115234268-1eec7780-a119-11eb-9fb0-5719f38bcd24.png)
5. Take a look to the the direction of the arrow

**Expected behavior**
The direction of the arrow should not be changed if the menu still remains expanded.

**Current behavior**
The direction of the arrow has been changed, it shows down, which is the state of Collapsed menu.
![image](https://user-images.githubusercontent.com/14317365/115234133-fc5a5e80-a118-11eb-90e2-12a35931efe3.png)

**Screenshots**

**Additional context**

**Comment by laneli** [comment]
This specific bug is not reproduceable anymore, as the view was re-worked. But there is a similar behavior in the new view.
* Expand one service
* Expand a second service
* The first opened service is collapsed, but the icon is not updated

![image](https://user-images.githubusercontent.com/2674029/116072070-f3283f00-a68e-11eb-9692-1df7503961bf.png)
