### ISSUE TITLE
Slack-service: Include Dynatrace problem link in problem message

### ISSUE THREAD

**Issue by dirkwall** [keptn/keptn#385]

**Comment by robertjahn** [comment]
This feature will be useful in ChatOps Keptn Services such as Slack and MS Teams.   
Suggest something like this:

{
    "specversion":"0.2",
    "type":"sh.keptn.events.problem",
    "source":"dynatrace",
    "id":"{PID}",
    "time":"",
    "datacontenttype":"application/json",
    "shkeptncontext":"{PID}",
    "data": {
        **"problemUrl":"{ problemUrl }",    <<-----  NEW attribute**
        "State":"{State}",
        "ProblemID":"{ProblemID}",
        "PID":"{PID}",
        "ProblemTitle":"{ProblemTitle}",
        "ProblemDetails":{ProblemDetailsJSON},
        "ImpactedEntities":{ImpactedEntities},
        "ImpactedEntity":"{ImpactedEntity}"
    }
}

**Comment by robertjahn** [comment]
Also add the attribute
"{ProblemImpact}: Impact level of the problem. Possible values are APPLICATION, SERVICE, and INFRASTRUCTURE."

**Comment by dirkwall** [comment]
Slack-service has been replaced by https://github.com/keptn-contrib/notification-service
