### ISSUE TITLE
Keptn upgrade installs execution plane services on control-plane

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#3864]
I recently upgraded my Keptn installation from 0.8.1 to 0.8.2 via the `keptn upgrade` command.

Before the upgrade, I didn't have the execution plane service `jmeter-service` running. The upgrade procedure installed it, which was not desired.

Output:
```
keptn upgrade
* Warning: Your Keptn CLI version (0.8.2) and Keptn cluster version (0.8.1) don't match. This can lead to problems. Please make sure to use the same versions.
Helm Chart used for Keptn upgrade: https://storage.googleapis.com/keptn-installer/keptn-0.8.2.tgz

Please confirm that the provided cluster information is correct:
Cluster: gke_sai-research_us-central1-c_keptn-prometheus
Is this all correct? (y/n)
y
Do you want to upgrade Keptn version 0.8.1 to 0.8.2? (y/n)
y
Start upgrading Helm Chart keptn in namespace keptn
Finished upgrading Helm Chart keptn in namespace keptn
Upgrading of Keptn control plane has been successful.
Upgrading execution plane services for continuous-delivery use case.
Start upgrading Helm Chart helm-service in namespace keptn
Finished upgrading Helm Chart helm-service in namespace keptn
Start upgrading Helm Chart jmeter-service in namespace keptn
Finished upgrading Helm Chart jmeter-service in namespace keptn
Keptn has been successfully upgraded on your cluster.
juergen.etzlstorfer@TAG009441793070 Downloads % keptn version

Keptn CLI version: 0.8.2
Keptn cluster version: 0.8.2

Daily version check is enabled.
Keptn will collect statistical data and will notify about new versions and security patches for Keptn. Details can be found at: https://keptn.sh/docs/0.8.x/reference/version_check
---------------------------------------------------
* To disable the daily version check, please execute:
 - keptn set config AutomaticVersionCheck false
```

Is there any way to tell the `keptn upgrade` command not to install the execution plane services?
If not, this should be considered a bug.

**Desired behavior**
When I upgrade my Keptn installation, only the currently installed services should be updated and only needed core services that might have been added in a new release should be added. It should not install execution plane services that haven't been installed before.

**Comment by christian-kreuzberger-dtx** [comment]
If you had continuous-delivery installed before, jmeter-service and helm-service will be upgraded/installed aswell. If not, then we do not install it according to this code in the CLI:
https://github.com/keptn/keptn/blob/12f079a83cd3dc1b817ad1ae327cd272003d63b0/cli/cmd/upgrade.go#L257-L274

Nevertheless, we will take a look.

**Comment by christian-kreuzberger-dtx** [comment]
Please try to use the following command and verify if continuous-delivery is set to true/false:
```
helm get values -n keptn keptn

USER-SUPPLIED VALUES:
continuous-delivery:
  enabled: false
  openshift:
    enabled: false
control-plane:
  apiGatewayNginx:
    type: ClusterIP
  bridge:
    installationType: QUALITY_GATES,CONTINUOUS_OPERATIONS
  enabled: true

```

**Comment by jetzlstorfer** [comment]
Thanks - that really helps!
I could verify that I installed it via the `continuous-delivery` option and removed the services later on.
