### ISSUE TITLE
keptn 0.8.2 OSX build failed for Mojave

### ISSUE THREAD

**Issue by chenrui333** [keptn/keptn#3866]
Your issue may already be reported! Please search on the [issue tracker](https://github.com/keptn/keptn/issues) before creating a new one.

**Environment**

* Client OS (e.g., Linux, macOS, Windows): MacOS
* Keptn Version (`keptn version`): 0.8.2
* Kubernetes Cloud Provider (e.g., GKE, AKS):
* Kubernetes version (`kubectl version`):

**Affected Component**

* [ ] Docs
* [x] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [ ] Bridge
* [ ] Approval
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>test failure</summary>

```
==> /usr/local/Cellar/keptn/0.8.2/bin/keptn version 2>&1
sh: /usr/local/Cellar/keptn/0.8.2/bin/keptn: cannot execute binary file
Error: keptn: failed
An exception occurred within a child process:
  Minitest::Assertion: Expected: 0
  Actual: 126
```

</details>

Full build log is in here, https://github.com/Homebrew/homebrew-core/runs/2422025743
relates to https://github.com/Homebrew/homebrew-core/pull/75807

**Comment by carlocab** [comment]
This is likely a `brew` issue, @chenrui333. See https://github.com/Homebrew/homebrew-core/pull/75880.

**Comment by christian-kreuzberger-dtx** [comment]
Hi,

is this issue still present?

**Comment by carlocab** [comment]
No, it isn't. Please close this. Thanks for having a look!
