### ISSUE TITLE
Decide whether to use 'artifact' or 'artefact' and follow through in all projects

### ISSUE THREAD

**Issue by dirkwall** [keptn/keptn#387]
A simple poll showed a trend towards `artifact` (American English). Make sure this is considered in all of the following areas
- CLI
- documentation
- source code incl. comments
- website

This will result in a breaking change because the identifier of the new-artifact event changes. Make sure to include this information in the release notes of each service and in the overall release notes on the keptn/keptn readme on GitHub.

**Comment by johannes-b** [comment]
Repos to check:

- [ ] installer
- [ ] github-service
- [ ] jenkins-service
- [ ] pitometer-service
- [ ] control
- [ ] keptn.github.io
- [ ] keptn   website: https://keptn.sh
- [ ] keptn
- [ ] eventbroker-ext
- [ ] authenticator
- [ ] bridge
- [ ] dynatrace-service
- [ ] servicenow-service
- [ ] eventbroker
- [ ] slack-service
- [ ] examples
- [ ] pitometer-source-dynatrace
- [ ] pitometer
- [ ] pitometer-grader-thresholds
- [ ] pitometer-source-prometheus
- [ ] toc
- [ ] keptn-specification
- [ ] deploy-service
- [ ] keptn-service-template
- [ ] community
