### ISSUE TITLE
Implement deploy-service

### ISSUE THREAD

**Issue by dirkwall** [keptn/keptn#388]
A first version of the deploy-service has already been implemented (https://github.com/keptn/deploy-service). Extend and bulletproof this version, so that it can be used for deploying artifacts instead of calling a Jenkins pipeline.
Please consider writing tests, if appropriate, and also error handling. The resulting container should be as small as possible, so I suggest go for a multi-stage Dockerfile that only includes the binary in a small base image.

**Comment by agrimmer** [comment]
Implementation can be found in https://github.com/keptn/deploy-service/tree/develop.
The adoptions in the documentation are missing.

**Comment by agrimmer** [comment]
Now, this service is called [helm-service](https://github.com/keptn/helm-service/).
New status: Documentation is missing
