### ISSUE TITLE
Implement 'run tests' service

### ISSUE THREAD

**Issue by dirkwall** [keptn/keptn#389]
Implement a small go service that executes tests like the Jenkins pipeline 'run tests' does. If this service is primarily focused on executing JMeter tests, we could implement it as a jmeter-service, that gets its parameters through environment variables, so it can be reused for functional and performance tests.

**Comment by agrimmer** [comment]
The implementation of this service can be found here: [jmeter-service](https://github.com/keptn/jmeter-service/).
Status: Documentation is missing
