### ISSUE TITLE
Keptn installation fails when upgrading to newer version

### ISSUE THREAD

**Issue by Kirdock** [keptn/keptn#3890]
When I try to upgrade from `0.8.1-dev-PR-3529` to `0.8.2` via the `install` command the following error appears 

```
Error: Could not complete Keptn installation: Error when installing/upgrading Helm Chart keptn in namespace keptn: another operation (install/upgrade/rollback) is in progress
```

OS: Windows 10
CLI Version: 0.8.2

**Comment by christian-kreuzberger-dtx** [comment]
This is most likely due to the fact that you aborted the previous installation.

Helm checks if an installation is currently ongoing, and aborts it afterward.

Nevertheless, this is something that the Keptn CLI could check for.

**Comment by christian-kreuzberger-dtx** [comment]
Installation should eventually timeout (status should no longer be `is in progress`)
