### ISSUE TITLE
GetServiceResource function only fetches title

### ISSUE THREAD

**Issue by TannerGabriel** [keptn/keptn#3902]
The `GetAllServiceResources` function of the Go-Utils as well as the corresponding API endpoint `/project/{projectName}/stage/{stageName}/service/{serviceName}/resource` specify that they return a `resouces` object including fields like `resourceURI`, `resourceContent` and `metadata` but in reality they only return the `resourceURI` with the other two fields being constantly empty.

Expected return type:

```
{
  "nextPageKey": "string",
  "totalCount": 0,
  "pageSize": 0,
  "resources": [
    {
      "resourceURI": "string",
      "resourceContent": "string",
      "metadata": {
        "upstreamURL": "string",
        "version": "string",
        "branch": "string"
      }
    }
  ]
}
```

Actual response:

```
{
  "nextPageKey": "0",
  "resources": [
    { "resourceURI": "/basic.py" },
    { "resourceURI": "/helm/carts/Chart.yaml" },
    { "resourceURI": "/helm/carts/templates/deployment.yaml" },
    { "resourceURI": "/helm/carts/templates/service.yaml" },
    { "resourceURI": "/helm/carts/values.yaml" },
    { "resourceURI": "/helm/carts-generated/Chart.yaml" },
    {
      "resourceURI": "/helm/carts-generated/templates/carts-istio-destinationrule.yaml"
    },
    {
      "resourceURI": "/helm/carts-generated/templates/carts-istio-virtualservice.yaml"
    },
    { "resourceURI": "/jmeter/basiccheck.jmx" },
    { "resourceURI": "/locust/basic.py" },
    { "resourceURI": "/locust/load.py" },
    { "resourceURI": "/locust/locust.conf" },
    { "resourceURI": "/locust/locust.conf.yaml" },
    { "resourceURI": "/locust/locust.py" },
    { "resourceURI": "/locust.conf" },
    { "resourceURI": "/locust.py" },
    { "resourceURI": "/metadata.yaml" }
  ],
  "totalCount": 17
}

```

**Environment**

* Client OS (e.g., Linux, macOS, Windows): Ubuntu 20.04
* Keptn Version (`keptn version`): v0.8
* Kubernetes Cloud Provider (e.g., GKE, AKS): GKE

**Affected Component**

* [X] Api
* [X] [Go-utils](https://github.com/keptn/go-utils)

**To Reproduce**

1. Create Keptn project
2. Add resource to service `keptn add-resource --project=sockshop --service=carts --stage=dev --resource=basic.py --resourceUri=locust/basic.py` 
3. Call [GetServiceResource](https://github.com/keptn/go-utils/blob/8a71dcd5a7edec02c255d839f9d5dfe3a660fd35/pkg/api/utils/resourceUtils.go#L171) or make a request to the `/project/{projectName}/stage/{stageName}/service/{serviceName}/resource` endpoint

**Expected behavior**
Either return the entire resource object or only return the `resourceURI` as a string and not the full `resources` object.

**Comment by christian-kreuzberger-dtx** [comment]
Can you double check which endpoint you are talking about?
If you're talking about the `/project/{projectName}/stage/{stageName}/service/{serviceName}/resource` endpoint, that one is working as expected, at least according to our swagger docs:
![image](https://user-images.githubusercontent.com/56065213/116269129-3c0af100-a77e-11eb-90ff-9728680444f4.png)

If you're talking about the `/project/{projectName}/stage/{stageName}/service/{serviceName}/resource/{resourceURI}` endpoint (which should be the same as called by `GetServiceResource`) then there is a bug.

**Comment by TannerGabriel** [comment]
The `/project/{projectName}/stage/{stageName}/service/{serviceName}/resource` is used for the `GetAllServiceResources`, which returns an array of `resource` objects and shows the behavior I pointed out above. The `GetServiceResource` seems to work fine but the return type of `GetAllServiceResources` still seems to be wrong.

**Comment by christian-kreuzberger-dtx** [comment]
Okay, @bacherfl or @warber can one of you take a look at this?
