### ISSUE TITLE
Show currently selected project in the bridge

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#3912]
Currently, as user I can not see which project I am working.
![image](https://user-images.githubusercontent.com/7677092/116414733-024af080-a839-11eb-97c2-e164e94dda40.png)

**Feature request:**
As a user, I want to be able to see the project I am working in selected in the header of the bridge.

Instead of "Keptn / Choose Project" it should say "Keptn / Hipstershp" or whatever project I am in currently.

**Comment by johannes-b** [comment]
Hi @jetzlstorfer, this problem has already been encountered and fixed: https://github.com/keptn/keptn/issues/3853

But thanks for reporting!

**Comment by jetzlstorfer** [comment]
Thanks @johannes-b !

Another thing that is related to this issue: when selecting a project from the `drop-down` but then going back to the overview screen and selecting another project, the old project stays selected in the dropdown but the URL shows the "new" project that I am currently seeing.
![image](https://user-images.githubusercontent.com/7677092/116523510-97e88d80-a8d6-11eb-9d8a-1ceacc072767.png)

If this is also fixed in #3853 please close this issue again

**Comment by laneli** [comment]
It seems to be fixed with #3853.
