### ISSUE TITLE
JMeter service doesnt work for regular http/https URL as it infer the default http/https port from the URL

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#3916]
**Environment**
Keptn 0.8 installation running e.g: Argo Rollout tutorial. Automated Testing with JMeter fails!

**Issue**
It seems that with the following change - https://github.com/keptn/keptn/commit/e48cf151297622ad790cdd98f84df78333978dd9 - the jmeter-service became too restrictive when parsing URLs as "regular" URLs that do not contain a port result in an error.

Here is an example of an error of one of our tutorials that deploys an app on port 80:
```
Jmeter-service cannot reach URL http://simplenode.demo-rollout-staging.keptn-demo.alliances.dynatracelabs.com/: dial tcp: address simplenode.demo-rollout-staging.keptn-demo.alliances.dynatracelabs.com: missing port in address
```

This means that URLs like http://myservice or https://myservice will result into a failure as the jmeter-service currently only works if the port is included in the url, e.g: http://myservice:80 or https://myservice:443

This for me is a big issue as the default ports 80 and 443 are typically NOT part of the URL

**Comment by christian-kreuzberger-dtx** [comment]
For now the obvious workaround is to add the port to `deploymentURI`, but we'll work on a fix and restore the functionality as it was before.
