### ISSUE TITLE
Keptn bridge - Error pages

### ISSUE THREAD

**Issue by Kavindu-Dodan** [keptn/keptn#3925]
**Background**

Keptn bridge is a component which consists of  an Angular UI and an Express server. Right now, Express server is minimalistic and acts like a proxy between UI and other Keptn components (ex:- Include X Token for requests and facilitate responses).

However, with feature implementations such as #3448 & #3880 there are considerable logic introduced in server layer. And these features require error handling.

**Solution**

I can think about two approaches to implement error handling,

1. Redirect to Angular layer : Angular expose error routing
2. Minimalistic error templates in Express layer : Pug [1] is a good candidate

If we can agree on the approach, I am willing to contribute the first PRs for this feature request. 

[1] - https://www.npmjs.com/package/pug

**Comment by Kavindu-Dodan** [comment]
Discussed the topic with @ermin-muratovic & following was decided for the first iteration,

- Use a minimalistic Express template to generate basic error pages 
- Use following design, inspired by Bridge Angular UI error page

![image](https://user-images.githubusercontent.com/8186721/116693844-baee6c80-a9be-11eb-8904-27d50e1adb04.png)

 I will investigate about pug [1] and work on a flexible solution. 

[1] - https://www.npmjs.com/package/pug

**Comment by johannes-b** [comment]
Implemented by: https://github.com/keptn/keptn/pull/3952
