### ISSUE TITLE
Basic authentication via URL not possible

### ISSUE THREAD

**Issue by Kirdock** [keptn/keptn#3935]
If basic authentication is enabled, accessing `https://username:password@host/bridge/...` should automatically login the user.

**Comment by laneli** [comment]
https://docs.microsoft.com/en-US/troubleshoot/browsers/name-and-password-not-supported-in-website-address
https://bugs.chromium.org/p/chromium/issues/detail?id=82250#c7
https://medium.com/@lmakarov/say-goodbye-to-urls-with-embedded-credentials-b051f6c7b6a3

Embedded credentials are not supported anymore.

**Comment by laneli** [comment]
I also checked if it can still be parsed from the url but it seems that Chrome (where I tested it) removes it before sending it to the server.
Taking into account that it is actually not supported anymore i close this as **Won't Fix**.

**Comment by christian-kreuzberger-dtx** [comment]
FYI: I have removed it from the milestone and added a wontfix label.
