### ISSUE TITLE
Fix tests in travis builds

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#394]
Due to the restructuring of the repos #327, the tests of the core components have no PR-cluster available. Hence, these tests currently fail.

Make sure that the travis build of the following repos triggers the unit tests:
**core**
- [ ] control
- [ ] authenticator
- [ ] eventbroker
- [ ] eventbroker-ext
- [ ] bridge

**uniform**
- [ ] github-service
- [ ] jenkins-service
- [ ] servicenow-service
- [ ] pitometer-service
- [ ] dynatrace-service
- [ ] jmeter-service
- [ ] helm-service 
- [ ] slack-service

**Comment by dirkwall** [comment]
Reevaluate after migrating to monorepo.

**Comment by dirkwall** [comment]
@agrimmer is this still relevant?

**Comment by agrimmer** [comment]
No, this issue is outdated as lots of the components do not exist anymore.
Instead, we need a new issue for ensuring that our Go tests are executed in each Travis pipeline.
Currently, the Go tests are only executed for the CLI.

**Comment by agrimmer** [comment]
This issue is handled with #1083
