### ISSUE TITLE
Display question mark (no loading icon) for an open approval

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#3942]
## User Story
As a user, I want to get a question mark when there is an open approval since the loading icon indicates that there is something running

*Sequence screen:*
![image](https://user-images.githubusercontent.com/729071/116984092-28eea880-accb-11eb-9c06-63138a3ea5a4.png)

*Sequene screen:*
![image](https://user-images.githubusercontent.com/729071/116984207-4de31b80-accb-11eb-8714-f9553b1724a1.png)

## Acceptance Criteria

* [ ] Whenever there is an approval task, show the question mark instead of the loading icon

## Definition of Done
* [ ] Story is implemented in the Bridge

**Comment by laneli** [comment]
It has to be adapted for these components:
- [ ] Environment: Tile
- [ ] Sequence: List
- [ ] Sequence: Detail
