### ISSUE TITLE
Show every nth label in heatmap starting from end

### ISSUE THREAD

**Issue by laneli** [keptn/keptn#3943]
Related to #3811 
In consultation with @Gevorgisk we should show every nth label on the heatmap on small display sizes but starting from the end.
This means, that the last label is always visible - the evaluation the user is probably most interested in. Also see https://github.com/keptn/keptn/issues/3811#issuecomment-831838832

**Comment by warber** [comment]
If the library supports configuring the x-axis, then apply the configuration setting.
Otherwise, this issue will be closed with "wontfix".
