### ISSUE TITLE
Try out Keptn + Argo Rollouts and document UX flaws

### ISSUE THREAD

**Issue by warber** [keptn/keptn#3945]
## Action Item

Try out and get familiar with doing Canary Deployments using Keptn + Argo Rollouts.
For this, take a look at the already existing Keptn Turorial [1].

Identify possible UX flaws in the Keptn Bridge while following the Tutorial, e.g.:
* Document cases where the user-flow is broken, e.g. identify "blind-ended" screens where the user is not able to know what to do next or where the information shown on the screen does not make sense
* Find out whether the information shown to the user make sense, so that the actions performed during this use case are visible and reasonable

Note: This issue is timeboxed to 1 day

### Resources
[1] [Argo Rollout Tutorial](https://tutorials.keptn.sh/tutorials/keptn-argo-rollouts-dynatrace-08-on-k3s/index.html?index=../..keptn08x#0)

**Comment by Kirdock** [comment]
I was not even able to execute the script. Maybe I did something wrong.

Provider: GCP
Machine: Debian GNU/Linux 10 (buster), e2-standard-8 (8 vCPUs, 32 GB memory)

# Without specifying a domain
This error occurred just one time
```
#######################################>
# Installing Keptn for Continuous Delivery (Control & Execution Plane)
#######################################>
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /etc/rancher/k3s/k3s.yaml
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /etc/rancher/k3s/k3s.yaml
Release "keptn" does not exist. Installing it now.
Error: rate: Wait(n=1) would exceed context deadline
```
The following error occurred every time:
```
#######################################>
# Creating Dynatrace Secret!
#######################################>
Calling HTTP POST https://keptn.${myIP}/api/secrets/v1/secret
curl: (6) Could not resolve host: keptn.${myIP}
```

# With a domain
```
#######################################>
# Installing Gitea for upstream git
#######################################>
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /etc/rancher/k3s/k3s.yaml
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /etc/rancher/k3s/k3s.yaml
"gitea-charts" has been added to your repositories
Create namespace for git
namespace/git created
Install gitea via Helmchart
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /etc/rancher/k3s/k3s.yaml
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /etc/rancher/k3s/k3s.yaml
Error: template: gitea/templates/gitea/statefulset.yaml:19:28: executing "gitea/templates/gitea/statefulset.yaml" at <include (print $.Template.BasePath "/gitea/config.yaml") .>: error calling include: template: gitea/templates/gitea/config.yaml:53:84: executing "gitea/templates/gitea/config.yaml" at <0>: can't evaluate field host in type string
```
