### ISSUE TITLE
Selection change in heatmap does not always update SLO table - needs second click

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#4007]
## Enhancement request

*Selection change in heatmap doesn't always update SLO table - needs a second click*

I noticed this when clicking through the heatmap to view historical results. It seems that while the click in the heatmap will change the selection in the heatmap the table underneath doesn't always get updated. 

**Situation:** Every second time I have to click twice for the table to be refreshed

* **Click 1**:
![image](https://user-images.githubusercontent.com/675886/117449310-1f21ab00-af40-11eb-9c40-d116b240466d.png)

* **Click 2**: *Still shows the result from previously selected entry*
![image](https://user-images.githubusercontent.com/675886/117449368-31034e00-af40-11eb-9b94-63757e06ae79.png)

* Either mouse move or Click 3 will now get me to the right table information:
![image](https://user-images.githubusercontent.com/675886/117449636-7f185180-af40-11eb-8391-e2817b90d1be.png)

## Action item
- [ ] Investigation why the SLI breakdown does not get updated

## Acceptance criteria
- [ ] As a user, I can click through the heatmap and get the current SLI breakdown displayed.

**Comment by warber** [comment]
Note: This issue only appears if clicking on the highlighted reference evaluation, or clicking on another evaluation when the reference evaluation is currently selected.
