### ISSUE TITLE
Improvement for Bridge when displaying problems that are resolved

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#4009]
This is more an improvement request for displaying information about problems

If a Problem triggers a sequence then the problem is shown in RED in the sequence screen. That also makes sense as long as the problem is open. In case a problem gets closed / resolved it is a bit confusing that the item still shows in RED. I would rather then show it in a different color, e.g: GREY or BLUE to indicate that the problem is no longer an active problem

![image](https://user-images.githubusercontent.com/675886/117465706-3ff2fc00-af52-11eb-8a9a-7a6670d4a433.png)

**Comment by johannes-b** [comment]
This is related to the issue: https://github.com/keptn/keptn/issues/7129

Since the Bridge is not displaying problems, which work as trigger for a remediation sequence, I would like to close this issue.
