### ISSUE TITLE
Forward log messages of execution plane Keptn-services to Keptn core

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#4030]
# User Story: Forward log messages of execution plane Keptn-services to Keptn core

As a user, I want to see error (log) message of my execution plane Keptn-services without having to use `kubectl`. Therefore, those error messages need to be forwarded to Keptn core.

## Detail

Execution plane Keptn-services are usually started on Kubernetes and have a distributor as a sidecar. The service itself does not know about the sidecar, though it communicates with it via some REST API Endpoints (that are basically forwarded to Keptn control-plane).
Currently, log messages of the Keptn-service are just printed to stdout/stderr (depending on the logging framework). Those log messages can only be seen by calling `kubectl -n some-namespace logs deployment/my-service my-service`.

### Proposal
Capturing errors can be done in the Distributor of a Keptn Service, which would capture error logs (sent to std::err) of the side-car container (the service) and forward them to the keptn control plane
:exclamation: Note that calling the errors API shall be limited to one call per minute. (Implement `throttler` in go-utils)
:exclamation: Beware of possible refactoring tasks in the distributor
:exclamation: This operation must be allowed to fail (e.g. old Keptn version vs. new Distributor)

## Definition of Done

- [ ] Error Log Messages of Keptn-services are forwarded to Keptn core in a way that does not require implementation changes in the Keptn-service.

## Dependencies
#4032 

## Resources

- How to capture logs from as a side-car container https://superuser.com/a/1530503

**Comment by bacherfl** [comment]
In an internal meeting we agreed to intercept `*.finished` events with status `errored` and/or result `fail` and use the message payload from those to send requests to the log ingestion API. This way, we do not have to gather the logs via the K8s API, or a hostPath volume, but we can use our event based approach instead.
Additionally, we will introduce a new event type for the purpose of sending log information to the log ingestion API via the distributor, even when the respective event is not necessarily related to the execution of a specific task sequence of a Keptn project (e.g. if there is an error in the dynatrace-service during the synchronisation of projects)
