### ISSUE TITLE
Display Current Errors of a service

### ISSUE THREAD

**Issue by warber** [keptn/keptn#4036]
## User Story
As a user, I want to be able to see all the current errors of a particular Keptn service.

### Details

Type of Errors: In a Keptn-service, two types of errors can occur:

* Task-related: When executing a specific task, an error occurs. This already results in a `xyz.finished` event with **status** fail.
* Non-task-related: For example, the Keptn-service can not start, or an API endpoint can`t be reached. This functionality is not related to the execution of a task.

Mockup:
![image](https://user-images.githubusercontent.com/72415058/117800982-0c66e900-b254-11eb-88f5-4a531b3d636d.png)

(!) Please see KEP 45: https://github.com/keptn/enhancement-proposals/pull/45

### Acceptance Criteria

* The user is able to see the error messages related to the logs of a service. (Service Errors Tab)
* The user is able to see the error messages related to cloud events with `status=="fail"` and `source=="<service-name>"`  (Sequence Error Tab)
* The user is able to load older error messages via a link shown in the error component
* The error logs shall be polled every x seconds to be able to see up-to-date errors.

## Definition of Done
- [x] Feature implemented and (manually) tested

**Comment by laneli** [comment]
As discussed on 10.06.2021
* There will be only 1 tab, all errors are shown in one single table
* When there is a shkeptncontext set and task name, it is related to a sequence and a link to related sequence is shown
