### ISSUE TITLE
Verify adherence to cloudevents specification 0.2

### ISSUE THREAD

**Issue by dirkwall** [keptn/keptn#405]
It seems that we don't strictly follow the cloudevent 0.2 specification in our event definitions.
https://github.com/cloudevents/spec/blob/v0.2/spec.md

For example, the 0.2 spec says that there is a field with the name `contenttype` and not `datacontenttype`. The field `datacontenttype` is from the current working draft 0.3-wip on the master branch in the above-mentioned repository.

This also includes the documentation on the website and everywhere else.

**Comment by agrimmer** [comment]
Going forward our services will be written in Go and here it is easy to adhere to the cloudevents spec by using the library.
