### ISSUE TITLE
Evaluation result can be viewed from Sequence but not from Service screen

### ISSUE THREAD

**Issue by laneli** [keptn/keptn#4056]
**Describe the bug**
I have configured a very basic shipyard only for dev stage, which is only deploying on dev environment.
For test purposes I manually triggered an evaluation for this stage.
I can open the results of the evaluation only from the sequence. The services view does not show any evaluation results.

![image](https://user-images.githubusercontent.com/2674029/117941563-85c11300-b30a-11eb-90fa-a923fcdf4c51.png)
![image](https://user-images.githubusercontent.com/2674029/117941659-a12c1e00-b30a-11eb-991c-1981e3df7094.png)
![image](https://user-images.githubusercontent.com/2674029/117941530-7a6de780-b30a-11eb-9afa-b9bd25bd65e8.png)

**Expected behavior**
I would expect that the evaluation results are also shown in the Services screen.

Shipyard:
`
apiVersion: "spec.keptn.sh/0.2.0"
kind: "Shipyard"
metadata:
  name: "shipyard-sockshop"
spec:
  stages:
    - name: "dev"
      sequences:
        - name: "delivery"
          tasks:
            - name: "deployment"
              properties:
                deploymentstrategy: "direct"
            - name: "approval"
              properties:
                pass: "automatic"
                warning: "automatic"
            - name: "release"
        - name: "delivery-direct"
          tasks:
            - name: "deployment"
              properties:
                deploymentstrategy: "direct"
            - name: "release"
`

**Comment by Kirdock** [comment]
Probably the cause: The sequence of the deployments is defined by the latest delivery sequence and if it does not exist, it takes the latest evaluation sequence. The latest delivery sequence does not have any evaluation trace and that's why the evaluations are not fetched
