### ISSUE TITLE
Dependency incompatibility in services using helm library

### ISSUE THREAD

**Issue by bacherfl** [keptn/keptn#4063]
We are having problems when we try to update kubernetes related libraries, such as

```
k8s.io/api 
k8s.io/apimachinery 
k8s.io/cli-runtime 
k8s.io/client-go 
k8s.io/kubectl 
```

These problems occur in services that have a dependency to the `helm.sh/helm` library, and the main reason for that being the following `replace` that needs to be added if the helm library needs to be used.

```
github.com/Azure/go-autorest => github.com/Azure/go-autorest v13.3.2+incompatible
```

This is a problem especially because the [keptn/kubernetes-utils](https://github.com/keptn/kubernetes-utils) also have a dependency to helm, and is used by quite a lot of services.

Therefore, we will need to evaluate which of the services that are using the kubernetes-utils actually need the helm library, and which services do not require helm.
Further, if a service only uses the kubernetes-utils to, e.g. initialize a K8s client object, the dependency to the kubernetes-utils might also be omitted in the respective service.

**Note:** The lates version of helm, v3.5.4 does have another `replace`directive, and does not seem to use `github.com/Azure/go-autorest ` anymore: https://github.com/helm/helm/blob/v3.5.4/go.mod - so maybe upgrading the helm v3.5.4 in services that are using this library might already help to relieve that problem to some extend.

Also, a lot of incompatibilities seem to be caused by openapi dependencies, such as in the `go.mod` file of the [keptn/go-utils](https://github.com/keptn/go-utils):

```
github.com/go-openapi/errors v0.20.0
github.com/go-openapi/strfmt v0.20.1
github.com/go-openapi/swag v0.19.14
github.com/go-openapi/validate v0.20.2
```

We should go through all services (especially the go-utils) and check whether we really need those dependencies. If not, we should remove them.

**Comment by warber** [comment]
This issue is timeboxed to: **1d**
