### ISSUE TITLE
CLI: Replace  exechelper.ExecuteCommand with keptnutils.ExecuteCommand

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#4068]
During review of our existing code-base, we noticed this little helper function in CLI:

https://github.com/keptn/keptn/blob/e72dd50418ce70efc1b565f1ecf738b05f0ed750/cli/pkg/exechelper/exec_helper.go#L11-L23

This function should be removed, and calls should be replaced with go-utils `keptnutils.ExecuteCommand`.
:exclamation: The signatures differ, please take into account converting existing calls with strings into calls with []string, e.g.:

```
	res, err = exechelper.ExecuteCommand("kubectl", "get gateway -n "+gatewayNamespace+" "+gatewayName)
```

Needs to be changed to

```
	res, err = keptnutils.ExecuteCommand("kubectl", []string{"get", "gateway", "-n", ...})
```

In addition, the dependency `"github.com/mattn/go-shellwords"` should be removed from CLI.

# Definition of Done

- [ ] Helper Function `ExecuteCommand` is removed from CLI package, and `keptnutils.ExecuteCommand` is used instead
- [ ] Dependency `"github.com/mattn/go-shellwords"` is gone from CLI

**Comment by adigeak** [comment]
giving it a try.

**Comment by christian-kreuzberger-dtx** [comment]
Hi @adigeak , any luck so far?

**Comment by adigeak** [comment]
yeah I'm working on this will complete before community meeting.
