### ISSUE TITLE
Service tile breaks based on image:tag > `carts:353ff51.1`

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#4130]
### Problem 
When triggering a delivery for the image: `carts:353ff51.1` the UI component for the service breaks due to an invalid version: 353ff51.1

![image](https://user-images.githubusercontent.com/729071/118807586-c986c000-b8a8-11eb-8958-fac11afe55f2.png)

I don't see the reason, why 353ff51.1 is an invalid number.

## Acceptance criteria
- [ ]  As a user, I can deploy an image with the tag: `353ff51.1`

**Comment by christian-kreuzberger-dtx** [comment]
Pretty sure this is where it breakes:
https://github.com/keptn/keptn/blob/8dc6101c940082e151c66d1b0f5553bfd2c243ec/bridge/client/app/_models/project.ts#L100
