### ISSUE TITLE
UI Bug in Keptn Public demo

### ISSUE THREAD

**Issue by adigeak** [keptn/keptn#4131]
When we try to switch between the graph in the service page the size heatmap shrinks.  

**Environment**

* public demo of [keptn](https://keptn.public.demo.keptn.sh/bridge/dashboard)
* Web Browser Mozilla firefox
* zoom 100%

**Affected Component**

* [ ] Docs
* [X] Web Interface 
* [ ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [ ] Bridge
* [ ] Approval
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**

It is related to the keptn public demo when try to switch between the graph in the services of any project. The size of the heatmap abruptly shrink and remain same. When you refresh is again becomes normal. 

**To Reproduce**

1. Go to firefox
2. Open the url of [keptn public demo](https://keptn.public.demo.keptn.sh/)
3. Select project litmus and go to the services screen.
4. Open a service. Switch from heatmap to chart and back to heatmap.
5. Bug the size of heatmap reduce abruptly. 

**Expected behavior**

It should remain stretched over. 
**Current behavior**

It shrinks and remain like that until refreshed. 
**Screenshots**

![Screenshot from 2021-05-19 10-46-04](https://user-images.githubusercontent.com/31953737/118826762-62cdca80-b8d9-11eb-8bec-07e39b07ec1f.png)
![Screenshot from 2021-05-19 10-46-13](https://user-images.githubusercontent.com/31953737/118826773-65302480-b8d9-11eb-9b51-0b2006fcdb7f.png)
![Screenshot from 2021-05-19 10-46-16](https://user-images.githubusercontent.com/31953737/118826782-66f9e800-b8d9-11eb-958a-c2161ccfa919.png)

**Comment by johannes-b** [comment]
Hello @adigeak,
many thanks for reporting this issue! Luckily, this is already fixed and will be released with Keptn 0.8.3. See here: https://github.com/keptn/keptn/issues/3851

I'm so free to close this issue then.

**Comment by adigeak** [comment]
Sure please update on the Public demo.
