### ISSUE TITLE
Improve log output of installer

### ISSUE THREAD

**Issue by dirkwall** [keptn/keptn#414]
![image](https://user-images.githubusercontent.com/15996364/58789903-8796dd80-85ef-11e9-8f23-dc89adfe495e.png)

After asking if the provided information is correct, write "Starting the installation of keptn". A few lines down it says exactly that, but at this time the installation has already started. Something like this:

```
Is the provided information correct? (y/n)
y

Starting the installation keptn!
Deploying keptn installer pod ... SUCCESS
Testing connection to Kubernetes API ... SUCCESS
Installing Istio ... SUCCESS
Installing Knative ... 
```

Also:
![image](https://user-images.githubusercontent.com/15996364/58790768-4b647c80-85f1-11e9-82c2-c8ffa9cd2d99.png)

` Wear uniform` sounds awesome, but some explanation, e.g. `(installing keptn services that lorem ipsum dolor sit)`, wouldn't hurt.

**Comment by agrimmer** [comment]
In case the installer fails there should be more information of the root cause why it failed.
For example, point the user to the logs to help him identify the issue.
Also, point him to the troubleshooting section on the keptn website.

**Comment by dirkwall** [comment]
Closing - adds no value right now.
