### ISSUE TITLE
Migrate old sequences to materialized view

### ISSUE THREAD

**Issue by Kirdock** [keptn/keptn#4140]
Up to now the `controlplane/sequence` endpoint only returns new sequences (new sequences after the upgrade) but it should also return old sequences.

## Acceptance Criteria
- [ ] On `keptn upgrade` the sequences should be migrated to the materialized view.

**Comment by bacherfl** [comment]
Currently I see the following options for implementing this issue:

## Option 1: Integrate Task sequence migration into shipyrad-controller

During startup of the shipyard-controller: 
- Get root events; for each root event, check if there is a correlating task sequence in the collection already.
- If no task sequence can be found, derive its state by looking at the trace for the given root event

**Advantages:**
Can use the existing task sequence mongodb repo implementation directly

**Disadvantage:**
Introduces a dependency shipyard-controller --> mongodb-datastore (we need to load the root events and their event traces)

## Option 2: K8s Job that is executed as Helm chart hook after upgrading Keptn

After the helm upgrade has been done, start a Job that:
- Get root events; for each root event, check if there is a correlating task sequence available via the shipyard-controller's sequence endpoint already.
- If not, create a new task sequence entity via the shipyard controller (via a POST call to the sequence endpoint)

**Advantages:**
- Clear separation of concerns - Having this functionality in the shipyard controller itself might not be the cleanest solution, as it is only needed right after the upgrade
- Does not introduce a new dependency from the shipyard-controller to the mongodb-datastore

**Disadvantage:**
- Need to introduce a POST endpoint for creating sequences in the shipyard-controller

**Comment by bacherfl** [comment]
After discussing this iin an internal meeting, we agreed to go with option 1
