### ISSUE TITLE
Bridge: Guide users if a .triggered event does not retreive a .started (or .finished) event

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#4144]
With Keptn 0.8.3 I am going through some troubleshooting steps, and I accidentally forgot to install an SLI provider (but I ran `keptn configure monitoring dynatrace --project sockshop`).

This lead to the following screen in Bridge:
![image](https://user-images.githubusercontent.com/56065213/119009391-5ad26100-b993-11eb-8615-8ed37e35bfd8.png)

# Idea

The problem is only with the get-sli event handling

If a `.triggered` event does *not* retrieve a `.started` event after 5 minutes, we should show the user a warning, e.g.:
**Warning**: It seems that no service is configured to respond to `sh.keptn.event.type.triggered` cloudevents.

Similarly, if a service responds with a `.started` event, but we never receive a `.finished` event, we should show the user a message like this:
**Warning**: It seems that while `$servicename` responded with a `sh.keptn.event.type.started` cloudevent, no `.finished` CloudEvent was retrieved.

**Comment by thisthat** [comment]
This will be addressed with [KEP56](https://github.com/keptn/enhancement-proposals/pull/56)
