### ISSUE TITLE
Activate Snyk protection

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#417]
## Action Item
Activate Snyk to have security scans for all PRs.

## Acceptance Criteria
- [x] Snyk dependency checks are integrated into build pipeline and executed on a nightly schedule

**Comment by christian-kreuzberger-dtx** [comment]
Snyk protection has been enabled for bridge/package.json and pitometer-service/package.json

As we are in the process of switching from go-dep to go modules we will active snyk for go services later.

**Comment by dirkwall** [comment]
Can we activate snyk now for the Go services @christian-kreuzberger-dtx ?

**Comment by christian-kreuzberger-dtx** [comment]
Unfortunately not automatically:
```

        Processed keptn/go-utils from GitHub
          - Could not detect supported target files. Please see our documentation for supported languages and target files.
        0 projects created
```

go modules is not supported by snyk via the Web UI, only via the CLI, and that's a different story.

**Comment by christian-kreuzberger-dtx** [comment]
I've just checked again, and snyk still does not support go modules in the UI, and has no intention to do so in the future.

Snyk claims that they support go modules via the CLI, but I have not found a way to install the CLI on my linux system (Ubuntu 18.04). There is also no docker container available for easily testing it.

References:

* https://hub.docker.com/r/snyk/snyk-cli
* https://support.snyk.io/hc/en-us/articles/360003817417-Snyk-for-Golang
* https://snyk.io/blog/securing-go-modules-made-easy/

The only option I still have not tried is to include it via travis-ci or a github action. I'll leave this issue open until then.

**Comment by christian-kreuzberger-dtx** [comment]
I just checked again - Snyk still does not detect `go.mod`/`go.sum` files. Hence we can not integrate it for all our projects.

**Comment by mowies** [comment]
Snyk is now activated for `keptn/keptn` with weekly scans (fix PRs included) and PR scans
