### ISSUE TITLE
Document Access to Meta-Keptn and what is deployed

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#4178]
Currently, access to our Meta Keptn instance is not documented.

I propose to create a Wiki page with our Meta Keptn, stating
* how to access Bridge/API (e.g., address)
* who to ask to get access if needed
* where code is stored (e.g., SLO files, endpoints.yaml, ...)

# Definition of Done

- [ ] Documentation of how to access Meta Keptn should be part of our Wiki. Credentials **must not** be stored publicly.

**Comment by DARK-art108** [comment]
Can I work upon this? I want to know more details where should these things to be added! And what content should be added their!

**Comment by thisthat** [comment]
Given that the credentials are rotated at each deployment, we cannot provide a documentation for this.

**Comment by thisthat** [comment]
Since the credentials are rotated at each deployment, we cannot give easily access to this environment to others.
