### ISSUE TITLE
Installing/Upgrading Keptn in an air-gapped environment does not work for `configuration-service` and `nats`

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#4183]
Keptn Version: 0.8.3 (probably also affects Keptn 0.8.2)

## Problem 

As a user, I would like to install/upgrade my Keptn in an air-gaped environment using `helm upgrade` explained [here](https://keptn.sh/docs/0.8.x/operate/advanced_install_options/#example-execute-helm-upgrade-without-internet-connectivity)
but the upgrade fails due to the configuration-service that cannot start. 

The problem is that the `configuration-service` has an `initContainer` that refers to an `alpine:3.13` image. 
https://github.com/keptn/keptn/blob/0f24233122a216b6bf597731f8673f345b841e0c/installer/manifests/keptn/charts/control-plane/templates/core.yaml#L550-L561
Since the repository cannot be specified (e.g., `YOUR_REGISTRY/alpine:3.13`), the public `alpine:3.13` is going to be pulled from docker hub. This is not possible in an air-gapped environment. 

### Temporary Workaround

To be defined: 

First approach: Change the image of the `initContainer` of the configuration-service to an alpine image available in the cluster: 
1. Pull `alpine:3.13` and push it into your private registry
2. `kubectl edit deployment configuration-service -n keptn` and set `image` of the initContainer to the alpine image stored in your private registry

### Fix 1

* The deployment manifest of the `configuration-service` does not allow to specify an image repository for the image of the `initContainer` : https://github.com/keptn/keptn/blob/master/installer/manifests/keptn/charts/control-plane/templates/core.yaml#L552
  * An example of how to allow customization of the image repo is given here: https://github.com/keptn/keptn/blob/master/installer/manifests/keptn/charts/control-plane/templates/core.yaml#L564

### Fix 2 (to be discussed)

Is the approach using initContainer to change the permissions of the specified folder 
a) necessary? (why is it actually there?)
and 
b) correct? (can we use another container? e.g, the same container of configuration-service, just with root access?)

https://github.com/keptn/keptn/blob/0f24233122a216b6bf597731f8673f345b841e0c/installer/manifests/keptn/charts/control-plane/templates/core.yaml#L550-L561

### Acceptance criteria

* [ ] The script `For pulling, re-tagging, and pushing all Keptn Docker images, we prepared a small helper script:` provided at https://keptn.sh/docs/0.8.x/operate/advanced_install_options/#example-execute-helm-upgrade-without-internet-connectivity is updated and works for Keptn 0.8.3:
  * [ ] Add the pull/push of the `alpine:3.13` image to the script
  * [ ] Add missing images of services (secret-service) to the script 

* [ ] Updated `helm upgrade` command to work with 0.8.3: 
```
helm upgrade keptn keptn --install -n keptn --create-namespace --wait --version=0.8.3 --repo=https://storage.googleapis.com/keptn-installer --set=control-plane.apiGatewayNginx.type=LoadBalancer,continuous-delivery.enabled=true,\
control-plane.mongodb.image.repository=YOUR_REGISTRY/centos/mongodb-36-centos7,\
control-plane.nats.nats.image=YOUR_REGISTRY/nats:2.1.7-alpine3.11,\
control-plane.nats.reloader.image=YOUR_REGISTRY/connecteverything/nats-server-config-reloader:0.6.0,\
control-plane.nats.exporter.image=YOUR_REGISTRY/synadia/prometheus-nats-exporter:0.5.0,\
control-plane.apiGatewayNginx.image.repository=YOUR_REGISTRY/nginxinc/nginx-unprivileged:1.19.4-alpine,\
control-plane.remediationService.image.repository=YOUR_REGISTRY/keptn/remediation-service,\
control-plane.apiService.image.repository=YOUR_REGISTRY/keptn/api,\
control-plane.bridge.image.repository=YOUR_REGISTRY/keptn/bridge2,\
control-plane.distributor.image.repository=YOUR_REGISTRY/keptn/distributor,\
control-plane.shipyardController.image.repository=YOUR_REGISTRY/keptn/shipyard-controller,\
control-plane.configurationService.image.repository=YOUR_REGISTRY/keptn/configuration-service,\
control-plane.mongodbDatastore.image.repository=YOUR_REGISTRY/keptn/mongodb-datastore,\
control-plane.statisticsService.image.repository=YOUR_REGISTRY/keptn/statistics-service,\
control-plane.lighthouseService.image.repository=YOUR_REGISTRY/keptn/lighthouse-service,\
control-plane.approvalService.image.repository=YOUR_REGISTRY/keptn/approval-service,\
continuous-delivery.distributor.image.repository=YOUR_REGISTRY/keptn/distributor,\
continuous-delivery.helmService.image.repository=YOUR_REGISTRY/keptn/helm-service,\
continuous-delivery.jmeterService.image.repository=YOUR_REGISTRY/keptn/jmeter-service\
/
``` 

* [ ] Move the bash script (for download/upload) to keptn/keptn 
* [ ] An integration test executes the `script` and `helm upgrade` 

### Definition of Done
- [ ] Bash script moved to keptn/keptn
- [ ] As a user, I can upgrade my air-gapped Keptn using the approach [here](https://keptn.sh/docs/0.8.x/operate/advanced_install_options/#example-execute-helm-upgrade-without-internet-connectivity)
- [ ] An integration test covers the functionality in an airgapped cluster

**Comment by johannes-b** [comment]
Next to the configuration-service that does not start up due to its `initcontainer`, the Helm Chart of *nats* has been updated to a newer version which references also another image.

The commit: https://github.com/keptn/keptn/commit/d4d65b8c8bcc3b932e4c63c4afd70f1c42ab0800#diff-9180a9efb6d047a3ec52ef85c79d9cec051a6b0557240b197ede0cea1c370309

The image has changed from: `nats:2.1.7-alpine3.11` to `nats:2.1.9-alpine3.12` 

#### Definition of Done: 
- [ ] The new nats image is considered in the pull/push script.

**Comment by agrimmer** [comment]
We could easily get rid of the user container `change-user-init` if we can ensure that the user of the files was already changed to 65532 before. This can be done by defining an upgrade policy, e.g. only allow upgrades form a specific Keptn version.

**Comment by christian-kreuzberger-dtx** [comment]
Decision: Remove install instructions for airgapped installation from docs now, create a PR to add it again for 0.8.5
