### ISSUE TITLE
For non release-builds, use timestamps for containers in helm-charts

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#4191]
Right now in our CI build we build Docker Images with the following tags:

* `0.8.3-dev` (`x.y.z-dev`)
* `0.8.3-dev.202105280620` (`x.y.z-dev.timestamp`)

In our helm-charts, we always use the first version string (`x.y.z-dev`), which can lead to problem when trying to install and/or upgrade from a dev version to another dev version, as the Docker Images are not re-pulled.

This has partially already been done for master builds (the else branch is for release builds):
https://github.com/keptn/keptn/blob/0f24233122a216b6bf597731f8673f345b841e0c/.github/workflows/CI.yml#L603-L612

# Task

- Add a check for PR builds and also use the `$VERSION.$TIMESTAMP`

# Definition of Done

- [ ] Master/PR builds use the version string **with timestamp**
- [ ] Release builds still use the version string **without** timestamp

**Comment by mowies** [comment]
Working on this issue

**Comment by christian-kreuzberger-dtx** [comment]
Done in PR https://github.com/keptn/keptn/pull/4286 and https://github.com/keptn/keptn/pull/4296. Thanks @mowies
