### ISSUE TITLE
Meta Keptn + Monaco: Extend Dashboards to show Loadtests using JMeter metrics

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#4195]
Depends on https://github.com/keptn/keptn/issues/4194 and https://github.com/keptn/keptn/issues/2549

When executing load-tests (using jmeter) on our Meta Keptn, we should show adapt dashboards accordingly to show those Load Tests, e.g.:
![image](https://user-images.githubusercontent.com/56065213/119991297-99869d80-bfc9-11eb-883e-8854844834c1.png)

This is accomplished using [Dynatraces jmeter plugin](https://github.com/dynatrace-oss/jmeter-dynatrace-plugin) (which is already part of Keptns jmeter-service).
Please follow the tutorial here: https://www.dynatrace.com/news/blog/guide-to-automated-sre-driven-performance-engineering-analysis/

# Definition of Done

- [ ] Dynatrace Dashboards have a tile that show response times (or similar) when load-tests are running (per stage)

**Comment by thisthat** [comment]
The team decided to don't implement this feature
