### ISSUE TITLE
Forward if blue or green is the new version for correctly retrieving data

### ISSUE THREAD

**Issue by dirkwall** [keptn/keptn#422]
The GitHub service updates the configuration and defines which color a new version gets - either blue or green. We need to forward this information to the evaluation phase, so we can uniquely identify the entity we want to get metrics from.

**Comment by johannes-b** [comment]
The following questions need to be discussed in a design session:
- Name of the new property
- Is the property mandatory? Since there is no color in case of a direct deployment.
- How to deal with canary deployments?

**Comment by johannes-b** [comment]
The github-service has a branch with changes in this regard: https://github.com/keptn/github-service/tree/feature/422/active-color

**Comment by bacherfl** [comment]
the changes made in #850 enable Pitometer to retrieve metrics from the correct DT service entity

**Comment by dirkwall** [comment]
Can we close this issue then, @bacherfl ?
