### ISSUE TITLE
Collapsing evaluation Heatmap to top 10

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#4255]
### Use case

As a user, I have an SLO config containing 10+ SLI - typically 50 or more - and would like to have a collapsed Heatmap showing just the first 10 SLIs. With a `Show all SLIs` button I can expand the Heatmap to see all SLIs; with an `Collapse to 10 SLIs` button I can collapse the Heatmap to the top 10. 

#### Details

*Mockup* to explain the idea (but ignore the name of the SLIs because they are just copy-pasted).
- Just show the first 10 SLIs
- To display all, a user has to click the `Show all SLIs` button.
  - Is it possible to position the button as shown in the mockup? If not, move it to the top left corner.  
- The data is already available. The feature is implemented on the UI
![image](https://user-images.githubusercontent.com/729071/121149788-3efc0580-c843-11eb-9eb7-b2aaba002389.png)
- After expanding the Heatmap, the `Show all SLIs` button is changed to `Collapse to 10 SLIs` allowing collapsing the Heatmap.

### Acceptance criteria
- By default, just the first 10 SLIs in the Heatmap are shown. 
- A button allows expanding the entire Heatmap 

### Definition of Done
- [x] Feature is implemented in the Bridge
- [x] Unit Tests

**Comment by laneli** [comment]
I added unit tests instead of integration test, e2e tests would be flaky, because it depends on the number of defined SLOs and with unit tests there is more control over this.
