### ISSUE TITLE
Artifact gets promoted to prod if no perfspec file is found

### ISSUE THREAD

**Issue by alipatton10** [keptn/keptn#428]
If you don't supply the perfspec file keptn still promotes the artifact as it sends the evaluationpassed true anyway. It should only be promoted if the test passes. Below are the log details
{
  "_index": "logstash-2019.06.11",
  "_type": "fluentd",
  "_id": "AWtGNwPc7T0WdQYhbJxc",
  "_version": 1,
  "_score": null,
  "_source": {
    "keptnContext": "6d5b8f69-5122-4422-9d57-bdba38a6cf27",
    "logLevel": "INFO",
    "message": "No perfspec file defined for sockshop:carts:staging",
    "keptnService": "pitometer-service",
    "log": "{\"keptnContext\":\"6d5b8f69-5122-4422-9d57-bdba38a6cf27\",\"logLevel\":\"INFO\",\"message\":\"No perfspec file defined for sockshop:carts:staging\",\"keptnService\":\"pitometer-service\"}\n",
    "stream": "stdout",
    "docker": {
      "container_id": "9ab5cfad3ca0b65519f0eb9d6750005ba92e4131b0e50d595d9a934b467f3c7f"
    },
    "kubernetes": {
      "container_name": "user-container",
      "namespace_name": "keptn",
      "pod_name": "pitometer-service-52786-deployment-754cd855-blzfl",
      "pod_id": "cfb43177-8c38-11e9-9029-42010a8000dc",
      "labels": {
        "app": "pitometer-service-52786",
        "pod-template-hash": "754cd855",
        "serving_knative_dev/configuration": "pitometer-service",
        "serving_knative_dev/configurationGeneration": "1",
        "serving_knative_dev/configurationMetadataGeneration": "1",
        "serving_knative_dev/revision": "pitometer-service-52786",
        "serving_knative_dev/revisionUID": "fcce47d7-8c2b-11e9-9029-42010a8000dc",
        "serving_knative_dev/service": "pitometer-service"
      },
      "host": "gke-dt-acm-keptn-default-pool-02d16614-1jsk",
      "master_url": "https://10.7.240.1:443/api",
      "namespace_id": "5fa096d6-8c2a-11e9-9029-42010a8000dc",
      "namespace_labels": {
        "istio-injection": "enabled"
      }
    },
    "@timestamp": "2019-06-11T11:05:34.932405362+00:00",
    "tag": "kubernetes.var.log.containers.pitometer-service-52786-deployment-754cd855-blzfl_keptn_user-container-9ab5cfad3ca0b65519f0eb9d6750005ba92e4131b0e50d595d9a934b467f3c7f.log"
  },
  "fields": {
    "@timestamp": [
      1560251134932
    ]
  },
  "highlight": {
    "keptnContext": [
      "@kibana-highlighted-field@6d5b8f69@/kibana-highlighted-field@-@kibana-highlighted-field@5122@/kibana-highlighted-field@-@kibana-highlighted-field@4422@/kibana-highlighted-field@-@kibana-highlighted-field@9d57@/kibana-highlighted-field@-@kibana-highlighted-field@bdba38a6cf27@/kibana-highlighted-field@"
    ],
    "keptnContext.keyword": [
      "@kibana-highlighted-field@6d5b8f69-5122-4422-9d57-bdba38a6cf27@/kibana-highlighted-field@"
    ],
    "log": [
      "{\"keptnContext\":\"@kibana-highlighted-field@6d5b8f69@/kibana-highlighted-field@-@kibana-highlighted-field@5122@/kibana-highlighted-field@-@kibana-highlighted-field@4422@/kibana-highlighted-field@-@kibana-highlighted-field@9d57@/kibana-highlighted-field@-@kibana-highlighted-field@bdba38a6cf27@/kibana-highlighted-field@\",\"logLevel\":\"INFO\",\"message\":\"No perfspec file defined for sockshop:carts:staging\",\"keptnService\":\"pitometer-service\"}\n"
    ]
  },
  "sort": [
    1560251134932
  ]
}

{
  "_index": "logstash-2019.06.11",
  "_type": "fluentd",
  "_id": "AWtGNwPc7T0WdQYhbJxf",
  "_version": 1,
  "_score": null,
  "_source": {
    "keptnContext": "6d5b8f69-5122-4422-9d57-bdba38a6cf27",
    "logLevel": "INFO",
    "message": "Sending event: {\"id\":\"efe2c917-ddd9-40fc-9561-30aec81ae559\",\"specversion\":\"0.2\",\"time\":\"2019-06-11T11:05:34+00:00\",\"datacontenttype\":\"application/json\",\"shkeptncontext\":\"6d5b8f69-5122-4422-9d57-bdba38a6cf27\",\"data\":{\"githuborg\":\"dt-keptn\",\"project\":\"sockshop\",\"deploymentstrategy\":\"blue_green_service\",\"stage\":\"staging\",\"service\":\"carts\",\"image\":\"docker.io/keptnexamples/carts\",\"tag\":\"0.7.2\",\"evaluationpassed\":true,\"evaluationdetails\":{\"result\":\"pass\"}},\"type\":\"sh.keptn.events.evaluation-done\"}",
    "keptnService": "pitometer-service",
    "log": "{\"keptnContext\":\"6d5b8f69-5122-4422-9d57-bdba38a6cf27\",\"logLevel\":\"INFO\",\"message\":\"Sending event: {\\\"id\\\":\\\"efe2c917-ddd9-40fc-9561-30aec81ae559\\\",\\\"specversion\\\":\\\"0.2\\\",\\\"time\\\":\\\"2019-06-11T11:05:34+00:00\\\",\\\"datacontenttype\\\":\\\"application/json\\\",\\\"shkeptncontext\\\":\\\"6d5b8f69-5122-4422-9d57-bdba38a6cf27\\\",\\\"data\\\":{\\\"githuborg\\\":\\\"dt-keptn\\\",\\\"project\\\":\\\"sockshop\\\",\\\"deploymentstrategy\\\":\\\"blue_green_service\\\",\\\"stage\\\":\\\"staging\\\",\\\"service\\\":\\\"carts\\\",\\\"image\\\":\\\"docker.io/keptnexamples/carts\\\",\\\"tag\\\":\\\"0.7.2\\\",\\\"evaluationpassed\\\":true,\\\"evaluationdetails\\\":{\\\"result\\\":\\\"pass\\\"}},\\\"type\\\":\\\"sh.keptn.events.evaluation-done\\\"}\",\"keptnService\":\"pitometer-service\"}\n",
    "stream": "stdout",
    "docker": {
      "container_id": "9ab5cfad3ca0b65519f0eb9d6750005ba92e4131b0e50d595d9a934b467f3c7f"
    },
    "kubernetes": {
      "container_name": "user-container",
      "namespace_name": "keptn",
      "pod_name": "pitometer-service-52786-deployment-754cd855-blzfl",
      "pod_id": "cfb43177-8c38-11e9-9029-42010a8000dc",
      "labels": {
        "app": "pitometer-service-52786",
        "pod-template-hash": "754cd855",
        "serving_knative_dev/configuration": "pitometer-service",
        "serving_knative_dev/configurationGeneration": "1",
        "serving_knative_dev/configurationMetadataGeneration": "1",
        "serving_knative_dev/revision": "pitometer-service-52786",
        "serving_knative_dev/revisionUID": "fcce47d7-8c2b-11e9-9029-42010a8000dc",
        "serving_knative_dev/service": "pitometer-service"
      },
      "host": "gke-dt-acm-keptn-default-pool-02d16614-1jsk",
      "master_url": "https://10.7.240.1:443/api",
      "namespace_id": "5fa096d6-8c2a-11e9-9029-42010a8000dc",
      "namespace_labels": {
        "istio-injection": "enabled"
      }
    },
    "@timestamp": "2019-06-11T11:05:34.935648772+00:00",
    "tag": "kubernetes.var.log.containers.pitometer-service-52786-deployment-754cd855-blzfl_keptn_user-container-9ab5cfad3ca0b65519f0eb9d6750005ba92e4131b0e50d595d9a934b467f3c7f.log"
  },
  "fields": {
    "@timestamp": [
      1560251134935
    ]
  },
  "highlight": {
    "keptnContext": [
      "@kibana-highlighted-field@6d5b8f69@/kibana-highlighted-field@-@kibana-highlighted-field@5122@/kibana-highlighted-field@-@kibana-highlighted-field@4422@/kibana-highlighted-field@-@kibana-highlighted-field@9d57@/kibana-highlighted-field@-@kibana-highlighted-field@bdba38a6cf27@/kibana-highlighted-field@"
    ],
    "keptnContext.keyword": [
      "@kibana-highlighted-field@6d5b8f69-5122-4422-9d57-bdba38a6cf27@/kibana-highlighted-field@"
    ],
    "log": [
      "{\"keptnContext\":\"@kibana-highlighted-field@6d5b8f69@/kibana-highlighted-field@-@kibana-highlighted-field@5122@/kibana-highlighted-field@-@kibana-highlighted-field@4422@/kibana-highlighted-field@-@kibana-highlighted-field@9d57@/kibana-highlighted-field@-@kibana-highlighted-field@bdba38a6cf27@/kibana-highlighted-field@\",\"logLevel\":\"INFO\",\"message\":\"Sending event: {\\\"id\\\":\\\"efe2c917-ddd9-40fc-9561-30aec81ae559\\\",\\\"specversion\\\":\\\"0.2\\\",\\\"time\\\":\\\"2019-06-11T11:05:34+00:00\\\",\\\"datacontenttype\\\":\\\"application/json\\\",\\\"shkeptncontext\\\":\\\"@kibana-highlighted-field@6d5b8f69@/kibana-highlighted-field@-@kibana-highlighted-field@5122@/kibana-highlighted-field@-@kibana-highlighted-field@4422@/kibana-highlighted-field@-@kibana-highlighted-field@9d57@/kibana-highlighted-field@-@kibana-highlighted-field@bdba38a6cf27@/kibana-highlighted-field@\\\",\\\"data\\\":{\\\"githuborg\\\":\\\"dt-keptn\\\",\\\"project\\\":\\\"sockshop\\\",\\\"deploymentstrategy\\\":\\\"blue_green_service\\\",\\\"stage\\\":\\\"staging\\\",\\\"service\\\":\\\"carts\\\",\\\"image\\\":\\\"docker.io/keptnexamples/carts\\\",\\\"tag\\\":\\\"0.7.2\\\",\\\"evaluationpassed\\\":true,\\\"evaluationdetails\\\":{\\\"result\\\":\\\"pass\\\"}},\\\"type\\\":\\\"sh.keptn.events.evaluation-done\\\"}\",\"keptnService\":\"pitometer-service\"}\n"
    ],
    "message": [
      "Sending event: {\"id\":\"efe2c917-ddd9-40fc-9561-30aec81ae559\",\"specversion\":\"0.2\",\"time\":\"2019-06-11T11:05:34+00:00\",\"datacontenttype\":\"application/json\",\"shkeptncontext\":\"@kibana-highlighted-field@6d5b8f69@/kibana-highlighted-field@-@kibana-highlighted-field@5122@/kibana-highlighted-field@-@kibana-highlighted-field@4422@/kibana-highlighted-field@-@kibana-highlighted-field@9d57@/kibana-highlighted-field@-@kibana-highlighted-field@bdba38a6cf27@/kibana-highlighted-field@\",\"data\":{\"githuborg\":\"dt-keptn\",\"project\":\"sockshop\",\"deploymentstrategy\":\"blue_green_service\",\"stage\":\"staging\",\"service\":\"carts\",\"image\":\"docker.io/keptnexamples/carts\",\"tag\":\"0.7.2\",\"evaluationpassed\":true,\"evaluationdetails\":{\"result\":\"pass\"}},\"type\":\"sh.keptn.events.evaluation-done\"}"
    ]
  },
  "sort": [
    1560251134935
  ]
}

**Comment by agrimmer** [comment]
Thank you for pointing out!
However, this is intended behavior: If no `perfspec` file is available, always an `evaluationpassed true` is sent. This allows deploying an artifact w/o any quality gates.

**Comment by alipatton10** [comment]
That should only happen if I defined no testing strategy.

**Comment by agrimmer** [comment]
Thank you for your additional explanations!

We internally discussed this issue and will implement it as follows:
If the test strategy is `functional`, no perfspec-file is required because the `jmeter-service` already decides whether the test is successful or not.
However, if the test strategy is `performance`, a perfspec-file has to be available. More precisely, we will change the `pitometer-service` so that it will return `evaluationpassed false` if no perfspec-file is available.

Thank you again for determining this issue!

**Comment by alipatton10** [comment]
Thanks guys, although should this not be wider than just the perfspec file as in if i specify a test it must pass otherwise it should not be promoted. Missing file should just be an example of an error meaning it should fail, same as if DT returned no data to evaluate it against.

**Comment by bacherfl** [comment]
Hi, in the current implementation we do set the `evaluationpassed`property to `false` if we don't receive any data from DT. In the next version of this service we will implement this same behavior for missing perfspec files if the testing strategy has been set to `performance`

**Comment by bacherfl** [comment]
we are going to add the possibility to explicitly add quality gates via a certain parameter in the shipyard file. We are currently discussing the details and will update this issue when we have news on that
