### ISSUE TITLE
Persist keptn CLI logs

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#429]
Currently, the keptn CLI does not store its log output but just the logs from the installation process. 

Extend the logging capabilities of the keptn CLI to store the log output in a local file (maybe next to the installer logs).

**Comment by dirkwall** [comment]
@johannes-b is this still relevant?

**Comment by johannes-b** [comment]
This issue is still relevant. The Keptn CLI does not persist its log output. 
Consequently, the use of the keptn CLI cannot be investigated or replayed.
