### ISSUE TITLE
 --quiet option for keptn get event evaluation.finished is not suppressing all warnings and infromation

### ISSUE THREAD

**Issue by robertjahn** [keptn/keptn#4298]
Your issue may already be reported! Please search on the [issue tracker](https://github.com/keptn/keptn/issues) before creating a new one.

**Environment**

* Client OS (e.g., Linux, macOS, Windows): Linux, macOS,
* Keptn Version (`keptn version`):  0.8.2
* Kubernetes Cloud Provider (e.g., GKE, AKS): using DT cloud automation 
* Kubernetes version (`kubectl version`): n/a

**Affected Component**

* [ ] Docs
* [x] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [ ] Bridge
* [ ] Approval
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**
I have seen several CLI commands that still show warnings and info messages (see below).  I expect the `-q` and `--quiet` command to not show these.

**To Reproduce**
Here are some examples

```
mac# keptn get event evaluation.finished --keptn-context 2a7df387-4c89-4513-814e-5c5dea1dc672 -q
NOTE: The "keptn get event evaluation.finished" command is DEPRECATED and will be removed in a future release
Use "keptn get event evaluation.finished" instead

{
        "data": {
                "evaluation": {
                        "gitCommit": "",
                        "indicatorResults": null,
                        "result": "pass",
```

```
mac# keptn get event evaluation.finished --keptn-context $KTX -q 
* Warning: Your Keptn CLI version (0.8.2) and Keptn cluster version (0.8.3) don't match. This can lead to problems. Please make sure to use the same versions.
NOTE: The "keptn get event evaluation.finished" command is DEPRECATED and will be removed in a future release
Use "keptn get event evaluation.finished" instead
{
        "data": {
                "evaluation": {
                        "comparedEvents": [
                                "451eba49-6321-4d41-9cfd-e6376c8469e7"
                        ],
                        "gitCommit": "",
                        "indicatorResults": [
                                {
                                        "displayName": "",
                                        "keySli": false,
                                        "passTargets": null,
                                        "score": 0,
```

**Comment by ChinYing-Li** [comment]
I am assuming that we actually want `--quiet` to suppress the log message related to version check, is that correct? If so, I would like to take this one.

**Comment by robertjahn** [comment]
I opened this issue for this one command, but YES I would love it if ALL the command would suppress output on the `--quiet` command.  

@johannes-b [johannes-b](https://github.com/johannes-b) -- if you agree having this be more the universal behavior (i.e quiet means no output messages, should we rename this issue title if this issue or shall I open a new issue?
