### ISSUE TITLE
Show service details of a re-created service

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#4304]
## Use case

As a user, I would like to see the service details (history) of a re-created service; explained as follows: 

1. A service is created and sequences are executed on top of the service.
![image](https://user-images.githubusercontent.com/729071/121846968-29c22380-cce8-11eb-9f28-9511f4c4b0d1.png)

2. Service gets deleted: `keptn delete service carts` > the event history is not deleted by design. 
![image](https://user-images.githubusercontent.com/729071/121847017-39da0300-cce8-11eb-8623-35789c3f7c32.png)

3. Service gets re-created: `keptn onboard service` or `keptn create service`

4. **Problem**: Service details are not shown even though old sequences are available: 
![image](https://user-images.githubusercontent.com/729071/121847161-7279dc80-cce8-11eb-95f2-61a35cb91ee2.png)

5. **Fix**: Trigger a new `keptn trigger delivery` to get the old data

### Acceptance criteria
- [ ] After re-creating a service, the service details are displayed without the need to trigger a sequence. Hence, a user sees: 
![image](https://user-images.githubusercontent.com/729071/121846968-29c22380-cce8-11eb-9f28-9511f4c4b0d1.png)

### Defnition of Done
- [ ] Added E2E Test -ensures that the service details (history) of a re-created service are displayed after a `keptn onboard service` or `keptn create service` (with the need to trigger a sequence) 
- [ ] Added E2E Test
- [ ] Documentation updated
- [ ] Issue added to releasenotes

**Comment by warber** [comment]
This issue most probably needs to be fixed in Keptn Core.
