### ISSUE TITLE
Display comparison value and absolute/relative delta of SLI

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#4305]
## Use case

As a user, I would like to see the comparison value used to evaluate an SLI in case of relative comparison. Besides, the absolute change, as well as the relative change (in %) should be displayed. 

### Details

* Currently, a tooltip is shown when hovering over a failed relative comparison. This is hidden information and difficult to find. 
![image](https://user-images.githubusercontent.com/729071/121848658-a229e400-ccea-11eb-95dd-fc0d6ff1740b.png)

* To make it explicit to the end-user which value of the SLI was used for comparison, the information should be displayed as follows, when expanding, e.g.: `Response Time P90`: 
  * `compared with` ... is a label - show `no comparison value available` when an SLI has no comparison value (e.g., in case of the first evaluation)
  * `245` the value used for comparison
  * `+10` the absolute change
  * `+4%` the relative change
![image](https://user-images.githubusercontent.com/729071/121849115-3eec8180-cceb-11eb-9aeb-58b15f41f76d.png)

* **To be discussed:** Instead of showing a (+/-) sign for increase/decreasing values, a visual representation with red/green arrows would be more user-friendly.
  * If there is a positive value, an arrow is displayed showing up. Vice versa for a negative value. 
  * To determine whether the arrow is green or red, the criteria must be analyzed: 
    * for `<` an increase is bad --> red
    * for `>` an increase is good --> green
  * Should the +/- sign be displayed for users with achromatopsia?   
![image](https://user-images.githubusercontent.com/729071/121851125-09956300-ccee-11eb-8721-18762654f508.png)

### Acceptance criteria
- [x] A user gets the details of why a relative comparison failed what makes a quality gate more reasonable. 

### Definition of Done
- [x] Added unit tests
- [x] Documentation updated (screenshots, tutorial)

**Comment by Kirdock** [comment]
Added unit test instead of E2E tests, because E2E would depend on too much data (project created, SLO and SLI configured and evaluation triggered)
