### ISSUE TITLE
Activation of quality gate should be more explicit in documentation

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#431]
Currently, it may occur that an end-user forgets the activation of the perfspec file as explained [here](https://keptn.sh/docs/0.2.2/usecases/deployments-with-quality-gates/#set-up-of-monitoring-for-the-carts-service).

In the instructions of the deployment with quality gates use case it should be more obvious that the step of renaming the perfspec file is mandatory. Thus, the [heading](https://keptn.sh/docs/0.2.2/usecases/deployments-with-quality-gates/#set-up-of-monitoring-for-the-carts-service) has to be more focused and "Option 1" and "Option 2" should be merged.

**Comment by dirkwall** [comment]
This will be fixed with #952
