### ISSUE TITLE
Org Owners: Please create a repository for keptn-on-keptn

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#4324]
Please create a (private) repository for keptn-on-keptn, e.g., https://github.com/keptn/keptn-on-keptn, which will be used as the "GitOps Repo". Please add *maintainers* with Admin permissions

**Comment by johannes-b** [comment]
I will take care of that task.

**Comment by johannes-b** [comment]
Please find here the corresponding repo: https://github.com/keptn/keptn-on-keptn with the permissions set.
