### ISSUE TITLE
keptn install: Allow to specify local directory as a chart-path

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#4325]
Right now it's a huge pain to install Keptn from a draft release / temporary build, e.g.:

```console
download keptn-installer-0.8.4-dev.tgz # download or build helm charts
python3 -m http.server &
keptn install --chart-repo=http://0.0.0.0:8000/keptn-installer-0.8.4-dev.tgz
killall python3
```

This could be much easier, e.g., by being able to specify a chart repo on the local filesystem, e.g.:

```console
download keptn-installer-0.8.4-dev.tgz # download or build helm charts
keptn install --chart-repo=./dist/keptn-installer-0.8.4-dev.tgz
```

This change would have to be done in the helper functions used here:
https://github.com/keptn/keptn/blob/49022062c4ab1c63d8b93794aa810953629936a2/cli/cmd/install.go#L203-L213
https://github.com/keptn/keptn/blob/49022062c4ab1c63d8b93794aa810953629936a2/cli/pkg/helm/helm_helper.go#L66-L84

# Definition of Done

- [ ] Keptn can be installed/upgraded using a chart repo from local disk space by using the `--chart-repo` flag

# Acceptance Criteria

I can build a local version of helm charts from master branch, using
```
./gh-actions-scripts/build_helm_charts.sh 0.8.4-dev 0.8.4-dev 0.8.3
```

and install it afterwards using
```
keptn install --chart-repo=./keptn-charts/keptn-0.8.4-dev.tgz
```

**Comment by jimil749** [comment]
Hey @christian-kreuzberger-dtx, I would like to give this a shot. Does it make sense to add a simple check in the helper, which checks if the `chartRepoURL` string is a URL, if not we assume that the repo is stored in the disk and load it from there?

**Comment by warber** [comment]
hi @jimil749 thanks for taking this one, I'll assign it to you.

Basically, yes you need to distinguish between these two cases, e.g. inside the [doInstallation](https://github.com/keptn/keptn/blob/49022062c4ab1c63d8b93794aa810953629936a2/cli/cmd/install.go#L199) method, and do the corresponding action. Note that there is already a method available in [kuberentes-utils](https://github.com/keptn/kubernetes-utils/blob/1c37565807d5f7e03363b6f4c5dcca80815d753e/pkg/kubernetes-utils.go#L467) to load a chart from the local filesystem.
