### ISSUE TITLE
Allow project initialization via GitOps

### ISSUE THREAD

**Issue by ekarlso** [keptn/keptn#4335]
**Is your feature request related to a problem? Please describe.**

Initializing a *keptn* project today requires a empty GIT repository which is in many use-cases too imperative vs declarative configurations which is used by other tools.

**Describe the solution you'd like**

Be able to declarative configure both Projects and Service's using CRD's in the *keptn* cluster instead of the CLI directly.

Preferably by the keptn-operator would be watching for new Project resources and creating them in *keptn* on the user's behalf and *keptn* would be able to initialize itself based current state from the GitOps repository. 

This would allow easier use/integration with certain other tools like Flux V2 and potentially other tools that often has per-existing files in the repository.

It is also a benefit when it comes to mobility / disaster recovery of *keptn* Projects etc since if *keptn* get's a problem then you can simply re-create the Project | Services etc from a existing git repository.

**Describe alternatives you've considered**

* Have `keptn create project ...` be able to onboard a non-empty repository potentially where existing service definitions are present somehow where the repository already has a *shipyard.yaml* file, having stage structure etc present already.  
* The  the `keptn-gitops-operator` kicks in and watches either the repository or CRD's it does a analysis and triggers *keptn* actions behind the scenes via the API or alike.

**Comment by johannes-b** [comment]
Great idea @ekarlso, thanks for posting it!

While the CLI command `keptn create project` needs to be addressed on the Keptn core side for allowing non-empty repositories, I would like to ask @thschue: if the [keptn-gitops-operator](https://github.com/keptn-sandbox/keptn-gitops-operator) is already capable of bootstrapping the project then?

**Comment by thschue** [comment]
No, the project has to be initialized and the git repository connected. We could create the Keptn Project using the KeptnProject resource, but this is a thing that has to be discussed with the Keptn Core team, as it is not clear for us what Keptn is doing when creating a Project ...

**Comment by miguelvr** [comment]
As a new user, I have to say that this is precisely the behavior I expected to encounter. I was very surprised that I had to create an empty git repository, which simply did not feel right. 

Ideally, I would like to store Keptn configurations in the same repository as my application.

**Comment by utibeabasi6** [comment]
hey, if theres any way i can help, i would like to work on this @thisthat

**Comment by thisthat** [comment]
Sure @utibeabasi6, you can have a look. You might want to look into https://github.com/keptn-sandbox/keptn-gitea-provisioner-service to see if you can automate the provisioning of the project

**Comment by utibeabasi6** [comment]
alright, will do

**Comment by DavidPHirsch** [comment]
@utibeabasi6 can we close this?

**Comment by odubajDT** [comment]
Since Keptn V1 has reached EOL on December 22nd, 2023, this issue has been closed.
