### ISSUE TITLE
Investigation of Helm 3.0.0 to replace the current Helm version 2.12.3

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#435]
When helm 3.0.0 is available, investigate an upgrade of the current helm version [2.12.3](https://github.com/keptn/installer/blob/master/Dockerfile#L31) to 3.0.0.

**Comment by agrimmer** [comment]
Research completed. The current implementation can be found in branch https://github.com/keptn/keptn/tree/feature/435/upgrade-helm
https://github.com/keptn/go-utils/tree/feature/435/helm-upgrade

Remaining TODOs which have to be addressed can be found in Issue #1179
