### ISSUE TITLE
Extend keptn CLI to support different platforms for keptn install

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#436]
The installer pod will get a new environment variable 'PLATFORM' that specifies the target K8s cluster where keptn should be installed:
```
- name: PLATFORM
  value: PLATFORM
```
The supported values are: `aks`, `eks`, `ocp`, `gke`, `pks`

The keptn cli should be extended by an additional parameter that specifies the target platform for installing keptn, for example: `keptn install --platform=pks`

Based on the parameter, the keptn cli sets the environment variable PLATFORM for the installer pod.

**Comment by dirkwall** [comment]
PKS and AKS are missing in the CLI and the installer. Others are done.

**Comment by dirkwall** [comment]
Implement the missing platforms with #3 and #5 - closing.
