### ISSUE TITLE
On push to a release-branch, create a draft release for examples, go-utils and kubernetes-utils

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#4365]
Depends on https://github.com/keptn/keptn/issues/4364

Right now we have a step in our [release checklist](https://github.com/keptn/keptn/wiki/Release-Checklist) when we release examples, go-utils and kubernetes-utils to create a DRAFT release.

This has already been automated in Keptn core (though it still has some problems when re-creating draft releases):
https://github.com/keptn/keptn/blob/1290969017e627edcf8189f726e7fb09dfc9eab8/.github/workflows/integration_tests.yml#L897-L987

This automation needs to also work for release branches in the following repositories:
* [x] #4762
* [x] #4763
* [x] #4764

The draft release should contain

* release notes (generated as specified in #4364)
* link to the CI run (for debug purposes)

The workflow should not overwrite an existing published release (only draft releases).

# Definition of Done

- [x] When creating a release branch in the repositories go-utils, kubernetes-utils or examples, a draft release with release notes is automatically created
- [x] Keptn Core Developers are onboarded in the process of how to use this feature

# Next Steps / Future Work

We want the same mechanisms introduced in keptn core (keptn/keptn), and provide the automation also to keptn-contrib/keptn-sandbox.

**Comment by mowies** [comment]
All subtasks are done from this ticket. Closing this.
