### ISSUE TITLE
Create a PR that updates specification subfolder in keptn/keptn when a new Keptn spec is released 

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#4366]
Right now we have a step in our [release checklist](https://github.com/keptn/keptn/wiki/Release-Checklist) to update the specification sub-folder in Keptn core using the following command:

```
cd specification && git fetch && git checkout $KEPTN_SPEC_VERSION && cd .. && git add specification && git commit -m "updated spec to $KEPTN_SPEC_VERSION" --signoff && git push
```

This should be automated.

# Definition of Done

- [ ] Whenever a new keptn spec is released, a pull request changing to the newly released spec is automatically created on keptn/keptn

**Comment by mowies** [comment]
Plan:
* add a webhook to the `keptn/spec` repo with the `event_type` of `repository_dispatch` to trigger a GH actions workflow that will update the `specification` git submodule and then create a PR in the `keptn/keptn` repo
* the webhook should only trigger a workflow execution if a new release tag was pushed to the spec repo
