### ISSUE TITLE
Change mongodb to bitnami-docker-mongodb image 

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#4369]
This came up in #3936 by @donovanmuller.
It seems that mongodb is behaving poorly in certain auto-scaling situations.

As a fix, Donovan suggested to change to `bitnami-docker-mongodb` (they have addressed this in https://github.com/bitnami/bitnami-docker-mongodb/issues/159 ).

I'm not sure of the consequences of doing so (e.g., licence issues, etc...), so I'm leaving this up for discussion.

# Acceptance Criteria

- [ ] Keptn installer references the bitnami-docker-mongodb image
- [ ] keptn.sh/docs references to the mongodb image need to be updated to the bitnami-docker-mongodb image

**Comment by thisthat** [comment]
Closing this in favor of #4801
