### ISSUE TITLE
Setting upstream failed, but the error is not shown in Bridge

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#4374]
Using Keptn 0.8.3,

I added a git upstream in Bridge, but it seems that the API responded with a 500, which is not shown prominently in the UI:

![image](https://user-images.githubusercontent.com/56065213/122216921-35127c00-cead-11eb-9644-9133e5b07296.png)
![image](https://user-images.githubusercontent.com/56065213/122216969-4196d480-cead-11eb-9475-d3e20e6d0557.png)

**Note**: A short toast notification in the bottom-center is shown, but it disappears so quickly, that it is barely noticeable.

Probably related to https://github.com/keptn/keptn/issues/4375

**Comment by johannes-b** [comment]
Please consider #4398 & #4399 when working on one of these issues.
