### ISSUE TITLE
Docs/CLI: Updating the upstream of a project does not work according to the docs

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#4375]
Using Keptn 0.8.3, I followed the instructions provided here: https://keptn.sh/docs/0.8.x/manage/git_upstream/
Primarily, this step suggests to add a README file:
![image](https://keptn.sh/docs/0.8.x/manage/git_upstream/assets/github_create_repo.png)

This is my repo: https://github.com/keptn/keptn-on-keptn

![image](https://user-images.githubusercontent.com/56065213/122217628-e0233580-cead-11eb-913c-5a5a70c608e9.png)

This is my keptn update project command:
```
keptn update project keptn --git-remote-url=https://github.com/keptn/keptn-on-keptn.git --git-user=christian-kreuzberger-dtx --git-token=<redacted>
```

This is the output:
```
Error: Update project was unsuccessful. failed to set upstream: Error executing command git checkout main: exit status 1
error: pathspec 'main' did not match any file(s) known to git

Keptn requires an uninitialized repo

```

configuration-service shows the following logs:
```
{"timestamp":"2021-06-16T12:18:14.179734555Z","logLevel":"ERROR","message":"Could not add upstream repository while updating project keptn: failed to set upstream: Error executing command git checkout main: exit status 1\nerror: pathspec 'main' did not match any file(s) known to git\n\nKeptn requires an uninitialized repo"}

```

**Comment by bacherfl** [comment]
It seems like the requirement of having an uninitialized repo is shown at the very top of the docs:
https://keptn.sh/docs/0.8.x/manage/git_upstream/

⚠️ The Git repository you want to define as upstream for an already created project must not be initialized, i.e., an empty repo without any commits. Just do not select the check-box: Initialize this repository with a README when creating the repository.

The problem of updating the project with the credentials of an initialized upstream repo is that the histories of the branches will be unrelated

**Comment by christian-kreuzberger-dtx** [comment]
This means the advice given on the docs page is conflicting.

The instructions for GitHub suggest to initialize the repo with a README file. We should change this to an uninitialized repository.
