### ISSUE TITLE
Retrieve data for installer pod based on platform cli (e.g., gcloud, eksctl, ...) 

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#438]
Depending on the target platform where keptn should be installed (see #436), the keptn CLI should automatically retrieve values for environment variables needed by the installer pod. Thus, the platform related CLIs should be used, to retrieve the data for:
```
   - name: CLUSTER_IPV4_CIDR
     value: CLUSTER_IPV4_CIDR
   - name: SERVICES_IPV4_CIDR
     value: SERVICES_IPV4_CIDR
   - name: GCLOUD_USER
     value: GCLOUD_USER
```

- `aks`
_TBD_

- `eks`
Use `eksctl` (1) to test the prompted cluster configuration (2) to retrieve the missing data. 

- `ocp`
_TBD_

- `gke`
Use `glcoud` (1) to test the cluster configuration (2) to retrieve the missing data. 

- `pks`
A `pks` cli is available, but cannot be used to retrieve the missing data. The user must provide the values for CLUSTER_IPV4_CIDR, SERVICES_IPV4_CIDR, and GCLOUD_USER.

**Comment by dirkwall** [comment]
@johannes-b is this still relevant?

**Comment by johannes-b** [comment]
Retrieving the CLUSTER_IPV4_CIDR or SERVICES_IPV4_CIDR is not needed anymore and the Keptn CLI tries to get the cluster information from `kubectl config current-context`.

Thus, this issue not not relevant anymore. I will close it.
