### ISSUE TITLE
Provide a more accurate error description for SLO validation issues

### ISSUE THREAD

**Issue by robertjahn** [keptn/keptn#4382]
**Is your feature request related to a problem? Please describe.**
I misconfigured the dynatrace secret but the error message said I was missing the secret.  I had mistakenly used the variable name `DT_URL` versus `DT_TENANT` which is expected

**Describe the solution you'd like**
Have the service provide a more accurate message, like missing literal DT_TENANT

**Describe alternatives you've considered**
None

**Additional context**
Here is picture of error message
![image](https://user-images.githubusercontent.com/24907089/122290149-71e86e00-cec1-11eb-80a5-b6e39f8da8ba.png)

Here is the wrong value (but the secret was created OK)
`keptn create secret dynatrace --from-literal="DT_URL=abc" ....`

versus this that is the required name
`keptn create secret dynatrace --from-literal="DT_TENANT=abc" ....`

**Comment by robertjahn** [comment]
@oleg-nenashev  @johannes-b  - This may now be part of the some other issues, but if the output for error messages are the same then perhaps we can still keep this one open.

**Comment by thisthat** [comment]
This is a message provided by the integration, not by Keptn
