### ISSUE TITLE
Shipyard-controller and Bridge run into errors when using an `image` object for a configuration change

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#4384]
## User story

As a user, I have a Helm Chart with a `values.yaml` file that looks as follows:
```
image:
  repository: docker.io/keptnexamples/carts
  tag: 0.11.1
```

Consequently, I would like to trigger a new delivery for this Helm Chart by sending an event: 

```
{
  "data": {
    "configurationChange": {
      "values": {
        "image": {
          "repository": "docker.io/keptnexamples/carts",
          "tag": "0.11.3"
        }
      }
    },
    "deployment": {
      "deploymentURIsLocal": null,
      "deploymentstrategy": ""
    },
    "project": "sockshop",
    "service": "carts",
    "stage": "dev"
  },
  "source": "https://github.com/keptn/keptn/cli#configuration-change",
  "specversion": "1.0",
  "time": "2021-06-17T07:44:29.173Z",
  "type": "sh.keptn.event.dev.delivery.triggered"
}
```

### Bug Shipyard-controller

* The shipyard-controller runs into an error since it cannot deal with an `image` object in `values`. 
* If I rename `image` to `my_image`:

``` 
      "values": {
          "my_image": {
            "repository": "docker.io/keptnexamples/carts",
            "tag": "0.11.3"
        }
      }
```

everything works fine. Nevertheless, this does not reflect the `values.yaml` file of the Helm Chart. 

### Bug Bridge

When sending the above-mentioned event to Keptn, the Bridge runs into an Error: 

![image](https://user-images.githubusercontent.com/729071/122363453-3b5e3200-cf59-11eb-88f3-7a8bc38085d2.png)

* Implement a fallback to not show the image:tag if it is not available. > The bridge should still continue to work

### Acceptance criteria: 

- [ ] I can send the above-mentioned event to Keptn and the image gets deployed by the helm-service.

**Comment by johannes-b** [comment]
Is this bug also addressed from a core perspective?

**Comment by Kirdock** [comment]
> Is this bug also addressed from a core perspective?

Yes, see https://github.com/keptn/keptn/pull/4474

**Comment by johannes-b** [comment]
Many thanks for the clarification. I will close the issue then.
