### ISSUE TITLE
Make the upstream repo page have larger fields

### ISSUE THREAD

**Issue by robertjahn** [keptn/keptn#4398]
**Is your feature request related to a problem? Please describe.**
In the bridge,  the upstream repo page has not very wide fields making it hard to read value like the repo url field.

**Describe the solution you'd like**
Like to see a wider fields names as to see a larger string especially for repo url field.  This is not functional problem, more just nice to have on the cosmetic point of view.

**Describe alternatives you've considered**
None

**Additional context**
Here is screenshot showing how the repo url field cuts off the value.
![image](https://user-images.githubusercontent.com/24907089/122433521-4e2a3400-cf64-11eb-8afa-7bf5f3c75036.png)

**Comment by laneli** [comment]
Fixed with #4493
