### ISSUE TITLE
Vague error message when setting Git upstream

### ISSUE THREAD

**Issue by TannerGabriel** [keptn/keptn#4399]
**Environment**

* Client OS (e.g., Linux, macOS, Windows): Linux
* Keptn Version (`keptn version`): v0.8.3
* Kubernetes Cloud Provider (e.g., GKE, AKS): GKE

**Affected Component**

* [X] CLI

**Describe the bug**
The error message is really vague when making a typo in the `keptn update project` command. I had a small typo in the project name when using the command for setting a git upstream where I wrote `sockhop` instead of `sockshop`.

```
keptn update project sockhop --git-user=$USERNAME--git-token=$TOKEN --git-remote-url=$REMOTE
```

This led to the following error message:

```
Starting to update project
Error: Update project was unsuccessful. Received unexpected response: 500 500 Internal Server Error
```

This error message does not suggest that the input is wrong and makes it hard to debug the error. It would probably be advantageous to implement specific error messages for events when the project can not be found, e.g. `Error: Updating project was unsuccessful since the provided project could not be found. Please check the input information`.

**Comment by warber** [comment]
Consider cleaning up other Endpoints which also have this problem.
