### ISSUE TITLE
Provide instructions to create a PKS cluster

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#440]
In the docs section of keptn.sh, the installation instructions should explain how to create a PKS cluster for keptn. Therefore, a dedicated section is provided in: **keptn.github.io\content\docs\develop\installation\setup-keptn**

**Comment by johannes-b** [comment]
![Capture](https://user-images.githubusercontent.com/729071/59418027-97b97480-8dc8-11e9-858d-28c7bc87477d.PNG)

**Comment by dirkwall** [comment]
Can we just link to the PKS documentation where the setup is described? 
E.g.: https://docs.pivotal.io/runtimes/pks/1-3/
I think it's OK to go into detail with GKE, as it's our main platform and it's pretty easy. I don't want to spend time on maintaining an installation guide for setting up PKS.

**Comment by dirkwall** [comment]
@johannes-b is the link enough? Do you want to provide more information here?
