### ISSUE TITLE
Automate setting the default `shkeptnspecversion` in `keptn/go-utils`

### ISSUE THREAD

**Issue by bacherfl** [keptn/keptn#4404]
In our [keptn/go-utils](https://github.com/keptn/go-utils), we have a couple of helper functions for sending CloudEvents. These also make sure that the property `shkeptnspecversion` is set, if it is not already included in the passed CloudEvent. The default value for this property is set here: https://github.com/keptn/go-utils/blob/28ca6b2be5dcb1cfe45509696a7f68e5a5296e0f/pkg/lib/v0_2_0/events.go#L25

However, this is likely to get overlooked when a new version of the `go-utils`, that is based on a new version of the [keptn/spec](https://github.com/keptn/spec) is released. 
Therefore, it would make sense to have an automated step that updates that property via a PR, once a new version of the spec has been released.

**Definition of Done:**

Once a new version of the [keptn/spec](https://github.com/keptn/spec) has been released, a PR to the master branch of [ktpn/go-utils](https://github.com/keptn/go-utils) is created. This PR makes sure that the correct `shkeptnspecversion` is added to the CloudEvents that are being sent via this library.

**Comment by christian-kreuzberger-dtx** [comment]
@bacherfl @mowies 

We already have this available as an environment variable in the helm charts:

https://github.com/keptn/keptn/blob/2ca7f4277b1eda2e873f9d96825f90df6f2ecee8/.github/workflows/CI.yml#L253-L256

https://github.com/keptn/keptn/blob/2ca7f4277b1eda2e873f9d96825f90df6f2ecee8/.github/workflows/CI.yml#L607-L616

Please discuss which way we want to go forward in the future ;)
