### ISSUE TITLE
CLI help to show all flag options

### ISSUE THREAD

**Issue by robertjahn** [keptn/keptn#441]
**Is your feature request related to a problem? Please describe.**
several of the keptn help pages do now show the flags for example 'keptn create project' and 'keptn onboard -h'

**Describe the solution you'd like**
Show available flags.  For example 'keptn onboard service' has these two for example: ' --project=sockshop --values=values_carts.yaml'

**Describe alternatives you've considered**
None

**Additional context**
While in this code, consider also making the 'KEPTN' logo in the output smaller as to not take up a whole page and getting cropped on laptop screens.  
![image](https://user-images.githubusercontent.com/24907089/59346421-3918cb80-8ce0-11e9-8838-2ee4be49e4eb.png)

**Comment by agrimmer** [comment]
Thank you for your descriptions!

However, the help messages correctly show the flags.
- For `keptn create project` there are no flags.
- For `keptn onboard` there are no flags.
- For `keptn onboard service` the flags are shown correctly.

Furthermore, we know that the keptn logo is large. However, it is only shown when `keptn` is called w/o any sub-commands.
