### ISSUE TITLE
github-service returns a success response before files are available on GitHub

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#442]
When creating a project or onboarding a service, files are committed and pushed to GitHub. 
Currently, the github-service immediately closes the websocket communication after a successful HTTP response from the GitHub API. However, GitHub takes some time to apply these changes. 
Here, we can run into race conditions when e.g. further files are written in a following command.

**Proposed Solution:**
The github-service has to check whether the files are available on GitHub. Only when the files are available in GitHub, the github-service should return.

**Comment by dirkwall** [comment]
Consider this issue in #451 . Closing.
