### ISSUE TITLE
Upgrade Meta Keptn to 0.8.4

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#4421]
Keptn 0.8.4 is out, please upgrade Meta Keptn to 0.8.4.

Don't forget to also upgrade the keptn-exec based helm-service and jmeter-service to 0.8.4.

# Definition of Done

- [x] Meta Keptn control-plane is upgraded to 0.8.4
- [x] helm-service and jmeter-service are upgraded to 0.8.4

**Comment by mowies** [comment]
The upgrade to 0.8.4 was successful, both control plane and execution plane got upgraded to 0.8.4
