### ISSUE TITLE
Dynatrace Service NG: Allow to setup Dynatrace monitoring using CLI (including management zones and a dashboard)

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#443]
Currently, we use a shell script for setting up Dynatrace monitoring. However, they only work for our demo application (sockshop/carts).
Furthermore, they only work for Linux and Mac.
Going forward we should generalize the monitoring setup and allow to setup monitoring from the CLI/

```console
kubectl apply -f  github.com/keptn-contrib/dynatrace-service/dynatrace-service/deploy/
keptn configure monitoring dynatrace --api-token ... --paas-token ... --tenant-id ...
```

**Comment by christian-kreuzberger-dtx** [comment]
Part of this will also be to automatically create (if possible):

* Management Zone for the Keptn Installation
* Simple Dashboard
* Tagging rules
