### ISSUE TITLE
CLI prints deprecation warning about extensions/v1beta1 when doing keptn auth

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#4432]
With Keptn 0.8.4, when executing `keptn auth` without parameters, the following deprecation warning is shown:
```
$ keptn auth
W0622 09:12:38.907621  114793 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
```

This is caused by the function `GetKeptnEndpointFromIngress` which is implemented in kubernetes-utils:
https://github.com/keptn/kubernetes-utils/blob/334fb680480c179fdee3503dc6297ce067457945/pkg/kubernetes-utils.go#L345-L357

# Definition of Done

- [ ] The warning is no longer shown when executing `keptn auth` without parameters
- [ ] kubernetes-utils function `GetKeptnEndpointFromIngress` has been adapted to also work with `networking.k8s.io/v1` 
- [ ] Get rid of all beta APIs

**Comment by ritwizsinha** [comment]
Hello, I would like to work in it, I have been playing around with Keptn for some days and would like to take this up to have my first entry point in the project

**Comment by thisthat** [comment]
Hi @ritwizsinha! Thank you for helping us :smile: 
I will assign the issue to you then!

**Comment by ritwizsinha** [comment]
So, what I understand from looking at some documentation and looking at this [kubernetes-client](https://pkg.go.dev/k8s.io/client-go/kubernetes@v0.21.3) package is that I have to use the [Networking V1](https://pkg.go.dev/k8s.io/client-go/kubernetes@v0.21.3#Clientset.NetworkingV1) type of client which allows us to interact with features given by networking.k8s.io group to avoid a warning

The task list above says that 
> kubernetes-utils function GetKeptnEndpointFromIngress has been adapted to also work with networking.k8s.io/v1

The question I have is, do I have to replace the v1Beta1 client with the networkingv1 client or do I have to use the networkingv1 client whenever the v1beta1 client shows a warning.

**Comment by nvzard** [comment]
@thisthat can I pick this up?

**Comment by thisthat** [comment]
Hey @nvzard sure! Thank you a lot for helping us out 😊

**Comment by nvzard** [comment]
Can someone please review this? https://github.com/keptn/kubernetes-utils/pull/163

I guess I'll also need to upgrade the version of kubernetes-utils package being used by keptn cli?

**Comment by nvzard** [comment]
https://github.com/keptn/go-utils/pull/492

Made the PR for the correct repo. Can someone please review it?
