### ISSUE TITLE
Bridge: Show current subscriptions in Uniform Screen

### ISSUE THREAD

**Issue by warber** [keptn/keptn#4436]
## User Story
As a User
I want to be able to add additional subscriptions to my Keptn integration running on a remote execution plane or on a control plane

### Details
When opening the Uniform Screen of Keptn, the User shall have the possibility to add additional subscriptions to a Keptn Integration.

### Showing existing subscriptions
When clicking on a Keptn integration listed in the Uniform screen, the user is able to see an expandable tile called "Subscriptions" in the lower half of the screen. 

:information_source:  *Note that the already existing Errors view shall also be moved into a separate expandable tile*

The expandable tile holds the UI elements for showing/adding/deleting subscriptions:
![image](https://user-images.githubusercontent.com/729071/125417384-232a3f48-d188-4e98-83dc-7a6709c409fe.png)

**Comment by johannes-b** [comment]
**Update** 

* The above table should show all Keptn-service (Integrations) that are connected to the Control-Plane.
* If a service has no active subscription for the project, it is displayed in gray, and the tool-tip shows: 
```
Servicenow-service is not active for project sockshop. 
Add subscription to activate it for sockshop.
```
![image](https://user-images.githubusercontent.com/729071/126283567-b1de7bb5-6951-4f11-8d94-98cd80ef3fe6.png)

* After creating a subscription for the Keptn-service in this project, it is activated and turns from grey-style to "normal".

@Kirdock do you agree with that approach? I will also provide an update on https://github.com/keptn/keptn/issues/4437 to explain the data structure that is required for that.
