### ISSUE TITLE
Release 0.8.4-hotfix1

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#4479]
Create a hotfix release for 0.8.4 that incorporates the following Issue:

* #4476 (PR: https://github.com/keptn/keptn/pull/4481 )

**Comment by christian-kreuzberger-dtx** [comment]
Unfortunately the version `0.8.4-hotfix1` is a bad choice, as it suggests that it is a pre-release and that `0.8.4` is newer.
See this table for comparison:
![image](https://user-images.githubusercontent.com/56065213/123221591-63a4de00-d4cf-11eb-8c17-9f616f2f8549.png)

Due to this, we are presenting the user a message when installing 0.8.4-hotfix1 in bridge:
![image](https://user-images.githubusercontent.com/56065213/123221626-6bfd1900-d4cf-11eb-8e56-39778f08f7e6.png)

**Comment by warber** [comment]
Since there is no solution to this problem, the team decided to deliver the bugfix with version number `0.8.5` #4527
