### ISSUE TITLE
Integration Tests: multiple keptn integrations reacting to same triggered event

### ISSUE THREAD

**Issue by warber** [keptn/keptn#4496]
## Action Item

- [ ] Create an integration test using a shipyard that is configured to let multiple keptn integrations react to a `*.triggered` event.

## Acceptance Criteria
- [ ] Integration test passing, testing the above scenario
- [ ] Write the integration in GO

**Comment by thisthat** [comment]
Superseded by https://github.com/keptn/keptn/issues/8695
