### ISSUE TITLE
Expose nats-cluster via WebSockets

### ISSUE THREAD

**Issue by warber** [keptn/keptn#4498]
## Action Item

Currently, Keptn integration running on a remote execution plane does not have direct access to the `nats-cluster` just like it is the case for services directly running on the control plane. To overcome this issue, we use a polling mechanism in the `distributor` sidecar that polls for all open `*.triggered** cloud events from the public Keptn API and forwards them to the Keptn integration.

:information_source: Version 1.11.0 of the nats client for GO supports connecting to `nats-cluster` using the WebSocket protocol.
Note that `distributor` is already using that version.

:information_source: `nats-server` needs to be updated to version `2.2.0+` (currently: `2.1.9`)

## Acceptance Criteria

- [ ] Websocket interface of `nats-cluster` is exposed via `nginx` so that external services can connect to it using WebSocket protocol in a secure way
- [ ] `distributor` connects to `nats-cluster` using the Websocket Protocol
- [ ] For backward compatibility, there shall still be the possibility to poll the events as it is done right now, however, this feature shall be deprecated

## Definition of Done
- [ ] feature implemented and reviewed
- [ ] integration tests passing (no new tests necessary)
- [ ] documentation (deprecation of old polling mechanism)
- [ ] installer adjusted
---
## Resources
https://www.nginx.com/blog/websocket-nginx/

**Comment by warber** [comment]
After discussing the architectural topics of Keptn, we came to the conclusion that from an architecture/security point of view it should be avoided to expose the internal NATS broker to the outside. Hence, I would propose to close this issue.

**Comment by thisthat** [comment]
I agree with @warber 
Let's explore alternatives with #6280
