### ISSUE TITLE
Trigger a CI Build (Docker, Helm Charts) on a PR using labels

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#4499]
Right now the label `CI:trigger-build-everything` can be set on a PR to ensure that we build all docker images and the respective helm charts.
However, right now we need to push a new commit to the PR to make this work. In addition, it does not work for external contributions.

To overcome this problem, I propose to introduce a cron-based workflow that checks for this (and potentially other labels), and triggers the build on the PR.

https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/blob/c149a3143e8b2b3071f367032c3aeb625ebf4f5e/.github/workflows/fork-test-trigger.yml#L19-L35

# Definition of Done

- [ ] Pull Request Full/Partial Builds can be triggered via a label, even for external contributors

**Comment by thisthat** [comment]
We agreed to not work on this and let the maintainers add the labels when needed.
