### ISSUE TITLE
On demand oauth discovery 

### ISSUE THREAD

**Issue by Kavindu-Dodan** [keptn/keptn#4504]
With the fix for #3780, we now have the ability to provide oauth based login to bridge. 

This solution uses an external oauth service and rely on service discovery [1].

However, in case bridge pod starts before the oauth service, current logic make it an error, failing to start the bridge.

**Improvement**

We should mark the initial oauth service discovery failures as warnings and use on demand discovery when user actually uses the bridge.

This should avoid unnecessary pod starts or deployment failures. 

[1] https://github.com/keptn/keptn/blob/master/bridge/server/user/oauth.js#L37

**Comment by agrimmer** [comment]
Will become obsolete, if we implement the OAuth flow in Bridge server.

**Comment by agrimmer** [comment]
We decided to implement the OAuth flow in Bridge. Hence, this ticket is obsolete.
