### ISSUE TITLE
Trigger a sequence from Bridge

### ISSUE THREAD

**Issue by laneli** [keptn/keptn#4507]
## User Story
As a user, I want to trigger a delivery, an evaluation, or any other custom sequence directly from the Bridge, to be able to manage sequences without the CLI.

### Mockup
https://tinyurl.com/kep-4507-full

### Description
General flow and UI are in the mockup. Some details:

There are two starting points for triggering a sequence in the Bridge:
* Environment screen - here I have the overview of the whole project
* Sequence screen - context-wise I would expect to be able to trigger a sequence also here

When the user clicks on the button "Trigger a new sequence"
* Environment screen: Opens the form
* Sequence screen: Redirects to environment screen with an open form

Special considerations:
* The Delivery option is displayed if and only if `KEPTN_INSTALLATION_TYPE`
is `CONTINUOUS_DELIVERY`
* When coming from the sequence screen nothing is preselected in the form
* When opening the form in the environment screen:
   * When a stage is selected the stage is prefilled with the selected stage
   * When only one service is available then it would make sense to preselect that one too
* When switching between sequences the data already entered for Service and Stage is preserved, as the first part of the form is the same
* Next button is disabled as long not all mandatory fields are filled
* The button "Cancel and close" just closes the form. There is no redirect back to sequences needed if coming from there

Evaluation sequence:
* For evaluation, it is possible to use a timeframe or a start and end time
* Start at / End is a DateTime picker that must also include a time picker with hours, minutes, seconds
* Start / End time is parsed to an ISO 8601 date
* Timeframe is parsed to a format that supports: https://pkg.go.dev/time#ParseDuration

Custom sequence:
* Other sequences than delivery and evaluation are parsed from the shipyard.yaml file (e.g. delivery-direct)

Trigger sequence:
* The button "Trigger sequence" is disabled as long as not all mandatory fields are filled
* After clicking "Trigger sequence" all buttons (including Back and Cancel and close) are disabled as long as there was no response. Additionally, the "Trigger sequence" button replaces the bolt icon with a loading spinner

### Acceptance criteria
- [x] Buttons are in place on the environment and sequence screen and interaction (redirecting) is possible
- [x] Form is fully implemented and interactable
- [x] Data is parsed correctly and sent to API when clicking on "Trigger sequence"
- [x] If the request is successful the user is redirected to the sequence screen
- [x] If the request fails, all buttons are enabled again and an error message is shown on the page

### Definition of done
- [x]  Everything in acceptance criteria implemented and manually tested
- [x]  Added Unit Tests
- [x]  Added UI Test
- [ ]  Documentation updated
- [ ]  Update of releasenotes_develop.md

**Comment by laneli** [comment]
https://tinyurl.com/kep-4507-1
https://tinyurl.com/kep-4507-2

**Comment by grabnerandi** [comment]
I really like Variant 1. Would be great to also see how this looks like for evaluation and especially for custom. I assume you will allow defining a custom data block. Would be great for both delivery and evaluation to also overwrite the sequence name as it is not mandatory that a sequence is called delivery or evaluation

**Comment by laneli** [comment]
@grabnerandi I also created a full mockup for var. 1, where all other use cases are included 😄 
https://tinyurl.com/kep-4507-full

**Comment by thschue** [comment]
Nice work! I like Version 2 more, but I agree to @grabnerandi that we should be able to trigger every sequence. I'm not sure if there should be an option to add labels or similar things to that, as there might be tasks depending on that. 

Nice work!

**Comment by robertjahn** [comment]
misc comments in no particular order....
1. Maybe put the "trigger sequence" button on each stage versus the top of the page.  If you click the button then it defaults to the stage value so I don't have to pick it.  
![image](https://user-images.githubusercontent.com/24907089/145896277-71e3b085-363e-4845-a36c-abbd0259875d.png)
2. Or a variation on the above, but next to each service so I dont have to pick service, or stage
![image](https://user-images.githubusercontent.com/24907089/145897046-023e74dd-a4a8-45ce-aec3-1b644e2ca200.png)
2. if you were to have just one trigger button - default the sequence stage and service values -- Normally I would run the sequence for the first stage -- so maybe default the stage if have one.  OR folks who just use quality gate use cases have just one stage, so if just one stage default the value
4. I am usually on the "sequence" page not the "environment" page when I review and want to rerun a new sequence. might be nice to have a "trigger again" button 
![image](https://user-images.githubusercontent.com/24907089/145896609-f554c92a-08c5-47ca-a30f-8b91fb60d0c8.png)

**Comment by ermin-muratovic** [comment]
I don't like the idea of Popups (Variant 2) and we rarely use them at the moment, but I also don't like having the form for triggering a sequence "built-in" to the environment screen. It feels weird to have the form just appear between the filter field and the stages.

I would prefer Variant 1 being on a separate page, which I could also serve with a direct link (deep link). Since we already jump to the form when clicking the button on the Sequence screen, we could do the same also from the Environment screen, opening a new page with just the form for triggering the sequence. Once the sequence is triggered, we might either always jump to the Sequence screen or just back to the screen where the user was before and clicked the button.

**Comment by laneli** [comment]
> I don't like the idea of Popups (Variant 2) and we rarely use them at the moment, but I also don't like having the form for triggering a sequence "built-in" to the environment screen. It feels weird to have the form just appear between the filter field and the stages.
> 
> I would prefer Variant 1 being on a separate page, which I could also visit with a direct link (deep link). Since we already jump to the form when clicking the button on the Sequence screen, we could do the same also from the Environment screen, opening a new page with just the form for triggering the sequence. Once the sequence is triggered, we might either always jump to the Sequence screen or just back to the screen where the user was before and clicked the button.

@ermin-muratovic 
Yes you are right, but the issue I see here is, where is it in the navigation tree? Is it also accessible from some other place, the settings for example? Also as we don't have any breadcrumbs I have the feeling that the user may get lost. I would say we go with the built-in form and if we see that it does not work we still can move it to a separate page. I wanted it to make it as quickly accessible as possible in the first step.

**Comment by ermin-muratovic** [comment]
I agree, let's have it like it is designed now and decide later if we need to move it to a separate page.

**Comment by robertjahn** [comment]
Hi -- this maybe for a step 2 enhancement -- but did you like any if the ideas of added a "re-trigger" button somehow too? https://github.com/keptn/keptn/issues/4507#issuecomment-992958056

**Comment by thschue** [comment]
> Hi -- this maybe for a step 2 enhancement -- but did you like any if the ideas of added a "re-trigger" button somehow too? [#4507 (comment)](https://github.com/keptn/keptn/issues/4507#issuecomment-992958056)

Hello! There's also a discussion and an issue for that (#6588)

**Comment by Dynatrace-Adam-Gardner** [comment]
I like the first variant but for me the most logical place for a trigger is on the sequences page:

<img width="382" alt="image" src="https://user-images.githubusercontent.com/13639658/152257654-2beb37bc-17fe-47f7-a499-dab4cddb4e00.png">
