### ISSUE TITLE
Make shipyard fully configurable in Bridge

### ISSUE THREAD

**Issue by laneli** [keptn/keptn#4508]
## User Story
As a user, I want to configure a shipyard while creating a new project, to not have to provide a shipyard file manually.

### Description
While creating a project or editing we should give the user the opportunity to either upload a shipyard file they already have or to let them configure the shipyard directly in the bridge.

On project creation:
![image](https://user-images.githubusercontent.com/729071/122954492-c5563280-d37f-11eb-9f54-f4ec471a6823.png)

On project edit:
![image](https://user-images.githubusercontent.com/729071/122954834-1108dc00-d380-11eb-8132-8213d862cf44.png)

The user should be able to:
* Create n Stages with
  * the possibility to give a custom name
  * This is not possible anymore after project creation - additional stages can not be added on edit!
* Create n Sequences with (possibility to add additional sequences to stage)
  * the possibility to choose from a template or to give a custom name
  * to select tasks
  * to order tasks
* On edit: Remove Sequences from stages (including all tasks related)
* On edit: Remove single tasks from sequences
 
When clicking on "Create Project" (on project creation) or on "Update Shipyard" the shipyard file is parsed and uploaded. In order to enable the buttons, it is necessary the shipyard has at least one stage (with one sequence + one task ?) defined.

When shipyard saving is successful, a success message is shown. In case of an error, an error message is displayed.
Success / error handling in case of project creation should be already implemented in #4493.

### Acceptance criteria
- [ ] Shipyard creation form
- [ ] "Upload Shipyard" button and stage adding restrictions in case of edit
- [ ] Validation if one stage (with one sequence + one task?) is present
- [ ] Parsing shipyard + upload
- [ ] Success / error handling in case of edit

### Definition of done
- [ ]  Everything in acceptance criteria implemented and manually tested
- [ ]  Added E2E Test
- [ ]  Documentation updated
- [ ]  Update of releasenotes_develop.md

**Comment by thisthat** [comment]
Open question: should the shipyard be fully configurable? For example, defining triggers, the delivery strategy, ...

**Comment by johannes-b** [comment]
I have put the `on hold` label on this issue because the shipyard (and the way of working with the shipyard) is subject to change when the KEP: https://github.com/keptn/enhancement-proposals/pull/67 becomes real.
