### ISSUE TITLE
Battle plan for monorepo

### ISSUE THREAD

**Issue by dirkwall** [keptn/keptn#452]
Going forward we want to have two keptn organizations and fewer projects.

keptn/keptn should hold all core components, the specification and the CLI
keptn/*-service could hold the batteries-included services, if they're not part of keptn/keptn

keptn-services/* should hold all keptn services, regardless if they're maintained by us or by others. This should also be the organization that is used for the first version of the wardrobe service.

**Comment by johannes-b** [comment]
The document [Battle Plan for Monorepo] (https://docs.google.com/document/d/1IpZ0f7Ra4ZQ82I_Ha2gnaDOtvQjcJyIKUFI_3jU2ZqE/edit?usp=sharing) summarizes the work of this issue. It outlines a plan for the reorganization of the keptn github organization and shows additional ideas in this regard.
