### ISSUE TITLE
Tooltip for Heatmap

### ISSUE THREAD

**Issue by vmasch** [keptn/keptn#4523]
As a user I want to have more information in the heatmap itself.
While discussing changes regarding the trend or individual metrics I don't want to scroll to the table serveral times.

It would be great to show
- the total score, the treshold and how many metrics are evaluated as yellow/red in the headline (score)
- the actual value, the treshold and whether it's a key metric for every sli

**Comment by grabnerandi** [comment]
Great request. I think this is super helpful when analyzing the heatmap - trying to get a quick understanding on why a certain metric is all of a sudden yellow or red. In a "day2day" life of a quality engineer you will analyze the heatmap with your peers and therefore hovering over and then seeing the score, the actual value and threshold as a tooltip would be extremely useful as it avoids annoying scrolling
