### ISSUE TITLE
Misdirected cursor

### ISSUE THREAD

**Issue by vmasch** [keptn/keptn#4524]
Sometimes the behavior of the cursor isn't comprehensible.

I'm using version 0.8.3 with Chrome.
![image](https://user-images.githubusercontent.com/51320708/123617380-79840d00-d807-11eb-9c1d-82186e3b94ec.png)

When switching from heatmap to chart and back again the cursor usually is back on its right place ;-)

**Comment by ermin-muratovic** [comment]
Can't reproduce this issue with the latest Keptn (Version 0.8.7) and latest Chrome (Version 92.0.4515.159)

Please note that we use [barista components](https://github.com/dynatrace-oss/barista) here for displaying the Heatmap, so if this issue occurs again it should be reported to that repository.
