### ISSUE TITLE
Deploy Configuration Service as a `StatefulSet`

### ISSUE THREAD

**Issue by warber** [keptn/keptn#4525]
## Action Item
The `configuration-service` shall be deployed as a `StatefulSet`.

### Details

Currently, we are deploying the `configuration-service` as a regular K8S deployment.
Because of this, and the fact that the configuration service is using a persistent volume claim (PVC) it cannot be deployed with a replica > 1.

Hence, the deployment specification of the `configuration-service` shall changed to use a `StatefulSet` instead of `Deployment`.

:exclamation: *Note, that in order to test the feature you need to use a K8S cluster with > 1 node.*

## Acceptatnce Criteria
- [ ] `configuraiton-service` is deployed as a stateful set which also supports the `rollingUpdate` deployment strategy

## Definition of Done
- [ ] feature implemented and reviewed
- [ ] installer adopted

**Comment by warber** [comment]
### Challenges observed when planning to run multiple replicas of the ConfigurationService

**GIT Repository**: The configuration service stores its data in a (local) GIT repository which is persisted using a K8s PV. When we run multiple instances (possibly on different nodes) the current state of the GIT repository needs to be in sync. Using a replicated volume (distributed fs) underneath seems to be not practical as we cannot assume that all platforms Keptn will be installed to support that. What's left is to manage that synchronization on the application level, meaning that instances of the configuration service would need to talk to each other and update the local state of the git repository in some way. This applies at least in the situation where we do not have an upstream git repository configured. Otherwise, the upstream repository could be taken as a single source of the current state of the git repository. However, requiring to configure an upstream git repository, in any case, can also be seen as not practically from a user perspective.

Possible solution (needs discussion) :
The problem above applies at least in the situation when we do not have an upstream GIT repository configured. If we would have that all the time, the upstream repository could be seen as a single source of the current state. However, requiring to configure an upstream git repository, in any case, can also be seen as not user-friendly. However, we could discuss shipping an internal GIT server with keptn core, which is used as the upstream if none is configured.

**Comment by johannes-b** [comment]
Please follow and discuss the comment here: https://github.com/keptn/enhancement-proposals/pull/48#issuecomment-925533808

**Comment by thisthat** [comment]
We decided to rewrite the configuration-service, called resource-service, to scale to multiple replicas.
