### ISSUE TITLE
helm-service - service labels should also be suffixed with "-primary" when blue_green_service is used

### ISSUE THREAD

**Issue by tolleiv** [keptn/keptn#4540]
**Environment**

* Client OS (e.g., Linux, macOS, Windows): not relevant
* Keptn Version (`keptn version`): 0.8.4
* Kubernetes Cloud Provider (e.g., GKE, AKS): AWS EKS
* Kubernetes version (`kubectl version`): 1.21.0
* Istio Version 1.9.5

**Affected Component**
helm-service

* [ ] Docs
* [ ] CLI
* [x] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [ ] Bridge
* [ ] Approval
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**
When releases are deployed with the `deploymentstrategy: "blue_green_service"`  the related pods will have their `app`  and `app.kubernetes.io/name` labels adjusted with the `-primary` suffix while the actual Kubernetes services objects will keep their `app` labels without the suffix. This leads to some inconsistency in the overall configuration where the canary-service and the primary-service share the same `app` label, while the Pods have different labels. When using tools like Kiali to observe the ServiceMesh this even leads to more confusion as applications are not visible consistently for users. 

**To Reproduce**
Deploy some application which has a service with a `app` label configured.
E.g. the sockshop example with these service configurations:
```
--- 
apiVersion: v1
kind: Service
metadata: 
  name: carts
  labels:
    app: carts
spec: 
  type: ClusterIP
  ports: 
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector: 
    app: carts
```

 Inspect the related pods and service with and see the inconsistency:
```
$ kubectl get services,pods -n sockshop-dev -L app | grep -v db
NAME                       TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)     AGE     APP
service/carts              ClusterIP   172.20.187.245   <none>        80/TCP      115s    carts
service/carts-canary       ClusterIP   172.20.184.235   <none>        80/TCP      37s     carts
service/carts-primary      ClusterIP   172.20.8.60      <none>        80/TCP      37s     carts

NAME                                    READY   STATUS             RESTARTS   AGE     APP
pod/carts-b4495d7c4-cx5pm               2/2     Running            0          115s    carts
pod/carts-primary-6c48784d54-78ft6      1/2     Running            0          37s     carts-primary
```

**Expected behavior**
I'd expect that the `carts-primary` service also carries the `carts-primary` app label to be consistent with the pods.

**Current behavior**
The `app` label of the pods is changed to `carts-primary`, the service keeps the `app` label unmodified.

**Screenshots**
-

**Additional context**
-

**Comment by johannes-b** [comment]
The issue has been implemented in: https://github.com/keptn/keptn/pull/4541
