### ISSUE TITLE
Return metadata during Pitometer Runs

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [keptn/keptn#460]
As a pitometer user I want to enable consumers of the pitometer output so that they can more quickly resolve issues.

Return the `metadata` object (remembering that `metadata` will be in an arbitrary structure or not present at all) allowing the client to parse this to suit their needs.

**Comment by agrimmer** [comment]
Related to #540

**Comment by bacherfl** [comment]
The latest version of the bridge in keptn 0.5.0 solves that.
