### ISSUE TITLE
Push Button Dummy Event Channel for Testing

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [keptn/keptn#461]
As a **keptn service developer** I want to test the event > service workflow on demand, rather than forcing an event into one of the "proper" event channels.

In short, I want a way to create my service, configure the event channel subscription and run a "test integration" command to see if my service works or not.

**Comment by agrimmer** [comment]
Currently, triggering a test only is not supported yet. But we see the need and will consider this.

**Comment by dirkwall** [comment]
We provide a postman collection of CloudEvents that you can use for local testing. Once we have the KeptnEngine we can think about providing a test-topic to quickly check new integrations. This is out of scope right now.
