### ISSUE TITLE
Remove deprecated links for bridge 0.10.0

### ISSUE THREAD

**Issue by laneli** [keptn/keptn#4612]
For being backward compatible there are still some deeplinks contained that are already marked as deprecated.
With version 0.10.0 we should remove them entirely.

```
project/:projectName/:serviceName
project/:projectName/:serviceName/:contextId
project/:projectName/:serviceName/:contextId/:eventId
```

## Acceptance Criteria
- [x] Routes are removed from routing module

## Definition of Done
- [x] No remaining routing for the routes in the application
- [x] No remaining routing for the routes in tests (unit and integration)
- [x] Bridge documentation is updated

**Comment by johannes-b** [comment]
As mentioned here: https://keptn.sh/docs/0.8.x/reference/bridge/deep_linking/#deprecated-links
