### ISSUE TITLE
Approvals are not excluded from task timeout

### ISSUE THREAD

**Issue by Kirdock** [keptn/keptn#4620]
At the moment there is a task timeout for all tasks, including approvals.
Approvals require manual interaction and therefore we don't need a timeout here.
![image](https://user-images.githubusercontent.com/11599148/125244050-26be5100-e2ef-11eb-861f-e6a25ee8156e.png)

**Comment by johannes-b** [comment]
The implementation of the issue: https://github.com/keptn/keptn/issues/3778 (ShipyardController: Termination of orphaned tasks) terminates a sequence when a task is `.triggered` that does not receive a `.started` event. 

To address the above-mentioned bug, the approval service has to send out an `approval.started` event when reacting on an `approval.triggered` event. 
* If the approval is set to *automatic* then the approval-service will take care of sending the `approval.finished`
* If the approval is set to *manual*  then the `finished` event will be received when, e.g., the user presses a button in the Bridge. 

By sending the `approval.started` immediately, the timeout (`TASK_STARTED_WAIT_DURATION`) of the shipyard controller gets ignored and the task can stay open as long as needed. 

**To be discussed**: If this is implemented, the Bridge does not need to send the `approval.started` event anymore.
