### ISSUE TITLE
Improve layout of configuring Git upstream repository

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#4623]
The new feature to set the git upstream right through the Keptn UI is great - however - I suggest some layout updates to make it easier to use
a) I suggest to make the github url field bigger as URLs tend to be longer and I like to see what I pasted in there
b) I suggest to put username & token in a separate row - giving the URL more space
c) I suggest to use a password field for the token. Especially when sharing screens you dont want the token to be exposed

here a quick mockup how that could look like

![image](https://user-images.githubusercontent.com/675886/125284660-03f56200-e31a-11eb-8a46-b0ad2859a86c.png)

**Comment by johannes-b** [comment]
Hi Andi, thanks for the feedback!! 

We are already working on that aspect as part of: https://github.com/keptn/keptn/issues/4493

**Comment by johannes-b** [comment]
![image (7)](https://user-images.githubusercontent.com/729071/125455426-e87ebf6e-c718-49b7-8101-080dc1e2a886.png)
