### ISSUE TITLE
Troubleshoot upstream git issues

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#4626]
Its great we can set the upstream git via the Keptns Bridge or the UI - but - there is not much of troubleshooting details when setting hte upstream fails. The only thing the user sees is "Git Upstream URL could not be set". and that is true when the URL is wrong or not reachable, when the username is wrong or the token invalid

We need better error messaging - both as response to the action of updating the project as well as in the uniform screen in the log section. If the configuration service has an upstream but it cant reach it we should highlight this as an error

**Comment by grabnerandi** [comment]
I need to extend this request.
It is also possible that an already defined Git Upstream is broken, e.g: tokens became invalid, url no longer reachable ..

This is a critical error because the configuration service cannot deliver any resource any more as it constantly runs into errors when requesting fiels bc the git upstream is not reachable

we had a situation where the complete keptn project was unusable but it was not obvious to the user as there was no error indication except in the configuration-service logs which said

```
Could not add upstream repository while updating project dynatrace: failed to set upstream: Error executing command git push --set-upstream http://kxxxxxxx/keptn/dynatrace.git master: exit status 128 remote: invalid credentials from 10.42.0.1 fatal: Authentication failed for 'http://xxxxx/keptn/dynatrace.git/' Keptn requires an uninitialized repo
```

**Comment by thisthat** [comment]
## Decision by the team
The `configuration-service` and `shipyard-controller` should report internal errors via the `/event` endpoint.
UI changes will be implemented in #tbd
