### ISSUE TITLE
No error description when lighthouse fails to parse SLO.yaml

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#4629]
This happens in Keptn 0.8.6

When modifying the slo.yaml and breaking it, e.g: incorrect YAML - the next quality gate evaluation will fail with an error from the lighthouse without any indication of what is actually wrong. Here is a screenshot of what the user sees in the bridge
![image](https://user-images.githubusercontent.com/675886/125308502-3f4f5b00-e331-11eb-98c3-47a08b804582.png)

Here is the lighthouse service finished event json:
```
{
  "data": {
    "evaluation": {
      "gitCommit": "",
      "indicatorResults": null,
      "result": "",
      "score": 0,
      "sloFileContent": "",
      "timeEnd": "2021-07-12T14:39:06.000Z",
      "timeStart": "2021-07-12T14:09:06.000Z"
    },
    "labels": {
      "buildId": "4",
      "executedBy": "manual"
    },
    "project": "dynatrace",
    "result": "fail",
    "service": "journeyservice",
    "stage": "quality-gate",
    "status": "errored"
  },
  "id": "41aff8b6-54ad-4a38-8153-0a27f0f4a8a7",
  "source": "lighthouse-service",
  "specversion": "1.0",
  "time": "2021-07-12T14:39:07.929Z",
  "type": "sh.keptn.event.evaluation.finished",
  "shkeptncontext": "c7b372db-640e-44de-adec-50d6d39008fe",
  "shkeptnspecversion": "0.2.3",
  "triggeredid": "d9c5b4b9-00ad-4935-b47e-d7dc8cb997d9"
}
```

In my situation today it was just an indent issue with a new slo that was added. 
It would be helpful to get this information as part of the error message from the lighthouse

**Comment by johannes-b** [comment]
Closed due to duplicate to: #5130
