### ISSUE TITLE
Better error reporting when stage name is incorrect

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#4635]
When I trigger an event and specify a stage that doesnt exist I dont get an error message indicating that the problem is the missing stage. i get errors from keptn services that e.g: they cant find certain resources. This is very misleading as it is hard to find the true root cause

Here is an example. My stage is called "quality-gate" but accidentially I sent an event with the stage name "quality-stage". The Keptns Bridge shows the full automation sequence. all tools such as lighthouse or dynatrace-sli service were triggered. While the error message that no SLO.yaml could be found is correct - the reason is that the stage simply doesnt exist

![image](https://user-images.githubusercontent.com/675886/125432488-3b5e9e1a-25e5-4fa3-aed4-eb2d4342b27a.png)

I think the proper handling should be that the shipyard controller doesnt execute any sequence but simply throwns an error that the stage is invalid

**to reproduce**
send an evaluation.triggered event with a stage that doesnt exist in your shipyard

**Comment by thisthat** [comment]
This problem has been solved. I just checked: 
![image](https://user-images.githubusercontent.com/992621/148203938-222417ee-b653-475b-bdca-149b7f2bb099.png)
