### ISSUE TITLE
Provide REST API for "New Artifact" exposed to external tools

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#464]
**Is your feature request related to a problem? Please describe.**
While we have a new keptn cli option to send a "new artifact" event we currently cant send a new artifact event form an external tool that is not able to interact with the keptn cli.
many tools provide a scripting language to e.g: execute HTTP Requests in order to integrate with external tools. For those tools, e.g: ServiceNow, GitLabs, ... we cant use the keptn cli

**Describe the solution you'd like**
It would be great to allow sending the cloud native "new-artifact" to the external event broker via HTTPS. that would make integrations with external tools easy!

**Comment by agrimmer** [comment]
Each external tool can send even arbitrary keptn events (not limited to new-artifact events) to the `control-service` to the endpoint /event (the control-service is publicly available). The only requirement is that the post has an HTTP Header called `X-Keptn-Signature`, which contains the SHA1-hash calculated with the api-token and the body. This header ensures that only authorized tools (i.e. tools knowing the keptn api-token) can send events.

**Comment by Dynatrace-Adam-Gardner** [comment]
Does this also cover / resolve #461 ? I'd love to get this documented @agrimmer

**Comment by agrimmer** [comment]
In the last weeks, we replaced the `control-service` as well as the `eventbroker-ext` with a single service called `api`. This `api` service provides an endpoint called `/event`, which takes POST requests with an arbitrary keptn event as payload. For authentication, no SHA1-hash is needed anymore. Instead we simply use an HTTP header called `x-token` which has to be set to the keptn API token. 
In case you have any further questions, please reach out to us e.g. on Slack using our keptn channel: https://join.slack.com/t/keptn/shared_invite/enQtNTUxMTQ1MzgzMzUxLTcxMzE0OWU1YzU5YjY3NjFhYTJlZTNjOTZjY2EwYzQyYWRkZThhY2I3ZDMzN2MzOThkZjIzOTdhOGViMDNiMzI
