### ISSUE TITLE
Make jmeter service configurable

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#466]
Currently the jmeter-service does require a certain naming convention for the jmeter test files as well as the port 80 to be exported by the services under test.

desired output:
- have the name of the jmeter file as a parameter
- have the port of the service to be tested as a parameter

**Comment by agrimmer** [comment]
Additionally to making the jmeter-service configurable, it should also provide logs. Currently, the jmeter-service only has logs in the pods which are overwritten by each run.

**Comment by avodaqstephan** [comment]
> Additionally to making the jmeter-service configurable, it should also provide logs. Currently, the jmeter-service only has logs in the pods which are overwritten by each run.

Just for clarification. Overwritten by each run includes running through different stages. It would be okay - not the best - if there are log files for each stage which will be overwritten by sending a new-artifact. 

I would suggest something like a results folder, which saves the log files for at least the last 10 runs (including alle stages) and it would be nice, if you could add the name of the stage to the log files.
