### ISSUE TITLE
After restore I have duplicates in my Uniform

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#4664]
**Environment**

* Client OS (e.g., Linux, macOS, Windows): macOS
* Keptn Version (`keptn version`): 0.8.6
* Kubernetes Cloud Provider (e.g., GKE, AKS): -
* Kubernetes version (`kubectl version`): -

**Affected Component**
Uniform

* [ ] Docs
* [ ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [ ] Bridge
* [ ] Approval
* [x] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**
I used Keptn 0.8.6 and did a backup and restore as described here https://github.com/keptn/keptn/pull/4663/checks?check_run_id=3077078432. After the restore, I get duplicate services in the Uniform.

**To Reproduce**
1. Make a backup
2. Restore using the backup
3. Check the Unifrom screen in Bridge

**Expected behavior**
Unifrom should not be restored.

**Current behavior**
Uniform is also restored.

**Screenshots**
![image (2)](https://user-images.githubusercontent.com/10980861/125798747-c9e99101-14ca-4f8d-86db-ec88011598e1.png)
![image (5)](https://user-images.githubusercontent.com/10980861/125798759-1d2b2411-082c-4e8f-8f99-a0679261d222.png)

**Comment by thisthat** [comment]
This will be fix with #4615
