### ISSUE TITLE
Bridge: Provide a warning if data will be lost in Project Creation

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#4677]
## User Story
As a user, I want to be notified that I will lose the data entered in all settings views.

### Description

We can create projects directly from the Bridge with #4493. If a user fills in some fields and then tries to change the page, all the entered data will be lost.
A message that notifies the user about losing the data should be displayed. 

## DoD
- [x] A message that notifies the user is provided
- [x] Unit tests

**Comment by laneli** [comment]
- On create project the notification will not be shown as it does not make sense in this context.
- For create project it will get necessary when the shipyard is going to be configurable. Then we have to show a notification before you leave the page as loosing data will be painful. But this will be in the scope of another issue.
- For save project the notification will be show as it is, but only if the (only existing) git form is valid. This notification will allow to save and to discard the changed data.
- Another discard mechanism will not be implemented - but could be topic of a future story.
- Also for future extensions of the form, the notification will stay and extended as needed. Also not scope of this story

.
