### ISSUE TITLE
configuration-service: git pull first

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [keptn/keptn#4694]
**Is your feature request related to a problem? Please describe.**
Manual commits to a Git repo managed by Keptn can break the `configuration-service`. This happens even if the changes have been reverted (by that I mean the files end up identical but the commit IDs known to Keptn and what's on GitHub will be different).

**Describe the solution you'd like**
Keptn `configuration-service` could do a `git pull` first before pushing.

**Working Example of Issue**
```
keptn create project demo \
--shipyard=shipyard.yaml
--git-user=whoever \
--git-remote-url=wherever \
--git-token=whatever
```

Manually change the `shipyard.yaml` on GitHub. For example, adding a stage.
Manually remove the change to `shipyard.yaml` on GitHub. Do not revert the commit but instead commit again (fix forward).

**Describe alternatives you've considered**
Clearer documentation on what manual changes are allowed on GitHub (eg. direct changes to `sli.yaml` or `slo.yaml` files are OK but changes to files A, B, C and X have the potential to cause Keptn errors). Or a blanket statement: Any file modifications must be done via `keptn add-resource` commands so that Keptn knows about new commit IDs.

**Comment by warber** [comment]
Actually, there is already a `git pull` happening before any changes are applied on the git repository.
Could you please provide more information, what exactly isn't working anymore? Do you have any logs etc...?

**Comment by Dynatrace-Adam-Gardner** [comment]
I cannot recreate this now on `0.9.2` even adding a new stage to the shipyard, which used to cause this issue, no longer does.
Of course, the new stage won't show in the bridge but at least nothing breaks.

We can close this.
