### ISSUE TITLE
Better packaging for windows keptn binary

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [keptn/keptn#4769]
**Is your feature request related to a problem? Please describe.**
The keptn window binary is packaged in a .tar file which is then wrapped in a .tar.gz
This requires third party software (eg. 7zip) to extract on windows.

**Describe the solution you'd like**
This could be simplified for users by just generating the `.exe` in a `.zip` file.

**Comment by warber** [comment]
Note:
Make sure that `get.keptn.sh` still works with the applied changes.
