### ISSUE TITLE
Bridge: Disconnect git remote upstream 

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#4787]
## User Story

As a user, I would like to disconnect the remote Git repo from my Project.

![image](https://user-images.githubusercontent.com/729071/131094449-ab23d3dd-0523-4171-87bf-0283bbd5f31e.png)

### Technical Details 

If there is a Git remote upstream connected to the project, the project setting page shall also provide a button to disconnect the project from the remote upstream. 
Upon the disconnect button is clicked, it shall provide a popup windows (similarly to the click on the `delete` project button) where the project name is requested. 

## DoD 
- [ ] The configuration of the Git remote repo (in the Bridge) is deleted and the Disconnect button is disabled
- [ ] Unit tests
- [ ] UI tests
- [ ] Hide this feature behind FF

## Dependencies 
- [ ] https://github.com/keptn/keptn/issues/5158
- [x] https://github.com/keptn/keptn/issues/5211

**Comment by agrimmer** [comment]
Furthermore, there is currently no way to update an expired token, which makes Keptn unusable.

**Comment by thisthat** [comment]
I created https://github.com/keptn/keptn/issues/5149 to track the problem of updating a token

**Comment by thisthat** [comment]
This has become obsolete since we are transitioning to an upstream-only approach
