### ISSUE TITLE
Handle time parameters consistently

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#4788]
## Action Item

Make sure the correct time format (ISO8601) is used across all Keptn components.

## Aceptance Criteria

`go-utils` should be made more lenient and support more time formats.

## DoD 
The following formats are accepted and Unit Tested:

- [ ] "2020-01-02T15:00:00"
- [ ] "2020-01-02T15:00:00Z"
- [ ] "2020-01-02T15:00:00+10:00"
- [ ] "2020-01-02T15:00:00.000Z"
- [ ] "2020-01-02T15:00:00.000000000Z"

**Comment by RealAnna** [comment]
Can I have this please?
