### ISSUE TITLE
Evaluation screen not loading

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#4803]
When opening the services screen and navigating to the evaluation overview, the chart is not loading.
This is running on Keptn 0.8.7.

E.g., you can verify by navigating to this screen https://keptn.public.demo.keptn.sh/bridge/project/sockshop/service/carts/context/32bb840f-a88e-447f-a4fb-5701cbb8c1f6/stage/staging 

As highlighted in the screenshot, the evaluation for the staging environment receives a score of 100%. However, the details are not loading
![image](https://user-images.githubusercontent.com/7677092/128004151-99add7ca-7a78-42bb-934a-dad09fe59416.png)

A quick look via the developer tools reveals an error message:
![image](https://user-images.githubusercontent.com/7677092/128004222-ed12b4eb-361f-4dcb-8143-64010cdc72ba.png)

**Comment by Kirdock** [comment]
Already fixed by https://github.com/keptn/keptn/pull/4692
