### ISSUE TITLE
Adapt SLO specifications to support tags

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#4829]
## User Story

As a user, I would like to add tags to my objectives. 

## Details

The specification for SLO should be changed to support the (optional) `tags` field:

```
objectives:
  - sli: "response_time_p95"
    displayName: "Response time P95"
    tags:
     - frontend
     - Team-Abc
    key_sli: false
    pass:             # pass if (relative change <= 10% AND absolute value is < 600ms)
      - criteria:
          - "<=+10%"  # relative values require a prefixed sign (plus or minus)
          - "<600"    # absolute values only require a logical operator
    warning:          # if the response time is below 800ms, the result should be a warning
      - criteria:
          - "<=800"
    weight: 1

   ...
```

## DoD

- [ ] The SLO specifications are updated to the new format
- [ ] The Lighthouse service returns the `tags` data as part of the `evaluation.finished` event
- [ ] Unit and Integration tests

**Comment by johannes-b** [comment]
Hi @thisthat, 

thanks for creating this issue, but I have concerns about it. When we add `tags` to the SLO `objectives` I think we put them semantically at the wrong place. I see them closer to the SLI.yaml file. 

Nevertheless, I identified 4 options I would like to lay out here: 

# Option 1: SLO.yaml - no breaking change

```
---
spec_version: "1.0"
comparison:
  aggregate_function: "avg"
  compare_with: "single_result"
  include_result_with_score: "pass"
  number_of_comparison_results: 1
filter:
objectives:
  - sli: "response_time_p95"
    displayName: "Response time P95"
    key_sli: false
    tags:
      - frontend
      - team-abc
    pass:            
      - criteria:
          - "<=+10%" 
          - "<600"    
```

**Pro:** 
* No breaking change

**Con:** 
* "Tagging" not centralized, but rather spread across SLO definitions (duplicates)
* Semantically at a wrong place

# Option 2: SLI.yaml – no breaking change


```
---
spec_version: '1.1'
indicators:
  throughput: ""
  error_rate: ""
  response_time_p50: ""
  response_time_p90: ""
  response_time_p95: ""
tags:
  - test (should work global)
  throughput:
    - frontend
    - team-abc
   

```
   

**Pro:** 
* No breaking change
* Sementically at the right place

**Con:** 
* Duplication of SLI-key (e.g., throughput)
* Not a "nice" approach



# Option 3: SLI.yaml new – breaking change


```
---
spec_version: '2.0'
tags: 
- frontend
indicators:
  - key: throughput
    displayName: Throughput
    query: "builtin:service.requestCount.total...
    type: 
    unit: 
    tags:
    - team-abc
```

**Pro:** 
* Defintion of SLI as an Object - Most generic approach allowing for extension

**Con:** 
* Breaking change


# Option 4: SLI.yaml / SLO.yaml merger – breaking change

```
---
spec_version: '2.0'
comparison:
  aggregate_function: "avg"
  compare_with: "single_result"
  include_result_with_score: "pass"
  number_of_comparison_results: 1
filter:
objectives:
  - sli: "response_time_p95"
    displayName: "Response time P95"
    query: "builtin:service.requestCount.total...     
    key_sli: false
    tags:
      - frontend
      - team-abc
    pass:            
      - criteria:
          - "<=+10%" 
          - "<600"    
    warning:         
      - criteria:
          - "<=800"
    weight: 1
total_score:
  pass: "90%"
  warning: "75%"
```
