### ISSUE TITLE
Support not properly signed certificates for external mongo db instances

### ISSUE THREAD

**Issue by kristofre** [keptn/keptn#4836]
**Is your feature request related to a problem? Please describe.**
When using an external mongo db instance for keptn, it needs to have properly signed certificates. In internal (dev) environments that is not always the case.

**Describe the solution you'd like**
Support for certificates that are not signed by an authority

**Comment by mowies** [comment]
possibly related: https://github.com/keptn/keptn/issues/3457

**Comment by thisthat** [comment]
This issue should have been fixed by #5369. Please, feel free to reopen if something is still missing.
