### ISSUE TITLE
Cannot read property of 'score' undefined [Bridge]

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [keptn/keptn#4936]
I pushed a bad evaluation and now getting the Javascript error which breaks the bridge.

I now can't get to any sequence details (note the blank part of the right hand panel).

```
ERROR TypeError: Cannot read property 'score' of undefined
```

![image](https://user-images.githubusercontent.com/13639658/129513046-4b6403e4-873a-4f04-9d64-c62b69cc39bf.png)

Using the `generic-executor-service` listening for `evaluation.triggered` event, I coded a bug which caused the generic-executor-service to error. This presumably caused a null

![image](https://user-images.githubusercontent.com/13639658/129513509-0183149d-91bd-4e2f-97b0-c61942e9f4dd.png)

Regardless of any bugs or issues is services, the bridge shouldn't be broken due to bad code executing in a plugin.

**Comment by Kirdock** [comment]
Is probably fixed by https://github.com/keptn/keptn/pull/4806.
Needs to be checked if the error still exists.

**Comment by Kirdock** [comment]
Fixed in #4806
