### ISSUE TITLE
Evaluation of helm

### ISSUE THREAD

**Issue by dirkwall** [keptn/keptn#504]
Going forward, is Helm the right way to go?
- consider the use case of onboarding of 2 services and sending of a new-artifact event for one of those services
- consider the use case of release brackets (i.e. promotion of the current configuration in a stage, as discussed excessively in today's meeting)
- identify alternatives and create a comparison
- reach out to the community for ideas
- check how others are solving the issue of release brackets

**Comment by johannes-b** [comment]
In this document, findings for the above questions are summarized: https://docs.google.com/document/d/1T8vLDWsbJa7Dxz5pfI1TUqpIBqxWbOK0aJnnl5J0-I4/edit?usp=sharing
