### ISSUE TITLE
Bridge / chore: Include jest-dom and jest-extended

### ISSUE THREAD

**Issue by laneli** [keptn/keptn#5051]
As we now use Jest as our test runner, including two additional packages would make testing a bit easier:
* https://github.com/jest-community/jest-extended
* ~https://github.com/testing-library/jest-dom~

This package provides an additional matcher for testing more advanced matches.

**Comment by Kirdock** [comment]
The team decided that we don't need `jest-extended`. It doesn't provide any additional value, just partly evaluations like `isDate` or `isEven` but we compare everything with exact values.
