### ISSUE TITLE
Add Ingress option to Keptn installer manifests for control plane

### ISSUE THREAD

**Issue by bradmccoydev** [keptn/keptn#5066]
**Is your feature request related to a problem? Please describe.**
As I would like to use the GitOps paradigm for deploying Keptn to my Kubernetes Cluster
Then I would like the ability to specify ingress in the values.yaml
When Deploying with ArgoCD so I don't have to run ingress separate after

I would much rather it be an option in the helm chart so I have a clean deployment, and everything is declared in one place, instead of running it after.

**Describe the solution you'd like**
This ingress.yaml should be in the installer/manifests/keptn/charts/control-plane/templates and its config in the values.yaml under a new section called ingress (if under apiGatewayNginx it could create confusion).

The solution needs to have the ability to say enabled: true/false this will not break any existing or future deployments or config.

It also needs to cater for annotations, hosts, and tls as options

**Describe alternatives you've considered**
Alternative solutions are to not have this and just create my ingress after. eg kubectl create -f ingress.yaml

**Additional context**
I'm happy to write this code myself

**Comment by bradmccoydev** [comment]
@Dynatrace-Adam-Gardner @grabnerandi

**Comment by mowies** [comment]
Follow-up documentation ticket: https://github.com/keptn/keptn/issues/5297
