### ISSUE TITLE
Revamp keptn logging

### ISSUE THREAD

**Issue by dirkwall** [keptn/keptn#507]
Use fluent-bit for logging. Configuration in:stdout, out:http. Target is the DBAccessService (find a better name while implementing this), the is a wrapper service to a NoSQL database, e.g. MongoDB. The same service is used by the bridge to retrieves data from the database.

Default the DBAccessService is shipped with MongoDB. It should be possible going forward to use for example DynamoDB for that, by providing a different plugin to the DBAccessService.

Implement a distributor that subscribes to all topics and stores all NATS events in the database.

While doing that, standardize logging in all components and rework the logging instructions for custom services.

**Comment by bacherfl** [comment]
The setup of the new architecture is already completed in https://github.com/keptn/installer/tree/feature/507/keptn-logging . We do have to wait for an adapted version of the bridge that retrieves the log messages from the new datastore. As soon as this is ready, the feature branch in the installer repo is ready to be released.

**Comment by grabnerandi** [comment]
Some comments on logging
#1: In a simple new artifacdt run I have 74 log messages from pitometer saying "Evaluation is passed" -> please reduce to 1
#2: Pitometer Result: I want to have a single log entry that tells me whether Pitomter has failed or passed INCLUDING the actual score, e.g: Pitometer EValuation PASS - total Score 75
#3: I also want to see the Pitometer Result + Score in the Dynatrace Event
