### ISSUE TITLE
Implement workflow engine in KeptnKernel based on DONE/START event specification and prototype

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#508]
Start with the implementation of the WorkflowEngine that knows about the workflow and the desired transitions between states and phases. It stores the state for each workflow in the MongoDB.
For now, the WorkflowEngine should translate incoming DONE events to the appropriate next START event.

WorkflowEngine handles the keptn default workflows and knows about the transition between states. Workflow definitions are in code for now.
Implement the engine so it receives generic DONE events and dispatches START-* events.

For more details on the workflows see 
- https://drive.google.com/open?id=1kmunoBGAFEADFjoksbfzYVzdlJ60326h
- https://dynatrace-my.sharepoint.com/:p:/p/dirk_wallerstorfer/EWhc0vvnpOVKjyrcAbhjv9gBTR0rXAfGhAXUdGbFPeTFRg?rtime=tbbdqhUX10g

**Comment by johannes-b** [comment]
* Update of Postman collection
* Research in implementing an operator for the WorkflowEngine
  * How do manage keptn with operators? (one operator for all custom resource definitions?)
* Implementation of WorkflowEngine (project in monorepo)
* Implementation of Operator (project in monorepo)

**Comment by johannes-b** [comment]
Decision: For the first version of the WorkflowEngine, the configuration of the transition logic will be hard-coded and cannot be configurable. Thus, an operator will not be provided.

**Comment by johannes-b** [comment]
This issue is not relevant anymore. I closed it.
