### ISSUE TITLE
Bridge: Unify error / success notifications

### ISSUE THREAD

**Issue by laneli** [keptn/keptn#5087]
In the bridge we have currently 2 different ways of showing errors to users:
* With a grey popup (toast) on the bottom of the page that vanishes after a few seconds
    * This popup is used by the HTTP interceptor to push errors to the frontend
* With a red bar that shows error information on form submit

For success we use the same bar as for errors on form submit but in green.

Suggestion:
* Get rid of the interceptor error messages, as they are not very visible and do not provide useful information
    * For page loading / polling errors we already have a error message in place. Maybe we can reuse this instead of the toast messages.
* Use https://barista.dynatrace.com/components/alert instead of the `ktb-notification-bar` for form submit feedback
    * Extend the component to also have a success state
    * Make it closable
    * Make it configurable for it to vanish after n seconds
    * Needs discussion: Show it on top of the related element, e.g. a form or the whole page that is affected - this will move the content a bit lower, but this is a common usage pattern for such notification elements, so I have no objections against it
    * Do not overlay it over the content, as content gets unreadable and also may get unusable because it overlays some interaction elements
    
## Acceptance criteria
- [ ] Shows a success message for form interactions that are successful
- [ ] Shows an error message for form interactions that fail
- [x] Shows an error message for every other interaction that fails
- [x] Shows an error for severe problems that occur without interaction
- [x] Message can be closed
- [x] Message can be configured to vanish after n seconds

**Comment by thisthat** [comment]
The team agreed to split into different ticket for:
 - creating the component
 - each screen will be replaced with the new notification component
