### ISSUE TITLE
lighthouse-service: Add error message for a failed evaluation

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#5142]
## User story

As a user, I would like to see an error message for a failed evaluation. Currently, I don't know why an evaluation failed: 

![image](https://user-images.githubusercontent.com/729071/131959856-6806cee9-57a2-4a98-8ab3-2d5dc25cfca4.png)

### Details

* The below function calculates the total score of an evaluation and checks it against the defined boundaries.  https://github.com/keptn/keptn/blob/d1555f9f6882742d3d26dd4157358e6769548fb7/lighthouse-service/event_handler/evaluate_sli_handler.go#L257
* Next to setting the `evaluationResult.Result`, and `evaluationResult.Status`, this function should also set a proper `evaluationResult.Message`, which is then part of the `evaluation.finished` event and displayed in the Bridge.

## Acceptance criteria: 

- [ ] An error message is shown for failed evaluation tasks:
![image](https://user-images.githubusercontent.com/729071/131960528-64986a30-f0a6-45c3-8cee-cc4b5130f509.png)

**Comment by masonwoodford** [comment]
Hello, could I work on this?

**Comment by thisthat** [comment]
Hi @masonwoodford! I am assigning the issue to you! Thank you for helping out 😄

**Comment by masonwoodford** [comment]
Sorry I am not that familiar with Docker I am having trouble getting testing my changes, feel free to unassign me!

**Comment by RealAnna** [comment]
Hi can I do it?
