### ISSUE TITLE
UX improvement to create/edit a subscription

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#5157]
## Use case

As a user, I would like to create a subscription:

![image](https://user-images.githubusercontent.com/729071/132185856-02baba30-3a6a-4ba6-8851-d588ff0d98a0.png)

While this is already possible, minor changes in the label name and order of text fields can help to improve the user experience. 

The goal is that the user can read the form like a sentence: *Webhook-service acts on `test` when `triggered` in stage `dev` for service `carts`.* If I would like to use this configuration for all projects, I - as a user - just have to select the check box.  I propose to adapt it in this way: 

![image](https://user-images.githubusercontent.com/729071/132185768-7ec8f2e6-edcf-4769-bd22-f6fa58c9f1f3.png)

Besides, it would then be aligned with the subscription overview that already follows the pattern. For the overview, I would propose the following minor changes (1-4): 

![image](https://user-images.githubusercontent.com/729071/132193646-6bd04f92-3658-474b-8a13-fd2884f920c9.png)
 

### Details 

- Don't change the size of the fields when the value has changed, e.g., when selecting `test` the field becomes smaller. (Stay with a fixed size) 

## Acceptance criteria

- [ ] The form to create a subscription has been adapted to allow reading it like a sentence.

**Comment by thisthat** [comment]
Closed in favor of #5270
