### ISSUE TITLE
Create structured log messages

### ISSUE THREAD

**Issue by danielkhan** [keptn/keptn#516]
Right now, the log messages are a JSON/text mix.
As an intermediate step towards a unified log and event service, we want to harmonize plain stdout log messages.

They should be in JSON only and contain all relevant information available at the time of writing, like the service, the stage, the app, etc.

Connected to that, we also need to define a unified JSON format - this can be the blueprint for the payload that a REST service will ingest later. FYI @jetzlstorfer @agrimmer

**Comment by agrimmer** [comment]
Duplicate to #535.
