### ISSUE TITLE
Several typos and inconsistencies in the messages after installing the Keptn CLI

### ISSUE THREAD

**Issue by arthurpitman** [keptn/keptn#5160]
**Environment**

* Client OS (e.g., Linux, macOS, Windows): Linux, Ubuntu 21.04
* Keptn Version (`keptn version`): Installing keptn 0.9.0
* Kubernetes Cloud Provider (e.g., GKE, AKS): GKE
* Kubernetes version (`kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.8-gke.2100", GitCommit:"4cd085fda961821985d176d25b67445c1efb6ba1", GitTreeState:"clean", BuildDate:"2021-07-16T09:22:57Z", GoVersion:"go1.15.13b5", Compiler:"gc", Platform:"linux/amd64"}
```

**Affected Component**

* [ ] Docs
* [x] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [ ] Bridge
* [ ] Approval
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**
Several typos and inconsistencies in the messages after installing the CLI. Current text:

> Keptn CLI installation completed successfully!
> You can check Keptn installation by running:
> 
> keptn --help
> 
> To install Keptn in your cluser, please follow the documentation https://keptn.sh/docs/ or execute 
> 
> keptn install
> 
> Learn more on how to use Keptn in our tutorials https://tutorials.keptn.sh/
> Welcome aboard!

Proposed changes:

> Keptn CLI installation completed successfully!
> You can check _**the**_ Keptn _**CLI**_ installation by running:
> 
> keptn --help
> 
> To install Keptn in your _**cluster**_, please follow the documentation _**at**_ https://keptn.sh/docs/ or _**execute:**_ 
> 
> keptn install
> 
> Learn more on how to use Keptn in our tutorials _**at**_ https://tutorials.keptn.sh/
> Welcome aboard!

**To Reproduce**

1. Run the Keptn CLI installer command: `curl -sL https://get.keptn.sh | KEPTN_VERSION=0.9.0 bash`

**Comment by bcdady** [comment]
Hi @arthurpitman et. al.,

I've gone ahead and submitted [PR 47](https://github.com/keptn/get.keptn.sh/pull/47) for this issue.

**Comment by arthurpitman** [comment]
@bcdady Thank you for this
