### ISSUE TITLE
Sending new artifact event fails with image not found

### ISSUE THREAD

**Issue by pahofmann** [keptn/keptn#520]
**Describe the bug**
When sending a _new artifact_ event the command fails with the following error:
> Error: Provided image not found: \<h1>Not Found\</h1>\<p>The requested URL was not found on this server.\</p>

**To Reproduce**
1. Onboard service
2. Send new artifact event

**Expected behavior**
The event should be sent and a pipeline should be started

**Environment**
AKS, keptn 0.3.0

**Additional context**
The image used is from a private docker repository (azure container registry). Not sure if that is already supported or if this should be a feature request for private registry support.    
Another option would be a webhook from the repository to keptn, haven't found any documentation on that tough.  

If there are any log files or debug info I can provide just let me know.

**Comment by johannes-b** [comment]
Hello Patrick, 
many thanks for the detailed bug report (feature request)! 
As of today, keptn does not support private docker repositories. We will address this features according to our priority list and issues in the backlog.

Can you use a public docker repository (hub.docker.com, quay.io) for your keptn use case or would it be possible to create a PR that implements this feature? 

(@grabnerandi)

**Comment by grabnerandi** [comment]
Hi. Wanted to share some additional information after talking with Johannes about this.
As Johannes said - the CLI currently validates if the passed artifact URL is valid and can be reached. In the moment we "assume" that a docker image reference that doesnt have a full qualified URL is hosted on dockerhub which means we create the dockerhub URL for that image reference and then do the URL check. The error message you currently get is basically the "image not found" from dockerhub.

As Johannes also said - we are going to address these issues in the CLI to support other docker registries as well. In the meantime though I want to propose an alternative approach. The new artifact event can also be sent via the keptn REST API. On the keptn slack one of our users has posted a PostMan sample that shows how to send the new artifact event via HTTP: https://keptn.slack.com/archives/CFH4VK9GT/p1561476278056200?thread_ts=1561388364.045700&cid=CFH4VK9GT

**Comment by dirkwall** [comment]
It's possible to use private registries now. Closing.
