### ISSUE TITLE
Quickstart: add resource requirements

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#5201]
The [quickstart guide](https://keptn.sh/docs/quickstart/) does not list the resource recommendation that is needed to run it. 
We should add some screenshots or text to specify the resources that are needed to run it.

Here is a screenshot of my local setup where it runs fine.

![image](https://user-images.githubusercontent.com/7677092/132637050-89843ffb-bbb5-4841-a225-19138879a9a3.png)

**Comment by thisthat** [comment]
The quickstart has the requirement listed here: https://keptn.sh/docs/quickstart/#prerequisites-for-k3d-based-keptn
