### ISSUE TITLE
`keptn set config AutomaticVersionCheck false` doesn't work

### ISSUE THREAD

**Issue by vadasambar** [keptn/keptn#5218]
**Environment**

* Client OS (e.g., Linux, macOS, Windows): Linux (I think)
* Keptn Version (`keptn version`): CLI is 0.8.7 and Server is 0.8.6
* Kubernetes Cloud Provider (e.g., GKE, AKS): No clue
* Kubernetes version (`kubectl version`): No clue

**Affected Component**

* [ ] Docs
* [x] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [ ] Bridge
* [ ] Approval
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**

Andreas Grabner
> Hi team. I have downloaded a newer CLI (0.8.7) than my connected keptn (0.8.6) - thats why I get this warning. I thought that the AutomaticVersionCheck flag helps me turn off this version check but I guess thats not the case as you can see below. Is there any other flag that allows me to suppress that version mismatch warning? `@Bernd Warmuth` `@Johannes Bräuer`
![image](https://user-images.githubusercontent.com/34534103/132718545-976b256c-261b-404d-928d-32c476aba957.png)

Bernd Warmuth 
> Nope, The message you see seems to be printed [here](https://github.com/keptn/keptn/blob/279c8114a3eae052a1362e94cbee3e021cee2baa/cli/cmd/root.go#L134) unconditionally, regardless of what you configure with `keptn set config`.  There is a [pull request](https://github.com/keptn/keptn/pull/5046) going on in this area of the CLI. Maybe we can also fix this as part this PR. `@Suraj Banakar`

From slack thread [here](https://keptn.slack.com/archives/CNRCGFU3U/p1629963363005200).

**To Reproduce**

Just run `keptn version` against a Keptn server where server version is not the same as the CLI version 
1. In my case, I built `keptn` [CLI from the source](https://github.com/keptn/keptn/tree/master/cli) using `go build -o keptn`
2. Ran `keptn version`
```
$ keptn version
* Warning: Your Keptn CLI version (develop) and Keptn cluster version (0.8.5) don't match. This can lead to problems. Please make sure to use the same versions.
``` 
3. Tried setting `AutomaticVersionCheck` to `false` to no avail
```
$ keptn set config AutomaticVersionCheck false
* Warning: Your Keptn CLI version (develop) and Keptn cluster version (0.8.5) don't match. This can lead to problems. Please make sure to use t
he same versions.
``` 
```
$ keptn version
* Warning: Your Keptn CLI version (develop) and Keptn cluster version (0.8.5) don't match. This can lead to problems. Please make sure to use t
he same versions.

Keptn CLI version: develop
Keptn cluster version: 0.8.5
...
```

**Expected behavior**

`keptn` should not show the warning when `AutomaticVersionCheck` is set to `false`.
**Current behavior**

`keptn` shows the warning (check above)
**Screenshots**

(check above)

**Comment by thisthat** [comment]
Thank you @vadasambar for pointing this out! Would you like to work on this issue?

**Comment by vadasambar** [comment]
@thisthat , I am working on this right now (I talked about this in yesterday's dev meeting). I don't have permission to assign this issue to myself.
