### ISSUE TITLE
(WIP) Bridge: Webhook - display previous event

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#5223]
## User Story
As a user, I would like to see a previous event of the selected type to facilitate the writing of the custom payload with event data.

mockup img (❓ TBD)

## Technical Details

The previous event shall be fetch from `GET /api/mongodb-datastore/event​/type​/{eventType}`. 
Filters for stage and service are applied to the `filter` query parameter. 
If no previous event is available, the Bridge shall show the message `No event of that type available`. 

## Open Questions

- [ ] how to show an event filtered by multiple stages and services

## DoD

- [ ] A previous event based on the subscription filters is shown
- [ ] Unit tests
- [ ] UI tests

**Comment by johannes-b** [comment]
@laneli can you please update this issue with the mockup we discussed on Monday. The `computer` icon should allow adding an event property to the custom payload.

**Comment by thisthat** [comment]
Closing in favor of #5265
