### ISSUE TITLE
Webhook integration

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#5225]
**Seamless integration of Webhook-based services:** [KEP 54](https://github.com/keptn/enhancement-proposals/pull/54)

Issues:
- https://github.com/keptn/keptn/issues/4736
- https://github.com/keptn/keptn/issues/4742
- https://github.com/keptn/keptn/issues/4743
- https://github.com/keptn/keptn/issues/4745
- https://github.com/keptn/keptn/issues/4749
- https://github.com/keptn/keptn/issues/4750
- https://github.com/keptn/keptn/issues/4751
- https://github.com/keptn/keptn/issues/5223
- https://github.com/keptn/keptn/issues/5260
- https://github.com/keptn/keptn/issues/5261
- https://github.com/keptn/keptn/issues/5265
- https://github.com/keptn/keptn/issues/5267
- https://github.com/keptn/keptn/issues/5264
- https://github.com/keptn/keptn/issues/5368
- https://github.com/keptn/keptn/issues/5733
- https://github.com/keptn/keptn/issues/5735

Research items:
- https://github.com/keptn/keptn/issues/5408

**Comment by oleg-nenashev** [comment]
Is it completed by now?
