### ISSUE TITLE
Bridge: Remove data mutation

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#5245]
## Action Item

Remove implicit data mutation in the data service.

### Technical details

The data in the Bridge is not passed via `next` to the subscribed components. Instead, data objects are changed on the fly. This leads to confusion where data was changed and makes it hard to debug and follow the data-flow because both patterns are used.
A better approach is to use **only** `subjects` in each component.
Furthermore, the list of `subjects` shall be split into smaller `subjects` that fit each view. 

## First step

With the refactoring effort we had in the last milestones, many components do not have this problem anymore. We should first list here what are the components that are still affected by it. Also, we shall list the info that is required by each component. 

## DoD
- [ ] Only the `subject` patterns is used
- [ ] Smaller `subjects` that fit the given view

**Comment by renepanzar** [comment]
Found some examples with this regex: `\.[a-zA-Z0-9]+ = ` and file mask: `*.component.ts` (incomplete!):

* `bridge/client/app/_components/ktb-sequence-list/ktb-sequence-list.component.ts:57`
* `bridge/client/app/_components/ktb-secrets-list/ktb-secrets-list.component.ts:31`
* `bridge/client/app/_components/ktb-sli-breakdown/ktb-sli-breakdown.component.ts:81,86,101,102,144`
* `bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.ts:257,297`
* `bridge/client/app/app-header/app-header.component.ts:70,71,142,149`

There are many more places where we store an instance in the component creating context within the component - 263 results. Should we also tackle those?
