### ISSUE TITLE
Bridge: Improve polling mechanism for sequences

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#5246]
## Action Item

Improve the polling mechanism for sequences. 

### Technical Details

Sequence Screen: Only requires the latest deployment of a service in a stage. This information is used for the approval-trace. There the currently deployed artifact is shown. 

## DoD 

- [ ] Improved polling logic

**Comment by agrimmer** [comment]
Which screen of the Bridge does the polling affect?
Why do we currently poll for open and finished sequences and why is it sufficient to only poll for open sequences?

**Comment by thisthat** [comment]
Duplicate of #5101
