### ISSUE TITLE
Image of containers are not set properly when doing a `keptn upgrade`

### ISSUE THREAD

**Issue by bacherfl** [keptn/keptn#5248]
Due to the recent changes made in https://github.com/keptn/keptn/pull/4984 , upgrading from Keptn <= 0.9.0 fails because the old value for the `repository` property of each service is not updated. Previously, this property included the docker registry, and looked like this for example: `docker.io/keptn/shipyard-controller`. In the referenced PR, this has been split up into the properties `registry` and `repository`, so the default values in the `values.yaml` now look like this:

```
    image:
      registry: docker.io
      repository: keptn/shipyard-controller
```

This works fine when a new installation of Keptn is created on a cluster. However, when upgrading a previous release, the resulting values then look like this:

```
    image:
      registry: docker.io
      repository: docker.io/keptn/shipyard-controller
```

Therefore, in this case, the resulting image will be set to `docker.io/docker.io/keptn/shipyard-controller` and will therefore fail.

**Comment by mowies** [comment]
Fixed in #5414
