### ISSUE TITLE
Bridge: Add event payload variables to webhook configuration

### ISSUE THREAD

**Issue by laneli** [keptn/keptn#5260]
## User Story
As I user I want to select an event payload variable for the custom payload from a predefined set, to not have to remember it, and I have not to search for the variables in an event payload.

## Mockup
![Add Subscription3](https://user-images.githubusercontent.com/2674029/133625071-3afd2e12-10b8-4ee6-8145-6f19134f59c5.png)

## Technical Details

The implementation depends on https://github.com/keptn/keptn/issues/5733
It should only fetch one previous event for a given type. 

### Acceptance criteria
* When the user clicks on the button in the text area header of the "Custom payload" field, a popup overlay opens.
* The overlay provides a list of variables from the event payload that can be selected.
    * This list provides the base properties as defined in the spec.
    * When the last event is available the properties are enhanced with these.
* When selected, the variable is inserted at the point where the cursor stands currently.
* The variable is inserted with the helm variable syntax: e.g., `{{ .varName }}`
* If the field loses focus, and the user clicks on the button, the field has to be at least focused again.
Nice to have: focus on the last point where the cursor was, or at the beginning if not focused yet.
* The list is expandable for nested properties. Clicking on such a nested property fills the whole path of the property.

❓ What list is provided when the user did not select a trigger yet? Or when there is no prev event?
 - The team decided to provide a default event:
 ```
{
  id, 
  shkeptncontext, 
  type, 
  data: {
    project,
    service,
    stage
  },
  time
}
```

❓ What list is provided when the user selects a wildcard?
  - The intersection of the events: look for an algo out-of-the-box to do this. 

## DoD
- [ ] Open points are discussed within the Bridge team and the final decision is documented here as a comment
- [ ] All fields where secret can be defined, they can also be enriched with variables
- [ ] UI Tests
- [ ] Unit tests 

## Dependencies

- https://github.com/keptn/keptn/issues/5733

**Comment by johannes-b** [comment]
Please keep in mind that there are advanced capabilities around Go templating documented here: https://github.com/keptn/keptn.github.io/pull/961
