### ISSUE TITLE
Bridge: Restructuring of Bridge settings for project

### ISSUE THREAD

**Issue by laneli** [keptn/keptn#5268]
### Description
To work more towards unifying all settings into one place following changes should be made to get closer to that goal:
![image](https://user-images.githubusercontent.com/2674029/133633947-ce1d2086-ac52-4aaf-9def-0a19448e1200.png)

## Acceptance criteria
* Add subnav sections to bring more structure to the menu (see mockup)
* Move uniform from main nav to settings
    * The already split subpages also are reflected here in the section "Uniform": Integration and Secret
    * Remove uniform nav entry from main nav
* Move "Integration" from main nav to settings under section "Uniform"
    *  As this point only contains common use cases, rename it to "Common use cases"
    * Remove integrations nav entry from main nav
* Move "Settings" nav item directly below the other nav entries to make it more visible

### DoD
- [ ] Refactor the settings 
- [ ] Adapt UI tests

**Comment by Kavindu-Dodan** [comment]
Query with regards to the mock, does this mean webhook integration will go under  **Project**  ->  **Uniform** -> **Integration**  ?

Reason, I tried the webhook integration with 0.10.0 pre-release. As a first time user, I was confused how to visit the webhook configuration page (project -> uniform -> search & click webhook-service -> Click Add subscription).
