### ISSUE TITLE
Move funcitonality of CredentialManager to go-utils

### ISSUE THREAD

**Issue by warber** [keptn/keptn#5273]
## Description

> As a Keptn Service running on the control plane,
> I want to be able to easily determine the public endpoints of the public Keptn API as well as the Keptn Bridge.

The `CredentialManager` used in the Keptn CLI is used to determine endpoints of the Keptn API and bridge in order to present that information to the user. Ther might be other control plane services that need to know the, api endpoint and token as well.

Refactor the `CredenatialManager` and move it into `go-utils`. Functionality specific to the CLI should remain there.
 
## Technical details

The CLI requires to be refactored before the `CredentialManager` could be moved

## DoD

- [ ] `CredentialManager`  moved into `go-utils`

**Comment by thisthat** [comment]
This information is specific for the CLI. We don't need this refactoring.
