### ISSUE TITLE
Documentation for ingress option in helm chart

### ISSUE THREAD

**Issue by mowies** [keptn/keptn#5297]
An option to add an ingress to the `api-gateway-nginx` service was implemented [here](https://github.com/keptn/keptn/pull/5293). This new option should be added to the documentation to keep confusion to a minimum.

References:
Related issue: #5066
Related PR: #5293

**Comment by bradmccoydev** [comment]
Hi, Please assign me to this issue

**Comment by mowies** [comment]
Done ✅

**Comment by bradmccoydev** [comment]
Thanks @mowies and please guide me to the repo/place to update documentation, thanks

**Comment by mowies** [comment]
I think [this](https://github.com/keptn/keptn.github.io/blob/master/content/docs/0.9.x/operate/install/index.md#option-3-expose-keptn-via-an-ingress) would be the right spot, maybe @thisthat can correct me if I'm wrong :)

**Comment by thisthat** [comment]
Yes, that's the right place! It will then be visible in our website at this page: https://keptn.sh/docs/0.9.x/operate/install/#option-3-expose-keptn-via-an-ingress

**Comment by bradmccoydev** [comment]
Hey @mowies and @thisthat technically the documentation should be in the advanced section as that is where the helm chart documentation is right? https://keptn.sh/docs/0.9.x/operate/advanced_install_options/

**Comment by mowies** [comment]
Yes that would also be a good fit. Would be great if you could add the new helm values there and then create a new example following the structure of the already existing ones.

**Comment by bradmccoydev** [comment]
Also Before merging we need to make sure the helm chart is available with those options. and please note it was done in the latest folder 0.9.x

**Comment by johannes-b** [comment]
@bradmccoydev thanks for working on this issue. I will close it.
