### ISSUE TITLE
High Availability

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#5302]
## Research

- https://github.com/keptn/keptn/issues/6686
- https://github.com/keptn/keptn/issues/6690
- https://github.com/keptn/keptn/issues/4182
- https://github.com/keptn/keptn/issues/5307
- https://github.com/keptn/keptn/issues/4689

## Core

- https://github.com/keptn/keptn/issues/6343
- https://github.com/keptn/keptn/issues/6308
- https://github.com/keptn/keptn/issues/6306
- https://github.com/keptn/keptn/issues/4519

## Bridge

-

## Known pain problems

- https://github.com/keptn/keptn/issues/4066

**Comment by utibeabasi6** [comment]
hi, i would like to work on this can you point me to some resources to help me get started

**Comment by thisthat** [comment]
Hey @utibeabasi6, for this ticket the only open point is the Bridge. It would be interesting to test if you can run multiple replicas of the Bridge ([K8s docs on Deployments](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment)) and verify if it works with OAuth enabled: https://keptn.sh/docs/1.0.x/bridge/oauth/#enable-disable-authentication

**Comment by utibeabasi6** [comment]
Ah ok
I will test that and get back to you
