### ISSUE TITLE
Implement WorkflowEngine

### ISSUE THREAD

**Issue by dirkwall** [keptn/keptn#531]
WorkflowEngine handles the keptn default workflows and knows about the transition between states. Workflow definitions are in code for now.
Implement the engine so it receives generic DONE events and dispatches START-* events.

For more details on the workflows see https://drive.google.com/open?id=1kmunoBGAFEADFjoksbfzYVzdlJ60326h

**Comment by johannes-b** [comment]
Duplicate to #508
