### ISSUE TITLE
Implement generic DONE event in external keptn services

### ISSUE THREAD

**Issue by dirkwall** [keptn/keptn#532]
Going forward, we don't want to have specific *-DONE events, but rather one generic DONE event that is dispatched by keptn services when they've finished their task. That leaves the workflow transition and control of the workflow to the WorkflowEngine, and that's how we want it.

- [ ] Implementation of generic DONE in keptn services

**Comment by agrimmer** [comment]
Generic DONE events are hard to map to corresponding triggered events and, hence, we will use a unique call-back ID in done/finished events.
