### ISSUE TITLE
Specification of START-* events and DONE event

### ISSUE THREAD

**Issue by dirkwall** [keptn/keptn#533]
Specify START-* events that clearly state when a new phase is started. START-* events are only dispatched by the WorkflowEngine.

Specify generic DONE event that clearly state when a phase is done (completed, finished). DONE events are sent by external keptn services.

**Comment by johannes-b** [comment]
*Documentation first*
- [ ] Update of keptn/specification to specify the new event types (according to current status)
- [ ] Update of Postman collection to include the new event types
- [ ] Design doc including sequence diagram

**Comment by dirkwall** [comment]
The specification needs to be done in the keptn/spec repository.

**Comment by johannes-b** [comment]
This issue is not relevant anymore. I closed it.
