### ISSUE TITLE
Implement MonoRepo battle plan

### ISSUE THREAD

**Issue by dirkwall** [keptn/keptn#537]

**Comment by johannes-b** [comment]
- [ ] Moving repos from keptn to keptn-service and pitometer-contrib
   - double-check the docs for references
   - inform contributors about moved repositories
---
- [ ] Merging repos from keptn to keptn/keptn (monorepo) for each repository that will be merged: 
  - see checklist: Before merging repos into monorepo
  - copy develop branch of repo in ./[folder]
  - clean-up of ./[folder] (remove obsolete files)
  - integrate component into Travis CI Build (selective test, build, docker push)
  - mark (✝️) as deprecated and archive them
