### ISSUE TITLE
Pitometer Score is not available in log nor dynatrace event

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#540]
**Describe the bug**
A key capability of Pitometer is to come up with a total score, e.g: 50 out of 100 potential points. Right now this information is not available anywhere. Neither in the keptns bridge nor the Dynatrace Event.
In order to know WHY an artifact was promoted or not promoted I need to at least know the total score of Pitometer. I want to see it in both the log and as a property in the Dynatrace Info Event

**To Reproduce**
Run a build that either fails or gets promoted. Try to find the Pitometer score! 

**Expected behavior**
See the score

**Screenshots**
![image](https://user-images.githubusercontent.com/675886/61512648-e5924f80-a9fa-11e9-8874-d5f759c70d12.png)

![image](https://user-images.githubusercontent.com/675886/61512665-f04ce480-a9fa-11e9-9550-5ce05c26977a.png)

**Comment by bacherfl** [comment]
The latest version of the bridge in Keptn 0.5.0 now shows the complete output of pitometer
