### ISSUE TITLE
Test Finished Event (with status=fail) if JMeter Tests fail

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#542]
**Describe the bug**
Seems that when JMeter tests fail no End-Test Event is sent becuase JMeter directly sends an Evaluation Done event. This means that I never see a Test Finished event in Dynatrace
What I expect is that I always see Test STart & Finished and Finished MUST ALSO INCLUDE the test status: pass or fail

**To Reproduce**
Run a build where JMeter tests fail e.g: with a high failure rate

**Expected behavior**
Always get start/stop test events in dynatrace including final test result

**Screenshots**
![image](https://user-images.githubusercontent.com/675886/61518702-84727800-aa0a-11e9-8559-f3dd569e5e8b.png)

**Environment**
keptn develop / July 19

**Comment by grabnerandi** [comment]
The root cause of this is becuase JMeter doesnt send a test finished event but directly a evaluation done.
the CORRECT workflow would be
* Jmeter sends TEst Finished event with status fail
* Pitomter still does the evaluation -> for additonal diagnositcs information -> then sends an evaluation done event with status fail because JMEter result was already fail!

**Comment by christian-kreuzberger-dtx** [comment]
This has been discussed and approved in [KEP 0002](https://github.com/keptn/enhancement-proposals/pull/2).
