### ISSUE TITLE
Core: Introduce a throttled logger in Shipyard-Controller

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#5442]
## Action Item

The backend should be using a throttled logger in the shipyard controller to block spamming situations in case of continuous failure. See #8570. 
The throttling should occur by `shkeptncontext` or `project` based on what is available. Furthermore, logs lines should always provide info about the project and/or shkeptncontext.

## Technical details

The logging should be throttled based on a logical unit group of a module, e.g. HTTP handling and core logic should be throttled individually. Configuration parameters, such as allowed burst or on/off, should be configurable via helm chart values. 

## Acceptance Criteria
- [ ] Identify places in the shipyard controller that could lead to continuous log messages due to the same failure and throttle these logs.
- [ ] Remove log lines that are not necessary
- [ ] All core-services use a formatted output
- [ ] Whenever possible, all log lines should provide info about project/shkeptncontext/stage/service via `WithFields(log.Fields{})`

## DoD
- [ ] Acceptance criteria are implemented
- [ ] Unit tests

## Resources 

- [ ] https://github.com/sirupsen/logrus/blob/master/example_basic_test.go

**Comment by warber** [comment]
Question: Are we sure we need to introduce this on the logging level?
IMO, it would make much more sense to rate limit our API endpoints.

**Comment by thisthat** [comment]
Thank you for your question @warber. The biggest problem I noticed is on the shipyard controller that was printing the same log lines over and over. It was crashing because of some wrong status of the database, which was not triggered via an API endpoint. 
Furthermore, having a rate limit on the API would hinder the dev experience for integrations.
