### ISSUE TITLE
Bridge: Disable Sequence abort button for a sequence which has not started

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#5471]
**Environment**

* Client OS (e.g., Linux, macOS, Windows): any
* Keptn Version (`keptn version`): 0.9.2
* Kubernetes Cloud Provider (e.g., GKE, AKS): any
* Kubernetes version (`kubectl version`): any

**Affected Component**
* [ ] Docs
* [ ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [x] Bridge
* [ ] Approval
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**
The Abort button for sequences is enabled although the shipyard-controller does not allow to abort sequences that have not been started.

**To Reproduce**
- Have multiple queued sequences
- Try to abort a sequence, which has not started yet.

**Expected behavior**
Pause and abort button should not be enabled for sequences which have not yet been started.

<img width="867" alt="Screen Shot 2021-10-04 at 13 06 43" src="https://user-images.githubusercontent.com/10980861/135840962-d8ddf90f-93e3-4ea1-b5cc-35f7b8c22019.png">

**Comment by thisthat** [comment]
Closing in favor of #5472
