### ISSUE TITLE
Bridge: Make use of new evaluation.finished payload

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#5498]
## Action Item

Adapt the Bridge to use the `comparedValue` property of the `evaluation.finished` event.

## Technical Details

In #5496, the `evaluation.finished` event contains the values used for comparison inside the `comparedValue` property. The bridge should prefer this field. If missing, it should fall back to use `comparedEvents`.

## DoD

- [x] The Bridge should prefer the  `comparedValue` property to show data in the UI, if present
- [x] Unit tests

## Dependencies

- https://github.com/keptn/keptn/issues/5496

**Comment by johannes-b** [comment]
@Kirdock and I agreed on minor changes in the UI when working on this issue. These are the three changes to consider: 

![image](https://user-images.githubusercontent.com/729071/144567793-5f537b4d-9229-4f4e-b886-253c40319bae.png)


Additional notes:
* Although the "compared with" value will be provided by the backend in the future, for old events it must be calculated. Hence add a comment to the code, which indicates the Keptn version that does not provide the "compared with" value. (i.e. <= Keptn 0.12)
