### ISSUE TITLE
Jenkins Image has outdated config files for sockshop k8s-deploy-staging

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#55]
**Describe the bug**
The jenkins image that is currently used is dynatraceacm/keptn-jenkins:0.2. This image comes with pre-deployed config directories for all sockshop pipelines. At least for one of the pipelines - k8s-deploy-staging - the job config file references the parameter APP_NAME instead of SERVICE_NAME. This results in a failed pipeline run with the error: null.yaml. Reason is that SERVICE_NAME is passed but Jenkins expects APP_NAME. This only happens the first time we deploy any service into staging because Jenkins uses the cached file instead of the jenkinsfile from our github repo.

Either create a known issue or update the Jenkins Image with an up2date config for all sockshop pipelines

**Comment by jetzlstorfer** [comment]
fixed in version 0.1.1
