### ISSUE TITLE
shipyard-controller terminates sequence with a timeout but task is executed successfully 

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#5501]
**Environment**

* Client OS (e.g., Linux, macOS, Windows): any
* Keptn Version (`keptn version`): 0.9.2
* Kubernetes Cloud Provider (e.g., GKE, AKS): any
* Kubernetes version (`kubectl version`): any

**Affected Component**

* [ ] Docs
* [ ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [ ] Bridge
* [ ] Approval
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter
* [x] shipyard-controller

**Describe the bug**
The shipyard-controller terminates my sequence with `sequence timed out while waiting for ...` although the task is executed successfully. See screenshot:
![image (7)](https://user-images.githubusercontent.com/10980861/136019747-1a891d6f-fcb3-4652-9480-1c0a98acfe0c.png)

Furthermore, in my shipard.yaml I have configured 
```
            - name: "evaluation"
              triggeredAfter: "10m"
```

It seems that the shipyard-controller does not add the triggeredAfter time to the timeout.

**Expected behavior**
My evaluation is not aborted when using a triggeredAfter with 10 minutes.

**Comment by bacherfl** [comment]
So far this behavior could not be reproduced with the current state on the master branch. Maybe there is some anomaly in the affected environment - this needs further investigation, but I suggest to move the issue to the 0.11.0 milestone

**Comment by thisthat** [comment]
@bacherfl thank you for your investigation. I concur and I am moving this issue to 0.11.0
