### ISSUE TITLE
Introduce waiting status in /sequence endpoint

### ISSUE THREAD

**Issue by ermin-muratovic** [keptn/keptn#5526]
The `/sequence` endpoint returns a `state` property and each stage has also a `state` property. Currently the overall state might be `triggered`, `paused` or `finished`. However, the stage state is either `triggered` or `finished`, see example below.
The `state` value should also return `started` for started stages. 

```
{
  "name": "delivery",
  "service": "carts",
  "project": "sockshop",
  "time": "2021-10-06T09:28:50.796Z",
  "shkeptncontext": "ae02c298-e6ab-4453-87c6-492eea4fdca9",
  "state": "paused",
  "stages": [
    {
      "name": "dev",
      "image": "docker.io/keptnexamples/carts:0.12.1",
      "state": "triggered",
      "latestEvent": {
        "type": "sh.keptn.event.test.triggered",
        "id": "ba87752d-3a99-4388-84b0-08f988322a9a",
        "time": "2021-10-06T09:30:19.744Z"
      }
    }
  ]
}'
```

If the user paused a sequence, I would expect to see the state `paused` instead of the state `triggered`.
If the sequence is waiting for another sequence to be finished, I would expect to see the state `waiting` instead of the state `triggered`.

This is a breaking change. 

## DoD

- [ ] Unit tests
- [ ] Integration tests

**Comment by thisthat** [comment]
We should define the list of possible states before we can tackle this issue

**Comment by odubajDT** [comment]
From discussion we know that states of sequences can have these values: 

- triggered
- started
- finished
- paused
- timedOut
- aborted

Stages have also the same states as sequences + succeeded

It should be enough to introduce a new state `waiting` to cover when the sequence is waiting for a condition (f. e. another sequence). 

#Use Case
When a sequence (in state `started`) needs to wait, it changes its state to `waiting`. The same happens to each stage with state `started`
