### ISSUE TITLE
Evaluation score is not shown if there is more than one finished event for it

### ISSUE THREAD

**Issue by Kirdock** [keptn/keptn#5527]
The score is missing if there is more than one finished event inside the evaluation.
![image](https://user-images.githubusercontent.com/11599148/136178644-0e7f18d5-c092-47e7-8e7f-6d6f090fdb32.png)
(if you expand the evaluation there is another started and finished event)

The score should be taken from either the latest finished event or the latest finished event of the lighthouse service instead of the first finished event.

**Comment by laneli** [comment]
[https://app.zenhub.com/files/166831098/fef9ccf8-3c57-449d-8df0-642537838b33/download](https://app.zenhub.com/files/166831098/fef9ccf8-3c57-449d-8df0-642537838b33/download)
