### ISSUE TITLE
Keptn CLI: Implement updateDomain.sh as CLI command

### ISSUE THREAD

**Issue by dirkwall** [keptn/keptn#553]
https://github.com/keptn/installer/blob/master/scripts/common/updateDomain.sh

Implement the actions done in the file above as a CLI command, that allows updating the domain, and, if desired, authenticates the CLI after updating the domain, e.g. (please use better wording)

```
keptn update domain testdomain.com --authenticate-cli true
```

**Comment by agrimmer** [comment]
Missing: Update docu.
