### ISSUE TITLE
Validation of inbound events

### ISSUE THREAD

**Issue by warber** [keptn/keptn#5544]
### User Story

> As a user,
> When I post an event to Keptn
> Then I want to be clear about whether the event payload is valid or not

#### Example:
User wants to post a `task.started` event using the `POST /event` endpoint of Keptn but uses the wrong event type (e.g. `sh.keptn.event.dev.verification.started` instead of `sh.keptn.event.verification.started`) 

### Acceptance Criteria
 - [x] check for missing mandatory fields (e.g., trigger id based on the event type, project, stage, service)
 - [x] type must have correct syntax and started events must not have a stage
 - [x] time format is correct
 - [x] if it is a well-defined event (from our spec), validate that it contains the mandatory fields
 - [x] `result` and `status` have a correct value set
 - [x] size of the [CloudEvent is respected](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#size-limits) (check Distributor for a reference implementation)

## DoD 
- [x] The user posts events that are **invalid** for the type of action he/she wants to trigger and gets a reason why in the logs.
- [ ] updated/new http endpoints are well documented in swagger doc
- [ ] integration test verifies that invalid events are marked as warnings by Keptn

**Comment by johannes-b** [comment]
In Slack, a discussion was ongoing, on whether `project`, `service`, and `stage` are needed when the `triggeredid` is available. Actually, the triggeredid is sufficient, because the other properties can be derived. It would help the users a lot if we just make the `triggeredid` mandatory.

**Comment by warber** [comment]
related issue https://github.com/keptn/keptn/issues/7309
