### ISSUE TITLE
Aborting a pending deployment sequence in helm-service leads to failure until the aborted sequence finally finishes

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#5557]
This is with Keptn 0.9.2.

# Current behaviour

I am deploying podtato-head and accidentally tried to deploy an image with a tag that does not exist.
I noticed my mistake, and aborted the delivery sequence:
![image](https://user-images.githubusercontent.com/56065213/136383019-ea9e4ddf-f70c-4120-9281-2ae272f012c8.png)

However, when I triggered the next delivery sequence, I ended up getting the following error message:
```
Error when installing/upgrading chart pod-tato-head-dev-helloservice in namespace pod-tato-head-dev: another operation (install/upgrade/rollback) is in progress
```

This is to be expected, as helm-service is still working (or in other words, helm-service has not finished and sent out a deployment.finished event).

Eventually helm-service has finished in the aborted sequence, and I can deploy again.

# Expected behaviour

Either helm-service or shipyard-controller need to react on the aborted sequence.

* When aborting, helm-service could abort the deployment process using `helm` cli and send out a `deployment.finished` event
* When aborting, shipyard-controller could wait until helm-service sends the `deployment.finished` CloudEvent (or times out) before starting the next sequence

**Comment by thisthat** [comment]
This ticket will be solved by adding this limitation to our documentation: `Aborting a sequence does not aborts the running task`

**Comment by bacherfl** [comment]
It seems like this behavior was already documented: https://keptn.sh/docs/0.10.x/reference/bridge/manage_sequences/#aborting-sequences
