### ISSUE TITLE
Pitometer-service handle the secrets and test id for the pitometer datasource

### ISSUE THREAD

**Issue by NeotysLab** [keptn/keptn#556]
**Is your feature request related to a problem? Please describe.**
The Keptn NeoLoad service is storing the settings of the service in a secrets named NeoLoad.
This secrets store :
- NL_WEB_HOST
- NL_API_HOST
- NL_API_TOKEN
- NL_WEB_ZONEID
- NL_UPLOAD_HOST

the pitometer neoload data source needs to have the following configuration:
new NeoLoadDatasource({
        neoloadapirul: "https://neoload-api.saas.neotys.com",
        neoloadwuploadurl:"https://neoload-api.saas.neotys.com",
        apiToken: "token"
    })

After each test the neoload service is adding the testid in the cloud event data.
the testid is also required to evaluate the tests.
.run(require("./perfspec.demo-live.json"), {
        context: "production-run-12345",
        neoloadContext: {
            testid:"f2472490-34bd-45c4-a1e0-f426bf006daf"
        },
        timeStart: +start / 1000,
        timeEnd: +end / 1000,
    })
    .then(results => console.log(JSON.stringify(results)))
    .catch(err => console.error(err));

**Describe the solution you'd like**
The pitometer should be able to get the secrets of external services to pass it to the configuration of the pitometer data source.
All the custom properties added in the payload should also pass to the the data source.

**Comment by jetzlstorfer** [comment]
Hi Henrik, 
thanks for your feature request. We are working on improving the pitometer service and will consider your feature request in our efforts! 
Am I assuming correctly that the secret is stored in the keptn namespace?

**Comment by NeotysLab** [comment]
Hi,

Yes all the secrets are stored in the namespace Keptn.

If we required we could plan a short web meeting from next week to 
discuss on this feature request.

Best regards,

<neotys.com>
*Henrik Rexed*
Partner Solution Evangelist
Phone: +33 442 180 834
Cell: +33 632 813 346
skype: rexedrexed
henrik.rexed@neotys.com <mailto:henrik.rexed@neotys.com>
http://www.neotys.com
<https://www.neotys.com/performance-advisory-council>
Le 06/08/2019 à 09:15, Jürgen Etzlstorfer a écrit :

**Comment by jetzlstorfer** [comment]
Hi Henrik,
we are currently redesigning some parts of the cloud events to make it easier for all internal and external services. We'll let you know once we have a design doc to share and we can start a discussion on this.

**Comment by NeotysLab** [comment]
HI,

Let me know i could contribute to the specification.

Best regards,

<neotys.com>
*Henrik Rexed*
Partner Solution Evangelist
Phone: +33 442 180 834
Cell: +33 632 813 346
skype: rexedrexed
henrik.rexed@neotys.com <mailto:henrik.rexed@neotys.com>
http://www.neotys.com
<https://www.neotys.com/performance-advisory-council>
Le 20/08/2019 à 09:10, Jürgen Etzlstorfer a écrit :

**Comment by dirkwall** [comment]
@NeotysLab , this issue is obsolete as we move from Pitometer to the Lighthouse-service. We'll support the propagation of custom data from events to SLI providers (#1147).
Secrets and other configuration data need to be part of the Neotys SLI Provider. Let's get on a call to discuss details at your earliest convenience.
