### ISSUE TITLE
api/uniform/registration is POST, should be GET request

### ISSUE THREAD

**Issue by carpe-github** [keptn/keptn#5560]
When I load Uniform page in UI I see "api/uniform/registration" is a POST request and the response is the data of the page which is loaded.
![image](https://user-images.githubusercontent.com/63784298/136391960-bf41473e-ffe6-4dc4-9856-323151ec027d.png)

a comment from the developer in scope of this issue:
`we would need to move that logic to the bridge-server, because with GET we can't send any body.`

**Comment by thisthat** [comment]
The list of timestamps can potentially be huge and thus, the team preferred to use a POST API.
This API is also not public facing.
