### ISSUE TITLE
Add short description that only secrets from `keptn-webhook-service` are shown in secret selection

### ISSUE THREAD

**Issue by laneli** [keptn/keptn#5576]
Add a short description e.g. on top of the page, that only secrets from scope `keptn-webhook-service` can be used to configure the webhook service.
This would clarify why configured secrets are not appearing in the selection list.

## DoD
- [ ] Bridge should provide a hint about this

**Comment by robertjahn** [comment]
See comment from this issue.  https://github.com/keptn/keptn/issues/5832#issuecomment-969038380
