### ISSUE TITLE
Errors in Helm chart after import via keptn onboard service

### ISSUE THREAD

**Issue by checkelmann** [keptn/keptn#559]
When onboarding a service via keptn cli the values yaml is beeing altered with the service name as top node, which is breaking all references in the nested template files.

values.yaml before import:
![image](https://user-images.githubusercontent.com/584370/61769476-b01aa700-adea-11e9-9ca2-38da7514febd.png)

values.yaml after import:
![image](https://user-images.githubusercontent.com/584370/61769512-cd4f7580-adea-11e9-9a8f-7a3d34c9ba46.png)

Example deployment.yaml
![image](https://user-images.githubusercontent.com/584370/61769575-05ef4f00-adeb-11e9-8117-19b84dad8472.png)

As you can see the Values references in the helm templates were not altered in the onboarding process with the new structure. We needed to adjust it manually e.g.

`.Values.image.repository ` to `.Values.goUrl.image.repository `

**Comment by jetzlstorfer** [comment]
Hi Christian,
thanks for opening an issue.
In the current implementation of keptn this is a limitation and we are aware of it. This issue is also related to #558 and we will address both issues with a rearchitecture of the keptn internals.

**Comment by dirkwall** [comment]
@checkelmann, @johannes-b is this issue still relevant?

**Comment by johannes-b** [comment]
This issue can be closed.

Due to the changes and enhancements in the helm-service (which takes care of the Helm Charts) the service doesn't modify a user's values.yaml file anymore.
