### ISSUE TITLE
helm-service 0.9.2 crashes with OOM

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#5595]
I just installed helm-service on an existing Keptn 0.9.2 (also 0.10.0-next.0) installation using
```
helm install helm-service https://github.com/keptn/keptn/releases/download/0.9.2/helm-service-0.9.2.tgz -n keptn
```

And two multi-stage blue-green deliveries (dev -> staging -> prod-a, prod-b)
![image](https://user-images.githubusercontent.com/56065213/136746471-87f95900-5927-49d6-a65e-953c535e8dc6.png)

**edit: With Keptn 0.10.0-next.0 it was harder, but I managed to do it with three parallel stages: prod-a, prod-b, prod-c**

helm-service crashed after two triggered deliveries with an OOM:

![image](https://user-images.githubusercontent.com/56065213/136555659-d025d44d-097b-48ec-9ad8-17ce14d9c560.png)
![image](https://user-images.githubusercontent.com/56065213/136809058-24335638-af2b-4290-adc8-c0039d3ab9f8.png)

# How to reproduce

1. Install Keptn 0.9.2 with continuous-delivery
2. Install istio
3. Create a project with the following multi-stage shipyard (part of our CD integration tests): https://github.com/keptn/keptn/blob/b3cd48f5d40fc37145dccae7b279517ed6e07393/test/go-tests/continuous_delivery_test.go#L10-L119
4. Onboard a service (e.g., carts, carts-db, whatever...)
5. Trigger delivery of a service (e.g., v1)
6. Shortly after that (within one to three minutes), trigger another delivery (e.g., v2)

# Current behaviour

It seems that the problem occurs because of the multi-stage parallel delivery in prod-a and prod-b. Once the canary deployment went through in prod-a and prod-b, we trigger another delivery.

At this point, helm-service is running the following tasks concurrently:
* release v1 in prod-a
* release v1 in prod-b
* 0.10.0-next.0: release v1 in prod-c
* deploy v2 direct in dev

In the end, helm-service crashes with an OOM, loses the current state of deployment, and I have two delivery sequences that are hanging:
![image](https://user-images.githubusercontent.com/56065213/136746731-3fb53e99-bebd-4880-97f3-778255fbfc35.png)

# Expected behaviour

helm-service must not crash with an OOM and delivery sequences need to go through with a finished event.

# Useful Tools

- Dynatrace Monitoring
- `watch -n1 "kubectl -n keptn top pods --containers=true | grep helm`
- `kubectl get event -owide` (without any namespace) and look for OOM

**Comment by bacherfl** [comment]
Just tried this out with Keptn v0.10.0 - during my tests I set up my project to deploy to 3 different stages (prod-a,prod-b,prod-c) after first deploying to dev and staging. After triggering the first delivery sequence I waited ~1min before I triggered another two instances of that sequence - meaning that eventually there were 5 deployments happening by the same time. The resulting memory consumption graph of the helm service looks as follows:

![Screenshot 2021-11-08 at 10.57.20.png](https://images.zenhubusercontent.com/5d08db5832d94d3393125f64/f5448b36-7769-450c-bc86-3ef8fb525ce2)

**Comment by bacherfl** [comment]
Closing this issue now since the current resource limit seem to be dimensioned reasonably high to handle a number of parallel helm deployments at the same time - of course, this might need to be configured individually if there is a need for being capable of a higher number of parallel deployments, but this can be done by applying the correct values in the helm-service's helm chart
