### ISSUE TITLE
Keptn CLI: Query keptn connection information

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#561]
**Is your feature request related to a problem? Please describe.**
As a user I want to query to which keptn I am currently connected/authenticated to

**Describe the solution you'd like**
I would like to have a; keptn status or keptn info

**Additional context**
Right now its not possible to determine to which keptn control API endpoint the CLI is connected to

**Comment by christian-kreuzberger-dtx** [comment]
Would the information provided in `~/.keptn/.keptn-creds` (clustername, clusterzone) plus the information from `~/.keptn/.keptn` (which contains the cluster URL) be enough?

We could integrate that into a ``keptn status`` CLI command showing the currently connected keptn installation as well as the status of the keptn installation (see #936 for details).

**Comment by dirkwall** [comment]
Fixed with #215
