### ISSUE TITLE
Keptn CLI: Provide --insecure-skip-tls-verify flag

### ISSUE THREAD

**Issue by nnganesha** [keptn/keptn#567]
**Describe the bug**

keptn install --platform=gke fails with the below error. Is it related to the number of nodes or memory?
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x131cd70]

**Comment by dirkwall** [comment]
Could you please provide more information, so we can investigate?
- What OS are you running? (e.g. post output of `uname -a`)
- Did you download a binary version of the CLI or did you compile it yourself?
- Which version of the CLI are you using? Can you provide the link where you've downloaded you're binary?
- Could you please append the stacktrace if available?

**Comment by nnganesha** [comment]
Hello Dirk,

Thanks a lot for the quick reply. Hope you are doing good… Please find the details below.

•	What OS are you running? (e.g. post output of uname -a)
Linux cmponprem-Virtual-Machine 4.18.0-15-generic #16~18.04.1-Ubuntu SMP Thu Feb 7 14:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
•	Did you download a binary version of the CLI or did you compile it yourself?
I downloaded the binary version of the CLI directly from GitHub (https://github.com/keptn/keptn/releases/download/0.4.0/0.4.0_keptn-linux.tar) 
•	Which version of the CLI are you using? Can you provide the link where you've downloaded you're binary?
As mentioned above.
•	Could you please append the stacktrace if available?
Sure, please find below.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x131cd70]

goroutine 1 [running]:
github.com/keptn/keptn/cli/utils.HasTokenRepoScope(0xc0005b4870, 0x28, 0xe, 0x1739359, 0x1c)
        /Users/travis/gopath/src/github.com/keptn/keptn/cli/utils/githubSettingChecker.go:56 +0xf0
github.com/keptn/keptn/cli/cmd.getInstallCredentials(0xc0002322a0, 0xc0002322a0, 0xc00015dbb8)
        /Users/travis/gopath/src/github.com/keptn/keptn/cli/cmd/install.go:357 +0x1c7
github.com/keptn/keptn/cli/cmd.glob..func6(0x279a360, 0xc0004a2c10, 0x0, 0x1, 0x0, 0x0)
        /Users/travis/gopath/src/github.com/keptn/keptn/cli/cmd/install.go:202 +0x8b
github.com/keptn/keptn/cli/vendor/github.com/spf13/cobra.(*Command).execute(0x279a360, 0xc0004a2bf0, 0x1, 0x1, 0x279a360, 0xc0004a2bf0)
        /Users/travis/gopath/src/github.com/keptn/keptn/cli/vendor/github.com/spf13/cobra/command.go:826 +0x465
github.com/keptn/keptn/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x279a0e0, 0x0, 0x0, 0xc00000e028)
        /Users/travis/gopath/src/github.com/keptn/keptn/cli/vendor/github.com/spf13/cobra/command.go:914 +0x2fc
github.com/keptn/keptn/cli/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /Users/travis/gopath/src/github.com/keptn/keptn/cli/vendor/github.com/spf13/cobra/command.go:864
github.com/keptn/keptn/cli/cmd.Execute()
        /Users/travis/gopath/src/github.com/keptn/keptn/cli/cmd/root.go:62 +0x2e
main.main()
        /Users/travis/gopath/src/github.com/keptn/keptn/cli/main.go:21 +0x45

Regards,
Ganesh.

**Comment by nnganesha** [comment]
Hello Dirk,

Looks like I found something here.. I was able to successfully execute the command from my Google Cloud Shell but not from my local Linux box.. But gcloud commands seem to work on my Linux box. Also this error came immediately after enter GitHub token. I believe this has something to do with Proxy, as gcloud uses the proxy slightly differently, than the normal way. Is there a GitHub authentication being performed after entering token? Since I did not get the Organization prompt, I believe something broke here.

Regards,
Ganesh.

**Comment by dirkwall** [comment]
Hey Ganesh,

We immediately check if the GitHub token has the right permissions to access the repository. That's also the last function that is called in the stacktrace: `HasTokenRepoScope`.
I'll internally follow up with the team on this issue with @agrimmer - he will provide guidance at latest on Monday.

Cheers,
Dirk

**Comment by nnganesha** [comment]
Thanks Dirk..

Regards,
Ganesh.

**Comment by agrimmer** [comment]
Dear Ganesh,

Thank you for pointing out and debugging this issue!

In the CLI we were missing a check if an error occurred when checking the GitHub token. I added this check.
Now I would like to ask you to again try to install keptn using your local Linux box. Therefore, please use the CLI available here: https://storage.googleapis.com/keptn-cli/20190729.0931-latest/keptn-macOS.zip

Now we should get a message explaining the reason for the failed check.

Thanks,
Andreas

**Comment by nnganesha** [comment]
Sure Andreas, thanks a lot.

But looks like you have given me macOS link, does it have the link to the Linux zip as well?

Regards,
Ganesh.

Distinguished Member of Technical Staff – Senior Member,
EC4-S2, Electronics City, Bangalore.

Ph: +91-80-30961089, +91 7022879872.

**Comment by agrimmer** [comment]
Sorry, I corrected the link:
https://storage.googleapis.com/keptn-cli/20190729.0931-latest/keptn-linux.zip

**Comment by nnganesha** [comment]
Thanks a lot Andreas.. This is now giving a proper message now, in terms of Git connection failure.. I am able to proceed after correcting the proxy details…



Regards,
Ganesh.

Distinguished Member of Technical Staff – Senior Member,
EC4-S2, Electronics City, Bangalore.

Ph: +91-80-30961089, +91 7022879872.

**Comment by agrimmer** [comment]
Perfect!
After fixing your Git connection failure, please use the CLI in version 0.4.0 because the version from the link above is the `develop` version.
Alternatively, you can use this version https://storage.googleapis.com/keptn-cli/bug-567-20190729.1126/keptn-linux.zip which only contains the bug fix printing a proper error message.

**Comment by nnganesha** [comment]
Thanks.. But right now, I am running into another error..

Error while applying RBAC for installer pod: Error while executing command kubectl apply -f https://raw.githubusercontent.com/keptn/installer/master/manifests/installer/rbac.yaml exit status 1
Aborting installation.

Content of rbac.yaml
-----------------------
# NOTE: The service account `default:default` already exists in k8s cluster.
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: rbac-service-account
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io


Regards,
Ganesh.

**Comment by nnganesha** [comment]
for some reason, the hash character in the textbox makes it appear bold.. updated the comment again.....

**Comment by agrimmer** [comment]
Here, the CLI tries to apply a `ClusterRoleBinding`, which results in an error.

Can you please execute the following comands from your terminal:
1. `kubectl delete -f https://raw.githubusercontent.com/keptn/installer/master/manifests/installer/rbac.yaml --ignore-not-found`
1. `kubectl apply -f https://raw.githubusercontent.com/keptn/installer/master/manifests/installer/rbac.yaml`

Afterwards, please post your error message.

**Comment by nnganesha** [comment]
Please find the error message below. Seems strange why I am seeing a forbidden message. When I use wget, I am able to retrieve rbac.yaml....

kubectl delete -f https://raw.githubusercontent.com/keptn/installer/master/manifests/installer/rbac.yaml --ignore-not-found
error: unable to recognize "https://raw.githubusercontent.com/keptn/installer/master/manifests/installer/rbac.yaml": Get https://35.200.147.114/api?timeout=32s: Forbidden
cmponprem@cmponprem-Virtual-Machine:~/keptn$ kubectl apply -f https://raw.githubusercontent.com/keptn/installer/master/manifests/installer/rbac.yaml
error: unable to recognize "https://raw.githubusercontent.com/keptn/installer/master/manifests/installer/rbac.yaml": Get https://35.200.147.114/api?timeout=32s: Forbidden

**Comment by agrimmer** [comment]
I guess this is again a network connection problem.
The Keptn CLI requires a working `kubectl`.

**Comment by nnganesha** [comment]
Yes I had the same doubt, but I am able to successfully do a wget and get the rbac.yaml fie.. Is there a separate setting for kubectl proxy? Also any clue what is the 35.200 ip address - is it the raw.githubusercontent website?

**Comment by agrimmer** [comment]
No, the 35.200 IP address is probably not Github. But you can make an `nslookup` to resolve the URL to an IP.

**Comment by nnganesha** [comment]
Finally I made the kubectl apply to work after a bit of a struggle. The point is that whenever I create a GKE cluster, it assigns the Public IP address (35.200.x.x) to it. The issue is that a corporate proxy usually blocks any https access via raw IP address. I circumvented this issue by creating a domain name in AWS Route 53 and assigned the IP address to it. This part resolved one issue. Again there is a blocker which checks for certificate validation, which again fails. Now I had to add the --insecure-skip-tls-verify flag, to bypass this.. With all these, apply seemed to work. My question now is there a way I can add these flags (insecure-skip-tls-verify flag) to kubectl commands or should I add them to the go script and compile myself? Thanks again for your help....

**Comment by agrimmer** [comment]
Do you install keptn on EKS (i.e. a Kubernetes cluster running on AWS)?
If so, this is not officially supported yet. However, @grabnerandi can help you here.

**Comment by nnganesha** [comment]
No Andreas, I am doing on a GKE cluster only.. Just for routing purpose I got a DNS entry through AWS Route53.. Also is there any documentation on recompiling the CLI? I want to make those changes to support certificate check, etc..

**Comment by agrimmer** [comment]
Before compiling the CLI, can you please first try to add the `insecure-skip-tls-verify` flag in your kube-conifg? In the CLI, we are using this config.

**Comment by nnganesha** [comment]
Yes Andreas, it worked fine while executing from command line. The other issue I am facing is that whenever i try to run the keptn install command, it resets the server parameter. For example, I am doing the below through command line.

1. kubectl config view (this gives me the clusters.cluster.server parameter as the ip address 35.200.*.*).
2. kubectl config set <clusters.clustername.server> <https://domainname>
3. kubectl get nodes

Above command works fine, since the server name is changed now. 

But, post this, if I run keptn install --platform=gke, for some reason, the server name in kubectl config gets reset to the IP address again and the kubectl apply command fails for the rbac url. Is there any reason why this gets reset again?

**Comment by agrimmer** [comment]
Thank you for this detailed description!
In fact, this is intended behavior because the CLI uses gcloud to automatically obtain the kube config.
In your case, you would like to re-use the existing kube config. Therefore, you can use the install command with the flag `--platform=kubernetes`.
I hope this solves the issue.

**Comment by nnganesha** [comment]
Thanks Andreas.. But no luck again.. This time at least the server name is retained, as you mentioned and did not get overwritten. But the rbac is failing, as the certificate error is coming. I checked the code and I can see that you have set the insecure flag only for OpenShift and not for other platforms. Is there a way you could do that please or is there any other option? I tried setting an alias for kubectl to use kubectl --insecure, but that also did not seem to work.....

**Comment by agrimmer** [comment]
Ok, I see.
So what you would need is that the CLI uses e.g.
`kubectl apply -f https://raw.githubusercontent.com/keptn/keptn/develop/installer/manifests/installer/rbac.yaml --insecure-skip-tls-verify=true`. Is this correct?

If so, I would suggest adding a new flag to the install command named `insecure-skip-tls-verify`. 

Would you be willing to contribute this new feature to the keptn CLI? Therefore, you can create a new branch from master (named feature/567/skip-tls-verify). After a push, the CLI artifact is automatically built and then I can send you the link for downloading the new CLI.

Otherwise, if you are not able to contribute, I will add the flag in the next days/weeks.

**Comment by nnganesha** [comment]
Yes Andreas, you are right.. Sure, I can definitely give it a try. Though I am new to Go language, will definitely want to explore. I will update you once done. Thanks again.

**Comment by nnganesha** [comment]
Do I have access to create a new branch here? Looks like I do not have permission to create.. Can you please check?

**Comment by agrimmer** [comment]
You have to make a fork.

**Comment by nnganesha** [comment]
Sure...

**Comment by grabnerandi** [comment]
Hi there. @nnganesha - if you want we can also discuss your steps on the keptn slack. that might be easier. If you havent joined the slack yet you can do it through this link: https://join.slack.com/t/keptn/shared_invite/enQtNTUxMTQ1MzgzMzUxLTcxMzE0OWU1YzU5YjY3NjFhYTJlZTNjOTZjY2EwYzQyYWRkZThhY2I3ZDMzN2MzOThkZjIzOTdhOGViMDNiMzI - you will find all of us on that slack workspace

**Comment by nnganesha** [comment]
Thanks Andreas.. I have submitted the pull request. I could not compile and check here, as I did not have the actual files. Please check and verify and let me know if it generated the build properly and alos the location of the build.

**Comment by agrimmer** [comment]
Hi Ganesha,
thank you very much for your PR!
Currently, we are missing a description of how to set up the environment so that external contributors can compile the CLI. We will definitely provide those instructions.
 
For now, please contact me on Slack then I can help you to set up yourenvironment.

**Comment by nnganesha** [comment]
Sure Andreas, thanks a lot. I have registered on the community..



Regards,
Ganesh.

Distinguished Member of Technical Staff – Senior Member,
EC4-S2, Electronics City, Bangalore.

Ph: +91-80-30961089, +91 7022879872.

**Comment by agrimmer** [comment]
Thank you for your contribution!
You can download the CLI here
https://storage.googleapis.com/keptn-cli/feature-567-20190803.1511/keptn-linux.zip
https://storage.googleapis.com/keptn-cli/feature-567-20190803.1511/keptn-macOS.zip
https://storage.googleapis.com/keptn-cli/feature-567-20190803.1511/keptn-windows.zip
