### ISSUE TITLE
Possibility to change ingress gateway

### ISSUE THREAD

**Issue by checkelmann** [keptn/keptn#568]
keptn is using istio as ingress gateway for web traffic and routing.
As we are using traefik (traefik.io) it would be beneficial for us to have the possibility to change the ingress type in keptn.

**Comment by jetzlstorfer** [comment]
Thanks Christian for opening an issue.
Currently keptn only supports Istio as a service mesh and all routing and virtual service definitions are based on Istio. We will take a look a traefik to investigate potential integration into keptn.

**Comment by checkelmann** [comment]
Hi @jetzlstorfer ,

what about moving from the heavyweight istio service mash to the lighter and easy to use linkerd (https://linkerd.io) which is supporting different type of ingresses like traefik per default.

All we (our company) has to change is to add an annotation to the ingress class that the connection will be handled by likerd in the backend 

https://linkerd.io/2/tasks/using-ingress/#traefik

**Comment by jetzlstorfer** [comment]
Thanks for the links - right now we have not investigated into researching alternatives to Istio.
Let's use this issue also for discussion. Once we have taken a look at it we'll come back to you.

**Comment by dirkwall** [comment]
For Keptn Quality Gates use case we now have nginx as an option. I want the ingress to be configurable and support a number of options: e.g. nginx and traefik.
More details to come.

**Comment by agrimmer** [comment]
@jetzlstorfer will also have a follow-up with linkerd for using linkerd for the traffic routing.

**Comment by pahofmann** [comment]
Are there any updates on this? We use nginx ingress on our aks cluster, would be great to have the possibility to use the existing ingress for the services deployt by keptn.

**Comment by grabnerandi** [comment]
Hi. We have additional users that want to install Keptn on a k8s cluster that already has an existing ingress. In their case it is nginx. We would need an installation option that is something like "--reuse-ingress=existing_ingress"

**Comment by agrimmer** [comment]
Keptn 0.6.2 will allow reusing an existing Istio as well as NGINX installation by providing the flag `--ingress-install-option=Reuse` in the `keptn install` command.
@pahofmann Can you please test whether this option works for you?

**Comment by christian-kreuzberger-dtx** [comment]
This issue will become obsolete once we implement [KEP 18](https://github.com/keptn/enhancement-proposals/pull/18).

**Comment by christian-kreuzberger-dtx** [comment]
Closing this as it will be part of KEP 18.
