### ISSUE TITLE
Sequence abort: The sequence abort does not work when applied on waiting state

### ISSUE THREAD

**Issue by carpe-github** [keptn/keptn#5718]
Your issue may already be reported! Please search on the [issue tracker](https://github.com/keptn/keptn/issues) before creating a new one.

**Environment**

* Client OS (e.g., Linux, macOS, Windows): Windows
* Keptn Version (`keptn version`):  0.10.0-next.1
* Kubernetes Cloud Provider (e.g., GKE, AKS):
* Kubernetes version (`kubectl version`):

**Affected Component**

* [ ] Docs
* [ ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [x] Bridge
* [ ] Approval
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**
When the sequence is aborted in "Waiting" state then an error is thrown and the sequence could not be aborted.

**To Reproduce**

1. Use api to trigger 2 evaluations one after another against the same service
![image](https://user-images.githubusercontent.com/63784298/137489480-d4d26dd8-0ee4-42a4-a60b-1ed52052d570.png)
2. Go to Keptn application
3. Go to Sequences page
4. Here you should see 2 sequences started where 1 of them is in waiting state because 2 evaluation cannot be running at the same time, right?
5. Click on abort button of the sequence which is in waiting state
![image](https://user-images.githubusercontent.com/63784298/137489794-0bee2494-b951-47ff-a960-b07a19c2daeb.png)
6. Confirm with the red button

**Expected behavior**
The sequence should be successfully aborted.

**Current behavior**
The following error is thrown :
![image](https://user-images.githubusercontent.com/63784298/137489970-744e1bd4-e5d7-401d-9e32-4d394221d5f4.png)
and the sequence (which was selected to abort) is being completed successfully in few more seconds.
![image](https://user-images.githubusercontent.com/63784298/137490207-003dca08-4d43-454b-a934-d177b6614490.png)

**Screenshots**

**Additional context**

**Comment by agrimmer** [comment]
Thank you for bringing this up!
This is a duplicate to https://github.com/keptn/keptn/issues/5472.
