### ISSUE TITLE
Keptn CLI: Have the CLI return with error status code as to support scripting

### ISSUE THREAD

**Issue by robertjahn** [keptn/keptn#572]
**Is your feature request related to a problem? Please describe.**
To support scripting, have the CLI return error status code

**Describe the solution you'd like**
When the CLI has an error such as when running "keptn create project" command and get "Could not find organziation abcd"

**Describe alternatives you've considered**
None

**Additional context**
>> example script and check
keptn create project $KEPTN_PROJECT shipyard.yaml
if [ $? -ne 0 ]
then
    echo "Project creation failed. Exiting"
    exit 1
fi

**Comment by agrimmer** [comment]
Duplicate #304
