### ISSUE TITLE
Upgrading from Keptn 0.8.3 to 0.9.x fails on OpenShift

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#5780]
There have been two reports on Slack of OpenShift users that failed to Upgrade from Keptn 0.8.3 to 0.9.x:

* https://keptn.slack.com/archives/CNRCGFU3U/p1634893032031400
* https://keptn.slack.com/archives/CNRCGFU3U/p1634700292373300

The information and screenshots provided here are from these slack conversations.

**Environment**

* Client OS (e.g., Linux, macOS, Windows): 
* Keptn Version (`keptn version`): 0.8.3, 0.9.0, 0.9.2
* Kubernetes Cloud Provider (e.g., GKE, AKS): OpenShift  v3.11
* Kubernetes version (`kubectl version`): OpenShift  v3.11

**Affected Component**

* [x] Install/Upgrade

**Describe the bug**
When upgrading from Keptn 0.8.3 to 0.9.0 on OpenShift, the upgrade seems to go through.
However, upgrading from 0.9.0 to 0.9.1 / 0.9.2 reveals the error message that there is no upgrade path between **0.8.3** and **0.9.1**.

**To Reproduce**

* Install Keptn 0.8.3 on OpenShift
* Upgrade to Keptn 0.9.0
* Open Bridge to verify you are on 0.9.0
* Then upgrade to Keptn 0.9.1/0.9.2 using `keptn upgrade --platform=openshift`

**Expected behavior**
Keptn CLI should perform the upgrade

**Current behavior**
Keptn CLI blocks the upgrade because it detects the wrong version

**Screenshots**
![image](https://user-images.githubusercontent.com/56065213/138444615-613f8386-1544-4e38-913b-801d9adb67b0.png)
![image](https://user-images.githubusercontent.com/56065213/138444784-b0f3eccc-0909-4e87-b7f6-d3779df8f9bf.png)

**Additional context**
This problem seems to be OpenShift related.

**Comment by thisthat** [comment]
I was not able to reproduce the error. A solution to overcome this problem is to manually use helm.
A guide on how to do that is available at the end of the [Quick Start](https://keptn.sh/docs/quickstart/#kubernetes-version-not-supported)
