### ISSUE TITLE
missing script: add-to-cart.sh for auto remediation use case

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#58]
**Describe the bug**
Followed the documentation for the runbook automation use cases. it references a script in usecases/runbook-automation-and-self-healing/scripts/add-to-cart.sh. Seems this file was not checked in

**Comment by jetzlstorfer** [comment]
file is now added in this section: 
https://keptn.sh/docs/0.1.0/usecases/runbook-automation-and-self-healing/#step-5-run-a-promotional-campaign
