### ISSUE TITLE
"No sequences"-message is shown right before the sequences are loaded/shown in the UI

### ISSUE THREAD

**Issue by Kirdock** [keptn/keptn#5812]
![image](https://user-images.githubusercontent.com/11599148/139049965-45823537-ce08-47b7-8ac8-f8cd72ea21fd.png)

Steps to reproduce:
1. Have a project with some sequences.
2. Refresh the sequence page.
2. Sometimes right before the sequences are shown, the "No sequence" message is shown for about a second or less.

Probably the cause: The sequences are loaded but before the view with all sequence states is rendered, the message is shown until it is fully rendered

**Comment by thisthat** [comment]
Please, verify if this was solved with Keptn 0.11

**Comment by TannerGilbert** [comment]
Could not reproduce this with Keptn v0.13.1 even when throttling the loading using the development tools.

**Comment by Kirdock** [comment]
Can't reproduce. Seems like it's already fixed.
