### ISSUE TITLE
Dynatrace alert is not being captured in keptn

### ISSUE THREAD

**Issue by SaveethaRavi** [keptn/keptn#5820]
Hi team,

Facing some issues related to dynatrace alert is not triggered to keptn. Created new project and checked as well, still there is an issue in keptn. I have also raised it in slack help channel. Please check and let us the issue to get resolve in keptn asap.
<img width="354" alt="keptn image3" src="https://user-images.githubusercontent.com/57527241/139087709-fa1a9c86-9a16-4f18-a898-f2c542a0674e.PNG">
<img width="351" alt="keptn image2" src="https://user-images.githubusercontent.com/57527241/139087717-52880531-b3d1-4c2b-a901-53ea1055e16f.PNG">
<img width="561" alt="keptn image1" src="https://user-images.githubusercontent.com/57527241/139087721-aad87daf-2b6c-4f8b-a13d-4b2c07870ab1.PNG">

**Comment by thisthat** [comment]
This was fixed over our slack channel.
