### ISSUE TITLE
(WIP) chore(shipyard-controller): cleanup code to do propper error formatting/handling 

### ISSUE THREAD

**Issue by warber** [keptn/keptn#5827]
## Action Item
The current code of the ShipyardController uses constructs like
```
if err == db.ErrNoEventFound {
	return ErrSequenceNotFound
}
```
to check for a given error type. However, comparing errors with == will fail on wrapped errors. (`%w`)
Clean up the code to use `errors.Is/As` as well as propper error wrapping to handle and format all kinds of errors.

**Comment by thisthat** [comment]
We should split this ticket on a component based.
