### ISSUE TITLE
Show integrations from ArtifactHub

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#5830]
Right now Keptn's Bridge displays integrations by loading them from an integrations.html page from [get.keptn.sh](https://github.com/keptn/get.keptn.sh/blob/master/src/integrations.html).

![image](https://user-images.githubusercontent.com/56065213/139402004-0fd28cbb-2c25-4d44-8169-55c3dc2127b9.png)

With our integrations being listed on ArtifactHub, there is now also a nice way to display them in HTML, see https://github.com/keptn/keptn.github.io/pull/950/files as a reference.

![image](https://user-images.githubusercontent.com/56065213/139402211-66725fa3-9657-4fd5-bcde-59b8dafedc8d.png)

**To be defined**: 
* Which integrations should be listed in Keptn Bridge (e.g., just the ones that are currently compatible?)
* Should there be filters in Keptn Bridge?

# Definition of Done

- [ ] Integrations page in Keptn Bridge shows a list of integrations

**Comment by TannerGilbert** [comment]
It's no longer planned to show the integrations from ArtifactHub inside the Bridge. They are available on https://keptn.sh/docs/integrations/ though.
