### ISSUE TITLE
Bridge: Clarify with a message that secrets are shared across project.

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#5832]
## Action Item

In the secret screen, the message `secrets are shared across projects` should be added.

**Comment by robertjahn** [comment]
The Bridge UI would be more intuitive if the “secrets” were managed at the global level (not in the project uniform page),  Then to indicate a secret is related to project, either (A) have a list of projects on that global secrets page where one checks the project(s) it applies to.  Or (B) on the project uniform page you don't add secrets, you just have check box to pick the existing secret(s) that were setup on the global page that are applicable for that project
