### ISSUE TITLE
Cannot set git upstream in configuration service if Git Tenant expects a certificate

### ISSUE THREAD

**Issue by thkoenia** [keptn/keptn#5833]
**Environment**

**Affected Component**

When using the configuration service and setting up a git upstream we need a certificate in order to connect to our onPrem Github. Unfortunalety I didnt find a method to do that, I also tried building a new image with root rights and loading the cert into the image but it doesnt work. Is there any possible solution you already done? or any advice for us?

Thanks in advance!

**Comment by thisthat** [comment]
Hi @thkoenia sorry if I miss this issue. With [KEP48](https://github.com/keptn/enhancement-proposals/pull/48#issuecomment-925533808), we are working on supporting this use case.

**Comment by thisthat** [comment]
I will close this ticket in favor of #6179 to have only a single ticket for discussion.
