### ISSUE TITLE
Build Pipeline: `CI:trigger-build-everything` does not consider changes on master

### ISSUE THREAD

**Issue by warber** [keptn/keptn#5942]
## Bug Description

The `CI:trigger-build-everything` is an important flag to tell the build pipeline to build every artifact from a specific branch/PR which can then be used during integration tests. Artifacts that went through code changes are freshly bulid, all other artifacts are just retagged. However, changes made on the master branch are not considered (even if you do a git rebase). 

## Workaround
In order to make sure that every artifact is up to date with the current state of the master branch, a new PR needs to be created.

**Comment by mowies** [comment]
Fixed in #5943
