### ISSUE TITLE
The sequence with webhook needs a timeout when "finished" event is not received

### ISSUE THREAD

**Issue by carpe-github** [keptn/keptn#5947]
**Environment**

* Client OS (Windows):
* Keptn Version (0.10.0):
* Kubernetes Cloud Provider (e.g., GKE, AKS):
* Kubernetes version (`kubectl version`):

**Affected Component**

* [ ] Approval
* [x] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**

**To Reproduce**

1. Setup a webhook which looks like in img1. The webhook triggers an evaluation of 'health' service. The webhook will be triggered when an evaluation is triggered against 'items' service.
img 1:
![image](https://user-images.githubusercontent.com/63784298/140905656-caab512a-f12a-4426-b981-a45c31076264.png)

2. Trigger an evaluation against 'items'
3. go to Sequences page
4. Here you will see the appropriate sequence is started, the evaluation against 'items' is triggered  and webhook service started 
5. Refresh the page
6. you will see an evaluation against 'health' service is triggered and finished (img 2)
img 2:
![image](https://user-images.githubusercontent.com/63784298/140905804-84b11256-73fb-4651-8f77-26283eaf25f9.png)

7. Now take a look to the sequence of 'items' (which was triggered initially )

**Current behavior/Issue**

Make sure the evaluation loading icon runs  continuously and never ends. (img 2)

**Expected behavior**

 A timeout is needed that should terminate a task when a service responded with a 'started' but not with a 'finished' event within x minutes.

**Important**
8. Go to Services -> Items
Here you can see that the evaluation chart cannot be loaded.
![image](https://user-images.githubusercontent.com/63784298/140951288-31d3baca-1b06-4e37-89dd-d85c2b4197c0.png)

 Even after aborting the sequence
![image](https://user-images.githubusercontent.com/63784298/140951678-a59dd692-3181-4068-83de-aa6d895d0a12.png)

The evaluation chart cannot be redrawn:
![image](https://user-images.githubusercontent.com/63784298/140951852-80b11640-bab9-478c-8271-d00c0a604915.png)

**Screenshots**

**Additional context**

**Comment by johannes-b** [comment]
This ticket should not be limited to the scope of a webhook execution, it is more general on task timeouts. 

Extending the shipyard-service functionality by a timeout mechanism that terminates a task execution when receiving a `started` but not `finished` event after x minutes.

**Comment by Kirdock** [comment]
Regarding the hidden evaluation chart.
It is hidden because the evaluation is not finished (in the case that all triggered events have to be finished). 
https://github.com/keptn/keptn/blob/5d3441b3063be5c276da2f2a1dd6e285391b2ba9/bridge/client/app/_components/ktb-service-details/ktb-service-details.component.html#L85

But this will be fixed with #5915

**Comment by thisthat** [comment]
This will be fixed by https://github.com/keptn/keptn/issues/6524

**Comment by thisthat** [comment]
#6524 has been solved. Closing this issue
