### ISSUE TITLE
Webhook: Add task data to error log events

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#5953]
## Action Item

The WebHook service should provide the `task` value as part of the [Error Log event](https://github.com/keptn/spec/blob/master/cloudevents.md#error-log) payload.

This way, it is easier to jump from the error log message to the sequence in the Bridge.
![webhook-error-logs](https://user-images.githubusercontent.com/992621/140922907-3036265e-e69a-4987-99f9-ae6f4fe64b79.PNG)

**Comment by odubajDT** [comment]
I will like to take it, thanks.

**Comment by odubajDT** [comment]
According to my investigation, there is a problem with an invalid event (sh.keptn.event.deployment.started.finished). The proper event (sh.keptn.event.deployment.started) is sent by multiple functions until we came to function `sendEvent(...)` https://github.com/keptn/keptn/blob/master/distributor/pkg/lib/events/receiver.go#L160, where on line 178 the receiver sends a proper event (sh.keptn.event.deployment.started) to NATS with the specified context. This is the last place where the event is valid. The first place (from what I know now), where the event is invalid (sh.keptn.event.deployment.started.finished) is forwarder (https://github.com/keptn/keptn/blob/master/distributor/pkg/lib/events/forwarder.go#L76), where the event is received by function `DecodeNATSMessage(body)`. From this and on, we are working with an invalid event (sh.keptn.event.deployment.started.finished).

The actual reason we are facing 'n/a' in Error Events logs in keptn is, that in UniformLogger on line 60 (https://github.com/keptn/keptn/blob/master/distributor/pkg/lib/controlplane/uniformlog.go#L60), we are parsing the task name from the invalid event. The invalid event is recognized by function `ParseTaskEventType(...)` and actually returns an empty string, as it has a check, if the event is valid. If we disable the check of the validity of event, it seems to work well (see picture).
![Screenshot from 2021-11-11 15-00-34](https://user-images.githubusercontent.com/93584209/141314689-afaf6669-8242-4621-a1f1-85190ac4d1e0.png)




The above mentioned solution is not a proper fix, as we need to investigate why suffix .finished is added to the valid event. Continuing to work on the fix.

**Comment by odubajDT** [comment]
The `ParseTaskEventType(...)` function is available here https://github.com/keptn/go-utils/blob/master/pkg/lib/v0_2_0/events.go#L211

**Comment by odubajDT** [comment]
Possible resolution, which was not tested properly yet:

`diff --git a/go-sdk/pkg/sdk/keptn.go b/go-sdk/pkg/sdk/keptn.go
index a33fc306..e6d61f67 100644
--- a/go-sdk/pkg/sdk/keptn.go
+++ b/go-sdk/pkg/sdk/keptn.go
@@ -245,7 +245,11 @@ func (k *Keptn) createFinishedEventForTriggeredEvent(triggeredEvent cloudevents.
                genericEvent["result"] = "pass"
        }
 
-       finishedEventType := strings.TrimSuffix(triggeredEvent.Type(), ".triggered") + ".finished"
+       if strings.HasSuffix(triggeredEvent.Type(), ".started") {
+               finishedEventType := strings.TrimSuffix(triggeredEvent.Type(), ".started") + ".finished"
+       } else if strings.HasSuffix(triggeredEvent.Type(), ".triggered") {
+               finishedEventType := strings.TrimSuffix(triggeredEvent.Type(), ".triggered") + ".finished"
+       }
        keptnContext, _ := triggeredEvent.Context.GetExtension(KeptnContextCEExtension)
        c := cloudevents.NewEvent()
        c.SetID(uuid.New().String())`

**Comment by odubajDT** [comment]
Issue fixed in PR:

https://github.com/keptn/keptn/pull/5998
