### ISSUE TITLE
Bridge: Show `timedOut` sequence status not in camel case 

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#5970]
## (UX) Design 

Show the `timedOut` status not in camel case, but rather in this way: `timed out`

![image](https://user-images.githubusercontent.com/729071/141086965-1ccbfd3c-b86a-4fe8-99ba-457eba8483b2.png)

![image](https://user-images.githubusercontent.com/729071/141087045-60b20e4a-9d98-4eb9-83cb-dc2855949ae5.png)

## Definition of Done:
- [ ] Tests adapted accordingly
- [ ] As a user, I see `timed out`

**Comment by thisthat** [comment]
Fixed with #6215
