### ISSUE TITLE
Keptn 0.10.0 distributor does not reconnect if it loses nats connection

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#5974]
Unfortunately https://github.com/keptn/keptn/issues/5819 was not solved, at least not in Keptn 0.10.0.

# Current behaviour

When the nats-cluster pod gets restarted / rescheduled by Kubernetes, some (if not all) Keptn distributors are malfunctioning. This behaviour manifests in "not reacting to any CloudEvent".

# Expected behaviour

Distributors should reconnect when they lose connection to NATS.

# To reproduce

1. Install Istio and Keptn 0.10.0 (`keptn install --use-case=continuous-delivery`)
2. Create a project and onboard services (e.g., sockshop or podtato-head)
3. Trigger a delivery - verify everything works
4. Kill the nats cluster pod: `kubectl -n keptn delete pod keptn-nats-cluster-0`
5. Wait for it to come back up (`watch -n1 kubectl -n keptn get pods`)
6. Trigger another delivery - verify in Bridge if this delivery has been triggered and if everything works

# Additional info

I am on a **multi-node** cluster on GKE 1.20

I've recorded this as a video, showing 4 commandlines on my screen

|   |  |
| ------------------------------------ | ---------------------------------- |
| Pods in Keptn Namespace | interactive command line |
| logs of distributor of shipyard-controller | logs of distributor of helm-service |

https://user-images.githubusercontent.com/56065213/141111787-afdec2d9-5dde-4ab9-8733-293c146ef3bb.mp4

**Comment by thisthat** [comment]
This fix will be released in 0.11
