### ISSUE TITLE
keptn add-resource with an invalid .tgz file makes your Keptn project unusable

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#5975]
This is with Keptn 0.10.0, and unfortunately, this is a very tricky one to describe (however, the fix should be easy):

When adding a `.tgz` file using `keptn add-resource` this file usually gets unpacked (unarchived) by configuration-service. This is used in order to add helm charts to Keptn, e.g.:

```
keptn add-resource --project=nodejs-example --service=hello-service --all-stages --resource=.keptn/helm/hello-service.tgz --resourceUri=helm/hello-service.tgz
```

However, if for whatever reason, the `.tgz` file is invalid (because of a user error!), we run into a lot of troubles.

# How to reproduce

Create a random file, e.g.
```console
echo "123" > my-service.tgz
```

Create a simple shipyard file, e.g.:
**shipyard.yaml**
```
apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "shipyard-quality-gates"
spec:
  stages:
    - name: "hardening"
```

Create a project, and a service
```
keptn create project example --shipyard=./shipyard.yaml
keptn create service my-service --project example
```

Add the .tgz file as a helm chart
```
keptn add-resource --project=example --service=my-service --all-stages --resource=./my-service.tgz --resourceUri=helm/my-service.tgz
```

The last command fails with
```
Adding resource ./my-service.tgz to all stages of project example
Error: Resource ./my-service.tgz could not be uploaded: Could not unarchive Helm chart
```

If you try to access configuration-service and look into the git repo, you will see this:
```
kubectl -n keptn exec -it deployment/configuration-service configuration-service -- sh

cd /data/config/example
git status
```

```
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	my-service/
```

For some reason, it is still possible to continue working (e.g., `keptn trigger evaluation`). In addition, the `.tgz` file seems to get added to the respective branches (hardening), but not extracted (because it's a faulty file).

# Expected behaviour

When adding a .tgz file as a resource and the extraction process fails, the git repo **must not** contain the `.tgz` file.

# Related code
https://github.com/keptn/keptn/blob/48fc51c1c2b4689b6658e36a8751d0d020c1912c/configuration-service/handlers/service_resource.go#L237-L264

**Comment by odubajDT** [comment]
I'll take it, thanks.

**Comment by thisthat** [comment]
Thank you @odubajDT !

**Comment by odubajDT** [comment]
This issue should be caused only by bad order of the actions. Currently, by looping through the resource(s), the code actually adds the resource to the git repository and then tries to extract it. From my POV, we should first extract the file and check if it is valid and if yes, then add it to the repository. Affected code here: https://github.com/keptn/keptn/blob/master/configuration-service/handlers/service_resource.go#L209 and on line 332 as well

I will test the fix and provide a PR.

**Comment by odubajDT** [comment]
PR fixing the issue:

https://github.com/keptn/keptn/pull/6006
