### ISSUE TITLE
Can't trigger delivery in user-managed setup with helm chart

### ISSUE THREAD

**Issue by mowies** [keptn/keptn#5979]
**Environment**

* Client OS (e.g., Linux, macOS, Windows): macOS
* Keptn Version (`keptn version`): Bug is there since `0.9.0`
* Kubernetes Cloud Provider (e.g., GKE, AKS): GKE `v1.20.10-gke.1600`
* Kubernetes version (`kubectl version`): `v1.22.1`

**Affected Component**

* Shipyard Controller
* User managed deployments

**Describe the bug**
In our integration tests setup we use the [user-managed deployment feature of keptn](https://keptn.sh/docs/0.10.x/continuous_delivery/deployment_helm/#user-managed-deployments-experimental) to deploy keptn on keptn with our released helm chart.
This worked until I upgraded to keptn `0.9.0` and any version later than that.

Now, I can't trigger a delivery anymore with the documented `delivery.triggered` event following the [docs here](https://keptn.sh/docs/0.10.x/continuous_delivery/deployment_helm/#user-managed-deployments-experimental).

The shipyard controller has the following error:
```
time="2021-11-11T08:35:41Z" level=info msg="Found matching task sequence delivery in stage dev"                                                                                      
time="2021-11-11T08:35:41Z" level=info msg="Returning first task of task sequence delivery"                                                                                          
time="2021-11-11T08:35:41Z" level=error msg="could not update deployed image of sequence state: could not determine deployed image: could not extract image name of event: could not find property configurationChange.Values['image'] of type string"
```

The event that I sent:
```
{
  "data": {
    "message": "",
    "project": "keptn",
    "result": "",
    "service": "keptn",
    "stage": "dev",
    "status": "",
  },
  "source": "gh",
  "specversion": "1.0",
  "type": "sh.keptn.event.dev.delivery.triggered",
  "shkeptnspecversion": "0.2.1"
}
```

** Additional Notes **
I think the problem is here: https://github.com/keptn/keptn/blob/master/shipyard-controller/common/keptn_helpers.go#L185-L190
The `configurationChange` field is not in the event and also cannot really be in the event since it's a user-managed deployment with no single image.

❗️ **This could be covered by an integration test**

**To Reproduce**

* set up a user-managed setup like keptn deployed with keptn that uses a user-managed helm chart instead of just a container image
* try to trigger a delivery with an event like the one above

**Expected behavior**
Delivery is triggered and a `deployment.started` event is fired.

**Current behavior**
The above error is fired and the delivery times out after some time.

**Screenshots**

![Screenshot 2021-11-11 at 11 06 14](https://user-images.githubusercontent.com/6901203/141279246-c88c60c6-2eff-4534-bb7c-e790648ee790.png)
![Screenshot 2021-11-11 at 11 08 02](https://user-images.githubusercontent.com/6901203/141279515-9daa7530-ca22-4d78-b774-cbc2f12d2068.png)

![Screenshot 2021-11-11 at 11 08 10](https://user-images.githubusercontent.com/6901203/141279525-dc91a8f3-ac97-46aa-90c5-738370ff0d87.png)

**Comment by christian-kreuzberger-dtx** [comment]
workaround for now: rename the sequence to something else :D
