### ISSUE TITLE
Core: Remove legacy update code 

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#5992]
## Action Item 

Remove legacy code in the CLI that handles the upgrade of shipyard definition from 0.7.x.

**Comment by odubajDT** [comment]
I will take it, thanks.

**Comment by thisthat** [comment]
Assigned to you @odubajDT! thank you!

**Comment by odubajDT** [comment]
I will take it, thanks.

**Comment by odubajDT** [comment]
Dependent issue: https://github.com/keptn/keptn/issues/6211
