### ISSUE TITLE
CLI: `keptn auth` command fails when `--endpoint` is passed without `http://` scheme prefix

### ISSUE THREAD

**Issue by warber** [keptn/keptn#6013]
The value  for `--endpoint` argument of `keptn auth` command does not work without the `http://` prefix:

```
keptn auth --api-token=$KEPTN_API_TOKEN --endpoint=1.2.3.4
Please make sure to use the same versions.
Starting to authenticate
Failed to resolve hostname 
Retrying...
```
For the user it is unclear why the `keptn auth` command failed.

Passing the value with `http://` prefix works:
```
keptn auth --api-token=$KEPTN_API_TOKEN --endpoint=http://1.2.3.4
Starting to authenticate
Successfully authenticated against the Keptn cluster http://146.148.113.109/api
Using a file-based storage for the key because the password-store seems to be not set up.

```

**Comment by odubajDT** [comment]
I can take it, thanks.

**Comment by odubajDT** [comment]
The fix is rather simple, in function `smartFetchKeptnAuthParameters()` (https://github.com/keptn/keptn/blob/master/cli/cmd/auth.go#L134) nothing checks if the endpoint URL does contain http or https prefix.
