### ISSUE TITLE
Run unit tests without rendering UI for Dashboard

### ISSUE THREAD

**Issue by ermin-muratovic** [keptn/keptn#6034]
To decrease the time for unit tests in Keptn's Bridge, we should get rid of all UI rendering in the unit tests.
The unit tests should just consist of functional tests of the components. UI tests should be covered by Cypress tests.

This issue should cover the Dashboard and used sub-components.

## Definition of Done

- [ ] Existing unit tests that touch the UI should be moved to Cypress UI tests
- [ ] Run unit tests without rendering UI (should decrease the time for running unit tests)

**Comment by thisthat** [comment]
This ticket should be split by page to create working packages of tests to look at

**Comment by ermin-muratovic** [comment]
I split this issue per view in the Bridge:
- #6352 
- #6353 
- #6354 
- #6355 
- #6356 
- #6357
