### ISSUE TITLE
Refactoring of configuration service

### ISSUE THREAD

**Issue by odubajDT** [keptn/keptn#6035]
**Is your feature request related to a problem? Please describe.**
Refactoring of configuration service should be done due to lack of unit tests. Currently it is very hard to create any tests due to the structure of the code. Therefore refactoring is needed.

**Comment by warber** [comment]
Also to be considered:
* Replace generated code by an implementation based on `gin-gonic` web framework
* Replace dependency to `git` binary with a propper git library
