### ISSUE TITLE
mongodb-datastore: check and fix `transformEventToInterface(event)`

### ISSUE THREAD

**Issue by warber** [keptn/keptn#6038]
## Action Item

The database related code of the mongodb-datastore has a function called `transformEventToInterface(event)` which is used before inserting stuff into the database.
Please check wheather this is still necessary, if yes, document why we are doing this, if not delete it.

**Comment by RealAnna** [comment]
We need too keep this since Mongo DB converts empty time location to a strange format, eg.

`Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -17,3 +17,898 @@
        	            	   ext: (int64) 62135596800,
        	            	-  loc: (*time.Location)(<nil>)
        	            	+  loc: (*time.Location)({
        	            	+   name: (string) (len=5) "Local",
        	            	+   zone: ([]time.zone) (len=7) {
        	            	+    (time.zone) {
        	            	+     name: (string) (len=3) "LMT",
        	            	+     offset: (int) 3921,
        	            	+     isDST: (bool) false
        	            	+    },
        	            	+    (time.zone) {
        	            	+     name: (string) (len=4) "CEST",
        	            	+     offset: (int) 7200,
        	            	+     isDST: (bool) true`
