### ISSUE TITLE
Use best practise helm chart patterns in installer

### ISSUE THREAD

**Issue by mowies** [keptn/keptn#6042]
This is a task derived from #5456.

As a provider of a whole lot of different helm charts, Bitnami has come to be a sort of best practise provider in helm chart implementations. They make use of a [common library chart](https://github.com/bitnami/charts/tree/master/bitnami/common) which we could also use as inspiration in this repo.
It provides useful helper functions to streamline the different manifests inside our installer and make it overall more maintainable and readable.

### DoD
* implement a separate helm chart or make use of bitnamis chart (Apache-2.0 License)
* replace custom implementations in the installer with the helper from the library chart where possible

Lots of work for this was already done in #5456 so it should be used as inspiration and baseline for this ticket.

**Comment by agardnerIT** [comment]
Will this allow me to disable / enable all services? For example what if I don't want the statistics-service just for a temporary demo? I shouldn't have to use kustomise for this.

**Comment by mowies** [comment]
Your use case is not planned to be done in this ticket, but it's definitely valid and useful, so it would be great if you could create a separate issue for that :)
