### ISSUE TITLE
Bridge: Implement OIDC flow

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#6076]
## User Story

As a User, I would like to login in Bridge via my SSO

## Technical details

The discovery URL is set via the `OAUTH_DISCOVERY` env var.  The scope should be set to `openid`. 
The token will be stored in the bridge-backend in the express layer.

## DoD

- [ ] Unit tests
- [ ] Integration tests
- [ ] The Bridge stores the access and id tokens

## Dependencies 

- https://github.com/keptn/keptn/issues/6073

**Comment by Kavindu-Dodan** [comment]
Some technical details to help the implementation.

OAuth discovery is standardized through [RFC8415](https://datatracker.ietf.org/doc/html/rfc8414). This will help us with supportability on different identity providers.

With regards to endpoints, I see following are essential to be exposed from the discovery,

- issuer 
- authorization_endpoint
- token_endpoint
- jwks_uri

To authenticate the end user, I would propose to utilize ID Token [1] and its validity . OpenID Connect specification already contain the validations [2] and following are some extracts from that,

- `iss` of the token to match the provider we expect token from
- `aud` must be the client id belongs to this specific bridge
- Token signature against current keys published by issuer (JWS validation) [3]
- `exp` to detect expiration 
- `nonce` to defense from replay attacks

Many of the technical details should be covered by libraries. I would proposed to use certified OpenID Connect library [4].

Sample discovery from Microsoft - https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration 

[1] https://openid.net/specs/openid-connect-core-1_0.html#IDToken 
[2] https://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation
[3] https://datatracker.ietf.org/doc/html/rfc7515
[4] https://openid.net/developers/certified/
