### ISSUE TITLE
Bridge: Document OIDC

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#6082]
## Action Item

Update the website describing how to enable and use OIDC to login into Bridge.

**Comment by johannes-b** [comment]
Next to the basic authentication, we have already **OAuth/OpenID Authentication** for Bridge explained here: https://keptn.sh/docs/0.11.x/reference/bridge/oauth/

I would leave this menu entry, but redirect to a new page under **Operate Keptn** > **User Management** > **Configuring Keptn OIDC**
