### ISSUE TITLE
CLI: Send the access token as Bearer header

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#6084]
## Action Item

If the CLI detects there are access and refresh tokens, it shall send the access token as an HTTP header to every Keptn API request.

## Technical details
The token is available in the local filesystem #6083
The HTTP header will be of the following format: `Authorization: Bearer <access-token>`.
The `x-token` header is not necessary if we logged in via SSO. 

## DoD

- [ ] Unit tests

**Comment by Kavindu-Dodan** [comment]
Given that CLI is installed locally and is public, the CLI need a mechanism to obtain required parameters to build OAuth requests. In general this is authorization server URLs and OAuth client credentials.

Given that we follow the bearer token specification ([RFC6750](https://datatracker.ietf.org/doc/html/rfc6750)), CLI can obtain the Authorization server and Public client details as claims in WWW-Authenticate Response Header [1]

For example, Keptn core must respond unauthorized API requests with following payload,

`HTTP/1.1 401 Unauthorized
WWW-Authenticate: error="no_token", issuer=<issuer_discovery>, client =<client_id>` 

Which will trigger a reauthentication in CLI. 

Further, CLI should be able to utilize a `localhost` redirect url if authorization code flow [2] is used to obtain the access token. 

[1] https://datatracker.ietf.org/doc/html/rfc6750#section-3
[2] https://datatracker.ietf.org/doc/html/rfc6749#section-4.1
