### ISSUE TITLE
Setup Prometheus for alerting rules and as alert manager

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#612]
- [x] Setup Prometheus for alerting rules and as alert manager
- [x] Remove dependencies to sockshop

**Comment by jetzlstorfer** [comment]
Removal of dependencies has been moved to a dedicated issue #657

**Comment by jetzlstorfer** [comment]
Research done. Results are committed to a feature branch https://github.com/keptn/examples/tree/feature/612/prometheus-alerting 

Alerting has to be tuned to meet the actual use case and is only for demo purposes here.
The alert can be fired by generating a little bit of load on containers in the `sockshop-dev` namespace, e.g., with
```
hey -z 5m http://carts.sockshop-dev.DOMAIN.xip.io/
```
