### ISSUE TITLE
Bridge refreshes and looses current selection on Environment Screen

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#6159]
**Environment**
* Client OS: Windows, Chrome
* Keptn Version (`keptn version`): 0.10.0

**Affected Component**
* [x] Bridge

**Describe the bug**
On the enviornment screen I can click on e.g: "4 services out of sync" -> see in the next screenshot

![image](https://user-images.githubusercontent.com/675886/143245289-63752593-7a71-49a7-9c61-9e0c43c779b6.png)

As the bridge refreshes its data every couple of seconds this selection is lost after every refresh. This lets me loose my current context if I e.g: want to look through the current services that can be pushed to this stage.

**Comment by ermin-muratovic** [comment]
Can't reproduce this with Keptn v0.11.3
