### ISSUE TITLE
Map evaluation data for d3 heatmap

### ISSUE THREAD

**Issue by Kirdock** [keptn/keptn#6165]
In order for the heatmap to correctly show the evaluation data, we need to map it in a way, the heatmap can read it.

Depends on #6162 

## Definition of Done
- [ ] The evaluation data is mapped to a format the heatmap accepts
- [ ] Highcharts heatmap is replaced by d3
- [ ] Unit tests
- [ ] UI tests
- [ ] Use d3 rendering only when FF `sh.keptn.d3` is enabled

**Comment by heinzburgstaller** [comment]
Feature flag is set `D3_HEATMAP_ENABLED` instead of `sh.keptn.d3`
