### ISSUE TITLE
Core: Research how to avoid use a local git repository

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#6179]
## User story

As a user, I would like to only use an upstream to store the Keptn project data.

## Technical details

Mind that, the repository could be configured:
- behind a [proxy](https://gist.github.com/evantoli/f8c23a37eb3558ab8765#setting-a-global-proxy)
- HTTPS via either: TLS or username/password
- SSH with private key authentication

The goal of this research is to:

- [ ] Identify possible performance bottlenecks
- [ ] Verify that the current git-model to store data scales to only upstream
- [ ] Collect the required changes to move to an upstream-only approach 
- [ ] How the configuration-service should change to support multiple replicas

## Researches

This ticket has been split into:
- https://github.com/keptn/keptn/issues/6229
- https://github.com/keptn/keptn/issues/6230
- https://github.com/keptn/keptn/issues/6231
- https://github.com/keptn/keptn/issues/6232

**Comment by agrimmer** [comment]
Please checkout my proposal documented on https://github.com/keptn/keptn/issues/4066
