### ISSUE TITLE
Sequences are empty if projects endpoint finishes after project endpoint of bridge server

### ISSUE THREAD

**Issue by Kirdock** [keptn/keptn#6183]
If the project endpoint of the bridge server responds before the projects endpoint of the shipyard controller, the sequences are removed.
Initial load:
![image](https://user-images.githubusercontent.com/11599148/143478245-dfa4843a-ac24-4ebb-88c8-3d3407c1b311.png)

After some milliseconds
![image](https://user-images.githubusercontent.com/11599148/143478057-95cd0ea4-4a58-4462-a2f9-3a6d1652d19d.png)

**Comment by carpe-github** [comment]
The issue is reproducible by simply refreshing the browser page when Sequences page is selected in Keptn.
Please consider this small test to verify while fixing it in local env.
