### ISSUE TITLE
Bridge: Mockup for selecting https/ssh upstream configuration

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#6217]
## Action Item 

Provide a mockup for the Bridge to configure a remote upstream via HTTPS or SSH. This can be configured in the setting page of a project and when creating a new project. 

Example: 

![](https://user-images.githubusercontent.com/729071/135441737-3b23490b-05ca-4598-a141-c8ec34d135b4.png)

**Comment by laneli** [comment]
![Create project - HTTPS.png](https://images.zenhubusercontent.com/613777b635e989b05cced7d7/d04ca1c9-e382-4c4f-b272-6c3ee2a0547d)
![Create project - SSH.png](https://images.zenhubusercontent.com/613777b635e989b05cced7d7/82a63601-cb82-4c23-b2f0-2998b4d0822c)
