### ISSUE TITLE
Add --shipyard option to `keptn update project` in cli

### ISSUE THREAD

**Issue by odubajDT** [keptn/keptn#6265]
**Is your feature request related to a problem? Please describe.**
Add --shipyard option to `keptn update project` in cli as an optional parameter. Also discuss if --git-* parameters should be required and add unit tests

**Comment by odubajDT** [comment]
Draft for this issue: https://github.com/odubajDT/keptn/commit/37dc57710c5f70e9f32281b04c8cedcd904b4c34

**Comment by thisthat** [comment]
Since we are moving towards an upstream only solution, the team decided that it is better to only update the shipyard via PR review on the linked repo.
