### ISSUE TITLE
Can't install keptn in openshift cluster.

### ISSUE THREAD

**Issue by fedextm** [keptn/keptn#6272]
Your issue may already be reported! Please search on the [issue tracker](https://github.com/keptn/keptn/issues) before creating a new one.

**Environment**

* Client OS (e.g., Linux, macOS, Windows):  Linux
* Keptn Version (`keptn version`): 0.11.2
* Kubernetes Cloud Provider (e.g., GKE, AKS): Openshift Selfhosted
* Kubernetes version (`kubectl version`): 
Client Version: 4.8.3
Server Version: 4.8.12
Kubernetes Version: v1.21.1+d8043e1

*Helm Version: version.BuildInfo{Version:"v3.2.3+4.el8", GitCommit:"2160a65177049990d1b76efc67cb1a9fd21909b1", GitTreeState:"clean", GoVersion:"go1.13.4"} 

**Affected Component**

* [ ] Approval
* [ ] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [x] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**

1. Install Helm
2. Follow the guide line describe here - https://keptn.sh/docs/0.11.x/operate/advanced_install_options/
3. Execute in command line "helm install keptn https://github.com/keptn/keptn/releases/download/0.11.2/keptn-0.11.2.tgz -n keptn --create-namespace --wait --set=continuous-delivery.enabled=true,continuous-delivery.openshift.enabled=true"

**Expected behavior**

Installed keptn in openshift cluster

**Current behavior**

Error 
Error: template: keptn/charts/continuous-delivery/charts/openshift/templates/route-service-openshift.yaml:113:14: executing "keptn/charts/continuous-delivery/charts/openshift/templates/route-service-openshift.yaml" at <include "control-plane.dist.common.env.vars" .>: error calling include: template: keptn/charts/control-plane/templates/_helpers.tpl:101:14: executing "control-plane.dist.common.env.vars" at <.Values.distributor.metadata.namespace>: nil pointer evaluating interface {}.namespace

**Screenshots**

**Additional context**

**Comment by oleg-nenashev** [comment]
Triage results:

* `control-plane.dist.common.env.vars` was introduced by @warber in #4276 : https://github.com/keptn/keptn/blame/master/installer/manifests/keptn/charts/continuous-delivery/charts/openshift/templates/route-service-openshift.yaml#L113 (Keptn 0.8.4)
* The variable was present in `installer/manifests/keptn/charts/control-plane/templates/_helpers.tpl`. The variables are still declared there. I check the conditional declarations, and it *should* be included by default
* The variable reference is still present in other places: https://github.com/keptn/keptn/search?q=control-plane+dist+common+env+vars 

I do not see why the variable does not get picked up in this case. Will try running the Helm chart generator locally to see whether there is any issue with templating

**Comment by bacherfl** [comment]
Hi, I just investigated this issue and it is very likely that we will not need the `openshift-route-service` anymore in the future. So for now you can also already omit the `continuous-delivery.openshift.enabled=true` option - this should make the installation work. 
Some background information: The openshift-route-service has been used for setting up the configuration needed for enabling Istio injection in a namespace within an openshift cluster, as described here: https://istio.io/latest/docs/setup/platform-setup/openshift/ 

So if you plan to use Keptn for deploying services using Istio, those instructions would need to be followed.

**Comment by fedextm** [comment]
> Hi, I just investigated this issue and it is very likely that we will not need the `openshift-route-service` anymore in the future. So for now you can also already omit the `continuous-delivery.openshift.enabled=true` option - this should make the installation work. Some background information: The openshift-route-service has been used for setting up the configuration needed for enabling Istio injection in a namespace within an openshift cluster, as described here: https://istio.io/latest/docs/setup/platform-setup/openshift/
> 
> So if you plan to use Keptn for deploying services using Istio, those instructions would need to be followed.

Hi. Unfortunately without "continuous-delivery.openshift.enabled=true" option installation doesn't work.
When I try to execute:

`helm install keptn https://github.com/keptn/keptn/releases/download/0.11.2/keptn-0.11.2.tgz -n keptn --wait --set=continuous-delivery.enabled=true`

I've got error:
`Error: timed out waiting for the condition`

And none of all needed deployments doesn't work:
```
NAME                                    READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/api-gateway-nginx       0/1     0            0           5m24s
deployment.apps/api-service             0/1     0            0           5m24s
deployment.apps/approval-service        0/1     0            0           5m24s
deployment.apps/bridge                  0/1     0            0           5m24s
deployment.apps/configuration-service   0/1     0            0           5m24s
deployment.apps/keptn-mongo             0/1     0            0           5m24s
deployment.apps/lighthouse-service      0/1     0            0           5m24s
deployment.apps/mongodb-datastore       0/1     0            0           5m24s
deployment.apps/remediation-service     0/1     0            0           5m24s
deployment.apps/secret-service          0/1     0            0           5m24s
deployment.apps/shipyard-controller     0/1     0            0           5m24s
deployment.apps/statistics-service      0/1     0            0           5m24s
deployment.apps/webhook-service         0/1     0            0           5m24s
```

And some debug information from replicaset controller logs:
`Warning  FailedCreate  87s (x19 over 12m)  replicaset-controller  Error creating: pods "api-gateway-nginx-796446f658-" is forbidden: unable to validate against any security context constraint`

From my point of view we are missing  roles, cluster roles, scc and so on.
