### ISSUE TITLE
Able to `trigger delivery` with incorrect/non-existing service name

### ISSUE THREAD

**Issue by warber** [keptn/keptn#6288]
When triggering a sequence e.g. `keptn trigger delivery --project my-project --service my-misspelled-service ...` keptn validates the existence of project `my-project` but is **not** checking whether service `my-misspelled-service` was created.

**To Reproduce**
Trigger a sequence (e.g. delivery) with a service name for which no service was created.

**Expected behavior**
The sequence is not launched.
The user is presented with an error message like it is the case for non-existing projects.

**Current behavior**
The sequence is launched but fails later on, e.g. when the helm service wants to deploy the artifact for the service.

**Comment by odubajDT** [comment]
Does the same problem happen also when triggering evaluation?

**Comment by odubajDT** [comment]
@warber is the problem present only when using CLI or via API as well ?
