### ISSUE TITLE
Show secret scope and keys in overview table

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#6296]
### Use case

*Current screen:*

![image](https://user-images.githubusercontent.com/729071/145000825-07835ba8-1000-4821-a8c6-65a3366b70b0.png)

As a user, I would like to see the specified scope of a secret and the keys in the secret after creating a secret:

![image](https://user-images.githubusercontent.com/729071/145000700-771d53f3-61da-470c-a6d0-965b62aa8e7f.png)

**Details:**
- Scope: Single value
- Keys: List of values
- The GET /secrets endpoint provides this information
```
{
  "Secrets": [
    {
      "name": "slack-secret",
      "scope": "keptn-webhook-service",
      "keys": [
        "webhook-identifier"
      ]
    }
  ]
}
```

### Definition of Done: 
- [ ] UI test cover the updated table
- [ ] Feature is implemented
- [ ] Screenshots in docs are updated (if needed)

**Comment by lucasclerissepro** [comment]
Would be happy to help with that!
