### ISSUE TITLE
Bridge: warning for missing upstream

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#6307]
## Action Item 

The dashboard should change how it reports projects without an upstream. The message should be changed to:
```
Keptn will not support a project without Git upstream repository. <Set the Git upstream of your project>.
```

## Acceptance Criteria

- [ ] Message correctly displayed 
- [ ] Icon is changed from ℹ️ to⚠️

## DoD

- [ ] Acceptance Criteria are met

**Comment by laneli** [comment]
+ additional: Change it on settings page for Git settings
[Uploading... image.png]
