### ISSUE TITLE
YAML I/O: Output file corruption when input strings contain spaces

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/keptn#6339]
It is a follow-up to https://github.com/keptn/keptn.github.io/issues/984 and https://github.com/keptn-contrib/prometheus-service/issues/228 . It seems that the Keptn core components do not properly handle input strings with spaces in some cases. In the referenced issue "< 10" in the input yaml should have been passed without modification to output, but actually it led to a corrupted output like this one:

```
   expr: promhttp_metric_handler_requests_total{code!="200",job="helloservice-podtatohead-hardening"}[180s]>
      10
```

**Environment**

* Client OS (e.g., Linux, macOS, Windows): WSL 2
* Keptn Version (`keptn version`): 0.11.2
* Kubernetes Cloud Provider (e.g., GKE, AKS): N/A
* Kubernetes version (`kubectl version`): k3d 4.4.4

**Affected Component**

* [ ] Approval
* [ ] Bridge
* [ ] CLI
* [ ] Datastore
* [x] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [x] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**

**To Reproduce**

Follow the quickstart guide before the https://github.com/keptn/examples/pull/215 fix

**Expected behavior**
If a string with space is passed, this string still reaches the output YAML as a single string

**Current behavior**
YAML corruption

**Screenshots**

**Additional context**

**Comment by thisthat** [comment]
The code already takes care of removing spaces: https://github.com/keptn/keptn/blob/0.11.x/lighthouse-service/event_handler/evaluate_sli_handler.go#L507 
I don't think this is a Keptn problem.
