### ISSUE TITLE
CLI: Add the possibility to connect through a proxy server

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#6343]
## Action Item

The CLI should provide a general `--proxy` flag that accepts an endpoint in the form of `http[s]://[user:password@]proxyhost[:port]`. The proxy value should be stored locally and used at each request to Keptn. 

## Acceptance Criteria

- [ ] The proxy value is stored locally if used in the `auth` cmd
- [ ] If a new `auth` cmd is performed, it will overwrite the previous value for the proxy (removing it if none it is specified)
- [ ] If a proxy value is configured, each CLI request pass through the configured proxy

## DoD 

- [ ] Unit tests

**Comment by bacherfl** [comment]
this was luckily already working by making use of the `HTTP_PROXY`/`HTTPS_PROXY` environment variables. The following PR extends the CLI documentation with a section on how to make use of these env vars: https://github.com/keptn/keptn.github.io/pull/1018
