### ISSUE TITLE
Bridge OOM with ~30 evaluations of a few hundred metrics each

### ISSUE THREAD

**Issue by eostermueller** [keptn/keptn#6358]
**Environment**
The Keptn "dev" environment, aka "sre ocp"

* Client OS (e.g., Linux, macOS, Windows):  linux
* Keptn Version (`keptn version`): 0.9.2
* Kubernetes Cloud Provider (e.g., GKE, AKS):  on prem OpenShift
* Kubernetes version (`kubectl version`):
oc v3.11.439
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://sreocp.fisdev.local:443
openshift v3.11.439
kubernetes v1.11.0+d4cacc0

**Affected Component**

* [ ] Approval
* [X ] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**
The Bridge pod got OpenShift OOM error and restarted.

**To Reproduce**
a. Create about 200-300 SLIs/SLOs
b. Trigger 30 evaluations
c. Browse around the Bridge UI, displaying the entire red-green heap map, selecting different evaluation dates.

We saw the error -- sorry, didn't get a screenshot, in the OpenShift Events console for the Bridge...or perhaps was it the Log -- not sure.

**Expected behavior**
We were expecting that default Bridge deployment memory max would be large enough to process this much data without OOM killing.

**Current behavior**
OOM will not happen because larger memory foot print is specified in the default Bridge deployment Yaml

All the logs in the following file were captured using our NEW memory settings in the bridge deployment yaml:
`          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 25m
              memory: 128Mi
`
It would be acceptable if the above memory parameters were used as default for the Bridge.
The following data was captured to provide a general idea of the size of all data processed that caused the OOM with the Keptn default RAM settings.

[keptn-oom.zip](https://github.com/keptn/keptn/files/7715322/keptn-oom.zip)

**Comment by johannes-b** [comment]
I just looked up the current settings: 


Pod | Container | Memory (requested) | CPU (requested) | Memory (limit) | CPU (limit) | Images
-- | -- | -- | -- | -- | -- | --
bridge | bridge | 64Mi | 25m | 128Mi | 200m | docker.io/keptn/bridge2:0.11.2
