### ISSUE TITLE
[Security] Workflow CI.yml is using vulnerable action marocchino/sticky-pull-request-comment

### ISSUE THREAD

**Issue by akulpillai** [keptn/keptn#6402]
The workflow CI.yml is referencing action marocchino/sticky-pull-request-comment using references v2.1.0. However this reference is missing the commit [6df066128765d68c4bb046620d9d3b16da22c974](https://github.com/marocchino/sticky-pull-request-comment/commits/6df066128765d68c4bb046620d9d3b16da22c974) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by mowies** [comment]
Thank you for bringing this to our attention. We are already using `v2.2.0` of the action.
