### ISSUE TITLE
Refactor CI Workflow prepare step - use actions/workflows of keptn/gh-automation

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#6421]
**Depends on https://github.com/keptn/gh-automation/pull/10**

The code from the prepare step is used in Keptn, `keptn-contrib/*-service` and `keptn-sandbox/*-service` and is being merged into keptn/gh-automation - see https://github.com/keptn/gh-automation/pull/10

We should take action and refactor .github/workflows/CI.yml, mainly the `prepare_ci_run` step, to make use of the new re-usable workflow, e.g.:
Change
https://github.com/keptn/keptn/blob/e5e508e08dcba5d2c99d442c5a1beb406e0c16d5/.github/workflows/CI.yml#L166-L214

to
```
  prepare_ci_run:
    name: Prepare CI Run
    uses: keptn/gh-automation/.github/workflows/prepare-ci.yml@feat/prepare_ci
```

**Note**:
Some steps in `.github/workflows/CI.yml` differ, e.g., 
https://github.com/keptn/keptn/blob/e5e508e08dcba5d2c99d442c5a1beb406e0c16d5/.github/workflows/CI.yml#L199-L208

and
https://github.com/keptn/keptn/blob/e5e508e08dcba5d2c99d442c5a1beb406e0c16d5/.github/workflows/CI.yml#L147-L164

Still, with the aforementioned reusable workflow the code in CI.yml should be reduced by another 50 lines or so.

# Definition of Done
- [ ] Check if this is possible
- [ ] CI.yml uses re-usable workflow keptn/gh-automation/.workflows/prepare-ci.yml

**Comment by thisthat** [comment]
Let's first check if this is possible without increasing the complexity of the keptn/keptn pipeline.
