### ISSUE TITLE
Remove mandatory image parameter for keptn trigger delivery to support common values.yaml files

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#6446]
**Is your feature request related to a problem? Please describe.**
The current implementation of keptn trigger delivery requires a user to pass in the image parameter. This image parameter will be passed in the CloudEvent for the .triggered event in the configuration section. Here is an example snippet when executing: `keptn trigger delivery ... --image=registry/imagename--tag=3.0.1`

```
{
  "data": {
    "configurationChange": {
      "values": {
        "image": "registry/imagename:3.0.1"
      }
    },
   ...
  },
 ...
  "source": "https://github.com/keptn/keptn/cli#configuration-change",
  "type": "sh.keptn.event.staging.delivery.triggered",
}
```

In the current implementation the values object will be taken by the helm service and will be applied to the values.yaml file in the configuration repo. While this is great it forces users to have a single ìmage` value in their values.yaml. In several helm charts that we have seen recently the values yaml file however looks something like this:
```
image:
  repository: registry/imagename
  tag: 3.0.1
  imagePullPolicy: always
  ...
```

The current implementation of the keptn cli for trigger delivery doesnt allow to have a values.yaml with the above structure. This is why this issue suggests to make the image not mandatory or even remove it completely and rely on the optional --values parameter that allows a user to pass in any values. 

**Describe the solution you'd like**
To extend the above example - here is how a changed behavior of the keptn cli could look look
`keptn trigger delivery ... --values image.repository=registry/imagename,image.tag=3.0.1,image.imagePullPolicy=always`

This would translate into the following CloudEvent

```
{
  "data": {
    "configurationChange": {
      "values": {
        "image": {
          "repository": "myregistry/myimage",
          "tag": "3.01",
          "imagePullPolicy": "always"
        }      
       }
    },
   ...
  },
 ...
  "source": "https://github.com/keptn/keptn/cli#configuration-change",
  "type": "sh.keptn.event.staging.delivery.triggered",
}
```

**Additional context**
This issue was brought up in a conversation with some of the Keptn Users such as Diego Braga from Kiratech who ran into this issue. The workarounds are either
a) adapt their values.yaml
b) not use the keptn trigger delivery but keptn trigger event and passing an event.yaml with the correct configurationChange object

**Comment by thschue** [comment]
+1 

I'd propose that there could be a defined placeholder for the version in the values file and keptn would be able to replace this. Currently, there's a mixup between keptn functionality (the version used in the configuration change data is also used in other keptn services) and the logic to change values files.

**Comment by christian-kreuzberger-dtx** [comment]
also +1 on the `--values` proposal by Andi.

Both, the Keptn CLI aswell as the core services (shipyard-controller, Bridge, ...) should be artifact agnostic. 

Whether `--values` has the meaning of "helm values" or something else (e.g., patching a CRD for argo) is up for the dedicated deployment service to decide, not Keptn.

IMO we should provide some best practices, e.g.:

* `--values image.repository=registry/imagename,image.tag=3.0.1` is the best practice for deploying containers

Other things that might also work well with this approach (if the deployment service implements it):

* `--values chart=https://github.com/keptn/keptn/releases/download/0.11.4/keptn-0.11.4.tgz` for deploying a helm chart (`helm upgrade ${SERVICE} ${.values.chart}`)

**Comment by PatrikSteuer** [comment]
facing the same issue, e.g. with the[ OTEL collector helm chart](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/values.yaml#L86-L91).
