### ISSUE TITLE
Use logging library for bridge server

### ISSUE THREAD

**Issue by Kirdock** [keptn/keptn#6531]
At the moment the bridge server just logs everything with the console. This should be replaced with a proper logging library.
This will also allow us to hide some log levels, which is useful for testing. Then info logs on startup or expected error logs do not pollute the test log and we can add some debug messages which aren't included in production.

# Acceptance criteria
- [ ] Implement a simple log class to do it
- [ ] Replace current logs with the library.
- [ ] Introduce a new environment variable to determine the log level and set the default level to `info` or `warn`.

## Open questions:
- Should the log only be written to the console or also to a file? Only on console for the moment

**Comment by thisthat** [comment]
Check if the Component Logger that I introduced is enough or a new library is necessary
