### ISSUE TITLE
go-utils: create unit tests for pkg/api/utils

### ISSUE THREAD

**Issue by odubajDT** [keptn/keptn#6561]
There is very poor test coverage for pkg/api/utils in keptn/go-utils. There is a need to add multiple unit tests to check the correct functionality of the code.

## DoD

- [ ] Remove code duplication if any
- [ ] Improve testing coverage

The code coverage report will be done in a follow-up ticket TBD.

**Comment by thisthat** [comment]
Go-utils received a major overhaul and this ticket is not needed anymore
