### ISSUE TITLE
Re-run failed sequence execution

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#6589]
### Use case

As a user, I have a failed sequence and would like to run the same execution again. 

#### Workaround are:

* creating fake commits that start a CI which then calls the Keptn API
* sending a sequence triggered event manually to the Keptn API 

### Details

More details on that topic can be found here: https://github.com/keptn/keptn/discussions/6588

Not evaluated yet, but re-running a sequence on level 2 (please see discussion) can help Keptn users most. Basically, the idea is that a failed sequence execution can be re-run within the same context and stage. For example, when a sequence failed, e.g., `delivery`, a `Re-run` button appears the user with execution permissions can click: 

![image](https://user-images.githubusercontent.com/729071/149490288-03319bce-7e90-4f60-990c-652dc8cda63e.png) 

Afterwards, the new sequence is started and shown below: 

![image](https://user-images.githubusercontent.com/729071/149493586-48033b6e-4efc-4015-87c2-889216290109.png)

* Technically, sending the sequence event from the `delivery` allows re-running the sequence: 
![image](https://user-images.githubusercontent.com/729071/149493854-6d5f3bed-8d87-4794-af13-dd1d5caeb2a3.png)

### Definition of Done
- [ ] FF for this features
- [ ] Show a `Re-run` icon and label for a failed sequence
- [ ] When clicking the icon, a sequence execution gets triggered in the same context/stage
- [ ] The result of the last execution overrides the result from the others.

**Comment by thisthat** [comment]
Question: should the `re-run` reproduce the original sequence using the same resources or should it fetch the latest versions?

**Comment by johannes-b** [comment]
This `re-run` has to use the same resources. I assume that we are supporting this by having the resource-service aware of the git commit.

**Comment by thisthat** [comment]
Questions: 
1. is the rerun button shown only for finished items? 
2. is the pause/abort buttons available?

**Comment by thisthat** [comment]
The team agreed to provide a mockup application|figma to showcase possible UX implementations
