### ISSUE TITLE
When upgrading to Keptn 0.12 the color schema changes in Bridge

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#6614]
**Affected Component**

* [ ] Approval
* [x] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**

![image](https://user-images.githubusercontent.com/729071/149939212-f5397382-ce2b-4a4d-81ca-d348cee7864d.png)

* As shown in the screenshot, the color schema has changed to turquoise-ish. 
* Additionally, the loading icon is difficult to see: 

![image](https://user-images.githubusercontent.com/729071/149940079-36cd52ec-27d3-469e-ad37-925582526832.png)

**To Reproduce**
* I just upgraded to Keptn 0.12 using `keptn upgrade`

**Expected behavior**
* I want to have the blue color schema I was used to.

**Comment by ermin-muratovic** [comment]
The old stylesheet is cached in the browser. After clearing the cache this is fixed.
