### ISSUE TITLE
Update docs with new API token secret feature

### ISSUE THREAD

**Issue by mowies** [keptn/keptn#6623]
The docs need to be updated to include the feature from this PR: https://github.com/keptn/keptn/pull/6312
probably this page: https://keptn.sh/docs/0.13.x/operate/api_token/

**Comment by Im5tu** [comment]
I'll be away this weekend, but so if there's no a PR by the end of next week, please ping me on the Slack and remind me (unless someone beats me to the docs obviously :))

**Comment by thisthat** [comment]
Thank you @Im5tu for your help! I am assigning this ticket to you then :)

**Comment by mowies** [comment]
I took this issue over and it's already done in keptn/keptn.github.io#1054
