### ISSUE TITLE
Better visualization of failed evaluations based on key SLI

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#6639]
When defining SLOs including one that is a "key" SLO it can be that you reach a high score in your evaluation - yet the evaluation fails. In the bridge we are currently not displaying this information so that the user understands that the reason why the evaluation failed was because of a key SLI.

Here is a screenshot. The total score is 88 which is greater than 75 - yet - the result is fail. The reason why its fail is because the "Security Vulnerability - High" is a key SLI and it is violated

![image](https://user-images.githubusercontent.com/675886/150294946-0508634a-9a5f-4620-9aef-6e080c73b56e.png)

For the end user it would make more sense to do something like this
1: say "Total Score 85 but result fails because of at least one violated Key SLI"
2: Better highlight the failed Key SLI in the table - right now it is bold - but - I dont see that this is actually a violated

## DoD 

- [x] The message should say `{n} key SLI(s) failed`
- [x] Add UI tests

**Comment by ermin-muratovic** [comment]
This got already better, see #8250 

![image](https://user-images.githubusercontent.com/6098219/178727239-2ef0fb65-2ebb-4879-b46d-7cdc467f7525.png)

But we could still improve it to provide more details like `{n} key SLI(s) failed`
