### ISSUE TITLE
CLI command `keptn upgrade project` broken

### ISSUE THREAD

**Issue by r3pli** [keptn/keptn#6648]
**Environment**

* Client OS (e.g., Linux, macOS, Windows): Ubuntu Linux 21.04
* Keptn Version (`keptn version`): 0.12.0
* Kubernetes Cloud Provider (e.g., GKE, AKS): GKE
* Kubernetes version (`kubectl version`): v1.21.1

**Affected Component**

* [ ] Approval
* [ ] Bridge
* [x] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**
CLI command `keptn upgrade project` seems to be broken / seems to be overwritten by `keptn upgrade`

**To Reproduce**
When trying to execute `keptn upgrade project PROJECTNAME --shipyard` keptn complains `Error: unknown flag: --shipyard`
When trying to execute `keptn upgrade project PROJECTNAME` keptn responses with 

```
Keptn CLI and Keptn cluster version are already on the latest version ( 0.12.0 )! 
Error: Unable to upgrade due to the aforementioned error
```

**Expected behavior**
Executing the command above should upgrade the shipyard file to new / current spec.

**Current behavior**
Currently it seems that `keptn upgrade` command is triggered

**Comment by thisthat** [comment]
Hi @r3pli , in #5992 we eliminated old deprecated commands in the CLI. `keptn upgrade project` was one of these.

**Comment by r3pli** [comment]
Hi @thisthat thanks for clarification. Totally agree that CLI should return an error then. Is there any command I could use to achieve the same? Upgrading shipyard via command was very helpful to me.

**Comment by thisthat** [comment]
@r3pli unfortunately no with Keptn 0.12. We stop the support for version 1.x of the Shipyard file since Keptn 0.8.x.
As a workaround, I can suggest using the CLI for Keptn 0.11. 
What is your use case for requiring this command?

**Comment by r3pli** [comment]
Nothing really special or urgent. My current use case is that I double check shipyard files within github actions if they have the latest spec, if not I update them with this command. But I'm really sure that I can change these actions and solve it another way :)

**Comment by thisthat** [comment]
I will close this ticket and open a follow-up for addressing the commands with additional unsupported parameters.
Thank you for your help @r3pli :)

**Comment by thisthat** [comment]
The team agreed on tackle #6657 as bug. So I am reopening this issue
