### ISSUE TITLE
Core: Clean up legacy code

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#6650]
## Technical Details

Keptn still has some legacy code to support Keptn 0.7.x that we should get rid of.
The code can be found at https://github.com/keptn/keptn/blob/fbaf0f0b364f1c20c3303ffdba81b7465421ab12/mongodb-datastore/db/mongodb_event_repo.go#L634

## Acceptance Criteria

- [ ] Simplify the query to support only `.triggered` events (which we use from Keptn >0.8.x)

## DoD 

- [ ] Adapt existing Unit Tests
- [ ] Adapt existing Integration Tests

**Comment by bacherfl** [comment]
https://github.com/keptn/keptn/pull/6612 can be used as a reference

**Comment by mowies** [comment]
There is some more legacy code in the nginx config: https://github.com/keptn/keptn/blob/master/installer/manifests/keptn/charts/control-plane/templates/api-gateway-nginx.yaml#L268-L270
