### ISSUE TITLE
Extend Webhook Payload placeholders to reference full Cloud Event Payload

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#6661]
Webhooks are great but are currently limited with the way placeholders for data elements of the Cloud Events are provided. Currently we can only reference a specific element, e.g: `{{ .data.evaluation.result }}` - while this is create it means we need to put in a lot of those placeholders for a set of data elements we want to pass to the target webhook.
In a discussion we had on the Keptn Slack channel the idea was brought up to even allow referencing the whole Cloud Event payload with e.g: `{{ . }}`  - this would allow a user to pass the complete cloud automation event payload to an external tool for further processing

This feature enhancement would therefore make webhook integrations more flexible as it eliminates the need to reference all data elements that should be passed to the webhook individually.

Example Webhook Payload for e.g: passing content to an external ticketing tool (Jira, ...)
```
payload={
  "source": "keptn",
  "event" : "{{ .type }}",
  "fullKeptnCloudEvent" : "{{ . }}"
}
```

For reference - here is the Slack Conversation Link: https://keptn.slack.com/archives/CNRCGFU3U/p1642781849077200

**Comment by christian-kreuzberger-dtx** [comment]
As commented on Slack, it seems that from a techincal standpoint it's not trivial, but doable.

Something like this could work:
```
payload={
  "source": "keptn",
  "event" : "{{ .type }}",
  "fullKeptnCloudEvent" : {{ toJson . }}
}
```

**Comment by robertjahn** [comment]
Just another idea to throw out there.....
![image](https://user-images.githubusercontent.com/24907089/152557537-916e63c1-1627-4421-8f62-2964e78fea89.png)
