### ISSUE TITLE
Show service and time stamp on sequence details page

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#6676]
### Use case

As a user, I would like to see the service name and the timestamp also on the *details* page of a sequence execution. 

![image](https://user-images.githubusercontent.com/729071/158127740-e58ce329-e565-495f-981f-604617638cdb.png)

#### Details

* The service name, e.g. `of carts` is inserted between the *sequence name*  and *status*. -> `delivery of carts succeeded`
* If the image is available, display it `deliver of carts:0.13.3. succeeded`. If not, then just the service name. 
* The start time and duration (as shown in the sequence tile) is displayed on the details page below the **Context**

### Definition of Done
- UI tests

**Comment by CIPHERTron** [comment]
I would like to work on this issue. @johannes-b could you please assign me? Thanks! :)

**Comment by eyskim** [comment]
Hi @johannes-b, I've created a PR with the requested changes and have added you as a reviewer. Lmk what you think and thanks!
