### ISSUE TITLE
Research compatibility with resource-service

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#6684]
## Action Item

The goal of this research is to verify the compatibility of the bridge with the new resource-service. 
Please, document as a comment to this ticket what does not work out of the box.

**Comment by Kirdock** [comment]
Using keptn 0.14.1 and resource-service 0.14.1

Found incompatibilities:
- Deleting a webhook is not possible anymore
`DELETE /project/{projectName}/resource/{resourceURI}`
`DELETE /project/{projectName}/stage/{stageName}/resource/{resourceURI}`
`DELETE /project/{projectName}/stage/{stageName}/service/{serviceName}/resource/{resourceURI}`
Previously the resourceURI was double escaped with `webhook%252Fwebhook.yaml`, but seems like this isn't working anymore. The GET endpoints seem to work.
