### ISSUE TITLE
Angular 13: Use HttpContextToken to make handling of special case errors easier

### ISSUE THREAD

**Issue by laneli** [keptn/keptn#6702]
For https://github.com/keptn/keptn/issues/6297 a special case workaround had to be introduced. If we would make use of the HttpContextToken (https://angular.io/guide/http#creating-a-context-token) we could handle such cases in a more generalized way.

The prequisite for that is the update to Angular 13, as this is only supported > 12.

My suggestion would be, if special errors are needed to have it with a Bypass code.
* Set the BYPASS_CODE => 409 for the request.
* In Interceptor: Check if the token is set and if the error code matches

This can be handy for i18n.

## DoD 

- Introduce the bypass
- Remove the workaround of #6297
- Unit tests

## Dependencies

- #6731

**Comment by thisthat** [comment]
This tickets depends on Barista to be updated to Angular 13
