### ISSUE TITLE
Bridge - Upgrade to Angular 12 or 13

### ISSUE THREAD

**Issue by laneli** [keptn/keptn#6731]
Upgrade to Angular 12 or 13 (based on the barista components support) to resolve old dependencies like Barista and make use of HttpContextToken as proposed in:
https://github.com/keptn/keptn/issues/6702

https://update.angular.io/?l=3&v=11.0-12.0

https://update.angular.io/?l=3&v=12.0-13.0

**Comment by mowies** [comment]
I would suggest to also look at the blocked/on-hold renovate PRs [here](https://github.com/keptn/keptn/issues/6173) regarding updates in the bridge for NodeJS, Prettier, TypeScript etc.
Many of them are blocked by an upgrade of Angular and could probably be bumped together with this ticket.
