### ISSUE TITLE
Bridge: The webhook secret selector does not collapse once you expand it

### ISSUE THREAD

**Issue by robertjahn** [keptn/keptn#6772]
**Environment**

* Client OS (e.g., Linux, macOS, Windows): N/A
* Keptn Version (`keptn version`): 0.10
* Kubernetes Cloud Provider (e.g., GKE, AKS): N/A
* Kubernetes version (`kubectl version`): N/A

**Affected Component**

* [ ] Approval
* [ X] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**

Here is expanded secret. Once open it can't be closed.
![image](https://user-images.githubusercontent.com/24907089/152464480-8f201a68-de3f-4feb-90a8-d12292e25408.png)

**To Reproduce**

1. Add a secret for webhooks
2. Add a new webhook subscription
3. click any of the  "key" icons to show the secret selector
4. expand a secret
5. try to collapse the selected secret

**Expected behavior**

the selected secret should collapse
![image](https://user-images.githubusercontent.com/24907089/152464669-4a03f88f-a127-43b5-b815-a4cd8a5c0dbb.png)

**Current behavior**

**Screenshots**

**Additional context**

**Comment by thisthat** [comment]
I tried to replicate this in Keptn 0.12. The secret gets collapsed correctly.
