### ISSUE TITLE
Jmeter-service sends two sh.keptn.event.test.finished events when the endpoint is not reachable

### ISSUE THREAD

**Issue by pchila** [keptn/keptn#6778]
Your issue may already be reported! Please search on the [issue tracker](https://github.com/keptn/keptn/issues) before creating a new one.

**Environment**

* Client OS (e.g., Linux, macOS, Windows): Linux
* Keptn Version (`keptn version`): 0.12.0
* Kubernetes Cloud Provider (e.g., GKE, AKS): GKE
* Kubernetes version (`kubectl version`): 1.21.6-gke.1500

**Affected Component**

* [ ] Approval
* [ ] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [x] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**

When triggering test for a deployment that is not reachable, jmeter-service sends the `.finished` event twice:
- the first one has result `fail` and message `Jmeter-service cannot reach URL fooservice: operation unsuccessful after 3 retry` 
- the second one has result `succeeded` and message `Tests for functional with status = true. Project: pchilafoobar4, Service: fooservice, Stage: dev, TestStrategy: functional, Context: 3bad94fb-5b84-41f2-930c-b5ed51c0c376` (this is probably because no jmeter files are present for the stage).

**To Reproduce**

1. Trigger a functional test for endpoints that are not reachable and without any jmeter files
2. wait for the test task to finish

**Expected behavior**

There should be only one `sh.keptn.event.test.finished` generated.

**Current behavior**

We get 2 `finished` events, one for the reachability test and one for the task completion

**Screenshots**

![image](https://user-images.githubusercontent.com/96178987/152507013-d08baeff-fed4-4081-b7e9-da1c641543b0.png)

**Additional context**

First `finished event`

```
{
  "data": {
    "labels": {
      "buildId": "20220204.5",
      "runby": "Paolo Chila"
    },
    "message": "Jmeter-service cannot reach URL fooservice: operation unsuccessful after 3 retry",
    "project": "pchilafoobar4",
    "result": "fail",
    "service": "fooservice",
    "stage": "dev",
    "status": "succeeded",
    "test": {
      "end": "2022-02-04T09:03:33.703Z",
      "gitCommit": "",
      "start": "2022-02-04T09:03:18.195Z"
    }
  },
  "id": "5d021743-bfc5-4e4a-82b6-108f2718faf1",
  "source": "jmeter-service",
  "specversion": "1.0",
  "time": "2022-02-04T09:03:33.753Z",
  "type": "sh.keptn.event.test.finished",
  "shkeptncontext": "3bad94fb-5b84-41f2-930c-b5ed51c0c376",
  "shkeptnspecversion": "0.2.3",
  "triggeredid": "43ddf634-1524-48f6-82b5-630880a9dc54"
}
```

Second event:
```
{
  "data": {
    "labels": {
      "buildId": "20220204.5",
      "runby": "Paolo Chila"
    },
    "message": "Tests for functional with status = true. Project: pchilafoobar4, Service: fooservice, Stage: dev, TestStrategy: functional, Context: 3bad94fb-5b84-41f2-930c-b5ed51c0c376",
    "project": "pchilafoobar4",
    "result": "pass",
    "service": "fooservice",
    "stage": "dev",
    "status": "succeeded",
    "test": {
      "end": "2022-02-04T09:03:34.476Z",
      "gitCommit": "",
      "start": "2022-02-04T09:03:18.195Z"
    }
  },
  "id": "84a6ba77-8eea-4bec-b990-8df461a00c79",
  "source": "jmeter-service",
  "specversion": "1.0",
  "time": "2022-02-04T09:03:34.521Z",
  "type": "sh.keptn.event.test.finished",
  "shkeptncontext": "3bad94fb-5b84-41f2-930c-b5ed51c0c376",
  "shkeptnspecversion": "0.2.3",
  "triggeredid": "43ddf634-1524-48f6-82b5-630880a9dc54"
}
```

**Comment by odubajDT** [comment]
Hello @pchila, I see you are using Keptn version 0.12.0 and assume you are using all services at this version, are you please using the same version also for jmeter-service ?

Thank you

**Comment by pchila** [comment]
Yes jmeter service is installed on a remote execution plane:

```
helm ls -n keptn
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
helm-service    keptn           1               2022-02-03 12:07:48.836943727 +0100 CET deployed        helm-service-0.12.0     0.12.0     
jmeter-service  keptn           1               2022-02-03 12:09:14.511628866 +0100 CET deployed        jmeter-service-0.12.0   0.12.0    
```

**Comment by odubajDT** [comment]
Thank you for the quick reply! I will investigate the problem and keep you updated.

**Comment by odubajDT** [comment]
Hi @pchila I found the problem. Are you willing to test the fix on your environment?

**Comment by odubajDT** [comment]
It's on hub.docker.com. To pull it just use this command:

`docker pull keptn/jmeter-service:0.13.0-dev-PR-6786.202202071010`

Thanks in advance :)

**Comment by odubajDT** [comment]
Great, that is the expected behavior. Thank you for cooperation! :)
