### ISSUE TITLE
Improve consistency for "keptn configure monitoring" CloudEvents

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#6805]
While developing prometheus-service I noticed that there are different types of "configure monitoring" Cloud Events, e.g.:

```
keptn configure monitoring <monitoring-type> --project <project> --service <service>
```
sends a cloud event of type `sh.keptn.event.monitoring.configure`, and the CLI expects a cloud event of type `sh.keptn.event.configure-monitoring.finished` as a response.

https://github.com/keptn/keptn/blob/5ad04fadad24d06616880b3538a907cb1dcdfd46/cli/cmd/configure_monitoring.go#L78-L86

https://github.com/keptn/keptn/blob/5ad04fadad24d06616880b3538a907cb1dcdfd46/cli/cmd/configure_monitoring.go#L115-L119

# Spec

I guess everything is fine according to spec, at least we have specified `sh.keptn.event.monitoring.configure`:
https://github.com/keptn/spec/blob/master/cloudevents.md#monitoring

As a major difference to "normal" CloudEvents, the `monitoring.configure` CloudEvent does not have `Stage` property, so maybe that's the reason why it exists.

# Change Request

In my opinion it makes sense to streamline the CloudEvent(s), e.g.:
* `sh.keptn.event.monitoring.configure` -> `sh.keptn.event.configure-monitoring.triggered` (**Spec change**, **CLI implementation change**, **service implementation change**)
* Service needs to respond with  `sh.keptn.event.configure-monitoring.started` (**service implementation change**) and `sh.keptn.event.configure-monitoring.finished` (already there)

In addition, we should perform a clean-up of old/outdated structs and consts regarding the configure monitoring events in keptn/go-utils.

In addition to aligning this Cloud Event type, we get the benefit of knowing that a service has `.started` reacting on our `configure-monitoring` event, which should help user experience.

# Defintion of Done

TBD

**Comment by christian-kreuzberger-dtx** [comment]
Thanks for your comment @arthurpitman.

> Should multiple SLI providers be supported for a single project or service?

Yes, but it's not part of this RFE, and should not be blocking this RFE either.

> Should the event offer a way to remove monitoring?

This should be a separate event, in my opinion. Could be similar CLI command though. But also not blocking for this RFE.

**Comment by johannes-b** [comment]
This RFE is great because it enables us to integrate the `configure-monitoring` task into the sequence execution since it follows the default behavior. 

**Use-case**: I, as a DevOps engineer, provide an `initialization` sequence, which will be triggered to initialize *monitoring* for my stage/service. 

```
apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "shipyard-quality-gates"
spec:
  stages:
    - name: "production"
      sequences:

        - name: "initialization"
          tasks:
            - name: "configure-monitoring"
```
