### ISSUE TITLE
Bridge: Fix sequence waiting text

### ISSUE THREAD

**Issue by atharvkarajgi** [keptn/keptn#6829]
Your issue may already be reported! Please search on the [issue tracker](https://github.com/keptn/keptn/issues) before creating a new one.

**Environment**

* Client OS (e.g., Linux, macOS, Windows):
* Keptn Version (`keptn version`):
* Kubernetes Cloud Provider (e.g., GKE, AKS):
* Kubernetes version (`kubectl version`):

**Affected Component**

* [ ] Approval
* [x] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Webhook

**Describe the bug**
The tool currently says Sequence might be waiting for previous sequences to be finished. whereas it should as something like Sequence is waiting for previous sequences to finish. 

**Screenshots**

**Comment by Dynatrace-Adam-Gardner** [comment]
<img width="746" alt="image" src="https://user-images.githubusercontent.com/13639658/153359617-75444ca6-f8b0-4c33-a6b7-5689ec3d38db.png">

**Comment by thisthat** [comment]
At the moment, the Bridge has no clue if a sequence is really waiting for another to finish or not. Hence, the more loosely phrasing in this message. In https://github.com/keptn/keptn/issues/6823, we are changing the API to let external applications know the exact state of a sequence and we will adapt the message :)
