### ISSUE TITLE
Continuous Delivery: research Helm for blue/green

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#683]
We need to figure out, how to use Helm for blue/green deployment. 

Help:
- Design doc: [Is Helm the right way to go?](https://docs.google.com/document/d/1T8vLDWsbJa7Dxz5pfI1TUqpIBqxWbOK0aJnnl5J0-I4/edit?usp=sharing)
- Helm Subcharts Doc: [Tutorial](https://github.com/helm/helm/blob/master/docs/chart_template_guide/subcharts_and_globals.md)

**Comment by johannes-b** [comment]
[sockshop-umbrella.zip](https://github.com/keptn/keptn/files/3519648/sockshop-umbrella.zip)

**Comment by agrimmer** [comment]
### Multiple Chart Blue/Green

**Requirements**
- service manifest exists and has the `kind: service`. Furthermore, it has a `spec.selector.app` property
- deployment manifest exists and has the `kind: deployment`. Furthermore, it has `spec.selector.matchLabels.app` and `spec.template.metadata.labels.app properties`.
- _Convenience for traceability_: values.yaml exists and has a property `image`, which is used in the deployment.

**Service of user**
1. Validate requirements
1. Store in configuration-service
1. Update requirements.yaml
1. Update values.yaml

**Generated service**
1. Duplicate helm chart
1. Rename chart name in Chart.yaml
1. Take service.yaml and do the following steps:
  a. Create service-canary.yaml and change name to [xy]-canary
  b. Create service-primary.yaml and change name and selector to [xy]-primary
  c. Delete service.yaml
1. Take deployment.yaml and do the following steps:
   a. Rename into deployment-primary.yaml and change name, and app selectors to [xy]-primary
1. Create DestinationRule for canary and primary
1. Create Virtual service
1. Update requirements.yaml
1. Update values.yaml

### Stage Level
1. Create root Chart with project name
1. Create Requirements.yaml with empty dependencies
1. Create empty values.yaml
1. Create Istio Gateway in templates folder

**Comment by johannes-b** [comment]
Design doc containing a Comparions of keptn and Flagger showing the functionality of the helm-service: https://drive.google.com/open?id=1eRrKjkjcv-cGlNsAykMZbCjieykDc2Qp

**Comment by johannes-b** [comment]
Attached is the example used by flagger: 
[flagger-podinfo.zip](https://github.com/keptn/keptn/files/3519749/flagger-podinfo.zip)
