### ISSUE TITLE
Research: RBAC and new database for SSO related data

### ISSUE THREAD

**Issue by Kirdock** [keptn/keptn#6832]
#6689 uses MongoDB to store OAuth/OpenID related data. Currently, it is using the same database and user that is used by the core. The data should be saved in another database and a new user should be created that only has access to this database.

## Research
- [ ] How to create a new database is created on startup that is used by the Bridge for OAuth-related data?
- [ ] How to create a new user is created that only has access to this database (access to the Keptn database is not allowed)?
- [ ] Does the upgrade our MongoDB bitnami helm-charts to the latest versions solve our problems? Can we bind a specific user to a specific db?

**Comment by mowies** [comment]
This issue definitely requires some sort of initialization script to set up permissions for the users and databases.
Adding the users/databases is supported by newer versions of bitnami/mongodb but permission handle is not.
