### ISSUE TITLE
Webhook: Show more details in the logs shown on the uniform page

### ISSUE THREAD

**Issue by robertjahn** [keptn/keptn#6841]
**Is your feature request related to a problem? Please describe.**
When a webhook fails there is nothing in the uniform log to the  subscription and sequence where it failed. If you have multiple subscriptions this is difficult

**Describe the solution you'd like**
I would like the name and ideally a hyperlink to the subscription
I would like a hyperlink to the sequence

**Describe alternatives you've considered**
None.  One has to have access to service logs and try to figure it out.

**Additional context**
This is all your see now.
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/24907089/153500889-40787018-af52-4208-a72e-2daf813efa72.png">

**Comment by thisthat** [comment]
Idea from the team: update the log model (breaking change) to also allow an optional subscription id. The bridge can check, if this property is then set in the log entry, it could use it to link it to the subscription edit page.
