### ISSUE TITLE
Bridge: add support for labels at the task level

### ISSUE THREAD

**Issue by robertjahn** [keptn/keptn#6842]
**Is your feature request related to a problem? Please describe.**

Bridge labels are currently on the sequence-level, meaning that any labels sent back from the task finished event are displayed at every task triggered event that follows.

The proposal here is to the support labels on the task-level . In other words, just display the label on the task `started` or task `finished` step of a sequence that sent back the label

**Describe the solution you'd like**
A task `started` or task `finished` event sends back the label(s) in the task data block, e.g. task my-task:
```
data: {
  labels: { } < --- sequence level
  my-task: { 
    labels: { } < --- task level
  }
}
```

The Bridge should take a look into the event payload and if there is a label in .data.[task name].label then just display a label on the `started` or task `finished` step of a sequence that sent back the label.  The label would not be added to any other steps or tasks.

**Describe alternatives you've considered**
None

**Additional context**
here is a mock up of of two separate task finished events
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/24907089/153502263-f39a23d9-82da-4f40-8cde-61fb2de9ca40.png">

**Comment by thisthat** [comment]
Hi @robertjahn thank you for the suggestion. I think this is a great addition. However, I would suggest opening a [KEP](https://github.com/keptn/enhancement-proposals) since it requires substantial changes in the core-services, in the event specification, and shipyard definition.

**Comment by thisthat** [comment]
I am closing this issue
