### ISSUE TITLE
Bridge: Add more detailed error message for upstream git repo problems

### ISSUE THREAD

**Issue by robertjahn** [keptn/keptn#6843]
**Is your feature request related to a problem? Please describe.**
In the Bridge we have seen messages like `During the execution of a sequence  it gets error: could not retrieve shipyard: Could not retrieve shipyard.yaml for project demo: {"code":500,"message":"Could not check out branch"}` and with just this, we don't know what the root cause is.

**Describe the solution you'd like**
Have more details in the error message to help triage the problem. In this one use case the problem was the GIT Auth Token had expired.  So the the code would have to be reviewed to have more specific error messaging.

**Describe alternatives you've considered**
Had to have core developers research

**Additional context**
This error above was show in the sequence event, but here is another example where on the project setup page. 
<img width="570" alt="image" src="https://user-images.githubusercontent.com/24907089/153504568-841097b3-8135-4a2b-a49b-9709fc50c918.png">

**Comment by mehabhalodiya** [comment]
Hey @robertjahn @oleg-nenashev 
I am a newbie to this project and I would like to work on this.
Will you please let me know the location of the file inside `/bridge` directory?
Thanks.

**Comment by oleg-nenashev** [comment]
All of this code is within the Configuration Service codebase: https://github.com/keptn/keptn/tree/master/configuration-service . Search for the errands r message text for particular locations, there are multiple.of them

**Comment by thisthat** [comment]
Hi @mehabhalodiya, thanks for looking into this :) 
As an implementation note, I would discourage messages that are too specific since they could lead to SSRF attacks
