### ISSUE TITLE
keptn version outputs wrong version

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#6858]
**Environment**

* Client OS (e.g., Linux, macOS, Windows): Linux (Ubuntu 20.04)
* Keptn Version (`keptn version`): 0.12.0 on the CLI, 0.11.4 on the Kubernetes cluster
* Kubernetes Cloud Provider (e.g., GKE, AKS): Google Kubernetes Engine
* Kubernetes version (`kubectl version`): GKE 1.21.6

**Affected Component**

* [ ] Approval
* [ ] Bridge
* [x] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**

I was about to upgrade my 0.11.4 cluster to 0.12.0, and downloaded the latest CLI. The output of the CLI is weird when doing `keptn version`, as it indicates that I have both, version 0.11.4 and version 0.12.0 on my cluster:
![image](https://user-images.githubusercontent.com/56065213/153904677-02208187-d939-4fda-9a86-5cb0633455cd.png)

**To Reproduce**
What can I say... Install Keptn 0.11.4, then download 0.12.0 CLI, and run `keptn version`. I don't think it's as easy as that though...

**Expected behavior** vs. **Current behaviour**
I believe that the output is wrong:
```
Keptn CLI and Keptn cluster version are already on the latest version ( 0.12.0 )! 
```
It should probably show that CLI and cluster have a different version.

Also, the message
```
Kube context has been changed to gke_sai-research_europe-central2-c_keptn-ckr-dev
```
is appearing every time I run `keptn version`. This message was NOT appearing on Keptn 0.11.4, and I also have NOT changed my Kube Context in between.

**Screenshots**
Before upgrading, using Keptn 0.11.4 CLI, this was the output (and it was correct):
![image](https://user-images.githubusercontent.com/56065213/153905010-ba46dab2-d521-4758-bf2e-931fe676e7fc.png)

**Comment by odubajDT** [comment]
Hi @christian-kreuzberger-dtx can you please reproduce the problem about the changed context also with current master CLI ? I can reproduce it easily with CLI Keptn 0.12.0 as you described, but not with the current master, can you please double check this ?

Thanks.
