### ISSUE TITLE
Rounding evaluation score causes confusion on evaluation board

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#6890]
### Problem

When having an evaluation score of 89.69... it is still below the warning threshold of, e.g. 90, but due to rounding this value it looks like being exactly 90 and this violates the expression 90 < 90 shown below:

![issue](https://user-images.githubusercontent.com/729071/154294116-02bcb8d2-052c-4cd9-9585-0b043afe0839.png)

### Proposed fix

* Round the value to two decimals. Given the above example, this would be `89.68`

**Comment by ermin-muratovic** [comment]
The PR #6976 is rounding the number, so 69.9999999 as score will still result in 70. This needs to be changed, so that the decimals are just truncated.
