### ISSUE TITLE
Bridge: Hide "send finished event" buttons when the webhook subscription is for started and finished task events

### ISSUE THREAD

**Issue by robertjahn** [keptn/keptn#6892]
**Is your feature request related to a problem? Please describe.**
It is confusing and potential an issue if someone sets the "send finished event" true/false property for a webhook subscription on the started or finished task events.  

**Describe the solution you'd like**
Currently in keptn 0.12 bridge webhook subscription page, the "send finished event" radio buttons are shown with NO selection if the started or finished event it selected. 
<img width="737" alt="image" src="https://user-images.githubusercontent.com/24907089/154332181-49f91946-2e35-4729-a10e-bfd4a7d56d03.png">

The "send finished event" radio buttons should be shown only for triggered task events.
The "send finished event" radio buttons are OK to show with the default of "automatic" is fine to show as it works now.

**Describe alternatives you've considered**
None

**Additional context**
This Bridge web UI logic should be used once the "send started event" flag is added to keptn.

| UI element | display for task triggered event | display for task started event | display for task  finished event |
|------------|------------------|----------------|----------------|
| "send started event" radio buttons | YES | NO | YES |
| "send finished event" radio buttons | YES | NO | NO |

**Comment by thisthat** [comment]
Hi @robertjahn, the radio buttons are shown but they are disabled. They are enabled only if a user selects a triggered event. 
I'll mark this as UX and look for how to improve this.
