### ISSUE TITLE
Remediation sequence shows two `Labels`

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#6920]
### Use-case

When starting a remediation sequence, the Bridge shows two **Labels**

![image](https://user-images.githubusercontent.com/729071/154703039-9f3f36f5-3946-4574-835f-5c8f7ffdb134.png)

The event payload is:
```
{
  "data": {
    "labels": {
      "Problem URL": "xxxxxxxxxxxxx"
    },
    "problem": {
      "ImpactedEntities": [
        {
          "entity": "xxxxxxxxxxx",
          "name": "sockshop.carts.production",
          "type": "SERVICE"
        }
      ],

[...]


      "Tags": "[Environment]DT_RELEASE_PRODUCT:sockshop, keptn_service:carts, [Environment]DT_RELEASE_STAGE:production, keptn_project:sockshop, keptn_deployment:primary, podname:carts-primary-6cfc976787-rn4r2, keptn_stage:production",
      }
    },
    "project": "sockshop",
    "service": "carts",
    "stage": "production"
  },
  "id": "79f9ef26-36da-4707-92e0-933ca109d35c",
  "shkeptncontext": "34353134-3130-4932-b139-303537343036",
  "shkeptnspecversion": "0.2.3",
  "source": "dynatrace-service",
  "specversion": "1.0",
  "time": "2022-02-17T08:27:23.125Z",
  "type": "sh.keptn.event.production.remediation.triggered"
}
```

Given the above example, my assumption would be that we display `data.problem.tags` too. 

## Discussion

- Is my assumption correct? If so, we should not display tags under *Labels*.

**Comment by thisthat** [comment]
Hi @johannes-b, we indeed show two sets of labels. Namely, the following properties are used:
- `event.data.labels`
- `event.data.problem.ProblemDetails.tagsOfAffectedEntities`

**Comment by johannes-b** [comment]
Thanks for the comment. 
The `event.data.problem.ProblemDetails.tagsOfAffectedEntities` is a custom property that should not be supported this way. Hence I vote for removing it.

**Comment by afzal442** [comment]
hi there,
Is this related to removal of `div *ngIf="_event.data.problem?.ProblemDetails as problemDetails` section?
