### ISSUE TITLE
Lighthouse service does not include indicators when sending `get-sli.triggered` event

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#6921]
### Criticallity: high

* Quality gates don`t work

---

**Environment**

* Client OS (e.g., Linux, macOS, Windows):
* Keptn Version (`keptn version`): 0.13

**Affected Component**

* [ x ] Lighthouse-service

**Describe the bug**
* After upgrading to Keptn 0.13, the lighthouse-service does not add the `indicators` to the `get-sli.triggered` event.

Status quo:
```
{
  "data": {
    "deployment": "direct",
    "get-sli": {
      "end": "2022-02-18T14:48:33.501Z",
      "sliProvider": "dynatrace",
      "start": "2022-02-18T14:48:05.601Z"
    },
    "project": "sockshop",
    "service": "carts",
    "stage": "dev"
  },
  "gitcommitid": "a881b5b0c5f51a2f577bbcdaacef38ccbbbb7e56",
  "id": "8472e2dd-fe37-4062-b24f-53c7eef95049",
  "shkeptncontext": "1fc3497a-725f-4cc6-8ddc-e176bec524d3",
  "shkeptnspecversion": "0.2.4",
  "source": "lighthouse-service",
  "specversion": "1.0",
  "time": "2022-02-18T14:48:37.818Z",
  "type": "sh.keptn.event.get-sli.triggered"
}
```

In Keptn 0.12 it was:
```
{
  "data": {
    "deployment": "direct",
    "get-sli": {
      "end": "2022-02-16T16:04:48.194Z",
      "indicators": [
        "response_time_p95"
      ],
      "sliProvider": "dynatrace",
      "start": "2022-02-16T16:04:16.503Z"
    },
    "project": "sockshop",
    "service": "carts",
    "stage": "dev"
  },
  "id": "2ee55035-c1c7-490d-a9e9-2e0167de17a2",
  "shkeptncontext": "edfddfd5-4c9b-4fb1-a06c-439c6c626eb6",
  "shkeptnspecversion": "0.2.3",
  "source": "lighthouse-service",
  "specversion": "1.0",
  "time": "2022-02-16T16:04:52.520Z",
  "type": "sh.keptn.event.get-sli.triggered"
}
```

**To Reproduce**
* Run an evaluation step with Prometheus or Dynatrace as SLI-provider in use

**Expected behavior**
* The event couple of `evaluation` and `get-sli` works as expected; meaning that the lighthouse-service informs the SLI-provider about the indicators to fetch.

**Additional context**
* From a brief investigation, I would assume that the bug can be found here: https://github.com/keptn/keptn/blob/master/lighthouse-service/event_handler/start_evaluation_handler.go#L126 since the `indicators` parameter is neither returned by the function nor handed over via reference (call by reference).

**Comment by christian-kreuzberger-dtx** [comment]
Quick investigation:
In this PR #6567 the relevant code was touched, such that `indicators` are computed within the `computeObjectives` function. I think a pointer is missing here, I will give it a try.
