### ISSUE TITLE
Integration tests: Remove dependency to unleash service from self-healing test

### ISSUE THREAD

**Issue by bacherfl** [keptn/keptn#6929]
Right now, we are installing the unleash service during our self-healing integration test (See https://github.com/keptn/keptn/blob/f02cad5de1c584621504fdd4b3fe7bf4c19870e2/test/go-tests/test_selfhealing.go#L95) 

However, when testing Keptn core, we should not be dependent on a service from the Keptn-contrib org. Therefore, I suggest to directly send the events we would expect from an external service during the self healing use case. The same thing is already done during the quality gates integration test: See https://github.com/keptn/keptn/blob/f02cad5de1c584621504fdd4b3fe7bf4c19870e2/test/go-tests/test_qualitygate.go#L372 as a reference.

## DoD

- [ ] Switch out the unleash service
- [ ] Add additional tests
- [ ] Make sure every property has an assert to verify their correctness

**Comment by thisthat** [comment]
The tests has been moved to component tests
