### ISSUE TITLE
Release tasks fails with "Error when storing chart carts-generated of service carts in project sockshop"

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#6935]
**Environment**

* Keptn Version (`keptn version`): 0.13.0

**Affected Component**

* [x] Helm-service 0.13.0
* [x] Configuration-service 0.13.0 

**Describe the bug**

After upgrading to Keptn 0.13, the `release` task stopped working. I always get the error: `Error when storing chart carts-generated of service carts in project sockshop: `

![image](https://user-images.githubusercontent.com/729071/154951528-9d514e4b-e7ec-48c8-8e3c-afa2064314e7.png)

**To Reproduce**
* Run a delivery using `keptn trigger delivery --project=sockshop --service=carts --image=docker.io/keptnexamples/carts --taes/carts --tag=0.13.1`

**Expected behavior**
* The `release` task does an update of the generated chart and successfully finishes. 

**Current behavior**
* The `release` task fails with: `Error when storing chart carts-generated of service carts in project sockshop: `
* Interestingly, the update of the `carts-istio-virtualservice.yaml` did work:
![image](https://user-images.githubusercontent.com/729071/154952449-19ab9f15-1165-4968-874b-8aaa38502d13.png)
![image](https://user-images.githubusercontent.com/729071/154953059-b8fe63eb-65c9-4827-b9fe-4edbaf31d559.png)

* One aspect is **confusing me**. I cannot find the message `when storing chart` in the code of Keptn (neither configuration-service nor helm service). Hence, it is difficult to spot where the problem occurs in the code.

**Comment by johannes-b** [comment]
Suddenly, I got the problem also on a deployment task: 

![image](https://user-images.githubusercontent.com/729071/154957812-850b31e4-e70b-4008-bd6b-d379c50ddfc8.png)

**Comment by jonathanracine** [comment]
I can also confirm the same is happening for me. The only workaround I have so far is to restart the configuration-service pod and retry, however this produces inconsistent builds

**Comment by bacherfl** [comment]
@johannes-b @jonathanracine Thank you for reporting this. So far I haven't been able to reproduce this issue though. Can you confirm that this is still happening on your side? And if yes, can you please provide me with some logs of the configuration-service. Hopefully that will help to get to the root cause of this problem

**Comment by jonathanracine** [comment]
Hi @bacherfl  I can confirm this is still happening.

I have uploaded logs that might be relevant, if you need the full support archive I can also provide it
[api-gateway-nginx-855ffbbb46-7dsqd_log.txt](https://github.com/keptn/keptn/files/8116755/api-gateway-nginx-855ffbbb46-7dsqd_log.txt)
[bridge-c9988d9cd-q5wpw_log.txt](https://github.
[helm-service-766c79f8b-kdbd8_log.txt](https://github.com/keptn/keptn/files/8116763/helm-service-766c79f8b-kdbd8_log.txt)
com/keptn/keptn/files/8116761/bridge-c9988d9cd-q5wpw_log.txt)
[mongodb-datastore-5d876bd46d-shs4m_log.txt](https://github.com/keptn/keptn/files/8116770/mongodb-datastore-5d876bd46d-shs4m_log.txt)
[resource-service-b89f9f8df-kfsfw_log.txt](https://github.com/keptn/keptn/files/8116771/resource-service-b89f9f8df-kfsfw_log.txt)

**Comment by johannes-b** [comment]
Hello @jonathanracine, 

thanks to @bacherfl who has identified the problem. It is a too low timeout in the distributor. 
Florian has provided the fix already. If you cannot wait for 0.13.1 and would like to use it already, please exchange the image of the distributor with: `docker.io/keptndev/distributor:0.13.1-dev`

**Comment by DomineCore** [comment]
In 0.19.1 version, I still met this problem. @johannes-b
