### ISSUE TITLE
Keptn Installer: introduce deployment parameters to keptn helm chart (control-plane) to make resource limits/requests customisable

### ISSUE THREAD

**Issue by hubmat00** [keptn/keptn#6981]
# Problem:
We experience scalability issues with the api-gateway-nginx (control-plane chart) when running Keptn on K8s with the default Keptn Helm Charts. From time to time the liveness-probes fail resulting in triggered restarts, furthermore we experienced pod kills by OOM.

Our plan to overcome these issues would be to customise the resource limits/requests of pods to our individual demands. However, to change resource-definitions it currently demands manual intervention in the Keptn Helm Chart and leads to the problem that we can no longer relate/use the charts from the official Keptn Helm Repo (https://charts.keptn.sh/).

Keptn Version: 0.10.0

# Proposed fix:
The introduction of deployment parameters (with default values) would provide a generic way to make resource definitions customisable. As a reference implementation I suggest the bitnami charts that provide best-practices for helm chart templating:

* https://github.com/bitnami/charts/tree/master/bitnami/nginx/#nginx-deployment-parameters
* https://github.com/bitnami/charts/blob/master/bitnami/nginx/templates/deployment.yaml#L197

Currently we encounter this scalability issues on api-gateway-nginx, but I think it would make sense to introduce these deployment parameters (with current default values) to all containers.

I am open for feedback as well as for other solutions that help us to solve our issue!

## DoD

- Implement the suggestion with having the current values as default

**Comment by sarahhuber001** [comment]
I'm currently working on this issue.

**Comment by sarahhuber001** [comment]
@albertogdd is currently working on this issue.

**Comment by albertogdd** [comment]
As Sarah said, I'm currenlty working on this issue (see #7595, work in progress)
