### ISSUE TITLE
Keptn Installer: introduce deployment parameters to keptn helm chart (control-plane) to enable custom sidecar configurations

### ISSUE THREAD

**Issue by hubmat00** [keptn/keptn#6982]
**Is your feature request related to a problem? Please describe.**
We have the necessity to configure a custom sidecar container additionally to the keptn api-gateway-nginx container. The idea is to run a reverseproxy as a sidecar container independently of the already existent nginx-container within the same deployment of api-gateway-nginx.

In order to make this possible the current api-gateway-nginx.yaml of the Keptn Helm Chart (control-plane) needs some adjustments.

**Describe the solution you'd like**
The introduction of deployment parameters would enable such a custom sidecar injections in a generic way. Furthermore, to be fully flexible it is also necessary to introduce extra volumes (for mounting configmaps or secrets) that can be referenced by the sidecar. The bitnami nginx-charts provide a good reference implementation:

* sidecar: https://github.com/bitnami/charts/blob/master/bitnami/nginx/templates/deployment.yaml#L298
* extra volumes: https://github.com/bitnami/charts/blob/master/bitnami/nginx/templates/deployment.yaml#L323

This proposal has no incompatibilities within the current keptn helm charts but rather introduces a generic extension point to inject such sidecars or any other containers.

I am open for feedback as well as for other solutions!

**Comment by sarahhuber001** [comment]
I'm currently working on this issue.
