### ISSUE TITLE
Trigger sequence: Move custom sequences stage selection next to sequence selection

### ISSUE THREAD

**Issue by laneli** [keptn/keptn#6983]
Custom sequences are configured per stage and not globally in the shipyard.
Currently, the stage for a custom sequence is selected in the overview, like for delivery and evaluation. Then the sequence is selected in the next screen and the user can potentially select a sequence that is not available for the selected stage. The user can still trigger the sequence, and will get an error for the sequence execution in the sequences screen:

![image](https://user-images.githubusercontent.com/2674029/155509732-3be125e4-abe4-4ccd-aa00-ad60a2835b9c.png)

Proposal:
![image](https://user-images.githubusercontent.com/2674029/155670333-8a1adce6-bc42-45a2-99b7-d05175237329.png)

- [x] Return with the `/customSequences` endpoint the association between stage and sequence
- [x] Instead of the word custom show a select with the sequences for the selected stage.
- [x] If no stage is selected yet, disable the select.
- [ ] If the user selects a custom sequence, the stage dropdown is configured with the stages in which the selected sequence is defined. 
- [ ] If the user has both already selected and selects a different sequence, clear the stage dropdown menu and reset it to "Select..." 
- [ ] The preselected stage does not make any sense here - we cannot predict what the user will pick. Remove this functionality.

## DoD

- [x] UI tests need to be updated
- [x] Add and update existing unit tests

**Comment by christian-kreuzberger-dtx** [comment]
And I forgot to mention this:

Please make it possible to overwrite the sequence name, e.g.:
```
keptn trigger delivery --project=<project> --service=<service> --image=<image> --tag=<tag> [--sequence=<sequence>]
```

With the aforementioned shipyard-file, I would like to be able to call `delivery` sequence but specify `--sequence=delivery-direct`.

**Comment by johannes-b** [comment]
- [ ] I don't see it necessary to have this label: 

![image](https://user-images.githubusercontent.com/729071/160840756-c184ffb5-645a-42d7-b01d-b5af04e2f100.png)

- [ ] `Milli` and `Mirco` seconds are not needed: 

![image](https://user-images.githubusercontent.com/729071/160840982-f46cc68d-f4c0-4c95-a41c-123cc69fbeab.png)

- [ ] I find it confusing that the `Start at` changes from **left** to **right** depending on the selection:
  * ![image](https://user-images.githubusercontent.com/729071/160841299-204bd458-25e9-4d45-85db-560f9f0c6626.png)
  * ![image](https://user-images.githubusercontent.com/729071/160841391-ec8d9177-0a61-4740-8d58-e75219f3d706.png)
  * --> Proposal: Can we merge both options "Use timeframe" and "Use start / end time" into one form?

**Comment by johannes-b** [comment]
An idea to combine `User timeframe` and `Use start / end time` could be: 

![image](https://user-images.githubusercontent.com/729071/162777115-9bc899c6-57a2-473f-bf69-64802cca86fc.png)
