### ISSUE TITLE
Bridge overlay: Unify overlay modal to reduce code duplications

### ISSUE THREAD

**Issue by laneli** [keptn/keptn#6985]
With https://github.com/keptn/keptn/pull/6958 a new popup modal was introduced that works as a DateTime picker.
In the Bridge there is already the secret/data variable selection available as a popup modal.

With the introduction of the DateTime picker, code duplications were introduced, as the modals are opened basically the same way. For this PR, the duplications were already reduced by introducing an OverlayService that handles the common steps used for both modals.

The next step would be to unify it completely, and handle it in a similar manner to Angular Material dialog:
https://material.angular.io/components/dialog/overview
The solution would be to programmatically open the modal from the controller and pass the desired component and data to the component. This means discarding the directives.

The two components that are created as modals:
- ktb-tree-list-select.component.ts
- ktb-datetime-picker.component.ts

❓As we have Material as a dependency, would it make sense to directly use the dialog? But Material is strict in design and I don't know if it is possible to have the origin set to a button. I think the better approach is really to build our own solution that fits Keptn better.

## Acceptance Criteria

- [ ] Borrow the idea from material-ui to simplify our codebase
- [ ] Replace all popups with the new overlay implementation
- [ ] Sonarcloud warnings disappear 

## DoD

- [ ] Unit tests
- [ ] UI tests should not fail

**Comment by TannerGilbert** [comment]
This was already fixed by #8077, although the implementation is slightly different as described above.
