### ISSUE TITLE
Make use of nextPageKey instead of date for loading older sequences

### ISSUE THREAD

**Issue by laneli** [keptn/keptn#6988]
For getting older sequences we use a workaround that uses the date of the last sequence, to fetch older sequences:
```
  public loadOldSequences(project: Project, fromTime?: Date, oldSequence?: Sequence): void {
    if (project.sequences) {
      this.loadSequences(
        project,
        fromTime,
        new Date(project.sequences[project.sequences.length - 1].time),
        oldSequence
      );
    }
  }
```

The API is returning a `nextPageKey` with each request for `GET /controlPlane/sequence/{projectName}`.
It would be more reliable to make use of that, as it returns just no `nextPageKey` in case everything is already loaded.

**Comment by thisthat** [comment]
The nextPageKey is not stable for new items added to the list. Hence, we cannot use it for collecting data in chunks.
