### ISSUE TITLE
Selection of stage

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#7015]
### Acceptance Criteria

When clicking on the stage in the project overview screen:

![image](https://user-images.githubusercontent.com/729071/156009874-039532a9-40ec-4eea-a46e-31571ee6f00e.png)

the corresponding stage is already selected:

![image](https://user-images.githubusercontent.com/729071/156009779-98c89499-c0b6-4393-8702-01b006409d40.png)

#### Details

Right now, I just get to the environment screen and no stage is selected. 

## DoD 

- UI tests

**Comment by Kirdock** [comment]
I would change it to feature request because we have never had any additional parameters for the environment screen. So this is not a bug, it's a feature request.
