### ISSUE TITLE
Make it easier to do refresh of Keptn Bridge log data

### ISSUE THREAD

**Issue by robertjahn** [keptn/keptn#702]
**Is your feature request related to a problem? Please describe.**
In order to refresh the logs, I need to click search button and then click on the keptn context row again.  

**Describe the solution you'd like**
Add a refresh button or maybe allow me to click again on the keptn context row to refresh the log.

**Describe alternatives you've considered**
Only option is to search and click on row again.

**Additional context**

**Comment by dirkwall** [comment]
We'll start with the implementation of the next version of the bridge in December. Closing.
