### ISSUE TITLE
Expand keptn CLI trigger * to trigger any sequence?

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/keptn#7032]
### Discussed in https://github.com/keptn/keptn/discussions/4839

<div type='discussions-op-text'>

<sup>Originally posted by **Dynatrace-Adam-Gardner** August  6, 2021</sup>
Is it a good idea to expand the keptn CLI to trigger **any** sequence, not only `delivery` and `evaluation`</div>

**Comment by robertjahn** [comment]
Having this feature would simply what we have to do now. which is make a JSON file and use `keptn send event --file mysequence-triggered.json`.     I would like to see something like `keptn send event mysequence --project myproject`
