### ISSUE TITLE
Core: Limit the number of sequence queued in Shipyard-Controller

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#7033]
## User Story
As an operator, I would like to limit the number of sequences that the shipyard controller can queue.

## Technical details

The queue system was implemented in https://github.com/keptn/keptn/issues/3776

## Acceptance Criteria

- The maximum amount of sequences in a queue must be determined with the env var `MAX_QUEUE_SIZE` that is read from the helm value `shipyard-controller.maxQueueSize`.
- The env var `MAX_QUEUE_SIZE` can be configured via helm value and defaults to 15 per project.
- When a new sequence is triggered and the queue is full, then the shipyard controller returns a 429 HTTP error code.
- At each request to trigger a sequence, the shipyard controller returns two headers:
   - `x-queue-max` with the value of `MAX_QUEUE_SIZE`;
   - `x-queue-free` with the value of how many free spots there are in the queue.
- If the user sends an event to `POST /api/v1/event` and the queue is full, the shipyard controller will immediately create a failed sequence with a message "Queue full". 

## DoD

- Unit tests
- Integration tests

**Comment by thisthat** [comment]
> In a multi-project scenario, this means that one misbehaving project / sequence will block all other projects / sequences. Please consider queing per project / sequence.
The queue is already in place and it blocks on project/stage level. Blocking per sequence doesn't work, think about two different sequences that could still deploy a different artifact on the same service.
> Please consider that there are multiple endpoints that can be used, e.g., `/api/v1/event` in api-service and `/api/controlPlane/v1/project/$PROJECT/stage/$STAGE/service/$SERVICE/evaluation` in shipyard-controller.
Both are covered by the ticket. 
> Limiting this in POST `/api/v1/event` means that you need to distinguish between sequences and tasks (e.g., an external integration would also send task.finished to the same endpoint). That could have a negative performance impact.
This doesn't apply since we blocking a sequence from starting, not any events
> What happens when shipyard-controller itself triggers a new sequence, but the queue is full? see [1]
The new triggered sequence will be failed and not evaluated any further, stopping the circular loop
> Last but not least, not accepting a sequence and responding with a 429 is a breaking change that can have consequences for Keptn integrations (e.g., azure devops, jenkins), but also for the CLI and the Bridge.
Yes, this is a breaking change and will be communicated in the release notes.

**Comment by christian-kreuzberger-dtx** [comment]
> The queue is already in place and it blocks on project/stage level. 

I wasn't aware about this, and it's not reflected in the issue. The issue reads like there is a global queue. To avoid further confusion, could you update the issue description?


> > What happens when shipyard-controller itself triggers a new sequence, but the queue is full? see [1]
>
> The new triggered sequence will be failed and not be evaluated any further, stopping the circular loop

This should be reconsidered. This will not only block remediation workflows, but could also block rollbacks in continuous-deployment scenarios, pretty much rendering core use-cases of Keptn unusable.

IMO, *Keptn must not stop/ignore sequences started from existing sequences*.
One way would be to adapt the user story to not limit the number of sequences, but "active sequences based on sh keptn contexts". This way, a new sequence which has a new "shkeptncontext" could be blocked, but an existing sequence with the same "shkeptncontext" will keep running.

---

Regarding the rest of your message:

I think there is a mismatch between what endpoint the user is using, and what endpoint shipyard-controller is providing.
A user will always post to api-service `/api/v1/event`, which will put the event on NATS.
At this point, you can only return `200 OK` - you have no chance to evaluate queue size (per project/service/stage/sequence/...) at this point.

Shipyard-controller will eventually get the event, and could in theory return `429`, but the user will never know.

**Comment by thisthat** [comment]
> I wasn't aware about this, and it's not reflected in the issue. The issue reads like there is a global queue. To avoid further confusion, could you update the issue description? 
Good point! I'll add the issue which describes the implementation 👍 

> This should be reconsidered. This will not only block remediation workflows, but could also block rollbacks in continuous-deployment scenarios, pretty much rendering core use-cases of Keptn unusable. [...]

Unfortunately, there is no perfect solution. There could be the case where a misconfiguration in the remediations could trigger multiple sequences that will crash the pod with OOM. The value is configurable and the Keptn operator should configure it accordingly to their own needs. 

> I think there is a mismatch between what endpoint the user is using, and what endpoint shipyard-controller is providing.
A user will always post to api-service /api/v1/event, which will put the event on NATS.
At this point, you can only return 200 OK - you have no chance to evaluate queue size (per project/service/stage/sequence/...) at this point.
Shipyard-controller will eventually get the event, and could in theory return 429, but the user will never know.

What you are asking is a change in the semantics of the `/api/v1/event` endpoint. Currently, the endpoint is meant to only provide an answer if the event is well configured or not.

**Comment by christian-kreuzberger-dtx** [comment]
> What you are asking is a change in the semantics of the /api/v1/event endpoint. Currently, the endpoint is meant to only provide an answer if the event is well configured or not.

I must have mis-read the original story, I was under the impression that you want to inform the user via the initial API Call that the queue is full.

**Comment by thisthat** [comment]
With the change of the shipyard-controller to make use of JetStream, this ticket might be obsolete. Nevertheless, the `POST /api/v1/event` might get a new error code from NATS if the queue is full.
