### ISSUE TITLE
HTTP Webhook call containing semicolon fails

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#7042]
### Known limitation 

**Environment**

* Keptn Version (`keptn version`): 0.13.1 

**Affected Component**
* [x] Webhook

### Describe the Limitation

- In the payload for the webhook call I'm referencing a property (e.g., `URL`) and the value of this property contains a `;`. 
- Since the `;` is not allowed but also not detected by the Bridge, the Webhook call fails when called:
`throws the error curl command contains unallowed character ';' `
- Similarly, the validation of URLs should only be performed on URL values and not on the whole command.  

### Possible solutions

- Use something similar to https://github.com/curlconverter/curlconverter
- Refactor the webhook configuration to have different parts of the webhook in different fields
- Refactor the webhook-service to extract parts of the command 

### Screenshots

![image](https://user-images.githubusercontent.com/729071/156516747-0d40851d-eba1-46e6-9728-c885ba174669.png)

**Comment by robertjahn** [comment]
This is a high priority problem in my opinion.    These are two more examples that break the webhook
1) The Dynatrace problem URL contains a semi-colon and will break webhook subscriptions - example URL `https://MY-DYNATRACE-ENV/#problems/problemdetails;gf=all;pid=8788499646929644812_1646881634327V2`
2) a header like content-type like `multipart/form-data; boundary=something`

**Comment by robertjahn** [comment]
This is an issue that was present since webhooks were first introduced.

**Comment by grabnerandi** [comment]
Agree with Rob that this is a critical problem as we wont be able to forward many of the URLs that come in from other tools, e.g: Dynatrace Links to tools we connect via webhook.
Just wondering -> the current implementation of webhook uses CURL if I am not mistaken. Could many of these problems we see right now be solved by implementing this in a different way -> e.g: not executing a Curl statment but using Web Requests from the native language, e.g: Go
In the future I think we should allow the webhook service to also parse the response and use parts of that response, e.g: return messages, ... to push back to Keptn as part of the finished event. In my opinion this would then anyway require to move away from curl to someting more suitable

**Comment by martindstone** [comment]
One other (easy) solution would be to give the payload to curl on stdin (`--data @-`) rather than trying to give it as a command line arg. This also mitigates the security issue that I think the unallowed characters is intended to avoid.

**Comment by martindstone** [comment]
One more easy solution could be to shellescape those strings rather than trying to look for specific characters...

**Comment by christian-kreuzberger-dtx** [comment]
This probably also affects other unallowed characters, such as `$`,  `|`, `>`, `&`

Especially `&`  is used quite often in web URLs, but maybe not in webhooks.

**Comment by martindstone** [comment]
Exactly. And in JSON, all of those characters are legal... and even worse, someone might want to send application/x-www-form-urlencoded some day 😄

My suggestion would be, for the payload, pipe it in to curl's stdin using curl's `--data @-` flag, so that you don't have to look at the payload at all. And for things like `-H` that must be passed on the command line, run it through a shell escaper like the one Rob mentioned. A python example:

```
% python3
Python 3.9.7 (default, Sep  3 2021, 12:37:55) 
>>> import shellescape
>>> curl_command = f"curl -d @{dangerous_string}"
>>> print(curl_command)
curl -d @myFile.txt; rm -rf /
>>> # uh oh!
>>> curl_command = f"curl -d @{shellescape.quote(dangerous_string)}"
>>> print(curl_command)
curl -d @'myFile.txt; rm -rf /'
>>> # ah, better.
```

HTH...

**Comment by robertjahn** [comment]
For Dynatrace problems, a solution is to use this pattern that will open the problem list filtered to the problem.

```
"ProblemURL":"https://[your-dt-environment]/ui/problems?displayId={ProblemID}",
``` 

Then the webhook can have....

```
{
  "type": "{{.type}}",
  "shkeptncontext": "{{.shkeptncontext}}",
  "id": "{{.id}}",
  "data": {
    "project": "{{.data.project}}",
    "service": "{{.data.service}}",
    "stage": "{{.data.stage}}",
    "bridge": "{{.secret.bridge.url}}/project/{{.data.project}}/sequence/{{.shkeptncontext}}",
    "incident": {
      "ProblemID": "{{.data.incident.ProblemID}}",
      "ProblemURL": "{{.data.incident.ProblemURL}}",
      "Tags": "{{.data.incident.Tags}}",
      "ProblemTitle": "{{.data.incident.ProblemTitle}}",
      "State": "{{.data.incident.State}}"
    }
  }
}
```
