### ISSUE TITLE
[DOCS] How To Access Web Interface

### ISSUE THREAD

**Issue by RishabhBhatnagar** [keptn/keptn#7060]
**Environment**

* Client OS: Ubuntu 20.04
* Keptn Version (`keptn version`): 0.13.1
* Kubernetes version (`kubectl version`): 1.23

**Describe the Issue**
How to access the web interface for keptn running on local instance?
[sample UI interface can be seen here](https://keptn.sh/docs/quickstart/#try-multi-stage-delivery)

**Comment by thisthat** [comment]
Hi @RishabhBhatnagar, you can find the details on how to expose your Keptn installation under https://keptn.sh/docs/0.13.x/operate/install/#install-keptn 
We will add a link towards this page in the quick start guide :)

**Comment by thisthat** [comment]
PR: https://github.com/keptn/keptn.github.io/pull/1082
