### ISSUE TITLE
Better syntax for keptn add-resource

### ISSUE THREAD

**Issue by bmaschio** [keptn/keptn#7076]
**Is your feature request related to a problem? Please describe.**

The current syntax of the add-resounce
`keptn add-resource --project=PROJECT --stage=STAGE --service=SERVICE --resource=FILEPATH --resourceUri=FILEPATH [flags]`

I think it can lead to confusion the need to express the fact that we need to express the helm resouce as file path

`keptn add-resource --project=test --service=nginx --all-stages --resource=./nginx-9.9.3.tgz --resourceUri=helm/nginx.tgz`

I think it would be better in my opinion something like

`keptn add-resource --project=PROJECT --stage=STAGE --service=SERVICE --resource=[helm, endpoints , someOther connector ] --resource=FILEPATH `

In this way it will read 

Load this file as a  helm resouce in my projectId service and stage 

thanks

**Comment by johannes-b** [comment]
Hi @bmaschio, 

I need some clarification. Your proposal looks as follows: 
```
keptn add-resource --project=PROJECT --stage=STAGE --service=SERVICE 
   --resource=[helm, endpoints , someOther connector ] 
   --resource=FILEPATH
```

Now, the flag `--resource` is used two times. This does not work. Besides, what is your intention behind the connectors?
