### ISSUE TITLE
Trigger sequence: Format date / time of datetime in a user friendly way

### ISSUE THREAD

**Issue by laneli** [keptn/keptn#7089]
The datetime picker currently returns the date in ISO 8601 UTC format, which could be confusing especially with the time zone adaption.
It would be more user-friendly to format it in a more readable way.

## Acceptance criteria

- [x] Format the contents of the input field in `yyyy-mm-dd hh:mm:ss` in the current time zone (should be done by moment)
- [x] Make sure that the API still receives the ISO 8601 format

## DoD 

- [x] Adapt UI tests

**Comment by thisthat** [comment]
Hi @Aman-Godara thank you for your input! Do you want to take this issue? :) 
I would suggest keeping using moment.js since we don't need any additional features and it is still supported in terms of security and timezone problems.

**Comment by Aman-Godara** [comment]
@thisthat you can assign to whomever you wish to. If I get time and no one else is working on it then I will get this assigned to myself but until then feel free to assign it to whomever you wish. Thanks for asking.
