### ISSUE TITLE
CLI: Misleading version information

### ISSUE THREAD

**Issue by laneli** [keptn/keptn#7090]
When running any keptn command on the CLI the version check displays following information:
![image](https://user-images.githubusercontent.com/2674029/157209747-ffffd540-9c27-476f-92c4-abd5ab818a25.png)

It is misleading, that the first sentence says, that keptn is already on the latest version and below it says, that it is not. This can also be overseen easily.

**Comment by odubajDT** [comment]
Hi @laneli , I think this problem was already resolved in master. We recently had a similar issue: https://github.com/keptn/keptn/issues/6858 where the problems were resolved. I would suggest closing this issue, if you do not have any doubts about the fix.

**Comment by odubajDT** [comment]
According to the discussion, this issue is already resolved in master and there is no need to keep this tracker opened
