### ISSUE TITLE
keptn upgrade not responding on Git Bash / MINGW64

### ISSUE THREAD

**Issue by laneli** [keptn/keptn#7091]
**Environment**

* Client OS (e.g., Linux, macOS, Windows): Windows
* Keptn Version (`keptn version`): Keptn 0.11.4
* Kubernetes Cloud Provider (e.g., GKE, AKS): GKE
* Kubernetes version (`kubectl version`): 1.21.0

**Affected Component**
* [ ] Approval
* [ ] Bridge
* [x] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**
When starting `keptn upgrade` from Git Bash (MINGW64), the upgrade gets stuck after the prompt for
`Do you want to upgrade Keptn version 0.11.4 to 0.x.x? (y/n)`
Also I observed the cluster, if anything is happening - no pods were restarting. So it seems that it just gets stuck after the prompt without triggering any upgrade in the cluster.

![image](https://user-images.githubusercontent.com/2674029/157211161-57845511-0356-4371-94c9-f5912b9e3f1d.png)

**Comment by thisthat** [comment]
Git Bash is not officially supported since it is not a replacement for a Linux environment. I would recommend using Powershell or a Linux distro running in WLS2.
