### ISSUE TITLE
Research: Test of Zero Downtime Upgrades

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#7106]
## Technical details

The goal of the research is to first collect manual confidence that Keptn supports this feature. Furthermore, the outcome of the research should be how we can automate such tests. Please, comment on the outcome as part of this ticket. 

## Acceptance criteria
- [x] Manual test for Zero Downtime
- [x] If problems are identified, open a bug ticket
- [x] Open an issue and describe how these tests can be automated as part of our nightly build

## DoD
- [ ] Acceptance criteria are met

**Comment by bacherfl** [comment]
The following Issues have been created:

Automated testing: https://github.com/keptn/keptn/issues/7373 
Grace Period and preStop hooks for api services: https://github.com/keptn/keptn/issues/7345 
Fixing a rare problem where shippy does not completely process an event before terminating: https://github.com/keptn/keptn/issues/7304 
Execution plane distributor problems: https://github.com/keptn/keptn/issues/7290 

With the changes regarding the terminationGracePeriod, preStopHooks and the upgrade strategy implemented in #7373, all HTTP requests could be processed during the upgrades of Keptn. Regarding the distributor problematic, the switch to the cp-connector library, implemented in https://github.com/keptn/keptn/pull/7334 enabled the lighthouse service to process all evaluation events triggered during the upgradee
