### ISSUE TITLE
Installer: Improve NATS configuration

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#7125]
## Action Item
With the latest update of the NATS charts to [0.13.2](https://github.com/nats-io/k8s/blob/nats-0.13.2/helm/charts/nats/values.yaml) we can configure our NATS installation.

## Acceptance Criteria

- [ ] `automountServiceAccountToken` should be set to `false` either in the `ServiceAccount` or in the `PodSpec`.
- [x] Set Resource limits for CPU and RAM.
- [x] `runAsNonRoot` should be set to `true` or `runAsUser` should be set to a value > 10000 either in the container `SecurityContext` or in the `PodSecurityContext`.
- [x] `allowPrivilegeEscalation` should be set to 'false'.
- [x] `readOnlyRootFilesystem` should be set to 'true'.
- [x] Update the chart version (check https://github.com/nats-io/k8s/blob/main/helm/charts/nats/README.md and the changelog for info about breaking changes)

## DoD 

- [x] Acceptance criteria are met
- [x] Manual test to verify everything works fine
- [x] Integration tests are passing

**Comment by odubajDT** [comment]
value `automountServiceAccountToken` is not exposed in PodSpec of nats, so ti cannot be configured. Filed an issue about the details: https://github.com/nats-io/k8s/issues/527
