### ISSUE TITLE
Maximum of 50 projects in UI (Bridge)

### ISSUE THREAD

**Issue by limberger** [keptn/keptn#7146]
**Environment**

* Client OS - Linux
* Keptn Version:
```
$ keptn version

Keptn CLI version: 0.13.2
Keptn CLI is already on the latest version ( 0.13.2 )! 
Keptn cluster version: 0.13.2

Daily version check is enabled. 
Keptn will collect statistical data and will notify about new versions and security patches for Keptn. Details can be found at: https://keptn.sh/docs/0.13.x/reference/version_check
---------------------------------------------------
* To disable the daily version check, please execute:
 - keptn set config AutomaticVersionCheck false

```
* Kubernetes Cloud Provider : AWS
* Kubernetes version (`kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-13+d2965f0db10712", GitCommit:"d2965f0db1071203c6f5bc662c2827c71fc8b20d", GitTreeState:"clean", BuildDate:"2021-06-26T01:02:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Affected Component**

**Describe the bug**
In CLI the number of projects is 57,  the UI in the browser (bridge) show only 50 and not show next page.

**To Reproduce**
Open UI   (bridge) in browser having more then 50 projects.
http://keptn.[domain]/bridge/dashboard

**Expected behavior**
The UI (bridge) shows 57 projects

**Current behavior**
The UI (bridge) shows only 50 projects

**Comment by hromao** [comment]
I have the same issue. I can see the request to `http://keptn.<domain>/bridge/api/controlPlane/v1/project?disableUpstreamSync=true&pageSize=50`, but there is no "Next page" button.

**Comment by laneli** [comment]
@limberger, @hromao please use the `PROJECTS_PAGE_SIZE` environment variable to increase the number of projects loaded. The default value that is used, if the variable is not set, is always 50.
I also created a follow up issue to discuss if we should include paging to the dashboard or remove the variable entirely. Please feel free to follow the issue.
https://github.com/keptn/keptn/issues/7201

**Comment by limberger** [comment]
> @limberger, @hromao please use the `PROJECTS_PAGE_SIZE` environment variable to increase the number of projects loaded. The default value that is used, if the variable is not set, is always 50. I also created a follow up issue to discuss if we should include paging to the dashboard or remove the variable entirely. Please feel free to follow the issue. #7201

Thanks, this helps a lot! 
Of course, the pagination correction would be quite desirable.

Thank You!!!
