### ISSUE TITLE
Bridge: Enforce Git data at project creation

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#7150]
## Technical details

With moving to the `resource-service`, a git upstream will become mandatory. Hence, some fields for configuring the upstream are mandatory. However, a Keptn operator could have set automatic provisioning of repositories at project creation, making these values not mandatory. 

## Acceptance Criteria

- [x] Read the value from `GET /metadata` if the automatic provisioning is configured or not -> this value will be called `AUTOMATIC_PROVISIONING` in the rest of the ticket.
- [x] If `AUTOMATIC_PROVISIONING` is false, the default mandatory values are required (we preserve the current behavior).
- [x] If `AUTOMATIC_PROVISIONING` is true, the "Git upstream repository" section containing the information for setting up an upstream is **optional**. 
- [x] If the env var `AUTOMATIC_PROVISIONING_MSG` is not an empty string, which is read from the helm value `bridge.automaticProvisioningMsg`,  the bridge shows that message after the `Git upstream repository` header. 
- [x] The default value for the helm value `bridge.automaticProvisioningMsg` should be set to the same message in the "Git upstream repository" section. See pic below.

![git-msg](https://user-images.githubusercontent.com/992621/158541170-9e1349fb-38b9-490a-a277-d8345aac95ae.png)

## DoD

- Unit tests
- UI tests

## Dependencies
- https://github.com/keptn/keptn/issues/7151

**Comment by agardnerIT** [comment]
What happens to existing projects that do not have an upstream set?
