### ISSUE TITLE
Evaluate against specific previous evaluation

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [keptn/keptn#7153]
### Discussed in https://github.com/keptn/keptn/discussions/5610

<div type='discussions-op-text'>

<sup>Originally posted by **Dynatrace-Adam-Gardner** October 11, 2021</sup>
Is there a way (or should I raise a KEP) to evaluate against a **specific** previous Keptn evaluation?

Usecase: I have a known evaluation which is "good" for me to evaluate against. Someone then runs several other evaluations that all pass but for whatever reason, I'm not interested in (perhaps they ran a slightly different load). I know that for a fair comparison I now need to compare my next evaluation against `n-4`. Where `n-3`, `n-2` and `n-1` are all still passing builds.

Something like this where `comparison` specifies a specific evaluation as shown in the bridge?

```
keptn trigger evaluation \
--project=project1 \
--service=carts \
--stage=dev \
--timeframe=2h \
--comparison=2021-10-11 10:38
```</div>

**Comment by agardnerIT** [comment]
Please leave open as this came from a Keptn user

**Comment by agardnerIT** [comment]
Re-open

**Comment by agardnerIT** [comment]
Keep open....
