### ISSUE TITLE
Trigger sequence: Improve buttons on trigger sequence component

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#7157]
## Acceptance Criteria 

- verify if the button alignment is the best one or it is better to move "cancel" on the left and "next" & "trigger" on the right
- verify if the text "cancel and close" is the best or just "close" or "cancel" suffices 

## DoD

- UI/Unit tests are adapted

**Comment by johannes-b** [comment]
Some improvements are also discussed here: https://github.com/keptn/keptn/issues/6983

**Comment by johannes-b** [comment]
- [ ] I would like to see some sort of confirmation that the sequence is triggered (event was sent). Right now, I don't know what to do next.
![image](https://user-images.githubusercontent.com/729071/160764673-6dc62a17-38fb-4877-bb70-56e12c9f744f.png)

**Comment by laneli** [comment]
@johannes-b regarding your comment
The behaviour should be the following:

- Send event
- If error: set isLoading to false - HttpInterceptor should show the error anyways, so no error handling needed
- If successful:
   - Retry 5 times with interval of 1s: Try to fetch sequence by context
   - If sequence is found, navigate to sequences with context
   - If retry reaches 5 and no sequence found: Navigate to sequences w/o context
   - If error while fetching sequence: Fail gracefully - navigate to sequences w/o context

So if an event is sent you should be redirected to sequences page in any case. It seems more like it failed and no error was shown. Or we missed a success case. In any way, I would ask to create an issue for that, as it seems as it is not behaving like intended.
