### ISSUE TITLE
Publish SBOM for Keptn artifacts/images

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/keptn#7163]
It would be really nice to publish SBOMs for all Keptn deliverables, preferably in the SPDX format so that it can be consumed by the Linux Foundation tooling ecosystem and downstream projects.

Scope:
- [ ] Keptn service
- [ ] Keptn integration services
- [ ] Keptn CLI

**Comment by riteshsonawane1372** [comment]
I want to give it a try. kindly assign me

**Comment by mowies** [comment]
Great! I assigned you.
Check out this github action here. I had my eye on it for this ticket before already: https://github.com/anchore/sbom-action

**Comment by riteshsonawane1372** [comment]
I created a folder with the name "spdx" and added SBOM of each service in that folder in the default .spdx format 
![image](https://user-images.githubusercontent.com/72307121/209932148-8b387dc1-f0a1-4314-95a9-ae1e35ebdaeb.png)

**Comment by mowies** [comment]
Cool! The general plan would be to generate the SBOMs during the release pipeline (`.github/workflows/release.yml`)
and then attach them to the created release as one zip archive.

**Comment by riteshsonawane1372** [comment]
@mowies kindly review the #9391  PR and let me know what changes to be made.

**Comment by mowies** [comment]
This PR from keptn/lifecycle-toolkit can be used as a good reference: https://github.com/keptn/lifecycle-toolkit/pull/571

**Comment by riteshsonawane1372** [comment]
@mowies I'm so sorry I removed the assignment I gave it a try but got too many errors. I knew abt SPDX and SBOMs but wasn't familiar with CI/CD. Thanks a lot for the opportunity, learning CI/CD now.

**Comment by mowies** [comment]
@riteshsonawane1372 no worries, pipelines are not easy sometimes :)
