### ISSUE TITLE
Container signing for Keptn images with Project Sigstore and Cosign

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/keptn#7164]
It would be great too sign all artifacts we deliver so that they could be verified on the end user side and in downstream projects. Project Sigstore is a recommended solution in the Linux Foundation ecosystem, and there is a special tooling for container signing.

## Scope

- [ ] Keptn service
- [ ] Keptn integration services
- [ ] Keptn CLI image

## References

* https://www.sigstore.dev/
* https://github.com/sigstore/cosign

**Comment by thisthat** [comment]
Research: can we use self-sign certificates? can we get some trusted certificates from the Linux Foundations? Can we use some external provider like let's encript?

**Comment by mowies** [comment]
Some reference that could be interesting: https://www.cncf.io/blog/2021/09/14/how-to-secure-containers-with-cosign-and-distroless-images/

**Comment by mowies** [comment]
Some research was done and the results are the following:
- cosign works well for container image signing and potentially even helm chart signing in the future (if we switch to pushing helm charts to OCI registries)
- Only parts of cosign and the sigstore infrastructure are GA yet, namely the cosign tool. Other parts like the Rekor transparency log and Fulcio as a keyless OIDC PKI server are not GA yet and cannot be used for production yet.
- This means that for now, Keptn can use cosign to sign images but with a self-generated key pair and no transparency logging.

**Comment by mowies** [comment]
I changed strategy slightly, and will also use the experimental features of sigstore and cosign. This will enable us to use keyless signing through ephemeral keypairs and signatures and will also support the Rekor open transparency log by sigstore.
