### ISSUE TITLE
Restore configuration-service does not work when following instructions

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#7167]
**Environment**

* Keptn Version (`keptn version`): `0.13.2`

**Affected Component**

* [x] (Configuration-service) passiv, the bug is in the docs
* [x] Docs

## Describe the bug
When following the instructions for restoring the configuration service according to: https://keptn.sh/docs/0.13.x/operate/backup_and_restore/#restore-configuration-service

I get the following error when executing: 
```
johannes@TAG009442084012:~/keptn-backup$ kubectl cp ./reset-git-repos.sh keptn-migration/$CONFIG_SERVICE_POD:/ -c configuration-service

tar: can't remove old file reset-git-repos.sh: Read-only file system
command terminated with exit code 1
```

* The reason is that the configuration-service provides *write* permissions on the `/data/config` folder only: https://github.com/keptn/keptn/blob/master/installer/manifests/keptn/charts/control-plane/templates/configuration-service.yaml#L100

* The fix is already provided here: https://github.com/keptn/keptn.github.io/pull/1107

**To Reproduce**
* Execute the backup/restore instructions: https://keptn.sh/docs/0.13.x/operate/backup_and_restore/#title

## Definition of Done
- While the fix can be provided via the documentation (please see: https://github.com/keptn/keptn.github.io/pull/1107), I would kindly ask for an integration test of these instructions.

**Comment by odubajDT** [comment]
Hi @johannes-b thanks for testing the instructions! I have enhanced our integration test with the missing instructions (https://github.com/keptn/keptn/pull/7182), just a tiny notes regarding the docs:
- please change this line `kubectl exec -n keptn $CONFIG_SERVICE_POD -c configuration-service -- ./data/config/reset-git-repos.sh` to `kubectl exec -n keptn $CONFIG_SERVICE_POD -c configuration-service -- sh data/config/reset-git-repos.sh` -> it did not work for me with the previous format (not using `sh` directly)
- when using `sh` we do not need this line at all `kubectl exec -n keptn $CONFIG_SERVICE_POD -c configuration-service -- chmod +x -R ./data/config/reset-git-repos.sh` -> it can be removed from the docs

Thanks!
