### ISSUE TITLE
Inconsistent mandatory User for git upstream

### ISSUE THREAD

**Issue by RealAnna** [keptn/keptn#7186]
**Environment**

* Client OS (e.g., Linux, macOS, Windows): Windows
* Keptn Version (`keptn version`): `0.13.3`

**Affected Component**

* [x]Bridge
* [x] CLI

**Describe the bug**
Cannot create a project without specifying user, in some cases eg. github it is enough to provide token and repo to setup a stream so the field should not be mandatory.
In create project on bridge this is correct, but update on bridge and creations via CLI fails without a User.

**To Reproduce**
In bridge try to set git upstream for existing project
![image](https://user-images.githubusercontent.com/89971034/158783215-a3c24b18-e5b0-4d05-877f-1be4a90d8313.png)

In CLI
![image](https://user-images.githubusercontent.com/89971034/158783277-15033870-950c-4979-934a-26605b289406.png)

**Comment by christian-kreuzberger-dtx** [comment]
In my tests there seems to have been some problems with username:token authentication schema, but they seem to have been resolved by GitHub as of right now.

IMO you will always need username + token, except for when using "SSH" as an authentication method.
