### ISSUE TITLE
Allow creation of project without stages

### ISSUE THREAD

**Issue by agardnerIT** [keptn/keptn#7209]
Currently a keptn project can only be created with stages preconfigured. This makes beginner workflow harder as a logical flow (to me) would be:

1.  Create a project
2. Decide my stages
3. Decide my sequences and link to the stages

This workflow would also suit the GitOps approach. See: https://github.com/keptn-sandbox/keptn-gitops-operator/issues/35

**Describe the solution you'd like**
Ability to create a project without stages and add them later.

**Describe alternatives you've considered**
None available. Only alternative is to stick with status-quo.

**Comment by johannes-b** [comment]
Hi @agardnerIT 
thanks for the ticket.
I see this issue somehow related to: https://github.com/keptn/enhancement-proposals/pull/70
