### ISSUE TITLE
Compare our GitOps approach to others

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#722]
This is a research task for comparing our GitOps approach to others (e.g. flux).

**Comment by jkleinlercher** [comment]
I think that is an interesting task. We are using ArgoCD right now but keptn seems to be an interesting project. Now our question is: is keptn a replacement for argocd or an extension? Where are the differences? Advantages/Disadvantages? Migration Path?

**Comment by agrimmer** [comment]
Thank you for your interest in Keptn! For a high-level overview explaining “Why keptn”, I would like to refer you to our new page https://keptn.sh/why-keptn/
But in my opinion, the most important differences between ArgoCD and Keptn are the following:
- Keptn is not only designed for Continuous Delivery but in general for DevOps automation. For example, Keptn allows automating operation tasks as e.g. rolling back to an old version, toggling feature flags, clearing disks or any of your operation tasks!
- Keptn provides Quality Gates, which allow you to automatically check the quality of a software artifact using so-called Service Level Indicators and Service Level Objects (see https://github.com/keptn/spec/blob/master/sre.md). As SLI providers Keptn currently supports Prometheus and Dynatrace.
- Keptn is designed for extensibility. More precisely, Keptn is an event-based system and you can simply register your service on one of these events. See https://github.com/keptn/spec/blob/master/cloudevents.md

I hope that helps! If you have further questions, please join our Slack channel. We are happy to answer all your questions.

**Comment by jkleinlercher** [comment]
@markuslackner
