### ISSUE TITLE
Eye-catching notification text for new releases

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#7264]
### Use case

Drive more attention to the notification text in order to guide the user to upgrade to the latest Keptn release.

#### Details

* Currently, the user sees:
![image](https://user-images.githubusercontent.com/729071/159876799-cf7b9826-a76c-47a2-a11b-440d25149069.png)
* While this message informs about a new release, motivation is missing to use it. Motivation could be the need to get a bug fix or security patch. 

In this ticket, the notification text should be changed from: 

> *New Keptn CLI 0.13.4 and Keptn Bridge 0.13.4 available. For details how to upgrade visit https://keptn.sh/docs/0.13.x/operate/upgrade/*

to 

> ⚠️ *New Keptn release [0.13.4](https://github.com/keptn/keptn/releases/tag/0.13.4) available. **Please upgrade** to this release following these [instructions](https://keptn.sh/docs/0.13.x/operate/upgrade/).*

--> Please replace the needle by a ⚠️ 

### Definition of Done

* [ ] Notification message drives more attention to upgrade.

**Comment by CIPHERTron** [comment]
Heyy @johannes-b I would love to work on this issue. Could you please assign it to me? Thanks :D

**Comment by oleg-nenashev** [comment]
If you want to try it, just go ahead and submit a pull request @CIPHERTron !

**Comment by eyskim** [comment]
@CIPHERTron - how is your progress on this issue? Let me know if you're opposed to me taking over.

**Comment by CIPHERTron** [comment]
> @CIPHERTron - how is your progress on this issue? Let me know if you're opposed to me taking over.

Hey @eyskim thanks for your interest. I'm almost done and will be sending a PR latest by today.
Will let you know if I'm facing any difficulty :)

**Comment by mehabhalodiya** [comment]
@CIPHERTron I see that you haven't worked on this for so long. 
@thisthat @johannes-b You can assign it to me. However, I stepped up and tried my way (see the linked PR). Happy to see the suggestions and improve them. Thank you 🙂

**Comment by thisthat** [comment]
Thank you @mehabhalodiya :D

**Comment by agardnerIT** [comment]
Isn't this done now? The banner at the top of the keptn.sh site does this quite well.
