### ISSUE TITLE
Trigger sequence: Timeframe is not sent, instead start / end date is set

### ISSUE THREAD

**Issue by laneli** [keptn/keptn#7268]
**Affected Component**

**Describe the bug**
For triggering an evaluation, when I put in 100h 50s and no start date. The evaluation fails with following error:
`no evaluation performed by lighthouse because SLI failed with message error validating time range: Supplied end-time 2022-03-24 13:29:05.867 +0000 UTC is too far (>120seconds) in the future (now: 2022-03-24 12:28:17.472012479 +0000 UTC m=+257312.515908793 - diff in sec: -3648.394987521)
`

This is what was sent in the event payload for the event:
```"evaluation": {
      "end": "2022-03-24T13:29:05.867Z",
      "start": "2022-03-24T12:28:15.867Z",
      "timeframe": ""
    },
```

It seems, that no timeframe was set at all, just the start and end date. There should be the timeframe 100h50s and the start date in the payload.

**To Reproduce**
* Go to Bridge
* Trigger a new sequence
* Trigger an evaluation
* Put in for timeframe 100h50s (or any other)
* Trigger sequence and observe started sequence + payload

**Expected behavior**
The timeframe is sent in the payload.

**Current behavior**
Start and end date are sent as payload.

**Comment by johannes-b** [comment]
I observe the same behavior when using the API. If I select the following: 

![image](https://user-images.githubusercontent.com/729071/160618224-03ddc014-d5d7-44e5-bb84-0ea03300dde8.png)

it will be translated into: 

![image](https://user-images.githubusercontent.com/729071/160618342-f328b142-6d6f-4ac9-bda4-b82cea69ad7c.png)

I'm wondering why we actually send the `timeframe` property.
