### ISSUE TITLE
Invalid Token - Drift From Helm Chart Secret

### ISSUE THREAD

**Issue by joshua-giumelli-deltatre** [keptn/keptn#7274]
Hi there,

I've deployed Keptn via Helm chart (from [charts.keptn.com](http://charts.keptn.com/)) and it seems that if the pods for API service and Bridge run for long enough, the SECRET_TOKEN/API_TOKEN values are reset inside the app. The spec of the Helm chart says that these values should be read from a Kubernetes secret however after exec-ing into the pods, I can see that these env vars values have drifted from the secret. Replacing the pods sets these env vars back to the value in the secret and resolves the issue. Trying to access bridge results in a redirect loop because the token's do not match. To confirm, when these pods are first launched, the env vars values matches what is in the secret object, but after while the env var in the pods does not match what is in the secret anymore.

Reproduction:
Install Keptn Helm charts version 0.13.2, leave API service and Bridge pods running for at least 12 hours. Attempt to log into Bridge via Chrome and observe redirect loop and pod logs about invalid token.

* Client OS (e.g., Linux, macOS, Windows): MacOS/NA
* Keptn Version (`keptn version`): 0.13.2
* Kubernetes Cloud Provider (e.g., GKE, AKS): EKS
* Kubernetes version (`kubectl version`): client 1.23, server 1.21

Please let me know if any further details are required

**Comment by thisthat** [comment]
Hi @joshua-giumelli-deltatre do you have only Keptn installed into your cluster?

**Comment by AbhijithGanesh** [comment]
I'd like to further investigate this issue.

**Comment by thisthat** [comment]
Thank you @AbhijithGanesh, the more eyes on this bug the easier is to spot why there was a drift :)

**Comment by joshua-giumelli-deltatre** [comment]
Hi @thisthat and @AbhijithGanesh,thanks for looking into this. There's nothing running in this cluster that would rotate the secret. I currently have this issue at the moment if there's anything you'd like me to provide.

**Comment by joshua-giumelli-deltatre** [comment]
Actually, just had a thought. We've deployed Keptn via ArgoCD, which regularly runs syncs on Helm charts to resolve drift. Looking at the template for the `keptn-api-token` secret, I can see this line:

```{{- $apiToken := (randAlphaNum 45) | b64enc | quote }}```

The `randAlphaNum` function appears to generate a new value on every evaluation (https://github.com/helm/helm/issues/3053) so that would show up as a drift when Argo runs.

[This](https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments) looks like it could be used as a workaround but I wonder if another function should be used instead of `randAlphaNum`?

**Comment by mowies** [comment]
This is some interesting behaviour here... :D
@joshua-giumelli-deltatre shouldn't the `apiToken` variable actually be set to the value from the secret if it already exists? I am not sure if this is also the case with helm template though. But it is definitely set to the secret value if it exists already ([source](https://github.com/keptn/keptn/blob/0.13.2/installer/manifests/keptn/charts/control-plane/templates/core.yaml#L2))

**Comment by mowies** [comment]
Aha I think I found my answer already:
> Any values that would normally be looked up or retrieved in-cluster will be faked locally
[Source](https://helm.sh/docs/helm/helm_template/)

**Comment by mowies** [comment]
I think an easy solution would be to just add the option to add annotations to the `keptn-api-token` secret so that you can add the Argo annotation there. I don't think that it's an option for the Keptn team to get rid of the random generated tokens. Those are there to make it easy for first-time users to install Keptn and already be provided with proper secrets instead of hardcoded values.

**Comment by mowies** [comment]
@AbhijithGanesh since you wanted to work on this earlier, is it something you still want to work on or should I take it over?

**Comment by AbhijithGanesh** [comment]
@mowies Please take over! I am unable to solve this!
