### ISSUE TITLE
CLI: Remove functionality to delete all services when deleting a Keptn project

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#7297]
The CLI command `keptn delete project` contains logic for first deleting all services of a project before deleting the actual project. This functionality for first deleting all services should be removed because it manipulates the Git repository, i.e. deletes folders. These deletions in the Git repo are potentially not the user-desired behavior because the Git repository cannot be reused.

Furthermore, the behavior of the CLI is inconsistent with the API of the shipyard-controller and the Bridge – both do not delete services before deleting the project.

**Definition of Done:**
- The services are not deleted when deleting a project with Keptn CLI
- Follow the boy scout rule

**Comment by RealAnna** [comment]
This is the current behaviour of the API
**Delete Project :** 

```
1.  calls DeleteSecret
2.  calls MV DeleteProject
3.  deletes project sequences from collections
4.  calls resource service DeleteProject (this only cleans up resource service local file system)
```

**Delete Service :** 

```
1.  calls resource service DeleteService (this actually stages and commit the change)
2.  deletes service from MVPRepo
3.  deletes service from uniform subscriptions
```

       
CLI Delete Project calls both endpoints. Indeed CLI should only call the corresponding endpoint.

However IMH DeleteProject should also clean up the uniform from its now unexisting filters to avoid inheriting them again if the project is recreated e.g. webhook keeps listening for events of a deleted project/service.
