### ISSUE TITLE
Core: Migrate webhook configuration from `v1alpha1` to `v1beta1`

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#7322]
## User Story

As a Keptn operator, I want to control the migration of the webhook configuration.

## Acceptance Criteria

- The webhook-service should have a boolean new env var `MIGRATE_CONFIG` that is read from the helm value `webhook.configMigration.enabled`
- At the startup of the webhook-service, if the env var `MIGRATE_CONFIG` is `true`, then the service migrates all webhook.yaml files from `alpha` to the `beta` version.
- When a migration fails, the webhook-service should print a warning message in the logs and continue working normally.

## Technical Details 

The current format of the request field is the following:
```
requests:
  - >-
     curl --request ${method} --proxy ${proxy} --data ${payload} ${url}
```

## DoD

- [x] Unit tests
- [x] Integration tests

**Comment by jainammm** [comment]
Here, what would be the unit test for? Won't the unit tests be written while the version changes?

**Comment by thisthat** [comment]
Hi @jainammm, your general flow sounds correct to me 👍 
For unit tests, I would expect a validation that the "transformation function" from `v1alpha1` to `v1beta1` works as expected and can handle weird cases, e.g., missing the URL, a different version specified, empty requests array etc

**Comment by odubajDT** [comment]
Hello @jainammm ! Thanks one more time for you interest for contributing to our project :) Here is a first working version of the new `v1beta1` standard of webhook configuration https://github.com/keptn/keptn/pull/7329. You can look at it and it should certainly help you with implementing/testing your issue. There may be some minor fixes, but I don't expect any crucial changes to this PR before merging. Probably just adding some more tests and covering corner cases.

Good luck!

**Comment by jainammm** [comment]
Thanks for the update @odubajDT... I'll look into the PR and let you know if I have any doubts and start implementing the migration task this weekend 👍

**Comment by thisthat** [comment]
Hey @jainammm, did you manage to work on this ticket? Do you need further support?

**Comment by jainammm** [comment]
Hey @thisthat, sorry I went on a bit of vacation and for a conference in the USA so was not able to work on it yet. I can work on this in the next week. If you can let me know the date this needs to be closed, it'd be good. 

Thanks.

**Comment by thisthat** [comment]
Hey @jainammm, it would be nice to have this in for Keptn 0.17 which will be delivered by the first week of July. Would that work for you? :)

**Comment by odubajDT** [comment]
Hi, taking over this issue, as we have a deadline to deliver this feature into the next release

**Comment by odubajDT** [comment]
As a team, we discussed this topic and came to a conclusion, that the best solution will be to introduce a new CLI command `migrate-webhooks`, which can be executed by the user, when there is the need to migrate webhook-configs from `v1alpha1` to `v1beta1` version. 

Usage:

`keptn migrate-webhooks [--project=PROJECTNAME] [--dry-run] [--yes]`

Explanation:
- no flag included: all webhooks in all projects are migrated, before updating the webhook in git, user needs to manually accept the changes
- `--project` specifies the project whose webhooks will be migrated, user needs to manually accept the changes
- `--dry-run` command only prints the migrated webhooks but does not update then in git
- `--yes` accepts all webhook changes automatically

@thisthat
