### ISSUE TITLE
Double trouble: Multiple subscriptions for the same task (and project) in uniform lead to multiple forwarded events

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#7333]
**Not sure if this qualifies as a bug, might be working as designed, but I want to raise awareness about this, as it did just cost me some time to troubleshoot**

With Keptn 0.12.6 and `keptn/distributor:0.12.6` (also tested with 0.12.2) I configured the following in my uniform (on accident):

![image](https://user-images.githubusercontent.com/56065213/161248916-bae5a1a2-248c-45f1-a895-60da464a2000.png)

While this is clearly a user error, it leads to sub-optimal behaviour: The task Cloud event is forwarded twice to the Keptn-service, at least in the case of remote execution-plane services that are polling events.

**Behaviour with two subscriptions**
![image](https://user-images.githubusercontent.com/56065213/161249961-b103788b-78fd-4347-93b4-b8eb379a9a6b.png)

**Normal (expected) behaviour**
![image](https://user-images.githubusercontent.com/56065213/161249553-24c96703-e7f3-4c68-b785-252a6727619a.png)

In fact, it is possible to specify as many subscriptions as you want, even for the same project:
![image](https://user-images.githubusercontent.com/56065213/161250089-9217444d-f0cd-44f1-ba4b-d68f2a41ee2e.png)
Which leads to the cloud event being sent multiple times.

# Logs

Cloud Event
* `"id": "e5683e7f-3178-4ae0-a8f2-993d9dc3a05e",`
* `"shkeptncontext": "b7d43eb6-22d5-4656-b73e-0927b737fddd",`

Output of distributor:
```
time="2022-04-01T10:51:39Z" level=info msg="Starting Event Forwarder"
time="2022-04-01T10:51:39Z" level=info msg="Registering Keptn Integration"
time="2022-04-01T10:51:39Z" level=info msg="Registered Keptn Integration with id 10e99213062f84499c1a23077adf5009b0e9c2e6"
time="2022-04-01T10:51:39Z" level=info msg="Starting uniform log for Keptn service with integration ID 10e99213062f84499c1a23077adf5009b0e9c2e6"
time="2022-04-01T10:51:39Z" level=info msg="Connection type: http"
time="2022-04-01T10:51:39Z" level=info msg="Starting HTTP event poller"
time="2022-04-01T10:51:39Z" level=info msg="Polling events from: http://api-gateway-nginx.keptn/api/controlPlane/v1/event/triggered"

time="2022-04-01T10:53:21Z" level=info msg="Adding temporary data to event: <subscriptionID=ba5b65c1-d4d1-421c-b430-f3e455f8078e>"
time="2022-04-01T10:53:21Z" level=info msg="Sending CloudEvent with ID e5683e7f-3178-4ae0-a8f2-993d9dc3a05e to 127.0.0.1"
time="2022-04-01T10:53:21Z" level=info msg="Adding temporary data to event: <subscriptionID=5b9ad25b-354f-49d8-a099-4cc678cd9aa0>"
time="2022-04-01T10:53:21Z" level=info msg="Sending CloudEvent with ID e5683e7f-3178-4ae0-a8f2-993d9dc3a05e to 127.0.0.1"
time="2022-04-01T10:53:21Z" level=info msg="Adding temporary data to event: <subscriptionID=7fb6fcbf-1ca7-42fe-b745-316514de3fbb>"
time="2022-04-01T10:53:21Z" level=info msg="Sending CloudEvent with ID e5683e7f-3178-4ae0-a8f2-993d9dc3a05e to 127.0.0.1"
time="2022-04-01T10:53:21Z" level=info msg="Received CloudEvent with ID fc3cc90e-90d4-4fea-a84a-ef14c3405a48 - Forwarding to Keptn"
time="2022-04-01T10:53:21Z" level=info msg="Event forwarded successfully"
time="2022-04-01T10:53:22Z" level=info msg="Adding temporary data to event: <subscriptionID=f6337f98-d6b4-4f38-966e-ed81d5e62446>"
time="2022-04-01T10:53:22Z" level=info msg="Sending CloudEvent with ID e5683e7f-3178-4ae0-a8f2-993d9dc3a05e to 127.0.0.1"
time="2022-04-01T10:53:22Z" level=info msg="Received CloudEvent with ID 84bd254c-4ba6-4549-8013-3d814f03ebe5 - Forwarding to Keptn"
time="2022-04-01T10:53:22Z" level=info msg="Event forwarded successfully"
time="2022-04-01T10:53:22Z" level=info msg="Received CloudEvent with ID 609014d5-9621-4fa4-98ef-e5f39a8256c6 - Forwarding to Keptn"
time="2022-04-01T10:53:22Z" level=info msg="Received '.finished' event with status 'errored'. Forwarding log message to log ingestion API"
time="2022-04-01T10:53:22Z" level=info msg="Event forwarded successfully"
time="2022-04-01T10:53:22Z" level=info msg="Received CloudEvent with ID ec8926bc-772e-4154-bfc0-cac684dabf12 - Forwarding to Keptn"
time="2022-04-01T10:53:22Z" level=info msg="Event forwarded successfully"
time="2022-04-01T10:53:22Z" level=info msg="Received CloudEvent with ID b2346e1d-a4c3-449d-81fe-7362c10b9058 - Forwarding to Keptn"
time="2022-04-01T10:53:22Z" level=info msg="Received '.finished' event with status 'errored'. Forwarding log message to log ingestion API"
time="2022-04-01T10:53:22Z" level=info msg="Event forwarded successfully"
time="2022-04-01T10:53:32Z" level=info msg="Received CloudEvent with ID e3d5810a-fc60-4e93-82b8-59e9007e0848 - Forwarding to Keptn"
time="2022-04-01T10:53:32Z" level=info msg="Event forwarded successfully"
```

# Workaround

For now, it's possible to just delete / reconfigure subscriptions properly (e.g., one sub per project)

# Room for improvement

Two ideas for improvement:
* distributor could make sure to forward a `.triggered` event with a certain shkeptncontext **at most once**, independent of subscriptions
* uniform could deny creating overlapping subscriptions (though IMO this could be intended as it is right now and should not be changed)

**Comment by robertjahn** [comment]
Here is another use case:  I have two subscriptions for the same task and one passed and one fails, but then the overall passes. I would expect if one of the  activities within a task "starts" and "finishes" with a failure, then the overall task would fail and thus the controller would fail the sequence.   See screen shot example of what happens now. 

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/24907089/164011550-f675259a-92b3-4f20-9f4a-bc499cf59b3a.png">
