### ISSUE TITLE
Cleanup of obsolete feature in Bridge

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#7378]
## Cleanup task

About 1.5 years ago, we introduced a feature in Keptn Bridge to dynamically load a list of available integrations. See:

![image](https://user-images.githubusercontent.com/729071/161940241-11c92a71-e83e-49e7-9167-07f22c8c8bdb.png)

With the ArtifactHub in place (https://artifacthub.io/packages/search?ts_query_web=keptn&sort=relevance&page=1), this feature is not needed anymore and should be removed. 

### Definition of done
- [x] In Bridge, the button **Load more information about integrations** and below label are removed:
   ![image](https://user-images.githubusercontent.com/729071/161940833-0ae7b3d9-9511-4a95-a238-f03d220645ac.png)
- [x] Environment variable is removed here: https://github.com/keptn/keptn/blob/master/installer/manifests/keptn/charts/control-plane/templates/core.yaml#L145
- [x] The file [integrations.html](https://github.com/keptn/get.keptn.sh/blob/master/src/integrations.html) is deleted including an update of https://github.com/keptn/get.keptn.sh/blob/master/.github/workflows/deploy_to_s3.yaml#L32
- [x] The Keptn docs is update, i.e., this page is deleted: https://keptn.sh/docs/0.14.x/bridge/load_information/

**Comment by Brijesh-09** [comment]
Can you assign this issue to me?

**Comment by Brijesh-09** [comment]
Is the issue related to UI/UX as I am not able to find the button and dashboards details from above image in the code can you help me with that?

**Comment by heinzburgstaller** [comment]
> Is the issue related to UI/UX as I am not able to find the button and dashboards details from above image in the code can you help me with that?

Hi! You will find the code/button in `bridge/client/app/_views/ktb-integration-view/ktb-integration-view.component.htmll` at line number 63.
