### ISSUE TITLE
Keptn CLI has a misleading user message

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#7390]
## Cleanup

As a user, I'm running a Keptn CLI `0.11.4` for a Keptn cluster `0.12.6` while a new version of Keptn is available `0.13.4`. When executing `keptn get project` I get the following output: 

![image](https://user-images.githubusercontent.com/729071/162134778-60d592e6-cc97-4c90-a97a-d8bf940c88db.png)

* **Question**: What is the intention behind the message: `Keptn CLI and Keptn version are already on the latest version (0.11.4)!` > If there is no meaningful reason, can we please delete it.  

---

Some improvements have already been made. Because when I'm running a Keptn CLI `0.13.4` for a Keptn cluster `0.12.6` I get the following output: 

![image](https://user-images.githubusercontent.com/729071/162135310-b3974164-8c0a-4a99-9e84-0e26c3477ff0.png)

* But still, the message `Keptn CLI is ... ` confuses me.

### Definition of Done
- If there is no strong argument for leaving the above-mentioned message (I'm happy to discuss this), the message is removed and the code in the CLI is cleaned up accordingly.

**Comment by thisthat** [comment]
Solved with #7222
