### ISSUE TITLE
mock jmeter

### ISSUE THREAD

**Issue by RealAnna** [keptn/keptn#7401]
We should add mocking of jmeter command execution via interface to the command, to enable unit test of the full jmeter service, now only the part before the execution is tested properly. 
![image](https://user-images.githubusercontent.com/89971034/162200113-3673210d-2092-4648-a434-b310fc64782f.png)

DoD

- [ ] increased coverage
- [ ] created mock

**Comment by huggingpixels** [comment]
Can I be assigned to this issue please?
