### ISSUE TITLE
resourceURI needs to be URL encoded for GET resource API endpoint to retrieve dynatrace.conf.yaml file

### ISSUE THREAD

**Issue by anton-fr** [keptn/keptn#7412]
The /project/{projectName}resource/{resourceURI} endpoint needs the {resourceURI} to be URL encoded to retrieve the dynatrace.conf.yaml file. Other files like the shipyard file work. This does not seem to be documented anywhere.

![image](https://user-images.githubusercontent.com/64915718/162447407-57300955-d365-46e4-bb81-f08c096d7527.png)

**Comment by thisthat** [comment]
This is a known limitation of our APIs
