### ISSUE TITLE
webhook-service unallowed urls too strict

### ISSUE THREAD

**Issue by agardnerIT** [keptn/keptn#7413]
The webhook service invalid urls checking is currently too strict. The code currently checks the entire `curl` string.

This makes testing the webhook-service impossible to use when developing and testing integration on a local keptn instance.

Given the following curl, the webhook-service deems this as invalid whereas this should be valid IMO.

```
curl -X POST https://mysite.com \
--body {
  "foo": "http://127.0.0.1/someEndpoint"
}
```

Just because `127.0.0.1` is found in the curl `body` doesn't mean this should be an invalid request.

**Comment by thisthat** [comment]
Hey @agardnerIT, thank you for the report. We are aware of this limitation and it is planned to be solved with Keptn 0.15. You can follow the relative ticket here: https://github.com/keptn/keptn/issues/7239
The idea is to provide the users with a more fine-grained configuration of which URLs are forbidden.
