### ISSUE TITLE
`keptn upgrade` should not display the warning about CLI and cluster mismatch

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#7419]
### Enhancement

The `keptn upgrade` command should not display the warning: *Your Keptn CLI version (0.13.1) and Keptn cluster (0.12.0) don`t match ... * because at this point of time the CLI will always be ahead of the cluster:

![image (3)](https://user-images.githubusercontent.com/729071/162686062-e5a63d5e-0e2e-45cb-9ecf-da649f52dc66.png)

### Defintion of Done: 
- [ ] `keptn upgrade` does not display the warning message.

**Comment by Lucifergene** [comment]
I would like to work on this issue

**Comment by thisthat** [comment]
This ticket is superseded by the work done in https://github.com/keptn/keptn/issues/7846
