### ISSUE TITLE
Bridge: Transform SSH string of GitHub

### ISSUE THREAD

**Issue by Kirdock** [keptn/keptn#7423]
## Technical Details

Currently, the SSH string that is provided by GitHub is not supported `git@github.com:Kirdock/my-new-ssh-project.git`. To tackle this the input should be transformed (on input or on paste) to be a valid one `ssh://github.com/Kirdock/my-new-ssh-project.git`.

## Acceptance Criteria
- [ ] The SSH string provided by GitHub is transformed into a valid one
- [ ] Add a notification toast about the "change" 

## Definition of Done
- [ ] Acceptance criteria are met
- [ ] Unit tests

**Comment by thisthat** [comment]
Questions: 
1. Should the API handle that?
2. How to show the changes in the UI?
3. Which formats are supported?

**Comment by thisthat** [comment]
The decision from the team: the UI should not care about this.
