### ISSUE TITLE
go-sdk: use `cp-connector` to connect to keptn

### ISSUE THREAD

**Issue by warber** [keptn/keptn#7434]
Currently the experimental [go-sdk](https://github.com/keptn/keptn/tree/master/go-sdk) is, like every other regular keptn service relying on the `distributor` to communicate with Keptn. With the introduction of `cp-connector` however the `distributor` is not required anymore. Hence, the `go-sdk` shall be adopted to use `cp-connector` internally.

## Acceptance Criteria
- `go-sdk` is using `cp-connector` internally
- Keptn Service written in using `go-sdk` can run without a `distributor`

## DoD

- [x] Webhook-, remediation-, approval-svc don't use the distributor
- [ ] Integration tests are adapted
- [x] Extend the unit tests in the SDK
- [ ] Manual test of installing/upgrading via helm w/ and w/o `--reuse-values`

**Comment by bacherfl** [comment]
putting back into the backlog for now since we have to complete #7530 first
