### ISSUE TITLE
RFE: Provide default sorting of services (e.g., by name) on Uniform screen

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#7442]
In Keptn 0.12.6, I noticed that there is no proper default sorting on the Uniform screen, e.g.:

* Installation A: 
![image](https://user-images.githubusercontent.com/56065213/162912213-2e685100-9677-4077-ab1f-a50ffc071376.png)

* Installation B: 
![image](https://user-images.githubusercontent.com/56065213/162912250-299e2fb5-eb27-4b4e-ad71-848f59ea5e58.png)

# RFE: Sort uniform screen by name

I think a default sorting, e.g., by name, would make perfect sense for Uniform screen. Whether this is done via API or in the UI, doesn't matter.

**Comment by shardulsrivastava** [comment]
/assign
i would like to work on this.

**Comment by shardulsrivastava** [comment]
@thisthat can I work on this pls ?

**Comment by thisthat** [comment]
Hey @shardulsrivastava sure thing! Thanks for helping us out :)

**Comment by rakshitgondwal** [comment]
Hey @shardulsrivastava !! Are you still working on this issue?

**Comment by meenaljain0303** [comment]
if this issue is still open, please assign it to me.

**Comment by shardulsrivastava** [comment]
@rakshitgondwal i will raise the PR in the next few fays

**Comment by shardulsrivastava** [comment]
Had a few hiccups setting up `keptn`, raise a couple of issues to fix the outdated docs.

https://github.com/keptn/keptn/issues/9324
https://github.com/keptn/keptn/issues/9325
