### ISSUE TITLE
Ansible Tower has API token in clear text inside inventory

### ISSUE THREAD

**Issue by kristofre** [keptn/keptn#75]
**Is your feature request related to a problem? Please describe.**
Dynatrace API tokens are entered in clear text inside ansible tower inside the "inventory" Inventory. 

**Describe the solution you'd like**
Use a custom "Credential Type" for the API token and store the token in an instance of that. Attach the credential to the job templates

**Comment by jetzlstorfer** [comment]
switched to encrypted storage in version 0.1.1
