### ISSUE TITLE
Delete notifications with autofocus on input field and delete button

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#7521]
## User story

As a user, I click on `Delete this service` or `Delete this project` button that opens a notification: 

![image](https://user-images.githubusercontent.com/729071/163968064-a6d80d82-e905-481f-827d-72b6fc669dc6.png)

In this notification, I have to click in the input field to enter the name of the service/project and an additional click to delete it. 

## UX improvement

* Use `autofocus` to focus the input field --> Consequently, no need to click the input field and the user can immediately start to enter the service/project name.
* After the service/project name is entered correctly, the **delete** button gets activated. Allow confirming the deletion by focusing the button. Hence, the user can just hit the *Enter* key without an extra click. 

## Defintion of done: 
![image](https://user-images.githubusercontent.com/729071/163968892-3441d83f-3c7c-48bc-8619-7534f49c2d6c.png)
- [ ] Autofocus of input field
- [ ] Focus on **Delete** button

* For both: deletion of project and service

**Comment by arishmaurya** [comment]
@johannes-b  can i take up this issue ?

**Comment by TannerGilbert** [comment]
@arishmaurya are you still working on this or can someone else take up this issue?

**Comment by lavakush07** [comment]
Hello @TannerGilbert Can I take up this issue ?

**Comment by thisthat** [comment]
Thank you @lavakush07 for volunteering :) i have assigned the issue to you!

**Comment by TannerGilbert** [comment]
@lavakush07 If you need any help, feel free to ask. If you haven't installed Keptn yet, take a look at the [Keptn documentation](https://keptn.sh/docs/install/) or the [install master](https://github.com/keptn/keptn/blob/master/docs/developer/install_master.md) guide.

**Comment by lavakush07** [comment]
Thank you @TannerGilbert for asking. I have installed the keptn✅. If I get stuck anywhere I would ping here for sure.

**Comment by TannerGilbert** [comment]
@lavakush07 are you still working on this?
