### ISSUE TITLE
go-utils: no method available for creating an `APIHandler` that sends requests directly to the shipyard-controller

### ISSUE THREAD

**Issue by arthurpitman** [keptn/keptn#7537]
**Is your feature request related to a problem? Please describe.**
I'm currently refactoring the dynatrace-service to use go-utils for accessing all Keptn APIs. While most handlers offer a way to work directly within the control-plane, `APIHandler` does not.

**Describe the solution you'd like**
A method like `NewAPIHandler` which creates an `APIHandler` that works directly with the shipyard-controller.

**Comment by thisthat** [comment]
https://github.com/keptn/go-utils/pull/449 fixed this
