### ISSUE TITLE
Cannot add big resources to Keptn

### ISSUE THREAD

**Issue by Raffy23** [keptn/keptn#7567]
**Environment**

* Client OS (e.g., Linux, macOS, Windows): Linux
* Keptn Version (`keptn version`): 0.13.1
* Kubernetes Cloud Provider (e.g., GKE, AKS): k3d
* Kubernetes version (`kubectl version`): Client: v1.23.5; Server: v1.22.6+k3s1

**Affected Component**

* [ ] Approval
* [ ] Bridge
* [x] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [x] REST API
* [ ] Webhook

**Describe the bug**

It is not possible to add bigger resources to Keptn via the Keptn CLI or the go-client.
All resources seem to be limited to around 768KiB and will be rejected with the following message:
```
Adding resource random-ascii.txt to all stages of project test-project
Error: Resource random-ascii.txt could not be uploaded: invalid character '<' looking for beginning of value
-----DETAILS-----<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**To Reproduce**

1. Create a random file, I used the following command to generate a random ascii file:
`base64 /dev/urandom -w0 | head -c $((1024*1024)) > random-ascii.txt`
2. Add the generated file to a already existing keptn project: `keptn add-resource --project=test-project --service=test-service --all-stages --resource=random-ascii.txt --resourceUri=random-ascii.txt`
3. See error

**Expected behavior**

Adding bigger resources to a Keptn project should work and not display an error.

**Current behavior**

Adding big resources yields an error

**Additional context**

We have a use-case for the job-executor-service which requires us to upload multiple bigger (>1MiB) files to Keptn, such that they can be used in the defined jobs. With the current behavior this is not possible.

**Comment by thisthat** [comment]
Thank you for the report @Raffy23. For the moment, I would suggest changing the `nginx.conf` configMap adding `client_max_body_size 5M;` to the `server` directive of Nginx.  Please change the size according to your requirements.
