### ISSUE TITLE
Keptn Full Tour on Prometheus - Event timing out

### ISSUE THREAD

**Issue by rjrosa** [keptn/keptn#7575]
**Environment**

Environment: EKS, 2 worker nodes, m5-Large, autoscaler, max node 12. 
* Client OS (e.g., Linux, macOS, Windows): MAC
* Keptn Version (`keptn version`): CLI:  0.14.1, Keptn: 0.14.0
* Kubernetes Cloud Provider (e.g., GKE, AKS): AKS
* Kubernetes version (`kubectl version`): v1.23.5

**Affected Component**

* [ ] Approval
* [ ] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [X] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**
Keptn Full Tour on Prometheus. I was not able to pass demo step 10 Deploy your first build with keptn. Events timeout.  No pods were created.   

**To Reproduce**
Run demo issue was found in step 10. 
https://tutorials.keptn.sh/tutorials/keptn-full-tour-prometheus-011/index.html?index=..%2F..index#9

**Expected behavior**
Pods were created and status of each task shown in the bridge.

**Current behavior**
Pods not created,  bridge shows events timeout.

**Screenshots**
![image](https://user-images.githubusercontent.com/102756323/165392216-cd17b742-e6d3-4e78-a905-ea3ddd31fc52.png)

**Comment by Dynatrace-Adam-Gardner** [comment]
@rjrosa I've just followed the tutorial and it works for me.

My theory is that the helm-service is (for some reason) not listening for the `sh.keptn.event.{taskname}.triggered` event (eg. `sh.keptn.event.deployment.triggered`) and so no deployment actually ever occurs and the sequence times out.

If you click a `delivery-direct` sequence tile, you do see the helm service responding to the `delivery` cloud event as my screenshot shows or is your box empty (ie. it just shows the `delivery` event but nothing actioning that event?)

![image](https://user-images.githubusercontent.com/13639658/165411264-24406358-e5c1-4113-befe-a6b7bd93c16b.png)

If so, please check that the subscriptions on the `helm-service` are accurate. Click the 4th icon down (the square one) and highlight the `helm-service` and it should be subscribed to the events shown below:

![image](https://user-images.githubusercontent.com/13639658/165411385-218aa3ef-98c7-4044-83e6-2745a8dbf246.png)

## Background Info

To understand what is happening here, first look at the `shipyard.yaml` file in the upstream repo `main` branch. Humans (and other tools) trigger sequences in stages (bullet 1 below). Keptn services or "tooling that actions" responds to task events (bullet 2 below). In other words, when you run the following command, you are triggering the `delivery-direct` in the `dev` stage for the `sockshop` project. Nowhere are you explicitly telling Keptn which tool (helm) to use to **action** the deployment. That comes later by subscribing to events.

Now that you've triggered the `delivery-direct` sequence, Keptn knows due to the shipyard file, which tasks now need to run, so Keptn crafts and distributes a new cloudevent based on the task name to anyone listening. Here's where the `helm-service` comes in as it is configured during install (see above) to be listening for the `sh.keptn.event.deployment.triggered` event (among others). In which case `helm-service` "puts its hand up" and says "yes, I can handle a deployment task".

```
keptn trigger delivery --project=sockshop --service=carts-db --image=docker.io/mongo --tag=4.2.2 --sequence=delivery-direct
```

![image](https://user-images.githubusercontent.com/13639658/165412046-d448c696-81d0-470b-9ed9-8a2346a9191d.png)

**Comment by Dynatrace-Adam-Gardner** [comment]
@StackScribe some notes for your consideration as I went through the prometheus full tutorial:

## Step 3
Outdated Istio (uses `1.12.1`. Current Istio version is `1.13.3`). Does Keptn work with `1.13.3`?

## Step 4
Outdated Keptn CLI version:
`curl -sL https://get.keptn.sh | KEPTN_VERSION=0.11.4 bash`

## Step 5

Docs give pods as:
```
NAME                          READY   UP-TO-DATE   AVAILABLE   AGE
api-gateway-nginx             1/1     1            1           2m44s
api-service                   1/1     1            1           2m44s
approval-service              1/1     1            1           2m44s
bridge                        1/1     1            1           2m44s
configuration-service         1/1     1            1           2m44s
helm-service                  1/1     1            1           2m44s
jmeter-service                1/1     1            1           2m44s
lighthouse-service            1/1     1            1           2m44s
litmus-service                1/1     1            1           2m44s
mongodb                       1/1     1            1           2m44s
mongodb-datastore             1/1     1            1           2m44s
remediation-service           1/1     1            1           2m44s
shipyard-controller           1/1     1            1           2m44s
statistics-service            1/1     1            1           2m44s
```

Actual pods are slightly different:
```
Actual
NAME                    READY   UP-TO-DATE   AVAILABLE   AGE
api-gateway-nginx       1/1     1            1           8m23s
api-service             1/1     1            1           8m23s
approval-service        1/1     1            1           8m23s
bridge                  1/1     1            1           8m23s
configuration-service   1/1     1            1           8m23s
helm-service            1/1     1            1           7m15s
jmeter-service          1/1     1            1           6m59s
keptn-mongo             1/1     1            1           8m23s
lighthouse-service      1/1     1            1           8m23s
mongodb-datastore       1/1     1            1           8m23s
remediation-service     1/1     1            1           8m23s
secret-service          1/1     1            1           8m23s
shipyard-controller     1/1     1            1           8m23s
statistics-service      1/1     1            1           8m23s
webhook-service         1/1     1            1           8m23s
```

## Step 8:
Keptn 0.11.4 is not the latest version, nor is 0.12.7 (see output below when running `keptn create project`):

```
$ keptn create project sockshop --shipyard=./shipyard.yaml --git-user=$GIT_USER --git-token=$GIT_TOKEN --git-remote-url=$GIT_REMOTE_URL
Keptn CLI and Keptn cluster version are already on the latest version ( 0.11.4 )!
* Your Keptn CLI version: 0.11.4
* Keptn version 0.12.7 is available! Please visit https://keptn.sh/docs/0.12.x/operate/upgrade/ for more information.
```

## Step 12
Shouldn't we be using "keptn trigger deployment" not "kubectl apply"?
Docker image is available: `keptnexamples/cartsloadgenerator:0.1`

## Step 13
Outdated prometheus-service. Shouldn't this also use `keptn trigger deployment`?

```
prometheus-service should be 0.7.4 not 0.7.2
helm install -n keptn prometheus-service https://github.com/keptn-contrib/prometheus-service/releases/download/0.7.2/prometheus-service-0.7.2.tgz --wait
```

## Step 23:
`What we've covered` section isn't complete. Talks about project and quality gates but not self healing.

This wording is strange. A full tour but there's more that Keptn offers?

```
Thanks for taking a full tour through Keptn!
Although Keptn has even more to offer that should have given you a good overview what you can do with Keptn.
```

**Comment by rjrosa** [comment]
Hi Adam;

The demo is missing a step, adding the tools that will be used in step 10 (Helm).   Do you agree with me?

Thanks;




Robinson.

From: Robinson Rosa ***@***.***>
Date: Wednesday, April 27, 2022 at 11:09 AM
To: keptn/keptn ***@***.***>, keptn/keptn ***@***.***>
Cc: Mention ***@***.***>
Subject: Re: [keptn/keptn] Keptn Full Tour on Prometheus - Event timing out (Issue #7575)
Thanks for your feedback!

Helm-service nor Jmeter-service are not listed (snapshot bellow).  How do I subscribe Keptn events to tools (Helm, Jmeter, etc..)?  Is there CLI command or even better a yaml file template that I can use?  I was not able to find an option in Bridge to do so either:
***@***.***

Subscription to a triggered event Link: “deploy/service.yaml” is giving me a 404 Error.

https://keptn.sh/docs/0.8.x/integrations/custom_integration/#subscription-to-keptn-event

Thanks;




Robinson.



From: Adam Gardner ***@***.***>
Date: Tuesday, April 26, 2022 at 8:09 PM
To: keptn/keptn ***@***.***>
Cc: Robinson Rosa ***@***.***>, Mention ***@***.***>
Subject: Re: [keptn/keptn] Keptn Full Tour on Prometheus - Event timing out (Issue #7575)

@rjrosa<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frjrosa&data=05%7C01%7Crobinson.rosa%40madmobile.com%7C7f77538ca62e422ccc7108da27e22f13%7C0edabf895e1342c3abd6f687e9fe0f3a%7C0%7C0%7C637866149667637178%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=AKy7QlM6YsrZ21RKQaDbhPxv%2BvW%2FSIrfPDiDdxgl10o%3D&reserved=0> I've just followed the tutorial and it works for me.

My theory is that the helm-service is (for some reason) not listening for the sh.keptn.event.{taskname}.triggered event (eg. sh.keptn.event.deployment.triggered) and so no deployment actually ever occurs and the sequence times out.

If you click a delivery-direct sequence tile, you do see the helm service responding to the delivery cloud event as my screenshot shows or is your box empty (ie. it just shows the delivery event but nothing actioning that event?)

[image]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F13639658%2F165411264-24406358-e5c1-4113-befe-a6b7bd93c16b.png&data=05%7C01%7Crobinson.rosa%40madmobile.com%7C7f77538ca62e422ccc7108da27e22f13%7C0edabf895e1342c3abd6f687e9fe0f3a%7C0%7C0%7C637866149667637178%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hnDETINv1v6Tsl6hwK1HGDrTXxc8dibOTEB1fYWKtiU%3D&reserved=0>

If so, please check that the subscriptions on the helm-service are accurate. Click the 4th icon down (the square one) and highlight the helm-service and it should be subscribed to the events shown below:

[image]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F13639658%2F165411385-218aa3ef-98c7-4044-83e6-2745a8dbf246.png&data=05%7C01%7Crobinson.rosa%40madmobile.com%7C7f77538ca62e422ccc7108da27e22f13%7C0edabf895e1342c3abd6f687e9fe0f3a%7C0%7C0%7C637866149667637178%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=nRzNL65ZHGA4aMlw98pToV4SBg6jz%2BJWEH%2F%2BxXaFA4k%3D&reserved=0>

Background Info

To understand what is happening here, first look at the shipyard.yaml file in the upstream repo main branch. Humans (and other tools) trigger sequences in stages (bullet 1 below). Keptn services or "tooling that actions" responds to task events (bullet 2 below). In other words, when you run the following command, you are triggering the delivery-direct in the dev stage for the sockshop project. Nowhere are you explicitly telling Keptn which tool (helm) to use to action the deployment. That comes later by subscribing to events.

Now that you've triggered the delivery-direct sequence, Keptn knows due to the shipyard file, which tasks now need to run, so Keptn crafts and distributes a new cloudevent based on the task name to anyone listening. Here's where the helm-service comes in as it is configured during install (see above) to be listening for the sh.keptn.event.deployment.triggered event (among others). In which case helm-service "puts its hand up" and says "yes, I can handle a deployment task".

keptn trigger delivery --project=sockshop --service=carts-db --image=docker.io/mongo --tag=4.2.2 --sequence=delivery-direct

[image]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F13639658%2F165412046-d448c696-81d0-470b-9ed9-8a2346a9191d.png&data=05%7C01%7Crobinson.rosa%40madmobile.com%7C7f77538ca62e422ccc7108da27e22f13%7C0edabf895e1342c3abd6f687e9fe0f3a%7C0%7C0%7C637866149667637178%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=x1McxOvjqqLe8kxIOtHqzzqy4YXR6f4AsX%2FqJC02TOQ%3D&reserved=0>

**Comment by rjrosa** [comment]
Demo is missing the following verification in step # 10:
Check Bridge: setting/uniform/integrations for helm-service exist. If it does not, then download it from here: https://github.com/keptn/keptn/releases/tag/0.14.1

**Comment by rjrosa** [comment]
Delivery of carts time out. Only dev website was up:

{
  "data": {
    "project": "sockshop",
    "service": "carts",
    "stage": "dev"
  },
  "id": "d7dd9c85-b339-4493-8c1a-fd2d6c38f99f",
  "shkeptncontext": "a7ca2ecf-7024-4e51-bb77-0c0dc27d3297",
  "shkeptnspecversion": "0.2.4",
  "source": "shipyard-controller",
  "specversion": "1.0",
  "time": "2022-04-28T17:43:20.560Z",
  "triggeredid": "2313e205-18a7-4ef5-85ef-b4fc6b051ca3",
  "type": "sh.keptn.event.dev.delivery.finished"
}

No all the pod instances came up:

***@***.*** keptn % kubectl get pods --all-namespaces | grep carts-

sockshop-dev           carts-64466b8f55-mddd7                          1/1     Running            0          28m

sockshop-dev           carts-db-54b449c598-cqkfz                       1/1     Running            0          32m

sockshop-production    carts-db-54b449c598-sg5l6                       1/1     Running            0          31m

sockshop-staging       carts-db-54b449c598-pxqc9                       1/1     Running            0          31m


***@***.***

**Comment by thisthat** [comment]
Maybe @christian-kreuzberger-dtx can provide more support here being the maintainer of the prometheus-service

**Comment by christian-kreuzberger-dtx** [comment]
I'm not seeing a prometheus related problem here. It seems that `carts` is not starting in staging and production, and @rjrosa mentioned that the problem relates to helm-service.
