### ISSUE TITLE
Failed to resolve hostname and  check a server's availability error

### ISSUE THREAD

**Issue by swapnilkhaire333** [keptn/keptn#7581]
Failed to resolve hostname and  check a server's availability error

**Comment by thisthat** [comment]
Hi @swapnilkhaire333, could you please provide more information about your problem?

**Comment by swapnilkhaire333** [comment]
Hello Giovanni,

Can we have a quick remote session pls?

So that I will show you properly

Regards,
Swapnil

**Comment by thisthat** [comment]
Hey @swapnilkhaire333, sorry for the late reply, I miss your comment. 
Sure, please reach out to me over the Keptn slack and we can support you :)
