### ISSUE TITLE
Provide an official containerized CLI

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/keptn#7586]
Currently Keptn ships the CLI executable, but there is no container version for it. It would be great to have one so that it could be used in container environments to interact with Keptn.

Use-cases:

* Using externa Keptn instance, e.g. invoking Keptn sequences from Job Executor service
* Using Keptn CLI as a task in Tekton/GitHub Actions and other containerized automation systems

**Comment by thisthat** [comment]
The Keptn core team agreed on moving this into a keptn-contrib project.

**Comment by MdSahil-oss** [comment]
@thisthat What about this issue ? can I work on this.
