### ISSUE TITLE
Playbooks in configureAnsible script are in different location

### ISSUE THREAD

**Issue by kristofre** [keptn/keptn#76]
**Describe the bug**
The job templates refer to playbooks that are stored in scripts/playbooks/***.yaml.

playbooks are actually stored in install/scripts/playbooks/***.yaml

**Comment by jetzlstorfer** [comment]
in keptn v0.1 playbooks are located in scripts/playbooks/***.yaml.

**Comment by jetzlstorfer** [comment]
double checked. files are in correct folder in release-0.1.x branch. closing the issue.
