### ISSUE TITLE
Automatic E2E tests for Keptn

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#7608]
## Overall Goal
As a Keptn developer, I need a setup that allows continuous testing and evaluation of the Keptn core-components quality.

This requires:
- multiple managed clusters where tests can be run against the latest version of Keptn,
- continuous deployment of the master build of Keptn,
- notifications to the developers when bugs, regressions, or other failures are detected.

### Testing strategies

- E2E tests
- Chaos tests

### Setting up the infrastructure to automatically manage the testing clusters.
- https://github.com/keptn/keptn/issues/7478

### Provide the initial, limited, set of tests covering the basic use cases of Ketpn.

- https://github.com/keptn/keptn/issues/7606

## DoD
- As a Keptn operator, I don't need to manage the testing infrastructure.
- As a Keptn developer, I can create E2E tests and Chaos tests that are automatically continuously triggered.
- As a Keptn developer, I receive feedback periodically on functional and non-functional problems of the code.
- CLI and Bridge have a basic coverage via E2E test.

**Comment by MdSahil-oss** [comment]
@thisthat is this feature still needed to built ? if so the I would like to work on it :)

**Comment by DavidPHirsch** [comment]
@thisthat keep or close?
