### ISSUE TITLE
Long stage names cause a line break in stage tag on the sequence screen

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#7625]
### Status quo

When having multiple stages and long names, a line break happens in the "bubbles" on the sequence screen: 

![image](https://user-images.githubusercontent.com/729071/166412428-af7c9712-b8f4-470c-bf1a-ee82c4fbc565.png)

### Style improvements
- Introduction of max length to deal with long sequence names
- Displaying just 3 stages and hiding the others behind a `y more ...` label.

## DoD

- [ ] Names are shortened to fit without breaking the line and have `...` as a suffix
- [ ] Tooltip on hover shows the full (long) stage name
- [ ] Consider the case of too many stages that do not fit in the sequence view

**Comment by thisthat** [comment]
Resolved with #8524
