### ISSUE TITLE
(WIP) Improve  keptn documentation for developers

### ISSUE THREAD

**Issue by RealAnna** [keptn/keptn#7660]
- [x] Add instructions on setting up gitea and mockserver for local integration tests 
- [x] List needed environmental variables: KEPTN_API_ENDPOINT KEPTN_API_TOKEN
- [x] Swagger Documentation uses the correct models (e.g. `/uniform/registration/{integrationID}/subscription` has no model for the 200 case although it returns the subscription id)
- [x] Improve documentation for resource-service: benefits & how to enable

**Comment by sarahhuber001** [comment]
### Local Integration Tests
- Additional ENV Vars
   ````
   export AIRGAPPED_REGISTRY_URL=k3d-container-registry.localhost:12345
   export KEPTN_NAMESPACE=keptn
   ````
- Install Gitea
    - TODO: like at .github/workflows/integration_tests.yaml#Install Gitea
- Install Mockserver
    - TODO: like at .github/workflows/integration_tests.yaml#Install Mockserver
