### ISSUE TITLE
Bridge: Show full date on hover in sequence screen

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#7719]
## User Story

As a user, I'd like to know on which day a sequence/task was executed.

## Technical Details

In the sequence screen, stages have below them the timestamp of when a sequence was executed for that stage. Similarly, next to the task a timestamp is shown. The format is always `HH:MM`. 

In the best-case, it's usually clear that the sequence was executed within the same day (but you wouldn't be able to tell).
![image](https://user-images.githubusercontent.com/992621/167870695-f7cdbf99-7950-4fe3-a332-30c0808172b4.png)

In the worst-case, sequences span multiple days:
![image](https://user-images.githubusercontent.com/56065213/167871975-675c2205-1426-4aa6-a409-06bdd074ce1d.png)

## Acceptance Criteria

- When the user hovers over a timestamp, it should show a tooltip with the full date in the `YYYY-MM-dd HH:mm:ss` format

## DoD

- [ ] Acceptance criteria are met

**Comment by ShivamTyagi12345** [comment]
/assign
i would like to work on this

**Comment by mehabhalodiya** [comment]
@ShivamTyagi12345 can you please post if you have any updates on this?

**Comment by ShivamTyagi12345** [comment]
I have attempted to set up the project locally, but due to campus placements, I have not been able to continue. I apologize for the inconvenience, and I will make the necessary changes as soon as possible.

**Comment by TannerGilbert** [comment]
Hi @ShivamTyagi12345 do you need any help implementing this?

**Comment by ShivamTyagi12345** [comment]
please expect an update within the next hour. Thanks a lot for your patience

**Comment by ShivamTyagi12345** [comment]
![Uploading image.png…]()
@TannerGilbert if you can please help me resolve this

**Comment by TannerGilbert** [comment]
@ShivamTyagi12345 Please follow the [install master](https://github.com/keptn/keptn/blob/master/docs/developer/install_master.md) guide to install Keptn for development and use version `0.18.1-dev` (current development version)

**Comment by thisthat** [comment]
Hey @ShivamTyagi12345, are you still interested in working on this feature?
