### ISSUE TITLE
Shipyard-controller skipped a sequence

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#7767]
**Environment**

* Keptn Version (`keptn version`): `0.15.0`

**Affected Component**

* [x] Shipyard-controller

**Describe the bug**

Keptn skipped a sequence even though it has an older timestamp: 

![image](https://user-images.githubusercontent.com/729071/168749199-09dd57df-dea4-4626-a7ef-ddc5fc2138f4.png)

**To Reproduce**
* Trigger a delivery sequence multiple times. I triggered it for `carts-db` as well as `carts`:
```
keptn trigger delivery --project=sockshop --service=carts --image=docker.io/keptnexamples/carts:0.13.3
keptn trigger delivery --project=sockshop --service=carts-db --image=docker.io/mongo:4.2.2 --sequence=delivery-direct
keptn trigger delivery --project=sockshop --service=carts --image=docker.io/keptnexamples/carts:0.13.2
keptn trigger delivery --project=sockshop --service=carts --image=docker.io/keptnexamples/carts:0.13.1
```

**Expected behavior**
* The sequences are executed in the same order they were triggered

**Current behavior**
* For some reason, the sequence for `carts:0.13.1` was overtaken by `0.13.1`

**Comment by odubajDT** [comment]
Problem reproducible also with current master
