### ISSUE TITLE
secret-service: Deleting a secret does not remove it from the respective role

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#7786]
**Environment**

* Client OS (e.g., Linux, macOS, Windows): Linux
* Keptn Version (`keptn version`): 0.14.2
* Kubernetes Cloud Provider (e.g., GKE, AKS): K3d 1.21
* Kubernetes version (`kubectl version`): 1.21

**Affected Component**

* [x] secret-service

**Describe the bug**

When deleting a secret, it is not removed from the respective role. Worst-case, we end up having the same secret multiple times within the role.

**To Reproduce**

* Create secret
```bash
$ keptn create secret secret-1 --scope="keptn-prometheus-service" --from-literal="KEY=VALUE" 
```
* Verify role
```bash
$ kubectl -n keptn get role keptn-prometheus-svc-read -oyaml
...
rules:
- apiGroups:
  - ""
  resourceNames:
  - secret-1
  resources:
  - secrets
  verbs:
  - get
```
* Delete secret
```bash
$ keptn delete secret secret-1
```
* Verify role again - secret-1 is still in there
* Add secret again
```bash
$ keptn create secret secret-1 --scope="keptn-prometheus-service" --from-literal="KEY=VALUE" 
```
* Verify role
```bash
rules:
- apiGroups:
  - ""
  resourceNames:
  - secret-1
  - secret-1
  resources:
  - secrets
  verbs:
  - get

```

**Expected behavior**

`secret-1` should be removed when we call `keptn delete secret`

**Current behavior**

`secret-1` stays in the role, and is duplicated over and over again

**Comment by warber** [comment]
Problem here is, that the secret was created with scope "keptn-prometheus-service" and deleted without giving a scope (then scope "keptn-default" will be applied. The secret is deleted tho. But it cannot update the references wrt to roles and stuff bc it's using the wrong scope.

**Comment by christian-kreuzberger-dtx** [comment]
> Problem here is, that the secret was created with scope "keptn-prometheus-service" and deleted without giving a scope (then scope "keptn-default" will be applied). 

Understood. If that's the case, we should check and alarm the user in case of a wrong scope.

> The secret is deleted tho. 

Exactly... this leads to an inconsistent state, and also duplicates.

I'm fine with setting `keptn delete secret ... --scope=keptn-prometheus-service`, but I think secret-service should check that the secret scope is correct before deleting the secret.

**Comment by warber** [comment]
> I'm fine with setting keptn delete secret ... --scope=keptn-prometheus-service, but I think secret-service should check that the secret scope is correct before deleting the secret.
sure :)
