### ISSUE TITLE
Refactor Lighthouse Service to use `go-sdk` 

### ISSUE THREAD

**Issue by warber** [keptn/keptn#7790]
## Action Items
* Refactor Lighthouse Service to make use of `go-sdk` like it is already done for webhook service or remediation service.
* Test Task Handler using FakeKeptn of the `go-sdk`
* Identify integration tests that could be removed bc functionality is covered enough via the FakeHandler tests

## Potential Blockers

- [ ] SDK might not be able to provide the feature to wait for specific events (mini event orchestrator) -> KEP (tbd) will solve this issue moving away this responsibility from the svc

## DoD 
- [ ] The lighthouse uses the SDK
- [ ] Integration tests for lighthouse are moved to component tests

**Comment by thisthat** [comment]
The go-sdk shall not provide any workflow capability, hence `lighthouse` cannot make use of the go-sdk.
