### ISSUE TITLE
Identify and replace obsolete wh-service integration tests with TaskHandler tests using `go-sdk`

### ISSUE THREAD

**Issue by warber** [keptn/keptn#7791]
# Action Item

In order to reduce the number of integration tests and replace them with faster, yet equally valuable component tests, 
* identify which existing integration tests for the webhook service can be replaced by fast task handler tests using the FakeKeptn component of `go-sdk`.
* Implement respective Task Handler tests.

**Comment by thisthat** [comment]
This will be done with https://github.com/keptn/keptn/issues/7822
