### ISSUE TITLE
Bridge :: Header - Remove polling of projects

### ISSUE THREAD

**Issue by laneli** [keptn/keptn#7804]
In the header there is a polling in place to fetch all projects to show them in the dropdown. This can be removed and replaced with an initial fetch on page load.

## Acceptance criteria
- [ ] Remove polling for projects in header
- [ ] Load projects on initial page load
- [ ] Trigger local update of project list when project is created or deleted via bridge
- [ ] Create follow up issue to only fetch project names

## DoD
- [ ] Acceptance criteria implemented
- [ ] Unit tests adapted to test project creation/removal
- [ ] UI tests adapted/introduced to test project creation/removal

**Comment by ermin-muratovic** [comment]
The `AppHeaderComponent` is actually not polling for projects. The projects are loaded once in `AppComponent` and should be reloaded everytime when the user visits the `ProjectBoardComponent`. Therefore this issue is obsolete.
