### ISSUE TITLE
Generalization of showing a running sequence

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#7854]
### Use case

As a user, I want to see a sequence that is currently running on my deployed artifact. 

For example: When a remediation sequence is running, we currently display it as follows: 
![image](https://user-images.githubusercontent.com/729071/170065144-f8b9223b-e506-420c-ae4f-b0c5c95ab684.png)

Instead of focusing on `remediation` only (which is very opinionated), it helps to show any sequence that is executed on an already deployed artifact. Therefore, a replacement of the **red icon** with a **loading icon** can solve this request:

![image](https://user-images.githubusercontent.com/729071/170066076-b4c1537b-bdd2-4394-9d61-8a32942d17b7.png)

### Definition of Done
- [x] Any kind of sequence that is happening after a deployment is finished is displayed on the service screen
- [x] Any kind of sequence that is currently running (and not a deployment) is visualized using a loading icon
- [x] Adapt tests

**Comment by thisthat** [comment]
For having the icon on the left-hand side, Bridge requires an additional API call. Is the icon really needed @johannes-b? Would it be ok to don't show any icon there?

**Comment by johannes-b** [comment]
@thisthat , thanks for the hint. 

Concerning performance implications, I would rather vote for not doing the API call. Consequently, we don`t show the icon on the left-hand side.
