### ISSUE TITLE
keptn oauth logout requires me to log in

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#7882]
Not sure if it classifies as a bug, but I believe so. Maybe it's intended oauth behaviour though...

With Keptn 0.15.0 CLI I tried to logout from an oauth endpoint, e.g.:
```
keptn auth --oauth --oauth-logout
```

# How to reproduce

1. Log in with the CLI via oauth
2. Wait a day or two (such that your token is expired and you would have to re-login) 
3. Try to logout using the CLI
4. Alternatively, try to connect your CLI to another cluster, e.g., `keptn auth --endpoint=http://10.201.2.2.nip.io --api-token=$(kubectl get secret keptn-api-token -n keptn -ojsonpath={.data.keptn-api-token} | base64 --decode)`

# Current behaviour

This opens a login page on the oauth provider.

# Expected behaviour 

I would have expected that it just logs me out, or at least it just removes the oauth configuration from my system. The token was expired anyway...

**Comment by thisthat** [comment]
Hey @christian-kreuzberger-dtx, the `--oauth` flag is responsible to starts the login process so it is the expected behavior. 
You should only use the `--oauth-logout` flag

**Comment by christian-kreuzberger-dtx** [comment]
Using `keptn --oauth-logout` (using Keptn CLI 0.15.1) leads to the same behaviour. I'm asked to login.

Essentially, it's not possible for me to get rid of an oauth setting here...

**Comment by christian-kreuzberger-dtx** [comment]
The panic is/was caused by #8102
