### ISSUE TITLE
keptn trigger sequence invalid helper text / unnecessary --sequence flag

### ISSUE THREAD

**Issue by agardnerIT** [keptn/keptn#7884]
@afzal442 @odubajDT FYI

The `keptn trigger sequence` help text is invalid. It leads me to believe that `keptn trigger sequence delivery --project fulltour --service helloservice --stage qa` is valid whereas in fact the command needs to be `keptn trigger sequence delivery --sequence delivery --project fulltour --service helloservice --stage qa`

Is the flag even required if we're passing the sequence name after `keptn trigger sequence foo` it seems like pointless duplication to have that flag.

Affects keptn 0.15.0 and higher.

**Comment by thisthat** [comment]
Thank you @agardnerIT for the bug report! The `--sequence` flag should be considered optional
