### ISSUE TITLE
Bridge :: Configure Auth message

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#7924]
## Technical Details

In #6069, we introduced OAuth support. Keptn operators that want to make use of this feature, need to configure the Bridge with several additional values, such as the discovery URL. The CLI needs these values as well. Hence, the Bridge should allow configuring the Auth input field:

![image.png](https://images.zenhubusercontent.com/613622dc41f39751c08348ad/d7b18223-5f51-4b75-8958-596f78e98ebe)

## Acceptance Criteria

- [ ] A new `bridge.auth_msg` helm value is added to our installer with default value an empty string
- [ ] The Bridge deployment has a new env var `AUTH_MSG` that is set by `bridge.auth_msg`
- [ ] If `AUTH_MSG` is empty, then the Bridge shows the current auth message
- [ ] If `AUTH_MSG` is **not** empty, then the Bridge shows the value of `AUTH_MSG` in the input field

## DoD

- Unit tests
- UI test

**Comment by heinzburgstaller** [comment]
@thisthat I changed the installer var name a bit to match the current patterns:
```
            - name: AUTH_MSG
              value: {{ .Values.bridge.authMsg | default "" }}
```
