### ISSUE TITLE
`cp-connector`: flush buffered bytes when shutting down nats event source

### ISSUE THREAD

**Issue by warber** [keptn/keptn#7953]
It is possible that clients using the `cp-connector` lib will miss to send out pending messages to the event broker, e.g. when shutting down. The nats event source implementation of `cp-connector` already provides a `Stop()` method that can be used to disconnect from the event broker, however before doing it, it should make sure that pending messages are flushed before closing the connection. (see nats `Flush()/FlushWithContext()`. Further `eventsource::stop()` shall be called when canceling the `controlplane` component.

## Acceptance Criteria
When shutting down the `cp-connector` library, pending messages are flushed before actually closing the connection.

**Comment by bacherfl** [comment]
Resolved by https://github.com/keptn/go-utils/pull/496
