### ISSUE TITLE
Heading 'Git upstream repository' is duplicated in the project settings

### ISSUE THREAD

**Issue by heinzburgstaller** [keptn/keptn#7969]
**Environment**

* Client OS (e.g., Linux, macOS, Windows): Linux
* Keptn Version (`keptn version`): Keptn CLI version: 0.15.0, Keptn cluster version: 0.15.0
* Kubernetes Cloud Provider (e.g., GKE, AKS): GKE
* Kubernetes version (`kubectl version`):

**Affected Component**

* [ ] Approval
* [x] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**
Heading 'Git upstream repository' is duplicated in the project settings.

**To Reproduce**
Go to settings page

**Expected behavior**
Only one heading.

**Current behavior**
Duplicate heading

**Screenshots**
![image](https://user-images.githubusercontent.com/7067172/171619756-99a39830-a93b-45bd-adda-c65c3834bd3f.png)

**Comment by heinzburgstaller** [comment]
@thisthat which headline should be kept? With or without red asterisk?

**Comment by thisthat** [comment]
Hey @heinzburgstaller thank you for the question :) 
If the automatic provisioning is enabled, without the red asterisk. Otherwise, if is disabled, with the red asterisk
