### ISSUE TITLE
Current screen breaks when clicking the user menu

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#7995]
**Environment**

* Keptn Version (`keptn version`): `0.16.0.next-1`

**Affected Component**

* [ x ] Bridge

**Describe the bug**
* When clicking on the user menu, the Bridge looks as follows: 

![image](https://user-images.githubusercontent.com/729071/171842067-5c2adc72-c69f-4ec5-bbff-1aac78ba2d33.png)

**Example**

* I'm on the screen: 
![image](https://user-images.githubusercontent.com/729071/171842699-6021a313-c96a-42fc-b5d8-d1b8fcdb7bd2.png)

* A click on the user menu (top right corner) results in: 

![image](https://user-images.githubusercontent.com/729071/171842782-70271d6e-3656-4f77-a877-a10870bfb5e4.png)

**Expected behavior**

* I see the underlying screen.

**Comment by johannes-b** [comment]
This same problem appears, when other overlays are opened too: 

![image](https://user-images.githubusercontent.com/729071/171843445-877433f4-06f8-4a21-b6ce-aad1d1040256.png)

**Comment by johannes-b** [comment]
For some reason, I cannot reproduce this behaviour.

**Comment by Kirdock** [comment]
> For some reason, I cannot reproduce this behaviour.

I can't reproduce it either so I guess those bugs were related to some caching in the browser. With https://github.com/keptn/keptn/pull/7794 we introduced another layer to the bridge that may have caused this bug.

**Comment by thisthat** [comment]
Let's monitor the situation with Keptn 0.17.0-next.0 if it still reproducible

**Comment by johannes-b** [comment]
With an upgrade to 0.17, the problem seems to be gone.
