### ISSUE TITLE
docs: Incorrect links to referenced command in sli.yaml and slo.yaml documentation

### ISSUE THREAD

**Issue by eyskim** [keptn/keptn#8000]
The links to the `keptn add-resource` command referenced in the [sli.yaml](https://keptn.sh/docs/0.15.x/reference/files/sli/) and [slo.yaml](https://keptn.sh/docs/0.15.x/reference/files/slo/) documentation incorrectly links to:
- https://keptn.sh/docs/0.15.x/reference/reference/cli/commands/keptn_add-resource

![image](https://user-images.githubusercontent.com/42628024/172153148-389d7c46-6e90-4aea-bb7f-36dbd64c7ea8.png)

I believe it's meant to link to:
- https://keptn.sh/docs/0.15.x/reference/cli/commands/keptn_add-resource

* [ ] Approval
* [ ] Bridge
* [ ] CLI
* [ ] Datastore
* [x] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Comment by thisthat** [comment]
This has been fixed
