### ISSUE TITLE
Blocked version.json causes setting Git upstream to fail

### ISSUE THREAD

**Issue by agardnerIT** [keptn/keptn#8001]
If `version.json` is blocked, creating a project fails when setting a Git upstream presumably because there is some dependancy between the `version.json` call and creating a project with an upstream.

* Keptn Version (`keptn version`): 0.15.1

**Affected Component**

* [ ] Approval
* [x] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

** Screenshots**
![image](https://user-images.githubusercontent.com/26523841/172287997-174775a5-74ae-4b7f-8f7b-7b478db3d822.png)

![image](https://user-images.githubusercontent.com/26523841/172288201-bbc53b5f-1c41-4e80-a95f-149551efce90.png)

Now unblock `version.json`:

![image](https://user-images.githubusercontent.com/26523841/172288671-7f2e0e3d-eaba-4fdc-988a-f808c5ef51af.png)

**Comment by Kirdock** [comment]
@agardnerIT did you block the `version.json` for your whole keptn installation or just for the bridge (e.g. via the browser)? For the bridge there isn't any dependency between the create-project and the `version.json` and the response also tells me that the core instead of the bridge failed here.
