### ISSUE TITLE
Core :: Cleanup tasks for resource/configuration-service - K8s service name

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#8082]
## Technical details

Subtask of #7827

## Action Items

- [x] Remove the old configuration-service `Service`

## DoD 

- [x] Acceptance criteria are met
- [x] Manual test that every pipeline works fine

**Comment by odubajDT** [comment]
Most of the pipelines are tested with integration tests run, zeroDowntime test run and CI, the non-tested are: release and pre-release pipelines, which should not be affected
