### ISSUE TITLE
Improve message in Bridge (0.16.0) when creating a new project

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#8106]
![image](https://user-images.githubusercontent.com/56065213/174298051-bd3e2088-92ee-4251-babe-717c19c47dbf.png)

Message reads:

> Your project needs a Shipyard. Add a file from your filesystem or drag & drop it here it add it to your project.

I think it should be 

> Your project needs a Shipyard. Add a file from your filesystem or drag & drop it here **to** add it to your project.

Relevant code:
https://github.com/keptn/keptn/blob/258c5a603498ef89d7c563298c68b9b273ec4a0f/bridge/client/app/_components/ktb-project-settings/ktb-project-settings-shipyard/ktb-project-settings-shipyard.component.html#L4-L7

**Comment by mehabhalodiya** [comment]
@christian-kreuzberger-dtx Can you please assign it to me?
