### ISSUE TITLE
Core :: Get rid of cp and sdk dependency hell

### ISSUE THREAD

**Issue by RealAnna** [keptn/keptn#8168]
The newcomers in our repo( cp-common, cp-connector) and our old friend go-sdk must be moved to their own separated repo, since updating dependencies has become quite bothersome. 

DoD

- [ ] the keptn repo pipelines are adapted (remove them from build, release, pre-release, and from codecoverage config file)
- [ ] the new repo has the minimum workflows/pipelines set up, such as in go-utils ( semantics checks, dependabot, go test, releases etc..)

**Comment by odubajDT** [comment]
resolved by https://github.com/keptn/keptn/commit/7b141c8d6f53136e023eaee2737a4a708f2125ca
