### ISSUE TITLE
Intelligently roll api-gateway deployment instead of always

### ISSUE THREAD

**Issue by mowies** [keptn/keptn#8215]
Right now, the `api-gateway-nginx` Deployment is always updated due to the `rollme` random hash in the helm chart.
This could be changed to make the whole update a little more intelligent.

The gateway only needs to be restarted if the nginx configmap was updated.

Solution:
- Extract the config out of the configmap into its own file
- as the `rollme` hash, use a hashsum of the nginx config file
- this way, only when the nginx config actually changes, the gateway is restarted

To be researched:
- How to create the configmap from an external file in helm (without kustomize)

**Comment by mowies** [comment]
good resource: https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments

**Comment by mowies** [comment]
nginx does not refresh its DNS cache once it started. This means that a restart is also necessary when any of the keptn k8s services are updated or recreated and their IP could possibly change in k8s. This would result in nginx not being able to forward requests correctly since it does not have TTLs on its DNS cached entries

**Comment by christian-kreuzberger-dtx** [comment]
Another alternative would be to implement a global health check that tries to reach all services, and rely on Kubernetes to restart the pod if the health check fails

**Comment by thisthat** [comment]
Given the high burden for little gain, we won't implement this
