### ISSUE TITLE
webhook-service: Add response as JSON object if content-type is application/json

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#8256]
**Status-quo**
Currently, the webhook-service embeds the response as a plain string in the event.

**What?**
However, especially if the response is of content-type `application/json`, it would be good to embed the JSON object in the event (not as string) to simplify further processing.

## DoD

- [x] Unit tests
- [x] Component Tests

**Comment by odubajDT** [comment]
According to investigation and consultation with @bacherfl we should be able to implement a feature, which checks if the content-type is `application/json` and if yes, it should try to unmarshal the responses to a JSON object. If we do not succeed, we should fallback to a string.
