### ISSUE TITLE
Ability to abort a current deployment

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#832]
**Is your feature request related to a problem? Please describe.**
When I realize that a new artifact that is currently running through the Keptn pipeline should be stopped for e.g: I called the CLI with a wrong artifact ID or there are some other objections against an artifact I want to be able to stop the continuous delivery in Keptn for that artifact

**Describe the solution you'd like:**
I want a CLI endpoint like this:
```
$ keptn send event stop-artifact ARTIFACT_KEPTN_CONTEXT
```

In order for this approach to work, the Keptn send event new-artifact would also need to return the keptn_context so that we can use it in subsequent interactions with Keptn.

**Comment by dirkwall** [comment]
We'll be able to do this with the KeptnEngine that can stop event propagation for a specific delivery flow identified by a keptn-context.

**Comment by warber** [comment]
I close this issue as this will be implemented in #3783 and #3785
