### ISSUE TITLE
Core :: Cleanup tasks for resource/configuration-service - Remove `keptn-configuration-service` ServiceAccount

### ISSUE THREAD

**Issue by bacherfl** [keptn/keptn#8327]
As of v0.18, the resource-service will use the `keptn-resource-service` ServiceAccount, which has the permission to read secrets in order to be able to read upstream credentials. In versions <=0.17, that service was using the `keptn-configuration-service` ServiceAccount, which is still needed in v0.18, because otherwise the pod running the v0.17 resource service will not be able to access any git upstream credentials during the upgrade from 0.17 to 0.18. 

After the release of 0.18, this `keptn-configuration-service` ServiceAccount can and should be removed.

# Action Items

- [x] Remove the `keptn-configuration-service` Service Account and its related RoleBindings

# DoD

- [x] Acceptance criteria are met
- [x] Test that Keptn works without such a SA
- [x] ZD tests work for updates from versions >=0.18 to the version including the changes introduced for this ticket

**Comment by odubajDT** [comment]
I guess this was already been done by this PR https://github.com/keptn/keptn/pull/8530

**Comment by odubajDT** [comment]
Resolved via https://github.com/keptn/keptn/pull/8530
