### ISSUE TITLE
Keptn 0.15.0 stuck at delivery/deploying (delivery timed out)

### ISSUE THREAD

**Issue by vadasambar** [keptn/keptn#8328]
**Environment**

* Client OS (e.g., Linux, macOS, Windows): Linux
* Keptn Version (`keptn version`):
```
Keptn CLI version: 0.15.0
...
```
* Kubernetes Cloud Provider (e.g., GKE, AKS): NA (minikube)
* Kubernetes version (`kubectl version`): 
```
Client Version: v1.23.1
Server Version: v1.22.3
```

**Affected Component**

* [ ] Approval
* [ ] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**

Keptn is stuck at delivery/deploying for more than 5m. Same service and deployment takes less than 2m on older Keptn version (0.11.x)
![image](https://user-images.githubusercontent.com/34534103/177707944-39a528e6-aa3c-4a38-a26c-e23020c6fccf.png)

**To Reproduce**

Here's what I did:
1. Install Keptn
```
helm repo add keptn https://charts.keptn.sh
kubectl create ns keptn
kubectl config set-context --current --namespace=keptn
helm install keptn keptn/keptn -f examples/keptn-values.yaml --version 0.15.0
```
keptn-values.yaml
```
continuous-delivery:
  enabled: true
control-plane:
  apiGatewayNginx:
    type: ClusterIP
  bridge:
    installationType: QUALITY_GATES,CONTINUOUS_OPERATIONS,CONTINUOUS_DELIVERY
  enabled: true
  # enable volumePermissions
  mongo:
    volumePermissions:
      enabled: true
```
2. Create project
```
keptn create project podtatohead --shipyard=./quickstart/shipyard.yaml
```
[shipyard.yaml](https://github.com/keptn-sandbox/datadog-service/blob/3a47aa7b24dd6ee6dd45bb681fc41b7f3d516ae9/examples/quickstart/shipyard.yaml)

2. Create service
```
keptn create service helloservice --project="podtatohead" 

```
3. Add helm chart resource
```
keptn add-resource --project=podtatohead --service=helloservice --all-stages --resource=./quickstart/helm/helloservice.tgz --resourceUri=helm/helloservice.tgz

```
[helloservice.tgz](https://github.com/keptn-sandbox/datadog-service/blob/e8818eea882dfa976a1c35993e1117f3ccff94c8/examples/quickstart/helm/helloservice.tgz) (I have just compressed the helm chart [here](https://github.com/keptn-sandbox/datadog-service/tree/e8818eea882dfa976a1c35993e1117f3ccff94c8/examples/quickstart/helm/helloservice) to create the zip)

4. Add test resources
```
keptn add-resource --project=podtatohead --service=helloservice --stage=hardening --resource=./quickstart/jmeter/jmeter.conf.yaml --resourceUri=jmeter/jmeter.conf.yaml
keptn add-resource --project=podtatohead --service=helloservice --stage=hardening --resource=./quickstart/jmeter/load.jmx --resourceUri=jmeter/load.jmx


```
[jmeter.conf.yaml](https://github.com/keptn-sandbox/datadog-service/blob/8d66901f4d4edc886e1b382e18386a9c7d4148c5/examples/quickstart/jmeter/jmeter.conf.yaml)
[load.jmx](https://github.com/keptn-sandbox/datadog-service/blob/3a47aa7b24dd6ee6dd45bb681fc41b7f3d516ae9/examples/quickstart/jmeter/load.jmx)
// Other things around setting up SLI provider, adding SLI and SLO etc., here (which I think are not related to the problem)
5. Trigger delivery
```
keptn trigger delivery --project=podtatohead --service=helloservice --image=docker.io/jetzlstorfer/helloserver:0.1.1
Starting to deliver the service helloservice in project podtatohead with image: docker.io/jetzlstorfer/helloserver:0.1.1
ID of Keptn context: 3bd09f5f-0ae2-4967-a06d-08bb2aa7e894
```

After 10m, the delivery times out like this
![image](https://user-images.githubusercontent.com/34534103/177709458-15f59e0a-d42f-427c-af4e-7b612aeea54c.png)

shipyard controller logs
```
time="2022-07-07T06:29:13Z" level=info msg="Received event of type sh.keptn.event.hardening.delivery.triggered from https://github.com/keptn/keptn/cli#configuration-change"
time="2022-07-07T06:29:13Z" level=info msg="Checking if sequence '.triggered' event should start a sequence in project podtatohead"
time="2022-07-07T06:29:14Z" level=info msg="Found matching task sequence delivery in stage hardening"
time="2022-07-07T06:29:15Z" level=info msg="Received event of type sh.keptn.event.deployment.triggered from shipyard-controller"
time="2022-07-07T06:40:03Z" level=info msg="sequence 3bd09f5f-0ae2-4967-a06d-08bb2aa7e894 has been timed out"
time="2022-07-07T06:40:03Z" level=info msg="Deleted event dd4c287f-43a5-4409-b0d5-332b5b48911a"
time="2022-07-07T06:40:03Z" level=info msg="Deleting all task.finished events of task sequence delivery with context 3bd09f5f-0ae2-4967-a06d-08bb2aa7e894"
time="2022-07-07T06:40:03Z" level=info msg="Deleted event 76aa53a1-ddd1-4ab6-b066-f947292ed6a8"
time="2022-07-07T06:40:03Z" level=info msg="Received event of type sh.keptn.event.hardening.delivery.finished from shipyard-controller"
```

**Expected behavior**
I expect the delivery not to time out. 

**Current behavior**
Delivery is timing out

**Screenshots**
Added above

**Comment by vadasambar** [comment]
I am not sure where to look to further debug this issue.

**Comment by grabnerandi** [comment]
Hi. Do you have any keptn service that is subscribing to the deployment.triggered event? Either the helm-service or whatever other service you want to use to do the actual deployment? 
Looking at your screenshot makes me wonder if the problem is not a keptn problem but just the fact that you dont have any tool that handles those events. 
You can validate your installed tools and active subscriptions by looking into the uniform screen

**Comment by vadasambar** [comment]
I missed installing jmeter-service and helm-service
I installed it like this:
```
helm install jmeter-service keptn/jmeter-service  --version 0.15.0
helm install helm-service keptn/helm-service --version 0.15.0
```

![image](https://user-images.githubusercontent.com/34534103/178203149-1c36f499-6a5d-4e61-8e42-bee22494c8ad.png)

I had a delivery stuck at `evaluation` even after installing the above 2 charts.
![image](https://user-images.githubusercontent.com/34534103/178203238-82e2680e-004b-4193-bfad-b76ab9f23439.png)

Shipyard controller said
```
time="2022-07-11T06:26:15Z" level=info msg="Sequence 15cbcb82-f6f4-4894-8f13-0be02bbfe887 cannot be started yet because sequences are still running in stage hardening"
```

Aborting and re-triggering the delivery worked for me. 

Keptn slack thread around this [here](https://keptn.slack.com/archives/CNRCGFU3U/p1657176659387959)
