### ISSUE TITLE
Core :: Webhook sends a started event although subscribed to finished event

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#8334]
Your issue may already be reported! Please search on the [issue tracker](https://github.com/keptn/keptn/issues) before creating a new one.

**Environment**

* Client OS (e.g., Linux, macOS, Windows):
* Keptn Version (`keptn version`): 0.17
* Kubernetes Cloud Provider (e.g., GKE, AKS):
* Kubernetes version (`kubectl version`):

**Affected Component**

* [ ] Approval
* [ ] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [x] Webhook

**Describe the bug**

I subscribed the webhook-service to the `evaluation.finished` event. Calling `/api/mongodb-datastore/event?keptnContext=af51de49-a9ee-48ea-b462-70fef60e2196` I see also a `evaluation.started` event sent by the webhook-service.

```json
{
  "events": [
    {
      "contenttype": "application/json",
      "data": {
        "message": "Evaluation failed since the calculated score of 0 is below the warning value of 75",
        "project": "prj",
        "result": "fail",
        "service": "service",
        "stage": "stage",
        "status": "succeeded",
        "temporaryData": {
          "distributor": {
            "subscriptionID": ""
          }
        }
      },
      "id": "96ea3fe3-c0eb-47b1-85f2-98939e1b3f8d",
      "shkeptncontext": "af51de49-a9ee-48ea-b462-70fef60e2196",
      "shkeptnspecversion": "0.2.4",
      "source": "webhook-service",
      "specversion": "1.0",
      "time": "2022-07-07T07:45:59.070704264Z",
      "triggeredid": "dc6bfb14-55b0-47e1-b63e-659373c5cc43",
      "type": "sh.keptn.event.evaluation.started"
    }
  ],
  "pageSize": 20,
  "totalCount": 1
}
```

**To Reproduce**

Configure a webhook subscription to `evaluation.finished`. Delete `webhook.yaml` from the repository without passing through Keptn. 

**Expected behavior**
No `started` event is sent

**Comment by agrimmer** [comment]
Relates to https://github.com/keptn/keptn/issues/8331
