### ISSUE TITLE
cp-connector: Deprecate/remove `Integration::RegistrationData()` method

### ISSUE THREAD

**Issue by warber** [keptn/keptn#8347]
Deprecate or Remove the [RegistrationData()](https://github.com/keptn/go-utils/blob/d9a621b678384a8a1e0e7fcbe2ddcfef292aaa87/pkg/sdk/connector/controlplane/controlplane.go#L36) method the user is required to implement. Instead let the user pass initial registration data directly when initializing the controlplane component, e.g. like:

```go
controlplane.New(subscriptionSource, eventSource, logForwarder, controlplane.WithRegistrationData(...))
``` 

Additionally there shall, be the possibility to load registration data from environment variables:

```go
controlplane.New(subscriptionSource, eventSource, logForwarder, controlplane.WithRegistrationDataFromEnv(...))
``` 

If no registration data is given, the service shall register itself without subscriptions.

## DoD

- [ ] Method `WithRegistrationData` is removed
- [ ] Method `WithRegistrationDataFromEnv` is provided
- [ ] Tests must be adapted

**Comment by thisthat** [comment]
We agreed that the benefits of breaking the current interface with the clients that are using the go-sdk has little value for the effort required in adapting the integrations.
