### ISSUE TITLE
Move CLI docs generation trigger into CI pipeline

### ISSUE THREAD

**Issue by mowies** [keptn/keptn#8372]
Since some time, the auto-generation of CLI docs doesn't work anymore in the docs repo. ([link](https://github.com/keptn/keptn.github.io/actions/workflows/auto-update.yml))
This is due to us skipping CI builds for pushed tags, and also a timing issue between a pushed tags and CLI artifact being built for it and the triggered auto generation which needs that CLI artifact.

This workflow could be fixed by moving the [`send-event-on-release-push.yml`](https://github.com/keptn/keptn/blob/master/.github/workflows/send-event-on-release-push.yml) pipeline into the CI pipeline with an if conditional so that it's only being run on (pre)releases. This way, we can be sure that the CLI artifact is already built.
Also, the `skip-ci` tag needs to be removed from the `versionrc` file to re-enable builds for release commits.

**Comment by rghdrizzle** [comment]
Hello , does this issue still persist ??

**Comment by mowies** [comment]
Hi @rghdrizzle 
The issue is heavily outdated, I will close it.
