### ISSUE TITLE
Deny list for Git remote upstream URLs

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#8422]
**What and why?** 
As a Keptn operator, I would like to be able to specify what Git providers must not be used. For example, when adopting Keptn within a company, I would like to prevent e.g. that the Keptn upstream repos are hosted at GitHub, Gitlab, etc. 

## Acceptance Criteria

- [x] A ConfigMap `keptn-git-config` is created with a key `git-remote-url-denylist`
- [x] A Helm value `features.tbd` fills the `git-remote-url-denylist` values, by default is empty
- [x] Each line of the `git-remote-url-denylist` should be handled as a regex. 
- [x] This ConfigMap shall be mounted to the shipyard-controller as a file via Volume.
- [x] When an API call setting/changing the Git remote upstream is performed, shippy reads the ConfigMap via the file and performs a validation.
- [x] When the Git remote upstream matches one of the values from `git-remote-url-denylist`, the API should return an [HTTP 422](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422) error.

## Technical Details

In the case of the automatic provisioned, the Git URL received is empty. Hence, repositories provided by the Automatic Provisioning service are not validated.

## **Definition of Done**
- [x] Unit Tests
- As an operator of Keptn, I can specify a denylist for Git remote upstream URLs e.g. using a regex during installation time

**Comment by odubajDT** [comment]
Note:
The way of setting the content of `git-remote-url-denylist` will be possible via `--set=Values.features.gitRemoteURLDenyList=<string>` only if we are considering a single line string (single denied `RemoteURL`). If we need to add multiple lines (multiple denied `RemoteURL`s), we need to create a second `values_patch.yaml` file and apply it via `--values` during the install command. More info here https://stackoverflow.com/questions/64682166/how-to-override-a-multi-line-string-with-set-in-helm-install-command

Example of the `values_patch.yaml` file:

```
features:
  gitRemoteURLDenyList: |-
    some
    randomizer
    data
```
