### ISSUE TITLE
Flag for specifying whether an on-demand provisioned Git repo URL is shown

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#8423]
**What and why?**
Keptn has the capability to provision on-demand Git repositories if no upstream URL is provided. However, those on-demand generated repositories are frequently not accessible from the internet. Hence, also the Git remote URL should not be exposed via the API of the shipyard-controller because might not be usable. Furhtermore, Keptn operators might want to lock the access to the repository only through Keptn's resource-service APIs to limit from how many points Keptn can be configured.  

## Acceptance Criteria

 - [ ] The info if a project was automatic provisioned should be stored in the project data
 - [ ] When an automatic provisioned project has its Git URL changed, the project shall not be marked as automatic provisioned and its flag changes to `https` or `ssh` based on the mode. This flag will also be available via the APIs that return the project info.
 - [ ] When the env var `HIDE_AUTOMATIC_PROVISIONED_URL` is set to `true`, then the API will return an empty URL for the Git upstream
 - [ ] The `bool` value of `HIDE_AUTOMATIC_PROVISIONED_URL` can be set via the Helm value `features.automaticProvisioning.hideURL`
- [ ] Test that resource-service can switch between automatic provisioned, https, ssh remotes without failing / restarting

## **Definition of Done**
- Manual tests & Unit tests (integration test if necessary)
- As an operator of Keptn, I can choose whether the API returns the URL of on-demand provisioned Git repos

**Comment by odubajDT** [comment]
Putting this ticket back to backlog, as there are multiple questionmarks here

**Comment by odubajDT** [comment]
open questions:
- How the `mode` should look like, where should it be placed?
- Should it be a required parameter? If yes, there is a need to to implement a transformer for older projects
- Should it be a read-only parameter or R/W ?
- Are there any changes required in the Bridge?

**Comment by odubajDT** [comment]
Note: the team decided no to implement the mode feature as described in this issue. It should be enough to add information whether the upstream was provisioned to the ExpandedProject model (store it only into the DB) and hide the git URL and the user when the `HIDE_AUTOMATIC_PROVISIONED_URL` is set to true
