### ISSUE TITLE
Bridge: Docs for Version Check can not be reached

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#8431]
This is with Keptn 0.16, but I guess it also affects 0.15 and 0.14. Keptn 0.13 is the last version that had the URL available.

![image](https://user-images.githubusercontent.com/56065213/178988729-4095a2a4-e050-4113-92eb-de07dfea65b3.png)

The existing URL https://keptn.sh/docs/0.16.x/reference/version_check/ is not reachable and leads to a 404.

**Comment by thisthat** [comment]
Moving this on the website since we don't have that page anymore
