### ISSUE TITLE
Bridge does a line break on evaluation history when running in quality gates only mode

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#8437]
**Environment**

* Keptn Version (`keptn version`): 0.16.1

**Affected Component**

* [ x ] Bridge

**Describe the bug**
* When using Keptn for quality gates only, a message is displayed on the environment screen: `Use [keptn trigger evaluation](https://keptn.sh/docs/0.16.x/reference/cli/commands/keptn_trigger_evaluation/) to trigger a quality gate evaluation.`

* Unfortunately, this message is causing line breaks on the evaluation result history: 

![image](https://user-images.githubusercontent.com/729071/179178782-d5cea719-83e9-4534-a3c7-48ee550e6455.png)

**Expected behaviour**
* The evaluation result history is always shown in a row.

**Comment by Kirdock** [comment]
This is related to https://github.com/keptn/keptn/issues/7013. I'll address both
