### ISSUE TITLE
Core :: Adapt pipelines removing helm and jmeter services

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#8439]
## Technical Details

With the moving out of Helm and JMeter services #7845, the Keptn core pipelines need some changes.

## Acceptance Criteria
The following pipelines need to be touched removing the references to these services:

- [x] [CI](https://github.com/keptn/keptn/blob/master/.github/workflows/CI.yml)
- [x] [Pre-Release](https://github.com/keptn/keptn/blob/master/.github/workflows/pre-release.yml)
- [x] [Release](https://github.com/keptn/keptn/blob/master/.github/workflows/release.yml)
- [x] [Zero Downtime tests](https://github.com/keptn/keptn/blob/master/.github/workflows/zero-downtime-tests.yml)
- [x] [Dependencies and Licenses](https://github.com/keptn/keptn/blob/master/.github/workflows/dependencies-and-licenses.yml)
- [x] [Semantic PR](https://github.com/keptn/keptn/blob/master/.github/workflows/validate-semantic-pr.yml)
- [x] [CodeCov](https://github.com/keptn/keptn/blob/master/codecov.yml)
- [x] [Build Helm Charts](https://github.com/keptn/keptn/blob/master/gh-actions-scripts/build-helm-charts.sh)
- [x] [Remove ingress-config.yaml](https://github.com/keptn/keptn/blob/master/installer/manifests/keptn/templates/ingress-config.yaml) and remove corresponding Helm values

## DoD

- [x] Helm and JMeter services are not built
- [x] Helm and JMeter services are not tested
- [x] Helm and JMeter services do not report code coverage

**Comment by mowies** [comment]
If the continuous delivery test is also removed during this ticket, we can also remove istio from the integration tests pipeline since it was only needed for helm service
