### ISSUE TITLE
keptn create secret usage instructions: small typo 

### ISSUE THREAD

**Issue by agardnerIT** [keptn/keptn#8469]
Small typo on the usage instructions for `keptn create secret`

Notice the additional `"`.

```
keptn create secret SECRET_NAME --from-literal="key1=value1"" --from-literal="key2=value2" --scope=my-scope [flags]
```

Please mark as a `good first issue`

**Comment by bhavyastar** [comment]
I would like to work on this issue. 😀
Would you please assign me?  @agardnerIT and @StackScribe

**Comment by vanshaj** [comment]
Hello @agardnerIT / @StackScribe 
I have raised a PR for this issue. Kindly review
PR ID - #8498 

Regards,
Vanshaj
