### ISSUE TITLE
Core :: Add filters to `GET /secret`

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#8474]
## Technical Details

Integrations rely on secrets to store private data. For example, to store an API token to work with an external tool.
The current APIs return the whole list of secrets stored into Keptn. If an integration has to check for a specific secret, it has to perform filtering on the client-side which is not ideal. Keptn should provide a filter on the server-side to allow for fewer data to transfer and facilitate the work of integrations.

## Acceptance criteria

- [x] `GET /secret` accepts two query parameters: `scope` and `name`
- [x] When the `scope` query parameter is set, only secrets belonging to that scope are returned
- [x] When the `name` query parameter is set, only secrets matching that name are returned
- [x] When both `name` and `scope` are set, secrets matching the name **and** the scope are returned
- [x] The swagger documentation is updated

## DoD
- [x] Unit tests
- [x] Manual API tests
- [x] `GET /secret` has filtering by name and/or scope

**Comment by warber** [comment]
@thisthat  For `v2` of our APIs (guidelines in review) there might be a dedicated "filter" parameter that accepts filter expressions that should be used for result filtering.
However, I think this proposal is OK for `v1`.
