### ISSUE TITLE
Bridge 0.17.0: Incorrect detection of pending changes when accessing project details of a project with auto-provisioned project

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#8493]
Using Keptn 0.17.0 and the [keptn-gitea-provisioner-service](https://github.com/keptn-sandbox/keptn-gitea-provisioner-service), I created a new project, e.g.:
```bash
keptn create project jes4 --shipyard=shipyard.yaml
```

This will auto create a repo and asign it to the project, e.g.:

# Current Behaviour

When editing the project in Bridge, something weird is happening and this seems to cause Bridge to think that I have changed some values:
![image](https://user-images.githubusercontent.com/56065213/180263840-a56394af-b30e-4a44-a1f5-5d680ab7af49.png)

# Expected Behaviour

As I did not change any values, I am not expecting the popup regarding unsaved changes

**Comment by ermin-muratovic** [comment]
This behavior might change with #8510

**Comment by ermin-muratovic** [comment]
Found the problem:

`this.dataChanged` is called when `this.selectedForm` is `GitFormType.NO_UPSTREAM`, which is only possible with `automaticProvisioning`. 

https://github.com/keptn/keptn/blob/c4845c9b568351ab2c93320095d4f061584b7463/bridge/client/app/_views/ktb-settings-view/ktb-project-settings/ktb-project-settings-git-extended/ktb-project-settings-git-extended.component.ts#L60-L62

@Kirdock do you remember why this was added by @laneli initially?

**Comment by Kirdock** [comment]
> Found the problem:
> 
> `this.dataChanged` is called when `this.selectedForm` is `GitFormType.NO_UPSTREAM`, which is only possible with `automaticProvisioning`.
> 
> https://github.com/keptn/keptn/blob/c4845c9b568351ab2c93320095d4f061584b7463/bridge/client/app/_views/ktb-settings-view/ktb-project-settings/ktb-project-settings-git-extended/ktb-project-settings-git-extended.component.ts#L60-L62
> 
> @Kirdock do you remember why this was added by @laneli initially? Otherwise we could get rid of this easily and in my opinion without any issues.

Yes. Else the selection and the required data is not emitted. Therefore if you select `NO_UPSTREAM` the create button would not be enabled without it

**Comment by Kirdock** [comment]
> > > Found the problem:
> > > `this.dataChanged` is called when `this.selectedForm` is `GitFormType.NO_UPSTREAM`, which is only possible with `automaticProvisioning`.
> > > https://github.com/keptn/keptn/blob/c4845c9b568351ab2c93320095d4f061584b7463/bridge/client/app/_views/ktb-settings-view/ktb-project-settings/ktb-project-settings-git-extended/ktb-project-settings-git-extended.component.ts#L60-L62
> > > 
> > > @Kirdock do you remember why this was added by @laneli initially? Otherwise we could get rid of this easily and in my opinion without any issues.
> > 
> > 
> > Yes. Else the selection and the required data is not emitted. Therefore if you select `NO_UPSTREAM` the create button would not be enabled without it
> 
> Ok, but then we need this just in `createMode`? Means `if (this.selectedForm === GitFormType.NO_UPSTREAM && this.isCreateMode) {`

No, the root cause is probably here:
https://github.com/keptn/keptn/blob/dd276ff4005d50a2b97bcbdd914b9b8580209b6b/bridge/client/app/_views/ktb-settings-view/ktb-project-settings/ktb-project-settings-git-extended/ktb-project-settings-git-extended.component.ts#L58

This should be changed to
```ts
this.selectedForm = !this.gitUpstreamRequired && this.isCreateMode ? GitFormType.NO_UPSTREAM : GitFormType.HTTPS
```
