### ISSUE TITLE
Core :: Remove code of Helm and JMeter services

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#8502]
## Technical Details 

The code of JMeter and Helm services should be removed since they have been moved into https://github.com/keptn-contrib/

## Dependencies

- [ ] Repos have been created over Keptn-Contrib
- [ ] (Pre-)Release automation in place for both repos
- [ ] PRs have been merged (e.g., https://github.com/keptn-contrib/helm-service/pull/2 and https://github.com/keptn-contrib/jmeter-service/pull/1)

**Comment by oleg-nenashev** [comment]
Needs @christian-kreuzberger-dtx to create repositories

**Comment by christian-kreuzberger-dtx** [comment]
Repos are already there, we're working on the migration as we speak:
* https://github.com/keptn-contrib/helm-service/
* https://github.com/keptn-contrib/jmeter-service/
