### ISSUE TITLE
Bug: Link to Keptn Installation link is wrong in CLI error message.

### ISSUE THREAD

**Issue by shardulsrivastava** [keptn/keptn#8521]
**Environment**

* Client OS (e.g., Linux, macOS, Windows): `macOS`
* Keptn Version (`keptn version`): `0.17.0`
* Kubernetes Cloud Provider (e.g., GKE, AKS): N/A 
* Kubernetes version (`kubectl version`): N/A

**Affected Component**

* [ ] Approval
* [ ] Bridge
* [x] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**

Hello Team,

I would like to report a bug in `Keptn CLI` error message, where when you run `keptn install`, it gives the following message : 

```
Command "install" is deprecated, please, use the Helm CLI instead. For further information, refer to the documentation https://keptn.sh/docs/0.17.0/operate/install/#install-keptn
Error: this command is deprecated
```

Here the link to `installation` docs is wrong and doesn't exist. It seems like as part of this [PR],(https://github.com/keptn/keptn.github.io/pull/1279) `installation, uninstallation and upgrade` section was moved to it's own directory [here](https://github.com/keptn/keptn.github.io/tree/master/content/docs/install).

**To Reproduce**

1. Install `keptn` latest version using the command ```curl -sL https://get.keptn.sh | bash```
2. Once `keptn` is installed, run `keptn version`
3. See error message with the link.
4. Click on the link - https://keptn.sh/docs/0.17.0/operate/install/#install-keptn

**Expected behavior**
Error message should give this link for `installation` -> https://keptn.sh/docs/install/

**Current behavior**

Currently error message shows this link -> https://keptn.sh/docs/0.17.0/operate/install/#install-keptn that results into `404`.
**Screenshots**

<img width="1412" alt="image" src="https://user-images.githubusercontent.com/9951135/181137197-456b0009-92ca-4020-a2af-49b0e855b353.png">

**Additional context**

**Comment by shardulsrivastava** [comment]
/assign
I would like to take this up.

**Comment by shardulsrivastava** [comment]
I would like to take this up.

**Comment by agardnerIT** [comment]
@shardulsrivastava thank you for a) noticing this, b) taking the time to raise an issue and c) offering to help fix it!

Please:
1) Clone the keptn/keptn repo
2) Create a branch in your fork and make changes on your new branch
3) Create a PR back on keptn/keptn
4) Project maintainers will review and merge

Feel free to ping me on the [Keptn Slack](https://slack.keptn.sh) for any assistance.
