### ISSUE TITLE
The custom header in webhook-service subscription still uses the property "name" in yaml

### ISSUE THREAD

**Issue by DuncanCloud** [keptn/keptn#8540]
**Environment**

* Client OS (e.g., Linux, macOS, Windows): Linux
* Keptn Version (`keptn version`): 0.17.0
* Kubernetes Cloud Provider (e.g., GKE, AKS): N/A
* Kubernetes version (`kubectl version`): 1.20.15

**Affected Component**

* [ ] Approval
* [x] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [x] Webhook

**Describe the bug**
Issue1 : when I click edit this subscription, the added custom header name not shows `Content-Type` , but value shows

**To Reproduce**

1. create webhook subscription and add custom header
2. git upstream repo 's webhook yaml has shows the custom header
3. click edit subscription to check
4. test trigger event to call webhook

**Expected behavior**

![](https://i.imgur.com/dVtmhzx.png)

**Current behavior**

**Screenshots**
![](https://i.imgur.com/mu6ChaG.png)
![](https://i.imgur.com/Hfu8ge0.png)
![](https://i.imgur.com/vJ7L7sS.png)
![](https://i.imgur.com/dStzsI8.png)
**Additional context**

**Comment by agardnerIT** [comment]
Did this make it into 0.18.0 or will it come for 0.18.1. Will it be back ported to 0.17.* ?
