### ISSUE TITLE
Make bridge username configurable on install

### ISSUE THREAD

**Issue by agardnerIT** [keptn/keptn#8541]
The bridge username appears hardcoded to `keptn`. This issue is to make it configurable at install via helm.

I believe the correct place is here: https://github.com/keptn/keptn/blob/55db322e351d0b94ae0e63a767191f83f820736f/installer/manifests/keptn/templates/core.yaml#L55

@StackScribe please tag as a `good first issue`

**Comment by itisaby** [comment]
Hi @agardnerIT, can I work on this issue?

**Comment by atharvkarajgi** [comment]
@agardnerIT Is this issue resolved already?

**Comment by agardnerIT** [comment]
@atharvkarajgi Thanks for joining and helping out the Keptn community!

No this isn't yet completed (as it is still open with no-one assigned and no related PR). But, @itisaby did express interest in completing this so please organise between yourselves who works on this (or both together is cool too). Open a PR when ready and we'll review.

**Comment by itisaby** [comment]
Hi, I can take this issue, but it will also be great if @atharvkarajgi joins. We can work on this together.
