### ISSUE TITLE
Support `user` object in the request body on `webhook-integration svc`

### ISSUE THREAD

**Issue by afzal442** [keptn/keptn#8552]
Currently, there is no support for `user` object in the API call of `webhook-svc`. e.g. in the use case of `jira-svc`, there is need of `user` obj in the request.
```
curl --request GET \
  --url 'https://your-domain.atlassian.net/rest/api/3/issue/{issueIdOrKey}' \
  --user 'email@example.com:<api_token>' \
  --header 'Accept: application/json'
```

**Comment by agardnerIT** [comment]
As a workaround, when you create the webhook like via bridge, it persists to your Git upstream as a curl command.

Just edit the `webhook.conf` file and add whatever you need there

**Comment by afzal442** [comment]
Yes! That's exactly how I thought. Thanks. But seemed to be not working for me. Ended up with some err msg.
```
msg="error during webhook execution" error="could not execute request 'curl --request GET --header 'Accept: application/json' https://keptn-sp.atlassian.net/rest/api/3/events': error during curl request execution: exit status 22.\nResponse: \n{\"message\":\"Client must be authenticated to access this resource.\",\"status-code\":401}"
```

**Comment by agardnerIT** [comment]
`--user` flag is just a helper around the `Authorization` header:

Go to `https://webhook.site` and get a URL
```
curl -X GET https://webhook.site/YOUR-ENDPOINT \
--user foo:bar
```

Is received as

![image](https://user-images.githubusercontent.com/26523841/182492944-4946529f-12a5-4e68-8eb9-374095710161.png)

Notice the `base64` encoded `Authorization` header.

Decode that and you'll see it is `foo:bar`

So....

1. Format your username + password like this: `username:password`
2. base64 encode it
3. Add a Header key called `Authorization`
4. Add a value as `Basic <Your-Encoded-Value-Here>`

**Comment by afzal442** [comment]
hi Adam, I really appreciate your help. That formula worked for me. BTW that was a bit tedious job to do. I would like to create a PR for this to support `user` tag outside of `header`. 😉
