### ISSUE TITLE
Create Helm charts registry

### ISSUE THREAD

**Issue by Moon1706** [keptn/keptn#8556]
**Is your feature request related to a problem? Please describe.**
Hi, folks! Recently I've started closely work with [Pulumi tool](https://www.pulumi.com/). In particular, this utility allows to install Helm charts from registry, but doesn't support usual URL with tar gz. For example, if you append in [repo field](https://www.pulumi.com/registry/packages/kubernetes/api-docs/helm/v3/chart/#repo_nodejs) full path to the archive you'll get error. But I really wanna use your charts like [job-executor-service](https://github.com/keptn-contrib/job-executor-service) etc. Could you create the Helm chart registry, please? 

**Describe the solution you'd like**
You can utilize GitHub Page technology for this aim. I've already [realized this approach](https://github.com/Moon1706/keptn-helm-charts/blob/gh-pages/index.yaml), but maybe you wanna make this official...

**Describe alternatives you've considered**
Yeah, I can download tar gz, untar it, and setup with Pulumi local path, but I'm not sure that it's a modern approach)

**Additional context**
[Example](https://github.com/Moon1706/keptn-helm-charts/blob/gh-pages/index.yaml).

**Comment by agardnerIT** [comment]
Does `https://charts.keptn.sh` work for you?
