### ISSUE TITLE
Helm chart to support tolerations and affinity

### ISSUE THREAD

**Issue by jaimesantosferreira** [keptn/keptn#8568]
**Is your feature request related to a problem? Please describe.**
While deploying Keptn using Helm, I do not have a way for it to avoid using the default nodepool of my Kubernetes cluster.

**Describe the solution you'd like**
It would be great if the Helm chart would allow for tolerations and affinity.

## Acceptance Criteria

- [x] Node/Pod/Anti-Affinity should be supported
- [x] Provide two level of customizations: global- and service-level (take inspiration from `nodeSelector`)
- [x] Service level conf wins over global conf
- [x] Defaults: empty
- [x] Helm doc should be added for the value and the table [regenerated](https://github.com/keptn/keptn/blob/master/gh-actions-scripts/generate-helm-docs.sh) 

## DoD 

- [x] Affinity and Tolerations can be configured via Helm value
- [ ] Integration/ZD pipeline are green

## Resources

Take inspiration from the Bitnami charts

**Comment by jaimesantosferreira** [comment]
Could you guys provide me a timeline for this? Thank you very much!

**Comment by thisthat** [comment]
Hey @jaimesantosferreira, this ticket will most likely be part of Keptn 0.19 that will be available around the end of September :)

**Comment by jaimesantosferreira** [comment]
Thank you very much. :-)
