### ISSUE TITLE
CLI keptn configure monitoring example text outdated

### ISSUE THREAD

**Issue by agardnerIT** [keptn/keptn#8595]
**Environment**

* Client OS (e.g., Linux, macOS, Windows):
* Keptn Version (`keptn version`):  0.18.1
* Kubernetes Cloud Provider (e.g., GKE, AKS):
* Kubernetes version (`kubectl version`):

**Affected Component**

* [ ] Approval
* [ ] Bridge
* [x] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**
`keptn configure monitoring --help` shows some examples which include one:

```
Examples:
keptn configure monitoring dynatrace --project=PROJECTNAME
```

This is invalid as the command requires a service.

**To fix**
Remove this example line from the CLI examples command. The examples **with** a `--service` flag should remain as they are still valid.

**Comment by lunarwhite** [comment]
/assign

Hi, I'll try to fix it.
