### ISSUE TITLE
Bridge :: Improve visualization of failed SLO

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#8602]
## Technical Details

Currently, if an evaluation fails, Bridge will show only the overall score in red to notify about the failing evaluation.
The different SLOs that contribute to the score are not shown or not colored correctly. For example, in this picture, the evaluation is composed of 3 SLOs. Two SLOs cannot be computed due to failing to retrieve the data for the respective SLIs. The last SLO was successfully computed and the result of the SLO evaluation was `pass`. However, the UI does not provide information about the fact that the evaluation was made by 3 SLOs. Instead, only the successful one is shown but without the correct color code. 

![image (18)](https://user-images.githubusercontent.com/992621/183377860-59fda09f-45ac-4e91-aaaf-98601a42070c.png)
![image (19)](https://user-images.githubusercontent.com/992621/183377862-58c8c29a-db2d-44ca-b6ee-85a409278585.png)

## Acceptance Criteria

- [ ] When an evaluation finishes, all SLOs are visualized in the graphs
- [ ] When the evaluation fails, if an SLO is passing, it should be reported in green color
- [ ] When the evaluation fails, if an SLO has the value `null` then it is reported in white color
- [ ] When the evaluation fails, if an SLO has the value `success` equal to `false`, then it is reported in red color

## DoD

- [ ] UI Tests
- [ ] All SLO are visualized in the evaluation graphs

**Comment by Kirdock** [comment]
> When the evaluation fails, if an SLO has the value null then it is reported in white color

Can this even be the case? As far as I can see the value is always set, it can't be `null`

Currently, the info status is set if the indicatorResult has `success: false`

**Comment by thisthat** [comment]
When the SLI provider returns a result fail, the `lighthouse-service` has a circuit breaker that immediately returns an evaluation failed event without any SLO evaluation. This is expected since the SLI provider didn't correctly collected all metrics

https://github.com/keptn/keptn/blob/master/lighthouse-service/event_handler/evaluate_sli_handler.go#L129-L133
