### ISSUE TITLE
Bridge: Navigation to current running stage when polling is triggered

### ISSUE THREAD

**Issue by TannerGilbert** [keptn/keptn#8614]
**Environment**

* Client OS (e.g., Linux, macOS, Windows): Linux
* Keptn Version (`keptn version`): 0.18.1-dev

**Affected Component**

* [ ] Approval
* [x] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**
When watching a running sequence and navigating to an already finished stage, the UI will automatically load the current running stage when polling is executed. 

**To Reproduce**

1. Go to the sequences page
2. Open a running sequence
3. Navigate to a finished stage
4. Wait for polling to kick in 

**Expected behavior**
UI stays on the selected stage when polling happens.

**Current behavior**
UI moves to current running stage when polling happens.

**Screenshots**

https://user-images.githubusercontent.com/36239763/183863542-69ff8eab-047e-4937-9d6d-8f61937fa64a.mp4

**Comment by TannerGilbert** [comment]
This seems to be a problem with the `setTraces` and `SelectSequence` methods inside the `ktb-sequence-view.component.ts`. I'll wait for #8567 before working on this.

**Comment by agardnerIT** [comment]
This also happens for "finished" sequences #8648

**Comment by TannerGilbert** [comment]
Thanks, @agardnerIT. I just tested it, and it seems it's also happening for "finished" sequences as you described.

https://user-images.githubusercontent.com/36239763/184833434-7aef213e-b3d0-4b83-837d-92efe8483b11.mp4
