### ISSUE TITLE
Sequence with missing tasks (invalid Shipyard) causes 500 and breaks bridge create subscription screen

### ISSUE THREAD

**Issue by agardnerIT** [keptn/keptn#8647]
**Environment**

* Client OS (e.g., Linux, macOS, Windows):
* Keptn Version (`keptn version`): `0.18.1`
* Kubernetes Cloud Provider (e.g., GKE, AKS):
* Kubernetes version (`kubectl version`):

**Affected Component**

* [ ] Approval
* [x] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [x] Webhook
* [x] Resource service

**Describe the bug**
An invalid shipyard.yaml causes a blank "create subscription" page
**To Reproduce**

1. Set up a project with a valid shipyard file (all OK)
2. Remove the `tasks` from the sequence so you're left with an invalid shipyard (shown below) 

```
  stages:
    - name: "dev-precheck"
      sequences:
        - name: "validate"
          tasks:
```

**Bridge Logs**
```
GET /api/secrets/scope/keptn-webhook-service 304 51.941 ms - -
[Keptn] 2022-08-13T02:26:30.029Z info    [API] get http://api-gateway-nginx/api/resource-service/v1/project/infracost/resource/shipyard.yaml 200
[Keptn] 2022-08-13T02:26:30.033Z error   [API] Error: Could not parse shipyard.yaml
[Keptn] 2022-08-13T02:26:30.033Z info    [App] Response status: undefined
GET /api/project/infracost/tasks 500 983.493 ms - 29
[Keptn] 2022-08-13T02:26:31.849Z info    [API] get http://api-gateway-nginx/api/resource-service/v1/project/infracost/resource/shipyard.yaml 200
[Keptn] 2022-08-13T02:26:31.852Z error   [API] Error: Could not parse shipyard.yaml
[Keptn] 2022-08-13T02:26:31.852Z info    [App] Response status: undefined
GET /api/project/infracost/tasks 500 813.643 ms - 29
[Keptn] 2022-08-13T02:26:34.492Z info    [API] get http://api-gateway-nginx/api/resource-service/v1/project/infracost/resource/shipyard.yaml 200
[Keptn] 2022-08-13T02:26:34.498Z error   [API] Error: Could not parse shipyard.yaml
[Keptn] 2022-08-13T02:26:34.499Z info    [App] Response status: undefined
GET /api/project/infracost/tasks 500 622.984 ms - 29
```
 

**Expected behavior**
Perhaps print a user friendly error to the bridge that something went wrong parsing the shipyard file and the user should perhaps check to ensure it is valid.

**Comment by TannerGilbert** [comment]
I discussed this with @agardnerIT. The problem only occurs with Keptn v0.16 and is already fixed inside master (currently 0.18).
