### ISSUE TITLE
Explain webhook started / finished as async or sync

### ISSUE THREAD

**Issue by agardnerIT** [keptn/keptn#8652]
Improve / add to the wording of the webhok service screen so tell users that the model is sync or async.

**Describe the solution you'd like**
Adjust the wording on the webhook bridge screen to explain started and finished events more clearly to the user.

Sending started and finished from webhook service is an "async" model. The Keptn task immediately returns. In contrast, delegating the finished event to the receiving service will wait until the receiver is done. Thus it is a synchronous model and will "block.

Async is easier at first to implement as it needs no changes to the receiving side, but the task timing does not include the processing time of the receiving system. Sync allows users to send data from the system back to Keptn and gives accurate timings, but requires modifications.

Users usually start with the async model as it is easiest to implement.

![image](https://user-images.githubusercontent.com/26523841/184588213-5c28523c-4793-48d6-8166-749e9c702222.png)

**Comment by h20220025** [comment]
Hello there! Can I work for this one? Need to know bit more about this stuff.

**Comment by thisthat** [comment]
Sure @h20220025! I'll assign it to you :)

**Comment by h20220025** [comment]
Thank You @thisthat

**Comment by h20220025** [comment]
hi @thisthat I still am working on this issue and I hope to finish it soon.

**Comment by thisthat** [comment]
@h20220025 thank you :D

**Comment by h20220025** [comment]
@thisthat , I am trying to build environment, there is a problem with docker file in webhook service folder. Could please check it.

**Comment by h20220025** [comment]
![8](https://user-images.githubusercontent.com/112873674/198852249-bb930052-5fe4-4519-a501-1979778f9179.jpg)
I am getting errors while I am running the webhook service docker file.

**Comment by h20220025** [comment]
![Screenshot (4)](https://user-images.githubusercontent.com/112873674/200584249-f63fcc51-d33a-4c38-a785-c45aedd65a4b.png)
I'm getting errors like this please help me out.
Errors:
- Unable to start container process.
- Could not create Kubernetes client, unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined.

**Comment by agardnerIT** [comment]
Hi @h20220025 , these do not appear to be Keptn errors but rather errors pulling the k3d cluster image. Also, @afzal442 has opened this PR which suggests that the PR would close this issue. https://github.com/keptn/keptn/pull/9013

I suggest syncing with Afzal before continuing to decide if / what extra needs to be done here.

**Comment by meenaljain0303** [comment]
If this issue is still open, I would like to do it. Kindly assign it to me.

**Comment by thisthat** [comment]
Hi @meenaljain0303, thank you for stepping up to take this issue :) 
I have assigned to you!

**Comment by meenaljain0303** [comment]
will raise PR in the next few days!
