### ISSUE TITLE
Introduce caching for yarn/go installation

### ISSUE THREAD

**Issue by philipp-hinteregger** [keptn/keptn#8657]
In the PR #8634 some performance optimizations were already introduced for the pipeline.
In order to further improve the performance of the CI pipeline, a caching action might be useful to cache all the node modules and go modules from the different installation steps.

**Comment by mowies** [comment]
this could be interesting: https://github.com/actions/setup-node#caching-global-packages-data

**Comment by RealAnna** [comment]
https://yonatankra.com/7-github-actions-tricks-i-wish-i-knew-before-i-started/

has examples of how to do a caching action for yarn maybe it is worth having a look
