### ISSUE TITLE
fetching a service/stage resource fails with keptn 0.18.1-dev (2022-Aug-16)

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#8664]
**Disclaimer**: This is with the latest dev build from this morning (0.18.1-dev, 2022-Aug-16, `0.18.1-dev.202208160810`).

When I fetch a file using go-utils (which connects to localhost:8081/configuration-service, so basically the proxy via keptn/distributor:0.17.0), it fails. However, testing the same code against Keptn 0.18.1 release it works.

Code:
```golang
import (
	"fmt"
	"github.com/keptn/go-utils/pkg/api/models"
	api "github.com/keptn/go-utils/pkg/api/utils"
	"github.com/keptn/go-utils/pkg/lib/keptn"
	"net/url"
)

...

// buildResourceHandlerV1Options builds the URIOption list such that it contains a well formatted gitCommitID
func buildResourceHandlerV1Options(gitCommitID string) api.URIOption {
	var queryParam api.URIOption
	if gitCommitID != "" {
		queryParam = api.AppendQuery(url.Values{
			"gitCommitID": []string{gitCommitID},
		})
	} else {
		queryParam = api.AppendQuery(url.Values{})
	}

	return queryParam
}

func (r V1ResourceHandler) GetServiceResource(resource string, gitCommitID string) ([]byte, error) {
	scope := api.NewResourceScope()
	scope.Service(r.Event.Service)
	scope.Project(r.Event.Project)
	scope.Stage(r.Event.Stage)
	scope.Resource(resource)

	resourceContent, err := r.ResourceHandler.GetResource(*scope, buildResourceHandlerV1Options(gitCommitID))
	if err != nil {
		return nil, fmt.Errorf("unable to get resouce from keptn: %w", err)
	}
        ...
}
```
whereas `ResourceHandler.GetResource` is from go-utils v0.17.0 as well as v0.18.0 (pkg/api/utils/resourceUtils.go).

The same code works against Keptn 0.18.1.

## Logs resource-service

Resource Service spits out this error message on 0.18.1-dev:
```
time="2022-08-16T12:07:08Z" level=info msg="Could not complete request GET /v1/project/simple-jes-project/stage/dev/service/super-service/resource/job%25252Fconfig.yaml?gitCommitID=dd0d8c7a687775a3cebbfe97b88d4d9ebe2a5436: could not retrieve revision in  git repo for project simple-jes-project: resource not found"
```

**Comment by bacherfl** [comment]
@christian-kreuzberger-dtx Is the service running in the same cluster or via the remote execution plane?

**Comment by bacherfl** [comment]
Also, can you please set the LOG_LEVEL env var of the distributor to "debug" and post the relevant logs of the distributor here? Should be something like:

```
Incoming request: host=..., path=..., URL=...
Forwarding request to host=..., path=..., URL=...
```

**Comment by christian-kreuzberger-dtx** [comment]
After further investigation, we figured out that the log of resource-service was misleading.

The root-cause is that by using `keptn/distributor:0.17.0` we set
```
          - name: CONFIGURATION_SERVICE
            value: "http://localhost:8081/configuration-service"
```
which forwards to http://api-gateway-nginx/configuration-service, which is no longer existing with 0.18.1-dev (0.19.0):
```
10.42.0.243 - - [17/Aug/2022:10:47:35 +0000] "GET /api/configuration-service/v1/project/simple-jes-project/stage/dev/service/super-service/resource/job%252Fconfig.yaml?gitCommitID=24ab86be7fa8586f9401d528408aea5852ac5256 HTTP/1.1" 404 157 "-" "Go-http-client/1.1"
10.42.0.243 - - [17/Aug/2022:10:47:35 +0000] "GET /api/configuration-service/v1/project/simple-jes-project/stage/dev/resource/job%252Fconfig.yaml?gitCommitID=24ab86be7fa8586f9401d528408aea5852ac5256 HTTP/1.1" 404 135 "-" "Go-http-client/1.1"
10.42.0.243 - - [17/Aug/2022:10:47:35 +0000] "GET /api/configuration-service/v1/project/simple-jes-project/resource/job%252Fconfig.yaml HTTP/1.1" 404 125 "-" "Go-http-client/1.1"
```

Updating it with
```
          - name: CONFIGURATION_SERVICE
            value: "http://localhost:8081/resource-service"
```
resolved the issue.

Thanks @bacherfl for the troubleshooting.

FYI @thisthat @oleg-nenashev this will impact many Keptn integrations. We are or have already updated argo-service, unleash-service, prometheus-service and job-executor-service.

**Comment by thisthat** [comment]
Thank you @bacherfl and @christian-kreuzberger-dtx for the research!
The Distributor 0.18.x works fine with Keptn 0.18.x and plus, hence we can close the ticket.
