### ISSUE TITLE
keptn configure monitoring sends inconsistent Cloud Event types, leading to problems with go-sdk

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#8718]
We (@TannerGabriel and myself) are currently trying to change [prometheus-service](https://github.com/keptn-contrib/prometheus-service) to use the go-sdk.

prometheus-service has two use-cases that requires communication with Cloud Events:

* Configure Monitoring (triggered by using the CLI `keptn configure monitoring prometheus`),
* Quality Gate (triggered via `get-sli.triggered` Cloud Event)

This would be the usage with the SDK:
```go
const serviceName = "prometheus-service"
const envVarLogLevel = "LOG_LEVEL"
const monitoringTriggeredEvent = "sh.keptn.event.configure-monitoring.triggered" // "sh.keptn.event.monitoring.configure"
const getSliTriggeredEvent = "sh.keptn.event.get-sli.triggered"

...

	log.Fatal(sdk.NewKeptn(
		serviceName,
		sdk.WithTaskHandler(
			monitoringTriggeredEvent,
			eventhandling.NewConfigureMonitoringEventHandler(),
			prometheusTypeFilter),
		sdk.WithTaskHandler(
			getSliTriggeredEvent,
			eventhandling.NewGetSliEventHandler(*kubeClient),
			prometheusSLIProviderFilter),
		sdk.WithLogger(logrus.New()),
	).Start())
```

Unfortunately, we identified a huge problem with configure monitoring.

**keptn configure monitoring prometheus**  will send the following CloudEvent:
https://github.com/keptn/keptn/blob/3253bf522644f19ed44bbfdec53ab678f4dc86ce/cli/cmd/configure_monitoring.go#L80-L87

Whereas `keptn.ConfigureMonitoringEventType` is set to `sh.keptn.event.monitoring.configure` (see https://github.com/keptn/go-utils/blob/764b633614cb1cdc672d525d1dd3f9fab2514640/pkg/lib/events.go#L11-L12 for reference).

**However, the CLI then waits for a `sh.keptn.event.configure-monitoring.finished` Cloud Event**:
https://github.com/keptn/keptn/blob/3253bf522644f19ed44bbfdec53ab678f4dc86ce/cli/cmd/configure_monitoring.go#L117-L121

First of all, this Cloud Event Type is not specified in [keptn/spec](https://github.com/keptn/spec/blob/master/cloudevents.md).
Second, this is heavily inconsistent (CLI sends `sh.keptn.event.monitoring.configure` but expects `sh.keptn.event.configure-monitoring.finished`).
Third, and that's the biggest problem: While we could use [`WithAutomaticResponse(false)`](https://github.com/keptn/go-utils/blob/5ff2d4010e671b0e3fc14e55dd8214bd5643bede/pkg/sdk/keptn.go#L113-L119) from the SDK, this would disable the automatically generated response also for the `get-sli.triggered` handler, and therefore create a huge mess in our implementation.

# Affected Components / Services

* SLI providers (prometheus-service, dynatrace-service, datadog-service, sumologic-service)
* lighthouse service?
* CLI
* spec
* docs?

# Proposed Solutions

Either one of those could probably solve the problem.

- [ ] Rework the CLI to send a Cloud Event of type `configure-monitoring.triggered`, and wait for a `configure-monitoring.finished` (already there)
- [ ] Rework the CLI, keep sending a `monitoring.configure`, but wait for a `monitoring.configure.finished` Cloud Event
- [ ] Support both Cloud Event types for sending (waiting is still on `configure-monitoring.finished`) / adapt the SDK to handle this corner case properly
- [ ] Adapt the SDK to include a way to disable automatic response within a single task handler (not the whole `newKeptn`)

## Decision 

- Adapt the go SDK to provide a `WithAutomaticResponse(false)` per task handler and not globally 

## DoD

- [ ] Doc is updated
- [ ] Go SDK is adapted
- [ ] Unit tests

**Comment by christian-kreuzberger-dtx** [comment]
We just saw that there might be somethign in go-utils that helps us:
https://github.com/keptn/go-utils/blob/master/pkg/sdk/keptn.go#L239-L240
```
				// only respond with .started event if the incoming event is a task.triggered event
				if keptnv2.IsTaskEventType(*event.Type) && keptnv2.IsTriggeredEventType(*event.Type) && k.automaticEventResponse {
					startedEvent, err := createStartedEvent(k.source, event)
```

@TannerGabriel will investigate

**Comment by TannerGabriel** [comment]
Since the `sh.keptn.event.monitoring.configure` cloud event is not of type `TriggeredEvent` the `go-sdk` does not seem to automatically send a `.started` and `.finished`  event (see [here](https://github.com/keptn/keptn/issues/8718#issuecomment-1223943901)) and the `WithAutomaticResponse(false)` flag therefore does not need to be enabled.

This opens a workaround where you can send the correct `sh.keptn.event.configure-monitoring.started` and `sh.keptn.event.configure-monitoring.finished` event manually (example from [Prometheus-service](https://github.com/keptn-contrib/prometheus-service/blob/master/eventhandling/configure_event_handler.go#L84)).

This is a relatively easy workaround for implementing the `configuration-monitoring` event with the `go-sdk`, but the general event mismatch remains an issue.
