### ISSUE TITLE
Need proxy support for keptn-mongodb communications

### ISSUE THREAD

**Issue by eostermueller** [keptn/keptn#8748]
**Is your feature request related to a problem? Please describe.**
Need proxy for support for keptn-mongodb communications.  We need our on-prem keptn deployment to point to a MongoDB server in the cloud, and we want our internal internet proxy to handle the connectivity.

**Describe the solution you'd like**
We like to be able to configure our proxy hostname and tcp port in helm configuration.  We'd like the mongodb-service to use that proxy for internet access to connect to mongodb.

**Describe alternatives you've considered**
We use keptn in dev environments, but also in pre-prod environments that are hosted 'near' actual production environments.
Because of network security concerns, there is no connectivity between dev and these pre-prod environments and they can't both point to the same on-prem mongo db server.  However, both of these network can access mongodb on the internet via a proxy.

**Additional context**

**Comment by oleg-nenashev** [comment]
Hello. thanks for the feature request. For the database proxy, what are the authentication requirements on your side? I doubt just host/port are enough. Would you expect user/password authentication or any other kind of authentication and server validation?

**Comment by eostermueller** [comment]
For our immediate need, no authentication is required, but many of our environments require use/password authentication for proxy access.
