### ISSUE TITLE
Cannot add Image metadata (or other data) via Bridge

### ISSUE THREAD

**Issue by agardnerIT** [keptn/keptn#8802]
**Environment**

* Client OS (e.g., Linux, macOS, Windows):
* Keptn Version (`keptn version`): `0.17.1` and higher
* Kubernetes Cloud Provider (e.g., GKE, AKS):
* Kubernetes version (`kubectl version`):

**Affected Component**

* [x] Bridge

**Describe the bug**

**To Reproduce**
```
keptn trigger delivery \
--project=fulltour \
--service=helloservice \
--image="ghcr.io/podtato-head/podtatoserver:v0.1.1" \
--labels=image="ghcr.io/podtato-head/podtatoserver",version="v0.1.1"
```

This command cannot be replicated via the bridge as there is no way to add `--image` via the bridge.

**Expected behavior**
I can trigger sequences equally from API, bridge and CLI. They should be equivalent.

**Comment by thisthat** [comment]
Hey @agardnerIT, I am using Keptn 0.18.1 and the `--image` parameter can be specified in the first input field. Labels are passed in the second input field instead.
![image](https://user-images.githubusercontent.com/992621/188465282-f2a92ad1-7559-49d5-bbf7-c92c747c3bc2.png)
