### ISSUE TITLE
keptn trigger sequence does not accept metadata

### ISSUE THREAD

**Issue by agardnerIT** [keptn/keptn#8803]
Your issue may already be reported! Please search on the [issue tracker](https://github.com/keptn/keptn/issues) before creating a new one.

**Environment**

* Keptn Version (`keptn version`): `all`

**Affected Component**

* [ ] Approval
* [ ] Bridge
* [x] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**
The `keptn trigger sequence` command does not accept metadata so image, version or any custom metadata cannot be added.

**Comment by agardnerIT** [comment]
The initial issue was raised more around metadata like adding items into the data block for any sequence (not only `evaluation` and `delivery` and not solely labels).

As a concrete example, imagine I have a sequence called `doRelease` with two tasks: `test` and `evaluation`. Now I need to craft and send `data.test.strategy == "direct"` and `data.evaluation.timeframe=5m`. I now cannot use the CLI.

**Comment by thisthat** [comment]
This is morphing into a feature request @agardnerIT :) 
I will change the labels of the issue to reflect it

**Comment by agardnerIT** [comment]
I can’t see any drawback with @warber’s approach. In fact it’s an enhancement on my thought which was just the first option :)
