### ISSUE TITLE
During 0.18.x upgrade all pods fail with "ImagePullBackOff"

### ISSUE THREAD

**Issue by melcsanad** [keptn/keptn#8810]
**Environment**

* Client OS : Red Hat Enterprise Linux release 8.6 (Ootpa)
* Keptn Version (`keptn version`): 0.17.0
* Kubernetes Cloud Provider : local
* Kubernetes version (`kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15", GitCommit:"73dd5c840662bb066a146d0871216333181f4b64", GitTreeState:"clean", BuildDate:"2021-01-13T13:22:41Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15", GitCommit:"73dd5c840662bb066a146d0871216333181f4b64", GitTreeState:"clean", BuildDate:"2021-01-13T13:14:05Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"

**Affected Component**

* [ ] Approval
* [ ] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [x] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**

After start helm upgrade (helm upgrade keptn keptn/keptn -n keptn --version 0.18.2) all pods stuck in ""ImagePullBackOff" status:
Log:
Pulling image docker.io/nginxinc/docker.io/nginxinc/nginx-unprivileged:1.22.0-alpine
Failed to pull image docker.io/nginxinc/docker.io/nginxinc/nginx-unprivileged:1.22.0-alpine

The image regisrty is dulicated in image: "docker.io/nginxinc/docker.io/nginxinc/..."
also for /dokcer.io/keptn...

My assumption: 
By followed the 0.16.0->0.17.0 upgrade procedure, (https://keptn.sh/docs/install/upgrade/) the "current keptn values" export cointained these image references for all pods:

`apiGatewayNginx:`
`.`
`   image:`
`    repository: docker.io/nginxinc/nginx-unprivileged`
`    tag: 1.22.0-alpine`

During the suggested upgrade command (after value merge):  
`helm upgrade keptn keptn/keptn -n keptn-test --version 0.17.0 --values <your-adjusted-values-file>`
these values were imported as USER-SUPPLIED VALUES.

These USER-SUPPLIED VALUES override the 0.18.2 helm chart values and generate wrong image references by [_images.tpl](https://github.com/keptn/keptn/blob/master/installer/manifests/common/templates/_images.tpl) because the repository already contain the registry.

**To Reproduce**

Start the upgrade with USER-SUPPLIED VALUES (--values: cust_values.yaml):
apiGatewayNginx:
  image:
    repository: docker.io/nginxinc/nginx-unprivileged
    tag: 1.22.0-alpine

**Expected behavior**

Upgraded pod start without error!
**Current behavior**

Upgraded pods are failed with Image pull error!
**Screenshots**

**Additional context**

**Comment by melcsanad** [comment]
Have 2 idea but need you aprove/support:
- helm upgrade --reset-values  (I don't know what else could I loose from USER-SUPPLIED values what requires)
- remove image entries from USER-SUPPLIED values! I haven't found helm solution to remove and keep the others.

**Comment by RealAnna** [comment]
Hi @melcsanad I did try to go from 0.16.0 to 0.17.0 and then 0.18.2 following your instructions, but everything worked fine for me...  
However, the USER-SUPPLIED values did not contain any reference to image or repository in my case. Can you share what command you originally used to install 0.16.0 or what is your USER-SUPPLIED file?

**Comment by melcsanad** [comment]
Hello @RealAnna ,

Upgrade to 0.16.0 I used this command (as was described in upgrade doc point 5.): https://keptn.sh/docs/0.16.x/operate/upgrade/)
`helm upgrade keptn keptn/keptn -n keptn --version 0.16.0 --reuse-values`

The command result of `helm get values -n keptn keptn > keptn-values.yaml` and AFTER merge:
[keptn-values.yaml.txt](https://github.com/keptn/keptn/files/9505227/keptn-values.yaml.txt)
As you can see the service image descirptions are exists in this output file.

Than I made the upgrade used these values:
`helm upgrade keptn keptn/keptn -n keptn --version 0.17.0 --values ./keptn-values.yaml`

Now, If I start an `helm upgrade ---dryrun --debug 0.18.2` . I get this result:
[dryrun-debug.log.txt](https://github.com/keptn/keptn/files/9505246/dryrun-debug.log.txt)
`USER-SUPPLIED VALUES` are contains and generated image references are wrong:
      containers:
        - name: api-service
          image: "docker.io/keptn/docker.io/keptn/api:0.18.2"

If I understand your suggestion correctly, than the --set command eleminate the helm chart values during the upgrade and uses the USER-SUPPLIED VALUES. Long them this keep my values and ignore any change what may come with new releases.
Do you have a solution to eleminate my 'image:' USER-SUPPLIED-VALUES to keep the compatible with the upcoming releases?

**Comment by RealAnna** [comment]
@melcsanad 
Yes since you do not specify any set the reuse value is taken by default and you see this problem, indeed the --set would not solve long therm.

However I run a diff among the 0.18.2 values file and yours, I see you have very little changes (smaller jetstream memory allocation, d3 heatmap in bridge disabled ) in configurations compared to the keptn default.  You can doublecheck that and, if so, it makes sense as you suggest to use  --reset-values  or simply to have a custom value.yaml with only those changes and pass it to the upgrade command (anyway  setting a value implicitly calls --reset-values so the result should be the same)

**Comment by melcsanad** [comment]
@RealAnna 
OK, I try the upgrade according the following plan: 
- I will use --reset-values 
- I'll use a value.yaml supply file which contain only those values what are not present in helm chart 0.18.x
- run helm upgrade

I'll inform you about the result.

**Comment by melcsanad** [comment]
@RealAnna 
It seems finally worked. I lost somehow the write access to PV of keptn-nat-0 pod, but that was managable.
Thanks
