### ISSUE TITLE
Upstream git repository is initialized with branch master instead of main

### ISSUE THREAD

**Issue by AndreaTosti** [keptn/keptn#8816]
**Environment**

* Client OS (e.g., Linux, macOS, Windows): `macOS`
* Keptn Version (`keptn version`): `0.18.2`
* Kubernetes Cloud Provider (e.g., GKE, AKS): OpenShift On-Premise
* Kubernetes version (`kubectl version`): `v1.23.5`
* Upstream git repository: self-hosted GitHub Enterprise v3.4.0

**Affected Component**

* [ ] Approval
* [ ] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**
When a project is created on Keptn, indicating a Git repository that has not been initialized, the resulting Git repository will contain the `master` branch instead of the `main` branch

**To Reproduce**

1. Head to GitHub
2. Create a new repository
3. Choose a repository name
4. Do **not** check the "Initialize this repository with README / .gitignore" options
5. Head to Keptn
6. Create a new project
7. Choose a project name
8. Insert the link of the GitHub repository created in the previous steps
9. Insert Git user and Token
10. Choose a Shipyard file, i used the following: 
```
apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "shipyard"
spec:
  stages:
    - name: "prod"
```
11. Head to the link of the GitHub repository created in the previous steps
12. The `master` appears in the branch list

**Expected behavior**
Once the project is created on Keptn, the upstream Git repository should contain the `main` branch

**Current behavior**
Once the project is created on Keptn, the upstream Git repository contains the `master` branch

**Screenshots**
![](https://i.imgur.com/G3CA6LM.png)

**Additional context**

**Comment by rakshitgondwal** [comment]
Hey, I used to get this issue earlier when I tried to git init into any new folder. Git would automatically set the branch to `master` rather than `main`. I fixed this using `git config --global init.defaultBranch  main`. I wonder if this would be of any help for this issue.
