### ISSUE TITLE
Users can delete a project using the CLI

### ISSUE THREAD

**Issue by dirkwall** [keptn/keptn#887]
Keptn users can delete a project through the CLI via 
`keptn delete project <projectname>`

**Comment by johannes-b** [comment]
- [ ] Implementation
- [ ] Testing
- [ ] Documentation

**Comment by christian-kreuzberger-dtx** [comment]
Documentation still has an error
![Screenshot from 2019-10-10 10-41-51](https://user-images.githubusercontent.com/56065213/66553077-c4995080-eb4a-11e9-912b-1d5371b52e3e.png)
