### ISSUE TITLE
CI: Research Govulncheck

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#8899]
## Goal

This research aims to determine how [govulncheck](https://go.dev/blog/vuln) can be integrated into our pipelines.
The questions to answer are:
- does this replace/complement synk? 
- should we have it as part of every build?
- should we have it scheduled?
- can the result be imported into GitHub security alerts?

## DoD

- [x] Create a follow-up ticket to work on the implementation

**Comment by philipp-hinteregger** [comment]
follow-up ticket: #8937
