### ISSUE TITLE
Add info about auto-signoff in the README

### ISSUE THREAD

**Issue by vadasambar** [keptn/keptn#8914]
## Summary
We have a DCO check which runs on every PR to check if the commit has been signed off. 

Doing
```
git commit --amend --signoff
```
or something like 
```
git rebase HEAD~2 --signoff
```
is inconvenient. Signing off can be automated by adding the following hook in the local `.git` folder:
```bash
#!/bin/sh
#
# An example hook script to prepare the commit log message.
# Called by "git commit" with the name of the file that has the
# commit message, followed by the description of the commit
# message's source.  The hook's purpose is to edit the commit
# message file.  If the hook fails with a non-zero status,
# the commit is aborted.
#
# To enable this hook, rename this file to "prepare-commit-msg".

# This hook includes three examples.  The first comments out the
# "Conflicts:" part of a merge commit.
#
# The second includes the output of "git diff --name-status -r"
# into the message, just before the "git status" output.  It is
# commented because it doesn't cope with --amend or with squashed
# commits.
#
# The third example adds a Signed-off-by line to the message, that can
# still be edited.  This is rarely a good idea.

SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
grep -qs "^$SOB" "$1" || echo "$SOB" >> "$1"
```
This needs be put in the `.git/hooks/prepare-commit-msg` file (you need to create a new file called `prepare-commit-msg`) and give it permission to execute using:
```
chmod +x .git/hooks/prepare-commit-msg
```

## TODO
- [ ] Add info about this in the README after https://github.com/keptn/keptn/blob/master/CONTRIBUTING.md#commit-types-and-scopes (create a heading called `Auto signoff commit messages` and add a line in https://github.com/keptn/keptn/blob/master/CONTRIBUTING.md#make-a-pull-request before `Finally, go to GitHub and create a Pull Request...` like this:
```
Make sure you sign-off your commits. To do this automatically check [this](https://github.com/keptn/keptn/blob/master/CONTRIBUTING.md#auto-signoff-commit-messages). Finally, go to GitHub and create a Pull Request.
```
- [ ] Raise a PR and get it merged

## Notes
- This issue was originally filed in https://github.com/keptn-sandbox/datadog-service/issues/82 but we are moving it here because we think having this in the keptn CONTRIBUTING would be better. 
- PR already raised in datadog-service by @nitinmewar: https://github.com/keptn-sandbox/datadog-service/pull/83/files

**Comment by vadasambar** [comment]
@nitinmewar can you raise a PR here again :pray:

**Comment by rahul3002** [comment]
i would like to work on this issue
