### ISSUE TITLE
Core :: Enhance logs

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#8980]
## Technical Details

When a subscription/integration is deleted via the API, there is no log to record this action. Similarly, when a panic occur Gin will log with "NONE" log level the message making it hard to find in the logs.

## Acceptance Criteria
- [x] The handler that deletes a subscription reports a `WARN` log line the action with info about the subscription being deleted and the following additional info: `event`, `filters`, `integration name, integration id`. 
- [x] The handler that deletes an integration reports with a `WARN` log line the action with info about the integration being deleted and the following additional info:  `name`, `metadata.distributorversion`, `metadata.hostname`, `metadata.integrationversion`, `location`, and list of subscriptions with `event` and `filter`.
- [x] Gin gonic panic recovering are logged with a `ERROR` level. 
- [x] `cp-connector`/`sdk` log lines with `INFO` level as default.

**Comment by j-poecher** [comment]
maybe `cp-connector`/`sdk` levels could also be `debug` for some of the logs, as they are happening quite frequently @thisthat

**Comment by warber** [comment]
@j-poecher @thisthat fyi, logging behavior of `cp-connector/sdk` has been improved recently as part of [this](https://github.com/keptn/go-utils/pull/542) PR.
