### ISSUE TITLE
Filtering in Keptn Dashboard 'Chart'

### ISSUE THREAD

**Issue by eostermueller** [keptn/keptn#9001]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when there are so many metrics on a graph, it's not convenient to: click to disable most of the metrics (perhaps 20 or 40 or more) on a graph in order to see granular details of a few metrics.

**Describe the solution you'd like**
We'd like more features to view subsets of SLIs/metrics.
For example, we'd be much more productive with 
* a filter by metric type.  "Show me all the response time metrics"  "Show me all the CPU metrics" etc....  Other types:  throughput, response time, error %, and there will be others.  
* a filter by wildcard for partial SLI name.  Show me all metrics with "fundsXfer" in the SLI name
* a filter by timeframe.  "Exclude all metrics that are more than 1 year old"  "Only show metrics between June and July of last year"

...and to repeat, when we have 40 or more metrics, it's very inconvenient to de-select 30 of them to view the detail we're after.
We try to include an "metric type" abbreviation in our metrics by convention.  So as a concession, we could use that abbreviation (rpm=requests-per-minute, rt=response time, frp=failure-request-%) for a "partial SLI name" filter, if it's not possible to implement a "metric type" attribute.

Other helpful filters:
* only show metrics that passed.
* When searching for "metric creep", degrading metrics that still haven't surpassed the SLO, it would be helpful to filter/include all relative comparisons.

**Describe alternatives you've considered**
Clicking to disable individual metrics is a little helpful but is bothersome to have to click 30 times to filter out stuff.
We though of building our own dashboard, but like what you have so far.

**Additional context**
![keptn-dash-chart](https://user-images.githubusercontent.com/175773/195364349-50c4ee0a-f116-4207-a666-933d04246e20.png)

**Comment by shubham101991** [comment]
Add on to the Erik's requirement , just a sample filter we are looking for :
[](url)
<img width="450" alt="Filter" src="https://user-images.githubusercontent.com/115647435/195378815-710e4e16-20d9-4650-b403-d546cebb0d70.png">

**Comment by shubham101991** [comment]
@grabnerandi Any comments / update /views on above mentioned requirement ?

**Comment by oleg-nenashev** [comment]
Hello. I will provide feedback on that this week

**Comment by oleg-nenashev** [comment]
Just to set an expectation, I am about starting a conversation in the community about the future of the web interface and the feasibility of expanding it based on the current technology stack.
In the previous conversations in the community, I believe we have a consensus that we would like to move to a headless solution with proper apis and endpoints that would allow connecting an external interface, for example built on the top of grafana or backstage. If we need deeper discussion on this topic before we proceed this way, and every Keptn user is welcome to participate in this discussion.

@eostermueller if you would be interested to discuss your experiences with the Keptn UI in detail, I would be happy to jump on the call.
