### ISSUE TITLE
New usage analytics engine for Keptn

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/keptn#9050]
## Quick summary

* The current analytics engine is not reliable. The lack of a way to uniquely identify the instance ID is the biggest problem. Right now we rely on Cloud Front logs, so we cannot say for sure how many instances are used behind a single network
  - Proposal: Introduce uniqueId as a part of Keptn core. It should be persisted in the database and retained between restarts. The recipient side and processing scripts also need to be reworked to support unique ID, likely through the HTTP URL parameter. Maybe it requires another endpoint, like Bitly Enterprise
* Keptn CLI likely submits the usage analytics by default (opt-out), even for Cloud Automation
* The number of installations is not enough for decision making. We need to collect more data. Actually, the current analytics opt-in permissions in the Web UI allows for more data:
  - List of submitted data: TODO
  - Proposal: Implement the submitted data. It requires a fresh new analytics engine. There are many open source projects like Matomo, but maybe a simple database provider + GrimoireLab are a better solution for flexibility purposes.
  - Note: Oleg is also a big fan of Sentry that could be used as receiber/visualization tool && has open source sponsorship (and now Daniel Khan on the team :slightly_smiling_face: )
- The Linux Foundation has strict usage analytics rules that put many limits on what cannot be submitted. E.g. Usage analytics should be opt-in, and that there should be no personal or company identifyable data in public layouts. Also note all analytics engines should comply with GDPR and the Californian equivalent

## Related problems:

- LF Usage Analytics guidelines: https://www.linuxfoundation.org/legal/telemetry-data-policy

**Comment by oleg-nenashev** [comment]
Partially duplicates https://github.com/keptn/enhancement-proposals/issues/84

**Comment by MdSahil-oss** [comment]
@oleg-nenashev It looks like lots of features are mentioned in this issue, So can you tell me what features have been done and what are yet needed to be done ?

**Comment by agardnerIT** [comment]
I believe this is now solved with 1.0.0 as it uses https://about.scarf.sh/ to track download stats.
