### ISSUE TITLE
Verify/Ensure compatibility of the Prometheus service with Keptn LTS

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/keptn#9076]
We would like to verify the service compatibility with the upcoming LTS release, because we plan to include it into the LTS package. See https://github.com/keptn/enhancement-proposals/pull/86

## Scope

https://github.com/keptn/keptn/issues/9076#tasklist-block-e36a55c5-18c0-4345-b32b-5fe8de417223

**Comment by mowies** [comment]
I checked manually that everything works, and updated the integration tests to test against the latest Keptn version (automatically calculated).
