### ISSUE TITLE
Move community governance documents to keptn/community

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/keptn#9091]
### Discussed in https://github.com/keptn/keptn/discussions/9090

At the moment we have a number of community/membership/governance repositories in https://github.com/keptn/keptn . It was OK for a monorepo project, but gets more and more complicated with more root projects being added (website, integration services, sub-projects like Lifecycle Controller, etc.) 

## Proposal

https://github.com/keptn/keptn/issues/9091#tasklist-block-b9a93342-c315-43e5-8513-4c41b7a6dba3

**Comment by rahul3002** [comment]
i would like to work on this issue

**Comment by meenaljain0303** [comment]
If this issue is still open, I would like to do it . Kindly assign it to me.
