### ISSUE TITLE
Unable to debug logs because of log pollution

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#9096]
The logs of a keptn service contain every 5 seconds the following log lines:
```
2022/10/31 14:11:10.441207 Updating subscriptions                                                                                                          │
2022/10/31 14:11:15.429008 UniformSubscriptionSource: Renewing Integration ID 4b4d28a8f3bf811aa735f9531bae6bebf0df0f78                                     │
2022/10/31 14:11:15.461609 UniformSubscriptionSource: Ping successful, got 1 subscriptions for 4b4d28a8f3bf811aa735f9531bae6bebf0df0f78                    │
2022/10/31 14:11:15.461631 ControlPlane: Got a subscription update with 1 subscriptions
```
This makes debugging a log impossible.

*What?*
Log messages should be printed only if the log level is set to `Debug`.

**Comment by thisthat** [comment]
This is an action item for the `go-sdk`

**Comment by warber** [comment]
These logs are already printed with debug level in `go-sdk`. I think the only thing left to do is to verify that the correct level is passed to the sdk in the respective service(s).

**Comment by bacherfl** [comment]
I just verified that the debug level is passed correctly by setting the `logLevel` property in the helm chart accordingly. By default, this will be set to `info`. Also, I could verify that the logs regarding the periodic subscription updates were not printed anymore if the log level is set to `info`
