### ISSUE TITLE
MongoDB error "could not register integration: failed to connect client to MongoDB: connection() error occurred during connection handshake: auth error: unable to authenticate using mechanism \"SCRAM-SHA-256\": (AuthenticationFailed) Authentication failed."

### ISSUE THREAD

**Issue by darkgordon** [keptn/keptn#9122]
Hello keptn community hope everything is going well

Recently I installed the Keptn Control Plane Chart in my testing cluster, everything was great but after we had a restart of all our pods in our cluster, 

The keptn Services: approval-service, lighthouse-service, remediation-service and webhook-service stary in a crashloopbackoff state and the logs show the following:

`time="2022-11-08T20:39:21Z" level=fatal msg="could not register integration: failed to connect client to MongoDB: connection() error occurred during connection handshake: auth error: unable to authenticate using mechanism \"SCRAM-SHA-256\": (AuthenticationFailed) Authentication failed."`

My  mongodb datastore and the mongo pod are running well 

logs of mongo pod:
`4.8.1"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"5.4.0-1041-aws"},"platform":"Node.js v16.16.0, LE (unified)","version":"4.8.1|1.5.4","application":{"name":"mongosh 1.5.4"}}}}
{"t":{"$date":"2022-11-08T20:50:33.570+00:00"},"s":"I",  "c":"-",        "id":20883,   "ctx":"conn22401","msg":"Interrupted operation as its client disconnected","attr":{"opId":170336}}
{"t":{"$date":"2022-11-08T20:50:33.569+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn22404","msg":"Connection ended","attr":{"remote":"127.0.0.1:35458","uuid":"8c988e62-4781-44e6-94ad-f2fe9a09ddf1","connectionId":22404,"connectionCount":8}}
{"t":{"$date":"2022-11-08T20:50:33.570+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn22401","msg":"Connection ended","attr":{"remote":"127.0.0.1:35452","uuid":"8e9968a4-9996-447e-bc05-6e9730c68773","connectionId":22401,"connectionCount":7}}
{"t":{"$date":"2022-11-08T20:50:33.569+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn22403","msg":"Connection ended","attr":{"remote":"127.0.0.1:35456","uuid":"11ea91d2-fdcf-4beb-a5fc-c9b42e873adf","connectionId":22403,"connectionCount":9}}
{"t":{"$date":"2022-11-08T20:50:33.570+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn22402","msg":"Connection ended","attr":{"remote":"127.0.0.1:35454","uuid":"ab72d7ca-bcfb-4c42-866a-8badf7612315","connectionId":22402,"connectionCount":6}}`

and the mongodb datasource shows the following logs:
`time="2022-11-08T18:12:58Z" level=info msg="Registering control plane"
time="2022-11-08T18:12:58Z" level=info msg="Serving mongodb datastore at http://[::]:8080"`

**Environment**

* Kubernetes Cluster provided by KOPS in aws 
* Kubernetes version 1.24.3
* Keptn Version (`keptn version`):  CLI 0.19.1 and cluster 0.19.0

**To Reproduce**

1. Install a fresh keptn control plane helm chart
2. Restart all pods of the keptn namespace
3. you will see the previously mentioned pods stay in Crash state

**Expected behavior**
to restart all the pods and dont have problems with keptn 
![image](https://user-images.githubusercontent.com/28151796/200673429-9e129ebd-9f84-4b43-8ef9-260375c4da73.png)

Any help is appreciated have a nice day :)

**Comment by RealAnna** [comment]
Hi @darkgordon! I tried to reproduce on a kind cluster and this is what I had after restarting everything at the same time (aka deleted all pods in a namespace)
![image](https://user-images.githubusercontent.com/89971034/200807856-1797af9c-d3f2-4b20-8d9a-1b9c1381baaf.png)
![image](https://user-images.githubusercontent.com/89971034/200807987-3251cb52-a4db-40f3-a5d5-e9d28ee843f2.png)
In my case, the crash loop was there because of the shutdown of the other services, as soon as all of them terminated everything was up and running. 

In your case did the pods come up eventually? What is the cluster status 5min after restart?

**Comment by darkgordon** [comment]
Hello @RealAnna thanks for your reply, 

In my case after some hours , the previously mentioned pods stay in the same CrashLoopBackOff state

<img width="378" alt="image" src="https://user-images.githubusercontent.com/28151796/200853274-58b27187-e9ce-424a-9e4e-785f44183617.png">

I proceed to restart only the crashing pods and give some time (5 minutes aprox)
and the problem stills there :(
<img width="374" alt="image" src="https://user-images.githubusercontent.com/28151796/200854783-0fda653d-aa9b-43b7-bfb4-f8299f190e2d.png">

thank you very much

**Comment by RealAnna** [comment]
Hi @darkgordon, it looks like the integrations fail to register to the uniform. Can it be the mongo-datastore credential got compromised somehow? Can you verify the mongo-datastore pw (MONGODB_PASSWORD env var in the pod) corresponds to the secret (mongodb-credentials -> mongodb-passwords) ?

**Comment by RealAnna** [comment]
Actually @darkgordon I see you set up a custom name for mongodb, by default shipyards try to register integrations using           ```
- name: MONGODB_HOST
  value: 'keptn-mongo:27017'
```
This is taken from the mongodb values   
```
  usernames: []
  passwords: []
  databases: []
```
Have you updated this value in your mongodb helm chart or in your shipyard default yaml?

**Comment by darkgordon** [comment]
Hello @RealAnna  thanks again for the reply, in my case the svc of mongodb host still the same by default uses my custom mongosdb svc

![image](https://user-images.githubusercontent.com/28151796/202203829-9a707915-bdcc-4e96-acfd-01a21b029795.png)

This is inside  the shipyard pod in the Envs value.

What I did to fix my issue was to set in the values.yaml a custom password for the keptn user and the mongodb root user instead of the default mongodb secret provided by the values.yaml

and in some way it works after I restarted all my keptn namespace pods.

I deployed keptn with ArgoCD, and I was thinking if that kind of deployment strategy could affect the keptn deployment ?

**Comment by mizzack** [comment]
This happened to me as well using ArgoCD + the keptn 1.0.0 helm chart. Seems like the credentials in the initial mongodb store get out of sync with what's in the `mongodb-credentials` secret.

Since it was a new install, my solution was to delete the `keptn-mongodb` PVC, sync Argo, and restart the keptn-mongo pod(s). Everything came up right after that.
