### ISSUE TITLE
Replacement of keptn-contrib/keptn-service-template with template in Go and for Keptn >0.5.0

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#913]
The reference repository for building a keptn-service is out-of-date: https://github.com/keptn-contrib/keptn-service-template

This template need to be updated to a service written in Go and with deployment/service manifests that are supported by Keptn >0.5.0. Besides, a guideline for listening to Keptn events, building and deploying a custom service need to be provided in the Readme.md.

Finally, this new template has to be referenced in: https://keptn.sh/docs/0.5.0/reference/custom-service/

**Comment by dirkwall** [comment]
What if we just use one of the existing simpler services as a reference?

**Comment by christian-kreuzberger-dtx** [comment]
When updating the keptn-service-template we should also add the following to the tutorial:

* How to use (read and write) cloud events (eventbroker, distributor, etc...)
* How to make a good git repo for a service (such that a user can contribute it to keptn-contrib)
* Link to example repos (e.g., notification-service, alexa-service)
