### ISSUE TITLE
Lighthouse-service: Evaluation should fail if SLO file cannot be retrieved due to resource-service error

### ISSUE THREAD

**Issue by j-poecher** [keptn/keptn#9146]
**Environment**

* Client OS (e.g., Linux, macOS, Windows): Linux
* Keptn Version (`keptn version`): 0.19.2
* Kubernetes Cloud Provider (e.g., GKE, AKS): EKS
* Kubernetes version (`kubectl version`): n/a

**Affected Component**

* [ ] Lighthouse-service

**Describe the bug**

**To Reproduce**

1. setup a project with a service
2. setup a minimal SLO file - just to make sure that there is one available - you will not need it though.
3. use _dynatrace-service_ in combination with the dashboard integration use case, that will update the SLO file during the evaluation
4.trigger a **5min timeframe** evaluation via Keptn Bridge (with this you can make to sure to have enough time to scale down the _resource-service_, as _dynatrace-service_ will wait at least for 2 minutes before starting to process).
5. wait for _dynatrace-service_ to fail `get-sli`, because it could not upload SLOs via _resource-service_
6. see that _lighthouse-service_ passes the evaluation, because **[...] no SLO file configured for project [...]**

**Expected behavior**
I expect the _lighthouse-serivce_ to fail the *evaluation* sequence, because it cannot access any resource with a scaled down _resource-service_

**Current behavior**

_lighthouse-service_ does not fail, but succeeds as it treats the error as if there would be no SLO file

**Screenshots**

![lighthouse-service-slo-file-bug](https://user-images.githubusercontent.com/27000735/201667860-cb5c38ae-c90b-4792-95a0-a6514048f6ea.png)

**Comment by thisthat** [comment]
Closed with #9153
