### ISSUE TITLE
When creating a new project fails, the project is still created 

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#930]
**Describe the bug**

When creating a project with invalid values the CLI says that it failed, but trying again to create the project results in the error that the project is already existing.

Here are two commands to verify the error:

```
root@# keptn create project sockshop --shipyard=shipyard.yaml --git-user=xxx --git-token=xxx --git-remote-url=https://github.com/xxx/sockshoptest
Starting to create project
Creating project sockshop failed. Could not commit changes.
```

```
root@# keptn create project sockshop --shipyard=shipyard.yaml --git-user=xxx --git-token=xxx --git-remote-url=https://github.com/xxx/sockshoptest
Starting to create project
Creating project sockshop failed. Project already exists.
```

Expected behaviour:
If the creation of the project fails, it should completely fail and not create the project since the state is undefined.

**Comment by christian-kreuzberger-dtx** [comment]
Is `keptn delete project` a workaround for now?

**Comment by robertjahn** [comment]
I had the same issue.  We verified we had a README file when we tried it.  We deleted the project and i was able to create with NO upstream.  We thought it might be related to #929.  Once #929  is ready and does address the problem, I will close this this issue #930

**Comment by jetzlstorfer** [comment]
> Is `keptn delete project` a workaround for now?

It is a workaround, yes. However, the issue should still be adressed in a future release. Even adapting the CLI output to tell the user that the project was actually created would help already.

**Comment by dirkwall** [comment]
@robertjahn #929 has been fixed, so I'll close this issue as well.
