### ISSUE TITLE
After uninstalling keptn and installing it again helm is not working anymore

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#931]
**Describe the bug**

When uninstalling keptn and then installing it again on the same cluster, onboarding of a service fails due to an error in the helm service:

```
root@# keptn onboard service carts --project=sockshop --chart=./carts
Starting to onboard service
Start creating service carts in project sockshop
Create Helm umbrella charts
Error when initalizing and applying umbrella charts for project sockshop: Error when applying umbrella chart in stage dev: Error when upgrading chart sockshop-dev in namespace sockshop-dev: Error executing command helm upgrade --install sockshop-dev /tmp/558912023 --namespace sockshop-dev --reset-values --wait --force: exit status 1
Error: UPGRADE FAILED: Unauthorized
```

**To Reproduce**
1. Install keptn
1. Create project and onboard services
1. Uninstall keptn and delete the helm releases
1. Install keptn again
1. Create a project
1. Try to onboard services

**Expected behavior**
Onboarding of services should work.

**Comment by christian-kreuzberger-dtx** [comment]
Hi @jetzlstorfer 

Which version did you use for testing? I believe that this bug is not happening anymore with keptn 0.5.0.

**Comment by christian-kreuzberger-dtx** [comment]
I just noticed a similar issue with the current development version after uninstalling and re-installing:

```
Starting to onboard service
Create Helm umbrella charts
Error when initalizing and applying umbrella charts for project sockshop: Error when applying umbrella chart in stage dev: Error when upgrading chart sockshop-dev in namespace sockshop-dev: Error executing command helm upgrade --install sockshop-dev /tmp/560192422 --namespace sockshop-dev --reset-values --wait --force: exit status 1
Error: UPGRADE FAILED: failed to create resource: namespaces "sockshop-dev" not found
```

**Comment by christian-kreuzberger-dtx** [comment]
I believe this issue is also related to #1120 - we need to clean up helm/tiller releases.
