### ISSUE TITLE
Keptn installation fails with incorrect error message

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#932]
**Describe the bug**
If the Keptn installation fails the error message is incorrect since it refers the `uninstallKeptn.sh` script which is obsolete.

```
Stopping keptn installation. Already created resources are not deleted; execute the uninstallKeptn.sh script to clean-up. 
```

**Expected behavior**
Adap error message to `keptn uninstall`.

**Comment by christian-kreuzberger-dtx** [comment]
The text needs to be changed three times in [installer/scripts/common/utils.sh](https://github.com/keptn/keptn/blob/master/installer/scripts/common/utils.sh).

I also just saw that the `uninstallKeptn.sh` script is still referenced in 

* travis-scripts/setup_functions.sh
* travis-scripts/cronjob_main.sh
