### ISSUE TITLE
Migrate Killercoda tutorial to official Keptn repos

### ISSUE THREAD

**Issue by agardnerIT** [keptn/keptn#9320]
The Killercoda v1.0.0 tutorial is still hosted on @afzal442's personal repo. This should be migrated to an official `keptn` repo for continued support.

@DavidPHirsch FYI

**Comment by agardnerIT** [comment]
Linking: https://github.com/keptn/keptn/issues/9501 and https://github.com/keptn/community/issues/226

**Comment by agardnerIT** [comment]
Re-openening as not complete. The repo exists but we haven't migrated the tutorial over because we're missing admin rights.

https://github.com/keptn/killercoda

**Comment by odubajDT** [comment]
Since Keptn V1 has reached EOL on December 22nd, 2023, this issue has been closed.
