### ISSUE TITLE
Documentation is not up-to-date

### ISSUE THREAD

**Issue by shardulsr** [keptn/keptn#9325]
**Environment**

* Client OS (e.g., Linux, macOS, Windows): N/A
* Keptn Version (`keptn version`): N/A
* Kubernetes Cloud Provider (e.g., GKE, AKS): N/A
* Kubernetes version (`kubectl version`): N/A

**Affected Component**

* [ ] Approval
* [ ] Bridge
* [ ] CLI
* [ ] Datastore
* [x] Docs
* [ ] Distributor / Event Broker
* [x] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**

The documentation is not up to date.

1.  https://keptn.sh/docs/1.0.x/install/helm-install/#full-keptn-installation - It says that you can set `--set=continuousDelivery.enabled=true` can be set to enable Contnuous delivert, however as per the latest docs of 1.0, this has moved to `.bridge.installationType` [section](https://github.com/keptn/keptn/blob/dc432f515520bfb0f72b8acc4dab808acd11a745/installer/manifests/keptn/values.yaml#L462).

2. As per the docs [here](https://github.com/keptn/keptn/blob/dc432f515520bfb0f72b8acc4dab808acd11a745/installer/manifests/keptn/values.yaml#L462), to access the bridge, we have to run the command :

   ```bash
   kubectl -n keptn port-forward svc/api-gateway-nginx 8080:8080
   ```
    however, if we follow the instructions for installation till this point, then `api-gateway-nginx` is exposed on port `80` which is also  the [default](https://github.com/keptn/keptn/blob/6db0fe6b668b8096e1733951cfd1eaf6899bb997/installer/manifests/keptn/values.yaml#L190) with helm chart installation, so the command should be:

   ```bash
   kubectl -n keptn port-forward svc/api-gateway-nginx 8080:80
   ```

3. As of 1.0, both [jmeter-service](https://github.com/keptn-contrib/jmeter-service/) and [helm-service](https://github.com/keptn-contrib/helm-service/) have moved to `keptn-contrib` organization. Hence the instruction to install them in the [Install Execution Plane](https://github.com/keptn-contrib/helm-service/) section should be updated to: 

   ```bash
   helm upgrade --install jmeter-service https://github.com/keptn-contrib/jmeter-service/releases/download/0.18.1/jmeter-service-0.18.1.tgz -n keptn

   helm upgrade --install helm-service https://github.com/keptn-contrib/helm-service/releases/download/0.18.1/helm-service-0.18.1.tgz -n keptn
   ```

4.  The [The –set flag](https://keptn.sh/docs/1.0.x/install/helm-install/#the---set-flag) section should also be updated to give an example to set something other than `--set=continuousDelivery.enabled=true`, since it can not longer be set that way.

5.  The [Download Keptn Helm Charts](Download Keptn Helm Charts) section also has wrong helm chart URLs.

     https://github.com/keptn/keptn/releases/download/1.0.0/helm-service-1.0.0.tgz - Doesn't work.
     https://github.com/keptn/keptn/releases/download/1.0.0/jmeter-service-1.0.0.tgz - Doesn't work.

     The right URLs are these - 
       https://github.com/keptn-contrib/helm-service/releases/download/0.18.1/helm-service-0.18.1.tgz
       https://github.com/keptn-contrib/jmeter-service/releases/download/0.18.1/jmeter-service-0.18.1.tgz

6. This section [Install Keptn using a Root-Context](https://keptn.sh/docs/1.0.x/install/helm-install/#install-keptn-using-a-root-context) also points to the old `--set=continuousDelivery.enabled=true`.

**To Reproduce**

**Expected behavior**

The document should point to the right URL.

**Current behavior**

The document doesn't point to the right URL.

**Screenshots**

**Additional context**

**Comment by shardulsr** [comment]
I can raise a PR to fix these issues in the docs.

**Comment by odubajDT** [comment]
Hello @shardulsr, thank you for raising this ticket and using Keptn! We would really appreciate a contribution, so if you want to work on this fix, please let me know so I can assign this ticket to you.

Thanks!

**Comment by thisthat** [comment]
Thank you @shardulsr, I am assigning this ticket to you :shipit:

**Comment by shardulsrivastava** [comment]
@thisthat sorry for the confusion, but could you please assign the ticket to this ID, the other ID that i used to raise the ticket is my office ID.

**Comment by thisthat** [comment]
Sure thing :)
