### ISSUE TITLE
Add a Test Start Event

### ISSUE THREAD

**Issue by robertjahn** [keptn/keptn#933]
**Is your feature request related to a problem? Please describe.**
After a deployment one does not know that a test is running.  One does get a test finished event.

**Describe the solution you'd like**
Add a new keptn event.  then can be viewed in bridge and notification services that listen for events

**Describe alternatives you've considered**
Have to manually connect to jmeter service to review logs.

**Additional context**

**Comment by dirkwall** [comment]
We'll take care of that with the KeptnEngine and the introduction of START_* events and DONE events. #508 #533
