### ISSUE TITLE
Ensure that all needed Keptn services are running - implement sanity checks before executing

### ISSUE THREAD

**Issue by dirkwall** [keptn/keptn#936]
The information that Keptn is set up and configured properly, so it can handle incoming requests as expected is not available now. It either works or it doesn't and you have no way of telling beforehand what it's going to be, other than checking that all services have deployed successfully and are registered to the correct events.

Possible implementation: An operator of operators, that ensures that all needed services are running in the correct version.

**Comment by christian-kreuzberger-dtx** [comment]
So for the CLI this could be something like
```
keptn status # displays the status of the keptn installation
```

with the addition of
```
keptn ls # displays all namespaces, pods, ...
```
?

**Comment by christian-kreuzberger-dtx** [comment]
As an example output, `keptn status` could display the following output:

```bash
Connected to https://api.keptn.1.2.3.4.xip.io
Cluster Name: cluster-ckreuzberger
Cluster Zone: us-central1-a
GKE Project: my-cluster-project

Service Status
Name                                 Status
api                                      Running
configuration-service          Running
evaluation-service              Running
gatekeeper-service            not installed
...
```

**Comment by dirkwall** [comment]
`keptn status` now shows the remote endpoint to which it is connected (#215)
`keptn ls` should at one point in time show a list of projects and onboarded services, rather than Keptn services (maybe `keptn get projects` is a more accurate command for that).

Anyways, this issue is not about integrating a sanity check into the CLI, but more about having the first version of such a sanity check that is executed before starting a new delivery or operators flow.

Clearly, once we have that, the integration into the CLI makes sense.

**Comment by agrimmer** [comment]
With PR https://github.com/keptn/keptn/pull/2022, we now distribute Keptn as Helm-chart, which does not require any operator for now. Furthermore, the CLI even waits for all deployments in this Helm-chart to be ready. 

Finally, with issue https://github.com/keptn/keptn/issues/1779, we are introducing a /health endpoints which allow a way to check the availability of a service.
