### ISSUE TITLE
mongo probes timing out when installed via helm

### ISSUE THREAD

**Issue by mathnogueira** [keptn/keptn#9397]
**Environment**

* Client OS (e.g., Linux, macOS, Windows): N/A
* Keptn Version (`keptn version`): N/A
* Kubernetes Cloud Provider (e.g., GKE, AKS): GKE
* Kubernetes version (`kubectl version`): v1.22.13

**Affected Component**

* [ ] Approval
* [ ] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**

When installing Keptn via helm using the command described in the [quickstart page](https://keptn.sh/docs/quickstart/#helm), the mongo instance doesn't become healthy due to the probes taking too long to respond. For instance, the ping script was taking almost  60s to execute while the timeout was only 5s. This would happen with the readiness probe as well.

I managed to successfully install Keptn after I changed the configuration of the probes to increase the timeout and period parameters. But I know this is not the correct way of solving this issue.

Note: I tried updating the docker image to check if that was a bug in the used image version, but after updating to the latest bitnami's MongoDB image, the problem persisted.

**To Reproduce**

1. Create a GKE cluster
2. Install Keptn on it using helm
3. Notice that mongo will never be healthy

**Expected behavior**

Mongo should start

**Current behavior**

Mongo is not starting

**Screenshots**

**Additional context**

**Comment by eemrdog** [comment]
In my case, updating the keptn-mongo deployment with both readiness and liveness probe timeoutSeconds: 15 worked well on an Ubuntu 20.04 LTS Azure VM with microK8s deployed.

**Comment by thisthat** [comment]
Thanks for your input @eemrdog
I've seen this happening multiple times. I suggest bumping the default timeout to 15s, as you suggested.

You can directly configure the probes via helm values to fix your issue in the short term @mathnogueira.
You can pass values to the Bitnami Chart via `--set mongo. readinessProbe. initialDelaySeconds=30`, for example. You can see the list of options here: https://github.com/bitnami/charts/blob/main/bitnami/mongodb/values.yaml#L567

**Comment by thisthat** [comment]
I am closing the issue. @mathnogueira feel free to re-open it if bumping the initial delay of the readiness probe didn't solve your problem
