### ISSUE TITLE
Killercoda initial tutorial is not starting

### ISSUE THREAD

**Issue by danielbdias** [keptn/keptn#9398]
Hi folks!

I've tried to run your tutorial through Killercoda, but I got a high waiting time to start the environment. When I made a ctrl+c on the Killercoda terminal and tried to check the environment, I got this: 

<img width="1780" alt="image" src="https://user-images.githubusercontent.com/12397879/210637606-00de77c9-3112-457d-b7bc-cafeb8ccc885.png">

**Environment**

* Killercoda tutorial

**Affected Component**

* [ ] Approval
* [ ] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**

When I start a Killercoda tutorial, just in the setup phase I got 10 minutes waiting, most of the time on the last step (11/11).

**To Reproduce**

- Go to https://killercoda.com/keptn/scenario/keptn-end-to-end-delivery
- Login
- Wait for the Killercoda env to start

**Expected behavior**

All pods should be running properly.

**Current behavior**

Some keptn pods on Killercoda env stay on `CrashLoopBackOff` state.

**Comment by afzal442** [comment]
Hey @danielbdias I think you mistimed it. Did u check it again? here is below what I got. Thanks

![image](https://user-images.githubusercontent.com/11625672/211494375-4987b76f-918a-4ec4-92b7-5640c78daddc.png)

**Comment by danielbdias** [comment]
It worked @afzal442 , thanks!
