### ISSUE TITLE
Update 0.5.0 Cloud Events Specification 

### ISSUE THREAD

**Issue by robertjahn** [keptn/keptn#940]
**Describe the bug**
This document is not accurate.  Need accurate reference for developing community services.
https://github.com/keptn/keptn/blob/release-0.5.0/specification/cloudevents.md#configuration-change.   This document too also refers to old configuration-changed event. https://keptn.sh/docs/0.5.0/reference/custom-service/

**To Reproduce**
Review the logs in the keptn distributor services.  For example: configuration.change event document missing the 'canary' attribute.  For example test-finished document says testStrategy and deploymentStrategy, but the actual event is all lower case, not mixed case. 

**Expected behavior**
Document should show complete message examples will all available attributes listed in the correct case.

**Environment**
Keptn 050

**Additional context**
See attached postman collection for what I determined to be valid messages.  

[keptn-notifications.postman_collection.json.zip](https://github.com/keptn/keptn/files/3699086/keptn-notifications.postman_collection.json.zip)

**Comment by dirkwall** [comment]
We'll work on this, thanks for pointing that out.

**Comment by johannes-b** [comment]
This issues is related to: #997

**Comment by dirkwall** [comment]
Fixed with #997
