### ISSUE TITLE
Consider `cosign` tool in github release to sign the artifacts

### ISSUE THREAD

**Issue by afzal442** [keptn/keptn#9438]
**Describe the solution you'd like**

The following ways from the files linked below to be considered

https://github.com/pulumi/pulumi/pull/11310/files

https://github.com/kubearmor/kubearmor-client/pull/237/files

cc @mowies

**Comment by mowies** [comment]
We already use cosign to sign our container images :)
See this: https://github.com/keptn/keptn/blob/master/.github/workflows/test-and-build-docker-images.yml#L239-L259

**Comment by afzal442** [comment]
Hmm! nice thanks Moritz for that. I am confused if it is during release. 😄

**Comment by mowies** [comment]
yeah the signing only happens during the release, not on every dev image :)
i'll close this one :)
