### ISSUE TITLE
Publish Keptn spec (.json schema) in SchemaStore

### ISSUE THREAD

**Issue by lberardinelli** [keptn/keptn#9452]
**Is your feature request related to a problem? Please describe.**
Ketpn specs are consolidated JSON schema documents. It would be great to disseminate them in JSON Schemastore [https://www.schemastore.org/json/](https://www.schemastore.org/json/ )

**Describe the solution you'd like**
Publish Keptn specs in JSON Schema store. It may improve the visibility of the Keptn project and help us in disseminating research activities.

**Describe alternatives you've considered**
No alternatives

**Additional context**
The Johannes Kepler University, Business Informatics - Software Engineering Institute is performing research activities on JSON Schema and it is using Keptn and its specification as the main case study.

A. Colantoni, A. Garmendia, L. Berardinelli, M. Wimmer and J. Bräuer, "Leveraging Model-Driven Technologies for JSON Artefacts: The Shipyard Case Study," 2021 ACM/IEEE 24th International Conference on Model Driven Engineering Languages and Systems (MODELS), 2021, pp. 250-260, doi: 10.1109/MODELS50736.2021.00033.

A. Colantoni, B. Horvath, A. Horvath, L. Berardinelli and M. Wimmer, "Towards Continuous Consistency Checking of DevOps Artefacts," in 2021 ACM/IEEE International Conference on Model Driven Engineering Languages and Systems Companion (MODELS-C), Fukuoka, Japan, 2021 pp. 449-453.
doi: 10.1109/MODELS-C53483.2021.00069 

Alessandro Colantoni, Luca Berardinelli, Antonio Garmendia, and Johannes Bräuer. 2022. Towards blended modeling and simulation of DevOps processes: the Keptn case study. In Proceedings of the 25th International Conference on Model Driven Engineering Languages and Systems: Companion Proceedings (MODELS '22). Association for Computing Machinery, New York, NY, USA, 784–792. https://doi.org/10.1145/3550356.3561597

In particular, we are concentrating on **JSON Schema Draft 7**.  Any/all versions of the Keptn specs can. **We kindly ask you to publish the Keptn specs** (in particular, Shipyard and SLI/SLO) **that conform to [JSON Schema Draft 7](https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-validation-01)**

**Comment by sudiptob2** [comment]
Hi, I am willing to contribute to this issue. I am an opensource beginner, could you please assign this issue to me?

**Comment by sudiptob2** [comment]
Thanks, I am working on it. Will be opening a draft PR shortly :+1:

**Comment by sudiptob2** [comment]
Hi, could you please clarify my understanding of the task :pray: 

I have found **keptn** specs are defined [here](https://github.com/keptn/spec). What I understand from the issue description is that the task is to upload these schemas (for example [shipyard schema](https://github.com/keptn/spec)) into the [schema store](https://www.schemastore.org/json/).

I saw that **draft 4** is defined in the schema definitions (for example [shipyard schema](https://github.com/keptn/spec)).
Could you please guide me on how can I identify/validate schemas that conform to JSON Schema Draft 7? Or can I just take schemas from [spec repo](https://github.com/keptn/spec) and upload them in the schema store?

Thanks much for your continued support.

**Comment by agardnerIT** [comment]
@lberardinelli are you able to assist @sudiptob2 with the questions raised above?

**Comment by agardnerIT** [comment]
@sudiptob2 if you figure this out, I have a similar issue raised for KLT that you may wish to also complete?

https://github.com/keptn/lifecycle-toolkit/issues/1292

**Comment by sudiptob2** [comment]
Thanks, I could not finish this task because first, we need to aggregate **Keptn/KLT** schemas and save them as JSON files in GitHub. Then I can refer those schemas into the schema store by making a PR into the [schema store](https://www.schemastore.org/json/) repository.

**Comment by odubajDT** [comment]
Since Keptn V1 has reached EOL on December 22nd, 2023, this issue has been closed.
