### ISSUE TITLE
Keptn CLI: install option to roll-out a minimum set of services required for quality gates standalone

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#947]
The `keptn install` command has to be extended to roll-out a minimum set of services required for quality gates standalone.

**Comment by christian-kreuzberger-dtx** [comment]
We decided in the sprint planning that we will adapt the installer at the very end of the release (e.g., remove gatekeeper, remove jmeter). The quality-gates use case should work as it is right now (obviously the new evaluation service needs to be installed).

**Comment by christian-kreuzberger-dtx** [comment]
Closed as of Sprint Planning on Oct 24th.
We will use a different behaviour (delete the distributor)
