### ISSUE TITLE
Keptn CLI: support for 'start evaluation' and 'get evaluation-results'

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#948]
The Keptn CLI needs to support: 

- **keptn start evaluation**
E.g.: `keptn start evaluation --project PROJECTNAME --service SERVICENAME --reference test-run-A --start 2019-07-24T10:17:12 --period 5m`

The start-evaluation command, as shown above, will evaluate the service level objects of the specified service in the specified project over the last 5 minutes and will save the results under the reference test-run-A. This command will return a KeptnContext ID that you will need for querying the results of the evaluation.

- **keptn get evaluation-results**
E.g.: 
  - `keptn get evaluation-results --project PROJECTNAME --service SERVICENAME --reference test-run-A`
  - `keptn get evaluation-results --keptnContext 1234-5678-90`

Returns the results of the same Keptn quality gates evaluation. The results come in the form of the evaluation-done event, that is specified here.

---
Status:

- [x] keptn send event evaluation.start
- [x] keptn get event evaluation.done
- [x] keptn get event with wrong keptn-context returns pointer instead of errorMsg
- [x] double-check documentation on keptn.sh

**Comment by christian-kreuzberger-dtx** [comment]
About the add secret command: @bacherfl and myself are using `kubectl` as follows to add the relevant secrets within the keptn namespace:
```console
kubectl create secret -n keptn generic dynatrace-credentials-sockshop --from-file=dynatrace-credentials=./my-dynatrace-credentials.yaml
kubectl create secret -n keptn generic prometheus-credentials-sockshop --from-file=prometheus-credentials=./my-prometheus-credentials.yaml 
```

The secret contains the API URL as well as username/password or a token.

I think for now this is sufficient, but I'd like to see a `keptn create secret` command looking something like this (in accordance if the `keptn add-resource` command):
```console
keptn add-secret --project=sockshop --name=dynatrace-credentials --resource=./my-dynatrace-credentials.yaml
```
Where as the file provided in `resource` gets uploaded to the REST API, and the REST API then adds this to the current kubernetes cluster as a secret.
