### ISSUE TITLE
Move the Killercoda Demo to Keptn Repo

### ISSUE THREAD

**Issue by SuperAayush** [keptn/keptn#9501]
As discussed in today's community meeting have to move the Killercoda demo to the Keptn repo.
Original Repo: https://github.com/afzal442/keptn-pg-killerway

Meeting minutes: https://docs.google.com/document/d/1y7a6uaN8fwFJ7IRnvtxSfgz-OGFq6u7bKN6F7NDxKPg/edit#

cc- @DavidPHirsch @agardnerIT @bradmccoydev

**Comment by agardnerIT** [comment]
Fantastic. Thanks for creating this. You beat me to it!

Also linking this issue I before I saw this: https://github.com/keptn/community/issues/226

**Comment by odubajDT** [comment]
Since Keptn V1 has reached EOL on December 22nd, 2023, this issue has been closed.
