### ISSUE TITLE
Killercoda new issue link redirect correction

### ISSUE THREAD

**Issue by SuperAayush** [keptn/keptn#9502]
**Environment**

* Killercoda

**Affected Component**
* [ ] Approval
* [ ] Bridge
* [ ] CLI
* [ ] Datastore
* [X] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**

After completing the tutorial of keptn on killercoda the last page the link to "Create a issue on GitHub" redirects you to the GitHub homepage.  

**To Reproduce**
Visit this link and follow the steps mentioned in the tutorial until the last section appears.
Link: https://killercoda.com/keptn/scenario/keptn-end-to-end-delivery

**Expected behavior**
It should redirect to the keptn repo of creating a new issue.
Maybe here: https://github.com/keptn/keptn/issues/new/choose

**Screenshots**
![Screenshot 2023-02-07 at 6 28 06 PM](https://user-images.githubusercontent.com/78820926/217623201-717c58c5-a683-43ae-b10f-094aa3419f43.png)

**Additional context**
Before working on this issue should get along with issue #9501

cc- @DavidPHirsch @bradmccoydev @agardnerIT

**Comment by SuperAayush** [comment]
I would like to take this!!

**Comment by agardnerIT** [comment]
Thanks @SuperAayush. The file you need to modify is [here](https://github.com/afzal442/keptn-pg-killerway/blob/master/keptn-end-to-end-delivery/finish.md).

You can action this now and have it point to `https://github.com/afzal442/keptn-pg-killerway/issues/new` then when we transfer, we'll update the link. How does that sound?

**Comment by SuperAayush** [comment]
> Thanks @SuperAayush. The file you need to modify is [here](https://github.com/afzal442/keptn-pg-killerway/blob/master/keptn-end-to-end-delivery/finish.md).
> 
> You can action this now and have it point to `https://github.com/afzal442/keptn-pg-killerway/issues/new` then when we transfer, we'll update the link. How does that sound?

Understood!!
Made a PR - https://github.com/afzal442/keptn-pg-killerway/pull/75

**Comment by SuperAayush** [comment]
@agardnerIT should I close this issue as completed?

**Comment by agardnerIT** [comment]
Yup, all done and completed. Thanks!!
