### ISSUE TITLE
Keptn status Error: open /home/azureuser/.keptn/.keptn__k3d-mykeptn__keptn: no such file or directory

### ISSUE THREAD

**Issue by JJena** [keptn/keptn#9521]
**Environment**

* Client OS (e.g., Linux, macOS, Windows): Ubuntu
* Keptn Version (`keptn version`): 1.2.0
* Kubernetes Cloud Provider (e.g., GKE, AKS): Azure VM/k3d
* Kubernetes version (`kubectl version`): 

Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-19T02:26:55Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6+k3s1", GitCommit:"3228d9cb9a4727d48f60de4f1ab472f7c50df904", GitTreeState:"clean", BuildDate:"2022-01-25T01:27:44Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.26) and server (1.22) exceeds the supported minor version skew of +/-1

**Affected Component**

* [ ] Approval
* [ ] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ yes] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**

After installing Keptn from helm and all pods are in running status, getting multiple errors.

azureuser@master:~$keptn status:

Keptn CLI is already on the latest version ( 1.2.0 )!
* Your Keptn CLI version: 1.2.0
* Warning: could not check Keptn server version: This command requires to be authenticated. See "keptn auth" for details
* To disable the daily version check, please execute:
 - keptn set config AutomaticVersionCheck false

Error: open /home/azureuser/.keptn/.keptn__k3d-mykeptn__keptn: no such file or directory

azureuser@master:~$ keptn auth
Error: We haven't found any Keptn Installation, Please follow the upgrade guide and patch the namespace with the annotation & label 'keptn.sh/managed-by: keptn'

azureuser@master:~$ kubectl cluster-info
Kubernetes control plane is running at https://0.0.0.0:41677
CoreDNS is running at https://0.0.0.0:41677/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
Metrics-server is running at https://0.0.0.0:41677/api/v1/namespaces/kube-system/services/https:metrics-server:https/proxy

<img width="603" alt="image" src="https://user-images.githubusercontent.com/19985725/220175237-7730ed0c-1817-4004-9627-18c9e595e32d.png">

<img width="603" alt="image" src="https://user-images.githubusercontent.com/19985725/220175284-9dc79d95-3c7c-439d-811e-36601baf823a.png">

**To Reproduce**

Followed steps from here: https://github.com/keptn/keptn

- Azure ubuntu vm created 2vCPU/8GB RAM
- Install latest docker (23.0.1)
- Install latest kubectl (v1.22.6+k3s1)
- Install latest helm (v3.10.1)
- Install k3d 5.3.0
- k3d cluster create mykeptn -p "8082:80@loadbalancer" --k3s-arg "--no-deploy=traefik@server:*"
- export KUBECONFIG=$(k3d kubeconfig write mykeptn)
- Keptn cli install (v1.2.0)
- Install keptn: "helm install keptn keptn/keptn \
-n keptn --version=1.1.0 --create-namespace \
--wait \
--set=continuousDelivery.enabled=true,apiGatewayNginx.type=LoadBalancer \
--timeout 10m \
--debug"

**Expected behavior**

Supposed to return Keptn API/bridge Endpoint URL details

**Current behavior**

azureuser@master:~$ keptn status
Keptn CLI is already on the latest version ( 1.2.0 )!
* Your Keptn CLI version: 1.2.0
* Warning: could not check Keptn server version: This command requires to be authenticated. See "keptn auth" for details
* To disable the daily version check, please execute:
 - keptn set config AutomaticVersionCheck false

Error: open /home/azureuser/.keptn/.keptn__k3d-mykeptn__keptn: no such file or directory

azureuser@master:~$ keptn auth
Error: We haven't found any Keptn Installation, Please follow the upgrade guide and patch the namespace with the annotation & label 'keptn.sh/managed-by: keptn'

**Screenshots**

**Additional context**

**Comment by agardnerIT** [comment]
Hi @JJena , we're using k3d for the Killercoda demo too so this is strange. Here's the install script if you want to pick through it.

https://github.com/afzal442/keptn-pg-killerway/blob/master/keptn-end-to-end-delivery/intro_foreground.sh

A few things I noticed immediately:

- You are installing `1.2.0` for the CLI and `1.1.0` for the product (via helm). Please make these both `1.2.0` ([helm on artifacthub](https://artifacthub.io/packages/helm/keptn/keptn))
- You are exposing `8082` not `8080` as per my creation script.

**Comment by JJena** [comment]
Sorry I have tried both 1.2.0 first and then thought of trying a lower version to see if it makes diff but no.

I created another issue here for killercoda. Exactly same same err message.

https://github.com/afzal442/keptn-pg-killerway/issues/81

**Comment by agardnerIT** [comment]
`keptn status` will fail until `keptn auth` is executed because `keptn auth` creates the required `.keptn` folder and files.

If there is any enhancement here, perhaps the CLI could be more explicit about this. Running `keptn status` **before** `keptn auth` is still a valid usecase as users may want to see other info (such as installed versions) but the error message should be clearer.

This can be closed.
