### ISSUE TITLE
Keptn install failed due to pod status CrashLoopBackOff

### ISSUE THREAD

**Issue by JJena** [keptn/keptn#9523]
**Environment**

* Client OS (e.g., Linux, macOS, Windows): M1 Mac/Multipass/Ubuntu 22.04.1 LTS
* Keptn Version (`keptn version`): 1.2.0
* Kubernetes Cloud Provider (e.g., GKE, AKS): N/A
* Kubernetes version (`kubectl version`): k3d version v5.3.0, k3s version v1.22.6-k3s1 (default)
* Docker version: 23.0.1
* Helm version: v3.10.1

**Affected Component**

* [ ] Approval
* [ ] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook
* [ yes] Mongo
* [ yes] Secret Service
* [ yes] Resource Service
* [ yes] Api Service
* [ yes] Mongo

**Describe the bug**

Keptn install via Helm is failing because of error: 

ready.go:277: [debug] Deployment is not ready: keptn/keptn-mongo. 0 out of 1 expected pods are read
Error: INSTALLATION FAILED: timed out waiting for the condition
helm.go:84: [debug] timed out waiting for the condition

<img width="997" alt="image" src="https://user-images.githubusercontent.com/19985725/220473049-923b72cd-b904-4110-85c3-078c15b97d35.png">

ubuntu@k3s:~$ kubectl describe pod keptn-mongo-7dfcb6dbc7-tbf6g -nkeptn
Name:             keptn-mongo-7dfcb6dbc7-tbf6g
Namespace:        keptn
Priority:         0
Service Account:  keptn-mongo
Node:             k3d-mykeptn-server-0/172.18.0.2
Start Time:       Tue, 21 Feb 2023 16:58:44 -0500
Labels:           app.kubernetes.io/component=mongodb
                  app.kubernetes.io/instance=keptn
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=mongo
                  helm.sh/chart=mongo-13.6.3
                  pod-template-hash=7dfcb6dbc7
Annotations:      <none>
Status:           Running
IP:               10.42.0.58
IPs:
  IP:           10.42.0.58
Controlled By:  ReplicaSet/keptn-mongo-7dfcb6dbc7
Containers:
  mongodb:
    Container ID:   containerd://2eecabd54cae30580d386fc5073d7b7f1bb76812a3bf9cc18379b8ef12ac300e
    Image:          docker.io/bitnami/mongodb:6.0.3-debian-11-r20
    Image ID:       docker.io/bitnami/mongodb@sha256:cb2ca05a886273fad944c1256dc42b6c00b892037025c1ac3536b7f64f660f90
    Port:           27017/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 21 Feb 2023 17:19:56 -0500
      Finished:     Tue, 21 Feb 2023 17:19:56 -0500
    Ready:          False
    Restart Count:  9
    Limits:
      cpu:     1
      memory:  500Mi
    Requests:
      cpu:      200m
      memory:   100Mi
    Liveness:   exec [/bitnami/scripts/ping-mongodb.sh] delay=30s timeout=10s period=20s #success=1 #failure=6
    Readiness:  exec [/bitnami/scripts/readiness-probe.sh] delay=5s timeout=5s period=10s #success=1 #failure=6
    Environment:
      BITNAMI_DEBUG:                    false
      MONGODB_EXTRA_USERNAMES:          keptn
      MONGODB_EXTRA_DATABASES:          keptn
      MONGODB_EXTRA_PASSWORDS:          <set to the key 'mongodb-passwords' in secret 'mongodb-credentials'>  Optional: false
      MONGODB_ROOT_USER:                admin
      MONGODB_ROOT_PASSWORD:            <set to the key 'mongodb-root-password' in secret 'mongodb-credentials'>  Optional: false
      ALLOW_EMPTY_PASSWORD:             no
      MONGODB_SYSTEM_LOG_VERBOSITY:     0
      MONGODB_DISABLE_SYSTEM_LOG:       no
      MONGODB_DISABLE_JAVASCRIPT:       no
      MONGODB_ENABLE_JOURNAL:           yes
      MONGODB_PORT_NUMBER:              27017
      MONGODB_ENABLE_IPV6:              no
      MONGODB_ENABLE_DIRECTORY_PER_DB:  no
    Mounts:
      /bitnami/mongodb from datadir (rw)
      /bitnami/scripts from common-scripts (rw)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  common-scripts:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      keptn-mongo-common-scripts
    Optional:  false
  datadir:
    Type:        PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:   keptn-mongo
    ReadOnly:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  22m                   default-scheduler  Successfully assigned keptn/keptn-mongo-7dfcb6dbc7-tbf6g to k3d-mykeptn-server-0
  Normal   Started    21m (x4 over 22m)     kubelet            Started container mongodb
  Normal   Pulled     20m (x5 over 22m)     kubelet            Container image "docker.io/bitnami/mongodb:6.0.3-debian-11-r20" already present on machine
  Normal   Created    20m (x5 over 22m)     kubelet            Created container mongodb
  Warning  BackOff    116s (x101 over 22m)  kubelet            Back-off restarting failed container

**To Reproduce**

- Install Multipass on M1 mac and create instance - "multipass launch --name k3s --mem 8G --disk 20G --cpus 4"
- multipass shell k3s
- Docker install:
sudo apt-get update
sudo apt-get install \
    ca-certificates \
    curl \
    gnupg \
    lsb-release
sudo mkdir -m 0755 -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
sudo usermod -aG docker $USER
newgrp docker
- Kubectl install:
sudo snap install kubectl --classic
- Helm install:
sudo snap install helm --classic
- k3d install/cluster create:
curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | TAG=v5.3.0 bash
k3d cluster create mykeptn -p "8080:80@loadbalancer" --k3s-arg "--no-deploy=traefik@server:*"
export KUBECONFIG=$(k3d kubeconfig write mykeptn)
- Install Keptn CLI:
curl -sL https://get.keptn.sh | bash
- Install keptn
helm repo add keptn https://charts.keptn.sh && helm repo update
helm install keptn keptn/keptn \
-n keptn --version=1.2.0 --create-namespace \
--wait \
--set=continuousDelivery.enabled=true,apiGatewayNginx.type=LoadBalancer \
--timeout 10m \
--debug

**Expected behavior**

Keptn install should be successful with all pods in Running status.

**Current behavior**

**Screenshots**

**Additional context**

**Comment by RealAnna** [comment]
Hi @JJena, unfortunately, your Mac won't work with our installation of mongoDB since arm64 is currently not supported: https://github.com/bitnami/charts/issues/7305

**Comment by JJena** [comment]
> Hi @JJena, unfortunately, your Mac won't work with our installation of mongoDB since arm64 is currently not supported: [bitnami/charts#7305](https://github.com/bitnami/charts/issues/7305)
> 
> I created an issue to make sure we document this #9525

Thank you.

**Comment by JJena** [comment]
known limitation
