### ISSUE TITLE
docs: update support page to include known limitations

### ISSUE THREAD

**Issue by RealAnna** [keptn/keptn#9525]
https://keptn.sh/docs/1.0.x/install/k8s-support/

should be updated up to v1 and should mention the fact that we use bitnami MongoDB so this won't work on arm based nodes (e.g., on a Mac M1) due to this https://github.com/bitnami/charts/issues/7305

**Comment by bhavyastar** [comment]
Hey, @RealAnna, I would like to work on this issue. Can you assign this to me?

**Comment by thisthat** [comment]
Hey @bhavyastar thanks for volunteering! I am assigning the issue to you :)

**Comment by bhavyastar** [comment]
Hey @thisthat, Thanks for assigning this to me. I am working on this and I also understand it but I just want to confirm whether what I am thinking is the right one or not!! 

<img width="923" alt="Screenshot 2023-03-01 at 2 33 54 PM" src="https://user-images.githubusercontent.com/84725791/222092948-7d24e83c-4ea4-4f32-b646-56fa49d78679.png">

There are separate tables for versions 0.17, 0.18 and so on. So, I have to make a table with respect to version 1.0 and mention all the support from 0.17,01.18 and so on. 

<img width="1101" alt="Screenshot 2023-03-01 at 2 36 52 PM" src="https://user-images.githubusercontent.com/84725791/222093579-f124a7c9-b212-433f-b2b5-135174ae31ee.png">

**Comment by thisthat** [comment]
Hey @bhavyastar, the goal of this ticket should be changing this page https://keptn.sh/docs/1.0.x/install/k8s-support/ with the following:
- replace `0.17.x` with `1.x.y`
- add a disclaimer that we only support amd64 architecture. Arm-based nodes, e.g., a kind cluster on a mac book with the M1 processor, are not supported due to our dependency on the Bitnami Mongo Charts. 

I hope this clarifies your questions :)

**Comment by shayyxi** [comment]
I can work on this if it is still open?

**Comment by bhavyastar** [comment]
Hey @shayyxi, It has already been done and merged.

**Comment by agardnerIT** [comment]
@RealAnna, @thisthat or @bhavyastar please close this issue if it is done. Thanks.

**Comment by ashutosh887** [comment]
@bhavyastar If merged, please close this issue
Thanks 👍🏻 )

**Comment by odubajDT** [comment]
Since Keptn V1 has reached EOL on December 22nd, 2023, this issue has been closed.
