### ISSUE TITLE
bridge can't access mongodb when oauth is enabled

### ISSUE THREAD

**Issue by robbert229** [keptn/keptn#9526]
Your issue may already be reported! Please search on the [issue tracker](https://github.com/keptn/keptn/issues) before creating a new one.

**Environment**

* Client OS (e.g., Linux, macOS, Windows): Any
* Keptn Version (`keptn version`): 1.2.0
* Kubernetes Cloud Provider (e.g., GKE, AKS): Any
* Kubernetes version (`kubectl version`): Any 

Any

**Affected Component**

* [ ] Approval
* [x] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**

Currently the bridge service is unable to connect to mongodb due to its environment variable pointing to a host that doesn't exist. `MONGODB_HOST: keptn-:27017`.
```
> bridge-server@ start /usr/src/app/server
> node --experimental-specifier-resolution=node dist/server/server.js
[Keptn] 2023-02-24T21:38:07.419Z error   [Server] Error while starting the application. Cause : MongoServerSelectionError: getaddrinfo ENOTFOUND keptn-
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bridge-server@ start: `node --experimental-specifier-resolution=node dist/server/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bridge-server@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

The recent fix for mongo host overrides (#9470 #9471) introduced this defect. In that PR changes were made to the configuration such that mongo.service.nameOverride was stripped from the chart.
```
-              value: '{{ .Release.Name }}-{{ .Values.mongo.service.nameOverride }}:{{ .Values.mongo.service.ports.mongodb }}'
+              value: '{{ .Release.Name }}-mongo:{{ .Values.mongo.service.ports.mongodb }}'
```
However bridge was missed when this happened. Resulting in bridge crash looping whenever it needs to talk to mongodb.
https://github.com/keptn/keptn/blob/afe2ac73ce7c66acbe60d859250e7f4250c009ae/installer/manifests/keptn/templates/core.yaml#L154

**To Reproduce**

1. Install keptn with oidc enabled

**Expected behavior**
Bridge should not crashloop when oidc is turned on.

**Current behavior**
Bridge is crash looping with the following error: 
```
> bridge-server@ start /usr/src/app/server
> node --experimental-specifier-resolution=node dist/server/server.js
[Keptn] 2023-02-24T21:38:07.419Z error   [Server] Error while starting the application. Cause : MongoServerSelectionError: getaddrinfo ENOTFOUND keptn-
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bridge-server@ start: `node --experimental-specifier-resolution=node dist/server/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bridge-server@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Screenshots**

**Additional context**

**Comment by thisthat** [comment]
fixed by https://github.com/keptn/keptn/pull/9524

**Comment by WalkerSasser** [comment]
@thisthat & @robbert229 -- I ran into this issue upgrading Keptn from 1.1.0 to 1.3.0 using Helm. Is there a disconnect between the 1.3.0 Helm chart release and the 1.3.0 release on this repo?

**Comment by RealAnna** [comment]
@WalkerSasser our helm chart has the same release of the repo, after the refactoring we did not  introduce the change proposed by @robbert229, I started a pr to fix it. In the mean time you can use the chart changing this  https://github.com/keptn/keptn/pull/9656/files#diff-cdadd3bdfa83bb05ebea07ff71587edb2f970e7986cfe9d5ce8aa447b7b71186R155
