### ISSUE TITLE
Keptn_v1.2.0 - Install error: nginx: [emerg] host not found in upstream "api-service" in /etc/nginx/keptn-endpoints.conf:10

### ISSUE THREAD

**Issue by JJena** [keptn/keptn#9540]
**Environment**

* Client OS (e.g., Linux, macOS, Windows): centos-release-7-9.2009.1.el7.centos.x86_64
* Keptn Version (`keptn version`): 1.2.0
* Kubernetes Cloud Provider (e.g., GKE, AKS): N/A (On prem)
* Kubernetes version (`kubectl version`): v1.22.6+k3s1
* Docker version: 23.0.1

**Affected Component**

* [ ] Approval
* [ ] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook
* [ YES] Nginx api gateway 

**Describe the bug**

Installing Keptn using helm with k3d is timed out because pi-gateway-nginx is stuck in CrashLoopBackOff status. Below is the log details.

kubectl -nkeptn logs api-gateway-nginx-7845f499f8-sgvkz|more
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2023/02/27 20:49:39 [emerg] 1#1: host not found in upstream "api-service" in /etc/nginx/keptn-endpoints.conf:10
nginx: [emerg] host not found in upstream "api-service" in /etc/nginx/keptn-endpoints.conf:10
 
NAME                                   READY   STATUS             RESTARTS          AGE
svclb-api-gateway-nginx-gpxnf          1/1     Running            0                 17h
mongodb-datastore-6bd5dbf876-w5kng     0/1     Init:0/2           0                 17h
statistics-service-59f98f7895-xnt7s    0/2     Init:0/3           0                 17h
lighthouse-service-56b98c4f-vw87m      0/1     Init:0/4           0                 17h
approval-service-86769fcdb4-bz4rs      0/1     Init:0/3           0                 17h
bridge-bf57cc9bf-nnfqs                 0/1     Init:0/3           0                 17h
shipyard-controller-6957454576-tkmhd   0/1     Init:0/3           0                 17h
remediation-service-fb5756d8d-w9hd8    0/1     Init:0/4           0                 17h
webhook-service-5d77df9d-q7kfb         0/1     Init:0/3           0                 17h
resource-service-78dc895fc6-bmd2p      1/1     Running            0                 17h
api-service-f5d6c6db5-72rmt            1/1     Running            0                 17h
secret-service-568bc969f7-7rk7j        1/1     Running            0                 17h
keptn-nats-0                           1/1     Running            0                 17h
keptn-mongo-7dfcb6dbc7-x9ggc           1/1     Running            0                 17h
api-gateway-nginx-7845f499f8-sgvkz     0/1     CrashLoopBackOff   211 (3m19s ago)   17h

**To Reproduce**

curl -s [https://raw.githubusercontent.com/rancher/k3d/main/install.sh](https://protect-eu.mimecast.com/s/_BMSCpBxcLKAkBhYKgWv?domain=raw.githubusercontent.com) | TAG=v5.3.0 bash

k3d cluster create mykeptn -p "8080:80@loadbalancer" --k3s-arg "--no-deploy=traefik@server:*"

export KUBECONFIG=$(k3d kubeconfig write mykeptn)

helm repo add keptn [https://charts.keptn.sh](https://protect-eu.mimecast.com/s/V8X0CrBzcjo2MGIje9Z-?domain=charts.keptn.sh) && helm repo update

![image](https://user-images.githubusercontent.com/19985725/221888926-530da7ac-9939-4815-8d24-d27d9a66e1a4.png)

**Expected behavior**

All Pods should be in Running status and Keptn install should be successful

**Current behavior**

Installation failed due to timeout

**Screenshots**

**Additional context**

**Comment by thisthat** [comment]
Hey @JJena , could you please provide the output of `kubectl get svc -n keptn` ?

**Comment by JJena** [comment]
> kubectl get svc -n keptn

NAME                  TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                                                 AGE
keptn-nats            ClusterIP      None            <none>        4222/TCP,6222/TCP,8222/TCP,7777/TCP,7422/TCP,7522/TCP   19h
webhook-service       ClusterIP      10.43.108.116   <none>        8080/TCP                                                19h
api-service           ClusterIP      10.43.37.215    <none>        8080/TCP                                                19h
resource-service      ClusterIP      10.43.138.67    <none>        8080/TCP                                                19h
secret-service        ClusterIP      10.43.177.224   <none>        8080/TCP                                                19h
approval-service      ClusterIP      10.43.209.168   <none>        8080/TCP                                                19h
mongodb-datastore     ClusterIP      10.43.99.12     <none>        8080/TCP                                                19h
statistics-service    ClusterIP      10.43.48.249    <none>        8080/TCP                                                19h
remediation-service   ClusterIP      10.43.39.74     <none>        8080/TCP                                                19h
keptn-mongo           ClusterIP      10.43.228.71    <none>        27017/TCP                                               19h
bridge                ClusterIP      10.43.49.254    <none>        8080/TCP                                                19h
lighthouse-service    ClusterIP      10.43.195.141   <none>        8080/TCP                                                19h
shipyard-controller   ClusterIP      10.43.151.143   <none>        8080/TCP                                                19h
api-gateway-nginx     LoadBalancer   10.43.114.244   172.18.0.3    80:30843/TCP                                            19h

**Comment by JJena** [comment]
> Hi @JJena do you have a load balancer set up somehow? Is there a specific reason you disable the traefik server?
> If not, and you are just interested into testing keptn locally, you can consider installing keptn without overriding apiGatewayNginx type and using portforward the API gateway after installation instead.

I just followed the instructions on this repo. I will try without disabling traefik.

<img width="862" alt="image" src="https://user-images.githubusercontent.com/19985725/221916517-6834abd9-7ffb-4135-a54e-259fc6b25c7c.png">

**Comment by thisthat** [comment]
Do you have any network policy in place? 🤔 
Nginx looks like it fails on trying to reach out to the `api-service` K8s service for satisfying the `proxy_pass` statement 🤔

**Comment by JJena** [comment]
> Do you have any network policy in place? 🤔
> Nginx looks like it fails on trying to reach out to the `api-service` K8s service for satisfying the `proxy_pass` statement 🤔

We login to the server through ssh. It could be n/w policy. I know from the past that my taurus load test couldn't upload results into blazemeter cloud due to some policy in place. Not sure if that could be related though. Need to check on policy.

**Comment by JJena** [comment]
Thanks @RealAnna  I was able to install it when I tried without LB. 

cluster creation: k3d cluster create mykeptn

keptn install : helm install keptn keptn/keptn -n keptn -create-namespace --set=continuousDelivery.enabled=true

port formward: kubectl -n keptn port-forward service/api-gateway-nginx 8080:80
