### ISSUE TITLE
Allow keptn cli to push to gitlab where gpg signed push is mandatory

### ISSUE THREAD

**Issue by JJena** [keptn/keptn#9589]
**Is your feature request related to a problem? Please describe.**
My gitlab repo has settings enabled to allow only signed push with a GPG key. CLI v1.2.0 doesn't have any option use GPG key when creating project or adding new resource. Because of this, an error shows in resource-service log : 
<img width="888" alt="image" src="https://user-images.githubusercontent.com/19985725/226431195-b9d3b07a-8623-40f0-b072-b767765944d2.png">
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/19985725/226431352-6cd66f09-7062-4762-9209-c9dee30712d1.png">

**Describe the solution you'd like**
- Resource-service pod needs to have gpg2 installed
- Before creating project, new cli command (optional) need to accept user name, gitlab email id based on which gpg key pair can be created in the resource-service pod. The output of this step should be a public key that can be added to gitlab manually and a private key that reside in the pod. GPG key needs to be linked to the git profile and by default sign all commits with gpg. Detailed steps here (https://docs.gitlab.com/ee/user/project/repository/gpg_signed_commits/)
- When creating project, a flag needs to confirm if gpg sign is required. If yes, then  check if gpg key exists and if so do "git config --global commit.gpgsign true"

**Describe alternatives you've considered**
Temporarily disabled signed commits but that's not a long term option due to security risks.

**Additional context**

**Comment by odubajDT** [comment]
Since Keptn V1 has reached EOL on December 22nd, 2023, this issue has been closed.
