### ISSUE TITLE
Change go-utils from go-dep to go-modules

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#959]

**Comment by jetzlstorfer** [comment]
what does this change mean for Keptn developers? 
If there is anything I would have to change in my local setup to develop on Keptn please let me know - thanks!

**Comment by michaelHampel** [comment]
Hello Jürgen,

changing to modules hopefully is an improvement for all developers(better dependency and release
mgmt, no external tooling necessary..)
But I first have to get it to work and see if the promises are kept:)

**Comment by christian-kreuzberger-dtx** [comment]
Hi Jürgen,

just to add to that what Michael said: We are also working on a proper contributors guide. We will ensure that the changes of go-utils are reflected in that guide.

**Comment by jetzlstorfer** [comment]
Thanks for the updates on this.
Looking forward to see the new go-modules in Keptn!
