### ISSUE TITLE
create project gives 'upstream repository not found'

### ISSUE THREAD

**Issue by doc-olliday** [keptn/keptn#9614]
**Environment**

* Client OS (e.g., Linux, macOS, Windows): **Linux**
* Keptn Version (`keptn version`): **1.3.0**
* Kubernetes Cloud Provider (e.g., GKE, AKS): **Minikube**
* Kubernetes version (`kubectl version`): **1.26.1**
* **GitLab 15.10.0 (self-hosted)**

**Affected Component**

* [ ] Approval
* [x] Bridge
* [x] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**

Doing my first steps with `keptn`, I tried to create a project according to the documentation. The creation of the project failed within Bridge as well as within CLI. The message given in both cases is (message copied from CLI response on cmdline):
```
Error: Create project was unsuccessful.
upstream repository not found
```

**To Reproduce**

The CLI command I used:
```
keptn create project podinfo --verbose --shipyard=~/tmp/shipyard-podinfo.yaml --git-user=oliver --git-token=glpat-xxxxxxxxxxxxxxxxxxx --git-remote-url=https://gitlab/gitops/keptn/podinfo.git
```

The git repository exists in GitLab and the personal access token is correct. It's possible to clone the (still empty) repo with the given URL, username and token.

**Expected behavior**

The project is created.

**Current behavior**

Project creation fails with error `upstream repository not found`

**Additional context**

The GitLab server is self-hosted.

My fist assumption was my custom CA, I'm using for all my certificates. I haven't found a possibility to tell `keptn` about the custom certificate chain.

The Minikube cluster is running with fluxcd and flux is working with the same GitLab server. So, I don't assume a general problem with reachability of GitLab and TLS.

**Comment by mowies** [comment]
Did you make sure that your project repo is **fully** empty? also no readme/license etc?

**Comment by doc-olliday** [comment]
Hi,
yes, the repo is absolutely empty.
![grafik](https://user-images.githubusercontent.com/49946087/233704252-3157b70f-f9aa-41e6-874f-485545b587c5.png)

**Comment by mowies** [comment]
Ok good, then that should be fine.
If you have a custom root CA you can check out [this help thread from the Keptn slack](https://keptn.slack.com/archives/CNRCGFU3U/p1681933913114749) where somebody had the same issue.

**Comment by mowies** [comment]
@doc-olliday is this issue solved for you?

**Comment by mowies** [comment]
Pasting the slack thread here since we don't have message retention on our slack workspace.
![Screenshot 2023-06-13 at 08 42 44](https://github.com/keptn/keptn/assets/6901203/bdc85553-234b-456e-9fbe-f43b672fddc4)

**Comment by huguesgr** [comment]
Hi, I'm having the same issue in a very similar setup. Is there a workaround? I'm not using custom certs.

**Comment by RealAnna** [comment]
Hi @huguesgr! Did you have a look at [this page](https://keptn.sh/docs/1.0.x/manage/git_upstream/#gitlab) for the repo setup? 
Is your project repo empty, with no file? 
When creating the project, have you specified both git-user and token? 
Finally, it would be helpful if you could share the corresponding logs of resource service and shipyard controller.

**Comment by odubajDT** [comment]
Since Keptn V1 has reached EOL on December 22nd, 2023, this issue has been closed.
