### ISSUE TITLE
Add replica as a requirement for service helm charts

### ISSUE THREAD

**Issue by bacherfl** [keptn/keptn#967]
Currently, the canary deployment is scaled down to 0 by updating the deployment entity within the cluster. To fully implement the GitOps approach, we need to set a corresponding value in the user-provided values.yaml to 0 and then apply the helm chart. Therefore, we need to be certain that this property exists within a service's helm chart.

**Comment by christian-kreuzberger-dtx** [comment]
This affects the current develop version and was caused by PR #963 and resp. issue #715
