### ISSUE TITLE
Events containing multiple subsequent `.` in their type are ignored without any failure response

### ISSUE THREAD

**Issue by bacherfl** [keptn/keptn#9670]
Currently, it is possible to send CloudEvents to the `/event` API endpoint, containing multiple subsequent `.`s, such as the following:

```
{
  "contenttype": "application/json",
  "data": {
    "evaluation": {
      "timeframe": "5m"
    },
    "project": "sockshop",
    "service": "carts",
    "stage": "dev",
    "temporaryData": {
      "distributor": {
        "subscriptionID": ""
      }
    }
  },
  "source": "bridge",
  "specversion": "1.0",
  "time": "2023-05-10T08:11:34.021630419Z",
  "type": "sh.keptn.event..evaluation.triggered" <- the event type containing multiple dots will be used as the NATS subject  
}
```

 These will be accepted by the endpoint, and a payload containing a KeptnContext will be returned.

However, these events will be silently ignored by Nats JetStream, which means that the nats client of the API service will not receive an error when attempting to send the event, but the event will be dropped by the Nats server, since JetStream is enabled.

A potential place to fix this would be the event validator in the api service (see https://github.com/keptn/keptn/blob/3b37c4181dde63e724092b805fe15cb03510609c/api/handlers/eventvalidation.go#L37), where we could check for these kinds of event types, and return a proper error response in that case

**Comment by prakrit55** [comment]
hey @bacherfl, does that mean more than one dots are ignored by the api, and should notify the error after being encountered ?

**Comment by odubajDT** [comment]
Since Keptn V1 has reached EOL on December 22nd, 2023, this issue has been closed.
