### ISSUE TITLE
adding a definition of  "backwards-incompatible change"

### ISSUE THREAD

**Issue by Nitishupkr** [keptn/keptn#9707]
adding a definition of  "backwards-incompatible change". This would help to clarify what types of changes are allowed in stable releases and what types of changes should be avoided.
![Screenshot 2023-06-24 021300](https://github.com/keptn/keptn/assets/95420063/9498c74c-b1a4-4a38-a66e-23766a9ab5da)
I will work on this issue

**Comment by thisthat** [comment]
done with @9744
