### ISSUE TITLE
Maintainers file

### ISSUE THREAD

**Issue by DavidPHirsch** [keptn/keptn#9713]
Hello everyone,

does it make sense to keep this file? https://github.com/keptn/keptn/blob/master/MAINTAINERS 
all of the information is in peribolos and keeping this up to date is cumbersome

**Comment by DavidPHirsch** [comment]
same for this file https://github.com/keptn/keptn/blob/master/CODEOWNERS

**Comment by mowies** [comment]
I think we can remove the MAINTAINERS file since those are managed in the community repo by peribolos anyways. The CODEOWNERS file is in use and can't be removed. The code owners file defines, who needs to approve changes to specific parts of the code, which is important for PR reviews.

**Comment by odubajDT** [comment]
Since Keptn V1 has reached EOL on December 22nd, 2023, this issue has been closed.
