### ISSUE TITLE
`ADOPTERS.md` file not available

### ISSUE THREAD

**Issue by ShivangShandilya** [keptn/keptn#9715]
While checking out the `README`, I came across `ADOPTERS` section and noticed that the file is missing.
If the removal of file wasn't intentional we can add it back otherwise if it was we'll have to remove the `ADOPTERS` section from the `README` itself.

![image](https://github.com/keptn/keptn/assets/101946115/585f2098-4077-42a3-81c6-1311278fd493)

**Comment by ShivangShandilya** [comment]
I would like to work on this on either case

**Comment by agardnerIT** [comment]
Thanks for the report. I believe it should point here: https://github.com/keptn/community/blob/main/ADOPTERS
