### ISSUE TITLE
recoganize and rephrase the steps a bit to enhance the readability and understanding  for installing and setting up Keptn on a Kubernetes cluster.

### ISSUE THREAD

**Issue by Nitishupkr** [keptn/keptn#9734]
link to page:(https://keptn.sh/docs/explore/)
provided instructions are already quite clear and concise for installing and setting up Keptn on a Kubernetes cluster. However, I'll reorganize and rephrase the steps a bit to enhance the readability and understanding.

**Comment by thisthat** [comment]
Moving the issue under the Keptn repo

**Comment by mowies** [comment]
I will close this since it's about the old Keptn v1 docs
