### ISSUE TITLE
We can add the power of declarative approach in Multi-Stage Delivery and Breaking down of the process.

### ISSUE THREAD

**Issue by Nitishupkr** [keptn/keptn#9736]
https://keptn.sh/docs/concepts/delivery/
"Breaking Down the Process" refers to the detailed explanation or dissection of the various components, actions, or steps involved in a given scenario. I

The power of a declarative approach lies in its ability to focus on describing "what" needs to be achieved, rather than specifying "how" it should be achieved

**Comment by mowies** [comment]
Moving this to keptn/keptn since it's about the docs for Keptn v1

**Comment by Nitishupkr** [comment]
assign it to me

**Comment by mowies** [comment]
Sure, but please don't forget about the other 4 issues you already have assigned. If you don't want to work on those anymore, please tell us on the respective issues.

**Comment by odubajDT** [comment]
Since Keptn V1 has reached EOL on December 22nd, 2023, this issue has been closed.
