### ISSUE TITLE
Replace deprecated `set-output` command with environment file

### ISSUE THREAD

**Issue by jongwooo** [keptn/keptn#9770]
**Is your feature request related to a problem? Please describe.**

In workflow, `set-output` command is deprecated and will be disabled soon. 

**Describe the solution you'd like**

Please upgrade to using Environment Files. For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by mowies** [comment]
Can you please elaborate on your findings? From what I can tell, `set-output` is not used anymore in this repo ([code search](https://github.com/search?q=repo%3Akeptn%2Fkeptn%20set-output&type=code)).
Closing this for now, if you find anything, please just re-open the issue :)
