### ISSUE TITLE
Preparing Sunsetting Keptn

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#9806]
- [ ] Mark Keptn, go-utils, spec, keptn.github.io, get.keptn.sh as read-only
- [x] Migrate old website to v1.keptn.sh

**Comment by thisthat** [comment]
PR to adapt the URLs https://github.com/keptn/keptn.github.io/pull/1660

**Comment by odubajDT** [comment]
Since Keptn V1 has reached EOL on December 22nd, 2023, this issue has been closed.
