### ISSUE TITLE
checkImageAvailability function in send_event_newArtifact.go wrongly checks docker.io

### ISSUE THREAD

**Issue by nnganesha** [keptn/keptn#991]
There seems to be a minor bug in the checkImageAvailability function in the  module send_event_newArtifact.go. I can see that the function checks for 2 conditions: HasPrefix docker.io or if the Image name has exactly 1 forward slash (/) in the image name.

**if strings.HasPrefix(*newArtifact.Image, "docker.io/") || strings.Count(*newArtifact.Image, "/") == 1**

But if I have a local image in my registry, being exposed as myregistry.mydomain.com/myimage:latest, since the image name has exactly 1 slash, the function enters inside the if block and does a http.Get operation on https://index.docker.io/v1/repositories/tag/myimage, which will most likely fail. 

I believe the condition strings.Count(*newArtifact.Image, "/") should not be there or you should have && instead of ||, to force a check on image name with one / in docker.io.

Hope I am clear in my explanation. :)

Regards,
Ganesh.

**Comment by christian-kreuzberger-dtx** [comment]
Hi, thanks for bringing this up. Just for reference for everybody, these are the lines that are being discussed:
https://github.com/keptn/keptn/blob/b36446097980a7a0ca44ab268f025b827acd14a5/cli/cmd/send_event_newArtifact.go#L147-L176

I think you are right, the behaviour is wrong, as right now you can not use any registries other then the ones specified in the code above, and it will always fall back to docker.io.

I believe that 
```go
	if strings.HasPrefix(*newArtifact.Image, "docker.io/") || strings.Count(*newArtifact.Image, "/") == 1 {
```

could be simplified to
```go
	if strings.HasPrefix(*newArtifact.Image, "docker.io/") {
```
as we are checking for `docker.io/` (which already has a `/` in it).

Furthermore, we should probably add the possibility to fetch images from any docker registry (but that might be something for the future; we should however document that docker and quay are supported right now).

Also pinging @agrimmer on this issue for an opinion.

**Comment by christian-kreuzberger-dtx** [comment]
I've noticed that in our [onboarding tutorial](https://keptn.sh/docs/0.5.0/usecases/onboard-carts-service/) the following two lines are listed:

```bash
keptn send event new-artifact --project=sockshop --service=carts-db --image=mongo
```

```bash
keptn send event new-artifact --project=sockshop --service=carts --image=docker.io/keptnexamples/carts --tag=0.9.1
```

When using ``--image=mongo``, the code linked above will log ``Availability of provided image cannot be checked.``, while ``--image=docker.io/keptnexamples`` should work.

This has partically been documented in [this PR](https://github.com/keptn/keptn.github.io/pull/335/files), but we should furthermore clarify within the tutorial that we using ``--image=mongo`` is equal to using ``--image=docker.io/mongo``.

Long term I recommend that we refactor ``checkImageAvailability`` such that we always use `docker.io` as a fallback for checking image availability.

**Comment by nnganesha** [comment]
Thanks Christian. You are right.. But the problem is my image name is mydomain.com/myimage. Since this has one / in it, it goes inside and fails throwing an error image not found.

**Comment by christian-kreuzberger-dtx** [comment]
That's true.

I think @agrimmer is in the process of fixing this, so this should work in the next release.

**Comment by agrimmer** [comment]
Hi all,
@nnganesha you are right! Thank you for making this issue!
We thought that an image always has to be contained in a Docker-organization. Therefore, we added this check `strings.Count(*newArtifact.Image, "/") == 1`. But this is not true.

I fixed it here: https://github.com/keptn/keptn/pull/994

**Comment by nnganesha** [comment]
Thanks a lot Andreas & Christian for updating this and fixing this quickly.... Much appreciated...
