### ISSUE TITLE
Use keptn with argocd 

### ISSUE THREAD

**Issue by tschonnie** [keptn/keptn#992]
**Is your feature request related to a problem? Please describe.**
We currently use argocd but keptn also seems to be very cool! Any experience how to use it together? Can we install keptn in a gitops way instead of „keptn install --platform=kubernetes“

**Describe the solution you'd like**
Get a clear picture if keptn replaces argocd or if we can use both

**Comment by dirkwall** [comment]
Hi @tschonnie,
Keptn is a message-driven control plane for application delivery and automated operations. While we ship with simple services for CD, we plan to integrate with existing tools like argocd or flux/flagger. The integration could either be that those tools can work with Keptn events or having a small integration service that translates Keptn events to API calls on those tools.

You can us both, one for CD, one for orchestrating the entire application delivery flow.

Could you please elaborate on what you mean by "install keptn in a gitops way"?

**Comment by LucMellee** [comment]
> Hi @tschonnie, Keptn is a message-driven control plane for application delivery and automated operations. While we ship with simple services for CD, we plan to integrate with existing tools like argocd or flux/flagger. The integration could either be that those tools can work with Keptn events or having a small integration service that translates Keptn events to API calls on those tools.
> 
> You can us both, one for CD, one for orchestrating the entire application delivery flow.
> 
> Could you please elaborate on what you mean by "install keptn in a gitops way"?

Hi, 
I was wondering if there has been any progress in regards to the integration with Flagger for CD?
