### ISSUE TITLE
Double check specification and implementation of events

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#997]
- [x] Add an example for each event
- [x] Make sure keptn/spec is released before keptn/keptn is released

Open tasks:
- [x] InternalGetSLIEventType
- [x] InternalGetSLIDoneEventType
- [x] Problem event
- [x] Check examples of all events (missing: evaluation-done, get-sli.done)
- [x] Check for hard-coded event type references: `sh.keptn.events.*`
- [x] Check keptn-contrib repos.

**Comment by johannes-b** [comment]
This issue is related to: #940
